### ISSUE TITLE
Does traccar-web support SOS alarms?

### ISSUE THREAD

**Issue by joepr** [vitalidze/traccar-web#1000]
Hello Support

I have been using the latest version of traccar and it shows a pop up when the SOS button on LK106 trackers( H02 protocol ) its pressed. Is there a way to show this messages, audible alert or popup on the new web interface?

**Comment by vitalidze** [comment]
Currently such events are not supported. Also there is no way to see "audible alerts" in the UI, only email and pushbullet are supported at the moment.

**Comment by joepr** [comment]
**Thanks vitalidze**

For your fast replay. I appreciate the work you have done with the traccar web interface. Last few days I was using the default traccar UI with the LK106 trackers and I was happy to receive such SOS notifications via the web interface.

![image](https://cloud.githubusercontent.com/assets/10345032/21425337/f5d8b7fa-c81e-11e6-8ba0-57eb9958fb4c.png)

**Including the audible option**
![image](https://cloud.githubusercontent.com/assets/10345032/21425363/12df249c-c81f-11e6-9597-dcbd5509d2bf.png)

Your web interface provide more tools than the default one. I will like to ask... If I use your web interface and a user press the SOS button will this alert could be received by email?

**Comment by vitalidze** [comment]
> If I use your web interface and a user press the SOS button will this alert could be received by email?

Currently such events are not supported.

**Comment by joepr** [comment]
Thanks! 
I will wait until such features are available. 

Happy holidays!
