### ISSUE TITLE
Upgrading to Traccar Web UI 3.9

### ISSUE THREAD

**Issue by jenellej** [vitalidze/traccar-web#1005]
What would be the complete and proper instructions to upgrade from Traccar Web UI 3.5/3.6 to the latest version while preserving all the users, devices, and tracking data?

Thanks!

**Comment by vitalidze** [comment]
You can stay with 3.5/3.6 as for the "backend" version and just replace the `traccar-web.war` file. This should be enough. 

Otherwise, you will need to:

1) backup your database
2) uninstall previous version of "backend"
3) install new version of "backend"
4) follow [installation instructions](http://traccar.litvak.su/installation.html). You should NOT drop the database because you should already have proper schema.

**Comment by jenellej** [comment]
So basically I just uninstall the old "traccar" back-end, install the new 3.9 "back-end", install the new version of "traccar web ui", leave the database as is and use the same database?

Would the data on the same database be wiped by installing the new verions of the "backend" and "ui" and import the data back or it will work right away after installation?

**Comment by vitalidze** [comment]
> So basically I just uninstall the old "traccar" back-end, install the new 3.9 "back-end", install the new version of "traccar web ui", leave the database as is and use the same database?

Yes, it should work like this. But I highly recommend to take a backup.

> Would the data on the same database be wiped by installing the new verions of the "backend" and "ui" and import the data back or it will work right away after installation?

It should not be wiped. I have done it several times on the demo server. You need to be careful with installation instructions. You need to always disable database schema upgrades on the "backend" side.

**Comment by jenellej** [comment]
Ok thanks. Will make a snapshot first in digitalocean just in case and try your instructions :)

**Comment by shubhamalive** [comment]
Hello, i am trying to update my Traccar web to 3.9, all the installation is completed as given in instructions, but when i start the Traccar service, it stops automatically in fraction of seconds. What can be the possible issue. Error i got in log is :

> 2017-01-05 15:07:59  WARN: Table "GROUPS" not found; SQL statement:
SELECT * FROM groups; [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:239 < DeviceManager:244 < ...)
2017-01-05 15:08:00  WARN: Table "APPLICATION_SETTINGS" not found; SQL statement:
SELECT s.id, s.bingMapsKey AS bingKey,
    us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
    us.zoomLevel AS zoom
    FROM application_settings AS s
    LEFT OUTER JOIN user_settings AS us ON us.id = s.userSettings_id [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:318 < PermissionsManager:88 < ...)


>

**Comment by vitalidze** [comment]
@shubhamalive you haven't followed instructions carefully and because of that you don't have correct database schema.

**Comment by shubhamalive** [comment]
@vitalidze i have again tried and able to set it up and the server is running now, but when i am editing traccar-web.war file to add google api key for google maps, when i start server i am getting "Directory: /"

**Comment by vitalidze** [comment]
You have broken the `traccar-web.war` archive. I guess you are editing it incorrectly.
