### ISSUE TITLE
Can't create tables in MySql

### ISSUE THREAD

**Issue by pmlewisuk** [vitalidze/traccar-web#1006]
HI,

I followed the steps to go from standard Traccar to Traccar UI about 10 times but the tables aren't :-(

If I revert back to my original default.xml and traccar.xml it creates table that was dropped, so I know the use, password etc are correct.

I'm must be doing something really daft, I've even uninstalled Traccar and reinstalled

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
    
    <entry key="web.type">old</entry>
    <entry key="web.application">/opt/traccar/traccar-web.war</entry>
    
    <entry key="mail.smtp.host">smtp.gmail.com</entry>
    <entry key="mail.smtp.port">465</entry>
    <entry key="mail.smtp.ssl.enable">true</entry>
    <entry key="mail.smtp.from">XXXXXXXXXX</entry>
    <entry key="mail.smtp.auth">true</entry>
    <entry key="mail.smtp.username">XXXXXXXXX</entry>
    <entry key="mail.smtp.password">XXXXXXX</entry>
    
   
    <entry key="config.default">./conf/default.xml</entry>
    <entry key="database.driver">com.mysql.jdbc.Driver</entry>
    <entry key="database.url">jdbc:mysql://localhost:3306/traccar3.9ui?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key="database.user">USER</entry>
    <entry key="database.password">PSSWORD</entry>
    <entry key="event.enable">false</entry>
    <entry key="event.overspeedHandler">false</entry>
    <entry key="event.overspeed.notRepeat">true</entry>
    <entry key="event.motionHandler">false</entry>
    <entry key="event.geofenceHandler">false</entry>
    <entry key="event.alertHandler">false</entry>
    <entry key="event.ignitionHandler">false</entry>
    <entry key="event.statusHandler">false</entry>
    <entry key="event.maintenanceHandler">false</entry>
    <entry key="database.insertPosition">
        INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
        VALUES (:deviceId, :protocol, :now, :deviceTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
    </entry>
    <entry key="database.selectLatestPositions">
        SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime,
        valid, latitude, longitude, altitude, speed, course, address, other AS attributes
        FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
    </entry>
    <entry key="database.updateLatestPosition">
        UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;
    </entry>
    <entry key="database.ignoreUnknown">false</entry>
    <entry key="database.selectUsersAll">
        SELECT u.id, u.login AS name, u.password AS hashedPassword, u.salt, u.email, u.readOnly AS readonly,
        u.expirationDate AS expirationTime, u.blocked AS disabled, u.admin,
        us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
        us.zoomLevel AS zoom
        FROM users AS u
        LEFT OUTER JOIN user_settings us ON us.id = u.userSettings_id
    </entry>
    <entry key="database.loginUser">
        SELECT u.id, u.login AS name, u.password AS hashedPassword, u.salt, u.email, u.readOnly AS readonly,
        u.expirationDate AS expirationTime, u.blocked AS disabled, u.admin,
        us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
        us.zoomLevel AS zoom
        FROM users AS u
        LEFT OUTER JOIN user_settings AS us ON us.id = u.userSettings_id
        WHERE u.email = :email
    </entry>
    <entry key="database.selectServers">
        SELECT s.id, s.bingMapsKey AS bingKey,
        us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
        us.zoomLevel AS zoom
        FROM application_settings AS s
        LEFT OUTER JOIN user_settings AS us ON us.id = s.userSettings_id
    </entry>
    <entry key="database.selectDevicePermissions">
        SELECT u.id AS userId, d.id AS deviceId FROM users AS u, devices AS d WHERE u.admin = 1
        UNION
        SELECT ud.users_id AS userId, ud.devices_id AS deviceId FROM users_devices AS ud
        INNER JOIN users AS u ON ud.users_id=u.id
        WHERE u.admin=0 AND u.readOnly=0
    </entry>
</properties>

Wrapper log attached.....

Thanks

Mark

[wrapper.log.20161228.zip](https://github.com/vitalidze/traccar-web/files/675409/wrapper.log.20161228.zip)

**Comment by integreated** [comment]
I had this problem but I had forgotten to comment out to lines before creating the data base. Once I did this it created the database then when I un commented them again it worked fine.

**Comment by integreated** [comment]
This is what I forgot to do 


Old:

<entry key='database.selectGroupPermissions'>
    SELECT userId, groupId FROM user_group
</entry>

New:



Old:

<entry key='database.selectAttributeAliases'>
    SELECT * FROM attribute_aliases
</entry>

New:

**Comment by pmlewisuk** [comment]
HI Integreated,

Thanks for you help, I can confirm I had done that.

Regards

Mark

**Comment by vitalidze** [comment]
According to the `wrapper.log` file contents you have invalid format of your configuration file. Most probably you have made some typo:

````
INFO|10639/0|Service traccar|16-12-28 09:22:22|java.lang.reflect.InvocationTargetException
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at java.lang.reflect.Method.invoke(Method.java:606)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|10639/0|Service traccar|16-12-28 09:22:22|Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 47; columnNumber: 7; The content of elements must consist of well-formed character data or markup.
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at java.util.XMLUtils.load(XMLUtils.java:76)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at java.util.Properties.loadFromXML(Properties.java:868)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at org.traccar.Config.load(Config.java:37)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at org.traccar.Context.init(Context.java:168)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at org.traccar.Main.main(Main.java:35)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	... 6 more
INFO|10639/0|Service traccar|16-12-28 09:22:22|Caused by: org.xml.sax.SAXParseException; lineNumber: 47; columnNumber: 7; The content of elements must consist of well-formed character data or markup.
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2617)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2729)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	at java.util.XMLUtils.load(XMLUtils.java:74)
INFO|10639/0|Service traccar|16-12-28 09:22:22|	... 10 more
INFO|wrapper|Service traccar|16-12-28 09:22:23|waitpid 10639 59136
````

It should be around line 47.

**Comment by pmlewisuk** [comment]
Hi Vitalidze,

you say configuration file i guess thats the traccar.xml?

Regards

Mark

**Comment by vitalidze** [comment]
This could be either `traccar.xml` or `default.xml`. You should check both.

**Comment by pmlewisuk** [comment]
Hi Vitalidze

Sorry about this! I've rebuilt from scratch and just used a h2 database, still not working.

I attach both xml files and log file, hopefully you cab spot the error, I have copied and pasted from your instructions so no typo errors.

Regards

Mark
[Archive.zip](https://github.com/vitalidze/traccar-web/files/676380/Archive.zip)

**Comment by vitalidze** [comment]
I see the issue in `default.xml` file. It looks like your text editor puts some unsupported symbols. I recommend to change comments as follows:

Old (in your current XML file):

````xml
<!—- <entry key='database.changelog'>./schema/changelog-master.xml</entry> —->
````

New:

````xml
<!-- entry key='database.changelog'>./schema/changelog-master.xml</entry -->
````

Same should be done for all other commented out queries:

* database.selectGroupPermissions
* database.selectDevicesAll
* database.selectGroupsAll
* database.selectAttributeAliases

You can use standard notepad from windows or sublime. Then you can also check your XML for validity using some online XML validator.

**Comment by pmlewisuk** [comment]
Thank you so much, I've now downloaded a proper xml editor for my Macbook. 
Never had the issue before, it was caused by a default setting in Textedit called smartdash, must have changed to default during an update.

Thanks also for the online  validator tip :)

Regards

Mark
