### ISSUE TITLE
possibility of choosing language at login 

### ISSUE THREAD

**Issue by bigoss** [vitalidze/traccar-web#101]
Is there any possibility of adding language selection at login without manually writing prefixes in site address?

**Comment by vitalidze** [comment]
It is possible, but I think it should go further and allow user to set up his default language and administrator to set up default language for entire site. I thought about it, but for now the only way is to write prefixes. Anyway, you can always add bookmark to your web browser.

**Comment by bigoss** [comment]
Thank you Vitaly,
In my case traccar will be used as part of company website.
I will make company website at main address for example companyx.com and then add subdomain like tracking.companyx.com for traccar .
Already managed to set nginx proxy to tracers jetty
I think I will have to do some page on main domain before redirecting to traccar subdomain with links +prefixes to different traccar languages or simply give different prefixes in links for each language version of website.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/03/10/improved-localization-and-read-only-users.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
