### ISSUE TITLE
Customizing The Web Report Page

### ISSUE THREAD

**Issue by skylabz0rz** [vitalidze/traccar-web#1010]
Hello,

Is there a way to customize the web report html output? Mostly I am looking at adding some branding. I couldn't seem to locate that in the code.

Thanks!

**Comment by vitalidze** [comment]
You need to update `ReportRenderer` class: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/reports/ReportRenderer.java
