### ISSUE TITLE
Circle change color if GPS present

### ISSUE THREAD

**Issue by mehmetu61** [vitalidze/traccar-web#1011]
Hello, please add the Feature:
Circle change color if GPS present

**Comment by vitalidze** [comment]
What do you mean by "GPS present"?

**Comment by mehmetu61** [comment]
if GPS device on Geofencing Circle present change after x Seconds color from Circle

**Comment by vitalidze** [comment]
For me it sounds like a set of words. I still don't understand.

**Comment by mehmetu61** [comment]
My english is not good.
change automatik color from circle if present gps device

**Comment by vitalidze** [comment]
I think I am starting to understand. Sounds too custom for me, I think notification makes more sense. I doubt it will be implemented.
