### ISSUE TITLE
Animated Playback and auto refresh device position on map

### ISSUE THREAD

**Issue by subhamoysamanta** [vitalidze/traccar-web#1012]
how to add Animated Playback and Add auto refresh device position on map.
If this features added with it , the soft being more usefull.
It may be possible via using xml purch.
Any idea or suggetion?

**Comment by vitalidze** [comment]
> how to add Animated Playback 

I don't have a clear understanding on how to do that. You need to write some code in java.

>  Add auto refresh device position on map.

Not sure what you mean by this.

> It may be possible via using xml purch.

I don't get relation with XML.
