### ISSUE TITLE
Device have coordinates, but not show it on map.

### ISSUE THREAD

**Issue by cgomezconcha** [vitalidze/traccar-web#1013]
Hello vitalize, you have made a great work, thank you for share with us.
I have followed the instruction many time, but i still have the same problem. In the original version I don´t have any problem. Have you some recomendation?:

2017-01-03 00:23:56  WARN: NULL not allowed for column "DEVICEID"; SQL statement:
INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); [23502-193] - JdbcSQLException (... < QueryBuilder:443 < DataManager:293 < DefaultDataHandler:27 < ...)
2017-01-03 00:23:56  INFO: [80C222B7] id: 353067011070077, time: 2017-01-03 00:14:42, lat: 19.30314, lon: -99.10618, speed: 0.0, course: 128.1

**Comment by vitalidze** [comment]
This means you haven't followed installation instructions carefully. You either haven't deleted original traccar database or haven't disabled database schema upgrades in configuration file.
