### ISSUE TITLE
Google dont appear

### ISSUE THREAD

**Issue by djbo1982** [vitalidze/traccar-web#1014]
I just finished a clean installation on windows server. I have followed all the steps in http://traccar.litvak.su/installation.html for version 3.8 - 3.9, I am looking for the option to put google maps as default but I do not find the option in the maps tab, I have been able to change the default options from the preferences menu to google map and I have logged in again but an error appears and I leave it here.

This happens on any external computer to the server, everything seems good on the server, I can not understand it.

Here's what the Google console says

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
E4d @ traccar-0.js:6313
y4d @ traccar-0.js:6006
A4d @ traccar-0.js:5365
QRd @ traccar-0.js:7043
PRd @ traccar-0.js:5960
Nwd @ traccar-0.js:6295
Pwd @ traccar-0.js:7134
Hmb @ traccar-0.js:7124
Zs @ traccar-0.js:5082
mt @ traccar-0.js:7123
(anonymous) @ traccar-0.js:4740
fj @ traccar-0.js:3380
ij @ traccar-0.js:4604
(anonymous) @ traccar-0.js:5814
(index):1 This page includes a password or credit card input in a non-secure context. A warning will be added to the URL bar in Chrome 56 (Jan 2017). For more information, see https://goo.gl/zmWq3m.
util.js:210 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
TA.j @ util.js:210
(anonymous) @ js?v=3:126
(anonymous) @ js?v=3:46
(anonymous) @ js?v=3:43
(anonymous) @ js?v=3:46
(anonymous) @ js?v=3:98
(anonymous) @ js?v=3:43
(anonymous) @ js?v=3:98
(anonymous) @ js?v=3:43
(anonymous) @ js?v=3:98
hc @ js?v=3:45
gc.wb @ js?v=3:98
(anonymous) @ util.js:1
js?v=3:34 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
_.kb @ js?v=3:34
(anonymous) @ common.js:50
(anonymous) @ common.js:203
c @ common.js:44
(anonymous) @ AuthenticationService.Authenticate?1shttp%3A%2F%2F13.66.52.13%3A8082%2F&callback=_xdc_._qxkw9z&toke…:1

**Comment by vitalidze** [comment]
You need to obtain google maps API key and install it on your server. You can also read #754 for information about installation of the key.
