### ISSUE TITLE
Issues getting Bing OS Maps Working "help wanted"

### ISSUE THREAD

**Issue by mjthomson8431** [vitalidze/traccar-web#1016]
Hi,  I've been trying to get a OS Map to show on your demo site before making changes to our server however can't seem to get one up : (   It's probably something I'm doing !  can you help ?

Sorry.

Martin

**Comment by vitalidze** [comment]
From my memory I haven't installed the Bing Maps Key on demo site. That's why it does not work there.

**Comment by mjthomson8431** [comment]
That could explain it,  Is there a demo that has it working or do I need to just man up and install it ?


________________________________

**Comment by vitalidze** [comment]
I don't know anything about such demo server. You can always install your own server and set up bing maps key if needed.

**Comment by mjthomson8431** [comment]
Got it working on my server, thanks
