### ISSUE TITLE
Java Error On Startup

### ISSUE THREAD

**Issue by skylabz0rz** [vitalidze/traccar-web#1018]
At some point during the night, the traccar server stopped working. When I tried to check the status or start the service back up, this is what I get (CentOS):

> Starting traccar ...
> YAJSW: yajsw-beta-12.07
> OS   : Linux/2.6.32-642.11.1.el6.x86_64/amd64
> JVM  : Oracle Corporation/1.8.0_111//opt/jdk1.8.0_111/jre/64
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
> Caused by: java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna1040861497203318593.tmp: /tmp/jna-3506402/jna1040861497203318593.tmp: failed to map segment from shared object: Operation not permitted
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
>         at java.lang.Runtime.load0(Runtime.java:809)
>         at java.lang.System.load(System.java:1086)
>         at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
>         at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
>         at com.sun.jna.Native.<clinit>(Native.java:131)
>         at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
>         at com.sun.jna.PointerType.<init>(PointerType.java:25)
>         at com.sun.jna.ptr.ByReference.<init>(ByReference.java:30)
>         at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:22)
>         at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:18)
>         at org.rzo.yajsw.os.posix.PosixProcess.<init>(PosixProcess.java:67)
>         at org.rzo.yajsw.os.posix.OperatingSystemPosix.setWorkingDir(OperatingSystemPosix.java:27)
>         at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:115)
>         ... 5 more

Any thoughts?

**Comment by vitalidze** [comment]
Looks like you have some issues with your hardware/OS, maybe your disk crashed, or something like this.

**Comment by skylabz0rz** [comment]
Yup. The /tmp drive lost it's exec ability. While it's a slight security risk, I restored that functionality and it's working again.
