### ISSUE TITLE
Subject in all email is: [traccar-web] Notification

### ISSUE THREAD

**Issue by halie412** [vitalidze/traccar-web#1019]
Hello everybody have a good new year.

I have this issue: all notificacions are sent with this subject: [traccar-web] Notification. I change the template subject and body of nofitications but it still send with the subject wrong.

**Comment by akmal1999** [comment]
@halie412 could you provide steps for smtp server installation and configuration please.

**Comment by halie412** [comment]
@akmal1999 i used the settings in traccar web ui to set the smtp, but the smtp server is a third I used amazon ces for send emails to almost 100% of successfull delivery

**Comment by akmal1999** [comment]
did you get around price?

**Comment by akmal1999** [comment]
how much does it cost?

**Comment by halie412** [comment]
is something like USD0,2 per 1000 emails

**Comment by akmal1999** [comment]
thanks

**Comment by vitalidze** [comment]
@halie412 looks like you have configured something wrong. The notification templates are stored along with the notification settings. Every user can customize his notification template. You can read about it here: http://traccar.litvak.su/features/notifications.html It makes sense to pay attention to the `Important notes` chapter.

**Comment by halie412** [comment]
But is rare because the body of template work fine, but the subject no. ¿I would change the default subjetc ([traccar-web] Notification) in some file?

**Comment by vitalidze** [comment]
Well, I don't have any other suggestion but to check your notification settings. Subject can be set for each type of event. I think you have changed it for some of them, but not for all.

> I would change the default subjetc ([traccar-web] Notification) in some file?

In theory you can change it in `Messages.properties` file, but it will changing it in all used languages/locales.

**Comment by halie412** [comment]
I change the main code but like you say, this change to al managers. I don´t know where is the problem because i have 2 servers (one in production and an copy of that in tests) the same configuration, same structure in mysql, same version of traccar, same ui mod, same configs in test server works fine but production server not take the subject from database

**Comment by vitalidze** [comment]
If you have something in database, then it overrides default value. I guess that you have a default subject for some of your notifications in notification settings of some admin/manager. You need to find that user and update his settings.

**Comment by halie412** [comment]
Not friend, no have notification in the database awith the original... i think in this moment this will be fine using the subject in the main file... I wanna ask how i can add an plain value to save in the positions table with each position, explain: i have twoo servers in same database, i wanna have an column to know what server write each position in the common database, i know this can do but not how, you can help me?

If you guide me how to add this value in Position.java I can compile an version to each server

**Comment by vitalidze** [comment]
> Not friend, no have notification in the database awith the original... i think in this moment this will be fine using the subject in the main file... 

Not sure what do you mean. Hope it will work for you.

> I wanna ask how i can add an plain value to save in the positions table with each position, explain: i have twoo servers in same database, i wanna have an column to know what server write each position in the common database, i know this can do but not how, you can help me?
>
> If you guide me how to add this value in Position.java I can compile an version to each server

You should be able to achieve this if you update the 'database.insertPosition' query in `traccar.xml` file. You should be using different configs. So just add necessary column to your database and put the value to the insert query.

**Comment by halie412** [comment]
That works!!! Friend you are an genious... I have other question, how i need send a custom command to gps103 protocol, i try start with **,imei:xxxx,key,value  and not work, with ; in end, without ; too, all in hex, all in text but not was successfull

**Comment by vitalidze** [comment]
You need to look into `tracker-server.log` file to see what is actually being sent to your device.

**Comment by halie412** [comment]
Thanks friend but why you send to gps303 command different of the manual, in manual say: for autotrack **,imei:xxx,102(key) and you send this like **,imei:xxx,C(key) i wanna know how is the key to send custom command for change ip but i can´t find this, my guide is the gps103 protocol document in traccar.org/protocols

**Comment by vitalidze** [comment]
Sorry, I don't understand what do you mean. The protocol implementation is done on the "backend" side, along with the commands sending functionality. Thus, it's better to ask developers of the backend here: https://github.com/tananaev/traccar/issues

**Comment by halie412** [comment]
Perfect thanks.... I have other question please how i can make a call to an historic from the api? i dont find this in the api documentation

**Comment by vitalidze** [comment]
You can find example of such call here: http://traccar.litvak.su/features/rest-api.html (see `getPositions` method).

**Comment by halie412** [comment]
HOOO friend that was ther all but I ask this for you twoo times, sorry... But now I´m testing with getPositions method and this give me an Error 404 if i make the call like your api example but if i delete the body (testing) this give Error 500 so i think the api call is fine but for some reason this no work for me, this is my body: `[{"id":"276","uniqueId":"35971004818XXXX","name":"Kia"},"2017-01-13 00:00:00 GMT","2017-01-13 23:59:59 GMT",false,false]
`

**Comment by vitalidze** [comment]
There must be some error in `wrapper.log` file after you make such call. You need to look there for investigation.

**Comment by halie412** [comment]
Friend the wrapper.log say this when i make a call with api instructions:
`INFO   | jvm 1    | 2017/01/14 17:36:55 | [qtp1931683015-56] INFO / - Key[type=org.traccar.web.server.model.RESTApiServlet, annotation=[none]]: Method not found: getPositions`
And this if i make the call without body content
`INFO   | jvm 1    | 2017/01/14 17:37:46 | [qtp1931683015-56] WARN org.eclipse.jetty.servlet.ServletHandler - /traccar/rest/getPositions
INFO   | jvm 1    | 2017/01/14 17:37:46 | com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
INFO   | jvm 1    | 2017/01/14 17:37:46 |  at [Source: java.io.InputStreamReader@50ef4bc6; line: 1, column: 1]
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2773)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.traccar.web.server.model.RESTApiServlet.doPost(RESTApiServlet.java:62)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2017/01/14 17:37:46 | 	at java.lang.Thread.run(Thread.java:745)`

**Comment by vitalidze** [comment]
I think something is wrong with your call arguments. Have you tried running with cURL as said in examples on official web site? I was writing them for a demo server and I am pretty sure that they are working now.

**Comment by halie412** [comment]
I just see than the https://d.traccar.litvak.su/traccar/rest/getPositions give 404 error (not found) but other methods give 401 (unautorized). is posible than the addres /rest/getPositions are wrong writted?

**Comment by vitalidze** [comment]
Excuse me, but I was wrong. The last parameter is not needed in the call, so in example it should be:

````
curl -v --cookie "JSESSIONID=xxxxxxxxx" -X POST --data "[{\"id\":3,\"uniqueId\":\"123\",\"name\":\"Phone\"},\"2015-01-01 00:00:00 GMT\",\"2015-01-01 23:59:59 GMT\",false]" https://d.traccar.litvak.su/traccar/rest/getPositions
````

Pay attention to the last boolean parameter, there should be only one. This way it works just fine for me on the demo server. I will update documentation now.

**Comment by halie412** [comment]
Your are rigth that was the mistake, now is working fine.... very thanks for your time and your greate work

**Comment by halie412** [comment]
Is possible to add filters in the api call or only work with the date and time?

**Comment by vitalidze** [comment]
You can set up filters in UI and then enable them by specifying last parameter as `true` instead of `false`.

**Comment by halie412** [comment]
Hello dear Friend.... you can guide me to calculate formattedIdleSinceTime from api? i don´t know how to calculate this like in the web ui show and is very usefull

**Comment by vitalidze** [comment]
Actually it is already included in response to `getLatestPositions`, however, in API this field is skipped. You can just remove `@JsonIgnore` annotation from `idleSince` field in `Position` class and it will be included in the query results. There is one more useful field called `idleStatus`, which is skipped too and can be enabled in similar way.

Idle calculation is a bit complicated and happens in [MovementDetector](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/MovementDetector.java) class.

**Comment by halie412** [comment]
Very thanks! i will try this right now!... Friend i have an other question one part of the code is making me crazzy because if an device by mistake send an time in future future the web ui will show this position every time in the web ui and api calls, i check in the database and the mistake position still like latestposition in the device row (even if this position was sended many days in the past). I have this in database: An send in (2017-01-23 08:00:49 Servertime) And (2022-11-20 08:00:47 time) and here become the trouble: the server take this position all time like newest position, (in web ui and api calls) this same device send lots of positions in rigth way but the server not upgrade the lastPosition_id in device row... and i wanna ask to you if i can change the time (sended by devices for the serverTime) than the server show in same position.java file because this have ocurred in some devices and only solution finded now is delete and add the device (i think this worked because i take other device id)

**Comment by halie412** [comment]
I try this: Set null on devices.lastUpdate, Set null on devices.status and Set null on devices.latestposition and delete all events and all positions of the trouble device but now the system still saving new positions but devices.latestposition still in null //// other try: i fix the bad date manually but not changig the devices.latestPosition_id //// i try too only change the devices.latestPosition_id manually and the sistem not upgrathe this again, the system always still take this position like an newest even when the device have newest positions... I don´t know why system not upgrade latestposition in right way

**Comment by vitalidze** [comment]
Traccar currently always checks that new position time is greater than current latest position time. If it satisfies, then latest position is updated. That's why you stick with position in future.

The correct way to handle your case is to set up filters. You can read about them here: https://www.traccar.org/configuration-file/ For example there is a `filter.future` flag in version 3.9, however, it is not officially documented and thus may change in future versions.
