### ISSUE TITLE
"TraccarM" vs "Traccar Manager"

### ISSUE THREAD

**Issue by Fleetracking** [vitalidze/traccar-web#1021]
Hi @vitalidze 

I ask please if "TraccarM" android application is supported by your GUI project?
If else do you plan to develop an application similar to "Traccar Manager" with all GUI features?

Best regards

**Comment by vitalidze** [comment]
> I ask please if "TraccarM" android application is supported by your GUI project?

AFAIK it is compatible. However, I haven't tried it myself.

> If else do you plan to develop an application similar to "Traccar Manager" with all GUI features?

I don't plan to develop such application.

**Comment by Fleetracking** [comment]
Hi
I didn't find "AFAIK" app at google play market.

Do you plan to enhance GUI mobile version to support all available features?

BR

**Comment by vitalidze** [comment]
> I didn't find "AFAIK" app at google play market.

AFAIK is an acronym: http://www.urbandictionary.com/define.php?term=afaik

> Do you plan to enhance GUI mobile version to support all available features?

I think it will never support all features available in the desktop version. From my point of view it is not needed. Mobile version should be used as a "quick view" of the current situation.

**Comment by Fleetracking** [comment]
Ah OK :)

I think that mobile version is the most used by a lot of users instead of
desktop version.
So it will be a good evolution if mobile version support all basic
functions (historique data, cut-off commands...).

I think that the new version of Traccar Manager supports all features
available for desktop version.

BR

Le 9 janv. 2017 19:03, "Vitaly Litvak" <notifications@github.com> a écrit :

I didn't find "AFAIK" app at google play market.

AFAIK is an acronym: http://www.urbandictionary.com/define.php?term=afaik

Do you plan to enhance GUI mobile version to support all available features?

I think it will never support all features available in the desktop
version. From my point of view it is not needed. Mobile version should be
used as a "quick view" of the current situation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vitalidze/traccar-web/issues/1021#issuecomment-271375855>,
or mute the thread

**Comment by vitalidze** [comment]
> I think that mobile version is the most used by a lot of users instead of desktop version.

I don't think so.

> So it will be a good evolution if mobile version support all basic functions (historique data, cut-off commands...).

That is planned (to add more basic functions).

> I think that the new version of Traccar Manager supports all features available for desktop version.

Yes, because it is a web view of the desktop version, which tries to adapt to the mobile browser screen.

**Comment by Fleetracking** [comment]
Thank for your efforts.
And Good luck
