### ISSUE TITLE
Latitude and longitude settings (ITALIAN bug ?)

### ISSUE THREAD

**Issue by lcatoni72** [vitalidze/traccar-web#1025]
Below my user activity:
-login with ITALIAN language
-'Preferenze'->'Stato mappa di default'
-I try to update my 12.8135 longitude value to 12.8136 value  and I run save,  the decimal point is deleted from input field and the Integer value 128135 is wrongly stored on db.
-I open user settings popup again, now I can not change the integer value by inserting the point, but only comma is permitted.
-Now I can successfully save the new Double value (typing comma).

Thank you

**Comment by vitalidze** [comment]
You should use comma as a decimal separator for double values.
