### ISSUE TITLE
Server shutting down

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#1026]
> 2017-01-13 12:27:06  WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms. - SQLTransientConnectionException (... < QueryBuilder:56 < *:132 < DataManager:201 < DeviceManager:79 < ...)
> 2017-01-13 12:27:06  WARN: Unknown device - 38 (191.134.185.63)
> 2017-01-13 12:27:06 DEBUG: [6A82A138: 5001 < 191.134.185.63] HEX: 696d65693a3335393731303034383836323831382c747261636b65722c3137303131333233323633322c2c4c2c2c2c613230642c2c326264372c2c2c3b
> 2017-01-13 12:27:36  WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms. - SQLTransientConnectionException (... < QueryBuilder:56 < *:132 < DataManager:218 < DeviceManager:177 < ...)
> 2017-01-13 12:28:06  WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms. - SQLTransientConnectionException (... < QueryBuilder:56 < *:137 < DataManager:289 < DefaultDataHandler:27 < ...)
> 2017-01-13 12:28:06  INFO: [6A82A138] id: 38, time: 2017-01-12 08:44:01, lat: -3.72706, lon: -38.51960, speed: 1.0, course: 94.8
> 2017-01-13 12:28:06 DEBUG: [6A82A138: 5001 < 191.134.185.63] HEX: 3335393731303034383836323831383b

My traccar server turn off when show this message..

Someone knows?

**Comment by vitalidze** [comment]
This means traccar has lost connection to your database server.

**Comment by leontino** [comment]
and this 

> 
2017-01-14 09:16:59  WARN: The table 'positions' is full - SQLException (... < QueryBuilder:443 < DataManager:292 < DefaultDataHandler:27 < ...)

**Comment by vitalidze** [comment]
This means you have ran out of disk space on the drive hosting your MySQL data.
