### ISSUE TITLE
CSV Report

### ISSUE THREAD

**Issue by integreated** [vitalidze/traccar-web#1027]
Hi all
Can anyone tell me where I can edit what is shown in this report please?

**Comment by vitalidze** [comment]
The code is in `ExportServlet` class.

**Comment by integreated** [comment]
Thanks for that do you know a free program to edit .class files?

**Comment by vitalidze** [comment]
You should not edit .class files. Instead of this you need to update .java file and compile project by following official instructions: http://traccar.litvak.su/building.html To edit .java file you can use any text editor, like notepad.
