### ISSUE TITLE
eclipse problem

### ISSUE THREAD

**Issue by bigoss** [vitalidze/traccar-web#103]
I have a problem with eclipse when imported to eclipse as existing maven project gwt compile shows:
is not GWT project

**Comment by vitalidze** [comment]
I haven't tried it in eclipse for a year. I am using IntellIJ Idea. Which version of Eclipse are you using?

**Comment by bigoss** [comment]
my eclipse is luna required plugins installed , I will try IntellIJ Idea
community version then

Thank you

**Comment by vitalidze** [comment]
Community version will not work. You need Ultimate.

**Comment by bigoss** [comment]
got it will send you private msgsoon
Thanks

**Comment by vitalidze** [comment]
Should work now with [updated instructions](http://traccar.litvak.su/ide/eclipse.html)
