### ISSUE TITLE
How to connect chinese gps watch ?

### ISSUE THREAD

**Issue by elvudinbasha** [vitalidze/traccar-web#1030]
Im new in Traccar, and i find your project i download i add to my server but now i wanna Track a one chinese smartwatch, model of watch is **g36 gps kids watch**, can you explain if it possible to track with your project and how to connect this watch that project. 

Sincerely

**Comment by vitalidze** [comment]
I recommend to start from reading official guides:

* https://www.traccar.org/quick-start/
* https://www.traccar.org/identify-protocol/

**Comment by elvudinbasha** [comment]
Thanks, i will read, but i wanna know if this type of watch is possible to use with your project, and which port i will use for this g36 gps kids watch,

**Comment by vitalidze** [comment]
You need to read article about protocol identification. I haven't used such
watch with the system.

пт, 20 янв. 2017 г. в 17:47, Elvudin Basha <notifications@github.com>:
