### ISSUE TITLE
Last known postion is not reliable

### ISSUE THREAD

**Issue by Sargunan** [vitalidze/traccar-web#1032]
![pb1](https://cloud.githubusercontent.com/assets/5010960/22175947/af9afb9a-dff7-11e6-922c-2e1143b8a732.png)
The follow and trace of the vehicle position on move is working fine until the vehicle enters Geo-fence. The  moment  vehicle enters geo-fence the last known position keeps moving back and forth initial location - where the device first came online. Has anyone faced this issue ? Could you please help me solve this issue.  Thanks in advance.

**Comment by vitalidze** [comment]
This sounds like an issue with your device. You need to look into the data, which it sends and then maybe contact manufacturer for explanations. I don't see any relation with geo-fence.

**Comment by Sargunan** [comment]
Thanks for your response Vitali. This issue seems to related Invalid Location Jumps for vehicles #1720 and there seems to be a resolution by setting devicetime. Closing this issue.
