### ISSUE TITLE
Api webinterface example

### ISSUE THREAD

**Issue by tjeerd13** [vitalidze/traccar-web#1033]
I use the system for a first aid foundation. Mainly used in big events. Like 200km MTB trails, urban runs, survival runs. Because it is always difficult to locate participants, we want to add them to Traccar with the mobile app. But there are many. (300-1000).

Is there a possibility through the Api (Or has anyone an example) to import a lot of devices at one time.

It would be nice to use the start number eg 1-500. It would be great to use CSV, Device ID Name and separate group and user.

If anyone has an example of a web page with CURL / JSON it would be super!

**Comment by vitalidze** [comment]
You can start from reading [official docs about API](http://traccar.litvak.su/features/rest-api.html)

Then you may find #794 and #796 useful. There are examples on how to add devices through API.

**Comment by tjeerd13** [comment]
I.m getting somewhere,
If i use
`curl -v -X POST --data "[\"user\",\"pass\"]" http://192.168.10.2:1234/traccar/rest/login`
and
`curl -v --cookie "JSESSIONID=1js21517q0xyp9afety1bocx0" -X POST --data "[{\"uniqueId\":\"112223\",\"name\":\"Added from REST\",\"description\":\"5\",\"maintenances\":[],\"sensors\":[]}]" http://192.168.10.2:1234/traccar/rest/addDevice
`

I can add a user,  How can i Add a device to a Group?  (5)
I'm trying to use PHP to add but its not working. I have no idea how to add the login method. I treid something like this:

`$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://trace.spijkerit.nl:1234/traccar/rest/addDevice");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "[{\"uniqueId\":\"112223\",\"name\":\"Added from REST\",\"maintenances\":[],\"sensors\":[]}]");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
`

It's not working . The next step would be using an csv like this:

`uniqueId;name;description
1;Henk Peters;0612345678
2;Joost;0612456879
3;Peter;0645648975
4;Henk ;0645854523
5;klaas;0685479624
6;vicotr;0458854548
7;agnes;0546455645
8;wilma;0548789798
`
Or an aray like this?
`
[
 {
   "uniqueId": 1,
   "name": "Henk Peters",
   "description": 612345678
 },
 {
   "uniqueId": 2,
   "name": "Joost",
   "description": 612456879
 },
 {
   "uniqueId": 3,
   "name": "Peter",
   "description": 645648975
 },
 {
   "uniqueId": 4,
   "name": "Henk ",
   "description": 645854523
 },
 {
   "uniqueId": 5,
   "name": "klaas",
   "description": 685479624
 },
 {
   "uniqueId": 6,
   "name": "vicotr",
   "description": 458854548
 },
 {
   "uniqueId": 7,
   "name": "agnes",
   "description": 546455645
 },
 {
   "uniqueId": 8,
   "name": "wilma",
   "description": 548789798
 }
]

`
Some have an working example? I'm al little bit stuck and i have to add al lot op people.

THANKS !

**Comment by vitalidze** [comment]
To add device to a group, you need to specify it in the device profile as an object with at lest 'id' field filled in. The property in device is named `group`.

**Comment by joepr** [comment]
Tjeerd13

I had a similar scenario like yours. Currently I'm using a combined solution of GPS Trackers ande cell App . PM me I think I could help you.

Regards

**Comment by tjeerd13** [comment]
Hello @joepr  can you please contact me   ?  I can't find a way to PM you?

Thanks!
