### ISSUE TITLE
Report Options.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1036]
Hi,
First of all great project and great work.
question:

When creating multiple reports. Could we have options to include or not the distance speed and also have an option of which type of map we would like to see the tracks.  for instance, tracks on google satellite map.
![capture](https://cloud.githubusercontent.com/assets/22064319/22307711/2349f150-e312-11e6-8897-3a2f2fa3aa81.PNG)

**Comment by vitalidze** [comment]
1) Hiding all fields looks weird for me. You can easily show desired positions by simply calling an API method and drawing all track data with code in javascript. There are tons of examples on how to do it.

2) Changing of map type in reports is planned. It was requested several times and makes sense. I think there can be an option right in report settings.

**Comment by akmal1999** [comment]
HI Vitali,

Many thanks, is it possible to connect power BI with its database and create the above report. I am sorry however I am not a programmer to change lots of codes.

many thanks again.

**Comment by vitalidze** [comment]
I have no idea. Never heard of power BI.

**Comment by akmal1999** [comment]
Ok not a problem. thanks.
