### ISSUE TITLE
Auto add new devices

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#1038]
Hello everyone,

I wanna know, if it’s possible automate the creation of new device. When show “unknown device” on ‘tracker-server.log’ file, auto add on device list, on specific group, with custom name.

Thank you!

**Comment by vitalidze** [comment]
It makes much more sense to post same question on "backend" [issue tracker](https://github.com/tananaev/traccar/issues) or [forums](https://www.traccar.org/forums/).

**Comment by leontino** [comment]
But in backend it's possible? Because the structure is different from them

**Comment by vitalidze** [comment]
It is possible to update queries used for backend to create devices for the database schema used in this project.

**Comment by leontino** [comment]
I will try and post here. Thank you!

**Comment by leontino** [comment]
> 2017-01-29 00:02:25  INFO: Version: 3.9-SNAPSHOT
> 2017-01-29 00:02:26  INFO: Query not provided: database.selectGroupsAll
> 2017-01-29 00:02:27  INFO: Query not provided: database.selectGroupsAll
> 2017-01-29 00:02:27  WARN: Table 'testeocean.user_group' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:192 < PermissionsManager:106 < ...)
> 2017-01-29 00:02:29  INFO: Query not provided: database.selectAttributeAliases
> 2017-01-29 00:02:29  INFO: Starting server...

I put, but show it.

And when show new "unknown device", show this message:

> 2017-01-29 00:08:35  WARN: Unknown column 'groupId' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:443 < DataManager:203 < DeviceManager:164 < ...)
> 2017-01-29 00:08:35 DEBUG: [B8649229: 5055 > 191.33.116.246] HEX: 485454502f312e31203430302042616420526571756573740d0a436f6e74656e742d4c656e6774683a20300d0a0d0a

I added:

```
<entry key='database.ignoreUnknown'>false</entry>
<entry key='database.registerUnknown'>true</entry>
<entry key='database.registerUnknown.defaultGroup_id'>1</entry>
<entry key='database.registerUnknown.defaultIcon_id'>1</entry>
```

and this 

> 2017-01-29 00:29:23  WARN: No value specified for parameter 3 - SQLException (... < QueryBuilder:443 < DataManager:203 < DeviceManager:164 < ...)
> 2017-01-29 00:29:23 DEBUG: [F944DAF4: 5055 > 191.33.116.246] HEX: 485454502f312e31203430302042616420526571756573740d0a436f6e74656e742d4c656e6774683a20300d0a0d0a

**Comment by vitalidze** [comment]
You need to make some changes in queries related with groups, devices and relation device/group, user/group, user/device.

**Comment by leontino** [comment]
But I make just yours adaptations. And show this error when turn on the traccar.

> 2017-01-29 08:44:25  INFO: Version: 3.9-SNAPSHOT
> 2017-01-29 08:44:26  WARN: Unknown column 'device_id' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:305 < DeviceManager:65 < ...)
> 2017-01-29 08:44:26  WARN: Table 'traccar.application_settings' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:319 < PermissionsManager:88 < ...)
> 2017-01-29 08:44:26  INFO: Query not provided: database.selectGroupPermissions
> 2017-01-29 08:44:26  WARN: Table 'traccar.users_devices' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:187 < PermissionsManager:117 < ...)
> 2017-01-29 08:44:27  INFO: Query not provided: database.selectAttributeAliases
> 2017-01-29 08:44:27  INFO: Starting server...

**Comment by vitalidze** [comment]
This means you haven't followed installation instructions carefully and it did not create necessary tables. Or maybe you have database structure from backend.
