### ISSUE TITLE
Rest API Ajax Calls

### ISSUE THREAD

**Issue by garaekz** [vitalidze/traccar-web#1041]
I saw that the origican Traccar API is not working and I tried to use your implementation of the API but I'm using Javascript, AJAX request doesnt give me the cookie response, It gives me the cookie on a separate XHR response, I cannot use cURL because is a full HTML AngularJS app, is there a way to retake the original API or to properly getting the session cookie with AJAX?

**Comment by vitalidze** [comment]
Mobile version of the web UI is written in javascript/html (not angularJS, but anyway), and it is working just fine with session cookies. I think you are doing something wrong.

You can find current implementation here: https://github.com/vitalidze/traccar-web/tree/dev/src/main/webapp/m

**Comment by garaekz** [comment]
It affects that I'm consuming the API from my app outside the server?

**Comment by vitalidze** [comment]
You can use `JSESSIONID` cookie. It should be easy to access it from AngularJS, or any other javascript framework.

**Comment by garaekz** [comment]
I found that the issue is with origin header from the response given by the server, with CORS the browser first sends an OPTIONS request and then the POST request that I asked for, the response gives me the headers from the OPTIONS request but not the one from the POST request, any idea?

**Comment by vitalidze** [comment]
Well, I don't think I fully understood what are you talking about. Anyway, Traccar Web UI Mod does not do anything with CORS, i.e. it does not send any `Access-Control-Allow-Origin: *` header.

**Comment by garaekz** [comment]
Thanks, you can close this

**Comment by garaekz** [comment]
Oh, wait, maybe that's the issue? Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by garaekz** [comment]
Is there a way I can add the needed headers?

**Comment by vitalidze** [comment]
I can see two ways:

1) Change source code so it will add necessary headers. For example [RESTApiServlet](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/RESTApiServlet.java) can be updated.

2) Run app behind a reverse proxy. Then you can define some rule for the reverse proxy to add necessary headers.

**Comment by garaekz** [comment]
Ok, thanks
