### ISSUE TITLE
How total distance in archive is calculated

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#1042]
Hi @vitalidze 

i've been trying to calculate the total distance of a movement directly from the database in the web app i'm working on, some time it's correct using totalDistance or distance but when device goes offline for a while these two get messed up and some how traccar-web UI manages to remain correct, i'd appreciate any advice from you.
the two different situation screenshot are attached below.

![total_distance](https://cloud.githubusercontent.com/assets/11395006/22471836/dc292dce-e7d3-11e6-999c-7bd5230bb773.PNG)
![total_distance_exc](https://cloud.githubusercontent.com/assets/11395006/22471971/7560cf6a-e7d4-11e6-9b1f-460acc202eb6.PNG)

**Comment by vitalidze** [comment]
It does not do anything special. Just sums up all values from the "Distance" column:

````java
    void updateTotals(List<Position> positions) {
        double totalDistance = 0;
        double averageSpeed = 0;
        for (int i = 0; i < positions.size(); i++) {
            Position position = positions.get(i);
            totalDistance += position.getDistance();
            averageSpeed += position.getSpeed();
        }
        averageSpeed = averageSpeed / positions.size();
        this.totalDistance.setLabel(ApplicationContext.getInstance().getFormatterUtil().getDistanceFormat().format(totalDistance));
        this.averageSpeed.setLabel(ApplicationContext.getInstance().getFormatterUtil().getSpeedFormat().format(averageSpeed));
    }
````

Maybe you have some filter applied in the "archive", then total distance will be calculated on the filtered positions. However, when you do calculations by yourself, you don't use any filter. My other guess is that you are calculating distance between positions incorrectly.

**Comment by gpproton** [comment]
Hi @vitalidze 
i've been trying out distance in the other column on the database but it still sometimes different when device goes offline for a while, exactly like the picture i posted up and somehow distance archive panel column is different from other column in database.

**Comment by vitalidze** [comment]
Most probably distance in `other` column is calculated by backend part, which takes into account only filters defined in configuration file. Another case is that your device sends distance somehow and traccar simply puts it into `other` column. You need to check both cases, and for the first one tune up filters somehow.

**Comment by gpproton** [comment]
You mean like this issue https://github.com/tananaev/traccar/issues/2771 in the backend, but somehow traccar-web UI mod mostly get the distance acurately in both the reports and archive ui panel. And apart from backend distance column what other option is possible.

**Comment by vitalidze** [comment]
Again, distance in Traccar Web UI Mod is calculated on-the-fly with all filters applied from the settings in UI and positions are sorted by the time. Distance calculated by the backend is stored in the database, and yes as said in https://github.com/tananaev/traccar/issues/2771 order of positions received from device matters. 

You can do the calculation manually in your web app.
