### ISSUE TITLE
GEOLOCATE-ME don't work

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#1052]
When I click on @ in mobile version, nothing happends

**Comment by vitalidze** [comment]
Which OS are you using? If you are using iPhone, then for geolocation to work your site must be served via SSL (i.e. HTTPS).

**Comment by leontino** [comment]
I used android, and test with google chrome too.

**Comment by vitalidze** [comment]
Please check whether it works for you on the demo site https://d.traccar.litvak.su I have checked that right now and it works just fine on my iPhone and my desktop chrome. Please note that site is served via HTTPS.
