### ISSUE TITLE
Modify user permissions

### ISSUE THREAD

**Issue by fmelin** [vitalidze/traccar-web#1053]
Dear, very good day together with greetings, I would like you to help me.

I need the read-only users can create geofences.

Beforehand thank you very much.

**Comment by vitalidze** [comment]
The only way to achieve this is to modify code. In particular the `@RequireWrite` annotation must be removed from all methods related with geo-fence management in `DataServiceImpl` class.

**Comment by fmelin** [comment]
Estimated, did not work.

This is the code, please help.
Beforehand thank you very much.
And excuse my English


[DataServiceImpl.zip](https://github.com/vitalidze/traccar-web/files/759530/DataServiceImpl.zip)

**Comment by vitalidze** [comment]
Looks like you did changes correctly. Then you need to update UI part to show buttons. Some changes must be done here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/DeviceView.java#L897 You need to check other places in that class as well.

**Comment by fmelin** [comment]
What should I do in that class?
thank you very much.

**Comment by vitalidze** [comment]
You need to update code so it will not hide buttons for geo-fences when user is read only.

**Comment by fmelin** [comment]
Sorry to bother you, but I do not know there is a change, you could give me an example.

Greetings and thank you very much for everything.

**Comment by vitalidze** [comment]
I already gave you all necessary info including line numbers. You need to write some code yourself. Here is another line, which hides buttons: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/DeviceView.java#L767
