### ISSUE TITLE
Installatuon commands

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1056]
Can a Ver 3.9 installation instraction be uploaded. 

Thanks

**Comment by vitalidze** [comment]
They are present for a long time: http://traccar.litvak.su/installation.html

**Comment by degaray** [comment]
Can you make them more "goof-proof". I mean line-by-line. For instance, if I download the .war file, how come can I change a config file.

**Comment by vitalidze** [comment]
You mean I should write that you must be able to edit text file in notepad or what?

**Comment by degaray** [comment]
Ok, it would be much easier for newbies, like I, to have a step by step installation. For instance:

1. Download the file.
`curl http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war --output /opt/traccar`

2. Stop Traccar service. In case you are running Traccar already, you need to stop the service. Else if you are installing Traccar for the first time, jump to 3.
`Some command needed, I have no idea which one`

**Comment by vitalidze** [comment]
It will require separating instructions for multiple platforms, which will make things more complicated. For example there are no `curl` on windows OS. Also even in different linux based OS there will be different preferred text editors. I prefer `vim`, someone like `nano`, someone else `emacs` or `gedit`. If you want, you can always submit a pull request for the instructions or any documentation update. Everything is in the `gh-pages` branch of this github repository: https://github.com/vitalidze/traccar-web/tree/gh-pages

**Comment by degaray** [comment]
Yes. I understand that. But it will be much easier to have them. I am starting to understand how to install it so I cannot write them for now. I do have some questions though. For instance how do I move the .war file to /opt/traccar, is it just a simple move? or is it a compressed file I need to uncompress?

**Comment by vitalidze** [comment]
>  For instance how do I move the .war file to /opt/traccar, is it just a simple move? or is it a compressed file I need to uncompress?

Just a simple move, there is no word about "uncompressing" in instructions, actually there is no word "move" either. It clearly says:

> 3) Put the downloaded traccar-web.war in Traccar installation folder (/opt/traccar or c:\Program Files\Traccar). I recommend to do a backup of existing traccar-web.war just in case.

From my point of view there are no double-meanings here. It's just about putting downloaded file into specific folder.

**Comment by degaray** [comment]
Ok, well, I do not have the folder `/opt/traccar` in my system. For obvious reasons!!!! I am installing it for the first time. So I do not understand where am I going to get the configuration file from. Nor I have traccar running so I will not stop it for that sake.

**Comment by vitalidze** [comment]
You need to install basic version of traccar first. See the documentation here: https://www.traccar.org/documentation/

**Comment by degaray** [comment]
Ok, thank you. Now it makes sense. By the way that is not written in your installation instructions.

**Comment by vitalidze** [comment]
This is written in "About" page. The whole project is a web interface for traccar server. This is not a separate standalone product. I guess you should know what are you going to install before installing it.

**Comment by degaray** [comment]
Look at this:

> This is the modified version of original project (also called “fork”) with many features added.

Isn't that confusing? You are actually saying this is "a modified version of the original project".

**Comment by vitalidze** [comment]
The main descriptive sentence is the first one:

> Web interface for traccar server.

The "original project" link will lead you to the `traccar-web` project, which is actually a web UI for the traccar. Maybe it is confusing, but to be honest you are the first one, who complain about these, please do not take offense.
