### ISSUE TITLE
Map matching

### ISSUE THREAD

**Issue by dudek-marcin** [vitalidze/traccar-web#106]
I was looking for solution that lets to magnet points to the road, I've found this open source solution:
https://github.com/graphhopper/map-matching
What do you think about implementing this in traccar ?

**Comment by vitalidze** [comment]
From my understanding currently it requires importing/converting of OpenStreetMap `PBF` data of area where you want this map-matching to work. But they mentioned about web service. I think the most convenient way to integrate it with traccar is to use web service. Anyway, for now I don't have such feature in plans.

**Comment by vitalidze** [comment]
Also for now you can try using it without any modifications to traccar with export/import GPX function. That `graphhoper` utility consumes GPX and produces GPX with points sticked to the road.

**Comment by dudek-marcin** [comment]
Ok, thanks. I know that I can use it with GPX, but just wanted to let you know, that something like that exist, if you would like to implement magneting. Useful for example for counting real kilometres.

**Comment by vitalidze** [comment]
Thank you for information. I appreciate that.
