### ISSUE TITLE
Issue when installing Traccar (WEB UI) server with MS SQL server

### ISSUE THREAD

**Issue by peterghobrial** [vitalidze/traccar-web#1063]
I get error log when install traccar server with your UI and connecting it to MS SQL Server, attached the configuration files and log file containing error.

However I didn't any errors when connecting to MS-SQL without the UI installation.
Also I tried with Traccar 3.6, 3.9 and 3.10.

[wrapperlog.txt](https://github.com/vitalidze/traccar-web/files/777189/wrapperlog.txt)
[default.txt](https://github.com/vitalidze/traccar-web/files/777203/default.txt)
[traccar.txt](https://github.com/vitalidze/traccar-web/files/777204/traccar.txt)

**Comment by peterghobrial** [comment]
i solved it by editing persistence.xml file as in #669, thanks

**Comment by vitalidze** [comment]
Thanks for the info.
