### ISSUE TITLE
Marker doesn't update

### ISSUE THREAD

**Issue by garaekz** [vitalidze/traccar-web#1065]
Hi, I was working ok with Traccar-web but suddenly one of the devices stoped to update the marker location, in the log I see the correct coordinates but in the map the marker doesn't update and it gives me minus seconds ago ex. -50s ago and the date it tells me a wrong date
![image](https://cloud.githubusercontent.com/assets/14919842/22990635/b6309aca-f36e-11e6-9b42-ae4251aa986f.png)

Edit. It is happening to me kind of frequently and the only solution I've tried that works is to delete the device and register it again but then it happens again with other device, It only happened one device at the time.

**Comment by vitalidze** [comment]
Your device reports date in future. Traccar backend always tries to preserve positions with greater time value, which means it will not update latest position when time is below 2023. You should figure out why your device is sending such data. It's worth to contact manufacturer. Also there is a way to configure filtering by traccar backend, see this article https://www.traccar.org/configuration-file/ (properties starting from `filter.`).

**Comment by garaekz** [comment]
But in log device sends the correct date, also in DB is stored the correct date.

**Comment by vitalidze** [comment]
I will try explaining again. Once your device sent such "faulty" position and it was stored as the "latest" position of your device, then it will never be updated anymore until your device sends position with date and time later than of that "faulty" position. 

In your example latest position has 2023 year. If all newly received positions have year 2017 (which should be correct), they cannot overwrite latest position from 2017. However, they will be stored in database. It's all about "latest" position, which is not updated in this case.

**Comment by garaekz** [comment]
Ok, ok, thank's i'll keep track of any faulty position.
