### ISSUE TITLE
Adding google map api key to mobile interface index.html

### ISSUE THREAD

**Issue by peterghobrial** [vitalidze/traccar-web#1066]
after adding google map api key to index.html in traccar-web.war /m/index.html the mobile interface doesn't logme in?
Attached the index.html after editing
[index.txt](https://github.com/vitalidze/traccar-web/files/779365/index.txt)

**Comment by vitalidze** [comment]
You have added it incorrectly, missed the `src` attribute.

Your version:

````html
<script type="text/javascript" "//maps.googleapis.com/maps/api/js?key=I_ENTERED_THE_KEY_HERE"></script>
````

Must be:

````html
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=I_ENTERED_THE_KEY_HERE"></script>
````
