### ISSUE TITLE
Trouble: "Username is already taken"

### ISSUE THREAD

**Issue by morpheus1000** [vitalidze/traccar-web#1067]
Good morning

I have been working on the mount this project since a few weeks ago, and I have just discovered the litvak project,

I have performed the entire procedure as indicated on its website: http://traccar.litvak.su/installation.html

However I have not managed to make the devices visible on the map, I also have problems creating new users since the following message always appears:
"Username is already taken"

Where could I find the solution to this problem?

Thanks in advance.

**Comment by vitalidze** [comment]
You need to look into log file for error messages. Most probably you haven't followed instructions precisely. I suppose you haven't deleted old database or haven't disabled database schema upgrades.

**Comment by morpheus1000** [comment]
Thank you very much for your comment,

To solve the visualization problem, I had to install an old version of traccar (version 3.6). It was the way I could visualize my units. Thank you very much for everything.
