### ISSUE TITLE
Geocoder problem

### ISSUE THREAD

**Issue by dudek-marcin** [vitalidze/traccar-web#107]
I know it's been saying many times, but I can not resolve the problem. 
I set in config:

```
<!-- Geocoder options -->
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>
```

So after server restart all new data should contain address, but nothing like that happens, I still get empty address column and nulls in db. What else can I do ?

**Comment by vitalidze** [comment]
First thing to check is `tracker-server.log` file for error messages. Next you should try putting your latitude/longitude into this url http://nominatim.openstreetmap.org/reverse?format=xml&lat=60&lon=30&zoom=18&addressdetails=0 (`lat` and `lon` parameters) to check whether your address can be resolved.

**Comment by dudek-marcin** [comment]
Yes, when I put my lat and lon into link parameters it shows address correctly.
Also there are no errors in tracker-server.log

**Comment by vitalidze** [comment]
Then check whether address column is filled for your latest positions in database.

**Comment by dudek-marcin** [comment]
This is the first thing I checked. My latests positions: http://i.imgur.com/QwR35RO.png
Last one is from few minutes ago

**Comment by vitalidze** [comment]
According to the code of nominatim reverse geocoder in traccar backend you should either have an error message in `tracker-server.log` or an address column filled. Maybe you have updated wrong configuration file? I am out of ideas. I think you should post similar issue on project's issue tracker https://github.com/tananaev/traccar/issues

**Comment by vitalidze** [comment]
Closed due to inactivity
