### ISSUE TITLE
Get Current devices's unique id

### ISSUE THREAD

**Issue by sumisdev11** [vitalidze/traccar-web#1071]
Hi

I am trying to get current devices's unique id in my appplication, as when i opne a link in the browser,
I want to send the uniqueID of tracccar client to my application server.

Is  is possible with API call? 

Thanks in advance.

**Comment by vitalidze** [comment]
You can get unique ids of all available devices via the `getDevices` API call. Refer to the official docs for an example: http://traccar.litvak.su/features/rest-api.html

**Comment by sumisdev11** [comment]
Thanks for the response vitalidze. I refferd this document and  able get all the devices details.

But what I want is, when I open my own Application through the smartphone's browser, I have to send this device's traccar unique ID to my Application server via API call.. 
Is it possible?

**Comment by vitalidze** [comment]
I am not sure I understand, but what stops you from doing that? You have all the data, then you can write some code for your own application, which will take the data and make some server API call.
