### ISSUE TITLE
devices appear idle

### ISSUE THREAD

**Issue by fmelin** [vitalidze/traccar-web#1078]
Dear, good afternoon.
Along with greeting I need your help.

The devices appear as idle
![sintitulo](https://cloud.githubusercontent.com/assets/23340246/23520317/33e37082-ff59-11e6-8fd8-27ebca82d240.png)
, even though they are in motion or have been in motion recently.

Please help.
Beforehand thank you very much!!.

Greetings.

**Comment by gpproton** [comment]
Review your filter settings or rather temporarily comment out the filter on traccar.xml or in traccar-web ui.
If it's what I think it is it'll be resolved.

**Comment by fmelin** [comment]
Dear, excuse me.

I can not find the filter setting line in the traccar.xml file

`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key="config.default">./conf/default.xml</entry>

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
		<entry key='database.url'>jdbc:mysql://192.168.200.12:3306/telemetria_thk?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
		<entry key='database.user'>app_tr</entry> 
		<entry key='database.password'>Traccar.2017</entry>

		<entry key='web.type'>old</entry>
		<entry key='web.application'>/opt/traccar/traccar-web.war</entry>
		
		<entry key='event.enable'>false</entry>
		<entry key='event.overspeedHandler'>false</entry>
		<entry key='event.overspeed.notRepeat'>true</entry>
		<entry key='event.motionHandler'>false</entry>
		<entry key='event.geofenceHandler'>false</entry>
		<entry key='event.alertHandler'>false</entry>
		<entry key='event.ignitionHandler'>false</entry>
		<entry key='event.statusHandler'>false</entry>
		<entry key='event.maintenanceHandler'>false</entry>
		
		<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :protocol, :now, :deviceTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
		</entry>

		<entry key='database.selectLatestPositions'>
		    SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime,
		    valid, latitude, longitude, altitude, speed, course, address, other AS attributes
		    FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
		</entry>

		<entry key='database.updateLatestPosition'>
		    UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;
		</entry>

		<entry key='database.ignoreUnknown'>false</entry>

		<entry key='database.selectUsersAll'>
		    SELECT u.id, u.login AS name, u.password AS hashedPassword, u.salt, u.email, u.readOnly AS readonly,
		    u.expirationDate AS expirationTime, u.blocked AS disabled, u.admin,
		    us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
		    us.zoomLevel AS zoom
		    FROM users AS u
		    LEFT OUTER JOIN user_settings us ON us.id = u.userSettings_id
		</entry>

		<entry key='database.loginUser'>
		    SELECT u.id, u.login AS name, u.password AS hashedPassword, u.salt, u.email, u.readOnly AS readonly,
		    u.expirationDate AS expirationTime, u.blocked AS disabled, u.admin,
		    us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
		    us.zoomLevel AS zoom
		    FROM users AS u
		    LEFT OUTER JOIN user_settings AS us ON us.id = u.userSettings_id
		    WHERE u.email = :email
		</entry>

		<entry key='database.selectServers'>
		    SELECT s.id, s.bingMapsKey AS bingKey,
		    us.speedUnit, us.centerLatitude AS latitude, us.centerLongitude AS longitude,
		    us.zoomLevel AS zoom
		    FROM application_settings AS s
		    LEFT OUTER JOIN user_settings AS us ON us.id = s.userSettings_id
		</entry>

		<entry key='database.selectDevicePermissions'>
		    SELECT u.id AS userId, d.id AS deviceId FROM users AS u, devices AS d WHERE u.admin = 1
		    UNION
		    SELECT ud.users_id AS userId, ud.devices_id AS deviceId FROM users_devices AS ud
		    INNER JOIN users AS u ON ud.users_id=u.id
		    WHERE u.admin=0 AND u.readOnly=0
		</entry>
</properties>
`

**Comment by vitalidze** [comment]
This means that your devices sends data, which makes web UI considering it as Idle. You need to check historical data and settings in your device profile.
