### ISSUE TITLE
help modifi code for use personal

### ISSUE THREAD

**Issue by sjose778** [vitalidze/traccar-web#1079]
1. if there is very little programming, I would like to know which lines I must modify in the code to avoid that the managers have the option to create other manager that the manager box is disabled

2. you could do so that in the list of commands to send does not appear the option of sms or command

**Comment by vitalidze** [comment]
You need to have some programming skills to understand what should be changed and how. There is no other way.

>  managers have the option to create other manager that the manager box is disabled

Columns for users table are defined here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/UsersDialog.java#L106

User dialog is here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/UserDialog.java

Also to make it correctly it needs to have proper handling on the backend side, so even if UI is disabled server side will still not allow changing that option.

> you could do so that in the list of commands to send does not appear the option of sms or command

Commands drop-down list is defined here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/CommandDialog.java#L116

Also as for the first option it makes sense to update server side code to restrict such commands.
