### ISSUE TITLE
while installing traccar web in mac it shows an error called Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from bf7a8ddec10dc91618276bbeb1532592

### ISSUE THREAD

**Issue by AravinthElangovan** [vitalidze/traccar-web#1084]

**Comment by vitalidze** [comment]
Where do you see this error?

**Comment by AravinthElangovan** [comment]
while installing on mac it shows the above error on terminal

**Comment by vitalidze** [comment]
On which step of official instructions http://traccar.litvak.su/installation.html do you get this error ?

If you are talking about initial installation of the traccar backend, then it has nothing to do with "Traccar Web UI Mod". You should ask about it here: https://github.com/tananaev/traccar/issues
