### ISSUE TITLE
How to start web UI

### ISSUE THREAD

**Issue by forlearnios** [vitalidze/traccar-web#1086]
how to start the traccar mod web UI..? In traccar official it has localhost:8082 to view the web UI    In mod traccar web UI what I need to give to start traccar mod web UI..?

**Comment by vitalidze** [comment]
You need to follow official installation instructions: http://traccar.litvak.su/installation.html

**Comment by forlearnios** [comment]
In web UI it shows Device with this Unique ID already exists... But now only I firstly entered.. It is not connecting...

**Comment by vitalidze** [comment]
You need to look into log file for error messages. Most probably you haven't followed installation instructions carefully.

**Comment by forlearnios** [comment]
I'm not installed UI.... I'm just using demo this link https://d.traccar.litvak.su/?locale=default&nomobileredirect=1

**Comment by vitalidze** [comment]
Then most probably device with such ID already exists in the system. There are lots of devices registered there, many of them are mobile apps on android/ios, where you can define your own identifier.

So, you need to try another device ID.

**Comment by forlearnios** [comment]
ok I'll try....

**Comment by forlearnios** [comment]
I have given this unique device ID 12345678998765432112345678998765432112345678998765432192537485564758495061
but it also shows the same error Device with this Unique ID already exists

**Comment by vitalidze** [comment]
My demo server ran out of disk space. I have cleaned it up. Please try again now.

**Comment by forlearnios** [comment]
It worked....

**Comment by forlearnios** [comment]
While configuring the traccar web UI mod it shows an error in terminal and I'm using MAC 10.11.6
The file /Users/admin/opt/traccar/conf/traccar.xml does not exist. but the file is shown on ls command

**Comment by vitalidze** [comment]
On which step do you get this error?
