### ISSUE TITLE
New erros on traccar

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#1100]
> 2017-04-06 05:05:18 DEBUG: [5544BD92: 5023 > IP] HEX: 7878051307cda8990d0a
> 2017-04-06 05:05:32  WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms. - SQLTransientConnectionException (... < QueryBuilder:54 < *:135 < DataManager:293 < DefaultDataHandler:27 < ...)
> 
> 2017-04-06 05:03:48  WARN: Geocoding failed - nominatim.openstreetmap.org: System error - UnknownHostException (... < JsonGeocoder:62 < GeocoderHandler:58 < ... < ExtendedObjectDecoder:74 < ...)

This is turning off the platform alone.

Someone knows?

**Comment by vitalidze** [comment]
First one means your server lost connection to the database server (maybe it crashed, or networking went down). Second one means that your server running traccar could not resolve domain name nominatim.openstreetmap.org. By the way you should not use that server for reverse geocoding in production environment.
