### ISSUE TITLE
Server Down what happens to tracks

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1101]
Hi,

Can someone let me know when a server goes down and all the phones are running and trying to update the server it will fail. But if the server comes up at a later stage and clients connect does the server get all the tracks from the clients if the client is still running from the time it started?

Also, if the client stop the service and enable it later on does the server get the previously tracked info that the client was running before stopping the service?

thanks.

**Comment by vitalidze** [comment]
It depends on the client implementation. Some devices may record data when there are no connection to tracking server and send all recorded positions at once when connection is reestablished.

**Comment by akmal1999** [comment]
Does the traccar client does this?

**Comment by vitalidze** [comment]
According to https://github.com/tananaev/traccar-client-android/issues/109 it is implemented. I haven't tried it myself though.

**Comment by akmal1999** [comment]
I works and great we can close this issue.
