### ISSUE TITLE
how run Traccar 2.12 on server 

### ISSUE THREAD

**Issue by balasmeh** [vitalidze/traccar-web#1102]
Hello there, 

i want to ask is there any away to run Traccar 2.12 on server ? as of now im using my localhost with my platform and i can receive message from traccar client android to my localhost server .

is there any away to run traccar server over cloud because i found the file is .exe 
 
i hope i found any answer 

thank you

**Comment by vitalidze** [comment]
Traccar is written in java, so you can run it on any system, which can run can run Java Virtual Machine. I think all cloud virtual machines from all cloud providers can run it. Also you can create a Windows VM in Amazon if you are familiar with windows.
