### ISSUE TITLE
System going down

### ISSUE THREAD

**Issue by sankalpask** [vitalidze/traccar-web#1105]
hello,
when I try to generate a report more than 7 days, traccar system going offline. Then I can't login to system until restart traccar service..
Please help.

Thanks.

**Comment by vitalidze** [comment]
You need to look into log file for error messages. Looks like your server is running out of memory.

**Comment by sankalpask** [comment]
This is the log,

WARNING|wrapper|Service traccar|17-04-19 02:04:11|YAJSW: yajsw-beta-12.07
WARNING|wrapper|Service traccar|17-04-19 02:04:11|OS   : Linux/4.4.0-66-generic/i386
WARNING|wrapper|Service traccar|17-04-19 02:04:11|JVM  : Oracle Corporation/1.7.0_121//usr/lib/jvm/java-7-openjdk-i386/jre/32
INFO|wrapper|Service traccar|17-04-19 02:04:12|exec:"java" "-classpath" "/opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j-1.2.17.jar:/opt/traccar/lib/joda-time-2.9.6.jar:/opt/traccar/lib/h2-1.4.193.jar:/opt/traccar/lib/mysql-connector-java-5.1.40.jar:/opt/traccar/lib/postgresql-9.4.1212.jre7.jar:/opt/traccar/lib/mssql-jdbc-6.1.0.jre7.jar:/opt/traccar/lib/HikariCP-java7-2.4.9.jar:/opt/traccar/lib/slf4j-api-1.7.21.jar:/opt/traccar/lib/netty-3.10.6.Final.jar:/opt/traccar/lib/async-http-client-1.9.40.jar:/opt/traccar/lib/slf4j-simple-1.7.21.jar:/opt/traccar/lib/javax.json-1.0.4.jar:/opt/traccar/lib/jetty-server-9.2.19.v20160908.jar:/opt/traccar/lib/javax.servlet-api-3.1.0.jar:/opt/traccar/lib/jetty-http-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-io-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-security-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-webapp-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-xml-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-jndi-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-util-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-server-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-common-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-api-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-client-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jersey-container-servlet-2.24.jar:/opt/traccar/lib/jersey-container-servlet-core-2.24.jar:/opt/traccar/lib/javax.inject-2.5.0-b05.jar:/opt/traccar/lib/jersey-common-2.24.jar:/opt/traccar/lib/javax.annotation-api-1.2.jar:/opt/traccar/lib/jersey-guava-2.24.jar:/opt/traccar/lib/hk2-api-2.5.0-b05.jar:/opt/traccar/lib/hk2-utils-2.5.0-b05.jar:/opt/traccar/lib/aopalliance-repackaged-2.5.0-b05.jar:/opt/traccar/lib/hk2-locator-2.5.0-b05.jar:/opt/traccar/lib/javassist-3.20.0-GA.jar:/opt/traccar/lib/osgi-resource-locator-1.0.1.jar:/opt/traccar/lib/jersey-server-2.24.jar:/opt/traccar/lib/jersey-client-2.24.jar:/opt/traccar/lib/jersey-media-jaxb-2.24.jar:/opt/traccar/lib/validation-api-1.1.0.Final.jar:/opt/traccar/lib/javax.ws.rs-api-2.0.1.jar:/opt/traccar/lib/jersey-media-json-jackson-2.24.jar:/opt/traccar/lib/jersey-entity-filtering-2.24.jar:/opt/traccar/lib/jackson-jaxrs-base-2.5.4.jar:/opt/traccar/lib/jackson-core-2.5.4.jar:/opt/traccar/lib/jackson-databind-2.5.4.jar:/opt/traccar/lib/jackson-jaxrs-json-provider-2.5.4.jar:/opt/traccar/lib/jackson-module-jaxb-annotations-2.5.4.jar:/opt/traccar/lib/jackson-annotations-2.5.4.jar:/opt/traccar/lib/liquibase-core-3.5.3.jar:/opt/traccar/lib/snakeyaml-1.17.jar:/opt/traccar/lib/mail-1.4.7.jar:/opt/traccar/lib/activation-1.1.jar:/opt/traccar/lib/jxls-2.3.0.jar:/opt/traccar/lib/commons-jexl-2.1.1.jar:/opt/traccar/lib/commons-logging-1.1.1.jar:/opt/traccar/lib/commons-beanutils-1.9.2.jar:/opt/traccar/lib/jcl-over-slf4j-1.7.12.jar:/opt/traccar/lib/logback-core-1.1.3.jar:/opt/traccar/lib/jxls-poi-1.0.11.jar:/opt/traccar/lib/poi-3.14.jar:/opt/traccar/lib/commons-codec-1.10.jar:/opt/traccar/lib/poi-ooxml-3.14.jar:/opt/traccar/lib/poi-ooxml-schemas-3.14.jar:/opt/traccar/lib/xmlbeans-2.6.0.jar:/opt/traccar/lib/stax-api-1.0.1.jar:/opt/traccar/lib/curvesapi-1.03.jar:/opt/traccar/lib/velocity-1.7.jar:/opt/traccar/lib/commons-collections-3.2.1.jar:/opt/traccar/lib/commons-lang-2.4.jar" "-Dfile.encoding=UTF-8" "-Xrs" "-Dwrapper.service=true" "-Dwrapper.console.visible=false" "-Dwrapper.port=15003" "-Dwrapper.key=770044375494649972" "-Dwrapper.teeName=770044375494649972$1492567451960" "-Dwrapper.tmp.path=/opt/traccar/tmp" "-Djna_tmpdir=/opt/traccar/tmp" "-Dwrapper.config=/opt/traccar/conf/wrapper.conf" "-Dwrapper.visible=false" "-Dwrapper.pidfile=/run/wrapper.traccar.pid" "org.rzo.yajsw.app.WrapperJVMMain" 
INFO|wrapper|Service traccar|17-04-19 02:04:12|posix_spawn pid 28412
INFO|wrapper|Service traccar|17-04-19 02:04:12|started process 28412
INFO|wrapper|Service traccar|17-04-19 02:04:12|started process with pid 28412
INFO|28412/0|Service traccar|17-04-19 02:04:13|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|28412/0|Service traccar|17-04-19 02:04:14|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO|28412/0|Service traccar|17-04-19 02:04:19|[main] INFO org.eclipse.jetty.util.log - Logging initialized @6950ms
INFO|28412/0|Service traccar|17-04-19 02:04:20|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO|28412/0|Service traccar|17-04-19 02:04:21|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5734ea{/api,null,AVAILABLE}
INFO|28412/0|Service traccar|17-04-19 02:04:22|[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO|28412/0|Service traccar|17-04-19 02:04:26|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@12d4250{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-6390205218666209274.dir/webapp/,AVAILABLE}{/opt/traccar/traccar-web.war}
INFO|28412/0|Service traccar|17-04-19 02:04:26|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@11d58e0{HTTP/1.1}{0.0.0.0:8082}
INFO|28412/0|Service traccar|17-04-19 02:04:26|[main] INFO org.eclipse.jetty.server.Server - Started @14033ms
INFO|28412/0|Service traccar|17-04-19 02:12:38|Apr 19, 2017 2:12:38 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO|28412/0|Service traccar|17-04-19 02:12:38|INFO: Login 'administrator'

**Comment by sankalpask** [comment]
I'll increase the memory & try again..

Thanks a lot for your help.

**Comment by vitalidze** [comment]
I don't see any error messages in the above log. You can check 'tracker-server.log' file as well. Also it makes sense to check your linux log, like dmesg.
