### ISSUE TITLE
I dont upgrade traccar server with GUI

### ISSUE THREAD

**Issue by proyntec** [vitalidze/traccar-web#1107]
Hi, I am new in this and I need help with any problems with upgrade installation of traccar server. my problem is that icon of my device no show ,and in the original but simply proyect traccar found perfect but upgrade no found, and the log say the problem

WARN: Column count does not match; SQL statement:
INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); [21002-194] - JdbcSQLException (... < QueryBuilder:58 < *:135 < DataManager:293 < DefaultDataHandler:27 < ...)

I dont create db and dont know how.

please can you help me. note: sorry for english idiom but I speak and write only spanish,

**Comment by vitalidze** [comment]
You need to follow installation instructions carefully: http://traccar.litvak.su/installation.html H2 database is usually created by default and there is some tip on how to drop it.
