### ISSUE TITLE
Problem when I add new strings to ru translation

### ISSUE THREAD

**Issue by vilix13** [vitalidze/traccar-web#1108]
Hi, I'm working on some new functionality that I need. During this process, I added additional lines to the Messages_ru.properties:
```
# Drivers
drivers = Водители
surname = Фамилия
middlename = Отчество
newItem = Новый
driversOnDevice = Водители на устройстве
driver = Водитель
```
and Messages.properties:
```
# Drivers
drivers = Drivers
surname = Surname
middlename = Middle name
newItem = New
driversOnDevice = Drivers on device
driver = Driver
```
When I run project localy in Eclipse, all work as excepted, but when I build .war - `mvn clean package` and put .war to traccar server and run it, i have next:

![image](https://cloud.githubusercontent.com/assets/7453583/25199851/e47b7464-2554-11e7-88ae-567e94f051fd.png)

When I change locale to not `ru`, shows normal translations from en. That is, the problem is with translations that are new and only for the ru locale.

I do not know what the problem is. Thx for help.

**Comment by vitalidze** [comment]
In short: you need to clean up web browser cache. 

These strings with `@@@@` signs are showing for the strings, which were not found in loaded JSON file. Browser caches these files on it's own and since you are seeing these string, you have an old version of JSON file in your web browser cache.

**Comment by vilix13** [comment]
@vitalidze oh many thanks, I thought about the cache, but faith that chrome сtr + f5 cleans the cache knocked me..
