### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by maxlife70** [vitalidze/traccar-web#111]
Hi Vitalidze,
i would like to delete some language from the combo box in the login windows, but i don't understand how do it. Can you help me?

**Comment by vitalidze** [comment]
For desktop version update this line in this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/LoginDialog.java#L88 

For mobile version update this line in this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/pages/login.html#L13

Then build .war file using official instructions http://traccar.litvak.su/building.html

**Comment by maxlife70** [comment]
Thanks!!
