### ISSUE TITLE
Server website issue.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1119]
My website from time to time becomes like the picture attached and stops working.

I check the process still running. I stop it and start it and it works after that. I am wondering what is causing this.
![unnasmed](https://cloud.githubusercontent.com/assets/22064319/25493541/92048efa-2b44-11e7-8fa1-5a4a174c9639.jpg)

**Comment by vitalidze** [comment]
This is a known issue on some linux distributions. Read #484 for additional info and solution.
