### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by thericardovega** [vitalidze/traccar-web#1120]
Excuse my English, I'm using a translator.
Excellent work you do.

I am using gpstk103 protocol gps103, when iginicion is on, it is displayed on screen
Alarm poweron and ignition true, but after about 30 seconds it disappears. How can I do it so it will not be erased?

![ignition on](https://cloud.githubusercontent.com/assets/28070939/25505748/d997c7b8-2b68-11e7-97f1-18f3b628ecac.JPG)

![ignition on2](https://cloud.githubusercontent.com/assets/28070939/25505760/e446583c-2b68-11e7-9fe3-ee8a76cd9d14.JPG)

Thanks for your help.

**Comment by vitalidze** [comment]
You should be able to work it out using `processing.copyAttributes.enable` parameter in the traccar configuration file: https://www.traccar.org/configuration-file/

**Comment by thericardovega** [comment]
Yes, i add this line traccar.xml

`<entry key='processing.copyAttributes.enable'>true</entry>`
`<entry key='processing.copyAttributes'>power,ignition,battery</entry>`

but Still disappears,
What else could it be?

i restart traccar.xml -> service traccar restart, but still disappears

im unsing tk103 protocol gps103 port 5001
thanks for your time

**Comment by vitalidze** [comment]
I think the better place to ask about devices is [this issue tracker](https://github.com/tananaev/traccar/issues) or [forums](https://www.traccar.org/forums/).
