### ISSUE TITLE
Traccar 3.11 With UI 3.8

### ISSUE THREAD

**Issue by pmlewisuk** [vitalidze/traccar-web#1121]
Hi

I'm currently running Traccar 3.9 and UI 3.8.

I'm looking at upgrading to Traccar 3.11, are there any issues with this on UI 3.8 or procedures I need to follow? 

I'm hoping the SMS Notification works with it.

Regards

Mark

**Comment by vitalidze** [comment]
I haven't tried it with 3.11.

> I'm hoping the SMS Notification works with it.

This will not work for sure. This is part of original web UI. If you want to use this functionality you should stay with original web UI.
