### ISSUE TITLE
MapQuest

### ISSUE THREAD

**Issue by EasywareMX** [vitalidze/traccar-web#1124]
Hi Vitalidze! i was searching about MapQuest implementation.. But i don't find something that helps.. MapQuest is available for Web UI?, Is there any post where somebody explain how to do in the new version?

KeepWorking Litvak!

**Comment by vitalidze** [comment]
MapQuest is not available anymore. They have closed public access to their tiles server. The only option to use MapQuest is to switch to leaflet, which is not possible at the moment.
