### ISSUE TITLE
Unable to get battery or power info 

### ISSUE THREAD

**Issue by mehroz377** [vitalidze/traccar-web#1125]
I am unable to get battery level attribute in response even though I have enabled copyAttributes true like this

````xml
<entry key='processing.copyAttributes.enable'>true</entry> 
<entry key='processing.copyAttributes'>power,ignition,battery</entry>
````

and the response I get is 

````json
{"ignition":true,"status":4293393407,"ip":"119.160.102.157","distance":857.45,"totalDistance":735830.09} 
````

any idea what could be wrong I am using traccar 3.10 version and HO2 protocol.

**Comment by vitalidze** [comment]
Are you sure your device has reported either `power` or `battery` for some of the positions?

**Comment by mehroz377** [comment]
@vitalidze  I am able to get it using sms command

**Comment by vitalidze** [comment]
Your device must be reporting it to the traccar service. I think the better place to ask about devices is [this issue tracker](https://github.com/tananaev/traccar/issues) or [forums](https://www.traccar.org/forums/).
