### ISSUE TITLE
[Help wanted] Starting/stopping service

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#1126]
Hi!
On the traccar website, in order to start the traccar service it states:
> 3.8 and later: sudo /opt/traccar/bin/startDaemon.sh
> 3.7 and earlier: sudo /opt/traccar/bin/traccar start

I have tried both commands and they work for traccar-web. What's the most suitable command for traccar-web? Also @vitalidze I think it will be helpful for new users if you can add this command at the installation instructions page: http://traccar.litvak.su/installation.html

Thank you!

**Comment by vitalidze** [comment]
I am always using service command:

````
service traccar start
````

Or init.d script (much more rarely):

````
/etc/init.d/traccar start
````

You can prepend `sudo` if needed.

This is the correct way to deal with service, in most cases you should never use scripts from `/opt/traccar/bin` directly.

**Comment by vitalidze** [comment]
> Also @vitalidze I think it will be helpful for new users if you can add this command at the installation instructions page: http://traccar.litvak.su/installation.html

I assume that a man, who is installing the Traccar Web UI Mod does know how to start/stop service in his operating system. I consider Traccar a system for advanced user in terms of installation/administration.

**Comment by gsiotas** [comment]
> This is the correct way to deal with service, in most cases you should never use scripts from /opt/traccar/bin directly.

Yes that I was using as well, but Anton mentioned it on his website: https://www.traccar.org/linux/ that's why I asked that. Yes about updating the instructions page you are probably right.

**Comment by vitalidze** [comment]
I don't know why it is written so and I cannot do anything with his instructions. I know that his installer installs service scripts/symlinks as well. Thus, I still insist to do it in a similar way that it's done for all other linux services. This way you have to only know the service name (`traccar`) and should not care about anything else.
