### ISSUE TITLE
Mobile version through HTTPS

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#113]
I published traccar server throught HTTPS with apache mod_proxy.
Desktop version works fine, but mobile is just blank. Error in Crome console:

```
Mixed Content: The page at 'https://traccar/m/?locale=ru' was loaded over HTTPS, but requested an insecure stylesheet 'http://openlayers.org/en/v3.0.0/css/ol.css'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://traccar/m/?locale=ru' was loaded over HTTPS, but requested an insecure script 'http://openlayers.org/en/v3.0.0/build/ol.js'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://traccar/m/?locale=ru' was loaded over HTTPS, but requested an insecure script 'http://maps.google.com/maps/api/js?v=3&sensor=false'. This request has been blocked; the content must be served over HTTPS.
```

I think protocol (http) should also be removed from URLs in `/m/index.html`
https://github.com/tananaev/traccar/issues/731#issuecomment-44742917

**Comment by vitalidze** [comment]
I have updated URLs. Will do my best to release new version todays evening. There is a security issue with new 'read-only' users, which was fixed, but I want to cover all security checks by unit-tests.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/03/15/security-fix,-mobile-ui-script-links-fix-and-updated-spanish-translation.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
