### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MMartinezV** [vitalidze/traccar-web#1130]
Hi,

Yesterday I had problems to compile traccar-web ui from sources.

I think I'm using the recommended way, download the sources via git and then compile using: ./mvnw package (and java 1.7.0).

I get the following message:

````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project traccar-web: Compilation failure: Compilation failure:
[ERROR] /Users/manu/src/traccar-web/src/main/java/org/traccar/web/server/model/DataServiceImpl.java:[1152,25] cannot find symbol
[ERROR] symbol:   class Field
[ERROR] location: class org.traccar.web.server.model.DataServiceImpl
[ERROR] /Users/manu/src/traccar-web/src/main/java/org/traccar/web/server/model/DataServiceImpl.java:[1153,30] cannot find symbol
[ERROR] symbol:   class Field
[ERROR] location: class org.traccar.web.server.model.DataServiceImpl
[ERROR] -> [Help 1]
````

I've solved adding:
import java.lang.reflect.Field;
 to ./traccar-web/src/main/java/org/traccar/web/server/model/DataServiceImpl.java

Hope this helps. Regards,

  Manuel Martínez

**Comment by vitalidze** [comment]
I have just fixed this issue. Thank you very much for noting!
