### ISSUE TITLE
How to use traccar-web with traccar 3.11?

### ISSUE THREAD

**Issue by hardikm10** [vitalidze/traccar-web#1133]
As , traccar 3.11 doesnt have traccar-web.war in /opt/traccar, there is no point of replacing.
Can anyone guide me on this?

**Comment by vitalidze** [comment]
Traccar 3.11 is not officially supported. You don't need to replace anything if you do the installation for the first time.

**Comment by ghost** [comment]
Hi. I did all instruction of 3.8-3.9 in 3.11 installation and didn't works. Any other tips?

**Comment by vitalidze** [comment]
@rodgui you can try looking into log file for error messages to find what exactly does not work. Another option is to use 3.8 or 3.9 version of traccar.
