### ISSUE TITLE
GT06N Device Status Always online even vechile igintion is turned off

### ISSUE THREAD

**Issue by Sargunan** [vitalidze/traccar-web#1149]
Hi,

We are trying integrate GT06N device, we found device status does not turn to OFFLINE, Even though ignition state changed to NO

![image](https://user-images.githubusercontent.com/5010960/27446188-49d960b0-579a-11e7-8c75-8516fb3155e6.png)

is it configurable to show the device status as OFFLINE, when ignition status is NO

Thanks for your help

**Comment by vitalidze** [comment]
According to the screen shot you are using original web UI. You should ask questions about it on [forums](https://www.traccar.org/forums/) or in [issue tracker](https://github.com/tananaev/traccar/issues).
