### ISSUE TITLE
Can I develop this hole project using Struts,Hibernate and Spring Frameworks

### ISSUE THREAD

**Issue by umeshbichukale** [vitalidze/traccar-web#115]
Please let me know details of this project like can i develop this project by using frameworks after developing which type of vps is needed and about IP address and port number. please share above details. And one more thing is which java technologies i need to learn for developing this project as a my software company product. please please share all this details.
Thanks and regards
Umesh

**Comment by vitalidze** [comment]
I think it's possible to develop this project in struts, but I haven't used it. Right now it is using hibernate and Google Guice for dependency injection and AOP. Last one can be replaced with spring without much modifications.

To run it you will need a machine that is able to run java (virtual machines work too, i.e. amazon's EC2, google's computation engine, digital ocean,...). 

IP address is needed if you want to have an access from the internet, all cloud providers will give you an IP address. 

Default port in current `traccar-web` is 8082, but if you want to collect data from devices you can find list of ports here https://www.traccar.org/devices/

This web UI is built in GWT (http://www.gwtproject.org/) using the sencha's GXT component library (http://www.sencha.com/products/gxt/) and OpenLayers as the mapping library (with gwt-openlayers wrapper library for GWT).

I guess you should know how to code in java, basic things in web technologies (like web server, http protocol, html, etc.), networking (tcp/ip), servlets, hibernate, dependency injection, aop, RESTful services.

Hope this helps.

**Comment by umeshbichukale** [comment]
ok sir,
Thank you very much for your time and information you shared with me.I will
be touch with you whenever i need information now i am starting to develop
this project and i am going to develop this application as a my business.
Thanks and Regards,
Umesh Bichukale
917387970488
