### ISSUE TITLE
Can't register for or login to Demo

### ISSUE THREAD

**Issue by jmtces** [vitalidze/traccar-web#1150]
I cannot register or Login to your Demo server to have a look at your Mod UI.  When I put in any username/password and click register, I get "User name is already taken"...

![image](https://user-images.githubusercontent.com/29648359/27467773-4ffdccd4-5839-11e7-83a8-da32c0635a98.png)

When I put in any username/password and click login, I get "User name or password is invalid"...
![image](https://user-images.githubusercontent.com/29648359/27467831-d4f20cd4-5839-11e7-9d93-d3b84ba1805f.png)

How can I get a valid login to have a look at the UI?

James Taylor

**Comment by vitalidze** [comment]
Demo server ran out of disk space. I have cleaned it up and now it should work just fine.

**Comment by jmtces** [comment]
Thanks, it works now!
