### ISSUE TITLE
wrapper log file grows 9.9 gb from time to time.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#1152]
Hi,

It seems abnormal for the wrapper file to grow 9 GB. has anyone else experienced this if yes, what was the cause and how did you resolve this.

Many thanks.

**Comment by leontino** [comment]
with me too... The server always shutdown...

**Comment by akmal1999** [comment]
Exactly it overloads the server and the server space is done and then turns off. I wonder no one answers ?

**Comment by vitalidze** [comment]
You should use search before asking your own question. See #826 for example.

**Comment by andyguz** [comment]
hi leontino and akmal1999
