### ISSUE TITLE
Migrate to another Server (Computer)

### ISSUE THREAD

**Issue by EasywareMX** [vitalidze/traccar-web#1157]
Hi Litvak! Thanks for you hard work. Keep working, we are expecting more and more upgrade from you! (It's a little selfish comment) We love you! =D

Excuse me, but, please tell me if i will do this correctly. 

I need to change my server to another server.
I am missing something?
1.- Install same version of traccar in new server as the old server.
2.- copy configuration files from old server to new server
3.- stop traccar in old server
4.- export mysql database from old to new server
5.- import data
6.- start traccar server.

I'm right? my server is in production so, i need to confirm first. Please tell me if i am losing something.!

Thank You!

**Comment by vitalidze** [comment]
These steps looks good to me.

**Comment by EasywareMX** [comment]
Done! Worked fine!
