### ISSUE TITLE
API report help

### ISSUE THREAD

**Issue by pmlewisuk** [vitalidze/traccar-web#1159]
Hi 

Trying to pull a report using the API with the following, 

http://webaddress:8082/api/reports/trips/?groupId=6&from=2017-01-01&to=2017-06-30

I get a user / password box pop up, i enter the details and it keeps asking me for them when I hit enter. I know they are correct.

Is there a setting I've missed?

Thanks

Mark

**Comment by vitalidze** [comment]
These reports are not supported by this project. You should ask for help on the "backend" forums: https://www.traccar.org/forums/forum/server/

**Comment by pmlewisuk** [comment]
OK Thanks Vitalidze

Regards

MArk
