### ISSUE TITLE
How to migrate?

### ISSUE THREAD

**Issue by ediazhu** [vitalidze/traccar-web#1163]
First.
Thanks for the modification, and I speak Spanish. (Sorry for grammar errors)

I've been using Traccar for a while. (months) But it is a long time, using MySQL as a data base, and up there, working properly.

My server is in the United States. and MySQL too.

I want to move the server to my country. Because there is already fiber optics, less latency and all the benefits of proximity.

I need to migrate and install your modification on a new server
Already having an existing base?

Help me.

I have a poor idea, but I hope it works.

1. Install Traccar with the modification. (MYSQL empties with data from the new database)
2. Make a drop of the old MySQL, and paste it into the new MySQL.

Is this correct?

Please help me. I need to migrate and I don't want it to go wrong.

Thank you so much for your work. Bye

**Comment by vitalidze** [comment]
Please take a look at #1157. It contains basic steps. Generally your approach looks good too.

**Comment by ediazhu** [comment]
Thanks vitalidze! 

And as they say in my country....
"¡Eres de la ptm!"
