### ISSUE TITLE
Pick date calendar start day

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#117]
Pick date calendar starts on Sunday.
Could we choose to make it start on Monday, please?
Thank you.

**Comment by vitalidze** [comment]
I think this is locale (or browser) dependent thing. In my case it starts from monday both in default (english) and russian locales:

![screen shot 2015-03-17 at 22 54 06](https://cloud.githubusercontent.com/assets/2294325/6696197/9ac38bec-ccf8-11e4-9067-1f017084c08d.png)

![screen shot 2015-03-17 at 22 54 18](https://cloud.githubusercontent.com/assets/2294325/6696196/9ac28346-ccf8-11e4-976b-1875e98b73e5.png)

**Comment by peptoni** [comment]
OK. You are right.  My locale is english and that determines the day order.
Thank you!
