### ISSUE TITLE
TK102 the eyes are disconnected

### ISSUE THREAD

**Issue by kamil55** [vitalidze/traccar-web#1175]
after some days - hours - is tk102 disconectes (if server some hours stop)
tk102 is not reconected
will help
sms123456
gprs123456

TK103 is work fine.. (conect is ok)

can anything be done on the traccar server side?

Thanks Kamil

**Comment by kamil55** [comment]
after some days - hours - is tk102 disconectes (if server some hours stop)
tk102 is not reconected
will help
sms123456
gprs123456 (after this action is conecteed) it is all right

some new versions have been fixed

or user service (paid)

**Comment by vitalidze** [comment]
Please ask same question on the official traccar forum, which is more related with devices, then this issue tracker: https://www.traccar.org/forums/
