### ISSUE TITLE
Hide inactive devices

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#118]
Would it be possible to add an option to hide inactive devices on the map (only show active devices on map)?

**Comment by vitalidze** [comment]
It is possible. I also planned to add column with check boxes to the device table to make it possible to show/hide particular device/vehicle. I think this may be combined somehow.

**Comment by hardjumper** [comment]
Sorry I did not mean to close the issue.Yes It will be nice if we can combine them some how.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html) and [article](http://traccar.litvak.su/features/visibility.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
