### ISSUE TITLE
Not Supported in Protocol Osmand

### ISSUE THREAD

**Issue by allanqm** [vitalidze/traccar-web#1183]
When I try to send a command to a device, the following message is displayed:

"{\"reason\":\"java.lang.RuntimeException: Command rebootDevice is not supported in protocol osmand\",\"success\":false}"

My version of traccar is the 3.9 with the web gui http://traccar.litvak.su/. I configured the smpp server in the file traccar.xml.

How can I solve this problem?

Thanks.

Translate Portuguese by English.

**Comment by vitalidze** [comment]
AFAIK Traccar 3.9 does not support sending commands over SMPP. Thus, since the `rebootDevice` is not supported command to be sent via internet, then I don't see a way to solve this in 3.9.

**Comment by allanqm** [comment]
Thanks, I confused, the command is not smp, but grps. The issue has been resolved.
