### ISSUE TITLE
StateController.js url to external map coordinates

### ISSUE THREAD

**Issue by mihailtudoran** [vitalidze/traccar-web#1184]
It will be nice that coordinates shown into the State window of each device to have a link ( URL ) to external map, something like:

https://www.google.com/maps/place/44.478944,26.111047

I think it is very easy to implement and good to have if we want to get directions or calculate ETA to destination.

Thanks!

**Comment by vitalidze** [comment]
I think you have posted this into the wrong project. This project does not have neither separate "State" window nor `StateController.js`. You should post your feature request here: https://github.com/tananaev/traccar-web
