### ISSUE TITLE
Protocol Meiligao TK510 LCK Function

### ISSUE THREAD

**Issue by arrafa20** [vitalidze/traccar-web#1188]
Hello everyone,

We bought a TK510 GPS, it works under the meiligao protocol, but on the options there is no Arm/disarm the alarm, also it have doors lock/unlock on output 4 and 5. 

How can i create a command on the server to arm/lock, and another to disamr/unlock (As tk103b)

[TK510 user manual V4.0_20170103.pdf](https://github.com/vitalidze/traccar-web/files/1701639/TK510.user.manual.V4.0_20170103.pdf)

**Comment by vitalidze** [comment]
Please submit this request to the "backend" issue tracker here https://github.com/tananaev/traccar/issues

**Comment by arrafa20** [comment]
How difficult its to create the Arm/lock and Disarm/unlock options for this devices, it works under the meiligao protocol

[TOPTEN GPRS Communication Protocol V5.0_20171213.pdf](https://github.com/vitalidze/traccar-web/files/1709073/TOPTEN.GPRS.Communication.Protocol.V5.0_20171213.pdf)
