### ISSUE TITLE
Mysql connection on Digital Ocean droplet

### ISSUE THREAD

**Issue by tha-ninja** [vitalidze/traccar-web#1189]
```
<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://localhost:3306/delta_tracker?allowMultiQueries=true&autoReconnect=true</entry>
<entry key='database.user'>ninja</entry>
<entry key='database.password'>password</entry>

```

Thats my config script in traccar.xml but on starting the service it doesnt create the tables.

**Comment by tha-ninja** [comment]
my droplet runs Ubuntu 16.04.3 x64

**Comment by vitalidze** [comment]
I think you should check log files for error messages. Also, this project is about web UI. How your request is related with UI?

**Comment by tha-ninja** [comment]
i had installed traccar with the default H2 Database....but i figured out how to connect.
