### ISSUE TITLE
Traccar-web.war not found in 3.x versions.

### ISSUE THREAD

**Issue by Obaid-ur-Rehman** [vitalidze/traccar-web#1190]
I have installed 2.12 and found the traccar-web.war file on windows 10. It is working fine with 2.12.
However when I installed 3.9 version, I did not found any traccar-web.war file.
Please guide me to install this mod.

P.S. I have search for this issue a lot but could not found anywhere.

Best Regards

**Comment by vitalidze** [comment]
You should follow installation instructions from here http://traccar.litvak.su/installation.html
