### ISSUE TITLE
Error in save data on users

### ISSUE THREAD

**Issue by fabber1987** [vitalidze/traccar-web#1191]
hi, i have a problem when i save data on the users page, on save the traccar page result this error (image) the database is Microsoft SQL Server 2014, and all user is authorized for access on the db (default user is sa).

![immagine](https://user-images.githubusercontent.com/33523898/36252334-907e2112-1244-11e8-99c7-b3a3f213ecae.png)

**Comment by vitalidze** [comment]
This project is about modified version of the Web UI. You seem to be using "original" version. Please use this issue tracker instead: https://github.com/tananaev/traccar-web/issues
