### ISSUE TITLE
hello for all, my traccar is 3.16, this mod run?

### ISSUE THREAD

**Issue by tsdantas01** [vitalidze/traccar-web#1208]

**Comment by vitalidze** [comment]
Version 3.16 is not supported at the moment. Please use search before posting your own questions.

**Comment by tsdantas01** [comment]
your job on this project was perfect. congratulations.

my server is reporting this mistake, could you give me an way to resolve?


requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.



________________________________
De: Vitaly Litvak <notifications@github.com>
Enviado: quarta-feira, 5 de setembro de 2018 02:43
Para: vitalidze/traccar-web
Cc: tsdantas01; Author
Assunto: Re: [vitalidze/traccar-web] hello for all, my traccar is 3.16, this mod run? (#1208)


Version 3.16 is not supported at the moment. Please use search before posting your own questions.

**Comment by vitalidze** [comment]
You should add the `&amp;useSSL=false` flag to the MySQL connection URL in the `traccar.xml` file. After that if you restart the server everything should be just fine.

**Comment by tsdantas01** [comment]
All right

Em qua, 5 de set de 2018 17:31, Vitaly Litvak <notifications@github.com<mailto:notifications@github.com>> escreveu:

You should add the &amp;useSSL=false flag to the MySQL connection URL in the traccar.xml file. After that if you restart the server everything should be just fine.
