### ISSUE TITLE
how to install traccar-web.war file in traccar linux 4.0

### ISSUE THREAD

**Issue by manishnEosoni** [vitalidze/traccar-web#1209]
sir please guide me step by step how to install or use traccar-web.war file into my existing traccar server .. im using traccar 4.0 on linux machine on aws server

**Comment by vitalidze** [comment]
Traccar Web UI Mod is not compatible with Traccar 4.0. You should use 3.9 version of backend. To install you need to follow official instructions from here: http://traccar.litvak.su/installation.html

**Comment by manishnEosoni** [comment]
ok sir i will install traccar 3.9 but ..im unable to understand (http://traccar.litvak.su/installation.html) this installation instruction
please tell me how to install or can u give me video link for better understand.
please help me out these problem

**Comment by vitalidze** [comment]
The documentation is complete. If you are unable to understand it then you should ask some system administrator to help you.

**Comment by manishnEosoni** [comment]
i have no entry then what should i have to do 
<entry key='database.selectGroupPermissions'>
    SELECT userId, groupId FROM user_group
</entry>

<entry key='database.selectAttributeAliases'>
    SELECT * FROM attribute_aliases
</entry>

**Comment by vitalidze** [comment]
I guess your version is not 3.9 The instructions are written for configuration files from that version.

**Comment by manishnEosoni** [comment]
why u always misguide on any topic and why u don't give solid solution on any problem .. at least u have to make video tutorial of traccar-web.war installation .. that people can easily to understand ..

**Comment by manishnEosoni** [comment]
i missing lot if entry in default.xml file then what should i have to do..
