### ISSUE TITLE
Report menu Twiced !!

### ISSUE THREAD

**Issue by igor98800** [vitalidze/traccar-web#1215]
Hello,

Since 2 days my 'reports menu' is twiced
![english](https://user-images.githubusercontent.com/37465908/52828629-a85d2500-311d-11e9-84d0-47a21fea16c2.jpg)
![menu_doublon](https://user-images.githubusercontent.com/37465908/52828638-adba6f80-311d-11e9-8519-0b134d1d0d93.jpg)

I don't update/upgrade my linux OS since 2 years, as all was fine.
I tried
Linux / Windows / Chrome / Firefox cleared all cache...
usualy I am in 'french' UI , so, I swithed in English, the problem
is still there.
I deleted log files, restarted the computer...
May you have a way to help me please ?
Thanks.
Regards.
Igor

**Comment by vitalidze** [comment]
This means you or someone else have saved a "template" or a "preset" for each report. You need to open each report from the top list and delete it.

**Comment by igor98800** [comment]
Thanks a lot Vitaly. 

⁣Igor​

Le 15 févr. 2019 à 16:26, à 16:26, Vitaly Litvak <notifications@github.com> a écrit:
