### ISSUE TITLE
Compact or clean database

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#1218]
Hello,

My  mysql database is  9Go  !!!
How to clean or compact it please ?

regards.
Igor

**Comment by vitalidze** [comment]
You need to:

1. delete excessive data (positions, events)
2. dump your DB with `mysqldump`
3. depending on your MySQL config either wipe your entire MySQL data folder or just drop your existing DB

I would recommend to just clean up the data in 1 and don't do any additional steps. Then you have to periodically do such clean ups.
