### ISSUE TITLE
traccar 4.3

### ISSUE THREAD

**Issue by spacecabbie** [vitalidze/traccar-web#1219]
Just wondering is this compatible with traccar 4.3 ?

**Comment by vitalidze** [comment]
No, it is not compatible.

**Comment by spacecabbie** [comment]
Alrighty is it planned ?

**Comment by vitalidze** [comment]
There are no such plans at the moment.

пт, 1 мар. 2019 г., 2:27 SpaceCabbie <notifications@github.com>:
