### ISSUE TITLE
reversed geocoding in archive

### ISSUE THREAD

**Issue by bigoss** [vitalidze/traccar-web#122]
There is address column in archive view for reversed geocoding but it does not work at all.
If is possible to make it work then it should show wider at start and should be resizable like some of other columns. I can't find settings for this to make necessary changes.
Please help!

**Comment by vitalidze** [comment]
It shows data if you have it in database. The address is recorded when position gets inserted to the database by backend application. You can make it wider like any other column and this setting is save in database.

**Comment by vitalidze** [comment]
Any update on this issue?
