### ISSUE TITLE
Managers Shall not view/edit/remove other manager groups, only admin can

### ISSUE THREAD

**Issue by quantumapps0** [vitalidze/traccar-web#1221]
So, I'm using traccar for few years and now I have this issue, the Manager users can view/edit/remove all groups add even by Admin or other managers.

If this issue is solved I would appreciate you for your efforts.

**Comment by vitalidze** [comment]
This is by design and applies not only to manager, but to any ordinary user. If an ordinary user has access to the group then such user can view/edit/remove groups. This works exactly same for all other entities in traccar and is not going to be changed.

**Comment by quantumapps0** [comment]
@vitalidze  Thanks for the reply.
For example: Adding/removing users in manager role, each manager views only his users but admin view all.
But in Groups it's not like this, but it must be like this in my opinion each manager creates it's own groups and it's not shared with other managers only admin view all.
thanks

**Comment by vitalidze** [comment]
It is like this. If you have two managers that don't share devices anyhow then each of them can create his own groups and they will NOT be visible to another managers. However, if these groups are created by someone from the upper-level hierarchy, then they will be visible. You can read about access to groups here: http://traccar.litvak.su/features/groups.html

Please let me know a specific example where it does not work for you.

**Comment by quantumapps0** [comment]
Dear sir,

Thank you! The problem solved! I didn't know about that.

Regards
