### ISSUE TITLE
Can I Host this project directly on VPS server?

### ISSUE THREAD

**Issue by umeshbichukale** [vitalidze/traccar-web#125]
Hi Sir,
  Please sir tell me in detail, I have downloaded project from here and i purchased VPS server now i want to host a project which i have downloaded from your site (Can i host it directly without any change and will it work fine) and i also purchased GPS tracking devise (TK 103) can i configure it on my vps and will it work fine.

Thank you very much sir your help is important for me,
Thanks and Regard,
Umesh Bichukale
917387970488

**Comment by vitalidze** [comment]
First of all you should install basic traccar version like described here https://www.traccar.org/docs/ I recommend to install and use MySQL database. Then you should update `traccar-web.war` with these modifications with this installation guide http://traccar.litvak.su/installation.html.

**Comment by umeshbichukale** [comment]
Thank you very much sir.

**Comment by umeshbichukale** [comment]
Yes sir,
I am doing lots of practice but after that will it work fine or any changes
needed.
