### ISSUE TITLE
I am getting this error. and can't seem they are moving in the tracker

### ISSUE THREAD

**Issue by gonenmustafa** [vitalidze/traccar-web#126]
This page contains the following errors:error on line 1 at column 1: Document is empty Below is a rendering of the page up to the first error

**Comment by vitalidze** [comment]
Which page you are talking about?

**Comment by gonenmustafa** [comment]
When I am using tracker on my cell phone. If I click on the device that I am trying to track than it saysthe error and it's not moving

**Comment by gonenmustafa** [comment]
Actually under body section.  It does for a bit and dissappear

**Comment by vitalidze** [comment]
You mean in the side panel on the left?

**Comment by gonenmustafa** [comment]
Yessir

**Comment by vitalidze** [comment]
This is a known issue. Will do my best to fix it ASAP.

**Comment by gonenmustafa** [comment]
You are the best. I am not a programmer or nothing. But I appreciate that you made something that even I can use it.

**Comment by vitalidze** [comment]
Should work fine now please check. You can install it as usual with these instructions http://traccar.litvak.su/installation.html and also I have updated demo version.

**Comment by gonenmustafa** [comment]
Ok. Ty.  I will try and let you know

**Comment by gonenmustafa** [comment]
Appreciate that works great after the fix. Only one problem that if I use traccar app in the phone that I try to track everything else than I can only see myself in the map. As soon as I turn the app off than rest will appear. .

**Comment by vitalidze** [comment]
That's weird. You mean that if you run traccar application that sends you mobile device coordinates then you don't see other devices, just your cell phone? Does it affect desktop version of traccar UI or you just don't see it on you mobile UI?

**Comment by gonenmustafa** [comment]
It does happen on my mobile ui. on my mobile phone if I use desktop ui it doesn't do anything wrong. If I try to use it on mobile ui than I can only see the mobile device which is the one on with traccar app with the one I am watching it.

**Comment by gonenmustafa** [comment]
If I turned traccar app off than everything get back normal but I cant only see myself pretty much which not a big deal but I need to be getting tracked too

**Comment by vitalidze** [comment]
So desktop app always works correctly and shows all devices (including your mobile phone)? And the issue is on mobile UI only (I mean when you access your traccar web server from mobile phone)?

**Comment by gonenmustafa** [comment]
Yes exactly

**Comment by gonenmustafa** [comment]
so any clue whats going on?

**Comment by vitalidze** [comment]
I don't have any. Traccar web UI just displays data from your database. Maybe your device sends incorrect coordinates or so.

**Comment by vitalidze** [comment]
I have fixed an issue in mobile UI, which looks like yours. Please try latest version.

**Comment by gonenmustafa** [comment]
Thanks I will try and let you know

**Comment by gonenmustafa** [comment]
Appreciate it. It works perfectly fine now.

Mustafa

**Comment by vitalidze** [comment]
Sounds great. Thanks for testing.
