### ISSUE TITLE
From where to get new traccar Source code?

### ISSUE THREAD

**Issue by umeshbichukale** [vitalidze/traccar-web#127]
Hi Sir,
  please tell me from where do i get your updated traccar source code for both web interface and server side.are you providing source code of both server side and web interface and one more thing what is difference in server side and web interface.

**Comment by vitalidze** [comment]
My project source code is in this github project and is in git repository. This is an all-in-one package which has code both for server side (servlets) and client side (javascript build from GWT).

Also there is another project https://github.com/tananaev/traccar which can be called a 'back end'. It is used to collect data from devices/vehicles and has a separate code base.

So my project may be called a 'front end' because it's main function is to show data collected by 'back end'.

P.S. on my web site http://traccar.litvak.su/ there is a section `IDE project setup` that contains instructions for different IDEs on how to check out project source code and run it.

**Comment by umeshbichukale** [comment]
yaaa whavvv very fast reply...

Thanks very much

**Comment by rahulzeel** [comment]
Hello Sir,

We are newbie to Java. Is it possible to get step by step instructions to build your project in Eclipse, please help us with that.

**Comment by vitalidze** [comment]
Here are instructions for eclipse: http://traccar.litvak.su/ide/eclipse.html

**Comment by thaihau** [comment]
In order to start the 'backend' and 'frontend' in my local computer, i need to get both source code from https://github.com/tananaev/traccar  and github.com/vitalidze/traccar-web/?

**Comment by vitalidze** [comment]
If you want to start from IDE or build it yourself then yes. Both projects must look into the same database, so you will need to use MySQL or any other DB that supports simultaneous connections from multiple applications.

**Comment by thaihau** [comment]
How the 'frontend' getting the database connection when run from IDE? Where to configure which DB connection?

**Comment by vitalidze** [comment]
It's in `persistence.xml` file located in `src/main/resources/META-INF`. You need to edit the `debug` section, for example:

``` xml
  <persistence-unit name="debug">
    <properties>
      <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver"/>
      <property name="hibernate.connection.url" value="jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES"/>
      <property name="hibernate.connection.username" value="traccar"/>
      <property name="hibernate.connection.password" value="traccar"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
  </persistence-unit>
```

This is my configuration for development.

**Comment by thaihau** [comment]
Another question, is zit possible to start the GWT web app using maven command? Because i am having difficulty to setup using eclipse IDE, and i also dont have IDEA ultima ..

**Comment by thaihau** [comment]
Why the persistence-unit is "debug" but not "release"? How the java:/DefaultDS related to "release" persistent unit?

**Comment by vitalidze** [comment]
> Another question, is zit possible to start the GWT web app using maven command? Because i am having difficulty to setup using eclipse IDE, and i also dont have IDEA ultima ..

It should be possible to start it with `mvn gwt:run`

> Why the persistence-unit is "debug" but not "release"? How the java:/DefaultDS related to "release" persistent unit?

This `debug` persistence unit used during development. The JDBC parameters are set up explicitly there.

The `java:/DefaultDS` is provided by the servlet container. When you deploy it to the traccar backend it supplies the correct datasource by this name.

**Comment by thaihau** [comment]
Which branch should i use? If i use "origin/dev" After i start using mvn gwt:run, i got this "traccar (GWT Code Server)This module hasn't been compiled yet." when browse to http://localhost:9876/traccar/
<img width="536" alt="screen shot 2016-03-05 at 9 10 11 pm" src="https://cloud.githubusercontent.com/assets/851803/13547660/b6a3883c-e316-11e5-800f-0b711b3f0eb8.png">

When i run `mvn gwt:compile`, i got this error

> [INFO]       [WARN] Ignoring identical definition of the configuration property named locale.cookie (originally defined in com.google.gwt.i18n.I18N, redefined in org.traccar.web.i18n.I18N)
> [INFO]       [ERROR] Line 44: Unable to load class 'org.traccar.web.i18n.rebind.LocalizableGenerator'
> [INFO] java.lang.ClassNotFoundException: org.traccar.web.i18n.rebind.LocalizableGenerator
> [INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> [INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [INFO]  at com.google.gwt.dev.cfg.ModuleDefSchema$ClassAttrCvt.convertToArg(ModuleDefSchema.java:902)
> [INFO]  at com.google.gwt.dev.util.xml.HandlerArgs.convertToArg(HandlerArgs.java:64)
> [INFO]  at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:221)
> [INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
> [INFO]  at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)

I checked and there already have `org.traccar.web.i18n.rebind.LocalizableGenerator` in the workspace.

I also try on "origin/master", i can run `mvn gwt:compile` and `mvn gwt:run`, however i got this screen.
<img width="564" alt="screen shot 2016-03-05 at 11 01 34 pm" src="https://cloud.githubusercontent.com/assets/851803/13548231/90ffa402-e326-11e5-9776-3b0035f857cd.png">

**Comment by thaihau** [comment]
Finally, I able to start using eclipse mars2 and gwt plugin. But i still no idea how to start using maven command line.

**Comment by vitalidze** [comment]
> Which branch should i use? If i use "origin/dev" After i start using mvn gwt:run, i got this "traccar (GWT Code Server)This module hasn't been compiled yet." when browse to http://localhost:9876/traccar/

You should use `dev` branch. All changes are there. The `http://localhost:9876/traccar/` is incorrect. By default it should be something like `http://127.0.0.1:8888/traccar.html`. Actually you should open it from the UI window like this, which is opened in the `gwt:run` task:

![screen shot 2016-03-06 at 10 01 12](https://cloud.githubusercontent.com/assets/2294325/13552818/6e4923b4-e382-11e5-9f45-526fb76e63b9.png)

I just hit `Launch default browser` button. Then browser opens, the compilation starts and completes in about couple of minutes. Then it is working.

> I also try on "origin/master", i can run mvn gwt:compile and mvn gwt:run, however i got this screen.

You should not use the `master` branch since it is configured to run through the old unsupported dev mode, which required the plugin for the web browser to work. Now such plugin is not supported by modern browsers and you must use the "SuperDevMode" for debugging.

**Comment by thaihau** [comment]
I run `mvn package` to package the WAR, is zit normal the WAR file contain "deploy" folder under "META-INF"? 
I get this message when i use the newly package WAR 

```
Couldn't load traccar from Super Dev Mode
server at http://:9876.
Please make sure this server is ready.
```

Checked with chrome console, it is triggering `$IP:9876/recompile-requester/traccar`...

Below is the screen shot by comparing original traccar-web with the one i build using maven package.

<img width="998" alt="screen shot 2016-03-10 at 11 03 45 pm" src="https://cloud.githubusercontent.com/assets/851803/13673589/b3e2c3e0-e714-11e5-9a92-75221c1478a4.png">

**Comment by vitalidze** [comment]
The correct way to build .war file is to run `package` task. Actually I don't know about the correctness of contents, the one publicly available is the correct one. If you haven't done any breaking changes then contents should be very similar. I recommend to run a `clean` task before building.

As for your browser error message I think you are using incorrect port. `9876` is used for the Code server, you should not use it directly.

**Comment by thaihau** [comment]
I din not use the `9876` port. The default page initiate request to `http://xxxxx:9876/recompile-requester/traccar` and hit this error. Just want to know in what condition the code will connect to code server? By right once i run `package` task, the WAR that generated will not contact code server?

**Comment by thaihau** [comment]
Found the root cause, this is because IDE gwt plugin generate "traccar" folder under webapp which will contact the code server.

**Comment by vitalidze** [comment]
Code server is used in SuperDevMode only. So it will connect there only when you enable such mode. By default on production system (i.e. in built `traccar-web.war`) it is not needed.

Let's stop discussion in this old closed thread. Please create a new one if needed.

**Comment by sandersonsa** [comment]
I love you
