### ISSUE TITLE
Is not a GWT Project?

### ISSUE THREAD

**Issue by umeshbichukale** [vitalidze/traccar-web#128]
I have a problem with eclipse when imported to eclipse luna 4.4 as existing maven project gwt compile shows:
is not GWT project 
please help me to solve this error.

**Comment by vitalidze** [comment]
I guess it's same issue as #103 . I will give it a try and update instructions accordingly once I have time. For now I recommend trying [IntelliJ Idea](http://traccar.litvak.su/ide/idea.html) or [NetBeans](http://traccar.litvak.su/ide/netbeans.html).

**Comment by umeshbichukale** [comment]
ok. but clear this issue as soon as possible.

**Comment by vitalidze** [comment]
Should work now with [updated instructions](http://traccar.litvak.su/ide/eclipse.html)
