### ISSUE TITLE
Language file

### ISSUE THREAD

**Issue by VentureSWE** [vitalidze/traccar-web#129]
Hi!

I have created a swedish translate file, Messages_sv_SE.properties and edited Traccar.gwt.xml which i added <extend-property name="locale" values="sv_SE" />

Is there some more files to edit because i cant get my translation to work.

I hope to get some help.

**Comment by vitalidze** [comment]
Sounds like you've done it right. Does your language shows on the login screen?

**Comment by VentureSWE** [comment]
No it does not show, Just the regular languages. Maybe i can sen you the translated file to update?

**Comment by vitalidze** [comment]
Have you rebuilt the traccar-web.war file using [these instructions](http://traccar.litvak.su/building.html)?

You can send it to me by email (find it in my github profile).

**Comment by VentureSWE** [comment]
No i did not. I unpacked the .war file and edited the files only.
I will try your instructions later today.

**Comment by vitalidze** [comment]
Added, written [news](http://traccar.litvak.su/2015/04/02/swedish-translation-and-minor-ui-bugfix.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
