### ISSUE TITLE
Possibility to choose which notifications to receive (send to user)

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#130]
It wold be nice to have possibility choose which notifications to receive (send to user) per user.

My device is sleeping most of time and i don't want receive notifications about going offline, but about entering/leaving geo-fence i want.

May be someone doesn't want to receive notifications about entering geo-fence, but about leaving wants.

**Comment by elRadix** [comment]
I agree, I don't want to receive constant online/offline message - geo-fence notifications are good enough for me.

maybe also add notifications send during working hours only - to be set/defined by the user.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/04/07/notification-event-type-selection-and-pushbullet-sender.html), updated [article](http://traccar.litvak.su/features/notifications.html), public available [version](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://traccar.litvak.su/demo.html).

@elRadix please submit another issue with request of notifications schedule feature if it is still needed
