### ISSUE TITLE
Information about Donation to project

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#131]
It would be nice to add information on how to thank you for the work. May be in README.md and on your website.

PayPal, Webmoney or non financial aid.

You do great work and i'm sure that people will want to thank you.

**Comment by vitalidze** [comment]
Added [donation page](http://traccar.litvak.su/donate.html) with PayPal link. I don't have a Webmoney account.

Anyway, thanks for suggestion ;) Glad to know that someone appreciates my time and effort spent on this project.

I am still thinking about paid support/features/development, but for now everything is free.
