### ISSUE TITLE
Pushbullet notifications

### ISSUE THREAD

**Issue by elRadix** [vitalidze/traccar-web#132]
Instead of receiving many emails, please add the possibility to send through pushbullet, free service for mobile/desktop devices 

API documentation here
https://docs.pushbullet.com

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/04/07/notification-event-type-selection-and-pushbullet-sender.html), updated [article](http://traccar.litvak.su/features/notifications.html), public available [version](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://traccar.litvak.su/demo.html).
