### ISSUE TITLE
Geo-Fence Email Notification Issue

### ISSUE THREAD

**Issue by joepr** [vitalidze/traccar-web#133]
Hello Everyone

I have just installed a fresh copy of traccar and latest build of traccar web on a virtual Centos machine at home. I wanted to test the brand new geo-fence option. Tracker shows perfectly on map and geo-fence was created. I Fill out all the email fields however I'm getting a Test Fail . I'm sure my Gmail credentials are correct I think this is something to do with my server configuration. I know OpenGTS uses Javamail to push email notifications. Does Traccar needs this to be installed on a special directory? I try to search on traccar website but no luck so far.  
![image](https://cloud.githubusercontent.com/assets/10345032/6984672/469614be-d9f9-11e4-88f8-373e38b2580f.png)

Best Regards,
Joe

**Comment by vitalidze** [comment]
JavaMail comes with traccar-web.war package. You should check wrapper.log file located on server under `/opt/traccar/logs` folder. Regarding gmail most probably you should enable third party application access to your account in google account security settings.

**Comment by joepr** [comment]
Hello VItalidze

Thanks for the tip. I search the web and I notice someone had the same issue . For those gmail users that want to use this feature need to visit this link https://www.google.com/settings/security/lesssecureapps
And click Turn Off 
This should solve their problem. Hope it helps in future.
Note: You must be logged in to your account before visiting the link

**Comment by vitalidze** [comment]
Does it help you?

**Comment by vitalidze** [comment]
FYI I have added 'Troubleshooting' section to [this article](http://traccar.litvak.su/features/notifications.html) with your link. Thanks.
