### ISSUE TITLE
versao mobile

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#137]
hello I am using the latest version UI.
but the mobile version geo -fence does not display in the UI sidebar.
I strongly believe in their work and ask for your help.

**Comment by vitalidze** [comment]
Sounds like an issue with mobile browser cache (i.e. it cached old version). Please try mobile UI from desktop browser. If it works then you should find out how to clear browser cache on your mobile device.

**Comment by MarceloMJM** [comment]
Hello in desktop mobile version works normally.
cache were cleaned , and tested with other phones , but the problem persists.

**Comment by vitalidze** [comment]
I have just checked it on demo site and it works just fine on my iPhone:

![img_1943](https://cloud.githubusercontent.com/assets/2294325/7003500/f339cfc8-dc63-11e4-8bde-e11726a85f43.png)

I still think this is an issue with caching on your mobile device. Please double-check it.

**Comment by MarceloMJM** [comment]
I think the problem is on my side  or I'm not using the current version will download and test again.

**Comment by vitalidze** [comment]
Any update on this issue? Can we close it? :)

**Comment by MarceloMJM** [comment]
problem still exists but can close the required question .

**Comment by ijrad** [comment]
Hi, I developed a Traccar manager version using hybrid framework (Ionic), it is free and compatible with the UI Mod:
https://play.google.com/store/apps/details?id=com.ionicframework.tracgpsmonitor461755
