### ISSUE TITLE
Redevelopment of traccar-web UI.

### ISSUE THREAD

**Issue by umeshbichukale** [vitalidze/traccar-web#138]
Can i redevelop this traccar-web for good look and feel using html,css,javascript by using Spring Framework mvc,ioc and aop for traccar-web. and i will use traccar-master for back-end as it is will it work fine or not. One more thing is i want to add reports facility how do i add it.

If any good suggestion please help me.
Thanks in advance

**Comment by vitalidze** [comment]
What is your question about? About your abilities? If you have knowledge in all these technologies then you can develop it. Traccar-master may be used as a backend to write data to the database, and you can develop a completely new application (even not in java) that will do a presentation for the data.

**Comment by vitalidze** [comment]
AFAIK here is the beginning of development for new web UI in javascript and HTML https://github.com/tananaev/traccar/tree/master/web

**Comment by umeshbichukale** [comment]
Thanks lot.
i am asking this because i am fresher and i don't have that much knowledge
and i am developing this because i like this technology.
please help my queries free minded.
Thanks lot sir.

**Comment by vitalidze** [comment]
Closed due to inactivity.
