### ISSUE TITLE
[traccar-web] Notification

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#139]
Hello , I would like to modify the header of notification
[ Traccar -web ] Notification
[ Xxxxx -xx ] Notification
Because edited the NotificationService $ NotificationSender on line 68, but the traccar does not start.
Is there another way ?

**Comment by elRadix** [comment]
I would be great to have the device name something like this
[ Device Name] Notification

or use a custom name [ server/custom name ] Notification -- [Device Name]

**Comment by vitalidze** [comment]
@Marcelomjm sounds like an issue with building. How did you built `traccar-web.war` after changing `NotificationService` class?

@elRadix What about notifications for many devices? Right now they are combined into a single message/pushbullet note.

**Comment by MarceloMJM** [comment]
Extract the folder $ Notification Service Notification Sender edited [traccar] Notification with a personal name and added it back in its original location.
The same procedure occurred in editing Exportservlet.class
traccar-positions.csv
traccar-positions.gpx

**Comment by vitalidze** [comment]
The correct way is to edit .java file and then rebuild traccar-web.war file with official instructions http://traccar.litvak.su/building.html

**Comment by MarceloMJM** [comment]
ok thanks.

**Comment by elRadix** [comment]
@vitalidze or just the possibility to have '[ Traccar -web ] Notification' to a custom user defined name as proposed initially '[ xxxxx ] Notification' without having to manually hack the files and having to do this for each update... just a thought.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/04/26/notification-templates-and-archive-loading-speedup.html), updated [article](http://traccar.litvak.su/features/notifications.html), [latest](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.
