### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by maxlife70** [vitalidze/traccar-web#141]
Hi,
I would like to know if is possible change the default language.to another insteed english.
Thanks

**Comment by vitalidze** [comment]
Yeah, it is possible. The easiest way is to add following line to the `traccar.html` file packaged inside `traccar-web.war` inside `<head>` tag:

```
 <meta name="gwt:property" content="locale=your_locale_code">
```

For example for russian locale:

```
 <meta name="gwt:property" content="locale=ru">
```

I have a shell script that automates it:

``` bash
#!/bin/bash

LOCALES=ru
for loc in $LOCALES
do
        cp -f $1 ${loc}_$1
        unzip -p $1 traccar.html | awk -v langtag="    <meta name=\"gwt:property\" content=\"locale=$loc\">" '{print} NR==4{print langtag}' > traccar.html
        jar uf ${loc}_$1 traccar.html
        rm traccar.html
done
```

To use it I do the following:

```
./addlocale.sh traccar-web.war
```

As an output there will be a `locale_code_traccar-web.war` file (`ru_traccar-web.war` in above case).

**Comment by vitalidze** [comment]
FYI I have somewhere in my TODO list to add locale and timezone selection to the user's preferences (and maybe to application's preferences too). This will help for example to send localized notifications with date/time in user's timezone.

**Comment by maxlife70** [comment]
Great is ok. Thanks.
For mobile version i have changed the lang parameter in the tag HEAD in the index.html file, but the default language is always english. There is other file to change?

PS. I have sent to you by email the new files for italian language. Desktop and mobile version.

**Comment by vitalidze** [comment]
Yeah, above instructions are for desktop version only. For mobile you should update this line https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/traccar-mobile.js#L9 and this line https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/traccar-mobile.js#L100 (i.e. change 'en' to your locale).

PS. Thanks for the translation. I will try to do my best to release it either today or tomorrow.

**Comment by maxlife70** [comment]
Ok also the mobile version. Thanks

**Comment by vitalidze** [comment]
FYI I have already finished language selection in 'Global' settings (in scope of 2 from #148). Thus, in newer version you won't need to change anything except that setting. Next version should come next week.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/04/20/bugfix,-translation-updates-and-default-language-selection.html), updated [latest](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by maxlife70** [comment]
Hi. With the last release (2.12) i'm no longer able to change default language for desktop versione as you have said to me previously with the meta tag. Mobile is ok.
there is other file to change?
Thanks

**Comment by maxlife70** [comment]
I have seen now the new option in global setting. Now is ok.
Sorry for the new question. I close the thread
