### ISSUE TITLE
Translate for pt_BR

### ISSUE THREAD

**Issue by robertoalmeida** [vitalidze/traccar-web#142]
I'm interested in contributing to the project with the translation for the pt_BR language (Portuguese Brazil). 

I can translate and send you?

**Comment by vitalidze** [comment]
You should translate this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/resources/org/traccar/web/client/i18n/Messages.properties and then send it to me either with pull request or by email (from my github profile). Also you can cooperate with @leontino because he wanted to provide same translation too.

**Comment by vitalidze** [comment]
For mobile version translation you should update this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/i18n/Messages.js

**Comment by jbaterdene** [comment]
After translation how we can show newly added language on a list? Please confirm, Looks need to add new language on two places, on a list. (login.html and Traccar.gwt.xml). When I compiling war file with new language "Desktop version" is working correct with newly added language and Mobile version completely broken, shows only black screen. Is there is missing something on configuration?

**Comment by vitalidze** [comment]
Sounds like you've done everything right. Do you see any error messages in web browser console?

**Comment by jbaterdene** [comment]
Sorry for the late respond, Found my mistake, forget to add coma between languages in Messages,js , in my case cloned the last language package and translated, so the last language set package finishes without coma, this means for when someone add new language looks first time shows without any errors, need to add coma "," between "language code" and "}" symbol. Every language set start with "Language code" then "{" symbol and finishes with "}" symbol. Example: "},    sv_SE: {"
This one is funny mistake, but when someone start with something new everything, even a tiny small symbol like a come will border you. Hope this one helps to someone noob like me.

**Comment by daniloadur** [comment]
Hi

Translation pt_BR done, I hope it be good and correct enough.

Cheers

**Comment by vitalidze** [comment]
Added, written [news](http://traccar.litvak.su/2015/06/09/major-changes-to-devices.html), added [article](http://traccar.litvak.su/features/portuguese-brazilian.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by leontino** [comment]
I came back! Alguém traduziu algo ?
