### ISSUE TITLE
Mobile Interface - Devices appear and disappear

### ISSUE THREAD

**Issue by studmuffinjj** [vitalidze/traccar-web#144]
I am experiencing this issue on the mobile interface where just 2 of my devices constantly disappear and reappear, presumably when the interface refreshes. I have my refresh set to 5 seconds. Below screenshots should indicate what I mean:

When I log on:
![selection_017](https://cloud.githubusercontent.com/assets/11912640/7106258/13f46af8-e109-11e4-9b87-32534e548efa.png)

After about 5 secs:
![selection_018](https://cloud.githubusercontent.com/assets/11912640/7106261/2c0fbd68-e109-11e4-9e0e-210d38d48b24.png)

After about 10 secs:
![selection_019](https://cloud.githubusercontent.com/assets/11912640/7106279/46dee3c6-e109-11e4-91ac-b1d749a0850e.png)

After about 20 secs:
![selection_017](https://cloud.githubusercontent.com/assets/11912640/7106285/641f53ee-e109-11e4-8c26-630c13c281b2.png)

And then both devices disappear again:
![selection_018](https://cloud.githubusercontent.com/assets/11912640/7106293/8f5e501e-e109-11e4-8c23-d6c46775aab1.png)

These are device IDs 2 and 3. The other IDs don't seem to exhibit this problem. I have reinstalled the traccar server and dropped and recreated a fresh mysql database and the problem persists.

This is the April 7 version of traccar-web.war. The problem was experienced in previous releases as well.

**Comment by vitalidze** [comment]
Thanks for reporting, sounds like an issue from #126. Do you experience same issue when looking into mobile web UI from desktop web browser? If so then please take a look at the javascript console for error messages.

**Comment by studmuffinjj** [comment]
Yes, problem exists on both android mobile chrome browser and desktop browser accessing the mobile UI.
Here is the only output from the javascript console:

 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-max-device-pixel-ratio: 1), (max-resolution: 120dpi)

I believe you are correct that it is related to #126 because I have, on some occasions, opened the mobile UI on my phone and did not see one or two devices, even after waiting for a while, they never showed up.

**Comment by vitalidze** [comment]
Ok, what about loading positions from archive? Do you get correct trace? Maybe these are some jumps related to incorrect work of GPS on your device?

**Comment by studmuffinjj** [comment]
On the desktop UI, loading from archive yields correct trace. If the device is in motion while on the mobile UI, they disappear and after a while, reappear at the new location. Web UI updates normally. There are 3 GPS devices, all the same gps103 protocol. Only 2 drop off the mobile UI. 

When I dropped and re-created the mysql database, I entered the devices in a different order. One of them which was giving problems has stopped disappearing, now it's another one.

**Comment by vitalidze** [comment]
Well, I will try to do a code revision next week to indicate an issue. But from my understanding the code is quite simple: both mobile and desktop UI use same code to retrieve latest positions, just the serialization format differs. Maybe this is some kind of issue in OpenLayers. You can also give me some kind of temporary access to your web UI if that's an option (in such case I can debug your issue directly in browser). Right now on my traccar instances this issue does not reproduce.

**Comment by studmuffinjj** [comment]
Not a problem. I have sent an email to vitavaque@gmail.com with details for admin credentials. Kindly confirm receipt.

Please let me know if you require SSH access to the server as well.

Thanks for your assistance.

**Comment by vitalidze** [comment]
Got them, thanks. I will start looking tomorrow.

**Comment by vitalidze** [comment]
I think I have found and fixed the issue. Please try latest version.

**Comment by studmuffinjj** [comment]
Issue has been corrected. All devices remain on the mobile UI as they should now.

Thanks!

**Comment by vitalidze** [comment]
Glad to hear that! Please don't forget to remove my user account from your server.

**Comment by vitalidze** [comment]
Written [news](http://traccar.litvak.su/2015/04/14/bugfix-and-translation-updates.html), included in [latest available](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.
