### ISSUE TITLE
Driver´s log

### ISSUE THREAD

**Issue by VentureSWE** [vitalidze/traccar-web#146]
Hey!
I wish to have the function for driver's log, that traccar register address at the starting point and stop point. The user should be able to change if the trip is on duty or privately, and be able to print the Journal.

My hope is to be able to put a switch in the car (TK103) where the driver can change from business or private driving. Guess you could register it via the ACC or door connecting cables.

Hope this is something that can be arranged.

// Martin

**Comment by vitalidze** [comment]
Looks relative to #37. I think they can be implemented altogether.

**Comment by ghost** [comment]
I think that you can achieve with a reader 1 wire, where the driver can be identified by a 1wire button, most of the Hardware GPS supports or has at least one 1wire port, the rest would add a table to store drivers to car is related and the number of button 1wire. Also interesting would be to separate the vehicles by groups, such as:
Group 1: Vehicle 1 Vehicle 2 Vehicle 3 ......
Driver 1 - 2 driver - driver X .......
regards
Mikel Cuellar O.

**Comment by matthuisman** [comment]
Why not more of a general URL call for notifications?
You can enter a URL, that it will post the data to?

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

@VentureSWE  Let me know if existing reports suite your needs. I guess something like 'Drives and stops' should be very close to your requirements.
