### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by angyy10** [vitalidze/traccar-web#147]
Hi, as advised, I submit my previous issues (https://github.com/tananaev/traccar-web/issues/249#issuecomment-93245573) over here, sorry for any inconvenience.

This is the guide I followed to deploy the application.
http://www.tutorialspoint.com/gwt/gwt_deploy_application.htm

Basically I am zipping the war folder, rename to .war extensions, then overwrite the war file in "C:\Program Files (x86)\Traccar" of my server.

By the way, thanks for your quick response :)

**Comment by vitalidze** [comment]
If you change anything that is related with GWT you need to recompile. Repacking won't work. Here are the official building instructions: http://traccar.litvak.su/building.html

Are you using eclipse? Are you sure you are using my modified version of `traccar-web`?

**Comment by angyy10** [comment]
yup, I am using eclipse :)
I am using the version from https://www.traccar.org/source-code/, I guess it is the one you mentioned "very different" than yours?

**Comment by vitalidze** [comment]
Yeah, that's right. Instructions from traccar.org website won't work. To set up my project in eclipse follow these instructions: http://traccar.litvak.su/ide/eclipse.html You can also find complete list of what has been added to the original project here: http://traccar.litvak.su/features/ (this is the differences)

**Comment by angyy10** [comment]
hi, after I build the war and deploy to my production server,  i got error similar to this: http://stackoverflow.com/questions/27186577/gwt-2-7-gae-app-looks-for-codeserver-when-deployed

do you know why it happened? I am following your build instruction

**Comment by vitalidze** [comment]
I haven't seen it before. That stackoverflow thread describes why it happens. Try running `mvn clean` and then `mvn package` or in a single command `mvn clean package`.

**Comment by angyy10** [comment]
Hi, I had solved by deleting the nocache.js.
Thanks for your assistance :) I will close the issue

**Comment by vitalidze** [comment]
Sounds weird. I guess it should not work without `.nocache.js` files because they contain java code compiled into javascript. Anyway, I'm glad that it works for you.
