### ISSUE TITLE
Localised notifications

### ISSUE THREAD

**Issue by vitalidze** [vitalidze/traccar-web#148]
For my private project I need localised notifications (in russian language). I can see two ways of implementation (which may probably be combined):

1) Add message template with following fields:
- title
- body

Template will be in [Java Minimal Template Engine](https://code.google.com/p/jmte/) format.

I think the best way will be to have a message template per event type (or maybe even per device so notification will always be send for single device).

This will work for #139 too.

2) Add global language setting (like said in #141) and have localized messages in `Messages.properties` file. This global setting will also change the default language of entire traccar interface (so you won't have to edit `traccar.html` file anymore).

If someone has any thoughts on this - please express them :)

**Comment by antoniopaisfernandes** [comment]
Don't quite grasp every aspect of it but... I'll help translating whatever needs to.

From the translation maintenance point of view, the least number of files to address, the better (for now, we have 1 for desktop UI - per language - and 1 for mobile UI - all languages). But I reckon that coding structure shouldn't oblige by this...

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/04/26/notification-templates-and-archive-loading-speedup.html), updated [article](http://traccar.litvak.su/features/notifications.html), [latest](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.
