### ISSUE TITLE
how to open in gwt designer

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#154]
hi vitalidze 

is there any way to open the views in GWT .

it is always  give me  

java.lang.NoSuchMethodError: com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(Lcom/google/gwt/core/ext/TreeLogger;Ljava/lang/String;Z)Lcom/google/gwt/dev/cfg/ModuleDef;

regrads

**Comment by vitalidze** [comment]
Looks like this is a bug in Eclipse Luna (see http://stackoverflow.com/questions/24208710/gwt-designer-eclipse for additional info).

Besides, I am not using it (I develop in IntelliJ Idea which don't have such feature at all) and I highly don't recommend using UI Designer at all. It's always better to know how it works under cover. Writing UIBinder XML files is quite simple too.

**Comment by xizoaziz** [comment]
thanx 4 ur help
