### ISSUE TITLE
Geo-fence Reporting functionality

### ISSUE THREAD

**Issue by elRadix** [vitalidze/traccar-web#158]
This is a feature request to have a reports to provide data regarding geo-fences.

Based on the reporting period per device and/or all devices:
Nr of checkin/out per geo-fence
Duration time in the geo-fence
Average time per geo-fence
Distance travelled when speed is higher than a certain threshold

Maybe also the possibility to have these report auto-scheduled sent by email (daily, weekly or monthly)

**Comment by MarceloMJM** [comment]
It would be great to have the notification for speeding

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
