### ISSUE TITLE
Direction overlay on device icon

### ISSUE THREAD

**Issue by studmuffinjj** [vitalidze/traccar-web#159]
Along the same lines as having a speed indicator as #124 , would it be possible to implement the device direction by means of an arrow overlay on or above the device icon? 

Older versions of the web interface used to indicate direction in the side bar by degree from 0-359. The arrow image can be rotated based on this degree value and removed/changed at a value of speed 0.

This can be useful when looking at devices at a glance to get general direction rather than wait for an update or manually checking the archive, especially devices which poll to the server every few minutes rather than seconds.

**Comment by gsiotas** [comment]
+1

**Comment by gsiotas** [comment]
Just to give my 2 cents, on another GPS server software the path of the device is mentioned in yellow arrows. Each arrow is like the marker of the traccar. If you double click on a arrow (marker) you get this popup and a larger green marker with a directional white arrow. Screenshot:
![screen-shot-2015-11-21-at-2 54 56-am](https://cloud.githubusercontent.com/assets/10040858/11315520/e0cd37f2-8ffb-11e5-8f1e-f53eb6365a43.jpg)

**Comment by 8wmas** [comment]
This is a very important feature and it would be nice to be included in a future release.
+1

**Comment by flyjodel** [comment]
in fact the original version of traccar, at least version 3.3 includes this feature

**Comment by ramlaxmanrimal** [comment]
As there is already Course detection 
![image](https://cloud.githubusercontent.com/assets/15964695/13141064/71618956-d65d-11e5-99a5-3add96c375c7.png) I think icon of 6 different orientation can be implement easily.

**Comment by vitalidze** [comment]
@ramlaxmanrimal There should be more than six orientations, at least eight for the basic support (N, NE, E, SE, S, SW, W, NW). Anyway, I thought that an arrow icon can be rotated to the exact angle stored in 'course' column.

If you think that it is easy to implement then you are welcome to implement it yourself. Then you can send a pull request to share your work with all users of this UI mod.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
