### ISSUE TITLE
Devices following in mobile version

### ISSUE THREAD

**Issue by vitalidze** [vitalidze/traccar-web#161]
Add a 'switch' element to the device panel with 'Follow' label. Once checked same logic for 'following' as on desktop version must be applied: device must be always on screen, i.e. when device goes off screen it should be centered back.

**Comment by wolfbgn** [comment]
That is if user has peveleges (not read only). May be in web interface when you check the box "follow"on one device, the other one ( ones) should be unchecked.

**Comment by vitalidze** [comment]
@wolfbgn got your point about having single 'followed' device. What do you mean about 'user has privileges'? You mean 'read only' user cannot use the 'follow' function?

**Comment by wolfbgn** [comment]
I do not know how to answer your question. I think there should be two kinds of users.
1.Without any priviliges, like it is now.(option for little kids who dont know what are they doing, there are such grown ups too).
2.Users who do not have the option to add, edit or remove devices but all other options for customization are available (changing maps, measurment units, username, password etc.)
Is it possible when registration is closed the button registration to disappear?

**Comment by vitalidze** [comment]
I think your thoughts are not related anyhow with the 'Following' option in mobile version, which is this issue about.

Please submit a separate issue/issues with your feature requests.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/05/15/mobile-ui-improvements-and-update-of-bulgarian-translation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
