### ISSUE TITLE
Sorting of archive entrys

### ISSUE THREAD

**Issue by codebude** [vitalidze/traccar-web#166]
I'm not able to sort any of the column in the archive/list view. In normal web ui I could sort the columns by clicking the column headers.

**Comment by vitalidze** [comment]
This is a side effect of using fast 'live-grid' that displays only part of data at the time. Maybe this can be worked out somehow, but also can become a problem for large number of points. Probably sorting can be moved to the server side. Which fields are you using for sorting?

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/05/12/bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by codebude** [comment]
Wow! That was fast! Thank you really much!
