### ISSUE TITLE
Изменение названия событий 

### ISSUE THREAD

**Issue by Anton7sk** [vitalidze/traccar-web#168]
Виталий приветствую! Существует ли возможность изменить название событий и действий связанных с событием? Например сейчас "io2 - 1" возможно ли "зажигание - включено", или "io2 - 0" "зажигание - выключено", имеются ввиду события в сплывающем окне при наведении мыши.

**Comment by vitalidze** [comment]
Этот текст хранится в базе. Без изменений в коде проекта это сделать нельзя. Вот здесь происходит генерация HTML для дополнительных полей: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/PositionInfoPopup.java#L51

**Comment by Anton7sk** [comment]
Виталий спасибо за столь быстрый ответ! При изменении в коде эти события изменятся для всех устройств. Возможно ли изменение настройки дополнительных полей через веб-интерфейс для каждого устройства?

**Comment by vitalidze** [comment]
Все верно, изменятся для всех. В текущей реализации возможности менять такие настройки из интерфейса не существует, но сделать это теоретически можно.

**Comment by Anton7sk** [comment]
Существуют ли планы по реализации теории на практике? )))

**Comment by vitalidze** [comment]
В данный момент планов нет. Кроме Вас об этом никто не спрашивал. Пусть эта задача пока висит в очереди :)

**Comment by Anton7sk** [comment]
Готов стать спонсором для приоритетности этой задачи. :)

**Comment by vitalidze** [comment]
Почему Вы закрыли эту задачу?

**Comment by Anton7sk** [comment]
Виталий прошу прощения за закрытую задачу. Я тупанул просто напросто.

**Comment by Anton7sk** [comment]
Виталий! День добрый! Как можно перевести деньги на paypal! Я заказал карту
в банке, ждал две недели пока ее изготовят, но не могу ее подключить к
системе paypal, платежные карты из Казахстана не поддерживаются! У меня
есть webmoney кошелек и qiwi кошелек но напрямую в paypal из этих кошельков
нет возможности перевести. Что делать, даже не знаю!

2015-05-13 18:46 GMT+06:00 Vitaly Litvak <notifications@github.com>:

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/06/09/major-changes-to-devices.html), added [article](http://traccar.litvak.su/features/sensors.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by pivasik** [comment]
Так как решилась проблема с названиями?

**Comment by vitalidze** [comment]
@pivasik я добавил [функционал по редактированию имен сенсоров](http://traccar.litvak.su/features/sensors.html)

**Comment by pivasik** [comment]
Все увидел а вашу сборку можно установить как сборку Антона(просто запустив ехе)?

**Comment by vitalidze** [comment]
Нельзя. Нужно следовать инструкциям http://traccar.litvak.su/installation.html . Если ставить поверх 3.3 или 3.4 то есть нюансы #509 #510 #519 #520 #521

**Comment by pivasik** [comment]
Спасибо, буду вникать. Было бы не плохо сделать инструкцию и на русском языке к сожалению не все знают англ.(

**Comment by pivasik** [comment]
Все получилось спасибо, 
Было бы еще не плохо выставлять важность события и отмечать данную запись на карте другим цветом например: датчик - ioXX важность - высокая, если значение => или < указаного значения.

**Comment by vitalidze** [comment]
> Было бы еще не плохо выставлять важность события и отмечать данную запись на карте другим цветом например: датчик - ioXX важность - высокая, если значение => или < указаного значения.

Это есть в планах. Также в планах добавить возможность задавать картинки для интервалов, которые потом показываются рядом с иконкой устройства - тоже разные в зависимости от интервала (например заряд батареи)

**Comment by pivasik** [comment]
Будем ждать))
