### ISSUE TITLE
Field "description" in table "devices"

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#170]
It will be great if you add field description in table devices like this:
![1](https://cloud.githubusercontent.com/assets/7967243/7698263/94aed7ca-fe30-11e4-9f25-b6872f80739d.png)
![2](https://cloud.githubusercontent.com/assets/7967243/7698265/9d6db93a-fe30-11e4-9885-f756b268ed15.png)

**Comment by vitalidze** [comment]
I also wanted to add a 'Photo' field in scope of #85 so anyone can upload big picture to the profile and then show it in popup (optional). I think these will be done at the same time and maybe with #168 too

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/06/09/major-changes-to-devices.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
