### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by gatsu666** [vitalidze/traccar-web#171]
Hi,
I would like to change the default language.
How can i do?

Thanks.

**Comment by vitalidze** [comment]
Since #141 it can be done in `Settings >> Global` menu.

**Comment by gatsu666** [comment]
I want to change the default language in the code.

**Comment by vitalidze** [comment]
I think the easiest way will be to remove this line from configuration file https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/Traccar.gwt.xml#L16

and then set it up in `<meta>` tag in `traccar.html` file like said here: https://github.com/vitalidze/traccar-web/issues/141#issuecomment-91893508

**Comment by vitalidze** [comment]
Closed due to inactivity.
