### ISSUE TITLE
Feature request: Access control and  limited number of devices

### ISSUE THREAD

**Issue by daniloadur** [vitalidze/traccar-web#175]
Great job Vitaly, the new UI is much better, very weldone.!

I have a feature request: I would like to have more control over the user and managers, and these are the suggestions:

Being admin and/or manager

1) have the possibility to block /allow some user access individually (admin can block managers and users and manager just can block users)

2) set the max number of devices that the users can add but individually (admin can set max number of devices for manager and manager can set max for users)

Cheer.

**Comment by bizkit1** [comment]
has this function been implemented?

**Comment by vitalidze** [comment]
Fields were added to the database and logic were added to the server and client side. But no UI to set this up yet. I believe it will come in nearest future (one-two weeks).

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/06/24/czech-translation-and-couple-of-updates-on-user-accounts.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
