### ISSUE TITLE
error : please help me to sovle this. Thanks

### ISSUE THREAD

**Issue by ChiHungLam** [vitalidze/traccar-web#178]
Description Resource    Path    Location    Type Resource file css (supported extensions: css, gss) is missing (expected at org/traccar/web/client/view)    DeviceMarkersDialog.java    /traccar-web/src/main/java/org/traccar/web/client/view  line 73 Google Web Toolkit ClientBundle Problem

**Comment by vitalidze** [comment]
Sounds like an incorrect project configuration issue. Which IDE are you using?

**Comment by ChiHungLam** [comment]
i use Eclipse Java EE IDE for Web Developers.

Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800

**Comment by ChiHungLam** [comment]
error at file : DeviceMakersDialog.java

```
interface Resources extends ClientBundle {
    @ClientBundle.Source("PicturesListView.css")      
    Style css();
}
```

**Comment by vitalidze** [comment]
I don't have an eclipse to try it right now, but I suggest you to try putting the full path to the CSS file as follows: `org/traccar/web/client/view/PicturesListView.css`

**Comment by ChiHungLam** [comment]
ok, thanks you.
i will try again.
