### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#180]
To have custom icons is wonderful.  Could we have bigger icons, please...?  70 pixels wide is quite small on big screens...

Thank you!!!!

**Comment by vitalidze** [comment]
Which size is optimal from your point of view? I want to avoid uploading photos as the device icons. 

Maybe other users can express their opinion?

**Comment by peptoni** [comment]
Ah... Good question.  Probably no unique answer to that.  I guess it's more related to final screen size.  Maybe not limit icon size and let the final user assume the performance impact on system...?  Here is how it looks on my screen...  I'd love to see, at least, double the size...  thank you my friend for a beautiful work.
![screen shot 2015-06-10 at 20 52 59](https://cloud.githubusercontent.com/assets/11501146/8091223/d9a19960-0fb2-11e5-8d44-76694fcb85ec.png)

**Comment by elRadix** [comment]
i think 256x256 would be a good size, not fixed but anything up to that size

**Comment by vitalidze** [comment]
Updated, written [news](http://traccar.litvak.su/2015/06/12/updated-icon-size-limits-and-translations.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
