### ISSUE TITLE
Plans for the future

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#182]
What are the plans for the future. Will this part of traccar system grow up as separate project? If I undersud well athanev is developing new, pure javascript, web interface.

**Comment by vitalidze** [comment]
This is already a separate project. Right now it is fully compatible with backend application. I plan to do my best to support deploying of my web interface instead of the "pure javascript" one. And I don't have any plans on rewriting it in pure javascript, at least for now.

**Comment by mpele** [comment]
Thank you for quick response. 
I am looking for software for fleet management, and in traccar system I see good basis for it. Are there plans to develop this application in that direction?

**Comment by vitalidze** [comment]
This application is already being used for fleet management for some people (including myself, but my fleet currently is of five vehicles only). The question is what do you understand by the means of this phrase. You can walk through this issue tracker to find out pending feature requests, I am trying to do my best tot work them out, but it takes quite long because it is a part time project for me.

**Comment by mpele** [comment]
In my opinion there are missing better user/vehicle management and reporting system. If there are plans for improvements in that area I could take part in developing, so right now I am trying to find out what are long turn plans.

**Comment by vitalidze** [comment]
I think next I will work on user management improvements, many tickets on this issue tracker are open for that topic right now (#140 #165 #169 #174 #175). Then I wanted to work out notifications on idle/start (#25 #88 #95). Then I thought about global notifications, which are not tied to a particular user but rather to something like channels or http URLs (#153 #173). Reporting is still quite unclear to me, I don't know which reports to implement, no one has ever submitted some examples or so (#146 #158).

This is briefly the long term plan.

**Comment by VentureSWE** [comment]
Hi! Here is my idea about drivers log. You have to choose whitch period you want to get the log, ex 2015-06-01 to 2015-06-30. You must have the abillity to change from business trip to private trip and save the log. See my example. 

![drivers log](https://cloud.githubusercontent.com/assets/11742454/8150254/d494ade4-12e2-11e5-9173-1ca517c82885.jpg)

//Martin

**Comment by mpele** [comment]
This project could be highly dependent on traccar server according database structure that is used. Is there a collaboration with atanev on this topic?

**Comment by vitalidze** [comment]
I have no collaboration with Anton. In traccar project Anton Tananaev has already moved database creation queries (SELECTs/INSERTs are already there in current public available version) to the configuration file, which makes it as flexible as possible (see https://github.com/vitalidze/traccar/blob/master/debug.xml#L41).

**Comment by mpele** [comment]
Thank you for clarifications.
