### ISSUE TITLE
traccar-web and Eclipse

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#184]
I have followed instructions from http://traccar.litvak.su/ide/eclipse.html and everything was OK but when I try start the error is reported (if that is error):

A port must be an integer or "auto"
Google Web Toolkit 2.7.0
DevMode [-[no]startServer] [-port port-number | "auto"] [-whitelist whitelist-string] [-blacklist blacklist-string] [-logdir directory] [-logLevel level] [-gen dir] [-bindAddress host-name-or-address] [-codeServerPort port-number | "auto"] [-[no]superDevMode] [-server servletContainerLauncher[:args]] [-startupUrl url] [-war dir] [-deploy dir] [-extra dir] [-modulePathPrefix ] [-workDir dir] [-XmethodNameDisplayMode NONE | ONLY_METHOD_NAME | ABBREVIATED | FULL] [-sourceLevel [auto, 1.6, 1.7]] [-XjsInteropMode [NONE, JS, CLOSURE]] [-[no]incremental] module[s] 

It is the same situation when I set in settings to use port 8888 or auto.
Does anyone have idea what was wrong?

**Comment by vitalidze** [comment]
Looks like you are running `GWT Classic Dev Mode` while you should run `GWT Super Dev Mode`.

**Comment by mpele** [comment]
It looks like that is not problem.
The arguments that are used:

-superDevMode -port 8085 -war /home/mpele/git/traccar-web/src/main/webapp -remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -logLevel INFO -codeServerPort 9997 -port org.traccar.web.Traccar

**Comment by vitalidze** [comment]
How have you fixed this issue? Maybe I should include it into `Troubleshooting` section on the [web site](http://traccar.litvak.su/ide/eclipse.html).
