### ISSUE TITLE
Geo-fence notification

### ISSUE THREAD

**Issue by bizkit1** [vitalidze/traccar-web#185]
I have a problem with geo-fence entry/leave notifications, i don't receive them. I have setup email address, server settings and all other notifications work. I have added geo-fences, selected for which tracker it's supposed to be available, but nothing happens. Anybody with the same problem? Thanks!

**Comment by vitalidze** [comment]
Do you see geo-fence in device popup when it entered the area?

**Comment by bizkit1** [comment]
yes,right now i see a blue icon with the name of my geofence

**Comment by vitalidze** [comment]
Then it's worth to check the `events` table for geo-fence enter/exit records.

**Comment by bizkit1** [comment]
i only have offline notifications in event

**Comment by vitalidze** [comment]
Well, it sounds like a bug. Will look into it once I have time. It would be great if you can send me a database backup, or at least screen shots of geo-fence set up and exported positions data in GPX format.

**Comment by bizkit1** [comment]
ok, check mail please

**Comment by vitalidze** [comment]
Any update on this issue? I have written to you by email that I wasn't able to reproduce your issue and need contents all `wrapper.log` files.
