### ISSUE TITLE
Maintenance bug

### ISSUE THREAD

**Issue by bizkit1** [vitalidze/traccar-web#186]
Another bug is in the maintenance tab calculation. I add the device km, the maintenance interval...etc and select auto. It sometimes calculates right, but sometimes it adds to much to the count.
For example, this morning i had 161600KM, and now it shows 205629Km and warns me about maintenance. Any idea?

**Comment by vitalidze** [comment]
Looks like there were some jump in position reported by your device. You can generate 'Archive' report to see when it happened, I believe you will see it in 'distance' column.

**Comment by bizkit1** [comment]
For today the distance is just 39km in the archive

**Comment by vitalidze** [comment]
Are you using "Filter" for archive?

**Comment by bizkit1** [comment]
no, again i have set the right km this morning, and now from 161650 it shows 231451km

**Comment by vitalidze** [comment]
This is an issue with your device, which sends wrong positions with date 2011-12-13 and zero latitude/longitude coordinates, like this one:

```
| 5447 | Kuluçka           |        0 |      0 |        0 |         0 | <info><protocol>tk103</protocol><milage>606528</milage></info> |  NULL |     0 | 2011-12-13 16:15:30 |     0 |         1 |
```

You can configure traccar backend to ignore these positions, see configuration options with names starting from `filter` here: https://www.traccar.org/configuration-file/

**Comment by vitalidze** [comment]
Any update on this issue?

**Comment by bizkit1** [comment]
I have just modified the config file with the filtering options. Later when i will leave work and arrive home, i will post an update about this.

**Comment by bizkit1** [comment]
ok, so, until now looks ok, calculations were ok. I just modified filtering options like this:

 
<entry key='filter.enable'>true</entry>

<entry key='filter.invalid'>true</entry>
<entry key='filter.zero'>true</entry>

**Comment by bizkit1** [comment]
ok, so, until now looks ok, calculations were ok. I just modified filtering options like this:

```
 <!-- Filtering options -->
<entry key='filter.enable'>true</entry>
<!-- <entry key='filter.limit'>3600</entry> -->
<entry key='filter.invalid'>true</entry>
<entry key='filter.zero'>true</entry>
<!-- <entry key='filter.duplicate'>true</entry> -->
<!-- <entry key='filter.distance'>50</entry> -->
```

**Comment by vitalidze** [comment]
Any update on this issue?
