### ISSUE TITLE
New language 

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#187]
What should be done to add new language?

**Comment by vitalidze** [comment]
Generally you have to:
- update `src/main/java/org/traccar/web/Traccar.gwt.xml` - add there a line for new locale XX. This is for 'desktop' version translation.
- add new `Messages_XX.properties` file to the `src/main/resources/org/traccar/web/client/i18n/` folder. It should contain translated strings from `src/main/resources/org/traccar/web/client/i18n/Messages.properties` file. Strings that are missing translation will use the value from `Messages.properties` file. This is for 'desktop' version translation.
- update `src/main/webapp/m/js/i18n/Messages.js` file by adding there XX translation block. This is for 'mobile' version translation.

For an example you can observe changes in this this revision: https://github.com/vitalidze/traccar-web/commit/19a9747368aba60bad717070d5c59151e62ed256

**Comment by xizoaziz** [comment]
hi vitalidze 

i tried to add Arabic langue it s working fine but HTML style works wrong it shift all panel and divs .

i tried to add
  <inherits name="com.google.gwt.user.theme.chrome.Chrome"/>  
 <inherits name='com.google.gwt.user.theme.standard.StandardRTL'/>  
 but the same issue .

<img width="556" alt="screen shot 2015-08-18 at 7 41 38 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336183/eba88e48-45e0-11e5-92b7-f7c531a8f2f2.png">
<img width="583" alt="screen shot 2015-08-18 at 7 41 22 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336184/ebaf6358-45e0-11e5-829a-37a08f3ed670.png">
<img width="1280" alt="screen shot 2015-08-18 at 7 42 29 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336186/ebb652e4-45e0-11e5-8539-ed1732c347aa.png">

any help please

**Comment by vitalidze** [comment]
@xizoaziz No need to post your question twice. See answer in #236

**Comment by xizoaziz** [comment]
sorry for that 

best regards
