### ISSUE TITLE
User Login Log

### ISSUE THREAD

**Issue by wahwahbinks** [vitalidze/traccar-web#189]
Hi,

Is it possible to log the Logins with Timestamp ?

Thanks

**Comment by vitalidze** [comment]
Right now it is not implemented. I guess for now the easiest way would be to log the calls of `login` method to the log file (wrapper.log).

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/06/24/czech-translation-and-couple-of-updates-on-user-accounts.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by wahwahbinks** [comment]
Thank you !!
