### ISSUE TITLE
Device State format

### ISSUE THREAD

**Issue by bizkit1** [vitalidze/traccar-web#190]
For my tk103, i have addes in the device sensor list the following:
Name: State, Parameter:state and the intervals are 0=Off and 1=On
I can see this in the device popup, but the value is: 000000A if it's on and 0000000B if is Off. How can i make text appear instead of these values?

**Comment by vitalidze** [comment]
Right now it works only with numeric values. I don't have in plans changing it to work with text due to complexity. I think it's better to update device protocol decoding on the backend side.

**Comment by vitalidze** [comment]
I thought a bit more and actually `000000A` and `000000B` may be interpreted as a number in [hexadecimal system](https://en.wikipedia.org/?title=Hexadecimal#Using_0.E2.80.939_and_A.E2.80.93F) - `10` and `11` accordingly. So probably current number parser can be updated to accept such as well (right now only decimal numbers with floating point are supported).

**Comment by bizkit1** [comment]
I am thinking of coding something like if string is hex make it number, then probably i could interpret it in the sensor values. But please tell me where can i find the code block for this part.

**Comment by vitalidze** [comment]
For desktop version it is done here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/view/PositionInfoPopup.java#L83

For mobile version it is done here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/traccar-mobile.js#L457

**Comment by bizkit1** [comment]
Ok, thanks, already modified for desktop version and works now, moving on to mobile :)

**Comment by vitalidze** [comment]
Sounds great. You may consider submitting a pull request with your work after it's finished.

**Comment by vitalidze** [comment]
Is there any chance to get your changes to the upstream?
