### ISSUE TITLE
Error changing icons

### ISSUE THREAD

**Issue by RobertBenedikt** [vitalidze/traccar-web#191]
If the user has "read only", should not be able to record, or change the icon for the device.
If it does, change the icons for all users on the system they are currently using these icons.

**Comment by vitalidze** [comment]
There was an issue with whole read-only function. Actually read-only user should not even be able to see the device management buttons (add/edit/remove). Right now it is fixed and pictures uploading was prohibited for read-only users on the server side as well. Please try latest version.

**Comment by RobertBenedikt** [comment]
thank you very much for quick response

**Comment by vitalidze** [comment]
Updated, written [news](http://traccar.litvak.su/2015/06/24/czech-translation-and-couple-of-updates-on-user-accounts.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
