### ISSUE TITLE
Snap to roads

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#193]
Would it be possible in the future to enable snap to roads in route drawing...?  Even the free option looks attractive.

https://developers.google.com/maps/documentation/roads/snap
https://developers.google.com/maps/documentation/roads/

Thanks for a beautiful work!!!

**Comment by peptoni** [comment]
I know Google requires a license...

For openstreetmap (THE open way to go...) there is this project:

http://project-osrm.org

**Comment by peptoni** [comment]
Here is a demo of the osrm engine.  It's very quick, can retrace in real time if you add points.

http://map.project-osrm.org

This is the service/function used, I think:

https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-match

**Comment by vitalidze** [comment]
I think it is possible. Looks like this one https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-match suits the needs of snapping of points loaded from archive. Also from my understanding their demo server may be used without any restrictions (see https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy for more info). I will put this feature to my roadmap.

**Comment by vitalidze** [comment]
Thanks for sharing information :+1:

**Comment by peptoni** [comment]
Thank YOU for this fantastic work, and for listening!!!

**Comment by dudek-marcin** [comment]
Big +1 for this!

**Comment by vitalidze** [comment]
Implemented basic snapping to roads function, written [news](http://traccar.litvak.su/2015/07/14/Snap-to-roads,-new-map-providers-and-translations.html) and [article](http://traccar.litvak.su/features/snap-to-roads.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by peptoni** [comment]
Just downloaded and installed the new version, but "snap to roads" is not working for me...  I see the same straight lines between points...  Am I doing something wrong...?  I am on a Amazon EC2 virtual machine...  Should I have to open some ports for this to work...?

**Comment by vitalidze** [comment]
Lines will be same 'straight' lines. Just the points are snapped for now.

**Comment by peptoni** [comment]
OK!

**Comment by vitalidze** [comment]
Actually I am still thinking about a better way of implementation, maybe will move this to the client side. Right now server makes requests and returns 'snapped' points to the client. Same OSRM service returns the line in some binary format as well, but I doubt it will pass through the GWT RPC. That's why I am thinking about calling of the OSRM service directly from the web browser after positions are loaded from the server side.

**Comment by peptoni** [comment]
Sounds good to me!

**Comment by peptoni** [comment]
This implementation would allow also to snap during the following of a vehicle, real time.

**Comment by ghost** [comment]
Hello,

In French interface "snap to road" is not so close to road :(  (Latest version).

**Comment by vitalidze** [comment]
@waca98 First of all, please do not post your issues on the closed threads. Open new instead.

Related your case with French, I was not able to reproduce it. It works for me in exactly same way as it does for English. Please submit a new issue with the track attached (in GPX format, just do the export).

**Comment by ramlaxmanrimal** [comment]
Snap to road cannot work on chrome, Is there any compatibility issues?

**Comment by vitalidze** [comment]
@ramlaxmanrimal please don't post questions in old threads. As for your question find discussion here #387
