### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fabover** [vitalidze/traccar-web#201]
Hello, some days ago I had to change the conf.cfg file because anton me so indicated after adding support for a new device, and make a new compilation for me. modifications were:
     Rename all http. \* Parameters to web. *
     Rename database.selectDevice to database.selectDevicesAll
     Change database.selectDevicesAll return column name from imei to uniqueId Which in case of default config just mean removing as IMEI

The question is whether these changes can use your version of the web interface. Thank you.

**Comment by vitalidze** [comment]
Actually I haven't time to test it yet, but the following changes to configuration file may work:

1) Change `web.new` from `true` to `false`:

``` xml
<entry key='web.new'>false</entry>
```

2) Add path to the `traccar-web.war` file:

``` xml
<entry key='web.application'>../traccar-web.war</entry>
```

I am not sure to which directory this path is related, but specifying absolute path might work, like:

``` xml
<entry key='web.application'>/optr/traccar/traccar-web.war</entry>
```

**Comment by vitalidze** [comment]
I don't have time right now to test it. But I will do it once the new version with all these changes gets released. I will be on vacation since tomorrow (25.06) up to 06.07.

**Comment by vitalidze** [comment]
I have added instructions for the 3.x version of traccar, please see official guide here: http://traccar.litvak.su/installation.html

**Comment by vitalidze** [comment]
Closed due to inactivity
