### ISSUE TITLE
RESTful API - Some bugs 

### ISSUE THREAD

**Issue by johnnyrlq** [vitalidze/traccar-web#202]
Hello, I am testing some features and I have some observations: 
# CHANGE PASSWORD (settings ->Users)
- Modifying the password of any user logged like ADMIN (with the "Change Password" option) it works.
- Modifying the password of any user logged like MANAGER (with the "Change Password" option) it does not work. The REMOTE CALL PROCEDURE ERROR appears.
# ACCOUNT(settings->Account)

I think the users should not change their "USER" just their "PASSWORD".
# QUESTION

Using the RESTful API or the webUI I can register a new user (with MANAGER privileges), but is it possible to register the user without MANAGER privileges?

Thank you for your help.

**Comment by vitalidze** [comment]
1) Sounds like a bug

2) This is quite subjective, I don't know which is wrong here. It's not clear to me why you should restrict user from changing the username.

3) Right now there is no way to do this. All new users are registered with 'Manager' privilege in current implementation.

**Comment by johnnyrlq** [comment]
1) Ok

2) I agree, is subjetive but I am thinking that when someone get into the system, have to be registered so, the primary information of the account will be the "username" field (Like "email" for Facebook or Gmail), so changing the "username" field should be restricted and if that person need another "username", he have to register again.
Then, the logic should works better.

3) I Undestand

**Comment by vitalidze** [comment]
Fixed 1st issue, written [news](http://traccar.litvak.su/2015/07/14/Snap-to-roads,-new-map-providers-and-translations.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
