### ISSUE TITLE
Hide inactive/offline devices from map

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#205]
Would it be possible/interesting to add an option to hide inactive/offline devices from map?

**Comment by antoniopaisfernandes** [comment]
I second that :)

**Comment by peptoni** [comment]
It could be a "Hide all inactive/offline" option, or a "Hide by device" option

**Comment by vitalidze** [comment]
I thought about both options - hide all and per device setting. The setting
may be in user's preferences. In my mind it looks like that setting for
"all devices" should have higher priority than a per-device setting. What
do you think?

среда, 1 июля 2015 г. пользователь peptoni написал:

> It could be a "Hide all inactive/offline" option, or a "Hide by device"
> option
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/205#issuecomment-117544731
> .

## 

Kind regards, Vitaly Litvak

**Comment by peptoni** [comment]
I agree that "hide all devices" option should have higher priority than per-device setting.
Should you treat "inactive" separate from "offline"...?
I mean: one setting for hiding inactive devices and another for hiding offline devices...

**Comment by peptoni** [comment]
Sorry... I just realized I already asked for this enhacement on #118...

**Comment by vitalidze** [comment]
By "active" you mean selected device? I thought just about "offline"
devices.

четверг, 2 июля 2015 г. пользователь peptoni написал:

> Sorry... I just realized I already asked for this enhacement on #118
> https://github.com/vitalidze/traccar-web/issues/118...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/205#issuecomment-118038308
> .

## 

Kind regards, Vitaly Litvak

**Comment by peptoni** [comment]
Offline would be the devices that are not transmitting.  Devices off.
Inactive would be the devices that don't move for a period of time, but still transmit.  Devices on.

**Comment by vitalidze** [comment]
I see. In current terminology of web UI the "inactive" devices are called
"idle". Well, I don't know whether it's worth to add an option to hide such
devices. But it does not make big difference in implementation means.

четверг, 2 июля 2015 г. пользователь peptoni написал:

> Offline would be the devices that are not transmitting. Devices off.
> Inactive would be the devices that don't move for a period of time, but
> still transmit. Devices on.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/205#issuecomment-118056760
> .

## 

Kind regards, Vitaly Litvak

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html) and [article](http://traccar.litvak.su/features/visibility.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
