### ISSUE TITLE
Raspian no traccar-web.war

### ISSUE THREAD

**Issue by manjoel** [vitalidze/traccar-web#206]
I have the latest version of traccar running an an raspberr Pi but i have no traccar-web.war.

What could I do to solve my problem

**Comment by RobertBenedikt** [comment]
Installation

1) Download latest build from http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war

2) Stop Traccar service.

3) Replace traccar-web.war in Traccar installation folder (/opt/traccar or c:\Program Files\Traccar) with downloaded one. I recommend to do a backup of existing traccar-web.war just in case.

4) Start Traccar service

5) If necessary clear web browser cookies related to your traccar web UI. In chrome this can be done like said here http://superuser.com/questions/548096/how-can-i-clear-cookies-for-a-single-site

**Comment by manjoel** [comment]
the problem is ther is no traccar-web.war in /opt/traccar, ther is only an traccar-server.jar

**Comment by RobertBenedikt** [comment]
when you write <b>/opt/traccar/bin/traccar stop</b> and then <b>/opt/traccar/bin/traccar start</b> so traccar runs?

**Comment by manjoel** [comment]
yes version 3.0

**Comment by RobertBenedikt** [comment]
you're allowed to see hidden files? Maybe somehow accidentally become file <b>traccar-web.war</b> hidden

**Comment by manjoel** [comment]
am think so am su

**Comment by manjoel** [comment]
but i used the installation package?

**Comment by RobertBenedikt** [comment]
Write in the terminal <b>/opt/traccar/bin/traccar stop</b> and then start the traccar command 
<b>/opt/traccar/bin/traccar console</b> You should see where the <b>traccar-web.war</b>

**Comment by vitalidze** [comment]
Current instructions are for 2.x versions of traccar. I didn't got time to
write instructions for 3.x because of still being on vacation. This please
either use 2.x version or wait until I update instructions.

четверг, 2 июля 2015 г. пользователь Robert Benedikt написал:

> Write in the terminal _/opt/traccar/bin/traccar stop_ and then start the
> traccar command
> _/opt/traccar/bin/traccar console_ You should see where the
> _traccar-web.war_
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/206#issuecomment-117840354
> .

## 

Kind regards, Vitaly Litvak

**Comment by vitalidze** [comment]
I have just updated the instructions, which now include steps for updating clean installation of 3.x version. Please check.

**Comment by manjoel** [comment]
it Seems there  is still something what's not working. When I start the traccar in web Interface the window stay's gray, the is no error, but I thing there is something what is not changed.

this is my log

```
SELECT * FROM position WHERE id IN (SELECT positionId FROM device);
 [42102-187] - JdbcSQLException (... < QueryBuilder.java:51 < *:120 < DataManager.java:330 < DataCache.java:36 < ...)
```

2015-07-04 21:14:07  INFO: Starting server...
2015-07-04 21:14:07  INFO: Operating System name: Linux version: 3.18.11-v7+ architecture: arm
2015-07-04 21:14:07  INFO: Java Runtime name: Java HotSpot(TM) Client VM vendor: Oracle Corporation version: 25.0-b70
2015-07-04 21:14:07  INFO: Memory Limit heap: 224mb non-heap: 0mb
2015-07-04 21:14:07  INFO: Version: 3.0-SNAPSHOT

**Comment by vitalidze** [comment]
Log looks good. You should also check out latest `wrapper.log` file for error messages.

Have you cleaned up cookies?

Have you tried accessing same server from another machine/web browser?

**Comment by manjoel** [comment]
Hi, 
I did find my error, in Firefox there is no problem, but under explorer nothing is showed.

**Comment by vitalidze** [comment]
Sounds like a same issue with browser cache/cookies. Does the [demo site](https://d.traccar.litvak.su) work for you in the internet explorer?

**Comment by mechanic98** [comment]
Hey guys
I traccar third version was installed. I have done all the above steps.
But I faced Currently enter the address with the following message:
http://62.60.138.28:8082/
this is my new traccar.xml :

---

<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

```
<!-- SERVER CONFIG -->

<entry key='web.enable'>true</entry>
<entry key='web.port'>8082</entry>
<entry key='web.path'>/opt/traccar/web</entry>
<entry key='web.old'>true</entry>
<entry key='web.application'>/opt/traccar/traccar-web.war</entry>

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>

<entry key='logger.enable'>true</entry>
<entry key='logger.level'>all</entry>
<entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

<!-- DATABASE CONFIG -->

<entry key='database.driver'>org.h2.Driver</entry>
<entry key='database.url'>jdbc:h2:/opt/traccar/data/database</entry>
<entry key='database.user'>sa</entry>
<entry key='database.password'></entry>
<entry key='database.checkTable'>traccar</entry>

<entry key='database.createSchema'>
    CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(1024) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    hashedPassword VARCHAR(1024) NOT NULL,
    salt VARCHAR(1024) DEFAULT '' NOT NULL,
    readonly BOOLEAN DEFAULT false NOT NULL,
    admin BOOLEAN DEFAULT false NOT NULL,
    map VARCHAR(1024) DEFAULT 'osm' NOT NULL,
    language VARCHAR(1024) DEFAULT 'en' NOT NULL,
    distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL,
    speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL,
    latitude DOUBLE DEFAULT 0 NOT NULL,
    longitude DOUBLE DEFAULT 0 NOT NULL,
    zoom INT DEFAULT 0 NOT NULL);

    CREATE TABLE device (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(1024) NOT NULL,
    uniqueId VARCHAR(256) NOT NULL UNIQUE,
    status VARCHAR(1024),
    lastUpdate TIMESTAMP,
    positionId INT,
    dataId INT);

    CREATE TABLE user_device (
    userId INT NOT NULL,
    deviceId INT NOT NULL,
    `read` BOOLEAN DEFAULT true NOT NULL,
    `write` BOOLEAN DEFAULT true NOT NULL,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (deviceId) REFERENCES device(id) ON DELETE CASCADE);

    CREATE INDEX user_device_user_id ON user_device(userId);

    CREATE TABLE position (
    id INT PRIMARY KEY AUTO_INCREMENT,
    protocol VARCHAR(1024),
    deviceId INT NOT NULL,
    serverTime TIMESTAMP NOT NULL,
    deviceTime TIMESTAMP NOT NULL,
    fixTime TIMESTAMP NOT NULL,
    valid BOOLEAN NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    altitude DOUBLE NOT NULL,
    speed DOUBLE NOT NULL,
    course DOUBLE NOT NULL,
    address VARCHAR(1024),
    other VARCHAR(8192) NOT NULL,
    FOREIGN KEY (deviceId) REFERENCES device(id) ON DELETE CASCADE);

    CREATE TABLE data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    protocol VARCHAR(1024),
    deviceId INT NOT NULL,
    serverTime TIMESTAMP NOT NULL,
    deviceTime TIMESTAMP NOT NULL,
    other VARCHAR(8192) NOT NULL,
    FOREIGN KEY (deviceId) REFERENCES device(id));

    ALTER TABLE device ADD
    FOREIGN KEY (positionId) REFERENCES `position`(id);

    ALTER TABLE device ADD
    FOREIGN KEY (dataId) REFERENCES data(id);

    CREATE TABLE server (
    id INT PRIMARY KEY AUTO_INCREMENT,
    registration BOOLEAN NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    zoom INT NOT NULL);

    CREATE TABLE traccar (
    id INT PRIMARY KEY AUTO_INCREMENT);
</entry>

<entry key='database.selectServers'>
    SELECT * FROM server;
</entry>

<entry key='database.insertServer'>
    INSERT INTO server (registration, latitude, longitude, zoom)
    VALUES (:registration, :latitude, :longitude, :zoom);
</entry>

<entry key='database.updateServer'>
    UPDATE server SET registration = :registration WHERE id = :id;
</entry>

<entry key='database.loginUser'>
    SELECT * FROM user
    WHERE email = :email;
</entry>

<entry key='database.selectUsersAll'>
    SELECT * FROM user;
</entry>

<entry key='database.insertUser'>
    INSERT INTO user (name, email, hashedPassword, salt, admin)
    VALUES (:name, :email, :hashedPassword, :salt, :admin);
</entry>

<entry key='database.updateUser'>
    UPDATE user SET name = :name, email = :email, admin = :admin
    WHERE id = :id;
</entry>

<entry key='database.updateUserPassword'>
    UPDATE user SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
</entry>

<entry key='database.deleteUser'>
    DELETE FROM user WHERE id = :id;
</entry>

<entry key='database.getPermissionsAll'>
    SELECT userId, deviceId FROM user_device;
</entry>

<entry key='database.selectDevicesAll'>
    SELECT * FROM devices;
</entry>

<entry key='database.selectDevices'>
    SELECT * FROM device d INNER JOIN user_device ud ON d.id = ud.deviceId WHERE ud.userId = :userId;
</entry>

<entry key='database.insertDevice'>
    INSERT INTO device (name, uniqueId) VALUES (:name, :uniqueId);
</entry>

<entry key='database.updateDevice'>
    UPDATE device SET name = :name, uniqueId = :uniqueId WHERE id = :id;
</entry>

<entry key='database.deleteDevice'>
    DELETE FROM device WHERE id = :id;
</entry>

<entry key='database.linkDevice'>
    INSERT INTO user_device (userId, deviceId) VALUES (:userId, :deviceId);
</entry>

<entry key='database.selectPositions'>
    SELECT * FROM position WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to;
</entry>

<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other);
</entry>

<entry key='database.selectLatestPositions'>
    SELECT * FROM position WHERE id IN (SELECT positionId FROM device);
</entry>

<entry key='database.updateLatestPosition'>
    UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;
</entry>

<!-- PROTOCOL CONFIG -->

<entry key='detector.port'>5000</entry>
<entry key='gps103.port'>5001</entry>
<entry key='tk103.port'>5002</entry>
<entry key='gl100.port'>5003</entry>
<entry key='gl200.port'>5004</entry>
<entry key='t55.port'>5005</entry>
<entry key='xexun.port'>5006</entry>
<entry key='xexun.extended'>false</entry>
<entry key='totem.port'>5007</entry>
<entry key='enfora.port'>5008</entry>
<entry key='meiligao.port'>5009</entry>
<entry key='maxon.port'>5010</entry>
<entry key='suntech.port'>5011</entry>
<entry key='progress.port'>5012</entry>
<entry key='h02.port'>5013</entry>
<entry key='jt600.port'>5014</entry>
<entry key='ev603.port'>5015</entry>
<entry key='v680.port'>5016</entry>
<entry key='pt502.port'>5017</entry>
<entry key='tr20.port'>5018</entry>
<entry key='navis.port'>5019</entry>
<entry key='meitrack.port'>5020</entry>
<entry key='skypatrol.port'>5021</entry>
<entry key='gt02.port'>5022</entry>
<entry key='gt06.port'>5023</entry>
<entry key='megastek.port'>5024</entry>
<entry key='navigil.port'>5025</entry>
<entry key='gpsgate.port'>5026</entry>
<entry key='teltonika.port'>5027</entry>
<entry key='mta6.port'>5028</entry>
<entry key='mta6can.port'>5029</entry>
<entry key='tlt2h.port'>5030</entry>
<entry key='syrus.port'>5031</entry>
<entry key='wondex.port'>5032</entry>
<entry key='cellocator.port'>5033</entry>
<entry key='galileo.port'>5034</entry>
<entry key='ywt.port'>5035</entry>
<entry key='tk102.port'>5036</entry>
<entry key='intellitrac.port'>5037</entry>
<entry key='xt7.port'>5038</entry>
<entry key='wialon.port'>5039</entry>
<entry key='carscop.port'>5040</entry>
<entry key='apel.port'>5041</entry>
<entry key='manpower.port'>5042</entry>
<entry key='globalsat.port'>5043</entry>
<entry key='atrack.port'>5044</entry>
<entry key='pt3000.port'>5045</entry>
<entry key='ruptela.port'>5046</entry>
<entry key='topflytech.port'>5047</entry>
<entry key='laipac.port'>5048</entry>
<entry key='aplicom.port'>5049</entry>
<entry key='aplicom.can'>false</entry>
<entry key='gotop.port'>5050</entry>
<entry key='sanav.port'>5051</entry>
<entry key='gator.port'>5052</entry>
<entry key='noran.port'>5053</entry>
<entry key='m2m.port'>5054</entry>
<entry key='osmand.port'>5055</entry>
<entry key='easytrack.port'>5056</entry>
<entry key='taip.port'>5057</entry>
<entry key='khd.port'>5058</entry>
<entry key='piligrim.port'>5059</entry>
<entry key='stl060.port'>5060</entry>
<entry key='cartrack.port'>5061</entry>
<entry key='minifinder.port'>5062</entry>
<entry key='haicom.port'>5063</entry>
<entry key='eelink.port'>5064</entry>
<entry key='box.port'>5065</entry>
<entry key='freedom.port'>5066</entry>
<entry key='telik.port'>5067</entry>
<entry key='trackbox.port'>5068</entry>
<entry key='visiontek.port'>5069</entry>
<entry key='orion.port'>5070</entry>
<entry key='riti.port'>5071</entry>
<entry key='ulbotech.port'>5072</entry>
<entry key='tramigo.port'>5073</entry>
<entry key='tr900.port'>5074</entry>
<entry key='ardi01.port'>5075</entry>
<entry key='xt013.port'>5076</entry>
<entry key='autofon.port'>5077</entry>
<entry key='gosafe.port'>5078</entry>
<entry key='autofon45.port'>5079</entry>
<entry key='bce.port'>5080</entry>
<entry key='xirgo.port'>5081</entry>
<entry key='calamp.port'>5082</entry>
<entry key='mtx.port'>5083</entry>
<entry key='tytan.port'>5084</entry>
<entry key='avl301.port'>5085</entry>
<entry key='castel.port'>5086</entry>
```

## </properties>

Please help me
Thank you for your help

**Comment by vitalidze** [comment]
Are you sure you have the file located here: `/opt/traccar/traccar-web.war`?

**Comment by mechanic98** [comment]
Yes, I'm sure
This is a screenshot of the traccar place an traccar-web.war
![traccar](https://cloud.githubusercontent.com/assets/13448402/8825174/5411c332-3092-11e5-8012-5147a63e652f.png)

## and this is my wrapper.log.20150722 :

STATUS | wrapper  | 2015/07/22 11:52:04 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/07/22 11:52:04 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/07/22 11:52:04 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/07/22 11:52:04 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/07/22 11:52:04 |
STATUS | wrapper  | 2015/07/22 11:52:05 | Launching a JVM...
INFO   | jvm 1    | 2015/07/22 11:52:07 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/07/22 11:52:17 | 2015-07-22 11:52:17.185:INFO:oejs.Server:jetty-8.1.17.v20150415
INFO   | jvm 1    | 2015/07/22 11:52:17 | 2015-07-22 11:52:17.497:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082
STATUS | wrapper  | 2015/07/22 11:53:36 | TERM trapped.  Shutting down.
WARN   | wrapper  | 2015/07/22 11:53:36 | JVM exited unexpectedly while stopping the application.
INFO   | jvm 1    | 2015/07/22 11:53:37 | 2015-07-22 11:53:36.789:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/api,null}
STATUS | wrapper  | 2015/07/22 11:53:37 | <-- Wrapper Stopped
STATUS | wrapper  | 2015/07/22 12:02:06 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/07/22 12:02:06 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/07/22 12:02:06 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/07/22 12:02:06 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/07/22 12:02:06 |
STATUS | wrapper  | 2015/07/22 12:02:07 | Launching a JVM...
INFO   | jvm 1    | 2015/07/22 12:02:07 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/07/22 12:02:08 | 2015-07-22 12:02:08.732:INFO:oejs.Server:jetty-8.1.17.v20150415
INFO   | jvm 1    | 2015/07/22 12:02:08 | 2015-07-22 12:02:08.767:INFO:oejw.WebInfConfiguration:Extract jar:file:/opt/traccar/traccar-web.war!/ to /tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp
INFO   | jvm 1    | 2015/07/22 12:02:08 | 2015-07-22 12:02:08.844:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
INFO   | jvm 1    | 2015/07/22 12:02:08 | 2015-07-22 12:02:08.913:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082

---

**Comment by vitalidze** [comment]
You configuration and server log looks good. Do you have something in this folder: `/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp` ?

**Comment by mechanic98** [comment]
no i don't have

![traccar2](https://cloud.githubusercontent.com/assets/13448402/8825693/3e5a9cea-3096-11e5-8bcf-713838c66d05.png)

**Comment by vitalidze** [comment]
That's weird. There should be something like this:

```
/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-# ls -la
total 12
drwxr-xr-x 3 root root 4096 Jul 14 20:37 .
drwxrwxrwt 6 root root 4096 Jul 22 12:54 ..
drwxr-xr-x 8 root root 4096 Jul 14 20:37 webapp
/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-# ls webapp/
META-INF  WEB-INF  img  js  m  traccar  traccar.html
```

Maybe you are running out of space?

**Comment by mechanic98** [comment]
Thank you for helping me
I'm really confused I do not know where is the problem
Can I send you username and password for the server?

**Comment by vitalidze** [comment]
You can send it by email. I can look only today's evening or tomorrow's morning.

**Comment by mechanic98** [comment]
Thanks a lot
I sent my server details to e-mail

**Comment by vitalidze** [comment]
I received them.

**Comment by vitalidze** [comment]
For some reason there was a damaged `traccar-web.war` file.

**Comment by amet123** [comment]
i also try same steps but afer that my user merge under admin and already user id hidden and unable to create same user

even previous data lose

**Comment by vitalidze** [comment]
@amet123 it sounds like an issue with 3.3 installation. I recommend to either install it over 3.2 or follow instructions in #510 #524 

P.S. why are you posting your question to a closed old issue? It's better to create a new one instead. You can refer to this issue if necessary.

**Comment by benchaa** [comment]
hello,
for the 4.1 version traccar, there is a solution ?
