### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by BigByteFP** [vitalidze/traccar-web#207]
Hi,
it would nice to that of an additional icon to show markerIcon for a chosen value in the filed XML other.

Thank you.

Francesco P.

**Comment by vitalidze** [comment]
Please give an example. If you seen it in another system then please give a
screenshot/link.

четверг, 2 июля 2015 г. пользователь Francesco Pezzella написал:

> Hi,
> it would nice to that of an additional icon to show markerIcon for a
> chosen value in the filed XML other.
> 
> Thank you.
> 
> Francesco P.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/207.

## 

Kind regards, Vitaly Litvak

**Comment by BigByteFP** [comment]
Ok I try to explain.
The interface should allow choose an XML tag within the field other (table positions) example : <battery> 2618 </ battery>
select a comparison operator  (<,>, =,<=,>=) : <
enter a value : 1000
if the comparision is true then show info on markerIcon until it return false

Francesco P.

**Comment by vitalidze** [comment]
Why doesn't the "sensors" function with custom intervals work for your
needs? You need some icon?

четверг, 2 июля 2015 г. пользователь Francesco Pezzella написал:

> Ok I try to explain.
> The interface should allow choose an XML tag within the field other (table
> positions) example : 2618 </ battery>
> select a comparison operator (<,>, =,<=,>=) : <
> enter a value : 1000
> if the comparision is true then show info on markerIcon until it return
> false
> 
> Francesco P.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/207#issuecomment-118029427
> .

## 

Kind regards, Vitaly Litvak

**Comment by ghost** [comment]
It is possible that these "sensors" generate "events", for example to control a state io2 1 or 0, and generate email, such as "panic button" and check the status of io1 to contact on or off?

**Comment by BigByteFP** [comment]
customize with UI one or two to be chosen by the user info without knowing if they are supported or not, in the above example we could have a markerIcon like this

(example with cut and paste)
![cattura](https://cloud.githubusercontent.com/assets/12140110/8479093/cac2fb76-20d5-11e5-99ef-cf67e73820a3.PNG)

**Comment by vitalidze** [comment]
Right now it is not possible to generate events from sensors values. Most
probably it will be added in future.

Regarding icons I think the most convenient way is to define such icons for
custom intervals along with the text values (or instead of them).

четверг, 2 июля 2015 г. пользователь Francesco Pezzella написал:

> customize with UI one or two to be chosen by the user info without knowing
> if they are supported or not, in the above example we could have a
> markerIcon like this
> 
> (example with cut and paste)
> [image: cattura]
> https://cloud.githubusercontent.com/assets/12140110/8479093/cac2fb76-20d5-11e5-99ef-cf67e73820a3.PNG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/207#issuecomment-118048394
> .

## 

Kind regards, Vitaly Litvak

**Comment by ghost** [comment]
Try to capture the sensor value io2 from outside with a php ($ query = "SELECT \* FROM` `other` positions`WHERE LIKE '% <io2> 1 </ io2>%' ORDER BY` time` ASC LIMIT 0.1 ";) to send an automatic mail when the event happens.
But I see that I ceunta making the request at every moment and that will put the database slow significantly, is not the most practical, you could suggest another way?

**Comment by vitalidze** [comment]
This is out of scope of this feature request. Please create a separate
issue with your questions.

четверг, 2 июля 2015 г. пользователь Mikelord2 написал:

> Try to capture the sensor value io2 from outside with a php ($ query =
> "SELECT \* FROMotherpositions WHERE LIKE '% 1 </ io2>%' ORDER BYtime ASC
> LIMIT 0.1 ";) to send an automatic mail when the event happens.
> But I see that I ceunta making the request at every moment and that will
> put the database slow significantly, is not the most practical, you could
> suggest another way?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/207#issuecomment-118063748
> .

## 

Kind regards, Vitaly Litvak

**Comment by gsiotas** [comment]
+1

**Comment by ramlaxmanrimal** [comment]
If it shows the direction, that would be great!

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2016/06/04/Sensor-text-color-and-icon,-bug-fixes.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
