### ISSUE TITLE
Capture logic gates values and thereby generate events

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#208]
Try to capture the sensor value io2 from outside with a php ($ query = "SELECT \* FROMotherpositions WHERE LIKE '% 1 </ io2>%' ORDER BYtime ASC LIMIT 0.1 ";) to send an automatic mail when the event happens.
But I see that I ceunta making the request at every moment and that will put the database slow significantly, is not the most practical, you could suggest another way?

**Comment by vitalidze** [comment]
First of all looks like your query can miss some events in theory - for example when multiple events come  at the time you poll the database.

Then, I don't think it will do a much load on the database if you have indexes both on `other` and `time` fields in `positions` table. You can check how it scales when number of rows grows. I think it should be good for a reasonable amount of rows.

If I would implement it for now it would took the same approach as it does for odometer updating and geo-fences events recording - it just loads all positions every minute and scans them one by one.

I believe the best approach would be to generate events right on the backend side - i.e. have some kind of pipeline for newly received positions. This is not possible in current implementation.
