### ISSUE TITLE
Option to remove label from icon

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#209]
Anyone else finds interesting to add an option to remove the label under the icons?
My icons include ID info already.  It could save in processing time also.
![screen shot 2015-07-04 at 17 44 24](https://cloud.githubusercontent.com/assets/11501146/8508532/98dbbf80-2274-11e5-877b-d833cd25d55c.png)

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
