### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#210]
Hi Vitaly,

I think it is time for next step in evolving of traccar-web. 
Could you create new branch with new structure (page, popup etc.) from where could be called generating reports. I would like to work on reports and I need from where to start. 

mpele

**Comment by vitalidze** [comment]
I think it should be started this way:

1) Add a button right to the 'Import / Export' and call it 'Reports' or 'Other reports'. It should be a drop-down button like 'Import / Export'

2) Once report is selected there should be some kind of toolbar with 'Recalculate' button at the top of screen. At the center of the report screen there should be report body and at the bottom there should be a 'Close' and maybe 'Export to ...' buttons (like export to PDF, XLS)

3) Report should have a new service called 'ReportService'.

What do you think?

**Comment by mpele** [comment]
I think it would be cleaner to be on separate page (or big popup). There
should be lot of space for some settings, parameters etc. I wouldn't put it
on overcrowded line like a patch.

The idea is to server prepare the report and to "give it" to the user.
Depending to the chosen settings the user would get html, pdf, or some
other printable format.

Definitely there is need for new service and the first report, for example,
could be the current locations of all devices.

**Comment by vitalidze** [comment]
Actually I meant the 'big' popup opened from a toolbar at the bottom.

I think it should be possible to view reports directly in the web interface. From my point of view this should be a starting point. Then it can be extended with other formats.

So, do you want me to implement the first report somehow and then someone (you?) will do the others?

**Comment by mpele** [comment]
I do not have a lot experience in gwt, especially in uiBinder, so I would
appreciate if the first step is done by you.

**Comment by dudek-marcin** [comment]
Great idea, if the first report and gui for them will be implemented clearly and described respectively I can help with developing next ones too.

**Comment by mpele** [comment]
I have started to work on the reports, but unfortunately I do not have time for it. The rough draft could be found on branch mdev .

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
