### ISSUE TITLE
how to upgrade safely from 2.x to 3.x  ?

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#211]
I think the title says it all.
As to migrate 3.x and not die trying?

**Comment by vitalidze** [comment]
Have you seen updated instructions here: http://traccar.litvak.su/installation.html ? It should work for migration.

**Comment by ghost** [comment]
if I have looked but can not find my file "traccar.xml" settings in / opt / traccar / config /
I only see "traccar.cgf" and the lines to be modified achievement not associate with the recommendations in installation, help me?

**Comment by elRadix** [comment]
you need to download the 3.0 traccar files move you old traccar to traccar_old and install the files and follow the instructions for the migration.

https://www.traccar.org/download/

**Comment by ghost** [comment]
Definitely something I missed in the process :( finally make an installation of version 3.x I have two BD old with all the data and news of traccar 3.x, not as dump data from a database the other, the tables have some variations. :(

**Comment by vitalidze** [comment]
Didn't understood what your problem is now. You want to migrate old data to the new database?

**Comment by ghost** [comment]
yes  :)

**Comment by vitalidze** [comment]
Are you using default h2 database?

**Comment by ghost** [comment]
Nope,  Mysql 5.x

**Comment by vitalidze** [comment]
I think the following might work:

1) Stop traccar service
2) Take a backup of old traccar database (version 2.x).
3) Restore that backup on a new traccar database (version 3.x).
4) Start service

If you have updated XML configuration file according to instructions you should get a working instance of traccar 3.x with your old data and web UI mod installed.

**Comment by vitalidze** [comment]
Note that you will lose all data from 3.x version when you do a restore from 2.x

**Comment by ghost** [comment]
yes , thanks you , for your help.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10438858/8579828/445e6662-258d-11e5-9af3-b8a4aeaf121a.png)

duplicate tables  :(

**Comment by vitalidze** [comment]
The `position` table is the one from "original" database schema. It should be safe to delete it. I don't know what is the `positions_process` table.

**Comment by ghost** [comment]
Sorry for not responding so quickly, that table to another process that is conducted with traccar, not linked to any other single purpose of having another parallel process, finally I did was install a new traccar but in version 3, I see that there are few options in the new traccar, for example geofences and other settings with the users, icons for the units.

**Comment by vitalidze** [comment]
So, does it work for you now?

**Comment by ghost** [comment]
If the version 3 works well, but how I can do to have the same configuration options, Geofences etc ....?

**Comment by vitalidze** [comment]
You need to install the `traccar-web.war` over the version 3 using the official instructions http://traccar.litvak.su/installation.html

**Comment by ghost** [comment]
I did as there says, but the result is that I have two traccar interface with all the options, the ideal would have been to have the interface traccar 3 and options for version 2, version 3 :) download from "1) Download latest build from http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war "

but I see it's the same link of the version 2 is ok?

Thank you a lot for your help on this     :)

**Comment by ghost** [comment]
to use the MySQL database is the same configuration as the version 2?

"<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/[DATABASE]?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8</entry>
<entry key='database.user'>[USER]</entry> 
<entry key='database.password'>[PASSWORD]</entry>"

**Comment by vitalidze** [comment]
1) `traccar-web.war` from version 2 can be used with version 3. You need to follow instructions mentioned in my previous message.

2) Yes, the MySQL configuration is same.
