### ISSUE TITLE
Traccar 3.0 Linux 64

### ISSUE THREAD

**Issue by wagnerdracha** [vitalidze/traccar-web#213]
Hi

I downloaded the latest version of traccar, but don't exist "traccar-web.war" to replace. So isn't necessary replace?

What i do?

Thank's

**Comment by vitalidze** [comment]
Please follow official instructions for 3.x version http://traccar.litvak.su/installation.html

**Comment by wagnerdracha** [comment]
I followed these instructions, but it worked. The browser went white.

**Comment by vitalidze** [comment]
Have you cleaned up the browser cache? Also it's worth to try different machine/browser.

**Comment by wagnerdracha** [comment]
Ok, I'll try again. If I can not, I'll post the step by step what I did. Thanks.

**Comment by wagnerdracha** [comment]
It worked. Thanks!
