### ISSUE TITLE
admin tools improvement

### ISSUE THREAD

**Issue by daniloadur** [vitalidze/traccar-web#214]
Hi Vitaly, 

The web interface is getting better and better....you have been doing a great job. congratulations for that.

About the admiminstration of user and devices, allow me suggest some improvement in structure and rules to would be very very usefull (and is close to what we have in open gts). Is something to think about after you vacations,allow me explain:

If possible I would like to have 3 levels, Admin, Manager, User

***Admin can create Managers and set  max number of devices every manager can distribute to its users

**Managers can create User and set the max number of devices the user can have but the total number of devices distributed by manager for all its users can not  exceed the max number of devices admin set to this manager.

*Users can just add devices baser in max number of devices that manger set for it.

![admin](https://cloud.githubusercontent.com/assets/4789505/8620998/97814fc2-26f9-11e5-897a-eecfc63d0fad.jpg)

Does it make sense? Do you you think is this feasible?

Cheers.

**Comment by wolfbgn** [comment]
At the moment USER is able to change maximum number of devices and expiration date.
 It has to be USER with limited rights not to be able to change these values.
 I dont know if I am right but I think that USERS should not be able to change those values
Sorry for duplicate comment.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
