### ISSUE TITLE
sending Sms

### ISSUE THREAD

**Issue by manjoel** [vitalidze/traccar-web#217]
is there a possibility to add an Sms support, to send Sms with an 3g Stick.
what is the reason for this. I have only an dynamic public ip and if the ip changes taccar should send an configuration sms the with the new ip to the gps device, because most devices don't have the possiblity to make an dns lookup.

And i think sms reports are faster than emails and pushbullet.

**Comment by vitalidze** [comment]
Your case looks too custom. Why can't you have a static public IP address?

As for the notifications, it is possible to add SMS in theory. This requires some third party provider, I don't know which one to choose.

**Comment by manjoel** [comment]
Cause of the Price, the Server is only to use with Family and some friends. And 30€ per month is a lot for this.

third Party provider's? do you mean something like this http://smslib.org/

I'm trying to do something like this http://www.kossboss.com/app---public-ip-change-to-email---linux and trying to add the possibility to send at commands

**Comment by vitalidze** [comment]
You can rent a VPS from [digital ocean](http://digitalocean.com) for $5 per month. It provides you with static public IP address and a virtual linux server with SSD drive. My demo version of traccar is running on such server. (I am not afiliated anyhow with DO, it's just an awesome company providing cheap virtual machines).

By third party provider I mean some company that allows sending of SMS through some web service API (like https://www.twilio.com/sms/pricing). From brief looking on that library (http://smslib.org) it allows you to send SMS through a GSM modem connected to the machine running the application. I never thought about such option.

**Comment by Jeferex** [comment]
I think twilio is the best option since most of people can't connect a GSM modem to the servers running traccar-web.

Another option if you want a VPS, you can get a free year of Amazon Web Services (http://aws.amazon.com)

**Comment by mpele** [comment]
If you have 3g stick the eseast way to what you want is to use combination
of python and gammu.
The concept is that you have some free hosting that would report the ip
address of the request (php script with one line of code), the python
periodicly check if the reported address is the same and if it is then send
sms to inform/reconfigue.
I have some similar system for the testing purposes.
Be aware that it could be expensive because of price of sms,  and check if
your provider have some service for free sms's.

**Comment by flyjodel** [comment]
I now let traccar run on a Raspberry Pi 2, and it works very well.
I've also bought a 3G key Huawei E220 and it works very well for sending SMS via AT commands. You may look at : https://myraspberryandme.wordpress.com/2013/09/13/short-message-texting-sms-with-huawei-e220/
and for further SMS service : RaspiSMS using Gammu library. It is not 100% working yet but it seems to be a good api.
In France I got a contract 24/24 illimited calls + illimited SMS for 1€/month
