### ISSUE TITLE
How wan I stop traccar-server on RPi

### ISSUE THREAD

**Issue by flyjodel** [vitalidze/traccar-web#220]
Hi,

I have installed traccar on a Raspberry Pi 2 following this procedure : http://www.forum-raspberrypi.de/Thread-tutorial-tracking-server-mit-traccar

I now want to update the webserver to Litvak's one, but I need to stop the "service". How can I do that ?

thank you
Michel

**Comment by vitalidze** [comment]
I think you can just replace the `traccar-web.war` file and then reboot your RPi2

**Comment by flyjodel** [comment]
yes you're right... But I was hoping for some java instruction to kill the process and restart traccar within Linux, without the need to reboot, because I still have some strange issues for the time being
