### ISSUE TITLE
VPS Server

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#221]
My question is, what caractersisticas should have a VPS server to accommodate traccar and see my fleet of 50 trucks?

any suggestions?

**Comment by vitalidze** [comment]
For recording purpose the cheapest instance from Digital Ocean (512 MB RAM, 1 single core) should be enough. Then it depends on the kind of tasks you want to do on the web UI. For example if you would like to see all tracks of all units by several users at the same time it may not fit in RAM.

Also I recommend to use MySQL database from the beginning.
