### ISSUE TITLE
issue on starting tracar service on linux server

### ISSUE THREAD

**Issue by seban1** [vitalidze/traccar-web#226]
Hi,

I Uploaded file to server. installed the software by running the traccar.run file..
Then running the traccar start file gave following errors.

INFO | jvm 4 | 2015/07/29 07:18:09 | WrapperManager Error: Exiting
JVM...
ERROR | wrapper | 2015/07/29 07:18:09 | JVM exited while loading the
application.
STATUS | wrapper | 2015/07/29 07:18:14 | Launching a JVM...
INFO | jvm 5 | 2015/07/29 07:18:14 | WrapperManager: Initializing...
INFO | jvm 5 | 2015/07/29 07:18:15 | WrapperManager Error: Failed to
connect to the Wrapper at port 32,000 by binding to any ports in the
range 31,000 to 31,999. Cause: java.net.BindException: Cannot assign
requested address
INFO | jvm 5 | 2015/07/29 07:18:15 | WrapperManager Error: Exiting
JVM...
ERROR | wrapper | 2015/07/29 07:18:15 | JVM exited while loading the
application.
FATAL | wrapper | 2015/07/29 07:18:15 | There were 5 failed launches in
a row, each lasting less than 300 seconds. Giving up.
FATAL | wrapper | 2015/07/29 07:18:15 | There may be a configuration
problem: please check the logs.
STATUS | wrapper | 2015/07/29 07:18:15 | <-- Wrapper Stopped

What could be the problem..?
can anyone help please...
TIA...

**Comment by vitalidze** [comment]
YLooks like something is wrong with networking on your VPS. I don't think
it is related with web UI mod so it's better to ask on traccar forum
https://www.traccar.org/forums/

среда, 29 июля 2015 г. пользователь seban1 написал:

> Hi,
> 
> I Uploaded file to server. installed the software by running the
> traccar.run file..
> Then running the traccar start file gave following errors.
> 
> INFO | jvm 4 | 2015/07/29 07:18:09 | WrapperManager Error: Exiting
> JVM...
> ERROR | wrapper | 2015/07/29 07:18:09 | JVM exited while loading the
> application.
> STATUS | wrapper | 2015/07/29 07:18:14 | Launching a JVM...
> INFO | jvm 5 | 2015/07/29 07:18:14 | WrapperManager: Initializing...
> INFO | jvm 5 | 2015/07/29 07:18:15 | WrapperManager Error: Failed to
> connect to the Wrapper at port 32,000 by binding to any ports in the
> range 31,000 to 31,999. Cause: java.net.BindException: Cannot assign
> requested address
> INFO | jvm 5 | 2015/07/29 07:18:15 | WrapperManager Error: Exiting
> JVM...
> ERROR | wrapper | 2015/07/29 07:18:15 | JVM exited while loading the
> application.
> FATAL | wrapper | 2015/07/29 07:18:15 | There were 5 failed launches in
> a row, each lasting less than 300 seconds. Giving up.
> FATAL | wrapper | 2015/07/29 07:18:15 | There may be a configuration
> problem: please check the logs.
> STATUS | wrapper | 2015/07/29 07:18:15 | <-- Wrapper Stopped
> 
> What could be the problem..?
> can anyone help please...
> TIA...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/226.

## 

Kind regards, Vitaly Litvak
