### ISSUE TITLE
Вопросы по настройке traccar-web

### ISSUE THREAD

**Issue by tehnoinstyle** [vitalidze/traccar-web#228]
Перенёс из темы https://github.com/vitalidze/traccar-web/issues/new

**Comment by tehnoinstyle** [comment]
Зарегистрировался на Pushbullet.
В настройках вставил Токен, Тест выдаёт ошибку:

![push](https://cloud.githubusercontent.com/assets/9967078/9108862/d1f334e0-3c39-11e5-9e5d-5d8f01bbd89a.png)

**Comment by tehnoinstyle** [comment]
На моём смартфоне я должен установить Pushbullet (с другой учеткой в Pushbullet)?

И в настройках учетки для Трассар, добавить учетку на смартфоне?

**Comment by vitalidze** [comment]
А точно он из: Settings >> Access Token из профиля?

Я только что проверил свой, у меня работает. Если есть уверенность в правильности token'а нужно смотреть в логи приложения в `logs/warpper.xx.log`

P.S. лучше уберите скриншот, т.к. ваш ключ доступа к сервису теперь доступен всем.

**Comment by vitalidze** [comment]
Почитайте про pushbullet на их сайте. Там подробно описано как это работает.

**Comment by tehnoinstyle** [comment]
Access Token из профиля

![wrapper log 20150806](https://cloud.githubusercontent.com/assets/9967078/9108972/b329e2d8-3c3a-11e5-97cf-3f25c5880cc2.png)

**Comment by vitalidze** [comment]
Это ошибка авторизации. Проверяйте token или попробуйте другой.

**Comment by tehnoinstyle** [comment]
Переавторизовался с той же учеткой, Тест прошел.

А вот как далее пользоваться, пока не пойму.
Как связать Приложение на Андроиде, и Трассар?

**Comment by vitalidze** [comment]
Через электронную почту должно сработать. На телефоне нужно авторизоваться с электронной почтой такой как в учетной записи в traccar. Это и есть адрес, по которому отправляются уведомления.

**Comment by tehnoinstyle** [comment]
Вроде что-то настроил, с сайта тестовые сообщения отправил на телефон - приходят, но только молча. Их можно увидеть, только открыв приложение. Или я что-то не до-настроил?

**Comment by vitalidze** [comment]
Когда я тестировал на iPhone мне приходили push-уведомления. Где-то в настройках телефона и/или приложения нужно разрешить приложению отправлять уведомления.

**Comment by tehnoinstyle** [comment]
Почитал http://4pda.ru/forum/index.php?showtopic=444653&st=200
переустановил приложение на телефоне, заработало.
Звуки издает, как и при пуш-сообщениях от Синоложи. В общем - работает, буду разбираться дальше.

В Глобальных настройках, время обновления 15000 это в ms? Т.е. 15 секунд?

**Comment by vitalidze** [comment]
Да, время в миллисекундах, т.е. 15000=15 секунд

**Comment by tehnoinstyle** [comment]
Вот по этой вкладке:
Период вывода времени - это время чего?
С ост. разобрался.
![default](https://cloud.githubusercontent.com/assets/9967078/9113259/38b43eaa-3c5c-11e5-995b-da3aac415d47.png)

**Comment by vitalidze** [comment]
Это на треке, каждые Х (в данном случае 10) минут будет подписываться время. Нужно чтобы быстро понять направление движения.

**Comment by tehnoinstyle** [comment]
Какое время выставлять? Или это среднее?

**Comment by vitalidze** [comment]
Это интервал, например если трек построен с 17:05 по 18:00, то время будет под точками 17:05, 17:15, ..., 17:55 в случае если 10 минут выставлено. Если выставить 30 минут, то будет только под 17:05 и 17:35 в том же случае.

**Comment by tehnoinstyle** [comment]
Ага, понял, и по треку вижу. Спасибо.

Но батарея на телефоне быстро садится.

И вопрос по RESTful API
Или это только с 3 версии? Если да, как можно обновиться до 3 версии?
Нужно ждать готовый пакет?

**Comment by vitalidze** [comment]
@tehnoinstyle, вопрос еще актуален?

**Comment by tehnoinstyle** [comment]
Да, жду обновлений сервера для Синоложи.

2015-09-28 21:58 GMT+03:00 Vitaly Litvak notifications@github.com:

**Comment by vitalidze** [comment]
@tehnoinstyle есть RESTful API в моей модификации веб интерфейса traccar (http://traccar.litvak.su/features/rest-api.html), который доступен и в версиях 2.х и 3.х. А в оригинальном traccar REST API появился с версии 3.х и доступен по другому адресу.
