### ISSUE TITLE
Login invalid after recompile of war file

### ISSUE THREAD

**Issue by christianfrick** [vitalidze/traccar-web#229]
Hi all

I'd like to slightly adapt the web interface and recompile it. This usually works when running with eclipse. But I can't build a valid traccar-web.war file. It compiles and I can load it, but I can't login ("User name or password is invalid", user: admin / pw: admin, this usually works when using the original war file). It's not even possible to register a new user ("Username is already taken", for any random username).

I've already tried to clone your sources in another directory and only replace the very slightly adapted files, but not altering any other file by setting up eclipse nor compiling anything with eclipse. However, this did not work either.

But the big difference is, that the war file compiled by eclipse has a size of about 18MB and the one from the 2nd try has a size of about 51MB.

I as well figured out, that the same login problem occurs randomly when running with eclipse.

Why do the sizes differ? Do I have to cleanup before a recompile? How to handle this problem when running with eclipse?

I'm working on Windows 7, 64-bit

Thanks a lot
Christian

**Comment by vitalidze** [comment]
The inability to log in from time to time is a head ache for me as well. I am experiencing same issue when running from IntelliJ Idea from time to time. Restart of the application always helps. I cannot find out what goes wrong. However, this problem NEVER reproduced when I built the `traccar-web.war` file. The only correct way is to use maven for building like described here: http://traccar.litvak.su/building.html Correct size is 51MB, or a bit more. 18MB is the wrong size meaning you have built it incorrectly.

**Comment by christianfrick** [comment]
Good to know that you are experiencing the same issue from time to time. So I don't care about that right now.

I'm using maven in both cases, but let's ignore the 18MB case since there might be some invalid settings caused by the use of eclipse.

However, there is still the issue that I get a successfully created war file of about 52MB which does not allow to login nor register a new user.

Do you have any experience in debugging when using the war file? Especially for the login function?

Cheers, Christian

**Comment by vitalidze** [comment]
Yeah. You can use so-called SuperDevMode to debug deployed application. Briefly it does the following:
- starts a code server on your local machine, which serves javascript that is going to be debugged in IDE
- in your web browser you should have bookmarks provided by the code server site and named like 'Dev Mode On' and 'Dev Mode Off'. Once clicked they replace references to the javascript files with references to your locally running code server. Then you can debug your code in IDE.

You can find more info about SDM here: http://www.gwtproject.org/articles/superdevmode.html

**Comment by vitalidze** [comment]
BTW, there were a change that may break serialization https://github.com/vitalidze/traccar-web/commit/1c7f257f93fab8e76dc2b6606cc4cc5ea7136136 , which can cause such issues. I suggest you to try building from tag [0.8.0](https://github.com/vitalidze/traccar-web/tree/0.8.0)

**Comment by christianfrick** [comment]
Thanks a lot for the information about SDM, gonna try it soon.

I could finally fix the problem by clearing the browsers cache. Do you know if this is required at every updated of the war-file? If so, can you may add this to the building section of your webpage?

Thanks a lot, we really appreciate your work and effort you put in this project!

**Comment by vitalidze** [comment]
You are welcome. Thanks for your interest, spent time and warm words.

Regarding the cache, cleanup is **required** when you switch from old (_original_) web interface to my mod. Then during updates of my web UI package it most probably will not be needed. I don't quite remember last time when I did browser cache cleanup. Anyway, I still include it in [upgrade instructions](http://traccar.litvak.su/installation.html) just in case.

**Comment by christianfrick** [comment]
Perfect. SDM works as well.. Thanks a lot
