### ISSUE TITLE
DB structure not updated

### ISSUE THREAD

**Issue by Huebenthal** [vitalidze/traccar-web#231]
I followed the installation instructions which makes several changes of the SQL statements in traccar.xml. But it seems that this changes do not fit to the tabel structure and the table structure is also not updated by traccar-web. Finally I can start the traccar-web UI but I can not see/track my device although this was working before without traccar-web. Following warnings in the log:
2015-08-10 05:53:12  INFO: Version: 3.1-SNAPSHOT
2015-08-10 05:53:13  WARN: Table "POSITION" not found; SQL statement:
SELECT \* FROM position WHERE id IN (SELECT positionId FROM device); [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:349 < ConnectionManager.java:41 < ...)

2015-08-10 06:46:35  WARN: Table "DEVICES" not found; SQL statement:
SELECT \* FROM devices; [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:283 < *:126 < BaseProtocolDecoder.java:43 < ...)

**Comment by vitalidze** [comment]
Looks like for some reason it hasn't created the necessary tables. Maybe this is an issue with 3.1. I suggest trying version 3.0 (or even 2.12) for now.

**Comment by uppaljs** [comment]
Hi, I am facing a similar problem as well ? Recommendations?

**Comment by vitalidze** [comment]
Have you read my answer? It contains recommendations.

**Comment by Huebenthal** [comment]
It works with 3.0. Thanks.

**Comment by vitalidze** [comment]
This is an issue with traccar v3.1 (I have already sent pull request to fix it). Please see updated instructions of my web UI mod [here](http://traccar.litvak.su/installation.html) (p.4.1 in particular)
