### ISSUE TITLE
GWT Designer

### ISSUE THREAD

**Issue by christianfrick** [vitalidze/traccar-web#232]
Hi Vitaly

How do you create or maintain the UIs? It seems like GWT Designer is obsolete and is not even working anymore since GWT 2.7.0 in Eclipse.

See: https://code.google.com/p/google-web-toolkit/issues/detail?id=8556
See: https://groups.google.com/forum/#!topic/google-plugin-eclipse/gWcCq0xenbk

Cheers, Christian

**Comment by vitalidze** [comment]
You are correct - the UI designer does not work with the project. The reason for that besides itself being obsolete is GXT library, which from my understanding does not work in UI designer. The whole project is based on components from that library. 

As I have already said here #154 I prefer manual editing of XML and java code. There is nothing complex there and it's quite easy to get used to it. The recompilation takes couple of seconds in SDM, so it's quite comfortable to develop UI in such mode.

**Comment by christianfrick** [comment]
Thanks for your fast reply. This works for me
