### ISSUE TITLE
duvida 

### ISSUE THREAD

**Issue by marivan4** [vitalidze/traccar-web#233]
eu consigo usar so tracker-server.jar da versao 3.x  na versao 2.x  ?

**Comment by vitalidze** [comment]
No, you cannot use it smoothly. You should do the upgrade. Instructions are here: https://www.traccar.org/update-from-2-x-to-3-0/ Then you still may use `traccar-web.war` of my mod (on 3.0 version for now) - just follow official instructions http://traccar.litvak.su/installation.html

**Comment by marivan4** [comment]
a sua traccar-web.war ele servi na versao  linux   3.1  e outra nao estou tendo sucesso com os modelo mxt com banco de dados para opengtes , por que sera

**Comment by vitalidze** [comment]
I don't know the reason why it doesn't work on 3.1. Please use either 3.0 or 2.x for now if you want my web UI mod in `traccar-web.war`. Or I don't understand your question.

**Comment by douglaspedro** [comment]
Nice! Thanks vitalidze! You are the man!
