### ISSUE TITLE
Demo server problem

### ISSUE THREAD

**Issue by catrucho** [vitalidze/traccar-web#234]
Just now I cannot access your demo server.
I can login and enter normally in the mobile web page, and I can login in the desktop page but after that I get a totally white page.

The other day I had the same problem in my server at home, and the only solution was to restore the database to a backup two days old.

I tried to refresh the browser with F5 and delete the cookies but no luck

Do you know what might be the problem so if It happens to me again I can solve it ?.

Thanks a lot.

**Comment by vitalidze** [comment]
I can say that for both my accounts it works just fine. Can you send your credentials (username/password) to my email (from github profile)?

**Comment by vitalidze** [comment]
The reason of this issue is that you have unchecked all overlays in users preferences. Have you done that manually? What is the purpose of such behaviour?

I will fix this issue, but it's weird because in such case there will be just maps and no objects over map.

**Comment by catrucho** [comment]
Dear Vitaly

Obviously I don't know what I am doing as I am just starting to use the
program, I am not a programmer and I was trying different settings withouth
understand the problem

Anyway I cannot remember to uncheck the overlays manually... Strange

Can you tell me

¿What can I do to solve this problem if happens in my local server ?? How
to manually restart the overlays ?

Thanks a lot

2015-08-17 10:21 GMT+02:00 Vitaly Litvak notifications@github.com:

**Comment by vitalidze** [comment]
I have fixed it with SQL query:

```
UPDATE user_settings SET overlays='VECTOR' where id=551
```

Another option is to:

1) Create new user account.
2) 'Share' all that faulty account's devices to that account
3) Delete faulty user account

To make it you will need a working administrator account.

**Comment by catrucho** [comment]
Ok Thanks. I have to process this info and google how to perform this SQL query in the db file of traccar but I think I will be able to.

The second option you say, I am not sure that if I register a new user I can access as administrator and share the devices as I can only see them from the faulty account ( admin) and as I have the white page I cannot perform any action nor share the devices.

Thanks a lot

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
