### ISSUE TITLE
New traccar client not working

### ISSUE THREAD

**Issue by catrucho** [vitalidze/traccar-web#235]
I have updated the traccar client and now is not wirking with the server even though I changed the port number to 5055.

¿¿Is there something new ??

Thanks

**Comment by vitalidze** [comment]
Why are you asking it here? This issue tracker is related to the web UI mod. It does not collect data from devices. You should ask here: https://github.com/tananaev/traccar/issues

**Comment by catrucho** [comment]
Well I thought that maybe is something related with your version of traccar as It looks like is working with the tananaev version but not with your version but 
I apologize if I posted in the wrong place.

**Comment by vitalidze** [comment]
By default starting from v3.0 original version uses different database tables for storing devices, positions etc. There are official instructions on how to update this behaviour: http://traccar.litvak.su/installation.html

**Comment by catrucho** [comment]
My mistake, I was using a proxy between the gps data and traccar server and the problem is there.

Apologize and thanks
