### ISSUE TITLE
Arabic Languge (RTL)

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#236]
hi all 

i tried to add Arabic langue by adding

 <extend-property name="locale" values="ar" /> and message file for it .

 it s working fine but HTML style gone wrong it shift all panel and divs .

i tried to add
  <inherits name="com.google.gwt.user.theme.chrome.Chrome"/>  
 <inherits name='com.google.gwt.user.theme.standard.StandardRTL'/>  
 but the same issue .

<img width="556" alt="screen shot 2015-08-18 at 7 41 38 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336183/eba88e48-45e0-11e5-92b7-f7c531a8f2f2.png">
<img width="583" alt="screen shot 2015-08-18 at 7 41 22 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336184/ebaf6358-45e0-11e5-829a-37a08f3ed670.png">
<img width="1280" alt="screen shot 2015-08-18 at 7 42 29 pm" src="https://cloud.githubusercontent.com/assets/12040752/9336186/ebb652e4-45e0-11e5-8539-ed1732c347aa.png">

any help please

**Comment by vitalidze** [comment]
The RTL locales will not work. However, there is a way to force it to be LTR. You can observe this commit as an example on how to do it: https://github.com/vitalidze/traccar-web/commit/b50a7a1c2b8463eb7850d6892bda80ac58f9b780

**Comment by xizoaziz** [comment]
thank you

**Comment by solimanovic** [comment]
@xizoaziz can you please share with us your translated war file or the method you followed please

**Comment by vitalidze** [comment]
@solimanovic here are instructions on how to add new language: https://github.com/vitalidze/traccar-web/issues/187#issuecomment-113206860

**Comment by solimanovic** [comment]
forgive my newbie  question, but i'm not sure why its not working with me, beside whenever i restart the traccar service it starts from temp directory under /tmp, beside i couldn't build war file this is why i asked him to share with us.

**Comment by vitalidze** [comment]
What is not working for you?

The `traccar-web.war` file is unpacked to the system temporary folder, this is a normal behaviour. 

Have you followed the official instructions http://traccar.litvak.su/building.html to build the `.war` file? You can create a separate ticket in this issue tracker, where we can discuss your problem with building.

**Comment by xizoaziz** [comment]
@solimanovic when i tried to implement arabic language i follow this way 
https://github.com/vitalidze/traccar-web/commit/19a9747368aba60bad717070d5c59151e62ed256

just as vitalidze post here.

and it works fine as a translation for labels but direction still LTR.

but in arabic u need also ( for best look and feel  ) to make the lay out RTL in direction of all page components and GWT didnt support it .

so i keep it in English lang .

if you need any help please dont hesitate and contact me

---

@vitalidze i received email about translation in  transifex how can i help .

**Comment by vitalidze** [comment]
@xizoaziz what is 'transifex'? Why you have received it? I don't remember that I was sending such emails. I thought about using 'crowdin' service to simplify translations for users, but they want money for that. So for now, I stick with the old text file translation way.

**Comment by xizoaziz** [comment]
sorry sir it sent by   Anton Tananaev    :)

**Comment by vitalidze** [comment]
Ok, looks like it is quite simple to set up open source project there. Maybe I will set it up here as well.

**Comment by vitalidze** [comment]
I have set up project there as well: https://www.transifex.com/traccar-web-ui-mod/traccar-web/ If anyone is interested, then please post your translations there. I will do the announcement on the web site later.
