### ISSUE TITLE
Question (Add Tab Event in object)

### ISSUE THREAD

**Issue by sanayaCorp** [vitalidze/traccar-web#237]
I am currently experimenting with traccar-web, where I would like to add the event tab in the Object tab, Data tab I took from the event table event (DeviceEvent), I wanted to like gps-server.net applications where there is a tab event originating from the device on line.
And this source
1. DeviceView.java (http://pastebin.com/GAFvZ7UU)
2. DeviceView.ui.xml (http://pastebin.com/rGE3buSD)
3. EventProperties.java (http://pastebin.com/9vtaScXc)
4. UserSettings.java (http://pastebin.com/aReBtqPt)
and I compile not found error and login pages can be displayed, but after logging in, the application does not menampilakan any or blank screent

Please give me a solution, there is where the real mistake.
Thanks

**Comment by sanayaCorp** [comment]
and I compile not found error and login pages can be displayed, but after logging in, the application does not menampilakan any or blank screent

**Comment by vitalidze** [comment]
I don't think I understand what do you want to achieve. Can you give more explanation? Screen shots, diagrams, etc. may be of help as well.

**Comment by sanayaCorp** [comment]
Ok, sorry if a bit confusing to my question. So here if I only rely Archive indeed I will get an information about each device I choose, therefore I wanted an object that can give me information about the device off, on, or exceeding the speed or out of the geo-fence. So I need information to look like the following table:

Time | Device | Event

where I can get that information from the event table. Did master can help me provide a solution, or did I have to register DeviceEvent in DeviceView.controller file because if the public DeviceController () I do change then it will have an effect to all files. I attach a picture design I want
![slide3](https://cloud.githubusercontent.com/assets/5285172/9357192/c0427f28-46af-11e5-876b-f3926c456735.JPG)

**Comment by vitalidze** [comment]
Well, if you want to put it into the view at the left hand side on a different tab then you will have to modify the `DeviceView` class and the `DeviceView.ui.xml`. You can put all logic into a separate class (like `DeviceEventView`). Then you will need to add a method to the `DataService` interface and `DataServiceImpl` implementation that will load events. I think you should do it step-by-step.

If you want me to observe your changes then it's better to create a github repository and show me commits. Otherwise it's hard to find out what changes you have made in a whole file.

**Comment by sanayaCorp** [comment]
excuse my late reply to your answer, ok I will make github repository so that you can review research traccar-web where the source comes from you. This addresses my github: https://github.com/sanayaCorp/traccar_UI_lamedh

**Comment by vitalidze** [comment]
Where can I find the changes you want me to observe?

**Comment by sanayaCorp** [comment]
excuse my late reply, I have added the file DeviceEventView.java, DeviceEventView.ui.xml and EventProperties.java
but DeviceEventView.java not my calling in DeviceView.java, like geofence called in DeviceView.java.
My question, like whether my steps in the implementation of deviceevent ??

**Comment by vitalidze** [comment]
I guess you should call it from device view somehow. Like taking a reference from a component (grid, panel, etc.) and putting it on the tab in `DeviceView`.

**Comment by sanayaCorp** [comment]
sorry i do not quite understand the purpose of you, I want to show in the form of tabs and the grid paging, I have given reference tabs and grids along with paging in DeviceEventView.ui.xml, but I am still confused to implement it into DeviceView, whether dideviceview.java I should also add that I used in reference DeviceEventView? sorry if confusing because I am new in using sencha and gwt.

**Comment by vitalidze** [comment]
I mean if you want to put it into panel with tabs in `DeviceView` you need to refer it somehow (or it can be said "link" or "connect").

**Comment by sanayaCorp** [comment]
if I can do research with tab geofence, because of the way the call list geofence like what was in my mind, just replace from the list into the grid, because the script earlier in pastebin, when I run no errors at all and the login page has been able to emerge but when login later black and white pages. And I think it possible that I have to register or call him also in DataService and DataServiceImpl, because last I have not had time to try the 2 files.

**Comment by vitalidze** [comment]
Now it is possible to view events in 'Events' report, I believe this is a good alternative to this. 

Implemented [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by NetoSantiago** [comment]
Anyone knows where can i find a class diagram of Traccar?
