### ISSUE TITLE
Selected device does not stay in front

### ISSUE THREAD

**Issue by studmuffinjj** [vitalidze/traccar-web#238]
Hi,
When multiple tracked devices are close together in one location, the selected/highlighted device sometimes gets sent to the back and another deselected device moves to the front overlaying it whenever the interface refreshes. 

Also, the label for the selected device never seems to come to the front of all other devices even when selected.

![selection_074](https://cloud.githubusercontent.com/assets/11912640/9356527/4d84ad86-464f-11e5-8b5c-32943b793444.png)  ![selection_075](https://cloud.githubusercontent.com/assets/11912640/9356530/5324f2f0-464f-11e5-8234-4bbbe091cb69.png)

I appears that that this behaviour depends on the order in which devices are added to the database. The later device added always seems to have priority over devices added before, pushing its marker to the top, selected or deselected. 

An active marker only remains on top until the next interface refresh which is set to 3 seconds in my instance.

**Comment by vitalidze** [comment]
@studmuffinjj  issue is fixed and can be tested both on demo site and in [0.8.1rc2](https://github.com/vitalidze/traccar-web/releases/tag/0.8.1rc2)

**Comment by studmuffinjj** [comment]
Thanks Vitaly,

Confirmed, the selected marker remains on top now. I am seeing some occasional hiccups where the label for the selected marker does not come to the front of other labels. Will keep an eye on it.

Thanks!

**Comment by vitalidze** [comment]
Actually I can confirm that label often comes to background for me as well. This happens because label is being drawn in a separate layer called 'vector' layer. I think this can be changed, so both 'Markers' and their labels will be drawn in same 'Vector' layer since the 'Marker' layer type is old and redundant for now.  I will try to do my best to update it in next release/or release candidate.

**Comment by studmuffinjj** [comment]
Hey Vitaly,
I just had a chance to check this, and the original problem is occurring in the mobile interface still. The selected marker is not always in front.

**Comment by vitalidze** [comment]
You are correct. The fix wasn't applied to the mobile version. Just to the desktop.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
