### ISSUE TITLE
where to find db tables 

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#239]
Hi vitalidze
first of all great thanks  for your support 

i downloaded the source from Git 

https://github.com/vitalidze/traccar-web

and after run from eclips i found this file database.mv.db in /private/var/root/Documents/traccar-web.

i tried to open it with H2 console but it give me Schema for admin not including trracer tables ?

is that right or where i can found tables for traccar to modify it ?

<img width="384" alt="screen shot 2015-08-19 at 9 56 44 pm" src="https://cloud.githubusercontent.com/assets/12040752/9365859/a4b7d908-46bc-11e5-832c-0eaf4eb1e0a7.png">

best regards

**Comment by vitalidze** [comment]
Tables are created only when you access web UI for the first time.

**Comment by xizoaziz** [comment]
i run it and access the web UI and add some data  but still have no tables on it !!

**Comment by vitalidze** [comment]
Are you sure you are looking in the right database file?

Here is how mine looks like:

![screen shot 2015-08-19 at 23 20 00](https://cloud.githubusercontent.com/assets/2294325/9367902/ef1992aa-46c8-11e5-86d3-b17a65fbbb3a.png)

**Comment by xizoaziz** [comment]
yes i m sure it is .

i deleted it  and  run the App from eclips  it generated again and my sample data i entered before were deleted 

and the connection URL is 
<img width="456" alt="screen shot 2015-08-19 at 11 31 45 pm" src="https://cloud.githubusercontent.com/assets/12040752/9368129/3a51f702-46ca-11e5-89a0-2db3353b3e44.png">

**Comment by vitalidze** [comment]
Well, I am almost out of ideas. Maybe you have your traccar instance running? By default you cannot connect to the H2 database from multiple processes, i.e. process which is accessing it locks the database.

**Comment by xizoaziz** [comment]
i tried it also :(  ....

could you please send me script to generate  DB tables ....

best regards and many thanks for your support

**Comment by vitalidze** [comment]
Try accessing it with the `Shell` tool from h2.

I don't have any script. Database is created automatically by hibernate schema generator.

**Comment by xizoaziz** [comment]
thanks for your support
