### ISSUE TITLE
Windows enviroment

### ISSUE THREAD

**Issue by rmatamoros2015** [vitalidze/traccar-web#241]
i just installed Traccar in Windows enviroment, but i keep getting this error on the log, has anyone else experience this? how can i solve it? Thanks 

WARN: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial - NoInitialContextException (... < WebServer.java:55 < Context.java:125 < Main.java:26 < ...)

**Comment by vitalidze** [comment]
This is actually the main reason of incompatibility with 3.1 #240 #231 This is an issue with traccar v3.1 (I have already sent pull request to fix it). Please see updated instructions of my web UI mod [here](http://traccar.litvak.su/installation.html) (p.4.1 in particular)

**Comment by rmatamoros2015** [comment]
Thank you Vitaly :)

On Aug 26, 2015, at 4:14 AM, Vitaly Litvak <notifications@github.com<mailto:notifications@github.com>> wrote:

This is actually the main reason of incompatibility with 3.1 #240https://github.com/vitalidze/traccar-web/issues/240 #231https://github.com/vitalidze/traccar-web/issues/231 This is an issue with traccar v3.1 (I have already sent pull request to fix it). Please see updated instructions of my web UI mod herehttp://traccar.litvak.su/installation.html (p.4.1 in particular)

—
Reply to this email directly or view it on GitHubhttps://github.com/vitalidze/traccar-web/issues/241#issuecomment-134893286.

---

The information contained in this e-mail message is privileged, confidential and protected from disclosure and discovery. If you are not the intended recipient , any dissemination, distribution, copying, or making available to be copied is strictly prohibited. If you think you have received this e-mail message in error, please alert the sender about the error. Thank you; we will extend the same courtesy. Any inconvenience to you for misdelivered messages is regretted.

**\* Please consider the environment before printing this email. ***
