### ISSUE TITLE
Geo-Fence Notification

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#242]
Hi!
I have a problem with Geo-Fence notification. Here is my gmail account sample:
From: myname@gmail.com
Server: smtp.gmail.com
Port: 465
Secure connection type: SSL/TLS
Use authorization: [X]
User: myname@gmail.com
Password: mypassword
Test was succeed. But Im getting no mails.

THX a lot.

**Comment by vitalidze** [comment]
You need to check logs for error messages (wrapper.log in particular).

**Comment by connectnet** [comment]
```
INFO   | jvm 1    | 2015/08/26 16:36:57 | INFO: Sending Email notification to 'someuser@gmail.com'...
INFO   | jvm 1    | 2015/08/26 16:36:57 | Aug 26, 2015 4:36:57 PM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2015/08/26 16:36:57 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2015/08/26 16:36:57 | java.lang.NullPointerException
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at org.traccar.web.server.model.NotificationServiceImpl.getSession(NotificationServiceImpl.java:346)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at org.traccar.web.server.model.NotificationServiceImpl.access$200(NotificationServiceImpl.java:55)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:229)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:155)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2015/08/26 16:36:57 |       at java.lang.Thread.run(Thread.java:745)
```

**Comment by vitalidze** [comment]
According to the log there is something wrong with 'Secure connection type' setting (it is blank). Can you check out what you have set in database table?

**Comment by connectnet** [comment]
Strange. There was one user with wrong entrys in Notification settings. No secure connection type no
use authorization. After removed this (bad) entry I receive thousand of old notification mails.

**Comment by connectnet** [comment]
wohhh... looks like a spam attack.... 
Device 'xxxx' went offline at 2015-08-23 19:57:39.0
Device 'yyyy' went offline at 2015-07-17 16:14:23.0
....and so on.

**Comment by vitalidze** [comment]
This is expected behaviour. Once event notification is sent you will never receive it again. So all old events are being sent to you. You can delete them from database or mark them 'sent'. Also you can set up types of notifications you want to receive.

**Comment by vitalidze** [comment]
This is a bug that you can't have a notification settings without secure connection type.

**Comment by connectnet** [comment]
I understand. But the wrong settings were from a user. After deleting the wrong settings my admin notifications are working now. (too good:-)

**Comment by vitalidze** [comment]
That's strange because when notification is sent it should take notification settings from the recipient user (or his manager/admin).
