### ISSUE TITLE
Position Filter

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#243]
Is it possible to use the "old" filter keys? I cant find them in the 3.x traccar.xml
<entry key='filter.enable'>true</entry>
<entry key='filter.limit'>3600</entry>
<entry key='filter.invalid'>true</entry>
<entry key='filter.zero'>true</entry>
<entry key='filter.duplicate'>true</entry>
<entry key='filter.distance'>50</entry>

**Comment by vitalidze** [comment]
Which filter keys are you talking about? In traccar.xml you define how positions are filtered in backend, i.e. such positions will not be stored in a database at all. In web UI you can define how to filter archive, which applies to already stored data.

**Comment by connectnet** [comment]
Im talking about the traccar.xml to filter double or bad positions. Cant find the "filtering options" entry and I cant post them here. :-(
![bildschirmfoto vom 2015-08-26 17 09 06](https://cloud.githubusercontent.com/assets/8360383/9497463/649777c6-4c15-11e5-9382-b1ae90d3d0c1.png)

**Comment by vitalidze** [comment]
They are still present and should be working. You can find documentation on configuration file here https://www.traccar.org/configuration-file/

Your lines look good.

**Comment by connectnet** [comment]
Ahhhh... _SORRY_ I see now. Its similar to the "old" version. Thanks a lot!
