### ISSUE TITLE
Delete old records

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#244]
Is is possible to delete old records with this entry in traccar.xml?

``` MySQL
<entry key="database.initialize">
DELETE e FROM events e INNER JOIN positions p ON p.id=e.position_id WHERE p.time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);
</entry>  
 <!-- does not work --> 
```

**Comment by vitalidze** [comment]
I don't know where you should put it and where/when it should run. I guess it's better to have an external cron task to run it.

**Comment by connectnet** [comment]
ok thank you. Maybe somebody can post a sample script?

**Comment by peptoni** [comment]
This is in my crontab:

mysql -u root -pPASSWORD TRACCAR < /usr/local/bin/purge.sql

(root is the user of the database.  TRACCAR is the name of the database)

purge.sql is:

UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id IN (SELECT id FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -2 MONTH));
DELETE FROM events WHERE time < DATE_ADD(NOW(), INTERVAL -2 MONTH);
DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -2 MONTH);

I wanted to keep 2 months of data.  Hope this helps.

**Comment by connectnet** [comment]
@peptoni 
Your script gives me this error:
ERROR 1451 (23000) at line 3: Cannot delete or update a parent row: a foreign key constraint fails (`traccar`.`events`, CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`))

**Comment by peptoni** [comment]
It is working for me, every night...  I'll take a closer look and come back to you.  thank you.

**Comment by connectnet** [comment]
Thats my (working) purge.sql now:

``` MySQL
DELETE e FROM events e INNER JOIN positions p ON p.id=e.position_id WHERE p.time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);
```

**Comment by peptoni** [comment]
I don't see how can you delete records older than 3 months on the first line without getting a foreign key constraint error...  That is why I first set latestposition_id to null BEFORE trying to delete.  You are assuming that no record would have a latestposition_id older than 3 months, which would happen if some device has been stopped for that time...

**Comment by connectnet** [comment]
But my strings are working well and without problems. Are there other opinions?

**Comment by peptoni** [comment]
This is not a matter of opinion.
All code works until it faces a different set of input conditions that were not covered by the programmer.
I did face the input conditions described earlier, so I had to improve my code.  Now, I share my little knowledge with others.
Usually, the dilemma lies in the cost of programming time (money) to cover those conditions and the probability of them appearing in real life usage.
In your case, the cost is to first update, then delete.  So it's nearly free to improve the code.
Of course, it's up to you to improve your code or not.

**Comment by connectnet** [comment]
Thank you. It works now.

**Comment by inetsof** [comment]
After purge, I can't login, for procedure call error and sexsion expired.
Please help me

**Comment by nemik** [comment]
An error I had sometimes was 

```
ERROR 1451 (23000) at line 6: Cannot delete or update a parent row: a foreign key constraint fails (`traccar`.`events`, CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`))
```

I changed the schema to make the `events_fkey_position_id` constraint to be ON DELETE CASCADE so that it removes the child references when a parent is removed. 
To do this, I first dropped the constraint with:

```
alter table events DROP FOREIGN KEY `events_fkey_position_id`;
```

then modified it with

```
alter table events ADD CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`) ON DELETE CASCADE;
```

after that, @peptoni 's commands worked fine, thanks for those.

**Comment by vitalidze** [comment]
@nemik thank you very much for sharing.

**Comment by inetsof** [comment]
Hello,

I drop foreing key `events_fkey_position_id`;

But when I try to ADD CONSTRAINT it give me the next error:

#1452 - Cannot add or update a child row: a foreign key constraint fails (`gps`.`#sql-648_22f`, CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`) ON DELETE CASCADE)

Please help me...

**Comment by vitalidze** [comment]
@inetsof this is because you have a broken reference in foreign key column `position_id`. You need to delete it somehow.

**Comment by sankalpask** [comment]
Is this solution work for Version 3.8 - 3.9?

**Comment by vitalidze** [comment]
@sankalpask yes, it should still be working for 3.8 and 3.9 versions.
