### ISSUE TITLE
Building on t2.micro

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#245]
Hi Vitaly,

Is it possible to build (http://traccar.litvak.su/building.html) war file directly on amazon t2.micro istance with 1 GB. I have tried but it reported some errors:

[INFO] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000dccf6000, 69939200, 0) failed; error='Cannot allocate memory' (errno=12)
[INFO] #
[INFO] # There is insufficient memory for the Java Runtime Environment to continue.
[INFO] # Native memory allocation (malloc) failed to allocate 69939200 bytes for committing reserved memory.

**Comment by vitalidze** [comment]
Looks like it's not possible - there is not enough memory. I suggest to add
swap to your instance and try again.

четверг, 27 августа 2015 г. пользователь mpele написал:

> Hi Vitaly,
> 
> Is it possible to build (http://traccar.litvak.su/building.html) war file
> directly on amazon t2.micro istance with 1 GB. I have tried but it reported
> some errors:
> 
> [INFO] OpenJDK 64-Bit Server VM warning: INFO:
> os::commit_memory(0x00000000dccf6000, 69939200, 0) failed; error='Cannot
> allocate memory' (errno=12)
> [INFO] #
> [INFO] # There is insufficient memory for the Java Runtime Environment to
> continue.
> [INFO] # Native memory allocation (malloc) failed to allocate 69939200
> bytes for committing reserved memory.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/245.

## 

Kind regards, Vitaly Litvak

**Comment by mpele** [comment]
Thank you for advice.
