### ISSUE TITLE
[traccar-web] Notification from user

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#247]
Im getting offline [traccar-web] Notifications from other users as Admin but in my account settings I only activate the fence notification.
![bildschirmfoto vom 2015-08-27 15 44 43](https://cloud.githubusercontent.com/assets/8360383/9522113/1a9edb46-4cd3-11e5-81cc-aa45a504cafd.png)

**Comment by vitalidze** [comment]
Sounds like a bug, but in code I am pretty sure it is doing the right thing. Are you sure you don't have other user with such email?

**Comment by connectnet** [comment]
Now I don't understand. Other users with my email?

**Comment by vitalidze** [comment]
It is not prohibited. Email is not unique for now, so you can have multiple users with same email address. Only username should be unique.

**Comment by vitalidze** [comment]
Any update on this issue?
