### ISSUE TITLE
google Chrome 

### ISSUE THREAD

**Issue by draganjovanovich** [vitalidze/traccar-web#249]
I got white screen when using chrome, is that becouse  google no longer support npapi ?

in IE,edge,opera and mozilla is working normaly.

**Comment by vitalidze** [comment]
AFAIK npapi was used for old 'dev' mode, which was used during development. From now on you should use SDM (SuperDevMode) in development. Built version works just fine in chrome.

**Comment by draganjovanovich** [comment]
ok,maybe its becouse of windows 10,i dont know , it was working  a few days ago, now is white, and some time after a few refreshes of page, it show page, but map isnt complete, it sort like chess board...

chrome version 44.0.2403.157 m

**Comment by vitalidze** [comment]
You should check chrome console in development tools for error messages.

**Comment by peptoni** [comment]
Since yesterday, I get white screen (no google road map) when loading the page first time.  If I force layer change to other layers, and back to Google road, it loads correctly.  Tried on OS X with Safari and Firefox...

**Comment by vitalidze** [comment]
I am able to reproduce it on my side too. If I switch to other layer than 'Google Normal' and then switch back everything works correctly. I consider it as a bug. Thanks for reporting.

**Comment by vitalidze** [comment]
@peptoni I have just fixed this issue with solution from here http://stackoverflow.com/questions/32335221/google-maps-api-change It can be tested on demo version and is available in release candidate version [0.8.1rc2](https://github.com/vitalidze/traccar-web/releases/tag/0.8.1rc2)

**Comment by peptoni** [comment]
Great work.  Thank you very much.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
