### ISSUE TITLE
Table 'devices' not found

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#253]
Hi Vitaly,
since I performed a recent upgrade on both the server and (android) client, I have been experiencing a strange issue, blocking position acquisition.

This is the error reported in the logfile:
2015-08-31 17:46:53  WARN: Table 'traccar.devices' doesn't exist - MySQLSyntaxEr
rorException (... < QueryBuilder.java:289 < DataManager.java:283 < *:126 < BaseP
rotocolDecoder.java:43 < ...)

Checking the 'traccar' database I realized the 'devices' table does not exist; I know that your implementation makes use of a different table (from the original 'device' table), so I assume your code checks for the existence of 'devices' when first run, creating the missing table if not (only references to table updates are changed in 'traccar.xml', as shown in your installation instructions).

But even if I reinstall all the code from scratch nothing changes, so I'm writing to you in order to find the cause of this issue.

I thank you in advance.

**Comment by vitalidze** [comment]
Sounds like the same issue as in #248 #240 #231 Looks like you haven't followed p.4.1 of installation instructions.

**Comment by webmst** [comment]
Hi Vitaly and thanks for the prompt answer.

Believe me, I followed new instructions 4.1 very carefully as you posted them (jetty-jndi is in the 'lib' subfolder and wrapper.xml has been modified) and I had checked the new issues too, deeming them unrelated (in #248 traccar.xml had not been modified, in #240 and #231 the issue was on different tables).

There should be something else.

**Comment by vitalidze** [comment]
@korjavin had the same issue today and mentioned [here](https://github.com/vitalidze/traccar-web/issues/248#issuecomment-136383507) that it worked for him after device sent some data. Maybe it will work for you too?

**Comment by webmst** [comment]
2015-08-31 20:33:14 DEBUG: [822796AD: 5055 < 192.168.0.235] HEX: 474554202f3f696
43d3335353230313230393233343533382674696d657374616d703d31343430383730313936266c6
1743d34342e3931323433383333333333333333266c6f6e3d382e363134353433333333333333333
3342673706565643d302e302662656172696e673d3235302e3631303030303631303335313536266
16c7469747564653d3135382e3526626174743d38352e3020485454502f312e310d0a557365722d4
167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342
e312e313b2047542d6939333030204275696c642f494d4d373644290d0a486f73743a20636470612
e6e6f69702e6d653a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a416
3636570742d456e636f64696e673a20677a69700d0a0d0a
2015-08-31 20:33:14  WARN: Table 'traccar.devices' doesn't exist - MySQLSyntaxEr
rorException (... < QueryBuilder.java:289 < DataManager.java:283 < *:126 < BaseP
rotocolDecoder.java:43 < ...)

**Comment by webmst** [comment]
I had had the same idea (new data may force table creation) but it cannot go that way.

My device (traccar client 3.5 for android using the new 'osmand' protocol on port 5055) is still displaying errors in sending data (while tracker-server.log is confirming reception) just before appending them to the 'devices' table, as you can see: 

2015-08-31 20:33:14 DEBUG: [822796AD: 5055 < 192.168.0.235] HEX: 474554202f3f696
43d3335353230313230393233343533382674696d657374616d703d31343430383730313936266c61743d34342e3931323433383333333333333333266c6f6e3d382e3631343534333333333333333333342673706565643d302e302662656172696e673d3235302e363130303030363130333531353626616c7469747564653d3135382e3526626174743d38352e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342e312e313b2047542d6939333030204275696c642f494d4d373644290d0a486f73743a20636470612e6e6f69702e6d653a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2015-08-31 20:33:14  WARN: Table 'traccar.devices' doesn't exist - MySQLSyntaxEr
rorException (... < QueryBuilder.java:289 < DataManager.java:283 < *:126 < BaseP
rotocolDecoder.java:43 < ...)

I don't know if this error is related to the table issue, but it seems that the client is now 'aware' that its data haven't been stored (but no errors were reported before when an unregistered device was trying to send data).

If you want to try to send some data to my traccar server with any other device, please let me know its code to register it.

**Comment by vitalidze** [comment]
As I have said in #248 about the following error:

```
2015-08-31 17:03:44  WARN: Table 'traccar.positions' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder.java:289 < DataManager.java:349 < ConnectionManager.java:41 < ...)
2015-08-31 17:03:45  INFO: Starting server...
```

It appears only for the first time because of an order of initialisation. Then when web UI is initialised it creates necessary tables and after another restart you should get working installation. Here is my log file for the MySQL:

```
2015-08-31 17:03:43  INFO: Operating System name: Linux version: 3.16.0-4-amd64 architecture: amd64
2015-08-31 17:03:43  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
2015-08-31 17:03:43  INFO: Memory Limit heap: 643mb non-heap: 214mb
2015-08-31 17:03:43  INFO: Version: 3.1-SNAPSHOT
2015-08-31 17:03:44  WARN: Table 'traccar.positions' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder.java:289 < DataManager.java:349 < ConnectionManager.java:41 < ...)
2015-08-31 17:03:45  INFO: Starting server...
2015-08-31 17:04:19  INFO: Shutting down server...
2015-08-31 17:04:29  INFO: Operating System name: Linux version: 3.16.0-4-amd64 architecture: amd64
2015-08-31 17:04:29  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
2015-08-31 17:04:29  INFO: Memory Limit heap: 643mb non-heap: 214mb
2015-08-31 17:04:29  INFO: Version: 3.1-SNAPSHOT
2015-08-31 17:04:31  INFO: Starting server...
```

Thus, if you don't see created tables then most probably there is something wrong with your database connection configuration. You should double check your settings.

**Comment by webmst** [comment]
Ok Vitaly, first of all I double checked the database connection configuration in traccar.xml, that is:

<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>traccar</entry>
<entry key='database.password'>traccar</entry>

I also verified to be manually able to access and create new tables in the 'traccar' database using the given 'traccar' user credentials.

Then, I analyzed the tracker-server.log file from the startup of the traccar service (that takes about 3-4mins to actually begin to serve the webpage of the GUI), finding the following errors:

2015-09-01 09:48:36  INFO: Operating System name: FreeBSD version: 10.1-RELEASE
-p10 architecture: i386
2015-09-01 09:48:36  INFO: Java Runtime name: OpenJDK Server VM vendor: Oracle
Corporation version: 25.51-b03
2015-09-01 09:48:36  INFO: Memory Limit heap: 179mb non-heap: 0mb
2015-09-01 09:48:36  INFO: Version: 3.1-SNAPSHOT
2015-09-01 09:51:23  WARN: Connections could not be acquired from the underlyin
g database! - SQLException (... < QueryBuilder.java:56 < *:132 < DataManager.ja
va:349 < ConnectionManager.java:41 < ...)
2015-09-01 09:51:24  WARN: Need to specify class name in environment or system
property, or as an applet parameter, or in an application resource file:  java.
naming.factory.initial - NoInitialContextException (... < WebServer.java:55 < C
ontext.java:125 < Main.java:26)
2015-09-01 09:51:28  INFO: Starting server...

I think you are right in deeming the database layer responsible for the issue, still I cannot figure out what it can be (btw, all the other applications on the same mysql server work fine).

**Comment by vitalidze** [comment]
Yeah, I confirm that it looks like a DB connectivity issue. Well, you can also check whether you have opened listening socket on this address `127.0.0.1:3306` using `netstat -lnt` command. Maybe replacing `127.0.0.1` with `localhost` helps.

**Comment by vitalidze** [comment]
If it does not help you can test JDBC connection to your MySQL database and read errors with approach described here: https://wiki.archlinux.org/index.php/JDBC_and_MySQL I think this will be the simplest way.

**Comment by webmst** [comment]
Ok, port 3306 is surely open (I was already using a remote mysql client connecting to the server via network for testing database access) and nothing changes replacing 127.0.0.1 with 'localhost'.

It was an excellent idea to build a simple java program like the one you pointed me at in order to test the jdbc driver (database name and user credentials have been set to access traccar); this is the result:

com.mysql.jdbc.Driver
Exception in thread "main" java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at DBtest.main(DBtest.java:18)

It seems the problem is in the jdbc interface, in line 18 there is:
Class.forName(dbClassName);

**Comment by vitalidze** [comment]
You should include MySQL JDBC driver in your classpath. You can download it from official web site http://dev.mysql.com/downloads/connector/j/ and then include it in command line like this:

```
java -cp mysql-connector-{version}.jar DBDemo
```

or better include current folder as a classpath too:

```
java -cp mysql-connector-{version}.jar:. DBDemo
```

**Comment by webmst** [comment]
I'm sorry to say that everything works, leaving us with the same issue. This is the result:

com.mysql.jdbc.Driver
It works !

I also checked for 'all privileges' granted to the user 'traccar', set in the database connection configuration (so it can create tables, not just access the database like the test program is trying to do).

**Comment by vitalidze** [comment]
I am out of ideas. Something is definitely wrong with your set up. Can you check that the default installation works for you (I mean without my web UI mod)? If it does not work either I suggest to ask question on https://www.traccar.org/forums/ - maybe guys there will have more ideas.

**Comment by webmst** [comment]
I agree; I want to start again from scratch with traccar 3.1 and next time I will test everything with the original setup before switching to your mod (I'll let it start before loading traccar-web, it's the only thing I have not done yet during the last two reinstallations, as I was sure to be willing to use your GUI).

I'll let you know, maybe we can identify a criticality in an 'anticipated' migration to traccar-web.

Thanks for your always kind and punctual cooperation in diagnosing the issue up to this point.

**Comment by vitalidze** [comment]
I believe that once you get working basic installation you will switch to my UI mod (and back if needed) without any issue. Anyway, let's see how it goes.

**Comment by webmst** [comment]
I'm sorry to be back with bad news, but I have reinstalled everything from the beginning and - at the end - the same issue shows up.

This time I have carefully noted what happened step-by-step, keeping the logfile along the process (I can forward it to you for a deeper analysis). Here is, in few words, the sequence:

1) Reinstalled traccar 3.1 from scratch, started service and registered some devices: it works perfectly with no errors displayed in the logfile
2) Test phase in the 'original mode' of traccar for about 2hrs with a client updating position: no errors
3) Applied traccar-web, started service and restarted 3 times (with no devices defined yet, those previously defined were lost applying the mod): some 'table traccar.positions not found' messages appeared as expected, then they disappeared
4) Ri-registered the clients: some 'table traccar.devices not found' messages appeared, restarted 4 times but those errors keep appearing, no matter if the client has already sent a lot of data or if I restart the service again

Now the situation is clean, let me know what you think.

**Comment by vitalidze** [comment]
I have no idea what is happening on your side. If you have:
- necessary tables in database, which I suppose is true since you can register devices through the web UI
- updated queries in configuration file

Then you should be fine. Under cover both traccar-web and traccar backend use same datasource for JDBC connections, so they should update same database.

I think the only option that's left is to give me access to your server so I take a look.

**Comment by webmst** [comment]
I agree and I appreciate your effort in checking directly.

Which kind of 'access' would you prefer?

Would you rather have a 'database' access (via phpmyadmin) or a complete ssh (e.g. it can be done via teamviewer)?

Thanks in advance for your kind cooperation.

**Comment by vitalidze** [comment]
I need ssh access. Either direct or through teamviewer should work. You can send me access details through email (in my github profile).

**Comment by webmst** [comment]
I can confirm that everything works now, no more errors in the logfile!

Regarding the unexpected 'disk full' situation we spotted on my server this evening, please note that my disk (already at 80%) was gradually filled up today by several runtime decompressions of the traccar-web.war file, each one requiring 50Mb.

In summary, I think that the relevant cause in my issue was the missing jetty-jndi library reference, correctly inserted in the wrapper.conf file but not in the /usr/local/etc/rc.d/traccar startup script (that is originally supplied for FreeBSD by the traccar project). Maybe you will want to update the related installation instructions.

**Comment by vitalidze** [comment]
Thank you for the update! I couldn't find traccar installation package for FreeBSD, where have you got it? Then, I don't quite understand why it doesn't use [Java Service Wrapper](http://wrapper.tanukisoftware.com/doc/english/download.jsp) since it has binaries for FreeBSD. Using it would make existing instructions working for FreeBSD as well. I believe this is the best option, i.e. having same instructions for all OS.

P.S. future versions of traccar will be free of the issue with `jetty-jndi` library because it is already included in main project.
