### ISSUE TITLE
demo is not working

### ISSUE THREAD

**Issue by juancresc** [vitalidze/traccar-web#255]
I would lo ve to see a working demo https://d.traccar.litvak.su/

**Comment by vitalidze** [comment]
Thank you for noticing. There was a network maintenance in digital ocean (VPS provider I am using for hosting), and the service did not survive it. Now it should be fine.

**Comment by juancresc** [comment]
User and pass?

Date: Tue, 1 Sep 2015 08:40:11 -0700

**Comment by vitalidze** [comment]
You should register. Just enter desired username and password and hit "Register" button.
