### ISSUE TITLE
Register new user also from mobile site

### ISSUE THREAD

**Issue by maxlife70** [vitalidze/traccar-web#257]
Hi,
i have a question. Is possible to have the Register button also on the mobile site? 
It could be useful to have, because register new user with the desktop site from mobile phone is a little bit uncomfortable.
Thanks.
BR

Max

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
