### ISSUE TITLE
shutdown car motor "tk103"

### ISSUE THREAD

**Issue by arasfi** [vitalidze/traccar-web#258]
please i can shut down car from this new version for traccar ?

**Comment by vitalidze** [comment]
Sending commands is not yet supported in this version of web UI.

**Comment by arasfi** [comment]
okay thanks,
it will be available ?

**Comment by vitalidze** [comment]
It will, but at least it requires next version of traccar (i.e. 3.2) to be released because in current version there is no way to access sending of commands API when my version of web UI is deployed.

**Comment by vitalidze** [comment]
This should be possible in next release. Keep watching over #380

**Comment by arasfi** [comment]
thans
