### ISSUE TITLE
locale doesn't work on mobile?

### ISSUE THREAD

**Issue by Jeferex** [vitalidze/traccar-web#26]
I went to http://URL:8082/m/?locale=es and doesn't load right language

Is the url correct?

Or mobile version doesn't support locale?

thanks

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/03/10/improved-localization-and-read-only-users.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
