### ISSUE TITLE
Plaintext user passwords

### ISSUE THREAD

**Issue by x-logLT** [vitalidze/traccar-web#260]
User passwords are kept as plain text in DB. They should be salted and hashed. 

It boggles my mind how this hasn't been raised yet, considering that original traccar already does this.

**Comment by vitalidze** [comment]
This was implemented long time ago. See [this](http://traccar.litvak.su/features/password-hashing.html) for description.

**Comment by x-logLT** [comment]
My bad, but then the question is why its not done by default or is not mentioned in installation instructions?
Even then, does it salt the passwords?

**Comment by vitalidze** [comment]
It can be done by default. I think I will update the default DB migration so it will set up say SHA-1 for the password encryption.

I don't think this should be a part of installation instructions.

Regarding salt, AFAIK there is no salt for now. I will think about it.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by meneva** [comment]
Hello, can we convert the hashedpassword of users table to a plaintext? for example: my hashedpassword in database is: "866f71c7d6b074f490e00a9fdae89403c46e06180d83fde6" and i want to convert it to plain text which should be: "123456"
thanks in advance

**Comment by vitalidze** [comment]
@meneva No, you cannot do it. The thing is that this is not an encrypted password, so it cannot be decrypted.

**Comment by meneva** [comment]
Hello thanks for your prompt reply.
in my application... i have a users list where i can click an user and get all information from users table which show with hashedpassword. Now i want to show the password to the user as human readable format. Is it possible any otherway ?

**Comment by vitalidze** [comment]
You can select "Plain" as password hash method in application settings. Then all passwords will be stored as plain text.
