### ISSUE TITLE
Demo site unreachable

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#261]
Hi Vitaly,
this to inform you that the demo website is currently down.

Trying to access http://d.traccar.litvak.su/ , users hit a "504 Gateway Time-out".

You may check it out.

**Comment by vitalidze** [comment]
Thank you very much for notifying me. Looks like it ran out of socket resources and just stopped accepting new connections on the OS-level. There were around 5K connections. Now I have restarted it and it works just fine.

**Comment by puneetshakya** [comment]
yupppp...now it is working....Thank you sir...
