### ISSUE TITLE
help in the chart

### ISSUE THREAD

**Issue by clinicamatiz** [vitalidze/traccar-web#264]
good morning. I wanted to help in the GUI presenting ideas that I have in mind. I would like to be informed that you use software to program the source code and make some changes to currents me if you like. excuse my English.It is not very good.

**Comment by clinicamatiz** [comment]
observed changes they did to traccar this site: http://www.axiomagps.com/en/. This excellent graphical interface that.

**Comment by vitalidze** [comment]
I am using IntelliJ Idea to write code for the project. Here is the guide on how to set it up http://traccar.litvak.su/ide/idea.html. You will need an Ultimate Edition of the IDE. Also there are guides on how to set up free [Eclipse](http://traccar.litvak.su/ide/eclipse.html) and [NetBeans](http://traccar.litvak.su/ide/netbeans.html).

This software is written in java with [Google Web Toolkit](http://www.gwtproject.org/), [GXT](https://www.sencha.com/products/gxt/) and [GWT-OpenLayers](http://gwt-openlayers.org). Sencha GXT library already has charting capabilities. You can find examples [here](https://www.sencha.com/examples/)
