### ISSUE TITLE
change the traccar-web home screen

### ISSUE THREAD

**Issue by clvschaves** [vitalidze/traccar-web#265]
I need to change the layout of the home screen, adding a different css, as the project is with GWT would identify where the referent this style authentication dialog box.

**Comment by vitalidze** [comment]
To change layout of login screen you need to modify the `LoginDialog.java` and `LoginDialog.ui.xml` files.

The styling is a more complex thing. I can see three approaches here:

1) The most correct approach is to use GXT appearances. You can find additional information here: https://docs.sencha.com/gxt-guides/3/concepts/appearance/Appearance_3.html Any component as well as the window can have it's own appearance. So you can just create your own appearance say based on the 'Blue' theme appearance and assign it to the login dialog.

2) You can define css classes directly in `*.ul.xml` files (like `LoginDialog.ui.xml`) in the `<ui:style>...</ui:style>` elements. For example in `DeviceDialog.ui.xml` there is a following style definition:

``` xml
    <ui:style>
        .tabBody {
            padding: 5px;
        }
    </ui:style>
```

Then almost for any component definition you can use `addStyleNames` attribute like in `DeviceDialog.ui.xml`:

``` xml
<container:VerticalLayoutContainer addStyleNames="{style.tabBody}">
```

3) Reverse engineer CSS classes using web browser developer tools and update necessary attributes. This may look as the easiest way. However, the class names are generated during the GWT compilation and thus are a subject to change in future. Then, these class names will update your style for the whole application and not just for the desired screen.

Hope this helps.

**Comment by clvschaves** [comment]
thank you will greatly help me, but one of my main problems is to change the background only the authenticating screen without changing the screen where is the map, when I do auteração the home screen and will me log nothing appears on the map area disappears .

**Comment by vitalidze** [comment]
I have used the following code to add background image in `LoginController.java` right before login dialog initialisation in `login()` method (in `onFailure`):

``` java
// ...
public void onFailure(Throwable caught) {
                RootPanel.get().addStyleName("rootWithBackground");
}
// ...
```

In `traccar.html` I have defined the following style:

``` css
      .rootWithBackground {
        background: url('/theme/img/background.jpg') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }
```

The image resides in `webapp/theme/img/background.png`.

**Comment by clvschaves** [comment]
thank you once again, I'm sorry for the questions, but I wonder if I have to do a redirect of my right site for a map of the area without going through the login

**Comment by vitalidze** [comment]
I don't have a quick and short answer for that. You need to write some code.

**Comment by halie412** [comment]
Hi friends am new on traccar (i install since 2 weeks, with the great mod of vitalidze) please excuse me if have mistakes writing. i set up a wall paper changing the archive reset.ccs in ./traccar

old line: 
img,body,html{border:0;}

new line:
body,html{border:0;background:url(http://image);}img{border:0;}

this set an wallpaper permanent behind all, is a easy solution

**Comment by israelrodri** [comment]
@nestor412 where is that lines of code..? i can't found it

**Comment by halie412** [comment]
well i use ubuntu for edit traccar-web.war, this comes with "archive manager" for compressed archives.
1- I open with "archive manager" and unzip
2- Edit the archive that i want
3- Insert modified archive in original traccar-web.war (this traccar-web.war without unzip, is the original that download before) only on preview of "archive manager" traccar-web.war insert it. 
I don't know if is the right way but it works for me.

**Comment by israelrodri** [comment]
thanks @nestor412 im gonna try it..xD

**Comment by ghost** [comment]
More precision please.
If my picture'name is     mine.jpg
it's inside  /opt/traccar/web
can you write the good syntax below please ?  
body,html{border:0;background:url(http://image);}img{border:0;}
Thanks.

**Comment by halie412** [comment]
I use a remote image: http://myweb/wallpaper/traccar.jpg, i don't put the image inside /opt/traccar/web

**Comment by ghost** [comment]
Wouahou... works for me too, But....
image is in 'mosaic' and if I grow or reduce the browser window, the picture is NOTE resize, but duplicate if I grow the window.

How to have the picture as just one full browser window ?

**Comment by MarceloMJM** [comment]
I tried several times the Nestor of the procedure 412 but without success, I believe that I'm using in windwons.
Any tips?

**Comment by halie412** [comment]
Hello Marcelomjm and waca98 if you want do a custom login you can use the api avaiable in the traccar mod of vitalidze i left the link for that.

http://traccar.litvak.su/features/automatic-login.html

**Comment by ghost** [comment]
Tnx Nestor412, but, we're looking about another background AROUND the login windows, not modifying  the login window itself, but all the window around it.

**Comment by halie412** [comment]
ok friend well you can test with different css styles... you can use Firebug addon for Firefox

**Comment by ghost** [comment]
@Marcelomjm 
This is my full procedure :

Before doing any thing, be sure you can access your background file ONLINE with your browser.
if you can see your background file in your browser....

Stop traccar
Backup your actual   traccar-web.war   for security
You need to edit    traccar-web.war with below 

You can open/decompress it with any unzip tool(archive manager), because it's an archive
1- So extract all files/folders
2- Inside folder traccar , find reset.css  and edit it, replace
    old line: 

``` css
        img,body,html{border:0;}
```

Be carefull, you MUST remove the  img,  as the begining of this line.
New line with the  (  )   inside the online path to file:

``` css
        body,html{border:0;background:url(http://onligne/background.jpg);}img{border:0;}
```

for example, my line is :

``` css
body,html{border:0;background:url(http://onlinewebpath/fred/traccarground.jpg);}img{border:0;}
```

3- Save the    reset.css
4- Compress all files/folders as  traccar-web.war.zip
5- Rename the archive so the name must be only  traccar-web.war
6- Put this file inside /opt/traccar
7- Start again traccar

Good luck.

**Comment by ghost** [comment]
I've change the background for "desktop"; but this background is not display when I use mobile.

Any idea about modifying the mobile display "around" login screen please ?

Thanks.

**Comment by crarchile** [comment]
Also works for me.. thanks  everybody for sharing !!!

Remember the correct order to get success:

1) sudo /opt/traccar/bin/traccar stop

2) modify reset.css file inside traccar-web.war file

body,html{border:0;background:url(http://www.rastreogps.xyz/wp-content/uploads/2016/01/rastreo-satelital-gps.jpg);}img{border:0;}

3) put new war file on /opt/traccar/

4) sudo /opt/traccar/bin/traccar start

5) Reload page and empty browser cache to show the new background image

**Comment by crarchile** [comment]
To create the new version of traccar-web.war remember to zip this files/folders....

![image](https://cloud.githubusercontent.com/assets/11233964/12242961/bf14ac38-b87a-11e5-8a67-0246969f0e8d.png)

to a file called traccar-web.war.zip

after that, rename the file traccar-web.war.zip to traccar-web.war

then upload the file to your /opt/traccar folder

**Comment by MarceloMJM** [comment]
What is the image size standard to use?

**Comment by vitalidze** [comment]
For anyone interested in changing background in latest version please see my comment here https://github.com/vitalidze/traccar-web/issues/576#issuecomment-203289520 (this should be done in java, in `traccar.html` changes are same).
