### ISSUE TITLE
Popup doesn't show all data

### ISSUE THREAD

**Issue by novak82** [vitalidze/traccar-web#266]
Hi Vitali,

After upgrading traccar to 3.1 the data shown in popup of location doesn't show the data that was shown when the version of traccar was 2.

**Comment by vitalidze** [comment]
Please be more specific, what data is missing?

**Comment by novak82** [comment]
I think you called it sensors. It was displayed in popup below the odometer.

**Comment by vitalidze** [comment]
Can you check whether they are stored in database?

**Comment by novak82** [comment]
That data was/are stored in table Point(s) in column Other.
It looks like that the format was changed.

**Comment by vitalidze** [comment]
Sounds good. Can you post here an example data from the column `other`?

**Comment by novak82** [comment]
This is the new format:
{"priority":0,"sat":8,"event":0,"power":0,"io2":0,"io69":1,"io240":0,"io80":4,"io21":4,"io181":30,"io182":20,"io24":0}
and the old one:
<info><protocol>teltonika</protocol><priority>0</priority><satellites>7</satellites><event>0</event><power>0</power><io2>0</io2><io69>1</io69><io240>0</io240><io80>0</io80><io21>3</io21><io181>22</io181><io182>13</io182><io24>0</io24></info>

**Comment by novak82** [comment]
'<info><protocol>teltonika</protocol><priority>0</priority><satellites>7</satellites><event>0</event><power>0</power><io2>0</io2><io69>1</io69><io240>0</io240><io80>0</io80><io21>3</io21><io181>22</io181><io182>13</io182><io24>0</io24><io205>41862</io205><io206>11111</io206><io199>0</io199><io241>22001</io241><io72>0</io72></info>'

**Comment by novak82** [comment]
The old format is xml.

**Comment by vitalidze** [comment]
I see that in your case it is JSON. I think the easiest way to update will be to force it storing data to XML by updating following line in configuration file:

``` xml
<entry key='database.xml'>false</entry>
```

set to 

``` xml
<entry key='database.xml'>true</entry>
```

After that all your new data will be stored in XML. Meanwhile I will think about handling both cases in the UI.

**Comment by novak82** [comment]
Thanks

ps. That information was not mentioned in install instructions http://traccar.litvak.su/installation.html .

**Comment by vitalidze** [comment]
Yeah, actually I have just figured that out that 3.1 (and probably 3.0) stores values in `other` column in JSON format by default. I think I will update instructions.

**Comment by vitalidze** [comment]
Updated instructions. For now I think this is the best solution. BTW, does it work for you?

PS thank you for reporting, I appreciate that.

**Comment by novak82** [comment]
It works ;)

**Comment by novak82** [comment]
Just to add, in the configuration file there wasn't line:
`<entry key='database.xml'>false</entry>`

**Comment by vitalidze** [comment]
Oh, I see. I can see it present in the 'debugging' config. Will update instructions.

**Comment by mpele** [comment]
Hi Vitaly,

Is this short-turn solution?
I am asking this because transition to json should be easy (only in popup)
and I have already started to implement it in my code.

**Comment by vitalidze** [comment]
I thought about supporting both formats. Right now I conclude that it would be easier both for traccar web UI and for the end user to have a single format in the database. Thus, I think it's better to stick with XML since it is already in currently existing databases.

**Comment by vitalidze** [comment]
@mpele FYI I have implemented parsing. It looks fine for me with the example JSON above as well as with XML at the same time. You can observe https://github.com/vitalidze/traccar-web/commit/df8479d195d0d1003acaa10c04b83f6363bfd7b2 for my implementation.

**Comment by mpele** [comment]
Hi Vitaly,

This changes will cover both cases.
So, I would like to suggest to revert instructions for forcing use of xml.
This could be silence accepting json as standard - there is no reason to
force splitting from original traccar-server.

**Comment by vitalidze** [comment]
I agree. I will remove it once the new version of my web UI is released.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
