### ISSUE TITLE
select the archive result will not jump to that location on the map

### ISSUE THREAD

**Issue by nikenikw** [vitalidze/traccar-web#268]
Hi,
select the archive result will not jump to that location on the map
I remember that old version can do this. is it a bug?

![004](https://cloud.githubusercontent.com/assets/14104325/9929927/900a04ec-5d62-11e5-9e14-af4e27323bba.png)

**Comment by mpele** [comment]
Try to load markers.

**Comment by vitalidze** [comment]
Does it jump when you load archive with markers?
