### ISSUE TITLE
Pushbullet notification by email

### ISSUE THREAD

**Issue by catrucho** [vitalidze/traccar-web#269]
I receive the pushbullet notifications by email only. ¿Is this the normal behaviour?
I don't receive the notifications on my phone, only on my email from pushbullet. 
Is there a way to receive the notifications on my pushbullet app on my cell pushbulle instead by email ??

Thanks a lot

**Comment by vitalidze** [comment]
Yes, it is definitely possible to receive notifications on your phone. Looks like you have configured it incorrectly. I suggest to configure it so you can send notifications say from your web browser to your phone. After that you should be able to receive them from traccar as well.

**Comment by catrucho** [comment]
It was my fault as you said.
A put the wrong email address in the traccar and I was receiving the notifications by email.
Thanks a lot.

**Comment by clinicamatiz** [comment]
It would be interesting to arrive by mail alerts generated by GPS103 when the door open, engine running, and so on are activated. It would also be interesting that although the right is blocked to change the car, you could modify the maintenance and safety that one could block data without modifying the vehicle but if stay modify access to the various maintenance.If it not well understood. Excuse my English. My native language is Spanish

**Comment by clinicamatiz** [comment]
if there is any way to arrive by email alarms "open door" and "idling", please explain to me how.

**Comment by vitalidze** [comment]
@clinicamatiz first of all, please don't flood this thread with unrelated questions. Open new instead.

Regarding your questions:

1) There is no way to send notifications on events came from sensors. They are not recorded for now. Same goes for idling. Both are in plans.

2) "Read-only" user does not have any access to anything. So it is not possible for him to update the maintenance. To handle your use case it will either require a full-featured role-based security system (like when you have a set of rights and can define roles for users) or a new set of check boxes.
