### ISSUE TITLE
Email on Speed Limit

### ISSUE THREAD

**Issue by fransbjtami** [vitalidze/traccar-web#270]
Hi,

Is it possible to set a speed limit & have the system send me an email if that limit is breached?

Thanks.

**Comment by vitalidze** [comment]
Right now there are no such function.

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
