### ISSUE TITLE
Traccar may have failed to start

### ISSUE THREAD

**Issue by wileymack** [vitalidze/traccar-web#271]
Installed pre-compiled traccar-web.war on pre-existing traccar server (Linux 64 bit v3.1) installation following instructions at http://traccar.litvak.su/installation.html. Running on Ubuntu Trusty 14.04 64bit EC2 t2.micro and OpenJDK 7. When I start the traccar service it says:

> Starting traccar...
> Waiting for traccar......
> WARNING: traccar may have failed to start.

Running with console option I get:

> Running traccar...
> wrapper  | --> Wrapper Started as Console
> wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
> wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
> wrapper  |     http://wrapper.tanukisoftware.com
> wrapper  | 
> wrapper  | Launching a JVM...
> jvm 1    | WrapperManager: Initializing...
> jvm 1    | WrapperSimpleApp: 
> jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
> jvm 1    | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 37; Attribute "key" is required and must be specified for element type "entry".
> jvm 1    | WrapperSimpleApp Error:  at java.util.XMLUtils.load(XMLUtils.java:76)
> jvm 1    | WrapperSimpleApp Error:  at java.util.Properties.loadFromXML(Properties.java:868)
> jvm 1    | WrapperSimpleApp Error:  at org.traccar.Config.load(Config.java:27)
> jvm 1    | WrapperSimpleApp Error:  at org.traccar.Context.init(Context.java:89)
> jvm 1    | WrapperSimpleApp Error:  at org.traccar.Main.main(Main.java:26)
> jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> jvm 1    | WrapperSimpleApp Error:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> jvm 1    | WrapperSimpleApp Error:  at java.lang.reflect.Method.invoke(Method.java:606)
> jvm 1    | WrapperSimpleApp Error:  at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
> jvm 1    | WrapperSimpleApp Error:  at java.lang.Thread.run(Thread.java:745)
> jvm 1    | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 37; Attribute "key" is required and must be specified for element type "entry".
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1171)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:742)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
> jvm 1    | WrapperSimpleApp Error:  at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
> jvm 1    | WrapperSimpleApp Error:  at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
> jvm 1    | WrapperSimpleApp Error:  at java.util.XMLUtils.load(XMLUtils.java:74)
> jvm 1    | WrapperSimpleApp Error:  ... 10 more
> wrapper  | <-- Wrapper Stopped 

Any thoughts?

**Comment by vitalidze** [comment]
You have error in configuration file. Some <entry> tag is missing "key"
attribute.

понедельник, 21 сентября 2015 г. пользователь wileymack написал:

> Installed pre-compiled traccar-web.war on pre-existing traccar server
> (Linux 64 bit v3.1) installation following instructions at
> http://traccar.litvak.su/installation.html. Running on Ubuntu Trusty
> 14.04 64bit EC2 t2.micro and OpenJDK 7. When I start the traccar service it
> says:
> 
> Starting traccar...
> Waiting for traccar......
> WARNING: traccar may have failed to start.
> 
> Running with console option I get:
> 
> Running traccar...
> wrapper | --> Wrapper Started as Console
> wrapper | Java Service Wrapper Community Edition 64-bit 3.5.26
> wrapper | Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights
> Reserved.
> wrapper | http://wrapper.tanukisoftware.com
> wrapper |
> wrapper | Launching a JVM...
> jvm 1 | WrapperManager: Initializing...
> jvm 1 | WrapperSimpleApp:
> jvm 1 | WrapperSimpleApp Error: Encountered an error running main:
> jvm 1 | WrapperSimpleApp Error:
> java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException;
> lineNumber: 12; columnNumber: 37; Attribute "key" is required and must be
> specified for element type "entry".
> jvm 1 | WrapperSimpleApp Error: at
> java.util.XMLUtils.load(XMLUtils.java:76)
> jvm 1 | WrapperSimpleApp Error: at
> java.util.Properties.loadFromXML(Properties.java:868)
> jvm 1 | WrapperSimpleApp Error: at org.traccar.Config.load(Config.java:27)
> jvm 1 | WrapperSimpleApp Error: at
> org.traccar.Context.init(Context.java:89)
> jvm 1 | WrapperSimpleApp Error: at org.traccar.Main.main(Main.java:26)
> jvm 1 | WrapperSimpleApp Error: at
> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> jvm 1 | WrapperSimpleApp Error: at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> jvm 1 | WrapperSimpleApp Error: at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> jvm 1 | WrapperSimpleApp Error: at
> java.lang.reflect.Method.invoke(Method.java:606)
> jvm 1 | WrapperSimpleApp Error: at
> org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
> jvm 1 | WrapperSimpleApp Error: at java.lang.Thread.run(Thread.java:745)
> jvm 1 | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException;
> lineNumber: 12; columnNumber: 37; Attribute "key" is required and must be
> specified for element type "entry".
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1171)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:742)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
> jvm 1 | WrapperSimpleApp Error: at
> com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
> jvm 1 | WrapperSimpleApp Error: at
> java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
> jvm 1 | WrapperSimpleApp Error: at
> java.util.XMLUtils.load(XMLUtils.java:74)
> jvm 1 | WrapperSimpleApp Error: ... 10 more
> wrapper | <-- Wrapper Stopped
> 
> Any thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/271.

## 

Kind regards, Vitaly Litvak

**Comment by wileymack** [comment]
Thanks, it was missing a / in one of the </entry>
