### ISSUE TITLE
Geofences automatically shared with all users

### ISSUE THREAD

**Issue by rt3norio** [vitalidze/traccar-web#272]
i'm having a problem with geofences.

any fence created by any user is shared with all users.

and the 'share' button shows that only the creator have the 'checkbox checked' but, every user can see it.

it seems like the fences are public between users. but it shouldn't.

thanks in advance.

**Comment by vitalidze** [comment]
I have just checked and it works just fine for me. If I have two ordinary users (not managers and not admins) and both of them create some geo-fence, then each geo-fence will be available for this particular user. However, it works differently for 'manager' and 'administrator' users. You can find additional information here http://traccar.litvak.su/features/geofences.html in section 'Sharing geo-fence'

**Comment by rt3norio** [comment]
I think i messed up with me being administrador and the hierarquy thing.

Anywhay, i couldn't find that link you posted. Thank you.

Your fork is great!
Em 23/09/2015 2:55 AM, "Vitaly Litvak" notifications@github.com escreveu:
