### ISSUE TITLE
Idle vs Power

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#273]
Hi Vitaly,

Could you explain what is the difference between idle status (it is calculated) and power (it is reported by device - it was in separated field in table and now is in others)?
I am asking this because I need to have some clear indicator are the vehicle should be considered not moving/moving. Of course, stop at the semaphore should be treated as moving.

**Comment by vitalidze** [comment]
AFAIK 'Power' is not used anymore, it was used in some previous versions of traccar backend. Now as you correctly mentioned it is in 'other' field. 

Then, I guess you have explained it yourself. When device is powered off, it is most probably not moving, but it cannot be used as the only condition to say that device is not moving. There are numerous of things that may happen with device/vehicle even when it is powered off. Right now 'idle' is calculated as when the speed is zero. I believe this is better way for devices which can report speed correctly, but it's not the best again. 

From my point of view  the best way will be to combine all these methods:
- by speed (current way)
- by position change (say by some considerable distance from previous point)
- by some parameters from 'other' fields like 'power'

All these settings should be configurable per device. This must be the most flexible way to figure out whether device is moving/idling.

**Comment by mpele** [comment]
The most modern devices take into account many aspects when reports this
status, and usually it is configurable on device level. If it is reported I
would believe it.

From the practical point of view I think that it would be better to
settings should be configurable per protocol with ability to be overridden
with settings per device.

Vitaly, how would you suggest to solve this situation. I need boolean
function that would report if the device is “not moving”. Should I add new
field below “Idle when speed is <=” in device settings for entering "power
on"condition (for check in other field), and later use that condition for
checking in function?

**Comment by vitalidze** [comment]
Wait, you are talking about 'power' flag or the 'idle' calculation on device side? If device can report that it is idling itself, then it's okay to use this value and probably it would be much better than calculate it on the traccar side. But the 'power' flag means different thing. Can you provide an example of device where 'power' means 'idle'? This is a mess from my point of view.

Per the implementation I don't mind if this will be configured by protocol. I think that it can be implemented similar as it is done in wialon system (see http://docs.wialon.com/en/local/cms/units/trip):

1) You can define some sensor as 'ignition' sensor (see http://docs.wialon.com/en/local/cms/units/sensors/types)
2) Then you define how you are going to detect movement in a drop down list. Maybe there should be a list of check boxes instead, like:
- [] Idle when speed is <= 
- [] Idle when ignition is off

When some of the check boxes is checked then this condition will be taken into account. The logical operand between this conditions should be 'OR', meaning if either of conditions is met then device is considered idling.
