### ISSUE TITLE
Multiple Email Notifications

### ISSUE THREAD

**Issue by garthbpos** [vitalidze/traccar-web#274]
Hi,
Is it, or would it be possible to have a different email address set for notifications for each geozone? For example, Device 1 has 5 geozones attached, and a notification is sent to user1@gmail.com for the first geozone, then user2@gmail.com for the second geozone and so on?

Thanks a lot.

**Comment by vitalidze** [comment]
You should use different user account for such case. Each user account may have access to different set of devices/geozones as well as the different email.

**Comment by garthbpos** [comment]
Thank you for the reply. From what I can see, you can only limit a geozone to a device, not to a user, so every user shared with that device will get an email at every geozone linked to that device, am I missing something simple? Thanks again

**Comment by vitalidze** [comment]
That's not right. You can limit access to geo-fence per user as well. User will receive notification only if he has access both to geo-fence and device.

However, the whole access for geo-fences works different than it works for devices. You can read here http://traccar.litvak.su/features/geofences.html about it in the **Sharing geo-fence** section.

**Comment by garthbpos** [comment]
Thanks so much! I was missing something simple, the Share button on the geofences tab! Thanks again
