### ISSUE TITLE
with change the return after click in button logout 

### ISSUE THREAD

**Issue by clvschaves** [vitalidze/traccar-web#275]
i need change the url when i click in button logout in map, I wonder where this class to make this change?

**Comment by vitalidze** [comment]
Here it is https://github.com/vitalidze/traccar-web/blob/04bf12a62b5b41e2b60ff4e57d4bf7aa97bfa4e0/src/main/java/org/traccar/web/client/view/DeviceView.java#L363

**Comment by clvschaves** [comment]
I found thank you, but I need to change where he's redirecting me, he's using the window.location.reload (), but I do not want to send the login I I auterei the main page for an html want when I click on logout it is redirected to the home page with this url "/".

**Comment by vitalidze** [comment]
You should read some docs about `Window.Location`

**Comment by clvschaves** [comment]
thank you, but I made the wrong question, which I find the folder that the com.goole.gwt.user.client.window

**Comment by vitalidze** [comment]
There are no such folder in my project. This class comes from the GWT library. You can google for the API documentation on that class.
