### ISSUE TITLE
Upgrade to 3.1 database

### ISSUE THREAD

**Issue by catrucho** [vitalidze/traccar-web#277]
I saw that the aplication can be upgraded to 3.1 now.

I would like to upgrade and I have a lot of data that I would like to transfer, I saw that this can be done with SQL querys.

I have installed SQLsquirrel to open the old database, and I am able to open it but I cannot find the old data, my knowledge of sql is very limited

If anyone who is goig to upgrade would be so kind to provide a small howto upgrade and transfer the data with a sql script I would apprecciate a lot, in the meantime I would wait with the 3.0 version.

Thanks a lot in advance and congratulations for your great work Mr Litvak.

**Comment by vitalidze** [comment]
Why do you think you should run some SQL queries? Are your data from 3.0 version or from 2.x?

**Comment by catrucho** [comment]
Well, maybe I missunderstood, in the web It says

IMPORTANT NOTE: existing data of original web interface will not be accessible because it is stored in other tables. It can be copied manually with SQL queries.

I thought that to upgrade from 3.0 to 3.1 version It aplies.

Does it means that to upgrade from 3.0 to 3.1 I have only to follow steps 3, 4.1, 5 and 6, and download and copy the last war ??

**Comment by vitalidze** [comment]
This is about case when you are using original web UI and updating to my version. In such case data from original version is stored in tables with different names than my version is using.

If you have 3.0 version with my UI installed then your data is already in right tables and there is no need to run SQL queries for migration.

**Comment by catrucho** [comment]
Thanks a lot for your help
