### ISSUE TITLE
Wrong  Notification     positionTime

### ISSUE THREAD

**Issue by ginei11** [vitalidze/traccar-web#278]
Help!
How can set the time zone?

![captura](https://cloud.githubusercontent.com/assets/9000567/10264374/57a98b58-69cf-11e5-83c0-580a5bf7d4f5.PNG)

**Comment by vitalidze** [comment]
Have you solved issue by yourself?

In current public available version the only way to set up timezone is to change it on server. In next release there will be a possibility to set up time zone in user's preferences (for the first time it is automatically detected). It is already implemented and committed to this github repo.
