### ISSUE TITLE
Device not connectid on traccar 

### ISSUE THREAD

**Issue by mirzaumair** [vitalidze/traccar-web#279]
2015-10-03 17:23:31  WARN: Unknown device - IME#

**Comment by vitalidze** [comment]
Do you have device with such identifier in your database?

**Comment by mirzaumair** [comment]
yes i add this IME number in my admin penal but its not connecting 
2015-10-04 06:38:56  WARN: Unknown device - 351789567271920
2015-10-04 06:39:06 DEBUG: [86E54C5D: 5023 < 119.160.119.124] HEX: 78781f120f0a040f222bc702aa529f07327ed500348e019a0100e700294d00023f430d0a

**Comment by vitalidze** [comment]
Then if you are using 3.x version of traccar with my UI mod most probably you have configured backend incorrectly. The error might be somewhere in queries configuration. This may lead to the case when backend part (which is responsible for receiving data from devices) is looking into different tables than are used in web UI. Please double check the configuration file according to instructions http://traccar.litvak.su/installation.html
