### ISSUE TITLE
Is it possible to change appearance to default for Traccar?

### ISSUE THREAD

**Issue by fitzy89** [vitalidze/traccar-web#283]
I would like to know if it is possible to easily change the look to be the same as the official Traccar project.

I know a bit of CSS but it looks like it would be a lot of work to change it back because your version is modified so much.

Is there an easy way?

Thanks

**Comment by vitalidze** [comment]
There are no easy way. It was discussed in #102 

However, the official UI uses 'neptune' theme and it is possible to switch to that theme in GXT. I have started work on it in the `neptune_theme` branch. You can try building it from source with official instructions http://traccar.litvak.su/building.html (don't forget to switch to the `neptune_theme` branch before building and be prepared to wait a reasonable amount of time, 20 minutes minimum).

**Comment by fitzy89** [comment]
Ok thankyou very much for your reply and work on this project, I personally prefer the neptune theme so I will give your instructions a try :)

**Comment by fitzy89** [comment]
Thanks very much, have built it from source with the neptune branch and it's worked perfectly :) thanks for your advice

**Comment by Estebanmg** [comment]
where do I find the neptune branch? thanks amazing project!

**Comment by vitalidze** [comment]
`neptune` branch was merged long time ago into upstream branch named `dev`
