### ISSUE TITLE
Проблемы с кириллицей

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#287]
Доброго времени суток!

У меня возникли проблемки с отображением кириллицы. Через Pushbullet и электронную почту приходят символы '?' вместо текста(там где кириллица). Название геозон и устройств (латиница) отображаются в сообщениях нормально. Проверил кодировку базы, стоит UTF-8. Сервер установлен на Ubuntu 14.04 x32. СУБД: MySQL.

В чем может быть проблема?

**Comment by akanayman** [comment]
На карте местоположение тоже отображаются символами '?'. 
![1](https://cloud.githubusercontent.com/assets/7967243/10572142/4984e082-7667-11e5-8f0e-22fa0fde46ef.jpg)

**Comment by vitalidze** [comment]
Скорее всего проблема кодировки базы. Попробуйте посмотреть какое значение там хранится, сделав SELECT запрос в таблицу `positions`.

Еще имеет значение настройка jdbc URL. В строке обязательно должен присутствовать параметр `characterEncoding=UTF-8`.:

```
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/[DATABASE]?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry> 
```

Может быть также проблема с кодировкой самого сервера, обсуждалось здесь #254

Также имеет смысл посмотреть в этот тикет #98

**Comment by akanayman** [comment]
Спасибо!

Помогло добавление строчки в wrapper.conf: wrapper.java.additional.1=-Dfile.encoding=UTF-8
