### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#290]
Hi Vitaly,
I would like to propose the realization of a "To Do List" on your website, with the aim of summarizing upcoming traccar-web implementations, modifications and corrections for future minor/major releases.
Most of all, the issue tracker database is growing up and it is getting difficult for users to keep their orientation on where the project is going to; I'm also confident you could receive some valuable feedback on already available and planned features to quickly achieve the full maturity of the code, especially in comparison with other GIS platforms.
Cheers,
Alberto

**Comment by vitalidze** [comment]
I have added the [Roadmap](http://traccar.litvak.su/roadmap.html) page to the web site. Please check and let me know if you have any questions/suggestions.

**Comment by webmst** [comment]
Perfect!!!
