### ISSUE TITLE
Sensors: change color according to status

### ISSUE THREAD

**Issue by nitrousnrg** [vitalidze/traccar-web#291]
This feature could make possible to see dangerous parameters at a glance in the map, spotting right away a problem in a fleet.

For example, turn the marker red when battery is critical, or with high speed or RPMs. Could it be added as an extra parameter in sensors->intervals (next to text)?

Thanks

**Comment by vitalidze** [comment]
I actually thought about putting icon to the custom intervals like discussed in #207 Probably text color may be added as an option too.

**Comment by nitrousnrg** [comment]
Yes, that would be a useful enhancement.
Let me know if I can help despite my non-existent java skills

**Comment by gsiotas** [comment]
+1

**Comment by xizoaziz** [comment]
:+1:  :+1:

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2016/06/04/Sensor-text-color-and-icon,-bug-fixes.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
