### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#292]
Hi Vitaly,
I'm going to ask you some help to identify the cause of a problem I've already experienced three times.
In few words, I noticed it occurs when I regularly reboot my FreeBSD system; getting the traccar service not to run any more.
Nothing is shown in the log file (except some java environment startup messages); to get more information I've run the program interactively, having the following:

java -cp /usr/local/traccar/jetty-jndi-9.2.13.v20150730.jar:/usr/local/traccar/tracker-server.jar org.traccar.Main /usr/local/traccar/conf/traccar.xml
[MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
[main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
[main] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kflt9c1546t6h1d04znu|1ae735e, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kflt9c1546t6h1d04znu|1ae735e, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=*****_, password=**_***}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
Exception in thread "main" java.lang.NullPointerException
        at org.traccar.database.QueryBuilder$6.process(QueryBuilder.java:371)
        at org.traccar.database.QueryBuilder$6.process(QueryBuilder.java:367)
        at org.traccar.database.QueryBuilder.executeQuery(QueryBuilder.java:393)
        at org.traccar.database.DataManager.getLatestPositions(DataManager.java:349)
        at org.traccar.database.ConnectionManager.<init>(ConnectionManager.java:41)
        at org.traccar.Context.init(Context.java:102)
        at org.traccar.Main.main(Main.java:26)

The only solutution I have tried so far is to recreate the database from scratch and reconfigure the traccar application; as you can understand it is not quick and most of all it doesn't solve the issue definitively.

Do you have any ideas?
Cheers,
Alberto

**Comment by vitalidze** [comment]
This is the issue discussed here #282 Please try the suggested solution.

**Comment by webmst** [comment]
Thanks Vitaly, I confirm it works now.

Following issue #282 I modified traccar.xml and performed the mysql update command, removing the error and - to be sure - I tried restarting the traccar service immediately, with no more issues.

Has the 'database.insertPosition' query changed recently? I haven't changed anything since I applied your mod (I've just installed the last two updates).

**Comment by vitalidze** [comment]
Yeah, that's right - it was changed recently. In scope of #256 I have added new column `serverTime` to the `positions` table, which will hold the time of server when the data was posted. Previously there were `time` column only, which had the time received from device. Now based on data on these two columns I believe we can find out more precisely that device went offline.
