### ISSUE TITLE
PT502 send command

### ISSUE THREAD

**Issue by and12345** [vitalidze/traccar-web#293]
Hi Vitalidze,

Sorry to bother you, but i needs some help implementing the PT502 send command, here's the documentation i can get, could you please help me implementing the send command please.

GPRS PROTOCOL
| Frame header | Verify | Data body length | Data Body |

Remark:
Frame header : Start of the frame. Fixed as 0xBF, 0xFB
Verify: XOR of Data Body. 1 byte
Data body length: length of frame, which include “Frame header, Verify, Data body length ,Data Body”, 2 bytes, Little Endian format, ie. Least Significant Byte first
Data body: Format of Command or terminal Reply.. which is Stop Car / Cut Engine : OPC1,1 ; Restore Car / Engine: OPC1,0

Commonly, the fields, including Frame head, Verify, Data body length, is not necessary; If the Data Body has unrecognizable binary data, in order to parse frame correctly, full frame package is suggested. Binary-date-type frame includes: FOTA, multi-media and etc. Terminal should support both full frame and simplified frame, which has Data Body only.
 Without specification, multi-byte binary data uses Little Endian format, ie. Least Significant Byte first

**Comment by vitalidze** [comment]
Do you have any particular questions? I don't have much time now to work on this protocol.

**Comment by and12345** [comment]
Hi vitalidze, i'm trying to work on this protocol by using GT06 as template. 

Could you help me with "Verify: XOR of Data Body. 1 byte" where the Data Body is "OPC1,1".

**Comment by vitalidze** [comment]
I don't quite understand what 'XOR' of Data Body means. [XOR](https://en.wikipedia.org/wiki/XOR_cipher) is the operation which is usually done with two numbers.
