### ISSUE TITLE
Cron line for   database.mv.db  backup 

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#294]
Hello,

I want to make a daily backup of the 
/opt/traccar/data/database.mv.db

I don't know anything about   h2  and so, about the command to write on my crontab.

Help please.

Thanks.

**Comment by vitalidze** [comment]
First of all, I don't recommend to use H2 database on production system. Better use MySQL, which more fast, reliable, mature, scalable and stable. MySQL has several options for backup.

As for backing up h2 database I don't know a way to do it without stopping your traccar server. So, briefly:

1) Stop traccar server:

```
service traccar stop
```

2) Backup database by doing simple copy.

```
cp -avR /opt/traccar/data /my/backup/place
```

3) Start traccar server:

```
service traccar start
```

All these three commands may reside in a shell script and then you can schedule it with cron.

**Comment by gsiotas** [comment]
@waca98 You can use [this guide](https://www.traccar.org/mysql/) to change to mysql.

**Comment by chkm8** [comment]
Hi, I am trying to backup the traccar db, Im having problems to back it up, we used the docker image of traccer, how could i backup the database from the container? thanks

**Comment by vitalidze** [comment]
The recommendation is same - switch to MySQL and then use it's tooling (like `mysqldump`) to make backups.

For H2 database it is described above in my comment.

P.S. Please pay some respect and name the project correctly, it's not 'tracer', it's 'traccar'.

**Comment by chkm8** [comment]
Thank you for the recommendation, btw it was a typo error , but sure will note it :)
