### ISSUE TITLE
user map and  login 

### ISSUE THREAD

**Issue by caslor** [vitalidze/traccar-web#295]
Hi thanks for the mod to the traccar 
it is a question but couldnt find   ''question label ''

Is it possible to share a users  map  with have to login ?
i would like to share a map to my web page  but the users dont have to login to see the map with the devices i would have choose to display 

Today i find the traccar..  so i install it to my ubuntu system and i install and your modifications . i am planning to install it to a server in the future

**Comment by vitalidze** [comment]
There is no way to do it out of the box. I think the cleanest way to do it is:

1) Create a 'read-only' user
2) Write some javascript code to authenticate that user
3) Embed mobile UI into your web page in some kind of `iframe`.

You can find mobile UI javascript code [here](https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/traccar-mobile.js)
