### ISSUE TITLE
Question about database change during installation

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#297]
Hi!
I have tried to install your software by following the [guide from here](http://traccar.litvak.su/installation.html). In the guide it mentions besides "installing" war file, I should change some values in the xml file. Example:

> Old:
> <entry key='database.selectDevicesAll'>
>     SELECT \* FROM device;
> </entry>
> 
> New:
> <entry key='database.selectDevicesAll'>
>     SELECT \* FROM devices;
> </entry>

Although the guide suggest that I should change the tables device to devices and position to positions, I can't see the reason behind this. Traccar has "constructed" the tables device and position, why I should change to the plural ones?

Thank you for the clarification.

**Comment by vitalidze** [comment]
Previous versions of traccar (2.x) were using tables with these names. My web UI mod was developed for these versions and should work both with 2.x and 3.x. So, generally it is for backwards compatibility.

**Comment by gsiotas** [comment]
Ohhh very fast feedback :+1: 

Ok my mistake I didn't saw the rest of the guide that you were explaining the situation:

> 4.1) Specific to v3.1 of traccar 
> etc.

I'm sorry and thank you again for your time. I'm closing this.
