### ISSUE TITLE
How to work with sensor

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#299]
Good evening,

I would like to fix my issue of sensor. I can not undertsand how it work with a devise.

I created a devise
I edited it I went to the sensor tab.
The I created a sensor called “Battery level” and the parameter name is “batt”.
Finally I setted some intervals.

Now what can I do more.

My devise send a parameter name batt as well and it the value is a number from 0 to 100, of course (the value is save in the ‘other’ field of my database

How can I now match my batt value to my Battery level sensor.

If the sent value is egual to a interval, should it send an alert e-mail?

Cheers

**Comment by pierrot10** [comment]
Some one suggest me, I may have a unoffical version. It ca be possible?
I follow that procedure : http://traccar.litvak.su/installation.html

**Comment by vitalidze** [comment]
You may set up your sensor per this description http://traccar.litvak.su/features/sensors.html (use custom intervals to change the displayed value).

As for notifications - for now there is no possibility to send it based on sensor value.

**Comment by pierrot10** [comment]
Dear Vitalidze. Thank for your reply. Then I suppose it plan to send e-mail alert based on sensor? Then where a save the message when sensor interval a reached. I already create sensor and interval as it state here : http://traccar.litvak.su/features/sensors.html
Thank for your help

**Comment by vitalidze** [comment]
It is in plans. But not in nearest future.

воскресенье, 25 октября 2015 г. пользователь Pierrot написал:

> Dear Vitalidze. Thank for your reply. Then I suppose it plan to send
> e-mail alert based on sensor? Then where a save the message when sensor
> interval a reached. I already create sensor and interval as it state here :
> http://traccar.litvak.su/features/sensors.html
> Thank for your help
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/299#issuecomment-150899006
> .

## 

Kind regards, Vitaly Litvak
