### ISSUE TITLE
[Feature request] Add OpenCellID to get cell tower position when staelite are not available

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#306]
Good day,

Some time we can not get a GPS position, particularely when we are in a building a traveling by train.
There is nice Opensource project call OpenCellid
http://wiki.opencellid.org/wiki/What_is_OpenCellID

OpenGTS include OpenGTS and when a GPS position is unavailable, it send the cell tower position to OpenCellID and open cell id return the GPS position

I would like to suggest this feature because I think it's important to have a position even we are in "closed\* location, as the train which make a barrier.
The Traccar administrator need to provide the OpenCellID key. He also need to open an account.

ince July 7th, 2014 all user accounts that just read data from the OpenCellID database but do not contribute anything to OpenCellID on more than 15 individual calender days with download activities in a row are automatically blocked.
Example: if a user downloads OpenCellID data once per week using the OpenCellID API but never contributes at least 10% of the data volume of the downloaded data in the same time frame, his account will be blocked. 
Additionnaly, and what does not do OpenGTS, I also would suggedt to let the Traccar administrator send send GPS fix with it collect cell tower position, to contribuate and not be blacklisted afte 15 days.

I hope to find that idea nice to use :o)
Cheers

**Comment by vitalidze** [comment]
Well, this is actually more related with the backend. So it's better to submit this feature request on the [traccar issue tracker](https://github.com/tananaev/traccar/issues). The web UI is not responsible for collecting data from devices.
