### ISSUE TITLE
Polygon geofence howto ?

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#307]
Hello,

I definitely don’t understand how to define polygon markers !!!

I create the geo fence as:
Type Polygone, and when I click on the map (1st dot), ok, I’ve this dot, but how to make the 2nd dot ???
I double click on the 1st, I drag and drop, I click another part of the map… unable to create 2nd dot for beginning the link with the 1st one.

Help please.

Thanks.

**Comment by pierrot10** [comment]
You have to click and draw your zone. Just try to do like a circle. The last should be a double click on the first. The zone will be "closed" and you will see the zone. It easy, choose polygone and make a circle and you will see.
Cheers

**Comment by ghost** [comment]
Ok, what about the difference between 
line  and  polygone,    because I can draw  polygones with lignes  ;)

**Comment by vitalidze** [comment]
These are two different shapes. Line geo-fence is entered when device is within a radius from line and not within any area bound by that line (try to play with `Radius/width` parameter). While polygon is an area that is bound by some line and it is entered both when device is on border and within the area.
