### ISSUE TITLE
Traccar api

### ISSUE THREAD

**Issue by ethankz** [vitalidze/traccar-web#309]
Hi, i want to use the traccar api with php and i wrote this code for the original traccar project:

``` php
$curl=curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
curl_setopt($curl, CURLOPT_POST,true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
$response=curl_exec($curl);
if ($response === false) {
$info = curl_getinfo($curl);
curl_close($curl);
die('error occured during curl exec. Additioanl info: ' . var_export($info));
}
curl_close($curl);
$decoded = json_decode($response);
if (isset($decoded->response->status) && $decoded->response->status == 'ERROR') {
die('error occured: ' . $decoded->response->errormessage);
}
var_dump($decoded);
```

But it always return success false. Can you tell me what is wrong with the code and how can i use your traccar version api with php for post method.

**Comment by vitalidze** [comment]
I am not a PHP programmer. But you should be able to use anything with the API that can submit a `POST` and `GET` HTTP requests. Here are examples with command-line cURL for my REST API: http://traccar.litvak.su/features/rest-api.html It is different than the one from original project. Also same API is used in mobile version of the web UI in javascript.

**Comment by ethankz** [comment]
I'm also new in php developpment that's why i tried to test it with poster, a firefox extension, and that is the answer i got:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /traccar/rest/login. Reason:
<pre>    Server Error</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>                                                

</body>
</html>

**Comment by vitalidze** [comment]
Are you sure it works from command line with cURL and the credentials are correct?

**Comment by ethankz** [comment]
Ok i'll check.

**Comment by ethankz** [comment]
Thank you i found the solution.

**Comment by rt3norio** [comment]
You should post your solution so anyone with a similar problem can be aware
of it.

Thanks in advance!

Em 12h24 Qua, 28/10/2015, ethankz notifications@github.com escreveu:
