### ISSUE TITLE
Search Devices

### ISSUE THREAD

**Issue by hardjumper** [vitalidze/traccar-web#311]
Is there a possibility to add a search function to the interface to quickly find a device ?Thank you

**Comment by rt3norio** [comment]
Maybe ctrl+f could do the job, don't it?

Em 7h16 Qui, 29/10/2015, hardjumper notifications@github.com escreveu:

**Comment by hardjumper** [comment]
Yes it does.Thank you

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
