### ISSUE TITLE
Web interface style

### ISSUE THREAD

**Issue by ethankz** [vitalidze/traccar-web#312]
Your traccar version is quite better then the original one. I'm learning java and i want to know if i can edit the web interface style (css and even html) without recompiling the source code.

**Comment by vitalidze** [comment]
Unfortunately there is no easy way to edit style. It was discussed in #102 and #283

**Comment by ethankz** [comment]
Ok thank you  for your quick reply.

**Comment by ethankz** [comment]
And do you know how can i can log in from my own page?

**Comment by vitalidze** [comment]
You can do it either with API call or by using special URL: http://traccar.litvak.su/features/automatic-login.html

**Comment by ethankz** [comment]
Ok that's great. thanks alo! But coming back to the style, i'm ready to do some effort and take my time to learn things. But i m really a beginer in java. So please can you give all the steps to edit the project especially the style, and what do i need to compile. Thank you.

**Comment by vitalidze** [comment]
I don't have these steps. You need to start from reading documentation on GXT library, import project into IDE, and so on.

**Comment by ethankz** [comment]
Ok

**Comment by ethankz** [comment]
Great work you have done so far. thanks
