### ISSUE TITLE
New interface not working

### ISSUE THREAD

**Issue by ekofficiel** [vitalidze/traccar-web#313]
Hi i followed all the instructions to install your traccae web ui but when i start it, it stops o in the loading step. I even cleared all cookies. What can i do?

**Comment by vitalidze** [comment]
You should check web browser console for error messages.

**Comment by ekofficiel** [comment]
Hi vitalidze there is no error message it just keep on loading...
I just switched to mysql before installing your interface is it a problem?

**Comment by vitalidze** [comment]
Have you looked into web browser console? It should be in "developer tools"
menu.

пятница, 30 октября 2015 г. пользователь ekofficiel написал:

> Hi vitalidze there is no error message it just keep on loading...
> I just switched to mysql before installing your interface is it a problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/313#issuecomment-152456489
> .

## 

Kind regards, Vitaly Litvak

**Comment by ekofficiel** [comment]
Thank you it worked!
