### ISSUE TITLE
when the tracker is offline

### ISSUE THREAD

**Issue by edgiru** [vitalidze/traccar-web#314]
Sorry, I do not know who to write about this error whether you whether Tanaev

I noticed when the tracker does not transmit data, the server shows as if the car goes back to the same point as the come. ie the marker itself starts to move back to the recorded track.

rus:
Извините я не знаю кому написать про эту ошибку то ли Вам то ли танаеву
Заметил когда трекер не передает данные, сервер показывает как будто машина едет назад по тем же точкам как и приехала. т.е. маркер начинает сам перемещаться обратно по записанному треку.

**Comment by edgiru** [comment]
The selected check that the car track.

**Comment by vitalidze** [comment]
This sounds like an issue with device. What happens if you load track for that time period?

**Comment by mpele** [comment]
It is up to your device. It should be configured to send data in order they are recorded. The server, when process data it updates last position in order they are processed (and it is order that they are received) - so the last packet that is processed is the last position (in your case it is the first position of track).
This, also, have side effect on wrong calculation of odometer.

**Comment by edgiru** [comment]
я еще буду тестировать этот момент и Вам сообщу. Если получится даже видео запишу. Мне это показалось очень странным.

**Comment by vitalidze** [comment]
@edgiru есть какие-то новости на тему этой проблемы?
