### ISSUE TITLE
MD5 hach

### ISSUE THREAD

**Issue by ekofficiel** [vitalidze/traccar-web#315]
Hi i want to login into traccar from my website. Passwords are stored as md5 hash in db. So how can i convert plain text password entered by username to md5 hash in order to compare this value with the value stored in db? i tried many generator found on the web but the result is different from password hash generated by traccar (the one stored in db). So how can i do it please?

**Comment by vitalidze** [comment]
The password is hashed with salt, which is stored in database and is unique to each traccar installation (generated some random string). You can see current implementation of MD5 hash generation here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/PasswordHashMethod.java#L56

**Comment by ekofficiel** [comment]
in which table?

**Comment by vitalidze** [comment]
In `application_settings`.

**Comment by ekofficiel** [comment]
Ok thank you. I have another question out of this topic: how events can be notified to the user? only in the web interface or is there any other mean?

**Comment by vitalidze** [comment]
You are welcome.

I don't quite understand your question about events. Right now they are stored in a special table, which is scanned from time to time (every one minute for now) and when there are some recipients it sends notifications to them.

**Comment by ekofficiel** [comment]
Which recipient? I 'm new to this software and i wanted to know how a user is notified that for eg his car went out of geofence zone. How does he receive the alert?

**Comment by vitalidze** [comment]
Recipient is a user, which has access both to device and geo-fence (if event is for geo-fence). Notification is sent either through SMTP or through pushbullet. You can find code here https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/NotificationServiceImpl.java
