### ISSUE TITLE
Raspberrypi: Segmentation fault

### ISSUE THREAD

**Issue by dschense** [vitalidze/traccar-web#316]
Traccar is running well with Raspberrypi (B Version) with the arm.zip
But after changing the stuff to the modded traccar-web i get this error:

Segmentation fault
Waiting for traccar..................
WARNING: traccar may have failed to start.

seems the mod is not running with the arm architectur.

Is there a fix for this?

**Comment by vitalidze** [comment]
It is written in java as the original traccar project is. So if your device runs java then you should be able to run the web UI mod. Try running traccar as a console application (something like `/etc/init.d/traccar console`) and see if there will be more information. Most probably your PI has some issue, or your SD card has some issue.

Also I can tell that I know about the cases when traccar worked from the start but then the PI lacks the power to hold it and it starts to be very unstable. For example, if it uses the H2 database it becomes damaged again and again. That's just for the information.

**Comment by dschense** [comment]
At first thank you for the fast response.

i tried with running the server manually:

$ cd /opt/traccar
$ sudo java -jar tracker-server.jar conf/traccar.xml

this is what i get:

[MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
[main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
[main] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9c1gntlu21mavdl2|668893, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9c1gntlu21mavdl2|668893, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=*****_, password=**_***}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
[main] INFO org.eclipse.jetty.util.log - Logging initialized @18601ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.13.v20150730
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@ecf6c0{/,null,null}{/opt/traccar/traccar-web.war}
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:345)
        at org.eclipse.jetty.util.IO.copy(IO.java:162)
        at org.eclipse.jetty.util.IO.copy(IO.java:118)
        at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:240)
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:468)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:468)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:504)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.traccar.web.WebServer.start(WebServer.java:102)
        at org.traccar.Main.main(Main.java:31)
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@1af895e{HTTP/1.1}{0.0.0.0:8082}
[main] INFO org.eclipse.jetty.server.Server - Started @52529ms

Control + C to close server

[Thread-15] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@1af895e{HTTP/1.1}{0.0.0.0:8082}
[Thread-15] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@ecf6c0{/,null,UNAVAILABLE}{/opt/traccar/traccar-web.war}

maybe this can help to identify the problem.

maybe this could be the problem:

java.io.IOException: No space left on device

Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G  1.2G   27G   4% /
udev             10M     0   10M   0% /dev
tmpfs            44M  124K   44M   1% /run
/dev/mmcblk0p2   30G  1.2G   27G   4% /
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            88M     0   88M   0% /run/shm
/dev/mmcblk0p1  122M   41M   82M  34% /boot
tmpfs            88M     0   88M   0% /tmp

**Comment by vitalidze** [comment]
You are absolutely correct, this is the reason of your issue:

```
java.io.IOException: No space left on device
```

When traccar starts it unpacks the `traccar-web.war` to the temporary folder, which looks like is `/tmp` in your case and there are no space left.

**Comment by dschense** [comment]
Okay, fixed the first part:

increased the /tmp directore over the /etc/fstab file:
added -->

tmpfs /tmp tmpfs size=2G 0 0

restarted the Pi and started the traccar server manually again.

$ cd /opt/traccar
$ sudo java -jar tracker-server.jar conf/traccar.xml

it took a while, but the server is starting fine and shows up with its webinterface over the local ip and the port 8280.

---

But the wrapper service seems still to be broken.

with 

$ sudo service traccar start 

i still get 

Starting traccar...
Segmentation fault
Waiting for traccar..................
WARNING: traccar may have failed to start.

any idea?

**Comment by vitalidze** [comment]
Are you sure it works without web UI mod? It looks like an issue with the java service wrapper itself.

**Comment by dschense** [comment]
at the first run without web ui mod traccar server started fine with

sudo service traccar start

so yes, i am sure..

maybe i have to take other java version

this is running atm:

java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-6~deb7u1+rpi1)
OpenJDK Zero VM (build 24.85-b03, mixed mode)

maybe have to switch to:

OpenJFX on the Raspberry Pi
https://wiki.openjdk.java.net/display/OpenJFX/OpenJFX+on+the+Raspberry+Pi

**Comment by vitalidze** [comment]
Does it work now if you disable the web UI mod?

Your java version looks good, I don't think you should change it. The OpenJFX looks like a technology that will allow to run JavaFX applications on raspberry PI. I don't think it will help in your case because traccar is not a JavaFX application, but in theory you can give it a try because probably it comes with other version of java.

**Comment by dschense** [comment]
okay, i tried and removed the web ui mod.
started to clean traccar installation but getting the same error.

Starting traccar...
Segmentation fault
Waiting for traccar..................
WARNING: traccar may have failed to start.

I dont know what the problem is.

**Comment by vitalidze** [comment]
Yeah, me too. I suggest the two things:
- try to reinstall wrapper special for the raspberry PI architecture (arm-hf, or something like this, AFAIK there are two arm wrappers, I suggest to try both)
- do not use wrapper and just start traccar with java -jar command. It is possible to implement an `init.d` script that will call that command. You can google for it.

**Comment by dschense** [comment]
can you tell me where to find the special rpi wrapper?

**Comment by vitalidze** [comment]
I don't know. You should google for it. [This stackoverflow thread](http://stackoverflow.com/questions/16214468/java-service-wrapper-on-raspberry-pi) suggests to build it from sources right on the PI. On the [official web site](https://wrapper.tanukisoftware.com/doc/english/download.jsp#stable) there are `armhf` and `armel` versions, which I was talking about.
