### ISSUE TITLE
other Notifications

### ISSUE THREAD

**Issue by manjoel** [vitalidze/traccar-web#317]
Hallo,
is it possible to add other notifications for example i have configured my device on motion, so that when there is motion, the status is changing in traccar, now i want an notification on this or other status changings.

Greeds

**Comment by vitalidze** [comment]
Right now it is not implemented. But it is in plans. You can find roadmap on the official web site: http://traccar.litvak.su/roadmap.html

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
