### ISSUE TITLE
sensor Protocole  is always display

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#318]
Hello,

Unable to disable the       Protocole     sensor display  for 3 devices differents !
Thanks.

Waca

**Comment by vitalidze** [comment]
'Protocol' along with 'Odometer' in newer versions are not sensors. They are stored differently. But I think I can treat them as sensors too. I will think about it.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
