### ISSUE TITLE
[Feature request] Change marker icon when device idle

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#321]
Correct me if I am wrong but I don't think this has been mentioned before (maybe this #60 ). I think it would be nice while viewing the history of a device (archive) the icon of the marker changes when the vehicle is stationary (not moving or idle), that is when the speed == 0. Thus when looking on the map we can easily and quickly see when the vehicle has stopped.
Maybe something like the screenshot:
![proposal](https://cloud.githubusercontent.com/assets/10040858/11048090/8bdf54de-873e-11e5-8a94-2070e541e806.jpg)
The I is for idle or X for striking out more 

Thank you for the consideration

**Comment by vitalidze** [comment]
Actually I thought about some kind of overlay or icon somewhere near the marker, which will show some kind of status of device (like battery, direction, idle/moving, etc.). Don't have a full picture in my mind on how to implement it yet.

**Comment by gsiotas** [comment]
OK thank you for the consideration. Maybe something like #60 but the marker changes according to the state. Keep up the good work!

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
