### ISSUE TITLE
[Feature request] Using leaflet.js library for archive

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#322]
I don't know if it is possible but you can use the powerful [leaflet library](http://leafletjs.com/) that will help you with all things related to the map.
Moreover you can use [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) to cluster (make groups) of multiple points of the map. [Check this demo](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html) for a visualization.

**Comment by vitalidze** [comment]
I don't think it's worth to switch the library. I think the amount of work will be comparable with rewriting the whole UI to something other than GWT. The clustering is supported by the OpenLayers as well, you can see examples [here](http://demo.gwt-openlayers.org/gwt_ol_showcase/GwtOpenLayersShowcase.html)

**Comment by gsiotas** [comment]
Fair enough, I didn't know the use of GWT-OpenLayers. Maybe the implementation of [this](http://demo.gwt-openlayers.org/gwt_ol_showcase/GwtOpenLayersShowcase.html?example=Animated%20cluster%20with%20popup) for multiple points in the archive.
