### ISSUE TITLE
[Bug] Different color for direfferent devices' track in the archive

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#324]
Steps to reproduce:
1. From the archive choose device 1, period and then load (color blue)
2. From the archive choose device 2, period, different color (say color red) for the track (from the style menu) and then load
3. The tracks will be overlaid onto the map perfectly with their respective colors. (blue->device1 & red->device2)
4. If you zoom in or out on the map the first color (blue) will be replaced with the second one. Thus all the tracks will be painted red.

This happens for more than 2 devices.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
