### ISSUE TITLE
New 3.2 X UI WEB

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#326]
hello the new 3.2 version was launched traccar my question is Web UI is compatible with is new version.

**Comment by vitalidze** [comment]
Yes, it is compatible. However, it requires different configuration. I will update instructions in nearest future. Basically, from what I know instead of this line in configuration file:

```
 <entry key='web.old'>true</entry>
```

You will need to put

```
 <entry key='web.type'>old</entry>
```

Then it both deploy the web UI mod and will expose the API. This will will allow to send commands from the web UI mod (not yet implemented, but technically it will be possible).

**Comment by ghost** [comment]
Vitaly Hello, I have the latest version 2.x installed and running, is there any way to use this new UI WEB, without making changes in the database?

**Comment by vitalidze** [comment]
@Mikelord2 you can use my web UI with 2.x without making any changes in the database, just replace the `traccar-web.war` file as said in instructions for 2.x version here: http://traccar.litvak.su/installation.html

**Comment by ghost** [comment]
Ops, I just do it as well as the instructions say, but I still see the same interface :( I do something else missing?

**Comment by vitalidze** [comment]
Why do you think the interface is same? What do you expect to change?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10438858/11183073/6d0dc8fa-8c4e-11e5-8e3b-93035f36025e.png)

I have that interface and see that there is another that is more advanced

![image](https://cloud.githubusercontent.com/assets/10438858/11183127/c1451e0a-8c4e-11e5-967a-06074cf52a24.png)

**Comment by vitalidze** [comment]
@Mikelord2 this is not yet released. It will be released later this week. I just deployed it on demo server for testing. Keep watching over news on the web site: http://traccar.litvak.su/news.html

**Comment by ghost** [comment]
Ops, apologies for being so impulsive, anxious wait with this improvement, congratulations on your work!

**Comment by vitalidze** [comment]
Released, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
