### ISSUE TITLE
Firefox and reports

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#327]
It looks like that reports doesn't work with firefox. 
I haven't noticed any errors - just, nothing happens when it is clicked on Generate.

**Comment by vitalidze** [comment]
Thanks for reporting. I confirm that it does not work for me in firefox as well.

**Comment by gpproton** [comment]
This same issue affects Microsoft edge browser.

Omonluimhen Godwin Peter

IT/Tracking
Officer | Beta Bridges Ltd

+2348083353682

godwin@betabridges.com

godwin@peter.com.ng

Date: Mon, 16 Nov 2015 09:43:56 -0800

**Comment by vitalidze** [comment]
I have fixed the issue. Now it works fine in both firefox and chrome. The fixed version is deployed on demo site https://d.traccar.litvak.su/ @gpproton can you please try running reports from Microsoft Edge web browser?

**Comment by mpele** [comment]
It works now :)
Great work!
May I ask - why it is forced to report be saved before it is opened? Why doesn't it silently open in new tab?

**Comment by vitalidze** [comment]
My goal was to implement a self-contained reports, which can be then distributed anyhow. Probably in next versions it will be possible to save reports in formats other than HTML.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by mpele** [comment]
I would like to suggest that the "initial" report should be in new tab and
on that page should be link/button for saving report in available formats.

**Comment by vitalidze** [comment]
I don't see much value in this. As I have seen in existing reports they work in similar way. Some of them try to display report in same window, but it will be too much for the web UI especially if report is big enough.

Current implementation also may allow to set up a schedule and then send reports by emails. I believe this is a better use-case for reports.

**Comment by vitalidze** [comment]
I will think about adding some kind of option to 'Preview' report in a separate tab. It should be quite easy to implement, but the use-case is still not very clean for me.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
