### ISSUE TITLE
Lower Report area Disappeared

### ISSUE THREAD

**Issue by angelburgos** [vitalidze/traccar-web#328]
Please provide insight on how to recover the lower part of the main window.  Today I realized that there is no area to do reports or see tracking hIt was and has been there but for some reason it's gone.  Please advise.  Thank you.
![image](https://cloud.githubusercontent.com/assets/15667566/11197491/3c49537e-8c94-11e5-8338-b9f21fef8272.png)

**Comment by vitalidze** [comment]
Looks like your account does not have access to the archive. In most recent versions of the web UI it is possible to disable archive for a user. If it is disabled then you won't be able to load archive and also the bottom panel will be hidden.

**Comment by gpproton** [comment]
Turn on archive on the user window it will come back

Godwin Peter .O
IT /Tracking Officer | Beta Bridges Ltd
Godwin@Betabridges.com
+2348083353682

**Comment by angelburgos** [comment]
Thank you both for the support.  Godwin, how can I turn it on again the archive for user window?  Or Vitalidze, how can I update my web GUI?.  I really appreciate your input gentlemen.  Thanks.

**Comment by vitalidze** [comment]
You need to log in as the system administrator or manager user and then in Settings>>Users check the "Archive" box in the line with your user account.

**Comment by angelburgos** [comment]
Thanks for the update.  There is no archive button or anything similar.  I have clicked all and have not found it.  Is it possible that a change be done in an internal file or xml?  Am sorry for the insistence, but your update finally gives functionality to the Traacar project.  Can you offer another solution or is there a way to PM with you?  I appreciate your time very much.  

Update:  I found where to do the change.  But would like to PM if possible.  Have a project to share and would like your insight.  Thanks again.

**Comment by vitalidze** [comment]
You can find my email in github profile.
