### ISSUE TITLE
Reports and 24h

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#329]
Hi Vitaly,

I have just tried report Drives and stops and noticed something strange.

The summary of report for one day (24h) is:

Route length: 24.74 km 
Move duration: 1h 4m 40s  
Stop duration: 21h 25m 41s  
Top speed: 49 km/h 
Average speed: 23.1 km/h 

It looks like that there is some error because the sum of move duration and stop duration is 22h 30m - there is missing 90 minutes. 
I have noticed that device have first record at 00:39:09 and last at 23:09:30.

**Comment by vitalidze** [comment]
If you have first position not at 00:00 and last position not at 23:59 then
you shouldn't expect the 24h in total.

вторник, 17 ноября 2015 г. пользователь mpele написал:

> Hi Vitaly,
> 
> I have just tried report Drives and stops and noticed something strange.
> 
> The summary of report for one day (24h) is:
> 
> Route length: 24.74 km
> Move duration: 1h 4m 40s
> 
> Stop duration: 21h 25m 41s
> 
> Top speed: 49 km/h
> Average speed: 23.1 km/h
> 
> It looks like that there is some error because the sum of move duration
> and stop duration is 22h 30m - there is missing 90 minutes.
> I have noticed that device have first record at 00:39:09 and last at
> 23:09:30.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/329.

## 

Kind regards, Vitaly Litvak
