### ISSUE TITLE
[Bug] Strange button in 0.9.0 redesign

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#330]
![bug](https://cloud.githubusercontent.com/assets/10040858/11216150/6c469ce4-8d52-11e5-938c-907263dd1313.png)
I have mark it up with a red arrow, this happens in FF, GC and Safari.

**Comment by vitalidze** [comment]
This is a "separator" element. In previous theme it looked differently. I know about it, but I hesitate about removing.

**Comment by vitalidze** [comment]
Actually this was a button used to display color of the track line. Will be fixed in next version.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
