### ISSUE TITLE
Mobile version error

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#331]
Hello after upgrading to the new UI user interface in the mobile version can not log in with my username and password, the web desktop this perfect.
this happens with multiple user even editing new login password is impossible login.

**Comment by vitalidze** [comment]
I have just checked two of my servers: demo and a private one. Both work just fine both from the desktop browser and from iPhone safari. Are you able to log in to the mobile version from desktop browser?

**Comment by MarceloMJM** [comment]
I'm using Android
Access mobile desktop version normally.

Desktop browser is fine.
![2015-11-17 16 17 11](https://cloud.githubusercontent.com/assets/9204676/11220424/259b732e-8d47-11e5-9816-835276ccc421.png)

![2015-11-17 16 19 37](https://cloud.githubusercontent.com/assets/9204676/11220561/c3b662b2-8d47-11e5-814a-f1477ae50bc0.png)

**Comment by vitalidze** [comment]
Maybe this is an issue with some script cache on your android mobile device. Try to clean it up. I don't have android device for testing.

**Comment by MarceloMJM** [comment]
I believe it is not browser cache problem , why not with all users, only a few users .

My normal administrator account access.
Manager does not have access .

As much as log with admin and change the password the problem persists.

Tested with iPhone also on safari

**Comment by vitalidze** [comment]
Can you log in to your account in mobile version from the desktop browser after changing the password?  I need a way to reproduce the issue. For now I cannot do it.

**Comment by vitalidze** [comment]
The only issue I can see is that popped up message 'Username or password invalid' does not disappear when you click on 'Ok' button.

**Comment by MarceloMJM** [comment]
Some characters missing , and then click OK it does not disappear .

But if the username and password is correct OK disappears , but not logs.

**Comment by vitalidze** [comment]
There was some mess with the .css files of the Framework7 library and I have now fixed this and uploaded the updated version to the demo site. Can you please check whether the issue reproduce for you there?

**Comment by MarceloMJM** [comment]
On its website demo is running !

**Comment by vitalidze** [comment]
You mean the issue does not reproduce on the demo site (https://d.traccar.litvak.su/)? If so then probably libraries update/correction fixed it. The fix will be included in next release, which should come later this week or at the beginning of next week.

**Comment by MarceloMJM** [comment]
On your site is perfect.
Thanks for your great work

**Comment by alvarengasv** [comment]
I was able to reproduce this. Setting the max number of devices to any number locks the user out of the mobile version. The only value that works is leaving it empty.

**Comment by vitalidze** [comment]
@mrpoopy confirmed. Will be fixed in next release version. Thanks.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
