### ISSUE TITLE
[Bug] 17 Nov 2015 update doesn't display speed limit

### ISSUE THREAD

**Issue by alvarengasv** [vitalidze/traccar-web#332]
You can set the device's speed limit and it shows the value in the devices table but if you select the device again in your browser the speed limit field is empty. Click on save again and the value will be saved as null in devices.

**Comment by vitalidze** [comment]
Confirmed, it reproduces for me as well.

**Comment by alvarengasv** [comment]
It's working correctly thanks.

**Comment by vitalidze** [comment]
I intend to close this issue when the next version is released.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
