### ISSUE TITLE
[Question] Should I update to traccar v3.2?

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#334]
Sorry for asking maybe a newbie question but  tananaev released version 3.2 of traccar 4 days ago. Should we proceed with the update? Or this will break the functionality of the traccar-web?

Thanks!

**Comment by alvarengasv** [comment]
I had to go back to 3.1. The custom website doesn't load with 3.2.

**Comment by ghost** [comment]
Hello,  I just made a new Xubuntu/Virtual computer.
As it's free of any software, I follow the instructions installing  traccar3.2  and instructions for Litvak installations.
traccar always run the 'Anton' 3.2 and no way to have the Litvak one.
I prefer that Litvak give some more informations about the compatibility.

**Comment by vitalidze** [comment]
It is compatible for sure. I didn't got a time to test the release version, but an intermediate version made before release work for sure. All you have to do besides the 3.1 instructions is to change one configuration value as said here: https://github.com/vitalidze/traccar-web/issues/326#issuecomment-157021517

**Comment by ghost** [comment]
Ok for me with :
modify
 <entry key='web.old'>true</entry>
You will need to put
 <entry key='web.type'>old</entry>

Thanks.

**Comment by vitalidze** [comment]
Updated [installation instructions](http://traccar.litvak.su/installation.html) for the 3.2
