### ISSUE TITLE
[Bug] manager's manager can see the the button to add new devices but it doesn't save

### ISSUE THREAD

**Issue by alvarengasv** [vitalidze/traccar-web#335]
I think the button should be hidden. Only the first level manager should be able to add devices.

**Comment by vitalidze** [comment]
From this description I don't understand the case. Why manager's manager should not be able to add devices?

**Comment by alvarengasv** [comment]
Sorry for the confusion. This is the real issue:
- add manager #1. Set max devices to 1.
- log in as manager #1 and add manager #2
- log in as manager #2
- Add device #1 and save. The device is saved correctly.
- Add device #2 and save. It doesn't save. That is correct but it should show an error. If you try to add device #1 while logged in as manager #1 it shows an error.

**Comment by vitalidze** [comment]
I don't see anything wrong in this case. If you want to restrict underlying managers from adding devices you have two options:
- set the underlying manager to 'read-only'
- set the devices limit to 0

As discussed in #214 and #215 the devices number restriction is applied to the whole hierarchy below any manager.

**Comment by alvarengasv** [comment]
Yes I understand that but the second manager doesn't see the error message "Limit on number of devices is reached (max 1)". This message is shown correctly while logged in as the first manager.

When the second manager clicks on add it asks for the device configuration and the save fails without an error message.

**Comment by vitalidze** [comment]
Oh, I see, so this is about error message display. I will check this out. Thank you.

**Comment by vitalidze** [comment]
Confirmed, will be fixed in next release version.

**Comment by vitalidze** [comment]
I intend to close this issue when the next version is released.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
