### ISSUE TITLE
[Bug] setting "Google Normal" in preferences shows blank map after login

### ISSUE THREAD

**Issue by alvarengasv** [vitalidze/traccar-web#336]
You can see this in the demo:
https://d.traccar.litvak.su/
user: bugdemo
pass: bugdemo

It works if you expand the maps on the right and switch to a different map then go back to "Google Normal".

**Comment by vitalidze** [comment]
I confirm that this is a bug. It was already reported couple of months ago in #249, but it looks like according to [stackoverflow thread](http://stackoverflow.com/questions/32335221/google-maps-api-change) and [this issue](https://github.com/openlayers/openlayers/issues/1450) the version 3.20 of google maps API should pass out very soon. And it looks like it is already not available, which breaks this function. I don't know how to handle it yet.

**Comment by vitalidze** [comment]
According to [this thread](https://groups.google.com/forum/#!topic/google-maps-js-api-v3-notify/prpOYuTs6jk) they have removed support for 3.20 yesterday.

**Comment by vitalidze** [comment]
I have included fix to the OpenLayers script. Now it works fine in my testing environment. Fix will be included in next release.

**Comment by alvarengasv** [comment]
Thanks I have confirmed it's working.

**Comment by vitalidze** [comment]
I intend to close this issue when the next version is released.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
