### ISSUE TITLE
Google map is not working

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#337]
The map is not displaying anytime google map is selected but other map are working.

![screenshot 20](https://cloud.githubusercontent.com/assets/11395006/11237551/ef340ca2-8de0-11e5-8770-bbc43c345b9b.png)

**Comment by vitalidze** [comment]
See #336

среда, 18 ноября 2015 г. пользователь gpproton написал:

> The map is not displaying anytime google map is selected but other map are
> working.
> 
> [image: screenshot 20]
> https://cloud.githubusercontent.com/assets/11395006/11237551/ef340ca2-8de0-11e5-8770-bbc43c345b9b.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/337.

## 

Kind regards, Vitaly Litvak

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
