### ISSUE TITLE
Marker stay fixed on the map since i updated to last version

### ISSUE THREAD

**Issue by noar1912** [vitalidze/traccar-web#339]
Yesterday I upated to the last version (previous was installer the 07/07/2015) with traccar 3.0.

Since this update my markers stay fixed to the point before the update and doesn't moove anymore (my cars has mooved)
I restarted teh service, reboot the server, reinstalled previous version and still the problem even with the older version.

**Comment by vitalidze** [comment]
Sounds like an issue from #282 Please try the [suggested solution](https://github.com/vitalidze/traccar-web/issues/282#issuecomment-150181388)
