### ISSUE TITLE
Configurações dos parametros de sensores

### ISSUE THREAD

**Issue by rafaelolivei** [vitalidze/traccar-web#340]
Boa tarde amigo!

gostaria de entender como e feita a configuração dos parametros para os sensores de um dispositivo.
Verifiquei no site, porém não consegui compreender, adquiri um rastreador CRX1 que usa a mesma base de protocolo do GT06. Porém estou tendo dificuldades de cadastrar os parâmetros. Onde consigo esta informação?

**Comment by vitalidze** [comment]
You can find all necessary information on the official web site here: http://traccar.litvak.su/features/sensors.html

**Comment by clinicamatiz** [comment]
when an event is generated by sensor, no email is sent?

**Comment by vitalidze** [comment]
@clinicamatiz currently events in the means of the system are not generated for sensors, all available types of events are in a list of user profile.
