### ISSUE TITLE
In english remove lines for 'yesterday'

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#344]
In English UI, if I  snap to road for  yesterday,  lines are not display.

**Comment by vitalidze** [comment]
Please add an example of track, where it does not work for you. 'Yesterday' only sets up the time period, it should be no difference in loading of snapped positions. Does it show track if you don't check the 'snap to roads' box?

**Comment by vitalidze** [comment]
Any update on this issue?
