### ISSUE TITLE
[Bug] Wrong encoding in email subject when utf8 charactes used

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#347]
If setting custom subject to email notifications and the title contains utf-8 characters it displays it with ANSI encoding

From the headers of the email I am receiving:

```
Subject:    =?ANSI_X3.4-1968?Q?[gps]_->_=3F=3F=3F=3F=3F=3F=3F=3F=3F=3F_'S5'?=
MIME-Version:   1.0
Content-Type:   text/plain; charset=utf-8
Content-Transfer-Encoding:  base64
X-Mailer:   traccar-web.sendmail
```

the set variable in the UI is: 

> [gps] -> Αποσύνδεση '${deviceName}' 

(Notice the greek characters)

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by gsiotas** [comment]
Thanks!

**Comment by vitalidze** [comment]
Does it work now?

**Comment by gsiotas** [comment]
Yes this works, thank you!
