### ISSUE TITLE
Color lines display

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#349]
Hello,

Using a tablett in "desktop display", no way to have in the bottom the 'style' button

**Comment by vitalidze** [comment]
You mean you can't see the color label? The buttons to select colors should be present.

**Comment by ghost** [comment]
I understand what happen, if I reduce the browser size as it can't display ALL the bottom butons and so, display the     >>      ,inside THIS  >>   ,     all hidden buttons are not displayed.

**Comment by vitalidze** [comment]
I think it cannot be fixed anyhow from my side, this is a sencha GXT library to blame.
