### ISSUE TITLE
Snap to road as "user's parameters"

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#350]
Hello,

Is it possible to have this  Snap to road  allways enable for all or specific users when he login ?

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
