### ISSUE TITLE
Allow for custom mapping URL in reports

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#351]
Hi Vitaly,

Nice work with the new version. I'm bumping use internally :)

A nice feature would be to have custom links in the reports:
![image](https://cloud.githubusercontent.com/assets/6171197/11299259/3fb40d56-8f7d-11e5-8f7d-eacc9b516d90.png)

Within the user's preferences, he could override the default ones (I believe they are in mapLink method in ReportGenerator.java) but still passing Lat & Long

That way, instead of point to google maps or openstreetmap, it could point, for example, to an internal mapping solution (with a bunch of other data).

What do you think?

**Comment by vitalidze** [comment]
Sounds like a very custom case. I don't think it's valuable. You can easily develop it yourself by changing the `mapLink` method in `ReportGenerator` class as you correctly mentioned.

**Comment by vitalidze** [comment]
Probably the better way would be to add a possibility to add a custom mapping solution (like it was done in original traccar project). But no one requested it yet and I doubt about this.

**Comment by antoniopaisfernandes** [comment]
OK then. I'll try to do it (don't really know if I can until I try :))

**Comment by antoniopaisfernandes** [comment]
I've committed some changes but can't seem to have the data stored in the database:
https://github.com/antoniopaisfernandes/traccar-web/commit/4e893d9fe4bac87549b0fd39d21f20b93448cf24

Can you please take a look?

What do you think about this approach:
![image](https://cloud.githubusercontent.com/assets/6171197/11326407/e88e5960-9160-11e5-9339-be8d9b556e2e.png)

**Comment by vitalidze** [comment]
You need to update the `copyFrom` method in `UserSettings` class for the property to be saved. You can observe this commit https://github.com/vitalidze/traccar-web/commit/9a6a0c7a7772b5938611b9a009aad4a9ba315645 where I am adding the `maximize overview map` setting.

As for the changes, I doubt anyone besides you will need this function. Thus, I don't want to merge it to upstream for now. 

I still believe that the better approach would be to add the new map types (like supply the tile url) along with such custom URL type. In this case it will be present on an upper level so you won't have to maintain this setting for all users.

**Comment by antoniopaisfernandes** [comment]
That's wierd... I've added that:
![image](https://cloud.githubusercontent.com/assets/6171197/11333858/b8bef902-91c8-11e5-918e-ad28997a6aee.png)

**Comment by vitalidze** [comment]
I see. Excuse me, I have missed it. Then you need to define a field in `UserSettingsDialog` with the name equal to the name of property.

**Comment by antoniopaisfernandes** [comment]
Missed that completely. Thank you so much.

**Comment by antoniopaisfernandes** [comment]
It works very nicely:
![image](https://cloud.githubusercontent.com/assets/6171197/11343823/d3128b1a-9205-11e5-90c6-ab9a86339978.png)

Thank you so much. I now have the trouble of finding how can I merge manually :(
