### ISSUE TITLE
mileage report ?

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#353]
hi all

 when i generate mileage report it is empty ,just info about device and the period for the report ?

i tried to select a long period but no data .

what data should appear in this report .

**Comment by gsiotas** [comment]
Yes I can confirm this happening to me as well.

**Comment by alvarengasv** [comment]
The report is showing the correct milage for me. Did you enable automatic milage in the device's maintenance settings?

**Comment by gsiotas** [comment]
No I didn't enable it. Thanks for the recommendation I enabled it and I will report back.

**Comment by xizoaziz** [comment]
thanks @mrpoopy  . i will enable it and check .

**Comment by vitalidze** [comment]
Actually this report does not depend on the 'automatic' mileage calculation. It shows the total distance for each day. If it does not show you anything then maybe your device/vehicle was not moving within the period? Also it's worth to check log file for error messages.

**Comment by xizoaziz** [comment]
hi vitalidze  
the device moved . i change the period for the report to a long period but the same thing. and no error in log.

hi @gsiotas  did it work ?

**Comment by vitalidze** [comment]
Does archive show you some distance when you load it for the same period for the same device?

**Comment by vitalidze** [comment]
There is some issue with the report. I confirm that it does not work for me too.

**Comment by xizoaziz** [comment]
it is working now .

but i think  ignore position with zero speed is needed, because you know some time device is stop but send different coordination which gives  a small distance .

if we have 1000 position withe average 2 m between them so it is 2 KM  my be in a day .

so i think 0 speed must add as a filter.

**Comment by vitalidze** [comment]
You can set up filter in archive, then it is applied to all reports.

воскресенье, 22 ноября 2015 г. пользователь xizoaziz написал:

> it is working now .
> 
> but i think ignore position with zero speed is needed, because you know
> some time device is stop but send different coordination which gives a
> small distance .
> 
> if we have 1000 position withe average 2 m between them so it is 2 KM my
> be in a day .
> 
> so i think 0 speed must add as a filter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/353#issuecomment-158786344
> .

## 

Kind regards, Vitaly Litvak

**Comment by xizoaziz** [comment]
yes it working very good . :+1: 

thanks @vitalidze

**Comment by gsiotas** [comment]
Yes after fiddling around with the reports, it works.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
