### ISSUE TITLE
[Feature request] Mini map

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#354]
On another tracking server there is this feature of a mini map at the lower left corner of the main map. Check screenshot:
![screen shot 2015-11-21 at 2 47 16 am](https://cloud.githubusercontent.com/assets/10040858/11315437/5e919c2a-8ffa-11e5-8085-58198a6d6687.png)

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/11/24/Reports%E2%80%93preview,-stop-and-moving-events,-several-bugs-fixed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by gsiotas** [comment]
It works great thanks!
