### ISSUE TITLE
remote procedure call eroor 

### ISSUE THREAD

**Issue by mirzaumair** [vitalidze/traccar-web#355]
when i login to my web penal it show 
remote procedure call error

**Comment by vitalidze** [comment]
Web penal? What is it? I guess a typo.

You need to check wrapper.log file for error messages.

**Comment by vitalidze** [comment]
Any update on this issue?

**Comment by kamil55** [comment]
I sometimes have this message - remote procedure call error
Not always - accidentally

```
INFO   | jvm 1    | 2015/12/06 16:02:48 | [qtp629882597
INFO   | jvm 1    | 2015/12/06 16:02:48 | [qtp629882597WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/12/06 16:02:48 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getDevices()' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/12/06 16:02:48 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
```

**Comment by kamil55** [comment]
wrong schema ? table devices ?
![1](https://cloud.githubusercontent.com/assets/16177382/11613999/683d4558-9c34-11e5-9c21-a0d22151e013.jpg)
![2](https://cloud.githubusercontent.com/assets/16177382/11614000/6e66c742-9c34-11e5-8d27-f4a3b02bdba1.jpg)

can delete Keyname PRIMARY ?

**Comment by kamil55** [comment]
![3](https://cloud.githubusercontent.com/assets/16177382/11614169/34be9b86-9c3a-11e5-8140-9a3020cd8618.jpg)
can delete Keyname PRIMARY ?

and 

INFO   | jvm 1    | 2015/12/06 16:46:12 | [qtp629882597-71] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/12/06 16:46:12 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.GroupService.getGroups()' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/06 16:46:12 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/12/06 16:46:12 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)

**Comment by vitalidze** [comment]
@kamil55 why are you posting your questions/issues in this thread?

Regarding `JDBC begin transaction failed` most probably it is caused by some connectivity issue. To say for sure please post full stack trace of the error when it reproduces.

As for the keys, I guess you can drop the 'PRIMARY' one. Looks like it is created by MySQL automatically, most probably it should not affect anything except these warnings.

**Comment by kamil55** [comment]
![1](https://cloud.githubusercontent.com/assets/16177382/11621880/c63209be-9cc0-11e5-9ee0-2f09c267ddeb.jpg)

remote procedure call error occurs after after login admin (08:45:26)
then everything works normally
[logs-etc.zip](https://github.com/vitalidze/traccar-web/files/53597/logsetc.zip)

**Comment by vitalidze** [comment]
I don't think it is related anyhow with the administrator user. According to the log file from time to time traccar gets disconnected from the MySQL. Probably it happens due to some non-standard timeout settings. Check this thread https://github.com/vitalidze/traccar-web/issues/176#issuecomment-111690177 for additional information.

**Comment by kamil55** [comment]
Thanks
my.cnf was set
wait_timeout = 60
after edit
wait_timeout = 600
is OK
