### ISSUE TITLE
[Bug] Java OutOfMemoryError when selecting more than 6 months period

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#358]
In the archive panel when I select more than 6 months period to load, my browser freezes for about 30'' and the I get a remote procedure error. In the log file I get this:

```
INFO   | jvm 1    | 2015/11/24 00:41:03 | java.lang.OutOfMemoryError: Java heap space
STATUS | wrapper  | 2015/11/24 00:41:03 | The JVM has run out of memory.  Restarting JVM.
```

Running a mysql query to the database I can see that it should return 75112 records.
There should be a try catch, to inform the user of this.

Thank you for the consideration

**Comment by vitalidze** [comment]
This is not a normal situation. The try..catch will not work in such case. It's up to you as a system administrator to set up your server for handling such number of records - either increase amount of memory allocated to your application, or set up archive pruning, so the old records will be removed.

**Comment by gsiotas** [comment]
Ok thank you for your prompt answer!
