### ISSUE TITLE
[Bug] Overall lag when showing multiple markers from archive.

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#359]
I have used traccar-web almost two months now, and overall I can say that @vitalidze has done an excellent software. 

My major drawback is when in the map there are many markers my web browser lags. I have tried in multiple machines and OS and I can watch the same behavior everywhere. The browser loads the markers relative fast (around 10 seconds) but when displaying it lags very much. Especially when I scroll the map to see the path then the CPU load of my computer tops up and the browser fails to respond properly. Moreover when selecting multiple months to show the archive then I get a Java Out Of Memory Error (further details here: #358). 

My suggestions are:
1. Maybe there should an option in the filter like this "create track omitting every 3rd/4th/10th marker" or oad only 100/200/300 markers evenly distributed. This of course means that we will lose accuracy on the results but I think overall the software will run smoother
2. Something like a smart load of the markers depending on the speed/distance/course. Thus not loading all the markers but only those needed to properly show the path.
3. Maybe it is better not to load metadata for each marker. I mean when selecting load to load a specific path it loads the metadata for each marker (the data showed when you hover your mouse over a marker) for the specific time period/path thus increasing the loading time. This data can be loaded afterwars when hovering the mouse and triggering a AJAX load.
4. Maybe not showing the markers at all on the track. There is a similar option in the style menu but this again loads the markers.

Please feel free to add/comment to my issue, as I think we can help Vitaly make this software run smoother and faster, thus eliminating this only major drawback I can think of.

Thank you

**Comment by vitalidze** [comment]
For handling large number of points you should use a 'no markers' mode, which is specially designed for that and is known to work fine for 100K of points. This mode is turned on by default.

You can also use filtering to reduce the number of markers.

**Comment by gsiotas** [comment]
I managed to increase the memory allocated to java from the OS and I am using the 'no marker' mode, it seems that it goes smoother. I still think that there should be an option to not load the metadata for each marker (see my previous comment, point 3), and that will increase the speed of the application.

**Comment by vitalidze** [comment]
The thing is that from my investigation metadata does not affect the loading time that much. The reason of lagging is the number of objects drawn on map. So the only way to speed things up is to apply some filtering. Then, from my investigation the single line option is the best thing we can do for now.
