### ISSUE TITLE
[Bug] Not displaying correctly the buttons of the archive when re-sizing browser's window

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#361]
i don't know if that is a bug or if it is intentionally, but when re-sizing my browser's window and make it smaller some elements of the archive panel disappear.

See pictures below:

Full width: 
![screen1](https://cloud.githubusercontent.com/assets/10040858/11357801/f55fb09e-9273-11e5-8d05-e91b672eed5f.png)

When making the windows smaller we lose the style button
![screen2](https://cloud.githubusercontent.com/assets/10040858/11357800/f55b7b6e-9273-11e5-905c-879dcbc81f6e.png)

When making even smaller the window we lose the "style", "disable filter" and "snap to road" option. 
![screen3](https://cloud.githubusercontent.com/assets/10040858/11357799/f5551878-9273-11e5-9dc3-0782a752c2cb.png)

**Comment by vitalidze** [comment]
This is the current limitation of the GXT library. Nothing can be done here.

**Comment by gsiotas** [comment]
Ok thank you for your prompt answer!
