### ISSUE TITLE
[Feature request] Show spinning gif when loading results from the archive.

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#362]
When loading tracks from the archive that takes more than 2-3'' to load, I think it is a good practice to show a loading spinning gif somewhere or in a modal dialog to inform the user that there is a process running in the background and the browser hasn't stop.

Thank you for the consideration.

**Comment by vitalidze** [comment]
I thought about it for many times. The tricky thing here is to not show the spinner until it is really loading for a too much time to not annoy the user (I don't like blinking). Probably it can be worked out some how with timers.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by gsiotas** [comment]
Very good! Nice work Vitaly! I have one minor question that I describe here: #648
