### ISSUE TITLE
Achieve playback animation and Folder grouping

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#363]
I think it would be ok if the the web interface can do a live playback of the selected period in the achieve, this feature is also available i most web tracking platform. This will enable users see all the movement for the selected vehicle without having to read or scroll through lengthy achieved reports of the vehicles.
Lastly folder grouping would also if virtual folders are available to group tracking devices with different purpose or even owners it would be really pleasant.
![folder](https://cloud.githubusercontent.com/assets/11395006/11367598/fbf6ffe8-92b4-11e5-893a-5217684cea74.PNG)
![folders_tramigo](https://cloud.githubusercontent.com/assets/11395006/11367597/fbb1ff4c-92b4-11e5-95d9-f014b833eebb.PNG)

**Comment by gsiotas** [comment]
:+1:

**Comment by viktorovac** [comment]
I need grouping tracking devices by owners/company, pleas add group folder

**Comment by xizoaziz** [comment]
i think it will be great if there is a sub group also

**Comment by vitalidze** [comment]
Folder grouping implemented, written [news](http://traccar.litvak.su/2015/12/02/Commands,-devices-groups,-couple-of-bugs-fixed.html), updated [demo](http://traccar.litvak.su/demo.html) and [latest](http://traccar.litvak.su/installation.html) versions.

**Comment by gpproton** [comment]
Great job Litvak but i'm hope the Achieve playback animation will be implemented soon.

Omonluimhen Godwin Peter

IT/Tracking
Officer | Beta Bridges Ltd

+2348083353682

godwin@betabridges.com

godwin@peter.com.ng

Date: Wed, 2 Dec 2015 00:19:17 -0800
