### ISSUE TITLE
[Feature request] More options in the notifications menu

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#364]
I think it will be useful if there was variable in the notification menu with the position data. For example ${positionTime} show the time of the position the event occurred. There should be a variable ${positionData} that will show all available data for the connected position: long. lang., speed, angle etc.

Thus when receiving email we can see the exact point where the event occurred. It will also be useful if there is a link to the point (in openstreetmaps) as in the reports.

Or there can be more variables like those: $(positionSpeed), $(positionAngle) etc. for more customization options.

This will be very usefeull when receiving an overspeed email, to have the speed of the position the event happened.

Thank you.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/12/02/Commands,-devices-groups,-couple-of-bugs-fixed.html), updated [demo](http://traccar.litvak.su/demo.html) and [latest](http://traccar.litvak.su/installation.html) versions.

**Comment by gsiotas** [comment]
Impressive! Thank very much, I can confirm it works!
