### ISSUE TITLE
Geo-fences

### ISSUE THREAD

**Issue by wagnerdracha** [vitalidze/traccar-web#365]
Hi, 

How does geofences on your system?

I would like to add some commands, but I understand some java.

Can you help me?

**Comment by vitalidze** [comment]
I don't understand your question. The documentation on geo-fences reside here: http://traccar.litvak.su/features/geofences.html

What commands are you talking about?

**Comment by wagnerdracha** [comment]
Good Morning,

So I would like to make a change in geofences so that when the car enters
the fence, the system sends a command "stop engine".

I tried to look in your source code where the traccar check that the car is
inside the fence, but as I understand some java, I could not.

Thank's

2015-11-25 2:45 GMT-02:00 Vitaly Litvak notifications@github.com:

> I don't understand your question. The documentation on geo-fences reside
> here: http://traccar.litvak.su/features/geofences.html
> 
> What commands are you talking about?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/365#issuecomment-159490973
> .

## 

Atenciosamente,
Wagner Drachinski,
(47) 9944-2785
www.drachinski.com.br

**Comment by vitalidze** [comment]
Here is the place where the geo-fences enter/exit events are detected: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/EventServiceImpl.java#L186

Actually it is always posting events, so maybe you can just scan them for the newly added events and then do some action when new event is registered.

**Comment by wagnerdracha** [comment]
Thank's!

Another question, I don't know a lot about Java, so for me it's a little
hard to understand. I tried to add a button, but I could not.

So I wonder if the Traccar is made up of some java framework? Or do you
have a tip for me to understand a bit how it works?

I appreciate your help.

PS .: Sorry for my English.

2015-11-25 7:50 GMT-02:00 Vitaly Litvak notifications@github.com:

> Here is the place where the geo-fences enter/exit events are detected:
> https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/EventServiceImpl.java#L186
> 
> Actually it is always posting events, so maybe you can just scan them for
> the newly added events and then do some action when new event is registered.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/365#issuecomment-159552865
> .

## 

Atenciosamente,
Wagner Drachinski,
(47) 9944-2785
www.drachinski.com.br

**Comment by vitalidze** [comment]
This software is written in java with [Google Web Toolkit](http://www.gwtproject.org/), [GXT](https://www.sencha.com/products/gxt/) and [GWT-OpenLayers](http://gwt-openlayers.org). You need to learn java to understand how it works.

**Comment by wagnerdracha** [comment]
Hi, 

At what time of verification of Geo-fences, the traccar send the email?

I don't found in: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/EventServiceImpl.java#L186

Thanks

**Comment by wagnerdracha** [comment]
I want to create a new type of notification through facebook, and then the Geo-fences the register, choose the type of sending the notification (email, facebook and pushbullet).

**Comment by vitalidze** [comment]
`EventService` is used to register events (i.e. save events to the database). The sending of notifications happens in [NotificationService](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/NotificationServiceImpl.java)
