### ISSUE TITLE
Problem with devices

### ISSUE THREAD

**Issue by ALAxHxC** [vitalidze/traccar-web#367]
Hello , when i connect devices to server , log's create this waring:
WARN: Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'address' at row 1 - SQLException (... < QueryBuilder.java:412 < DataManager.java:329 < DefaultDataHandler.java:27 < ...)
 How i can fix it?

**Comment by vitalidze** [comment]
This sounds like an issue #254 . Try the suggested solution from there https://github.com/vitalidze/traccar-web/issues/254#issuecomment-136685546

**Comment by ALAxHxC** [comment]
Reallyt thanks. it is works with https://github.com/vitalidze/traccar-web/issues/254#issuecomment-136685546
