### ISSUE TITLE
entry and exit of geofence

### ISSUE THREAD

**Issue by andyguz08** [vitalidze/traccar-web#368]
entry and exitof geofence

I'm taking the data generated traccar with the input and output geofencing, I have noticed that when you check in the box events in the database is not the same as shown on the map when loading the route having a difference of up to 2 minutes of delay in relation to the time I entered or left the geofence.

How you could do to make this information accurate.

**Comment by vitalidze** [comment]
The positions coming from your device are scanned every minute. Also there could be some time difference between your web browser, device and the server. It is also worth to run the 'Geo-fence enter/exit' and 'Events' reports for investigation.

**Comment by andyguz08** [comment]
devices send information to the server every 10 seconds, the server and PC devices have them at the same time (before variation in the time I had so set the time of the server, when the device and have it updated pc when windows), now when I generate the report in and out of geofencing (thanks for this update is helpful) is correctly mark the time.

**Comment by vitalidze** [comment]
I am a bit lost. Which time is inaccurate now? Can you give a concrete example?

**Comment by andyguz08** [comment]
these are the data that is in the database
31548   0   2015-11-27 13:03:03 GEO_FENCE_ENTER 84  32
31549   0   2015-11-27 13:03:03 GEO_FENCE_EXIT  84  32
31550   0   2015-11-27 13:03:03 GEO_FENCE_ENTER 84  32
31551   0   2015-11-27 13:03:03 GEO_FENCE_EXIT  84  32
31552   0   2015-11-27 13:04:04 GEO_FENCE_ENTER 84  33
31553   0   2015-11-27 13:05:04 GEO_FENCE_EXIT  84  33
31554   0   2015-11-27 13:07:05 GEO_FENCE_ENTER 84  34
31555   0   2015-11-27 13:07:05 GEO_FENCE_EXIT  84  34
31556   0   2015-11-27 13:08:05 GEO_FENCE_ENTER 84  35
31557   0   2015-11-27 13:08:05 GEO_FENCE_EXIT  84  35
31558   0   2015-11-27 13:10:05 GEO_FENCE_ENTER 84  36
31559   0   2015-11-27 13:10:05 GEO_FENCE_EXIT  84  36
31560   0   2015-11-27 13:11:05 GEO_FENCE_ENTER 84  37
31561   0   2015-11-27 13:11:05 GEO_FENCE_EXIT  84  37
31562   0   2015-11-27 13:12:06 GEO_FENCE_ENTER 84  38
31563   0   2015-11-27 13:13:06 GEO_FENCE_EXIT  84  38
31564   0   2015-11-27 13:13:06 GEO_FENCE_ENTER 84  39
31565   0   2015-11-27 13:13:06 GEO_FENCE_EXIT  84  39
31566   0   2015-11-27 13:13:06 GEO_FENCE_ENTER 84  41
31567   0   2015-11-27 13:13:06 GEO_FENCE_EXIT  84  41
31568   0   2015-11-27 13:14:06 GEO_FENCE_ENTER 84  40
31569   0   2015-11-27 13:14:06 GEO_FENCE_EXIT  84  40

and this is what generates me the input and output report. this is the right time for entering and leaving the geofence.
Entrada a geo-cerca Salida de geo-cerca     Duración   Nombre de geo-cerca 
2015-11-27 13:02:39 2015-11-27 13:02:51 12s Nueva geo-cerca
2015-11-27 13:02:54 2015-11-27 13:03:00 6s  Nueva geo-cerca
2015-11-27 13:03:48 2015-11-27 13:04:18 30s Nueva geo-cerca1
2015-11-27 13:05:30 2015-11-27 13:05:39 9s  Nueva geo-cerca2
2015-11-27 13:07:09 2015-11-27 13:07:18 9s  Nueva geo-cerca3
2015-11-27 13:08:51 2015-11-27 13:09:21 30s Nueva geo-cerca-sd
2015-11-27 13:10:03 2015-11-27 13:10:21 18s Nueva geo-cerca4
2015-11-27 13:11:39 2015-11-27 13:11:48 9s  Nueva geo-cerca5
2015-11-27 13:12:12 2015-11-27 13:12:21 9s  Nueva geo-cerca6

**Comment by vitalidze** [comment]
Time in `events` table is the time when the event was recorded. The `Geofence In/Out` report shows data based on the time in positions. I don't see any issue here.

**Comment by andyguz08** [comment]
geofence in the first database of events in input and the brand 13:03:03 13:02:39 report (this is the right time when I entered the geofence)

**Comment by vitalidze** [comment]
In notification it is possible to send the time of an event (13:03:03) and the time of position (13:02:39). There are two placeholders for these timestamps. By default it should show the time of position.

**Comment by andyguz08** [comment]
should mark the same hour in position and in event.
As I can do to make the event the same as that of the pocision, continuandno with testing and I have a difference between the event time and position of 00:01:20

**Comment by vitalidze** [comment]
I don't understand what's wrong with storing both event recording time and
reference to the position. I believe the more information you have about
event is the better.

суббота, 28 ноября 2015 г. пользователь andyguz08 написал:

> should mark the same hour in position and in event.
> As I can do to make the event the same as that of the pocision,
> continuandno with testing and I have a difference between the event time
> and position of 00:01:20
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/368#issuecomment-160222284
> .

## 

Kind regards, Vitaly Litvak

**Comment by andyguz08** [comment]
Record the time of entry into the geofence is very different to what has happened for example the car enters the geofence are 13:00:00 but in the event this as if I had happened to 13:01:20 in the best case there is a difference 30 seconds.

input events to the geofence have a variation from 1:20 in relation to the actual time they entered the geofence

**Comment by vitalidze** [comment]
Is the time in position correct? I don't plan to record the time from
position into event time.

суббота, 28 ноября 2015 г. пользователь andyguz08 написал:

> Record the time of entry into the geofence is very different to what has
> happened for example the car enters the geofence are 13:00:00 but in the
> event this as if I had happened to 13:01:20 in the best case there is a
> difference 30 seconds.
> 
> input events to the geofence have a variation from 1:20 in relation to the
> actual time they entered the geofence
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/368#issuecomment-160223472
> .

## 

Kind regards, Vitaly Litvak

**Comment by andyguz08** [comment]
which records the time the position is the correct event is varying, some pattern to adjust in both is the same time both the position in the event.
