### ISSUE TITLE
blank site after login

### ISSUE THREAD

**Issue by dschense** [vitalidze/traccar-web#371]
I was logged in to traccar, added some devices, logged out.
After wanted to login again I only get a blank white page after pushing the login button with Administrator account.

3 Other Accounts (no admin rights) can still login. 

anybody else with this problem ?

 ERROR: The serialization policy file was not found
 WARNING: Failed to get the SerializationPolicy

**Comment by vitalidze** [comment]
Try to clean up cookies/cache related to your server.

**Comment by dschense** [comment]
already did this. does not help

**Comment by vitalidze** [comment]
Then if there are no error messages in server log you should check web browser console for the errors.

**Comment by dschense** [comment]
The Mobile Version is running fine, but after switching to the Desktop version i get this Problem.

**Comment by dschense** [comment]
Launching a JVM...
INFO   | jvm 1    | 2015/11/29 21:52:13 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/11/29 21:52:13 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/11/29 21:52:13 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/11/29 21:52:13 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @865ms
INFO   | jvm 1    | 2015/11/29 21:52:14 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttem$
INFO   | jvm 1    | 2015/11/29 21:52:14 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.14.v20151106
INFO   | jvm 1    | 2015/11/29 21:52:14 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@67449181{/api,null,AVAILABLE}
INFO   | jvm 1    | 2015/11/29 21:52:18 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2015/11/29 21:52:22 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@6dc97b71{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-6030778110444239224.dir/$
INFO   | jvm 1    | 2015/11/29 21:52:22 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@3e329d62{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2015/11/29 21:52:22 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @9705ms
INFO   | jvm 1    | 2015/11/29 21:56:36 | Nov 29, 2015 9:56:35 PM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2015/11/29 21:56:36 | INFO: Login 'dschense'

**Comment by vitalidze** [comment]
I don't see any issue here. This is the `wrapper.log` file content. I meant the web browser console, the one which is in Chrome Developer Tools (if you are using google chrome).

**Comment by dschense** [comment]
get this Error in Chrome Console:

Uncaught java.lang.IllegalArgumentException: Enum constant undefined:

Af  @   traccar-0.js:3322
th  @   traccar-0.js:4862
pOd @   traccar-0.js:5373
Fod @   traccar-0.js:6114
E7c @   traccar-0.js:4891
l3c @   traccar-0.js:5975
g7c @   traccar-0.js:4335
j7c @   traccar-0.js:6166
pcb @   traccar-0.js:6158
Io  @   traccar-0.js:4443
Wo  @   traccar-0.js:6157
(anonymous function)    @   traccar-0.js:4139
Ee  @   traccar-0.js:2966
He  @   traccar-0.js:4017
(anonymous function)    @   traccar-0.js:5057

This Problem is only for one user. All other users can login without problem.
The biggest problem is, the User not working is the Admin user.

**Comment by vitalidze** [comment]
This is definitely a bug. However, it's hard to figure out where it is. Something is wrong either with you user profile or with some of your device. If possible please describe as detailed as possible what have you done with your database. Or if possible - send the SQL backup to me over email.

**Comment by dschense** [comment]
this is the big problem.. i was logged in to the webinterface and added some devices. i dont know what the Problem exactly is.

**Comment by vitalidze** [comment]
Then either send a database backup or paste here everything related with user your user, which can contain enums:
- application_settings
- devices
- geofences
- notification_settings
- notification_templates
- pictures
- reports
- user_settings

**Comment by dschense** [comment]
can you tell me how to get the backup you need ?

sent you database.mv.db and database.trace.db to
vitavaque@gmail.com

blank site after login #371

**Comment by vitalidze** [comment]
I got it. The issue is in `user_settings` table. For some reason it has empty 'overlays' selection. I have already seen it but as in your case I don't know the correct way to reproduce it. To fix database in your case you will need to run the following query (using the [h2 shell tool](http://www.h2database.com/html/tutorial.html#shell_tool)):

``` sql
update user_settings set overlays='GEO_FENCES,VECTOR,MARKERS,SEAMARK' where id=1;
```

To do it you will need to:

1) Stop the traccar service because H2 database cannot be updated by multiple OS processes.

2) Download the h2 database library (which has both the driver and SQL shell): http://search.maven.org/remotecontent?filepath=com/h2database/h2/1.4.190/h2-1.4.190.jar

3) Run the h2 shell tool. I have put all three files (two for database data and the h2 jar into same folder), so the path will be relative to current folder:

```
 java -cp h2-1.4.190.jar org.h2.tools.Shell

Welcome to H2 Shell 1.4.190 (2015-10-11)
Exit with Ctrl+C
[Enter]   jdbc:h2:~/Documents/traccar-web/database
URL       jdbc:h2:./database
[Enter]   org.h2.Driver
Driver    
[Enter]   sa
User      
[Enter]   Hide
Password  
Password  
Connected
Commands are case insensitive; SQL statements end with ';'
help or ?      Display this help
list           Toggle result list / stack trace mode
maxwidth       Set maximum column width (default is 100)
autocommit     Enable or disable autocommit
history        Show the last 20 statements
quit or exit   Close the connection and exit
```

Just leave blank all values except the path to your database

4) Make sure you are on the correct database by listing current tables:

```
sql> show tables;
TABLE_NAME             | TABLE_SCHEMA
APPLICATION_SETTINGS   | PUBLIC
DEVICE                 | PUBLIC
DEVICES                | PUBLIC
DEVICES_GEOFENCES      | PUBLIC
DEVICE_ICONS           | PUBLIC
EVENTS                 | PUBLIC
GEOFENCES              | PUBLIC
MAINTENANCES           | PUBLIC
NOTIFICATION_SETTINGS  | PUBLIC
NOTIFICATION_TEMPLATES | PUBLIC
PICTURES               | PUBLIC
POSITION               | PUBLIC
POSITIONS              | PUBLIC
REPORTS                | PUBLIC
REPORTS_DEVICES        | PUBLIC
REPORTS_GEOFENCES      | PUBLIC
REPORTS_USERS          | PUBLIC
SENSORS                | PUBLIC
SERVER                 | PUBLIC
TRACCAR                | PUBLIC
UI_STATE               | PUBLIC
USERS                  | PUBLIC
USERS_DEVICES          | PUBLIC
USERS_GEOFENCES        | PUBLIC
USERS_NOTIFICATIONS    | PUBLIC
USER_DEVICE            | PUBLIC
USER_SETTINGS          | PUBLIC
user                   | PUBLIC
(28 rows, 56 ms)
```

5) Run the needed query and exit from shell

```
sql> update user_settings set overlays='GEO_FENCES,VECTOR,MARKERS,SEAMARK' where id=1;
(Update count: 1, 6 ms)
sql> exit
Connection closed
```

6) Start traccar service

Hope this helps.

In future releases I will handle the empty values in that column, so no overlays are selected. If you will be able to reproduce it again please tell me the steps you have done.

I highly not recommend to use H2 database for production system. Switch to MySQL instead.

**Comment by dschense** [comment]
Nice man! after doing this everything is working great!
THX for your fast help! maybe i can reproduce the Bug and give you a hint for this Problem.

**Comment by vitalidze** [comment]
Closed due to inactivity.

**Comment by babos** [comment]
After compiling traccar -master and run I open in browser "localhost:8082" then the page is blank with a this visible label => ../traccar-web/web 
Can you help me ?
Thank

Osx and Window Too. The same result

Silvio

**Comment by vitalidze** [comment]
@babos first of all, please don't resurrect old closed threads. Create new one if necessary.

Regarding your issue you need to look into web browser console for error messages. Also if you compiled `master` branch then you should have original UI without any modifications. All changes are on `dev` branch.
