### ISSUE TITLE
Groups for devices

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#377]
Hi,

I've just built Traccar with the Groups feature but I believe that something is not quite right.

The Device has now a group_id meaning that universally (for all users sharing that device) it is assigned to the same group. But the Group might not exist/be shared to that another user (table groups_users).

The group_id property should be an attribute of the pair User/Device meaning that, for a particular user, the device X belongs to the group 1 and for another user, it belongs to the group 2.

Best regards,
António

**Comment by vitalidze** [comment]
I thought about it but I cannot imagine the use case you are talking about. Adding another level of relationship between user and group and device will definitely make things more complicated. 

I believe that if a user have access to the device, then he will have access to the group. The access to groups is managed in a different way that it is done for devices. Actually similar to the way it is working for geo-fences: users on a lower level of hierarchy have access to groups created by users in higher-level hierarchy.

**Comment by vitalidze** [comment]
In current way devices categorisation is done by some user with appropriate privileges. Then everyone users it. If each user will define a group on his own then at some point there will be a question on how to copy such settings between user accounts.

Everybody is welcome to show an example of how groups per user setting may be used in a better way than a group definition for each device.

**Comment by antoniopaisfernandes** [comment]
Ok.

But then

```
I believe that if a user have access to the device, then he will have access to the group.
```

should be enforced adding the necessary relationship in groups_users.

Best regards,
António

**Comment by vitalidze** [comment]
For now user will still see a group even if he don't have direct access to it. But he won't be able to neither change group nor assign another group to the device. Moreover, by default in most cases user will have access to the group created by the user from the upper-level (i.e. administrator or manager).

**Comment by antoniopaisfernandes** [comment]
Ok then.
