### ISSUE TITLE
[Help wanted] Multiple notifications after update to 0.10.0

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#378]
Hi!
After updating to 0.10.0 I received hundreds of email (notifications) for different events for all my devices. It seems to send me notifications from the last week.

Has anyone else experienced something similar?

Thank you!

**Comment by gsiotas** [comment]
And as the emails keep coming, I can notice that the majority of them is about start/stop events.

**Comment by vitalidze** [comment]
This means that all these notifications weren't send for some reason. Probably the notification sending process was not working after some error. Then when it's up again you get all "not sent" notifications.

**Comment by gsiotas** [comment]
It is strange as I was receiving notifications before updating. After updating I received 99% of the messages for stop/start events and I was curious if that is connected with the work you have done with these events.

**Comment by vitalidze** [comment]
Probably you haven't received them because there was no message template defined. In 0.10.0 I have added default message template for such events and probably you got them all at once.

**Comment by gsiotas** [comment]
OK thank you for the clarification!
