### ISSUE TITLE
[Bug] Notifications not working if more than 1 admin

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#379]
When there are more than one admin the second, third etc. admin don't get email notification, but only the first one.

**Comment by gsiotas** [comment]
After more tests, I can confirm that this is not the case anymore. Something should have been glitched.
--__--

**Comment by vitalidze** [comment]
The only thing I can imagine in your case that some of your administrators had invalid notification settings (i.e. smtp server config). Then when notification was sent to some non-administrator user, system got the settings from that administrator and it didn't work. For now during notification settings lookup system takes settings first from some manager in hierarchy, then if none found then settings from some administrator are taken (the order is undetermined for now). The last option is kind of fallback.

**Comment by gsiotas** [comment]
OK thank you for the feedback, if it happens again I'll report it.
