### ISSUE TITLE
Send command

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#380]
Good afternoon.
When selecting the vehicle the button to send this command inaccessible transparete even logged in as admin.

**Comment by gpproton** [comment]
I am also experiencing this issue even after following the installation instructions on updating the configuration
![command_greyed](https://cloud.githubusercontent.com/assets/11395006/11540754/dff6d11c-992e-11e5-9653-0725850a9d8d.PNG)
 file

**Comment by studmuffinjj** [comment]
Same problem by me as well. My devices are using the gps103 protocol.

**Comment by khfrabbi** [comment]
I am also getting same issue with Meitrack T1 device
I have tried with fresh installation of traccar 3.2

**Comment by vitalidze** [comment]
This is a bug. Something has changed in the backend API and it returns different code than I expected. It will be fixed in next version.

**Comment by marivan4** [comment]
vitalidze bom dia apos  a troca do beckend  ja esta funionando os comandos ?

**Comment by vitalidze** [comment]
@marivan4 read my previous comment https://github.com/vitalidze/traccar-web/issues/380#issuecomment-162206897

**Comment by marivan4** [comment]
ok para eu poder fazer essa modificaçao eu preciso fazer com netbeasn ? ou tem outro modo de fazer

**Comment by vitalidze** [comment]
There are official instructions to build the project: http://traccar.litvak.su/building.html You will need JDK (Java Development Kit) at least of v.7 installed.

**Comment by marivan4** [comment]
ok muito obrigado por enquanto

**Comment by vitalidze** [comment]
I have just released the new version. But looks like I am missing something about authentication. The button will be available, but it will not be possible to send command because authentication is not working for the API. I will investigate it and will try to put it in a next version.

**Comment by marivan4** [comment]
ok

**Comment by autotrafego** [comment]
Parabens pelo projeto , excelente , 
Ancioso para a correcao do buf de bloqueio do motor

**Comment by khfrabbi** [comment]
Waiting for new release.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/12/23/Bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
