### ISSUE TITLE
[Feature request] Trip report adjustment (Into trip and parked)

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#381]
Hi guys
The current trip report on traccar can not be easily understood, it think it should broken into two Trip report and parked report. The current trip reporting style is totally different from all my other platform.
see examples below.
![trip_report](https://cloud.githubusercontent.com/assets/11395006/11541547/183f5086-9933-11e5-9915-56a60d2d28d5.PNG)
![trip_report2](https://cloud.githubusercontent.com/assets/11395006/11541596/51ca5f94-9933-11e5-8a3b-f63604db46f2.PNG)
![trip_report3](https://cloud.githubusercontent.com/assets/11395006/11541661/aa01a866-9933-11e5-89e4-d211ff0a0e07.PNG)

**Comment by vitalidze** [comment]
I guess you are talking about "Drives and stops" report. I don't understand the clause that it is different from other platforms. Why should it be same? Then, what is hard to understand there? It shows you all vehicle's drives and stops in chronological way. I think it's a clean and easy report and I don't have any intent to change it or split it up into two reports. The only improvement I thought about it to add there a possibility to include map with each trip.
