### ISSUE TITLE
Feature for Groups

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#382]
A nice feature would add the ability to hide devices of certain groups (Groups devices visibility):
![image](https://cloud.githubusercontent.com/assets/6171197/11566641/34809676-99db-11e5-9f41-c01392567302.png)

Do you believe it is worth developing (I could try it) & merging?

Best regards,
António

**Comment by antoniopaisfernandes** [comment]
Being clearer, the idea is to have a mapVisibility boolean in the group (defaulting to true). If one set up the group to be mapVisibility = false, the devices would not be 'printed' on the map.
The screenshot would show only the 'red' vans :)

**Comment by vitalidze** [comment]
This should be implemented as a part of #118/#205/#333. I thought about adding a special column with check boxes to the devices list at the left, which will be called 'Visibility' (an eye icon at the grid header). Marking device as invisible should hide it from map. All invisible devices must be tied to the user account (maybe saved in UI settings), so when user logs back in he won't see previously hidden devices.

Then there should be some controls which will allow to change the visibility of a batch of devices (like for the devices from group, offline/offline devices, idle devices). That selection should be also saved in the user profile, so when the status of some device changes it will be hidden automatically.

I don't have the full picture on how it should be implemented, but I believe this is the only solid way to handle all cases at once.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html) and [article](http://traccar.litvak.su/features/visibility.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
