### ISSUE TITLE
[Help needed] Distance / distance filter

### ISSUE THREAD

**Issue by nelim** [vitalidze/traccar-web#383]
Hi, I have following problem and dont know is it server or device related.
I'm stopping the car at the morning(10:00 o`clock), everything is OK
But after work on 18:00+ after car and gps are started, tracker send one position with old coordinates and old date, before it gets GPS signal/lock and start with new positions.

I have filter.distance 30m in traccar.xml config and no matter that coordinates are the same (it must discard that position) it is in the database, also (maybe related) another strange thing that happens is - <distance> in other field got reset and start from zero, is this normal? 

Note that filter.distance is working when i drive and stop because i see "INFO: Position filtered from 1" in logs.

I'm not sure this is for here, but don't remember to have such problem with same device when using Anton's web interface, my json distance field was around 100km when i switched so it definitely didnt reset on every tracker start.

I also added new filter.duplicate option on config, which filter positions with same fixTime, i'm not sure that this works here? But sometimes device sends time 10 or more seconds ahead of last position time, with same gps coordinates so distance filter will be better.

```
mysql> select latitude,longitude,serverTime,time,other from positions where id = 1440;
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude         | longitude        | serverTime          | time                | other                                                                                                                                                        |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 42.1474616666667 | 24.7650883333333 | 2015-12-03 10:10:59 | 2015-12-03 10:10:57 | <info><status>00000000</status><charge>true</charge><ignition>false</ignition><odometer>0</odometer><distance>2833.55</distance><ip>212.5.158.25</ip></info> |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select latitude,longitude,serverTime,time,other from positions where id = 1441;
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude         | longitude        | serverTime          | time                | other                                                                                                                                                  |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 42.1474616666667 | 24.7650883333333 | 2015-12-03 18:17:23 | 2015-12-03 10:10:57 | <info><status>00000000</status><charge>true</charge><ignition>false</ignition><odometer>0</odometer><distance>0</distance><ip>212.5.158.22</ip></info> |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by vitalidze** [comment]
I have just checked the code of backend and it has nothing to do with this web UI. The backend manages these filters on it's own, both `filter.duplicate` and `filter.distance`. The distance filter in particular calculates the distance on the fly by the lon/lat. Thus, I think it's better to ask such questions here: https://github.com/tananaev/traccar/issues

**Comment by nelim** [comment]
Thanks Vitaly,
I just wasn't sure where to ask it :)
