### ISSUE TITLE
API Update devices

### ISSUE THREAD

**Issue by hungryjunk** [vitalidze/traccar-web#386]
Hi, I have a small question, I'm bussy with the rest-api and I wonder how I can edit devices with the api.

I'm using PHP Curl to do this, for adding new devices I use this piece of code:

$name = $_POST['name'];
    $ui = $_POST['ui'];

```
$add = curl_init();
curl_setopt($add, CURLOPT_URL, "111.222.333.444/traccar/rest/addDevice");
curl_setopt($add, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($add, CURLOPT_HEADER, 0);
curl_setopt($add, CURLOPT_POST, 1);
curl_setopt($add, CURLOPT_POSTFIELDS, "[{\"uniqueId\":\"".$ui."\",\"name\":\"".$name."\",\"maintenances\":[],\"sensors\":[]}]");
curl_setopt($add, CURLOPT_COOKIE, $cookie);
curl_exec($add);
curl_close($add);
```

**Comment by vitalidze** [comment]
You should be able to do it in a similar way, just use the `updateDevice` method instead, i.e. change the url to `111.222.333.444/traccar/rest/updateDevice`. You may want to load the device profile before editing with `getDevices` method, then update necessary fields and send it back to the service to the `updateDevice` method.

**Comment by hungryjunk** [comment]
getDevices gives me an array with all the devices, I managed to pull only the things I need, but it doesn't work if I do it like this

$editD = curl_init();
    curl_setopt($editD, CURLOPT_URL, "111.222.333.444/traccar/rest/updateDevice");
    curl_setopt($editD, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($editD, CURLOPT_HEADER, 0);
    curl_setopt($editD, CURLOPT_POST, 1);
    curl_setopt($editD, CURLOPT_POSTFIELDS, "[{\"uniqueId\":\"".$uiEdit."\",\"name\":\"".$nameEdit."\"}]");
    curl_setopt($editD, CURLOPT_COOKIE, $cookie);
    $editDev = curl_exec($editD);
    curl_close($editD);

I also tried it by putting the ID inside, didn't work either.

**Comment by vitalidze** [comment]
If you don't put everything, then it will just remove, clear missing fields. If you don't expect it then you need to put the full model. You can easily find the necessary device from the result of `getDevices` method. 

Then the following fields must be always present and filled in:
- id
- uniqueId
- name

**Comment by hungryjunk** [comment]
Had to throw maintenaces + sensors in the code to. Thanks for the quick answers!
