### ISSUE TITLE
Black map  [Close]

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#390]
Hello,

I just made the update  Dec2nd, and follow the  installation.html for  traccar.xml (for 3.2)

When I zoom on the map I get many mosaic sentences as
"Sorry, unable to display pictures for this area"  !!!

I change from openstreet to google map  it's the same map black screen

hum, after reboot the computer, it works fine.....

**Comment by vitalidze** [comment]
This sounds like something was wrong with your internet connection. You should check web browser console for error messages when you have issues with loading of map tiles.
