### ISSUE TITLE
[Question] What is considered a stop event?

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#392]
Hi! I want to ask what triggers a stop event? Beside the obvious no movement for X sec/minutes, does speed or direction play a part? Also can we change this options.

My problem is because sometimes devices give fault directions (a slight movement) and I receive a start/stop notification from traccar.

Thanks!

**Comment by vitalidze** [comment]
For now it is only detected by speed. If device has speed below specified threshold for the specified number of seconds it is considered stopped. Once speed becomes greater than the threshold device is considered as moving and appropriate event is recorded.

In future it is planned to improve this detection and add the following options:
- detect by distance between positions (i.e. when distance is less than specified value for the specified number of seconds, then device is considered stopped)
- detect by value of some sensor. It will be possible to define some sensor as 'ignition' and then based on it's value the stop/moving events will be produced

**Comment by gsiotas** [comment]
Thanks for the response, I think that this option
- detect by distance between positions (i.e. when distance is less than specified value for the specified number of seconds, then device is considered stopped

is crucial and should be included in next version. Anyway thanks again for your answer.
