### ISSUE TITLE
[Bug] Fuso horário relatórios

### ISSUE THREAD

**Issue by rafaelolivei** [vitalidze/traccar-web#393]
Ao gerar o relatório de (Entrada/Saida da Cerca Virtual) verifiquei que na geração de relatório, o fuso horário informado na pesquisa é diferente do que aparece no relatório. Acredito que seja um problema.
Na configuração das preferências do usuário está sendo utilizado o fuso horário (GMT-3:00) America/Sao_Paulo (BRT) o relatório teoricamente deveria seguir o fuso.

**Comment by vitalidze** [comment]
First of all, please write questions/issues in english, you can use google translate for the translations. I will not answer questions/issues written in different languages anymore. Also I understand russian, but english is preferred.

I confirm, this is a bug. Will be fixed in next version.

**Comment by rafaelolivei** [comment]
Vitaly okay, sorry for the inconvenience . In my next participation
will use English as their orientation.

Thanks,

2015-12-10 3:15 GMT-02:00 Vitaly Litvak notifications@github.com:

> First of all, please write questions/issues in english, you can use google
> translate for the translations. I will not answer questions/issues written
> in different languages anymore. Also I understand russian, but english is
> preferred.
> 
> I confirm, this is a bug. Will be fixed in next version.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/393#issuecomment-163489358
> .

## 

Rafael Oliveira
Analista de Sistemas
(27) 9 9981-4409

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
