### ISSUE TITLE
Not able to access rest api endpoints

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#394]
Hi,

I am trying to use rest api as described in this document 

https://www.traccar.org/traccar-api/

on this traccar-mod. But not seeing any response . Please can you help me out

**Comment by vitalidze** [comment]
If there are no endpoint then most probably you are using the 3.0 or 3.1 version of traccar backend.

Even if you will upgrade to 3.2 for proper work you will need to update all queries in the configuration files. I recommend to use RESTful API provided by the web UI mod: http://traccar.litvak.su/features/rest-api.html

**Comment by abhishekricky** [comment]
Hi,

I have updated all queries in configuration files . Plus I am also able to call the rest api only problem is 

I am not getting "JSESSIONID" in my header .

**Comment by vitalidze** [comment]
You must be missing something. Can you post your cURL requests/responses?

**Comment by abhishekricky** [comment]
Sorry I was trying to hit the url via postman (chrome app) . I see via Curl response is coming proper

Thanks for the help let me figure it out on my postman app
