### ISSUE TITLE
Geo fence

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#397]
Hello
I am facing problem in geo fence, I am logged in as manager and creating a geo fence for a particular device.
But I'm not sharing the geo fence with any User.
But the User device owner is viewing the geo fence created by min and the other already existing.

But someone with this problem?

**Comment by vitalidze** [comment]
If that manager is a manager for that user then this is a normal behaviour. Access to geo-fences is managed in a different way than it's done for devices. Read [this article](http://traccar.litvak.su/features/geofences.html) (**Sharing geo-fence** section) for more details.

**Comment by manishsaharan** [comment]
Hi,
I am developing an android app can you help me for add geofence using rest api how I send data to server for save circle or polygone geofence.
and how i get geofence points to draw on map in getgeofence api only id,name,color avaliable.
and for update profile for set first name and mobile number which api use and how to send data.
PLZ help.

**Comment by vitalidze** [comment]
@manishsaharan first of all, please don't ask questions related to the REST API in this thread. It is not related anyhow.

Regarding your question you should use `addGeoFence` method from the current API. However, for now it is not possible to define points (i.e. position) of geo-fence through the API. You will need to update the Geo-Fence entity by removing `@JsonIgnore` annotation from the `points` field. Then you will need to define set of points in a special format as a property of geo-fence entity to be saved.
