### ISSUE TITLE
API Calls to create, edit and delete devices/users

### ISSUE THREAD

**Issue by jsterkenburgh** [vitalidze/traccar-web#398]
Hi, 

I can not find any information regarding adding, editing or deleting users and devices.

Could you give me the parameters to post with the api call in order to perform the above named tasks or even provide me with the full API documentation?

Thanks in advance.

**Comment by vitalidze** [comment]
Here is the documentation: http://traccar.litvak.su/features/rest-api.html, which contains an example on how to add device. Here is some discussion from yesterday: #394

**Comment by jesse2612** [comment]
I have already succeeded in adding a device, but I can not find any information regarding editing or deleting users. I have also not succeeded in editing devices. Which parameters do I have to post with my API call?

**Comment by vitalidze** [comment]
As for updating devices please read discussion from here #386 

For editing users I don't have any example. But it should be similar to managing devices, the difference are the methods used (`addUser`, `updateUser`) and JSON. You need to read java code to find available fields here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/User.java

**Comment by jesse2612** [comment]
Vitali,

I have everything working so far, except for updating users. 

Could you give me a brief example how to update users with the API?

Thanks in advance.
