### ISSUE TITLE
Error Report Moving / Stopped and sending email

### ISSUE THREAD

**Issue by rafaelolivei** [vitalidze/traccar-web#399]
Hello!

I checked the report and also in sending email account linked to the stop and movement information is exchanged. Notice in the image attached believe can be another problem.

Regards
Rafael Oliveira
![relatorio_move_stop](https://cloud.githubusercontent.com/assets/8041024/11743454/b8ad2db0-9fee-11e5-920b-85bcf886327c.jpg)

**Comment by vitalidze** [comment]
Do you receive notifications for any other events except 'Stopped'?

**Comment by rafaelolivei** [comment]
When I enable the option ( moving) the system starts sending many emails stating that the car is moving , but the car is stopped.

The same is possible to observe in the report which points out that the car is moved for 9 hours about 1km , something impossible.

Now if we consider that it stood for nine hours , oh yes it would be true .

**Comment by vitalidze** [comment]
Those many emails most probably are from the recent events. If the notification is not sent then it will be sent when there is at least one recipient. You need to check the time in notification email.

As for the 9 hours of moving I guess you need to check your device settings for the minimal speed for idle detection. Probably your device reports some non-zero speed even when it is not moving. You need to compare this with the archive.

**Comment by rafaelolivei** [comment]
I will check, Thanks!

**Comment by vitalidze** [comment]
Any update on this issue?

**Comment by rafaelolivei** [comment]
I auditioned , I set my scanner to let me know if it gets stopped up three minutes and stopped. but still occurs divergent information in the report . I'm trying to capitar evidence to the problem.
