### ISSUE TITLE
Limiting access to some functions

### ISSUE THREAD

**Issue by novak82** [vitalidze/traccar-web#400]
Hi Vitaly,

It has been done great work in few last weeks !!!

If I may I would like to ask for new functionality - I would like to be able to hide button for importing gpx for all users. I do not want to someone try to fake their data through this mechanism. It is good for testing purposes but there is no need for it in real life.

All the best,
Novak

**Comment by vitalidze** [comment]
I don't quite understand the use case. Why can't you mark the users you want to restrict as 'read only'?

**Comment by novak82** [comment]
Even read only users have access to that button. And I wouldn't like to any user have ability to import data. 
Also I would like to be able to hide buttons/checkboxes for filtering and snapping to road from Archive and to hide button for sending commands (the devices that are in use doesn't support it). 

Thank you for considering the proposes,
Novak

**Comment by vitalidze** [comment]
I will try to hide the button from read-only users and when the 'disallow device management by users' is checked in a next version.

As for the other options to hide something, I don't plan it in nearest future.

**Comment by novak82** [comment]
Thanks !!!

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/12/23/Bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
