### ISSUE TITLE
Report's shortcut

### ISSUE THREAD

**Issue by MMartinezV** [vitalidze/traccar-web#402]
Hi,

Playing with the reports and thinking in how to enhance a little more the usability, I think that could be easier to get a quick report from the Archive toolbar.

Following with the issue https://github.com/vitalidze/traccar-web/issues/395. I think that once you have selected a device, period, from, to... you have almost everything to do a report. If you load this information when calling the "Reports Form" then you will just need to choose the type of report you want, write a name and click generate.

To give more sense to the relation between the fields in the "Archive toolbar" and the Reports, maybe placing a "QuickReport" button (or similar) in the bar will help.

Probably these little improvements makes things easier as more devices you have to manage with the UI.

I hope you'll like the idea,

Kind regards,

  Manuel Martínez

**Comment by vitalidze** [comment]
I like this suggestion. Probably will add it in some newer versions.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/21/Quick-reports,-device-context-menu.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by hardjumper** [comment]
I beleive this feature does not work as it is suposed to.the selected period for the quick report in the archive menu for a report  goes to a different  period rather than the one selected in the archive. Maybe I did not understand this feature.Can someone bouble check it ?

**Comment by vitalidze** [comment]
@hardjumper this sounds like a bug. I have tested it myself and looks like I am able to reproduce it only when "Custom" report period is selected. Please submit a separate issue to this issue tracker with screenshots of your archive toolbar and report opened from the archive "Reports" drop-down.
