### ISSUE TITLE
0.10.1 traccar-web-dev build failure

### ISSUE THREAD

**Issue by wizjer** [vitalidze/traccar-web#405]
I'm trying to compile traccar-web-dev 0.10.1. Compilation run on the same machine on which compilation the previous version. Prev wos ok. Now I get the error like in attachment.
[1.txt](https://github.com/vitalidze/traccar-web/files/60129/1.txt)

**Comment by vitalidze** [comment]
The GWT compiler ran out of memory. Try to update memory allocation in the following line:

``` xml
<extraJvmArgs>-Xmx1G -Xss1024k</extraJvmArgs>
```

Set it to 1500m for example:

``` xml
<extraJvmArgs>-Xmx1500M -Xss1024k</extraJvmArgs>
```

**Comment by wizjer** [comment]
Where I must do this? In witch file?

**Comment by wizjer** [comment]
pom.xml
Thanks

**Comment by antoniopaisfernandes** [comment]
I've removed locales I didn't need in order to reduce the memory usage, compilation time and war size.

**Comment by vitalidze** [comment]
I have spent whole yesterday to improve the compilation time and make it non-affected by the number of locales. It is almost finished and in next version it won't take so much time. Right now even on my macbook air the compilation with the current number of locales takes 4 (four) minutes. I think this is a great success.

**Comment by wizjer** [comment]
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:03:23.417s
[INFO] Finished at: Sat Dec 12 15:14:15 CET 2015
[INFO] Final Memory: 20M/192M
[INFO] ------------------------------------------------------------------------
Thanks.

**Comment by antoniopaisfernandes** [comment]
4 minutes!... from 1 hour... Super! :)

**Comment by gsiotas** [comment]
Yes I can confirm that this works. My compilation Total time: 6:40.179s
