### ISSUE TITLE
deleting Group Exception

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#406]
Hi
this exception raise when deleting a group that have a device a assigned to it .
it deletes group but did not refresh the devices in device view , it become empty and i have to log out and log in again to see devices .

<img width="908" alt="screen shot 2015-12-12 at 6 14 57 pm" src="https://cloud.githubusercontent.com/assets/12040752/11762971/a0cd364c-a109-11e5-80de-07dea222e711.png">

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/12/23/Bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.
