### ISSUE TITLE
api command

### ISSUE THREAD

**Issue by psyazax** [vitalidze/traccar-web#407]
Hello to all 

im using the last update but i can't send command "engine stop"

Request completed
Status: OK
Response
{"success":false,"error":"User not logged in - AccessControlException (BaseServlet:77 < CommandServlet:39 < *:18 < BaseServlet:53 < ...)"}

**Comment by psyazax** [comment]
okey i saw the another post that there is the problem with the authentication for the api.

**Comment by khfrabbi** [comment]
Please read discussion on

https://github.com/vitalidze/traccar-web/issues/380
