### ISSUE TITLE
How to update traccar/mod ?

### ISSUE THREAD

**Issue by nairazc621** [vitalidze/traccar-web#409]
Hi, how can i update my existing traccar-web/mod  without affecting my data/logs , devices etc. ?

thanks in advance

**Comment by vitalidze** [comment]
Just follow the installation instructions http://traccar.litvak.su/installation.html

**Comment by nairazc621** [comment]
is it going to erase my existing data? or not?

thanks

**Comment by vitalidze** [comment]
No, it should not erase. But I recommend to take a backup of your data before upgrading just in case.

**Comment by nairazc621** [comment]
thanks

**Comment by vitalidze** [comment]
Were you able to upgrade? If so then please close the issue.

**Comment by nairazc621** [comment]
not yet, but thanks :)
