### ISSUE TITLE
Getting Wierd error when I am deploying

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#410]
Hi,

I have followed all same instruction as it was in the link to build 

But getting error as javascript pop-up as below 

"GWT module 'traccar' may need to be (re)compiled"

**Comment by vitalidze** [comment]
How did you built it? From command line with maven?

**Comment by abhishekricky** [comment]
Yes I have built with command line mvnw package . 

Strangely when i compare with original files , just finds no difference in pom.xml and other files 

But I am able to run code from eclipse well

**Comment by vitalidze** [comment]
Something definitely went wrong during compilation. You need to check output log of maven for error messages.
