### ISSUE TITLE
address is empty

### ISSUE THREAD

**Issue by nairazc621** [vitalidze/traccar-web#411]
Hi , have any of you experience this kind of problem?
![traccar](https://cloud.githubusercontent.com/assets/13865157/11859850/12bf7a46-a4aa-11e5-9111-aca4911b9c74.jpg)

my logs in the previous months were fine until the month of  December came, and found out that the "address" inside the logs were empty. 
Other devices are the same too.

any help will be appreciated :)

**Comment by vitalidze** [comment]
Looks like reverse geocoding does not work for you. You need to check `tracker-server.log` file for error messages.

**Comment by nairazc621** [comment]
ok, i'll try to check it, 
btw
does updating helps?

thx

**Comment by vitalidze** [comment]
Updating of my web UI mod should not help for sure. But probably updating of the backend may help. Anyway, it's better to walk through logs to find the reason of your issue before making any further steps.

**Comment by nairazc621** [comment]
i found this error about the reverse geocoder starting in the month of december 

![traccarlog](https://cloud.githubusercontent.com/assets/13865157/11863703/12a32068-a4d1-11e5-8c51-941498b7c61a.jpg)

any help will be appreciated :) Thanks :)

**Comment by nairazc621** [comment]
![traccarlog2](https://cloud.githubusercontent.com/assets/13865157/11863732/59881b28-a4d1-11e5-9db2-c68c302d890a.jpg)

**Comment by vitalidze** [comment]
This means your backend application cannot connect to the reverse geocoding provider (google or nominatim). This sounds like a networking issue, or probably you are banned. You need to check this out. First you need to find out which reverse geocoding service you are using and then try to run some queries from the command line of your server (with `curl` for example).

**Comment by nairazc621** [comment]
Hi, can you tell me the ports that the traccar used? aside from the server port ?

**Comment by vitalidze** [comment]
For reverse geocoding it sends a request from the server to some third-party provider (like google or nominatim). Usually it works over HTTP (80) or HTTPS (443).

**Comment by nairazc621** [comment]
Hi vitalidze, what is the wrapper.log. for?

**Comment by nairazc621** [comment]
never mind, Thank you vitalidze for the help :)
issue has been resolved :)
it was a firewall issue within the network :) :+1:
