### ISSUE TITLE
when i compile with cmd it show error

### ISSUE THREAD

**Issue by kedarnathjimage** [vitalidze/traccar-web#413]
like Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.

i download source from https://github.com/vitalidze/traccar-web. i want to build the project in netbeans. tell me the procedure how to build the project and make a war file.

**Comment by vitalidze** [comment]
You need to follow these instructions to make a `.war` file: http://traccar.litvak.su/building.html

To investigate the error you need to walk through the maven output for error messages.
