### ISSUE TITLE
Command button

### ISSUE THREAD

**Issue by dsolissilva** [vitalidze/traccar-web#415]
Hi , I'm new at this and I have a big problem. when I press the button the command returns the following error:

Request completed
Status: OK
Response
{"success":false,"error":"User not logged in - AccessControlException (BaseServlet:77 < CommandServlet:39 < *:18 < BaseServlet:53 < ...)"}

I 'm using the protocol of a GPS103 and Teltonika fm1120

I hope excuse my English . Greetings from Chile.

**Comment by vitalidze** [comment]
This is a known issue. See #380 . Probably will be fixed in next release.
