### ISSUE TITLE
Save cloumn order in db

### ISSUE THREAD

**Issue by vzoltan** [vitalidze/traccar-web#42]
Save cloumn order in db
this way the user gets always the same saved experience in every browser after login.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/01/02/save-column-settings-in-database.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su)

**Comment by vzoltan** [comment]
Thanks ;)
Happy new year!

Az iPhone-omról küldve

2015. jan. 2. dátummal, 16:00 időpontban Vitaly Litvak <notifications@github.com> írta:
