### ISSUE TITLE
Some doubt about Traccar UI installation

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#421]
Good day,
I just reinstall Traccar 3.2 and Now I am readind that page
http://traccar.litvak.su/installation.html

Some line make me confused.
At the begining, you instruct how to modify the conf file by adding those line
<entry key='web.type'>old</entry>
<entry key='web.application'>/opt/traccar/traccar-web.war</entry>

Then you wrote to modify that line, but the table 'devises' does not exist
<entry key='database.selectDevicesAll'>
    SELECT \* FROM devices;
</entry>

here is the table I do have
device
position
server
traccar
user
user_device

Did I have something wrong?

**Comment by vitalidze** [comment]
You have tables structure from original version of traccar. All necessary tables are created/upgraded on service startup.

**Comment by pierrot10** [comment]
Dear Vitalidze,
Thank for your answer. Si waht should I do next?
Start the server to have the needed tables?
This will create 'users' and 'devises'? Then I will have 'user' and 'users', 'devise' and 'devises' tables etc?

Then I suppose, I should modify my conf file as you wrote?

<entry key='database.selectDevicesAll'>
    SELECT \* FROM devices;
</entry>

**Comment by vitalidze** [comment]
Yes. You must modify it in order to install the `traccar-web.war` correctly.
