### ISSUE TITLE
Search and real number plate displaying bug

### ISSUE THREAD

**Issue by ramlaxmanrimal** [vitalidze/traccar-web#422]
There is some error when searching the vehilce number plate. I search adding some letters, I can see the devices having the same name but when mouseover to that plate it is showing orinal detail not the exact one searching.
![image](https://cloud.githubusercontent.com/assets/15964695/11952259/f66b9cda-a8be-11e5-8f14-2b9c3291d86c.png)

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/12/23/Bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.

**Comment by abhishekricky** [comment]
possible to point out which files were edited to fix this becoz i can just fix them in my exisiting code

**Comment by vitalidze** [comment]
@abhishekricky you can observe this commit https://github.com/vitalidze/traccar-web/commit/05b636138b88337015eac14f515d1423510639dc
