### ISSUE TITLE
Tk103 sensors

### ISSUE THREAD

**Issue by ekofficiel** [vitalidze/traccar-web#425]
Hi vitalidze. I'm currently using the tk103 with a fuel sensor, and i'm using your traccar version as backend for my php website. but i don't know where i can find fuel sensor and other sensors data. Does traccar consider data from sensors?where can i find them on the database?

**Comment by vitalidze** [comment]
I think it should post data from sensors. Anyway, it's better to ask on the traccar backend's issue tracker: https://github.com/tananaev/traccar/issues

**Comment by ekofficiel** [comment]
Suppose it can get data from my tk103 sensors, in which table the data will be stored?

**Comment by vitalidze** [comment]
It will be stored in `positions` table in column named `other`.

**Comment by AdamNic** [comment]
If the WebUI doesn't show sensor information on the map (mouse hover over the device icon), send protocol123456 18 to the tracker to enable sending additional data over GPRS.
