### ISSUE TITLE
 Users with permissions read-only and manager, Error!!!

### ISSUE THREAD

**Issue by jonavargas** [vitalidze/traccar-web#427]
An administrator at the time of going to the settings tab , Users, and choose another user and this will mark the boxes and read-only user manager , both options at the same time, the user with that configuration when you log in you can see the settings tab but this will not make any changes dropping down , even in your personal data.

**Comment by vitalidze** [comment]
I think if this is a manager with 'read-only' access you should be able to see settings, but should not be able to make any changes. What's wrong with this approach?

**Comment by jonavargas** [comment]
I agree with you and I also believe that this view is the most optimal , but then I think the button or other settings tab this does not display anything good in a user with this particular setup , you attached a picture
![image](https://cloud.githubusercontent.com/assets/4804364/12014508/b1a0805a-acf3-11e5-9902-7b3b947ed150.png)

**Comment by vitalidze** [comment]
Why? Again, it displays all these settings in 'read-only' mode (you can view, but cannot change). Otherwise, I don't understand why you are setting up user as manager, just reset the 'manager' flag and let him be the ordinary 'read-only' user.

**Comment by jonavargas** [comment]
Reviewing this incredible web application , I realized that I was confused , I thought a manager could change non- personal account information ( expiration date and maximum number of devices ) and that if I allowed to modify those values ​​, that was my confusion , but I saw that despite that one change the value , this is not saved. Thank you for responding so quickly , and sorry for my bad English
