### ISSUE TITLE
Need help with rest api

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#428]
Hi,

I need to have rest api which creates and adds new Device or checks if information is already there , it updates with new one with device-indentifier as unique field

Then it should create a user for it with Read-only mode 

All this is in one web service url

**Comment by abhishekricky** [comment]
@vitalidze one thing how to test
rest api on my local when I launch project from Eclipse

**Comment by vitalidze** [comment]
Documentation on restful API is available here: http://traccar.litvak.su/features/rest-api.html It contains examples on managing devices. For users this should be similar, but with different API method names and data structures.

RESTful API will be available on the localhost when you run it on your local machine.

**Comment by abhishekricky** [comment]
Well onces I log in and fire this rest api from browser works 

https://d.traccar.litvak.su/traccar/rest/getLatestPositions
But now same I try to launch on local with url 

http://127.0.0.1:8888/traccar/rest/getLatestPositions doesnot work and even basic rest api like login

well if above local url correct ?

**Comment by vitalidze** [comment]
The url looks correct. What error message do you receive?

**Comment by abhishekricky** [comment]
Hey 

Sorry it was my mistake , its coming good now. 

Now just want to which all files would need to be updated. If i need to create a new rest api endpoint?

**Comment by vitalidze** [comment]
Current REST API exposes all `public` methods from [DataServiceImpl class](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/DataServiceImpl.java). I think the easiest way would be to add new method(s) in that class.
