### ISSUE TITLE
Pop-up (Vehicle information)

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#429]
I'm experiencing this problem, vehicle information displays only when it is approached on the map in larger distances is not displayed.
It has been tested with Chrome browser and Microsoft Edge, someone more with this supposed problem?

![img 1](https://cloud.githubusercontent.com/assets/9204676/12022230/059ccdae-ad75-11e5-8c57-b6cec59ca6fc.png)
![img 2](https://cloud.githubusercontent.com/assets/9204676/12022236/0de26730-ad75-11e5-8b0e-076942f4adff.png)

**Comment by gsiotas** [comment]
When you hover your mouse in the left panel (on the same device - Iveco) can you see the pop-up, or it depends on zoom level?

**Comment by MarceloMJM** [comment]
In the left pane is okay, just map the problem.

**Comment by gsiotas** [comment]
Can you try with mozilla firefox? In my computer it works both with firefox and chrome. Also maybe it has something to do with the icon? Can you also try with the default icons? Does it used to work in the past, and it suddenly stopped?

**Comment by MarceloMJM** [comment]
Always worked independently of the icon, and stopped a few hours ago.
I just try to mozila tabém not worked.

**Comment by MarceloMJM** [comment]
A detail only works on maximum zoom in normal google maps does not work in others.

**Comment by vitalidze** [comment]
I have tried right now and it works just fine for me. Probably something is wrong with your data. Do you see any error message in web browser console after trying to hover the vehicle icon?

**Comment by MarceloMJM** [comment]
Forgive me my lack of knowledge but would that be?
![erro](https://cloud.githubusercontent.com/assets/9204676/12025240/ae31ef58-ad93-11e5-9ebc-1c15bd7dd59c.png)

**Comment by MarceloMJM** [comment]
This chrome.
![chrome](https://cloud.githubusercontent.com/assets/9204676/12025481/8756707c-ad96-11e5-813e-38e21e0134ff.png)

**Comment by vitalidze** [comment]
Well, I don't see any critical error message on both screen shots. You can give me a test access to your server temporarily so I will take a look if possible.

**Comment by MarceloMJM** [comment]
access sent to your email, thank you for your support.

**Comment by vitalidze** [comment]
I figured out what was the reason. It was the 'Seamark' layer, which consumed mouse events. When the zoom is high enough the 'Seamark' layer was just hidden, so events passed through to the device marker. This will be fixed in next version. For now just disable the 'Seamark' layer in user's preferences.

**Comment by MarceloMJM** [comment]
Seamark actually turning off, everything works fine.
Thanks again for the support.
And a Happy New Year to all.

**Comment by crarchile** [comment]
Also works for me.. one thousand Thanks to both !

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
