### ISSUE TITLE
Redirect automatically to mobile version

### ISSUE THREAD

**Issue by Jeferex** [vitalidze/traccar-web#43]
When going to traccar web on a mobile web browser, traccar web should detect that the browser is mobile and redirect to mobile version automatically.

Maybe, this could be a setting and let the user choose if he wants to redirect automatically when using a mobile browser.

Also, mobile version should have a link to return to desktop version.

Thanks!

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/01/02/save-column-settings-in-database.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

Added 'Open Desktop Version' button to the mobile UI, which will add `?nomobileredirect=1` to the URL, which restrict auto-redirect.
