### ISSUE TITLE
Black screen after updated to lastest version

### ISSUE THREAD

**Issue by hanvienson** [vitalidze/traccar-web#430]
I have updated traccar-web to 23/12/2015 version and now when I login with mobile phone the screen is just black. Please help me to fix it. Thank you very much!
![image](https://cloud.githubusercontent.com/assets/16470002/12028247/d371ff4c-ae06-11e5-95e1-e3520bd0286e.png)

**Comment by vitalidze** [comment]
Have you cleaned up the cache? If so, then please look at browser console for error messages.

**Comment by hanvienson** [comment]
Please look at this error from my brower console: When I set Vietnamese for default language this error occur. Thank you!
![image](https://cloud.githubusercontent.com/assets/16470002/12045509/a8f07128-aed7-11e5-87f6-40f9bbf9ca40.png)

**Comment by hanvienson** [comment]
I think Vietnamese language is missing in mobile version.

**Comment by vitalidze** [comment]
Yeah. That's right, there is no vietnamese translation for the mobile version. This should be added. I will try to update transifex with mobile translations.

**Comment by hanvienson** [comment]
Thank you very much!

**Comment by vitalidze** [comment]
I have just added it: https://www.transifex.com/traccar-web-ui-mod/traccar-web/messages_mobilejson/ . Once it is translated I will include it into the next release.

**Comment by hanvienson** [comment]
Thank you Vitalidze!

**Comment by vitalidze** [comment]
I have just included it into codebase. Thank you for the translation.

**Comment by hanvienson** [comment]
You are welcome!

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Comment by hanvienson** [comment]
Thank you very much. Sorry for late reply!
