### ISSUE TITLE
JSON to XML after installing traccar-web

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#433]
Hi Vitaly,
Do you have any idea why the data in the field others are stored in xml after changing traccar.xml according to the instructions http://traccar.litvak.su/installation.html ? 
Within "original" traccar the other field is in JSON by default, but after installing traccar-web it is XML.
It happens with traccar 3.2 and, I think, with 3.1 - (I have no experience with 3.3).

**Comment by vitalidze** [comment]
I think this is because of this query:

``` xml
<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other);
</entry>
```

From my last investigation in `:other` parameter of query traccar backend ALWAYS stores XML. Try to change `:other` to `:attributes`:

``` xml
<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
</entry>
```

AFAIK in 3.0 and 3.1 `:other` stored either JSON or XML according to the configuration file settings. This was changed only since 3.2.

**Comment by mpele** [comment]
According to https://github.com/tananaev/traccar/issues/1627#issuecomment-167425988 it should be the same.
But it is not!!!
It looks that you are more familiar with traccar than Anton ;)

**Comment by crarchile** [comment]
Also worked for me. Thanks
