### ISSUE TITLE
Dont install Traccar Server in Window ?

### ISSUE THREAD

**Issue by ChiHungLam** [vitalidze/traccar-web#436]
Can you help me to add Traccar Server  into Traccar-Web (Server). After that I deploy it into TomCat Server to run.

Thanks,

**Comment by vitalidze** [comment]
You need to first install original traccar from https://www.traccar.org and then follow instructions http://traccar.litvak.su/installation.html to install this web UI mod. As for TomCat deployment you can do it as for any ordinary web application packaged in `.war` file. The only option that is required is the database datasource available at JNDI with `java:/DefaultDS` (see [persistence.xml](https://github.com/vitalidze/traccar-web/blob/dev/src/main/resources/META-INF/persistence.xml))

**Comment by ChiHungLam** [comment]
thanks you
