### ISSUE TITLE
Gxt Charts

### ISSUE THREAD

**Issue by wagnerdracha** [vitalidze/traccar-web#437]
Hi

Traccar work with GXT, ok? 

So, GXT support graph?

Thanks

**Comment by vitalidze** [comment]
Yes, this traccar web UI uses GXT and yes it supports charts. They are packaged as a separate maven artifact called `gxt-chart` (see http://search.maven.org/#search%7Cga%7C1%7Ccom.sencha.gxt), which is not included in the project at the moment. So if you need charts then include that dependency in the `pom.xml` and refresh project.

**Comment by wagnerdracha** [comment]
Hi

thanks!
