### ISSUE TITLE
STATUS and Address problem

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#439]
Hello, my traccar show me this error on tracker log. 
2015-12-31 01:44:25  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:256 < ConnectionManager:110 < ...)

and my devices don't show the address.

Traccar version: 3.3

Thanks

**Comment by ghost** [comment]
Hello,

For addresse  NOT  display....
same problem but  Traccar3.3

**Comment by gsiotas** [comment]
About the status problem after updating to traccar 3.3 I got the same error. After fiddling with the traccar.xml I think maybe the query in the updateDeviceStatus entry should change. I am talking about this one: 

> UPDATE devices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id;

For the meantime I have commented it, but I still get a relevant warning message in the log files:

> WARN: Query was empty - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:256 < ConnectionManager:110 < ...)

Edit: I am using traccer web 0.10.3

**Comment by vitalidze** [comment]
This query is not yet supported, i.e. there are no `status` and `lastUpdate` columns in the `devices` table yet. The warning can be safely ignored or you can remove/comment out the status update query if the warning bothers you.

**Comment by PascalVD** [comment]
i use the last Android client and last server version and i see no location of all my devices ... 
can you help to find the problem ?

**Comment by peptoni** [comment]
Do we have info about the 'status' column?  Could we just add the field to the table...?  It's annoying to have error messages in the log every couple of seconds.  It does not help to find other errors and clogs the server available space (I'm on a EC2 server, with limited disk space).

**Comment by vitalidze** [comment]
@peptoni you can either add column of following type:

``` xml
<column name="status" type="VARCHAR(128)" />
```

Or just comment out the `updateStatus` query in `traccar.xml`:

``` xml
    <!-- entry key='database.updateDeviceStatus'>
        UPDATE devices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id;
    </entry -->
```

In future I think it's worth to have such column in the web UI mod.

**Comment by peptoni** [comment]
Thank you.  I also had to add column "lastUpdate" as TIMESTAMP.  Now all errors have gone.

**Comment by peptoni** [comment]
Shit...  lastUpdate initializes as not null...  And I get this error:
WARN: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp - SQLException (... < QueryBuilder:346 < *:409 < DataManager:231 < *:118 < *:138 < BaseProtocolDecoder:47 < ...)

**Comment by peptoni** [comment]
Ok.  I solved doing this:
ALTER TABLE devices ADD lastUpdate DATETIME DEFAULT NULL;

Now it's working.

**Comment by peptoni** [comment]
So, the complete thing goes here:

msql -u USER -pPASSWORD
use TRACCAR;
ALTER TABLE devices ADD lastUpdate DATETIME DEFAULT NULL;
ALTER TABLE devices ADD status VARCHAR(128);
quit

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
