### ISSUE TITLE
Deploying on server and pointing to MySql

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#441]
Hi,

I followed your steps to deploy traccar mod , but I am confused where to change so that database is pointed to mysql

**Comment by abhishekricky** [comment]
I am seeing users table is created but is in-complete

**Comment by vitalidze** [comment]
Database connection is configured in backend's configuration file: https://www.traccar.org/mysql/

**Comment by abhishekricky** [comment]
I did same, but  I am seeing default username / password admin & admin is not working. when goto users table its not complete

**Comment by vitalidze** [comment]
Take a look at discussion in #424

**Comment by abhishekricky** [comment]
Thanks it solves it
