### ISSUE TITLE
mobile version Error

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#449]
hi all 

when trying to open traccar in mobile it gets a blank  black  page ,and this error in browser console : 

Uncaught TypeError: Cannot read property 'language' of undefined(anonymous function) @ VM105:7i.router.template7Render @ framework7.min.js:16i.router._load @ framework7.min.js:16(anonymous function) @ framework7.min.js:16i.router.preprocess @ framework7.min.js:16t @ framework7.min.js:16(anonymous function) @ framework7.min.js:16i.xhr.o.ajax.complete @ framework7.min.js:15r @ framework7.min.js:21g.onload @ framework7.min.js:21
util.js:30 SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

any idea ?

**Comment by vitalidze** [comment]
Which language you have set in your installation? If it is arabic or vietnamese then there are no translations of mobile UI at the moment. Vietnamese is already translated (will be included in next release), if you want you may provide arabic translation here: https://www.transifex.com/traccar-web-ui-mod/traccar-web/messages_mobilejson/

**Comment by xizoaziz** [comment]
i didn't chose any language . it is the login page it is not open  just plank black page .

it is opened some times and work fine and some times Error.

**Comment by vitalidze** [comment]
So you have 'english' in 'desktop' UI? This error means it could not load localization data. Are there any other error messages besides this?

**Comment by xizoaziz** [comment]
yes i have 'english' in desktop ,
no just this and a warning  : 
<img width="1274" alt="screen shot 2016-01-06 at 10 49 42 am" src="https://cloud.githubusercontent.com/assets/12040752/12137587/0ed0cb92-b463-11e5-9704-f7bd97dbe84d.png">

**Comment by vitalidze** [comment]
Try to set up language explicitly by providing URL parameter like `http://myserver:8082/m/?locale=en`.

**Comment by xizoaziz** [comment]
now  i got this 

<img width="1278" alt="screen shot 2016-01-06 at 11 19 36 am" src="https://cloud.githubusercontent.com/assets/12040752/12138110/46aa2028-b467-11e5-85f1-f760f5982aba.png">

<img width="826" alt="screen shot 2016-01-06 at 11 20 04 am" src="https://cloud.githubusercontent.com/assets/12040752/12138113/4ba87f98-b467-11e5-967d-e5a99175b758.png">

**Comment by vitalidze** [comment]
Something is wrong with you network connection with server. For some reason it cannot load the application settings. You need to check what's happening in 'Network' tab of the chrome developer tools.

**Comment by xizoaziz** [comment]
yes i think it may be network issue.
it is working now but why time for location got Na Na .

<img width="262" alt="screen shot 2016-01-06 at 12 07 32 pm" src="https://cloud.githubusercontent.com/assets/12040752/12138964/eaea847e-b46d-11e5-86a1-757a1386f26f.png">

**Comment by vitalidze** [comment]
Looks like it cannot load the time for the last position. You should investigate the response in networking tab in chrome dev tools.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
