### ISSUE TITLE
Issue with the latest release 

### ISSUE THREAD

**Issue by hardjumper** [vitalidze/traccar-web#452]
I am having an issue with the latest release when I try to use the visibility features like to unchek moving devices the interface will just hang and will never recover.Has anyone ran in to this issue?

**Comment by vitalidze** [comment]
It worked just fine for me when I was testing this feature. Are you able to reproduce it on the demo server?

**Comment by hardjumper** [comment]
No I am not able to reproduce the issue on the demo server.I do not know  the reason is it because I have to many devices.

**Comment by vitalidze** [comment]
This could be the reason. If possible, you can give me temporary access to your user account so I will take a look when I have time.

**Comment by hardjumper** [comment]
ok it works

**Comment by vitalidze** [comment]
Then send me credentials by email (find it in my github profile).

**Comment by crarchile** [comment]
Vitalidze, I want to thank you for all your great work with Traccar Web UI. I have a Traccar server v3.2 working perfectly with your Web UI. 

Today I had build your fork successfully.

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:48.595s
[INFO] Finished at: Thu Jan 07 14:33:12 CLT 2016
[INFO] Final Memory: 36M/88M
[INFO] ------------------------------------------------------------------------

Congratulations for your work !!!

**Comment by vitalidze** [comment]
@superservidor thank you. But please don't flood the threads. You could thank me by email ;)

**Comment by crarchile** [comment]
OK
