### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#454]
Hello,

inside
http://traccar.litvak.su/installation.html
Point 4.1   and  point 4.2
in the 4.2 there is no reference to   jetty-jndi-9.2.13.v20150730.jar
and to include it inside wrapper.conf

Does that mean, that for 3.2 of traccar there is no need of this lib ?
Or do I need to follow  4.1  AND  4.2  for traccar 3.2 ?

Thanks.

**Comment by vitalidze** [comment]
As said in instructions 4.1 is specific to traccar 3.1, which means you need to follow it only for that version. All other versions of traccar (2.x, 3.0, 3.2, 3.3) include that library by default.

Same goes for 4.2 You need to follow it only for 3.2 version of traccar.
