### ISSUE TITLE
Popup info does not appear when I hover a marker on the map...

### ISSUE THREAD

**Issue by crarchile** [vitalidze/traccar-web#457]
One of the traccar-web UI feature informed on your site is " replaced ‘current state’ panel with popups. They appear either when you hover a row in ‘devices’ table or when you hover a marker on map"...

Actually the info popup only appears when I hover a row in the "devices " column, but not when I hover the icon on the map

I am using traccar v3.2 with traccar-web ui last version...

Any idea to show popup at hover on both device name & map icon?

**Comment by MarceloMJM** [comment]
Please see it 
https://github.com/vitalidze/traccar-web/issues/429
Will be corrected in some version.

**Comment by crarchile** [comment]
Thank you Marcelo MJM... I will check #429 it to see what's happen.

**Comment by AkshaySRV** [comment]
how can i show my details of each points in the map by hovering.is there any other  way were i can show  the details?
