### ISSUE TITLE
New feature request: Seen by last time: days/hours ago (since date+time)

### ISSUE THREAD

**Issue by crarchile** [vitalidze/traccar-web#458]
Dear vitalidze,

Could you add some label before the field showed on the next image ?

https://app.box.com/s/vkpss0jd9jr3k0bzkyhv3u0b5pl8s56q

Regards.

**Comment by vitalidze** [comment]
I don't see any point in adding excessive labels. I believe this text is understandable without any label.

**Comment by crarchile** [comment]
ok, you are the Master !!!
