### ISSUE TITLE
No carga versión de escritorio en pc

### ISSUE THREAD

**Issue by andyguz08** [vitalidze/traccar-web#459]
tengo instalado traccar en un vps es la v2.12 y estuvo andando bien pero de un momento no me carga en la PC la versión de escritorio pero si puedo ingresar con la versión móvil desde el PC, ahora desde un S3 puedo entrar de la dos forma.

Saludos!!

**Comment by vitalidze** [comment]
Please write messages in english.

**Comment by crarchile** [comment]
Translation: I have Tracar v2.12 installed inside a VPS server, and It was running fine but now the web UI is not loading on desktop pc but it is loading OK when accesing it from my Samsung S3 cell phone. Both UI versions works OK from my phone (mobile and desktop)...

**Comment by vitalidze** [comment]
@andyguz08 this sounds like an issue with your desktop computer. You need to check web browser console in Developer Tools for error messages.
