### ISSUE TITLE
Can not loggin after installation

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#460]
Dear All,
I juts did a clean install of traccar 32.3.3
I also change the DB configuration to use MySQL instead of H2.
I log and change the admin password.

Then I installed traccar UI, but as there is no info regardi 32.3.3, I followed the 32.3.2 instruction
http://traccar.litvak.su/installation.html

I cleaned the cache and reboot the workstation.
Then I tried to login and I always get the error:

User name or password is invalid

I first use admin and admin and then admin with the new password.
I also find a post similar to my issue, and it propose to
# sudo chmod 777 database.mv.db

delete the users table and restart traccar. First I could not delete users table because of a foreign key and even if I chmod the above file, I still can not log into traccar.

Some had this issue?

Thank a lot

**Comment by pierrot10** [comment]
By the way, when I am trying to register a new user, it always say that username already exist while it's not the case...

**Comment by vitalidze** [comment]
Version 3.3 is not yet supported. Please use 3.2 for now.

**Comment by pierrot10** [comment]
Ok, thank, and when will it be supported? Do you have an estimation of time? Thank

**Comment by vitalidze** [comment]
There are no estimation time. Why do you want to use 3.3?

**Comment by pierrot10** [comment]
I uninstall 32.3.2 to have 32.3.3 for the CellID new feature. 32.3.3 give the Device connection status indication. But it mostely to try CellID

**Comment by vitalidze** [comment]
The connection status will not be supported until 3.4 because there is incompatibility in terms of authentication to the API. I got your point about CellID. Will post update here when I got some time to check the installation workflow over the 3.3 version.

**Comment by pierrot10** [comment]
So do you mean that traccar-web will not support direction until 3.4?

**Comment by vitalidze** [comment]
I mean device connection status, which right now is calculated on-the-fly based on the timeout settings. In original version it shows you whether device is connected right now or not. Direction is not related anyhow with the version of backend because it should be implemented in this version of web UI from scratch.

**Comment by pierrot10** [comment]
I am really stupid!!! I wrote devise connection, but I was thinking about devise direction status. In other word a pointer or an arrow which show the direction of the move. I am really sorry for the confusion.
I just reinstall 32.3.2 and traccar web. Should it be possible to adapt the traccar web to have the direction arrow? I other couple of question but I will open a new discussion to not have different subject in the same post

**Comment by vitalidze** [comment]
Showing device direction is in plans (you can find it in [roadmap](http://traccar.litvak.su/roadmap.html)). For now I event don't have a clear vision on how to implement it. There are several options.

**Comment by pierrot10** [comment]
Ok, great, thank for your work!!!!!!! I am impatient for the new feature.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
