### ISSUE TITLE
Running several Traccar installations

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#463]
Hi
How is the best way to run more than one installation of traccar? For example if a tailored interface is needed for a specific customer?

**Comment by vitalidze** [comment]
I think the best way will be to have a separate server or docker container for each installation. This will reduce the maintenance/support cost of each instance. You can set up a single virtual machine or docker container and then clone all your instances from it.

**Comment by zzyber** [comment]
Okay, I imagine that was the case. Maybe I will go with vmware or something to minimize cost. Superior support, thanks.
