### ISSUE TITLE
Unable login or register new account

### ISSUE THREAD

**Issue by 2safe** [vitalidze/traccar-web#464]
Hi Vitaly
I'm a newbie on this field, so my question may be silly, but I have not found any work decision on this issue.
Windows XP, Traccar 3.3 works fine.
After fork installation I can not register user or log in with existing Traccar user.
I get "name is already taken"  error
[wrapperlog.txt](https://github.com/vitalidze/traccar-web/files/85990/wrapperlog.txt)
Cleaning cash / trying another browsers / restart service  - same sh*t
What am I doing wrong ? Which direction to solve this problem ?
Thank you in advance
Alex

PS :3.3 issue ?

**Comment by vitalidze** [comment]
The 3.3 version is not yet supported. Please install it over 3.2

**Comment by 2safe** [comment]
Thank you
