### ISSUE TITLE
2 differents informations

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#466]
Hello...
2 pictures.... Mouse OVER the left colonn device's name shows that
![cayenne_1](https://cloud.githubusercontent.com/assets/15246747/12258781/46c468c2-b965-11e5-8669-56cf3e8739aa.png)
Seems to 'move' (105Km/h) and time since 01h19

The second picture, when mouse is over the Device inside the MAP. Time is wrong, and 0Km/h ??!!
![cayenne_2](https://cloud.githubusercontent.com/assets/15246747/12258803/7ebef134-b965-11e5-8429-e7052838a901.png)

Any idea ?

**Comment by vitalidze** [comment]
I think it shows the data from archive when you hover mouse over the map. Push the 'clear' button to remove archive data and try again.
