### ISSUE TITLE
./traccar.pid, already exists

### ISSUE THREAD

**Issue by wagnerdracha** [vitalidze/traccar-web#469]
Hi,

How to fix this?

ERROROR  | wrapper  | 2016/01/13 05:21:23 | 5958 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/01/13 05:21:23 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: Inappropriate ioctl for device

Thanks

**Comment by vitalidze** [comment]
Looks like you have stopped the service ungracefully. Just delete the file and try again. Also you may try running the `service traccar stop` or `service traccar restart` commands instead.

**Comment by wagnerdracha** [comment]
Thanks
