### ISSUE TITLE
Allow for multiple devices route print

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#47]
Today only one device route is printed.
It would be a nice feature to have multiple routes printed at the same time (in different colors).
For that, archive would have to be able to allow adding several devices.

Best regards,
Antonio

**Comment by vitalidze** [comment]
In theory to solve this issue I can merge this pull request https://github.com/tananaev/traccar-web/pull/262 if anyone is interested.

**Comment by antoniopaisfernandes** [comment]
That would be great.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/05/11/major-changes-to-archive.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
