### ISSUE TITLE
Online device while moving

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#470]
Hello,

If I check "moving"  but  UNcheck "Online" the icon's device disappear.
![moving](https://cloud.githubusercontent.com/assets/15246747/12294986/4aeb5aee-ba52-11e5-9532-743974bb54b9.png)
Is it possible to have a moving device OFFline ?
If not, perhaps if moving is ON, you can 'grey' the online switch !

**Comment by vitalidze** [comment]
Yes, it is possible to have 'Offline' device moving. It happens when your device lost connection when it was moving. I don't see any issue here.

**Comment by ghost** [comment]
OK, seems that "online" is upper prority on "moving"...
Because If I only check  moving , I don't see anything on the map (no icon's device), so I don't see the moving :(  ; so in this choice, I don't see any good thing with 'moving'... OR both of them must be check togother ?

Personaly, I think that "moving" MUST show the icon's device, perhaps having a 'new color icon' ?

Thanks..

**Comment by vitalidze** [comment]
It's not about priority. All statuses have same priority. Have you read the documentation http://traccar.litvak.su/features/visibility.html ? It clearly states:

> It is possible to check/uncheck multiple device states. Between such rules the ‘OR’ is applied. It means that if ‘offline’ and ‘idle’ is unchecked then if device is either idle OR offline it will be hidden.

I don't think that anything should be changed here. If you want to hide 'online' devices then system MUST hide them nevertheless device has another status, same goes for 'moving' or any other statuses. Why do you think something should be changed here?
