### ISSUE TITLE
User and group(s)

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#472]
I've a user with 2 groups (Aito and Ouare).

But, even if he can't do anything on others groups, is it possible that ONLY his groups are display on the menu ?
![aito](https://cloud.githubusercontent.com/assets/15246747/12295191/88e5da80-ba53-11e5-8b69-f32f009ba6ff.png)

he can see others groups that are NOT share with him.

**Comment by vitalidze** [comment]
This is a normal behaviour in current implementation. If user has access to the device with that group then he will see it in 'devices list' under that group. However, he won't be able neither to assign that group nor edit it.

**Comment by vitalidze** [comment]
Another case is that your user may have indirect access to the group, read more info about groups access here: http://traccar.litvak.su/features/groups.html
