### ISSUE TITLE
what is difference between server time and time

### ISSUE THREAD

**Issue by kedarnathjimage** [vitalidze/traccar-web#474]
i please see the following attachment. in this image server time and time is different. i have to do same time like UTC +5.30. then how to do it
![capture](https://cloud.githubusercontent.com/assets/16332684/12346358/b1584cec-bb79-11e5-8370-3e3f7e0f382f.PNG)

**Comment by vitalidze** [comment]
Time is stored in unified format, which is time zone independent. This difference means either your device sends data in wrong timezone or your server has incorrect date set.
