### ISSUE TITLE
Cannot login after upgrade traccar 3.3

### ISSUE THREAD

**Issue by Johntaa** [vitalidze/traccar-web#475]
using admin admin is not working any more, but  when I return to the original traccar.xml , it is working  . I tried to register other users but it respond with the user i already exist.
![img](https://cloud.githubusercontent.com/assets/3445006/12355623/eb3db750-bbae-11e5-833a-85c6a7e6afb8.jpg)

**Comment by vitalidze** [comment]
This is a known issue. This project does not support 3.3 yet, use 3.2 and lower versions instead.

P.S. have you tried searching over issues on this project before posting your own?

**Comment by Johntaa** [comment]
Nothing about this issue as of the last nigh.
P.S. if  I missed one , tell me

**Comment by vitalidze** [comment]
See #464 #443 #424  #460

**Comment by vitalidze** [comment]
This is the search query you may use https://github.com/vitalidze/traccar-web/search?q=3.3&type=Issues&utf8=%E2%9C%93

**Comment by Johntaa** [comment]
I see, Thank you
is there any soon plan to upgrade this project to 3.3

**Comment by vitalidze** [comment]
It is in plans for nearest future. I just haven't yet tried running it on 3.3

**Comment by Johntaa** [comment]
Thank you..
