### ISSUE TITLE
Info from reports

### ISSUE THREAD

**Issue by jcroman-itch** [vitalidze/traccar-web#476]
Hi Litvak

I need to add the information from "geo-fence in/out" to "drives and stop" report but i don't know where are these files.

I mean, I want to show both reports in the same file when you choose "drives and stop" type report and where you click on generate button.
I hope you can help me with this issue. 

Regards

**Comment by vitalidze** [comment]
Here are the source code files:
- Drives and Stops: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/reports/ReportDS.java
- Geo-Fences In/Out: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/reports/ReportGFIO.java

**Comment by jcroman-itch** [comment]
Thanks man

I have a last question.

I need to build all again or just modify these files?

**Comment by vitalidze** [comment]
You will need to build the `traccar-web.war` file by following these instructions: http://traccar.litvak.su/building.html

**Comment by jcroman-itch** [comment]
Thanks Litvak
I am sorry to ask you so many things but I am new in this of develop software.
I used git shell.exe and I followed your instructions but in the third step (Run build via maven wrapper), it displays an error. 

 'mvnw' it isn't  a cmdlet  command or  script or exe. 
In line 1 Carácter: 5
- mvnw <<<<  package
  - CategoryInfo          : ObjectNotFound: (mvnw:String) [],   command not found dException
  - FullyQualifiedErrorId : CommandNotFoundException

I think it could be a problem with the maven wrapper directory or something like that.

**Comment by vitalidze** [comment]
AFAIK there are issues with maven wrapper. Please install maven on your machine and use it for building.

**Comment by jcroman-itch** [comment]
Hi Litvak

I can't join both reports in a same file using netbeans, both reports use different syntax and I wonder if there are another simple way to join them.

It's possible modify ReportsModule.class to call ReportDS.class and ReportGFIO.class in a same file?

**Comment by vitalidze** [comment]
I don't think there is a simple way to join them on the upper level.
