### ISSUE TITLE
Mobile Geolocation

### ISSUE THREAD

**Issue by maxlife70** [vitalidze/traccar-web#477]
Hi Vitalidze,
i'm trying the new function of mobile version for geolocalize my mobile phone on the map but I don't see any point for my position. There is some configuration to do before activate?
Thanks
BR

Max

**Comment by vitalidze** [comment]
I think you should allow to access your geo-location somewhere in browser security settings. On my iPhone it asks this directly in web browser. Try running same function in your desktop chrome.

**Comment by maxlife70** [comment]
Resolved. My mistake.
Thanks
