### ISSUE TITLE
IDE project setup Intelli Jidea 15

### ISSUE THREAD

**Issue by warlockopy** [vitalidze/traccar-web#478]
Hello I am trying to mount the project on the new intellijidea version, and it really differs from the version showed on the website.
Can you try and add the steps on the web?
I am trying myself by now.
If I can make It I will provide screen shoots.

**Comment by vitalidze** [comment]
I would appreciate if you add screen shots yourself here. Is there much difference in a newer version?

**Comment by warlockopy** [comment]
OK I will do all over again.
for working properly we must make sure to have a standar jdk.
sudo apt-get install default-jdk.

i am skipping version control step GIT. that step is similar.
import
![traccar1](https://cloud.githubusercontent.com/assets/7785491/12420221/202d4a00-be9a-11e5-8410-8dd7ec5106e9.jpg)

I have choosed as maven
![traccar2](https://cloud.githubusercontent.com/assets/7785491/12420276/82e52d0c-be9a-11e5-8e55-8f356fc29bd1.jpg)

nothing changed here.
![traccar3](https://cloud.githubusercontent.com/assets/7785491/12420321/c37d614a-be9a-11e5-8951-8a66dcb5ac03.jpg)

here also untouched
![traccar4](https://cloud.githubusercontent.com/assets/7785491/12420357/ebbf5208-be9a-11e5-9a52-3be65e76e5cf.jpg)

JDK
![traccar5](https://cloud.githubusercontent.com/assets/7785491/12420398/1d8f6fca-be9b-11e5-9c00-6a2876635e75.jpg)

project name
![traccar6](https://cloud.githubusercontent.com/assets/7785491/12420443/5ea6c60c-be9b-11e5-9948-84c8be36cdd9.jpg)

Frameworks.
![traccar7](https://cloud.githubusercontent.com/assets/7785491/12420472/97606c32-be9b-11e5-88a2-d613d188f8bf.jpg)

Run configuration
![traccar8](https://cloud.githubusercontent.com/assets/7785491/12420506/dc523942-be9b-11e5-86b9-acf88e24b08e.jpg)

**Comment by vitalidze** [comment]
Thanks. Standard JDK installed is a must have for the previous version of instructions too. Means there is no change here. Actually you need standard JDK for any java project, so I haven't added this as a step. Probably I should, but I am hesitating.

**Comment by vitalidze** [comment]
I mean if you want to develop something for the project you need to learn java a bit. When you start learning java it is obvious that you will install JDK. I believe every java developer knows this.

**Comment by warlockopy** [comment]
I know java, You misunderstood, let me explain. another JDK was installed, not the standard, the auto installer from webup8team java. Now after installing standard works, but with problems in the debug.

**Comment by vitalidze** [comment]
I still don't understand. I think both JDK from oracle (webup8team?) and OpenJDK with version >=7 should work.

**Comment by warlockopy** [comment]
do not get confused there, the issue is that the other installer does not create all the config files for jdk, so the ide does not recognize the directory, but with the standard apt-get there is no problem.
Now is working, but firefox is not version compatible with the mint standard for the GWT plug in, I will try chrome and update.

**Comment by vitalidze** [comment]
Well, ok, there are lots of ways to install JDK. You can do it without anything like `webup8team` by just downloading from oracle's web site. Probably there is some issue with that unofficial JDK source, however it looks weird. Are you sure it does not work with any java project in Idea?

**Comment by warlockopy** [comment]
Yes, now is working, it was just a remark for some other people that might encounter same issue, developing in linux. I use mint.

**Comment by vitalidze** [comment]
So what's the difference with the IntelliJ Idea 15? I don't get it. That JDK issue is not related with Intellij Idea 15 anyhow.

**Comment by warlockopy** [comment]
1st just we have to make sure to use a official jdk, and 2nd some steps are not fully automated as is shown on the website. have to be done manually, using maven, as it does not recognize 1st as a itellijidea project

Problem with firefox for mint
Solution, run firefox24 (no need to remove newer version)
running several versions
download
https://ftp.mozilla.org/pub/firefox/releases/24.0esr/linux-x86_64/es-ES/
run configurations.
    firefox -P -no-remote

```
Now you can create a new Firefox profile (In my case Firefox24) and assing to the folder extracted from downloaded file.
```

create a profile and then run the other firefox (locate on folder)
./firefox -p *firefox24 -no-remote

here some reference.
https://support.mozilla.org/en-US/questions/974208

OK now everything is on place, but I do not know why plugin does not work on my firefox24

**Comment by warlockopy** [comment]
Now everything works fine!
