### ISSUE TITLE
No results on map

### ISSUE THREAD

**Issue by floor1** [vitalidze/traccar-web#479]
Hi,

First at want to thank you for this fantastic layout with all the things I was missing in the original traccar version :)

I got a problem,.. on my android phone I got the traccar client app installed and it worked in the past with the original traccar. Now after your web layout I cant see any results on the map. in the log file I still recive the HEX file the phone is sending. My traccar ver is 3.2 and follow instructions for changing to web UI.

Any idea ? could I have done something wrong.

Peter

**Comment by vitalidze** [comment]
Most probably you have set up configuration file incorrectly. Double check all entries.

**Comment by floor1** [comment]
Thanks,.. im going to check

**Comment by floor1** [comment]
hm, I think I found a mistake in your instrustions.

Old

<entry key='database.selectDevicesAll'>
    SELECT \* FROM device;
</entry>

New

<entry key='database.selectDevicesAll'>
    SELECT \* FROM devices;
</entry>

Can´t see the difference ?

**Comment by vitalidze** [comment]
You should change the name of table from `device` to `devices` (with 's' at the end). Where is the mistake?

**Comment by floor1** [comment]
oh sorry yes you are right. anyways I pasted the code into the file before testing so thats not the reason.

**Comment by floor1** [comment]
do you know how I can see which versions of traccar im running ? I installed in start dec so I think 3.2 but not 100% sure.

**Comment by vitalidze** [comment]
It prints version on the start in the `tracker-server.log` file.

**Comment by floor1** [comment]
Thanks

**Comment by floor1** [comment]
I guess thats the reason: 3.10.0-229.20.1.el7.x86_64 architecture: amd64

I downloaded it start dec which was suppose to be 3.2 I think.

**Comment by floor1** [comment]
Made a mistake. the ver was linux ver... the traccar is Version: 3.2-SNAPSHOT
