### ISSUE TITLE
WARNING: Failed to accept a connection (java.io.IOException: Too many open files)

### ISSUE THREAD

**Issue by rhani00** [vitalidze/traccar-web#482]
Hi
My traccar web server stopped to accept connections (80 port). 
You find below a part of "wrapper.log.20160121" file.
Any idea about this issue. It's a test server (only one integrated tracker) running on AWS palteform for 1 month ago. 
## Best regards

INFO   | jvm 1    | 2016/01/21 05:16:04 | Jan 21, 2016 5:16:04 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/21 05:16:04 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/21 05:16:04 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/21 05:16:04 |   at java.lang.Thread.run(Thread.java:745)

**Comment by vitalidze** [comment]
I haven't seen this issue before with traccar. Looks like you have reached operating system limit. Do you have any other application running on same virtual machine?

**Comment by rhani00** [comment]
Hi
No it's the only application running on my virtual machine.
Server answer again after restarting traccar service, but i want to
identify the source of this issue.
BR

**Comment by vitalidze** [comment]
You need to google about this problem `Too many open files`. As far as I remember there is a way to find out which application consumes open files.

**Comment by bhekimadide** [comment]
Can you tell us more about your server? configurations, maybe we can re-create the server? I have a few testing servers I can utilise

**Comment by vitalidze** [comment]
@bhekimadide who are you asking? My servers does not have any special configuration. One is on windows 7 x64, the real machine (i.e. non-virtual). Then there are couple of digital ocean instances with default ubuntu linux and lowest available memory 512MB and 1CPU (cheapest instance).

**Comment by bhekimadide** [comment]
Pardon me, I was asking @rhani00 about his server as it seems like a server issue as compare to traccar or traccar-web

**Comment by rhani00** [comment]
It's a Ubuntu 14.04 server instance 1GB RAM and 1 CPU (t2.micro AWS
instance)

2016-01-22 10:11 GMT+00:00 bhekimadide notifications@github.com:

> Pardon me, I was asking @rhani00 https://github.com/rhani00 about his
> server as it seems like a server issue as compare to traccar or traccar-web
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/482#issuecomment-173868534
> .

##

**Comment by rhani00** [comment]
Hi
I found the solution: https://github.com/tananaev/traccar/issues/553
BR
