### ISSUE TITLE
Plugin error when using GWT Development Mode with Chrome & Firefox

### ISSUE THREAD

**Issue by crarchile** [vitalidze/traccar-web#490]
Hi

When I try to follow your tutorial at: 

http://traccar.litvak.su/ide/netbeans.html

In the last part, Open Debug » Attach Debugger…

![image](https://cloud.githubusercontent.com/assets/11233964/12568216/f0360a36-c3a2-11e5-9551-8cd1424c4a82.png)

I follow the steps and a new window named ‘GWT Development Mode’ pop up. I Hit ‘Launch default browser’ button to open traccar web UI but Google Chrome shows a plugin  error.

Also inside NEtbeans 8.1 this error appears:

ene 25, 2016 8:20:40 PM java.util.prefs.WindowsPreferences <init>
## ADVERTENCIA: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

Hi, I am using Chrome v47.0.2526.111 m (64-bit) & Firefox 43 but I can't install the required plugin.

How can I solve it?

**Comment by vitalidze** [comment]
The GWT browser plugin used to run Development Mode is deprecated and not supported by modern browsers. You should use the SuperDevMode instead.

**Comment by crarchile** [comment]
Thanks @vitalidze
