### ISSUE TITLE
GUI MODS

### ISSUE THREAD

**Issue by warlockopy** [vitalidze/traccar-web#491]
Hello.
I have mounted the project on all available scenarios.
netbeans, eclipse, intellijidea.
I cannot figure out what tools or framework is used for the gui interface.

It looks like sencha, and also on the code is found many imports of it.
But after checking the code, it is not like a secha project or ext js project.

Can you point me in the right direction. I want to add some features to the GUI.

**Comment by vitalidze** [comment]
It uses Sencha GXT: https://www.sencha.com/products/gxt/

**Comment by warlockopy** [comment]
for the ui? do you hard code?
also wich version of GWT?

well I have found that someone has done what I need.

https://github.com/vitalidze/traccar-web/pull/468

In the mean time, how I can get some guide for more gui mods.
Basic guides for help.

**Comment by vitalidze** [comment]
Yes, GXT is used for the UI. Project is using latest public version of GWT at the moment 2.7.0. BTW you can find all libraries with their versions in maven project file: https://github.com/vitalidze/traccar-web/blob/dev/pom.xml

> do you hard code?

I don't understand this question.

> In the mean time, how I can get some guide for more gui mods.

The link I have send has guide on how to write code with GXT. For this project there is no guide, you must read the code to figure out how it is working.
