### ISSUE TITLE
GUI plans - Question

### ISSUE THREAD

**Issue by loshia74** [vitalidze/traccar-web#493]
Hi,
Do you have plans to reimplement web interface in js only + json replies like it is currently implemented in tanaev tracar github. 3.3 ?
Thanks

**Comment by gsiotas** [comment]
Nice request. :+1:  But I think it will be quite a challenge.

**Comment by loshia74** [comment]
Yeah it will be quite challenging for sure. However I am not in position to request anything I am just asking. This information is important for me. Tracar-web has a lot of great features which are mising in stock traccar. But if it is not following traccar 3.3 communicatin style it will be something like fork or to Put in another way to use latest web-hacks with latest stock traccar release will be very hard or even impossible in my personal oppinion

**Comment by vitalidze** [comment]
I don't have any plans to rewrite it with JS only. But I have plans to make it working with 3.3, which will happen for sure at some point of time.

**Comment by loshia74** [comment]
Super that sounds good
Thanks

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
