### ISSUE TITLE
Problems with negative temperatures

### ISSUE THREAD

**Issue by dsolissilva** [vitalidze/traccar-web#494]
sorry for my English. my problem is to compare two DS18B20 temperature. temperetara first Arduino and the other traccar website. In positive temperature shows a "16.37" Arduino and traccar web shows "166" if we translate it "16.6" not far from the Arduino.

however in negative temperatures show a different number.

What can be?
I am dealing with the protocol 5027 Teltonika

![_grados](https://cloud.githubusercontent.com/assets/16345932/12684764/7082a22c-c69f-11e5-8851-e6f7e4fcb475.jpg)
![grados](https://cloud.githubusercontent.com/assets/16345932/12684765/708734fe-c69f-11e5-8c9e-891a0abbf6d7.jpg)

**Comment by vitalidze** [comment]
This project has nothing to do with posting data from devices. It is the web UI project, used to display that data. It's better to ask here: https://github.com/tananaev/traccar/issues
