### ISSUE TITLE
Log file location

### ISSUE THREAD

**Issue by mtzro2003** [vitalidze/traccar-web#498]
Hello
I'm using latest traccar-web with traccar 3.2.
I want to ask: how to set the log file location?
In the interface, when I click Logs/Tracker server logs it opens a window with the following message:
"Log is not available. Looked at /root/logs/tracker-server.log, /logs/tracker-server.log, /root/tracker-server.log"
If I symlink traccar-server.log to /root/tracker-server.log it evidently works.
Also, where to find wrapper.log?
The message is: "Log is not available. Looked at /root/logs/wrapper.log.20160202, /logs/wrapper.log.20160202, /root/wrapper.log.20160202"

**Comment by vitalidze** [comment]
I guess you are running it from non-standard location. By default all logs on *nix systems are located under `/opt/traccar/logs` folder. System looks for the log files under the folder from `user.dir` property of java application, which must be the working folder of the application.

AFAIK there is no way to change the location without modifying source code. I think it's better to have it installed in `/opt` folder or create symlinks.

**Comment by mtzro2003** [comment]
Thanks for you answer, vitalidze.
You gave me a good tip: `user.dir`
Starting traccar with `java -Duser.dir=[PATH]` the path where it searches for the logs is OK.
What I think is not OK is that traccar-web expects the log file to be named `tracker-server.log`. I think it's better to read the conf file `traccar.xml`. 
But how do I enable `wrapper.log`?
I can't find it in `logs` directory...

**Comment by vitalidze** [comment]
> What I think is not OK is that traccar-web expects the log file to be named tracker-server.log. I think it's better to read the conf file traccar.xml. 

Then it will stick with the hard coded name `traccar.xml`. I don't see much difference.

Current configuration works for 99.999% cases. If you have non-standard installation, then you must do some additional steps to configure it properly.

> But how do I enable wrapper.log?

It appears only when you run traccar with the Java Service Wrapper (that's where the name comes from). If you don't run it this way, then you won't have it.

**Comment by mtzro2003** [comment]
Everything is clear now.
Thank you very much!
Keep up the good work!
