### ISSUE TITLE
How to sent sms with pushbullet

### ISSUE THREAD

**Issue by thogo1977** [vitalidze/traccar-web#503]
Hello,
how is it possible to send sms with pushbullet when a notification for enter geofences.
email is working fine.
Thanks for helping and have a nice day
Thomas

**Comment by vitalidze** [comment]
You should read about it on the pushbullet web site (or google for it). Right now the message is sent through the Pushbullet API, which then pushes notifications on your devices (through the application, browser extension, email). If there is a way to receive such notification by SMS then most probably it will work out of the box after proper configuration of your account.

**Comment by thogo1977** [comment]
hello vitalidze.
Thanks for your great work and sorry for my bad english.

I mean: With your gui it is possible when a device get maintenance (Edit Device/Maintenance) it will send an email to the registerd email in Account. To the same time it sends an email over the registered access token over pushbullets api. now i will send a sms directly with pushbullts api. But the api gets only the registered email adress to the pushbullet api. now my solution is that my email provider will send me the sms when it gets a email from traccar. ;-)) Good?

An other question. Where can i activate a filter for edit device/Maintenance? I have the problem that i get one time lat. 0.0 lon. 0.0 when i start  my car. so the maintenance will reach the limit and send that the device required mantenance. so i want to hide zero coordinates and hide invalid locations.

Thanks for helping.

Bye Thomas

**Comment by vitalidze** [comment]
> But the api gets only the registered email adress to the pushbullet api.

That's right. Actually email uniquely identifies your account on pushbullet so you get notification with the pushbullet application. I thought that probably it can send you notification over email as well if you set up your cell phone number in pushbullet profile.

> now my solution is that my email provider will send me the sms when it gets a email from traccar. ;-)) Good?

Well, if it works for you then it might be good. Another option may be to introduce another notification option - through the SMS sending provider like https://www.twilio.com/

> An other question. Where can i activate a filter for edit device/Maintenance? I have the problem that i get one time lat. 0.0 lon. 0.0 when i start my car. so the maintenance will reach the limit and send that the device required mantenance. so i want to hide zero coordinates and hide invalid locations.

You can set up positions filtering in traccar configuration file: https://www.traccar.org/configuration-file/ (look for options starting with `filter.`).

**Comment by thogo1977** [comment]
where i have to write filter.enable filter.zero filter.invalid in the traccar.xml? i can enable and disable this things in your web interface in the bottom line filter.... but this do not effect for the maintenace. Give a big big hint. ... Thanks Thomas

**Comment by vitalidze** [comment]
You should write it on the same level as other entries, something like:

``` xml
<!-- ... -->
<entry key='filter.enable'>true</entry>
<entry key='filter.zero'>true</entry>
<!-- ... -->
```

>  i can enable and disable this things in your web interface in the bottom line filter.... but this do not effect for the maintenace. 

This affects only loading data from archive. But what you need is to force backend part to not put such invalid positions to your database at all.

**Comment by thogo1977** [comment]
you are wonderfull. it seams to be work great. Thanks a lot. Thomas
