### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by wolfbgn** [vitalidze/traccar-web#504]
Sorry for stupid question but all my devices show **altitude** - 0m.
Is this normal or I am not doing something.

**Comment by vitalidze** [comment]
Most probably this means that either your device does not send altitude, or traccar cannot read that value.

**Comment by vitalidze** [comment]
It's better to ask here https://github.com/tananaev/traccar/issues with examples of HEX messages received from your device.

**Comment by wolfbgn** [comment]
Thank you
