### ISSUE TITLE
Migrate to Mysql keeping history

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#505]
Hi!

I finally got the Mysql config up and running as I hoped but I really would like to keep existing data from the H2 Database. What would be the easiest way to go?

**Comment by bhekimadide** [comment]
I used this tutorial http://stackoverflow.com/questions/11359813/how-to-convert-h2database-database-file-to-mysql-database-sql-file sometime ago to convert H2 to mysql for another opensource POS

**Comment by vitalidze** [comment]
This is not a trivial task. I confirm that solution suggested by @bhekimadide may work. But be prepared to start from scratch with your MySQL database.
