### ISSUE TITLE
traccar web.war issue

### ISSUE THREAD

**Issue by Nayan12** [vitalidze/traccar-web#506]
hi,
i need help!!!!
i am trying to run traccar-web UI on windows7, and i want to create traccar-web.war file throw "Package.bat" file but when i run it, it open and after 1sec closed :( which configuration is needed to run this file on my windows7 machine. 
please tell me step wise help me!!!!

**Comment by vitalidze** [comment]
If you want to install it then you can do it with the pre-built version by following instructions: http://traccar.litvak.su/installation.html

If you want to build it then you need to follow these instructions: http://traccar.litvak.su/building.html Most probably you will need JDK (7 or higher) and Apache Maven installed.

**Comment by Nayan12** [comment]
yes sir!!
my machine is fully configure.. but still package.bat is not running

**Comment by vitalidze** [comment]
I have no idea what is the 'package.bat'. As I said you need maven to build the `traccar-web.war`.

**Comment by Nayan12** [comment]
sir,
i downloaded apache-maven-3.3.9 and installed it C:\Program Files\Apache Software Foundation\apache-maven-3.3.9 and set path to the environment also..
and in cmd i put mvn -version then also 
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Nyan>mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: C:\Program Files\Apache Software Foundation\apache-maven-3.3.9
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

this output come....
but still no traccar-web.war file is not create? :-(

**Comment by vitalidze** [comment]
As I have said you need to follow these instructions: http://traccar.litvak.su/building.html

**Comment by Nayan12** [comment]
this result came..

C:\Users\Nyan>mvnw package;
'mvnw' is not recognized as an internal or external command,
operable program or batch file.

????

**Comment by vitalidze** [comment]
You need to run it from the folder where you have checked out project sources.

**Comment by Nayan12** [comment]
this error is coming..

C:\Users\Nyan\My Documents\NetBeansProjects\traccar-web>mvnw package;

ERROR: M2_HOME is set to an invalid directory.
M2_HOME = "C:\Program Files\Apache Software Foundation\apache-maven-3.3.9"
Please set the M2_HOME variable in your environment to match the
location of the Maven installation

'cmd' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Nyan\My Documents\NetBeansProjects\traccar-web>

????

**Comment by vitalidze** [comment]
Try to run `mvn package` instead of `mvnw package`. Also you don't need to add semicolon (`;`) at the end of command

**Comment by Nayan12** [comment]
i put as per you told.. but this error is comming...

C:\Users\Nyan\My Documents\NetBeansProjects\traccar-web>mvn package;
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Traccar Web UI 2.11-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.452 s
[INFO] Finished at: 2016-02-06T13:35:55+05:30
[INFO] Final Memory: 5M/56M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "package;". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-arti
fact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, c
ompile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prep
are-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site
, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

C:\Users\Nyan\My Documents\NetBeansProjects\traccar-web>

????

**Comment by Nayan12** [comment]
i am so sorry sir..
its my silly mistake.. i again put ; at the end.. 
but now i successfully run and create war file also..

**Comment by Nayan12** [comment]
now i want to put this file on traccar-server 3.2 and give the path of this war file into config file??
m i right sir? or any changes for desired output please tellme?

**Comment by Nayan12** [comment]
sir,
now i have  "traccar-web-2.11-SNAPSHOT.war" and i am put it on server and started server..
then http://localhost:8082 in browser.. output also shown
but now problem is it shows output like original traccar-master project. there is no modification shows in it???? please show me the correct way..

**Comment by vitalidze** [comment]
As I have already told you - all changes are on `dev` branch. You need to switch project to that branch and after that build the `traccar-web.war` file.

**Comment by Nayan12** [comment]
sir
please give me the link how to switch project in dev branch??
