### ISSUE TITLE
AddUser and password

### ISSUE THREAD

**Issue by franiis** [vitalidze/traccar-web#509]
Hi, 

I think that now it's impossible to create user with addUser API's Method. 
If you look into [DataServiceImpl code](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/DataServiceImpl.java#L220), there is if which requires login and password to create user (from User.java model).
But [User.java's password](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/User.java#L95) has JsonIgnore annotation.

So when I send request to AddUser with password, model doesn't use that field and throws exception on mentioned "if". It can be solved by deleting this annotation (methods works then), but IMO it's bad solution (unsafe).

Is there different method to use this method and I'm doing something incorrect?   

Greetings
Piotr - franiis

**Comment by vitalidze** [comment]
To add user you can call 'register' method. As for the solution for `addUser` method I believe the `@JsonIgnore@ annotation can be put on the`getPassword()`method only so the user entity won't be transferred with password. But then it will require to make some changes in`updateUser`method so it will ignore users with`null` passwords.

**Comment by franiis** [comment]
Thank you for answer.
I can do (more or less) the same thing with register (I don't know Traccar good enough to determine for example value managedBy_id column) and adding @JsonIgnore to getPassword (without further changes) doesn't solve it (I tried it). 
I just tried to report slightly broken API method :)

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/02/09/Minor-bugfix-release-and-support-of-traccar-v3.3.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
