### ISSUE TITLE
UpdateSettings and id

### ISSUE THREAD

**Issue by franiis** [vitalidze/traccar-web#511]
Hi,
I think that UpdateSettings has similar bug to #509 (I don't know java very well, but I guess similar solution would be enough).

API method updateUserSetting require [userSetting's id](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/DataServiceImpl.java#L326) (because it use [equals](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/UserSettings.java#L328) method which compares by mentioned id).

But [id has @JsonIgnore attribute](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/UserSettings.java#L32) - so it won't be loaded to API method, and will throw AccessDaniedException. 
As "id" of UserSetting is necessary to update UserSetting maybe just remove this attribute and allow API's users to obtain this ID.

Greetings
Piotr - franiis

PS. I deleted locally this attribute and it's working, but I think that it's worth reporting.

**Comment by vitalidze** [comment]
I think it should be safe to remove `@JsonIgnore` annotation from the `id` field. Previously there were no need to update it through the API.

Thanks for reporting.

P.S. you can submit a pull request with this change if it is possible.
