### ISSUE TITLE
Still ask to recompile, although it has been executed in the main application.

### ISSUE THREAD

**Issue by hijaumuda** [vitalidze/traccar-web#514]
I did a little modification to change the gif loader and remove loading text.
and successful run (gwt super mod dev) http://127.0.0.1:56448/traccar.html

after that I export the file traccar-web.war, new size 25,124kb (24,5mb), and I put it in the folder C:\Program Files\Traccar

and do stop & start traccar services.

the problem is:
after I run on a browser http://localhost:8082, there is a popup asking to recompile, but after the recompile, still does not display the login page.
popup msg: "GWT module 'traccar' may need to be (re)compiled"

I've also tried to do a fresh install traccar and put traccar-web.war, but still ask to recompile.

![recompile](https://cloud.githubusercontent.com/assets/8728222/12971413/7c702b94-d0cd-11e5-88dc-3c599bfd28c6.jpg)

**Comment by vitalidze** [comment]
Most probably you have built the `traccar-web.war` incorrectly. You should build it with maven.

**Comment by hijaumuda** [comment]
in Maven Build, What should I write in field GOALS.

**Comment by vitalidze** [comment]
You should do at least `package`, but I recommend to do `clean` too.

**Comment by hijaumuda** [comment]
ok i did build with maven, and popup to recompile is not shown anymore.

but now i got new popup msg:
"Couldn't load traccar from Super Dev Mode
server at http://127.0.0.1:58903.
Please make sure this server is ready.
Do you want to try again?".

![popupsuperdev](https://cloud.githubusercontent.com/assets/8728222/12973225/6af68a2e-d0dd-11e5-9063-98b327417f64.jpg)

**Comment by vitalidze** [comment]
Either you built it incorrectly or there is something cached on the browser side. Try to clean up cookies, restart browser or maybe even try another browser/machine.

**Comment by hijaumuda** [comment]
1.everything its ok, if i try fresh git clone https://github.com/vitalidze/traccar-web.git -> modification -> then build maven (without run gwt super dev mode).

2.but if i run gwt super dev mode first (just to see modification i made) -> then build maven, problem comes again.

it just me, or we can not build maven after run in gwt super dev mod?

i see different traccar.nocache.js structure code result between no.1 & 2.

**Comment by vitalidze** [comment]
I don't have such issues. Maybe you are not sopping the application running in SuperDevMode before running maven build.

**Comment by hijaumuda** [comment]
ok, thanks @vitalidze
