### ISSUE TITLE
Installation of Traccar web 3.3

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#522]
Hello

I am dorry for my stupid question but I am installing traccar and traccar web 3.3
http://traccar.litvak.su/installation.html
At the point 
4.2) Specific to v3.2 of traccar

Does it include 3.3 or there is no specific for 3,3?

**Comment by vitalidze** [comment]
For now there is no specific for 3.3. You should skip instructions for 3.2 and 3.1. However, probably you will need some manual steps from #509 #519 #520 #521

**Comment by thaihau** [comment]
Can this support traccar 3.3? I cant login once i follow the instruction from http://traccar.litvak.su/installation.html

Not sure i did the right step or not, 
1. change conf to use traccar-web.war
2. Change sql of database.insertPosition
3. Change sql of database.selectLatestPositions
4. Change sql of database.updateLatestPosition

Is my step above are correct? I just cant login using my existing user's credential.

**Comment by johansid** [comment]
Just follow the steps.
And drop all tables.
Start traccar.

It worked for me

-----Original Message-----

**Comment by thaihau** [comment]
Thanks. it work for me too after setup a new database.

**Comment by Mindreader12345** [comment]
Hi, can someone explain me step by step how I can change SQL of Database and drop tables ?

**Comment by vitalidze** [comment]
@Mindreader12345 It depends on the database engine you are using. Basically you need to run some application that will connect to your database server and allow you to run some queries.
