### ISSUE TITLE
Why 3.3 does not show the direction

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#523]
Hello
I just could install 3.3 and I am suprised that the direction are not showed.
Moever, I also thought be able to manage the valid field with a 1 (GPS fix) or a 0 (Tower location) and it does nto work ...
I would like to manage the icon for GPS and the same icon with a mark for GSM towel location

Cheers

**Comment by vitalidze** [comment]
> I just could install 3.3 and I am suprised that the direction are not showed.

This is because since version 3.x the web UI mod is not related with the original web UI anyhow. They are completely different projects. So if something is added in one of those project it is quite hard to include it in another one.

> Moever, I also thought be able to manage the valid field with a 1 (GPS fix) or a 0 (Tower location) and it does nto work ...
> I would like to manage the icon for GPS and the same icon with a mark for GSM towel location

I don't quite understand what it means. I think you need to update the web UI mod code if you want to achieve this.

**Comment by pierrot10** [comment]
Hello, may be I am confuse with traccar and traccar web ui,
The idea is to have an icon for the GSM tower location witht he filed 'valid' to 0
and te GPS location with filed 'valid' to 1.
I prepared the icon you can download her
https://www.dropbox.com/s/v33omx43c98drzd/traccar-image.zip?dl=0
I think it would be nice to distingish the GSM and GPS location with a small different icon.
How can I do with local traccar? It is easy to do? I do not know how to achieve it.
Thank for your support

**Comment by pierrot10** [comment]
https://www.dropbox.com/s/mfr68qght59grx5/traccar-icon.ai?dl=0

**Comment by pierrot10** [comment]
Sorry, I  issed something. Whe we have GPS position, it would be nice to have an additional arrow showing the direction. Or may be having an arrow on the blue path..... But the direction are important.
Thank for all and have a nice day
Cheers

**Comment by vitalidze** [comment]
> The idea is to have an icon for the GSM tower location witht he filed 'valid' to 0
> and te GPS location with filed 'valid' to 1.

This looks weird for me to show GSM or GPS icon based on `valid` field. Too specific to include into public release. At some point I plan to add possibility to define attributes based on status of device, this was planned on values from additional fields, but can be based on `valid` field as well.

> How can I do with local traccar? It is easy to do? I do not know how to achieve it.

You need to write some code to do it. Currently icon for latest position is defined [here](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/controller/MapController.java#L149)

> Sorry, I issed something. Whe we have GPS position, it would be nice to have an additional arrow showing the direction. Or may be having an arrow on the blue path..... But the direction are important.

This is planned for some future release.
