### ISSUE TITLE
Error after reciving tracker data in traccar.log

### ISSUE THREAD

**Issue by thogo1977** [vitalidze/traccar-web#527]
Hello,
after i maked a new install with drop database i get following warning. What does it means?

Thanks a lot

Thomas

2016-02-17 16:31:56  INFO: [XXXX] connected
2016-02-17 16:31:56 DEBUG: [XXXX: 55002 < IP-Adress] HEX: 
2016-02-17 16:31:56  WARN: Column "STATUS" not found; SQL statement:
UPDATE devices SET status = ?, lastUpdate = ? WHERE id = ?; [42122-190] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:254 < ConnectionManager:110 < ...)

**Comment by gsiotas** [comment]
Check: https://github.com/vitalidze/traccar-web/issues/524#issuecomment-184321908

**Comment by thogo1977** [comment]
hello.
thanks for fast answer.

First I stopt traccar 
sudo /opt/traccar/bin/traccar stop

in traccar.xml i comment out the changelog 



then i DROP TABLE positions; in my h2 database

then traccar start new. 

The table positions will rebulied fine but i get same error.

Have you some idears?

Thanks Thomas

**Comment by gsiotas** [comment]
The problem is with the 'devices' table. I suggest dropping all tables, before restarting traccar

**Comment by thogo1977** [comment]
sorry. i stop traccar thei droped the full database and restart it. but the same. Sorry. then i removed traccar complete restart my pi and installed it new. the same error. What is my mistake? Thanks Thomas

**Comment by gsiotas** [comment]
OK sorry I didn't get it at your first post, but this warning is know. You can find more info here: https://github.com/vitalidze/traccar-web/issues/439

You can comment it or leave it as it is. Traccar-web should work fine.

**Comment by thogo1977** [comment]
ok when you comment  out

UPDATE devices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id; it 

out you get this 

info: 2016-02-17 19:14:17  INFO: Query not provided: database.updateDeviceStatus

Is it right? I think traccar works fine.

Thanks for helping

Thomas

**Comment by gsiotas** [comment]
Yeap this is right for now.

**Comment by thogo1977** [comment]
many thanks and good night
