### ISSUE TITLE
"username is already taken" when trying to create new user

### ISSUE THREAD

**Issue by a4mkd9** [vitalidze/traccar-web#528]
Hello,

I have a new installation of traccar 3.3 on Debian Linux x64 with MySQL
After installing your web UI mod it's impossible to create a user. 

It even doesn't matter if you fill in all required fields - I've tried using only one single character as a username and left all other fields empty - just to check if error message will be different.

Every time it says: "Error: Username is already taken"
![image](https://cloud.githubusercontent.com/assets/17299937/13121861/18846198-d5ac-11e5-8411-004a8d7c5dc7.png)

<details>
<summary>

Here's what is in the wrapper.log:</summary>

`INFO   | jvm 1    | 2016/02/17 20:19:05 | [qtp1712926266-57] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/02/17 20:19:05 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.addUser(org.traccar.web.shared.model.User) throws org.traccar.web.shared.model.InvalidMaxDeviceNumberForUserException' threw an unexpected exception: java.lang.IllegalArgumentException
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/02/17 20:19:05 | Caused by: java.lang.IllegalArgumentException
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.traccar.web.server.model.DataServiceImpl.addUser(DataServiceImpl.java:222)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/02/17 20:19:05 |       ... 42 more
`
</details>

**Comment by vitalidze** [comment]
Please see #519 #524 #509

**Comment by a4mkd9** [comment]
Hello,

Thank you for your reply. Solution mentioned in #519 helped - stopped traccar service, dropped `user_device` table, dropped `users` table, started traccar service.

Adding users now works as expected.
