### ISSUE TITLE
Need help with installing v3.3(Table "SERVER" not found;)

### ISSUE THREAD

**Issue by avakyan-georgiy** [vitalidze/traccar-web#529]
Hi there! Trying to install your web interface over original traccar-server (v3.3):
What i did:
1) Install original traccar-server v3.3 from traccar-linux-64-3.3.zip
2) Check if it works. It works fine.
3) Install your web-interface:
Do steps 1) 2) 3) 4) (skip 4.1 and 4.2) from http://traccar.litvak.su/installation.html, then 5) and 6).
4) Then I read other issues #509 #519 #520 #521, and do therse steps:
- stop traccar service
- delete databases from /opt/traccar/data
- modyfied traccar.xml config (commented out changelog string as in #510)
- start the traccar service and received next error:

```
Table "SERVER" not found; SQL statement: SELECT * FROM server; [42102-190] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:328 < ServerResource:40 < ...).
Also piece of text from tracker-server.log after traccar restart:
[root@localhost traccar]# tail logs/tracker-server.log 
2016-02-18 17:00:54  INFO: Character encoding: UTF-8 charset: UTF-8
2016-02-18 17:00:54  INFO: Version: 3.2-SNAPSHOT
2016-02-18 17:00:54  WARN: Table "SERVER" not found; SQL statement:
SELECT * FROM server; [42102-190] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:328 < PermissionsManager:55 < ...)
2016-02-18 17:00:54  WARN: Table "POSITIONS" not found; SQL statement:
SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, 
    time AS fixTime, valid, latitude, longitude, altitude, speed, course, address, 
    other AS attributes
    FROM positions WHERE id IN (SELECT latestPosition_id FROM devices); [42102-190] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:323 < ConnectionManager:55 < ...)
2016-02-18 17:00:55  INFO: Starting server...
```

Hope you can help me with this.

**Comment by gsiotas** [comment]
OK follow this: https://github.com/vitalidze/traccar-web/issues/510#issuecomment-182235445 to disable database creation/migration and drop all tables from database. By the first running of traccar it should create the tables for you.

**Comment by avakyan-georgiy** [comment]
Already did this. Get same error.

**Comment by gsiotas** [comment]
You don't need to delete the database just the tables.

**Comment by vitalidze** [comment]
I think you have missed something in configuration file. It looks like the web application is not starting at all. I suggest to look into `wrapper.log` file as well.

**Comment by vitalidze** [comment]
Also I highly not recommend to use H2 database in production system. Use MySQL instead.

**Comment by avakyan-georgiy** [comment]
Problem solved after I completely reinstall latest traccar server and traccar-web versions, move database from h2 to mysql and then drop positions table(just in case).
Thank you guys, @gsiotas, @vitalidze. Now I'm trying to find if there's some API to create and save "styles" for reports. That will help to get reports in one-click.
