### ISSUE TITLE
RESTful API problem 

### ISSUE THREAD

**Issue by WiliamM** [vitalidze/traccar-web#530]
Hi, Im trying to use the RESTful API on a project from my local computer and find out that i needed to allow CORS access. So In the GuiceServletConfig.java i chance it so all the Rest calls go through the LocalFilter 
Old `filter("/", "/traccar.html", "/m/","/m/index.html").through(LocaleFilter.class);` 
New`filter("/", "/traccar.html", "/m/", "/m/index.html" ,"/traccar/*").through(LocaleFilter.class);`. 
In the LocaleFilter.java file i added  
`((HttpServletResponse) servletResponse).setHeader("Access-Control-Allow-Origin","*"); ((HttpServletResponse) servletResponse).setHeader("Access-Control-Allow-Methods","GET,POST");
((HttpServletResponse) servletResponse).setHeader("Access-Control-Allow-Headers","Origin, X-Requested-With, Content-Type, Accept");`

and it now works all fine when using the **/traccar/rest/login** but when using any other RESTful commands its response with **Unauthorized** **HTTP code 401** is it so that no Session is set or is it something else that cause this problem? Is it something that can be fixed and how?

**Comment by vitalidze** [comment]
First of all I suggest to not add functionality to `LocaleFilter` but rather create your filter instead. It's not a 'local' filter, but the 'locale' filter (with 'e' at the end), which purpose is to add 'locale' header for the GWT application.

Regarding your _401_ code you need to have properly set the `JSESSIONID` header for each request to the API. Find additional information here: http://traccar.litvak.su/features/rest-api.html

**Comment by WiliamM** [comment]
Thank you so much, It works all fine now

**Comment by vitalidze** [comment]
You are welcome. Please close this issue if you don't have any other questions.
