### ISSUE TITLE
a way to show stops and drives on the map

### ISSUE THREAD

**Issue by houssamfarag** [vitalidze/traccar-web#531]
is there a way to show stops and drives on the map 
i can generate a report for stops and drives but it loads in a page with coordinates without a map 

can i show them on map like this 

![traccar](https://cloud.githubusercontent.com/assets/17338209/13198869/3f433282-d81d-11e5-9c4d-424305eac879.jpg)

where p indicates stops and the red flag indicates drives and the start and the stop are the green signs one with play logo and the other with stop logo

thanks a lot

**Comment by vitalidze** [comment]
Such functionality is not yet present. But it is in plans. Also I plan to add new icon type or something like 'overlay' icon type to show stops on the main map view for latest positions and positions from archive.

**Comment by houssamfarag** [comment]
thanks a lot vitalidze for the great work 

waiting for the updates

Regards

**Comment by gsiotas** [comment]
:+1:

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
