### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#533]
Hello,

Please what is this update interval for ?

![updateinterval](https://cloud.githubusercontent.com/assets/15246747/13208186/67f22b9a-d96a-11e5-94cf-5ba638324691.jpg)

**Comment by vitalidze** [comment]
Currently latest positions of devices are fetched by making periodic requests to the server. This the time between such requests.

**Comment by thogo1977** [comment]
what unit is it? Thanks and have a good time

**Comment by vitalidze** [comment]
@thogo1977  It's in milliseconds, so default value 15000 means 15 seconds.
