### ISSUE TITLE
Cant figure out how to configure mail notifications

### ISSUE THREAD

**Issue by Estebanmg** [vitalidze/traccar-web#536]
I am trying to set up the email notifications but I keep getting this error: "500 Server Error The call failed on the server; see server log for details". What could I be missing? I think I set up the mail server, port and credentials the right way. Still I cant get it to work, Is there some tutorials about this?
What mail smpt service should I use? Is google´s one compatible with this web UI? 

PD. Im using traccar 2.12

Thanks in advance

**Comment by vitalidze** [comment]
First of all it's worth to look to the server logs, `wrapper.log` in particular. There should be some error message.

Google (gmail) is compatible for sure, but requires a third party application access configuration [here](https://www.google.com/settings/security/lesssecureapps)

Generally, any SMTP server should be compatible. If you still have some issues I recommend to first configure any other SMTP client (MS Outlook, Thunderbird, unix `sendmail`, etc.) and after that when your configuration works there - put exactly same settings to traccar.

**Comment by Estebanmg** [comment]
Thanks alot for quick response, Im already working on it, Another question... Is there any detailed guide on how to install your web mod to the lastest traccar version, I cant find the traccar-web.war file on the new installation it seems to be replaced by the "web" folder, looking forward to do this

**Comment by vitalidze** [comment]
Installation instructions are here: http://traccar.litvak.su/installation.html

If you are going to install it over 3.3 (latest version at the moment of writing) then most probably following issues will be of help #510 #519 #520 #521 #524

**Comment by johansid** [comment]
if using gmail please use 
from -> your email
server -> smtp.gmail.com
port -> 587
secure conn type -> STARTTLS
use auth -> true
user -> your email
pass -> your pass

**Comment by Estebanmg** [comment]
I keep getting the next error

"
Prueba fallida. Por favor, verifica los parámetros.
(Test failed. Please verify the parameters)

500 Server Error The call failed on the server; see server log for details"

Even tho I think the parameters are right, Tried different emails tho

**Comment by vitalidze** [comment]
As it says it's worth to look at the `wrapper.log` file.

**Comment by wolfbgn** [comment]
if using gmail please use 
from -> **your email**
server -> smtp.gmail.com
port -> 465
secure conn type -> SSL/TLS
use auth -> true
user -> **your email**
pass -> your password

Gmail has a limit of 2000 mails per day.
Keep in mind that Traccar sends alot of notifications and any mail server will take them for spam and block your IP.

**Comment by sdip025** [comment]
Im using traccar 2.12.  I configured from -> your email
server -> smtp.gmail.com
port -> 465
secure conn type -> SSL/TLS
use auth -> true
user -> your email
pass -> your password.
And testing successfully.But I wants to know that where i will set "TO" mail id  or receiver mail id?
please tell me what i will do..

**Comment by vitalidze** [comment]
@sdip025 

> And testing successfully.But I wants to know that where i will set "TO" mail id or receiver mail id?

You can set it up in user profile.

Please don't resurrect old closed threads.
