### ISSUE TITLE
Google map drawing tools

### ISSUE THREAD

**Issue by kampit** [vitalidze/traccar-web#539]
I have create a polygon using [**google map drawing tools**](https://google-developers.appspot.com/maps/documentation/javascript/examples/full/drawing-tools) & saved the latitude & longitude direct to the `geofences` table in the `points` column. 

I stored same format like traccar.

By the way when I looked into Geo-Fences tab from web, there is no polygon line was drawn.

Actually how the polygon works on traccar?

**Comment by vitalidze** [comment]
Have you set up the width and color of line? Also it's worth to try 'polygon' type of geo-fence.

**Comment by kampit** [comment]
@vitalidze Yes..

I make a default value & just add the `points` value when inserted to the database.

Also the `users_geofences` inserted as well.

Here an example.

![screen shot 2016-02-25 at 3 01 27 am](https://cloud.githubusercontent.com/assets/6607338/13297239/494e4b20-db6c-11e5-98ef-3e76b6408e86.png)

**Comment by vitalidze** [comment]
This looks correct. The format is:

```
{longitude1} {latitude1},{longitude2} {latitude2},...,{longitudeN} {latitudeN}
```

I see two issues here:

1) `allDevices` is set to 0, means this is a device-specific geo-fence. You should define devices relationship and it will be only shown only when you either click on geo-fence or on appropriate device.

2) Probably the precision is too high and javascript cannot parse such values. Do you see any error messages in web browser console?

**Comment by kampit** [comment]
1. `allDevices` is 0 when we not share the geo fences.
2. If we drawing from the Geo-Fences tab it's working fine.
3. Example : http://jsfiddle.net/cb1su05f/embedded/result/
4.  we draw & copy the results & modify the `{longitudeN} {latitudeN}` following the traccar format.
5. replace the `points` with google maps value and polygon shape is gone.

**Comment by vitalidze** [comment]
I have no idea what is happening. If it is text in a correct format then it should work fine. Check format of your values and errors in web browser console.

**Comment by kampit** [comment]
I found it. `{longitude} {latitude}` vs `{latitude} {longitude}`

Thanks @vitalidze
