### ISSUE TITLE
Adding users with Chrome doesn't work

### ISSUE THREAD

**Issue by webmst** [vitalidze/traccar-web#540]
Hi Vitaly, I'm back here with this issue we briefly analyzed in #538 with mixed database problems.

To summarize symptoms according to your suggestions, this is what's happening:
- On my working `traccar-web` installation based on `traccar 3.3`  and using Chrome as a browser, I'm unable to _add a new user_; when I press the `add` button, a form presenting username/password of the admin user is displayed (like editing); this time (yesterday - with database problems mentioned in #538 - it didn't solve) **I can manually modify the given username in the textbox**, otherwise a `"username is already taken"` message is displayed when I press `save`
- Trying to clear the browser cache as you suggested on the [installation page](http://superuser.com/questions/548096/how-can-i-clear-cookies-for-a-single-site) doesn't change anything and the same behavior is observed on 2 PCs of mine (that have both accessed the traccar gui before)
- Using IE11 on the same PCs, this issue is not seen at all
- The same problem happens to me accessing the _demo_ site `http://d.traccar.litvak.su`; in this case it is even stranger: the current user (webmst) is not seen on the list but - pressing the `add` button - a form editing it is displayed
- you have already confirmed not to be able to reproduce this issue (and nobody seems to be reporting it at the moment, but adding users could be not so common), so I'm almost sure I'm slipping on a banana peel here, still I have no ideas about the cause and the possible remedy

**Comment by petyots** [comment]
Same issue here...

**Comment by djuras** [comment]
Same problem with me, tried to delete databases but no success

**Comment by vitalidze** [comment]
> The same problem happens to me accessing the demo site http://d.traccar.litvak.su; in this case it is even stranger: the current user (webmst) is not seen on the list but - pressing the add button - a form editing it is displayed

I have just logged in as the `webmst` and latest google chrome `48.0.2564.116 (64-bit)` on the demo server. First of all it is expected that `webmst` will NOT be on this list because all users on demo server are managers and in `users` list manager sees ONLY managed users. If you want to edit password or anything else then you should do it in `account` page. Then I am still not able to reproduce the issue with `Add` button on `Users` page. It works as expected. See below screen shots:

![screen shot 2016-03-06 at 10 16 14](https://cloud.githubusercontent.com/assets/2294325/13552868/8893d30c-e384-11e5-92f1-313152f314f2.png)
![screen shot 2016-03-06 at 10 16 19](https://cloud.githubusercontent.com/assets/2294325/13552869/8894d28e-e384-11e5-9299-dfe92cb8760c.png)
![screen shot 2016-03-06 at 10 16 26](https://cloud.githubusercontent.com/assets/2294325/13552870/88970f04-e384-11e5-90a4-71dbf4f1f92c.png)

I think the issue is some misunderstanding of the current functionality.

**Comment by petyots** [comment]
You should delete changelog record from traccar.xml and everything will be ok then you will be able to manipulate users. If u need instructions let me know.

**Comment by vitalidze** [comment]
@petyots are you sure this will help to NOT see the credentials of admin in the `Users` screen after you press the `Add` button? From my understanding this is the main issue here.

**Comment by webmst** [comment]
@vitalidze 
Hi Vitaly and thank you for the reply; I've just read your message.

> First of all it is expected that  webmst  will NOT be on this list because all users on demo server are managers and in  users  list manager sees ONLY managed users

I can understand that listed users are only the managed ones (so it is ok the list was empty); what I cannot understand is that - with an empty list - the `add` button was still behaving like a 'edit' button, trying to change something I hadn't either selected.

> I think the issue is some misunderstanding of the current functionality.

As you requested in #538, I was just trying to reproduce the inability of adding a new user on the demo site and so I described what was happening to me.

In the meantime, I've checked this issue accessing my server with some PCs I hadn't used before **and I can confirm that it doesn't happen** so now I'm curious to understand why this is happening _only with the Chrome browser and using the PCs that were involved in the previous #538 database issues_ (and - if it is a 'local' issue - why it is not reset by a cache clean).

**Comment by vitalidze** [comment]
Well, my only guess is that you have some browser extension, which fills fields automatically for you. Try to disable all extensions (AFAIK there is some mode in chrome to do so) and check whether it helps. From the code I can clearly see that there is NO way to edit user from the `Users` screen. The only case when you get fields filled from current user account is when you click on `Account` button at the top-right menu.

**Comment by webmst** [comment]
@vitalidze Well, that was a good guess!

Strange to say but, after having disabled Chrome's default password storage feature (no 'extension' had been installed) and pressing the `add` button, the GUI doesn't show username/password for the admin user any more. I've lost the automatic logon capability but it doesn't matter.

@petyots @djuras Try to disable password storage selectively: open [chrome://settings/](url), select _password manager_ and delete the related traccar-web GUI url.

@vitaly I still wonder why Chrome thinks it is time to retrieve the admin credentials on a blank "new user" form... never seen this before.

**Comment by vitalidze** [comment]
I have seen such behaviour dozen of times. I think chrome matches form fields by name and when it encounters some known fields (like username, login, password, email, address, etc.) it just fills them in. I think it is a matter of google chrome configuration and I see no issue in the traccar web app.

**Comment by webmst** [comment]
Well Vitaly, at this point I was sure the problem was not in the traccar-web application (this is why I had defined it _"banana peel"_ previously).

We have done all of this (the issue started with #538 and you correctly suggested to split it in two separate issues) because it seemed correlated to a database problem introduced in the latest version of traccar-web (in that first one the `username is already taken` message was still persisting even if had deleted the 'admin' credentials and written a new username).

If this Chrome's behaviour can be said to be common, the analyzing effort was well worth having it on the traccar-web issue tracker for future user reference.

**Comment by vitalidze** [comment]
I don't mind having it on issue tracker. The more information and cases we have is the better, the more experience user and me myself will get out of it. Thank you for helping in this investigation.

My concern is that I don't see any issue in the web application to be fixed.
