### ISSUE TITLE
 WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException 

### ISSUE THREAD

**Issue by johansid** [vitalidze/traccar-web#541]
I have traccar 3.3 and it's working well.
But in traccer server log, i saw this warn
 WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:256 < ConnectionManager:110 < ...)

Any info for this

**Comment by vitalidze** [comment]
Please read #439

**Comment by johansid** [comment]
Thanks bos
