### ISSUE TITLE
Question - How archive module work?

### ISSUE THREAD

**Issue by thaihau** [vitalidze/traccar-web#543]
Any documentation explaining archive module work? 
Example after select Device, Date Range and press filter?
I had have added in demo site https://d.traccar.litvak.su/ also cant search any results.

**Comment by vitalidze** [comment]
There are no such documentation because this function is quite intuitive. You just:
- select device
- set up the time period
- hit 'Load' button

Then it will show the trace on map and points of that trace in table in archive panel. If you don't see anything then try disabling 'filter' function and check the time period, maybe set up a wider time period. Also it's worth to disable the 'snap to roads' function since it works only when your trace is less than 100 points length.

**Comment by thaihau** [comment]
Work in the demo server, however the one i setup cant show any results. But i checked there is records in the database.
Found this entry in tracker-server.log, not sure is this the root cause or not. `2016-02-29 01:32:28  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:256 < ConnectionManager:110 < ...)`

**Comment by vitalidze** [comment]
Are you sure you have the data for that particular device in your database for the period you are doing the query?

> Found this entry in tracker-server.log, not sure is this the root cause or not. 2016-02-29 01:32:28 WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:256 < ConnectionManager:110 < ...)

This one can be safely ignored. Or you can disable the query as said in #439

**Comment by thaihau** [comment]
Yes, i am sure the devices is added into system. From console, i got this js error, not sure is this the cause or not.

<img width="1209" alt="screen shot 2016-02-29 at 3 58 00 pm" src="https://cloud.githubusercontent.com/assets/851803/13388704/41c12802-defd-11e5-9d02-bd3a1af625f0.png">

**Comment by vitalidze** [comment]
Yes, it looks like the cause. I think the reason is the 'snap to roads' function. Try to disable it and re-run the 'load' query. The function is located in the hidden part of menu (on toolbar at the right hand side the '>>' button).

**Comment by thaihau** [comment]
Is this uncheck the "Zoom to track" function?

<img width="537" alt="screen shot 2016-02-29 at 5 06 02 pm" src="https://cloud.githubusercontent.com/assets/851803/13390057/c39011fa-df06-11e5-9bfa-b81d45f841ab.png">

**Comment by vitalidze** [comment]
No, it is called 'Snap to roads'. Looks like it is missing in your screen resolution. Try to enlarge browser window.

**Comment by thaihau** [comment]
Ok. Found it! Now i got everything working now after enlarge browser. Thanks!
Uploading the print screen hopefully can help other users.
<img width="1054" alt="screen shot 2016-02-29 at 5 22 53 pm" src="https://cloud.githubusercontent.com/assets/851803/13390415/232dc3e4-df09-11e5-8499-a0c1fd31db7b.png">
