### ISSUE TITLE
Why my position are not all saved

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#544]
Good day,
My module send GPS position to traccar. I observed that some are sent but not saved
I am using Adafruit board to manage my GPS module and format the URL and send the position to Traccar.
When my Adafruit microcontroller send the position, I have this in my log file store in a SD card

> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall: (0) 
> HTTP_term OK
> Coordinates sent (HTTP)

if HTTP_para URL or HTTP_action return me an error, the following line will not be display
and I also save into my log file the URL used to send the position:
http://dddddd.dyndns.org:5055/?id=865067020750884&valid=true&lat=46.456604&lon=6.218282&speed=41.40&altitude=722.09&heading=64.400001&batt=80&desc=GPS%20localisation&timestamp=2016-02-27%2016:48:35

I was surprise to se the above URL (I modified the url by adding dddddd) and nothing in my Traccar MySQL database. Then I copy/past the above URL to my browser and the position was saved. It means that the URL is correctly formated.

I have to understand why my microcontroller could send some position but this one and may be the 10 next following. Then after the 10 following it could send and save some until some could be sent but not saved
I looked at the traccar log file and I can not see a trace of my position sent at 2016-02-27 at 2016:48:35.

In my traccar.xml, I did not set any filter.

Some has a idea, why some position could be sent without error but it could not be saved without an error or warning message into the log?

Thank for your help

**Comment by vitalidze** [comment]
For me it sounds like an issue with your device. Maybe something with your code, or networking, etc. Anyway, the more proper place to ask is the backend issue tracker: https://github.com/tananaev/traccar/issues I don't think this issue is related with the web UI mod anyhow.
