### ISSUE TITLE
Why my desktop version does not shoe the map on my mobile

### ISSUE THREAD

**Issue by pierrot10** [vitalidze/traccar-web#546]
Dear All,
I am still testing my module, and I would like to see the desktop version from my smartphone.
When I click on "Desktop version" link I can see the a blank page while the smartphone version show me a map. Any idea Why?

I do have traccar 3.3 with traccar web UI and I am using Safari on a  Iphone

**Comment by vitalidze** [comment]
This is a bug. The issue here is that mobile version puts incorrect locale parameter to the desktop version. So it just does not start. You can remove the `?locale=` from URL and it should work.

**Comment by pierrot10** [comment]
Dear Vitalidze,
Thank for your reply. 
There is a way to not have it. So I mean, to change my local version to have to right URL to the link "Desktop version" (without ?local=)

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
