### ISSUE TITLE
traccar-web and Tomcat 8

### ISSUE THREAD

**Issue by petyots** [vitalidze/traccar-web#547]
Hello, i am trying to deploy the UI on tomcat but without any success... First of all is that possible ? If it's possible can you give me some hints? Thanks in advance

**Comment by vitalidze** [comment]
I think it's possible. Though I haven't tried it. You will need to define the datasource named `java:/DefaultDS` in your tomcat configuration. Then you may just deploy the `traccar-web.war` file. If it does not work for you then you should look into logs of your tomcat server.

**Comment by petyots** [comment]
I decided to leave it with jetty... If someone wants to make the server to work on domain or subdomain you can do it with nginx reverse proxy. If someone is interested let me know.

**Comment by thaihau** [comment]
@petyots  Do you have the config for the nginx reverse proxy?
