### ISSUE TITLE
[Question] Difference between timeout and min. idle time in device settings

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#548]
Hi!
Quick question: What's the difference between timeout and min. idle time in device settings? I can't find the correct answer anywhere. From the release note I can see that

> 'Min. idle time' - used to calculate device status both in live data and on reports. Device will not be considered idle until it's speed is less than the defined value for the specified duration

The timeout is the time that has to pass in order for the device to be considered offline?

Thank you!

**Comment by vitalidze** [comment]
> The timeout is the time that has to pass in order for the device to be considered offline?

That's correct. I think you have answered your question yourself :)

So, these two times are used to control two different states of device:
- idle or stopped state - means device is not moving
- offline state - means device does not send any data for a while (the `timeout` time)

**Comment by gsiotas** [comment]
Nice! Thank you!
