### ISSUE TITLE
BG translation

### ISSUE THREAD

**Issue by wolfbgn** [vitalidze/traccar-web#553]
On Traccar-web interface I see Bulgarian dates - Март 2016, Април 2016 ...
In the notifications that I receive in the mail it is EN - Няма връзка Mon Mar 07 08:04:14 EET 2016!
Is it possible that to be fixed?

**Comment by vitalidze** [comment]
This is a matter of locale configuration for the java application. To change it to the Bulgarian I think there are two options:

1) Switch your operating system locale to Bulgarian.

2) Specify a command line option for the traccar application. See [this stackoverflow thread](http://stackoverflow.com/questions/8809098/how-do-i-set-the-default-locale-for-my-jvm) for additional info. The variables must be put into the wrapper configuration file (`wrapper.cfg` as far as I remember) as the `wrapper.additional.X` properties (see [docs](https://wrapper.tanukisoftware.com/doc/english/prop-java-additional-n.html))

**Comment by wolfbgn** [comment]
Thank you.
