### ISSUE TITLE
increase in distance

### ISSUE THREAD

**Issue by naveen91** [vitalidze/traccar-web#555]
Hi Vitaly,

I need a help, in the reports distance should be increased by 30% where ever distance is calculated. is it possible, if yes please let me know how.

**Comment by vitalidze** [comment]
This is really weird, but it is possible. Distance calculation happens in `GeoFenceCalculator` here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/GeoFenceCalculator.java#L32
