### ISSUE TITLE
Not able to create new user. "Username is already taken" error for any username

### ISSUE THREAD

**Issue by Vik27** [vitalidze/traccar-web#557]
Hello I have installed Traccar on AWS linux server. I am able to login an admin, however I not able to create or register a new user. Always gets "Username is already taken" error. I have attached the logs!
Kindly help!
[serverlog.txt](https://github.com/vitalidze/traccar-web/files/167164/serverlog.txt)

[servicelog_3_10.txt](https://github.com/vitalidze/traccar-web/files/167161/servicelog_3_10.txt)

**Comment by vitalidze** [comment]
Try solution from here https://github.com/vitalidze/traccar-web/issues/519#issuecomment-183276834

**Comment by Vik27** [comment]
I installed Traccar 3.2 version and now it is working fine. Thnanks for the help.
