### ISSUE TITLE
Login via Mobile Version, white screen when click "open Desktop version"

### ISSUE THREAD

**Issue by t3mp30r3k** [vitalidze/traccar-web#558]
anybody does have same issue with me ?
i got problem with blank or white screen when login with mobile version, and switch to desktop version .. it's version 3.3 (latest), even try with demo https://d.traccar.litvak.su/m/

**Comment by johansid** [comment]
Mas tempeorek,
Please edit the link, remove location.  
But its too heavy to access desktop version with mobile dev.

-----Original Message-----

**Comment by vitalidze** [comment]
This is a known issue. See #546
