### ISSUE TITLE
All positions of devices

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#559]
Hi Vitaly,

I am working on new report that should show graph with data from sensors. I would like to have all positions (`List<Position>`) from all selected devices sorted by time. What should be the correct way of getting it? 

Kind regards,

**Comment by vitalidze** [comment]
You can do it with the JPA query or criteria. For all positions it should be something like

``` java
// I assume that you have got these somehow
Device device = ...;
EntityManager em = ...;

List<Position> allDevicePositions = em.createQuery("SELECT x FROM Position x WHERE x.device = :device", Position.class)
    .setParameter("device", device)
    .getResultList();
```

Then in `allDevicePositions` there will be all positions of some device.

**Comment by mpele** [comment]
Hi Vitaly,
Thank you for your instructions. The main problem for me is how to create query that select multiple devices (that are selected by the Report). Could you help me with it?

**Comment by vitalidze** [comment]
You can run several queries, one per each selected device.

Another option is to use the `IN` clause, something like this:

``` java
// I assume that you have got these somehow
List<Device> selectedDevices = ...;
EntityManager em = ...;

List<Position> allPositionsOfSelectedDevices = em.createQuery("SELECT x FROM Position x WHERE x.device IN :mySelectedDevices", Position.class)
    .setParameter("mySelectedDevices", selectedDevices)
    .getResultList();
```

**Comment by mpele** [comment]
Thank you.
It works.
