### ISSUE TITLE
Problems when generate reports

### ISSUE THREAD

**Issue by silasvasconcelos** [vitalidze/traccar-web#560]
hi man, i need you help, how your make the reports,  on traccar, i'm working in an web application in PHP, but, when I tell you generate a report, is killing the serverm, thank for you attention.

**Comment by vitalidze** [comment]
I think your report is too big and cannot fit into memory. It's worth to check `wrapper.log` for error messages.

I don't understand what do you want with PHP and how it is related with existing reports. The application (and reports generators as well) is written in java.

**Comment by silasvasconcelos** [comment]
i'm working in an enterprise and we are developing an web interface in php, and using the traccar, only with the GPS, but, thank you for everything!
