### ISSUE TITLE
Not showing 8082

### ISSUE THREAD

**Issue by wolfbgn** [vitalidze/traccar-web#562]
I have Debian 8.3,  nginx and Traccar 2.12. I would like to be able to reach Traccar service not on http://mydomain.com:8082 but prefer http://mydomain.com/traccar.
How can I do that? 
Thank you.

**Comment by vitalidze** [comment]
I think the easiest way is to configure nginx reverse proxy. See this guide for additional information: https://www.nginx.com/resources/admin-guide/reverse-proxy/

Below is the example of nginx configuration on the demo site:

```
server {
        listen 443;

# ...
        server_name d.traccar.litvak.su;
# ...

        location / {
                proxy_pass http://127.0.0.1:8082;
        }
}
```

It works just fine for more than a year.

**Comment by wolfbgn** [comment]
I am sorry but I am not a pro. I do this for fun and track my cars. I use default.conf of nginx. Added at the end of the file following:
        server_name mydomain.com;

# ...

```
    location /traccar/  {
            proxy_pass http://127.0.0.1:8082;
 }
```

but nothing happens.

At the moment on mydomain.com ( var/www/html) I have default nginx welcome page.
On mydomain.com/traccar  ( var/www/html/traccar ) in /traccar/ I have put index.html with redirection rule and it works fine but I  see mydomain.com:8082 and it does not work with SSL.
I have on the same machine iRedmail for Traccar-web mail notifications and every thing works fine.
I can access mail from mydomain.com/mail/ over SSL (bought certificate - green ). After that browser cashe does not allow mydomain.com/gps/ redirection because of http.
Sorry to bother you.

**Comment by wolfbgn** [comment]
Thank you, Vitaly. I used your suggestion. It works fine.
