### ISSUE TITLE
Expired session - wrong procedure call

### ISSUE THREAD

**Issue by flyjodel** [vitalidze/traccar-web#564]
Hi !

I did restore a mysql database in traccar because of the resintallation of my linux version.
But now... I always get this message ::

Wrong procedure call
Session expired

I get the same issue with all my users.

![13-03-2016 19-40-00](https://cloud.githubusercontent.com/assets/12589144/13730624/5d7d0fd2-e954-11e5-8283-40928cfb4cc7.jpg)

how can I fix this issue ? I think there is something to fix in the database, but which one ?
Many thanks
Michel

**Comment by vitalidze** [comment]
Do you see it in all web browsers? I think it's worth to refresh page and if problem exists then look in `wrapper.log` file.

**Comment by flyjodel** [comment]
yes, i've erased the cache in chrome... doesn't work. I've tried chrome and firefox on windows, on 2 different computers as chrome on my android phone. Same issue.

in the log file i can find this line ::

--> UPDATE
INFO   | jvm 1    | 2016/03/13 23:20:30 | [qtp16295851-55] WARN / - Exception while dispatching incoming RPC call
<<-- END OF UPDATE

this is the wrapper.log ::

STATUS | wrapper  | 2016/03/13 21:50:30 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/03/13 21:50:30 | Java Service Wrapper Community Edition 32-bit 3.5.28
STATUS | wrapper  | 2016/03/13 21:50:30 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/03/13 21:50:30 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/03/13 21:50:30 | 
STATUS | wrapper  | 2016/03/13 21:50:31 | Launching a JVM...
INFO   | jvm 1    | 2016/03/13 21:50:31 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/03/13 21:50:34 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/03/13 21:50:34 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/03/13 21:50:35 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9fvmb3s2u00x67|1b44943, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9fvmb3s2u00x67|1b44943, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccardb?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=*****_, password=**_***}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2016/03/13 21:50:38 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @6821ms
INFO   | jvm 1    | 2016/03/13 21:50:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.15.v20160210
INFO   | jvm 1    | 2016/03/13 21:50:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@1628de6{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/03/13 21:50:47 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2016/03/13 21:51:07 | Mar 13, 2016 9:51:06 PM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2016/03/13 21:51:07 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2016/03/13 21:51:07 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Position with id 21652
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:183)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:219)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:275)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1070)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:989)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:716)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.type.EntityType.resolve(EntityType.java:502)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:170)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.performTwoPhaseLoad(AbstractRowReader.java:244)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:215)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:140)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:138)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:186)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4126)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:503)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:468)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:213)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:275)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1070)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:989)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:716)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.type.EntityType.resolve(EntityType.java:502)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:170)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1115)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.processResultSet(Loader.java:973)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.doQuery(Loader.java:921)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.doList(Loader.java:2554)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.doList(Loader.java:2540)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.Loader.list(Loader.java:2365)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1264)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:449)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:101)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2016/03/13 21:51:07 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/03/13 21:51:07 | 
INFO   | jvm 1    | 2016/03/13 21:51:07 | Mar 13, 2016 9:51:06 PM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2016/03/13 21:51:07 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2016/03/13 21:51:07 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Position with id 99573

**Comment by flyjodel** [comment]
something is strange and let me think that it is not a java problem.

I am able to create a new user, and I can register a new device, log positions, they appear in the mysql database. But no access to the usual users that were registered before the reinstallation.

There must be somewhere a flag or so in the database, saying that a session is expired or not. Don't you think so ?

**Comment by vitalidze** [comment]
In log I can see that your database is damaged. There is at least one device with latest position reference that does not point to an existing position.

**Comment by flyjodel** [comment]
I don't want to bother you too much, ut can you show me which line leads you to this conclusion ? Then I'll try to fix it.
Many thanks

**Comment by vitalidze** [comment]
This:

```
INFO | jvm 1 | 2016/03/13 21:51:07 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Position with id 21652
```

and this:

```
INFO | jvm 1 | 2016/03/13 21:51:07 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Position with id 99573
```

**Comment by flyjodel** [comment]
you were right !

In fact I understand what was the fact ::
I didn't want to store the positions where the speed = 0 so I  ::

set FOREIGN_KEY_CHECKS=0;
the I deleted all the positions where speed=0
and then
set FOREIGN_KEY_CHECKS=1;

This lead the database to have wrong latestPosition_id

To fix it, I looked into the positions table for the last position of each device with this command ::
select id,time,device_id from positions where device_id=4 order by id desc limit 0,1;
and I put this 'id' in the devices table at the right place.

Thank you again, now everything works well. Sorry for the disturbance, that's what's going on when you plan with SQL tables without care.
Michel

ps : I think you can mark this post as closed or delete it if you think it is not worth to keep in the issues
