### ISSUE TITLE
Dutch language not working (?locale=nl)

### ISSUE THREAD

**Issue by novistudionl** [vitalidze/traccar-web#569]
Hi,

First of all: great work! Second: i have a problem with the Dutch language. When i add the following URL parameter the page stays blank: ?locale=nl. Other languages like Polish work.

Traccar version 3.3
GUI version: latest

Please help in troubleshooting this issue. Thanks.

**Comment by vitalidze** [comment]
It was lost when I changed the way to work with localization (the goal was to improve compilation time). I have just put it back. It will be in next version. You can build `traccar-web.war` file yourself if needed by following official instructions: http://traccar.litvak.su/building.html

**Comment by novistudionl** [comment]
great, you rock! Thanks a lot!

**Comment by novistudionl** [comment]
It works with the new build. Thanks a lot again, you rock!

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
