### ISSUE TITLE
Receive alerts of offline devices

### ISSUE THREAD

**Issue by aymanrb** [vitalidze/traccar-web#57]
I would like to receive email notifications when the device stops reporting for a time (gets offline). It happens every now and then with our fleet due to the data usage charges on the devices with prepaid subscriptions.

I would like to be notified instead of loosing track of the vehicle for a while.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/01/13/Notifications,-archive-styling-and-couple-minor-improvements.html), [article](http://traccar.litvak.su/features/notifications.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
