### ISSUE TITLE
Can't send command via API

### ISSUE THREAD

**Issue by hanselsen** [vitalidze/traccar-web#571]
I resumed my work in Traccar and I'm again struggling with sending (raw) commands.
Preferably I want to login using /traccar/rest/login and then use /traccar/rest/sendCommand to send a command to my minifinder device.
I've created this pull request for sending raw commands https://github.com/tananaev/traccar/pull/1725
Can somebody please provide me the necessary bodies/headers for sending custom commands?

Thanks

**Comment by hanselsen** [comment]
Somebody with a solution perhaps?

**Comment by vitalidze** [comment]
We have already discussed sending of raw commands by email. Here is an example of command argument for the `sendCommand` call:

``` json
[{
    "deviceId":1,
    "type":"CUSTOM",
    "command":"M,700"
}]
```

As for authentication you can read official docs: http://traccar.litvak.su/features/rest-api.html
