### ISSUE TITLE
retention database for 3 montrh

### ISSUE THREAD

**Issue by t3mp30r3k** [vitalidze/traccar-web#572]
does anybody know how to set automate retention database for each 3month. 
i'm stil using version 3.2

**Comment by vitalidze** [comment]
Currently the only way to do it is to set up a scheduled task in your operating system (like a cron task), which will run some queries against your traccar database periodically (say once per night). The queries are suggested here: #244

Also I plan to implement this functionality right in code. So such scheduled removal will be built in to the system. I am thinking about global configuration and configuration per user. I need it for my private task, so there is a high probability that this will be included in nearest future (say within next couple of weeks).

**Comment by t3mp30r3k** [comment]
ok.. thanks vitalidze..
traccar is a good gps apllication, and its look better if retention data could implemented as well.
