### ISSUE TITLE
Login Problem After Installation

### ISSUE THREAD

**Issue by pmercadohn** [vitalidze/traccar-web#574]
# Hi I have a problem after following the installation proccess It won't let me login with created user or enroll new ones; for the account already created display error "wron user or password" and for enrolling new ones it displays "Username already taken" wish I now is not.

I don't want to sound stupid but, why there is no .war file in my traccar instalation? I notice the replace of .war file in the installation process on your web site but the traccar package I install has no .war in it just a web folder.  I was installing version 3.4 of traccar and noticed that your guide is for 3.3. Y uninstall the 3.4 and install 3.3. got same errors.

I double check if traccar works before installing your web GUI and works fine the error apears after the .war installations proccess, any help will be gladllyapreciated.  I'm using Linux CentOs7 min.

**Comment by vitalidze** [comment]
> #Hi I have a problem after following the installation proccess It won't let me login with created user or enroll new ones; for the account already created display error "wron user or password" and for enrolling new ones it displays "Username already taken" wish I now is not.

This is a known issue. Try solution from here https://github.com/vitalidze/traccar-web/issues/519#issuecomment-183276834 (next time please search project's issue tracker before asking question).

> I don't want to sound stupid but, why there is no .war file in my traccar instalation? I notice the replace of .war file in the installation process on your web site but the traccar package I install has no .war in it just a web folder. I was installing version 3.4 of traccar and noticed that your guide is for 3.3. Y uninstall the 3.4 and install 3.3. got same errors.

The `traccar-web.war` file is not present since 3.0 version of traccar. These instructions apply to all versions and installations, and also can be used for an upgrade.

**Comment by inghenryh** [comment]
Hi, how to I Do?  Drop users table? Explain me please, my error is "User allready taken" I follow all Instalation instrucction. I test traccar 3.4 3.3 3.2 and 2.12 but the same error appear. the line database.changelog is missing from traccar.xml ... Do you have skype? I need contact you please. @vitalidze

**Comment by inghenryh** [comment]
Do you have skype? I need contact you please.

**Comment by vitalidze** [comment]
@inghenryh  You need to run SQL query, something like `DROP table users`. I have skype, but I don't want to share it here. You can contact me via email (from github profile).
