### ISSUE TITLE
3.4 Support

### ISSUE THREAD

**Issue by hanselsen** [vitalidze/traccar-web#575]
Hi @vitalidze when will the support be released for traccar 3.4?
Still struggling with the sending commands stuff.
Because the attributes of commands can be Strings now, would you care to update the Command class so that I can send strings as commands? (see minifinderprotocol)

**Comment by vitalidze** [comment]
I don't have an estimated date. There are two main reasons of the delay:

1) Lack of free time
2) No clear understanding on how to integrate database schema upgrades with the new approach used on backend (through liquibase). I want to support migration both for old versions (2.x and 3.0, 3.1 and 3.2) and new versions.

**Comment by gpproton** [comment]
I'm really hoping you have time soon, really looking forward to get new update.

**Comment by leontino** [comment]
Wainting too!

**Comment by vitalidze** [comment]
I think that soon I will update instructions with the following:

> For new installation over 3.3 or 3.4 and after upgrade of traccar backend (i.e. from 3.2 to 3.3/3.4) there will be two additional steps:
> 
> 1) Disable database migrations made by the backend by commenting out the following configuration file entry:
> 
> `<entry key='database.changelog'>./database/changelog-master.xml</entry>`
> 
> 2) Database must be empty before first startup. To ensure this please drop and re-create existing database:
> - for default H2 database this can be done by removing contents of `data` folder under the traccar installation folder. This database will be created automatically when service starts.
> - for any other databases like MySQL there are queries to drop and create them. Also this can be done via GUI management tools (like MySQL workbench).
> 
> _IMPORTANT NOTE_: this will delete all existing data. If it needed to be preserved, then instead of dropping database just use a brand new database with a different name. Then data can be copied between databases using SQL queries or some scripts.

From my point of view this will be the most universal and working way to install the Traccar Web UI Mod over versions 3.3 and 3.4. Other things like new command attributes support will be added later.

**Comment by kweskoj** [comment]
Hi thankx for the great work. do you have step by step installation  manual to upgrade 3.4 of traccar.

**Comment by vitalidze** [comment]
To install the web UI mod over traccar 3.4 you need to follow [official instructions](http://traccar.litvak.su/installation.html) + instructions from my previous comment in this thread.

**Comment by kweskoj** [comment]
there is nothing on 3.4 .and also there is no traccar-web.war file with 3.4.the only file is:tracker-server.jar in
/opt/traccar

**Comment by vitalidze** [comment]
You can follow instructions specific for 3.3, but there are lot of common instruction steps for all 3.x versions, which you must follow as well. 

The `traccar-web.war` is not present since 3.x, the instruction step telling to make a backup is for the case when you do the upgrade.

**Comment by kweskoj** [comment]
how how do i install your version of traccar. sorry but am abit novice

**Comment by kweskoj** [comment]
any direct and straight away instructions?

**Comment by kweskoj** [comment]
i did a fresh installation from traccar.org

**Comment by kweskoj** [comment]
was able to do it. wow . you rock my world :)
thankx alot. expect my donation after test. thankx

**Comment by kweskoj** [comment]
2016-03-28 12:05:56  INFO: Shutting down server...
2016-03-28 14:04:25  INFO: Operating system name: Linux version: 2.6.32-042stab093.5 architecture: amd64
2016-03-28 14:04:25  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.60-b23
2016-03-28 14:04:25  INFO: Memory limit heap: 247mb non-heap: 0mb
2016-03-28 14:04:25  INFO: Character encoding: UTF-8 charset: UTF-8
2016-03-28 14:04:25  INFO: Version: 3.4-SNAPSHOT
2016-03-28 14:04:25  WARN: Table "SERVER" not found; SQL statement:
SELECT \* FROM server; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:327 < PermissionsManager:55 < ...)
2016-03-28 14:04:25  WARN: Table "POSITIONS" not found; SQL statement:
SELECT \* FROM positions WHERE id IN (SELECT positionId FROM devices); [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:322 < ConnectionManager:55 < ...)
2016-03-28 14:04:25  INFO: Starting server...
2016-03-28 14:11:53  WARN: Table "SERVER" not found; SQL statement:
SELECT \* FROM server; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:327 < PermissionsManager:55 < ...)

**Comment by kweskoj** [comment]
anything wrong with this server log?

**Comment by vitalidze** [comment]
I think this one can be safely ignored:

```
2016-03-28 14:11:53 WARN: Table "SERVER" not found; SQL statement:
```

This one should be gone after you restart your service for the second time:

```
2016-03-28 14:04:25 WARN: Table "POSITIONS" not found; SQL statement:
```

If it does not then most probably you have set up something incorrectly and need to check entries in your configuration file.

**Comment by kweskoj** [comment]
will check and get back

**Comment by kweskoj** [comment]
2016-03-28 14:45:50  INFO: Operating system name: Linux version: 2.6.32-042stab093.5 architecture: amd64
2016-03-28 14:45:50  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.60-b23
2016-03-28 14:45:50  INFO: Memory limit heap: 247mb non-heap: 0mb
2016-03-28 14:45:50  INFO: Character encoding: UTF-8 charset: UTF-8
2016-03-28 14:45:50  INFO: Version: 3.4-SNAPSHOT
2016-03-28 14:45:50  WARN: Table "SERVER" not found; SQL statement:
SELECT \* FROM server; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:327 < PermissionsManager:55 < ...)
2016-03-28 14:45:51  INFO: Starting server...

**Comment by kweskoj** [comment]
anything to worry a bout?

**Comment by vitalidze** [comment]
I don't think so.

**Comment by vitalidze** [comment]
I have just updated installation instructions for v. 3.3 (and higher), please see paragraph 4.3: http://traccar.litvak.su/installation.html
