### ISSUE TITLE
Icons with black background in map (Traccar V3.3)

### ISSUE THREAD

**Issue by Fleetracking** [vitalidze/traccar-web#576]
Hello
After installation of last version supporting traccar 3.3 i remarked a default relative to viewing icons of markers and cars on map (icons with black background)

![image](https://cloud.githubusercontent.com/assets/17362734/13901417/63b40742-ee23-11e5-9382-286fbb4b9c75.png)

Best regards

**Comment by vitalidze** [comment]
This looks like an issue with the web browser. What web browser are you using?

Also, does it reproduce on the demo site https://d.traccar.litvak.su?

**Comment by Fleetracking** [comment]
Hi
I use chrome browser.
On demo site is OK, but the problem appears for me just after upgrade of my
server.
BR
Le 20 mars 2016 6:25 AM, "Vitaly Litvak" notifications@github.com a
écrit :

**Comment by vitalidze** [comment]
Can you try installing traccar server from scratch on another PC? Also it's worth to try accessing it from a different machine/web browser. These pictures are actually the PNG images with transparent background. They should render fine in a modern browser.

**Comment by Fleetracking** [comment]
Hi
Unfortunately when i tried to reinstall from scratch my traccar server, i
have a serious issue to start traccar daemon.

---

root@HP-Compaq# /opt/traccar/bin/traccar start
Starting traccar...
/opt/traccar/bin/./wrapper: 1: /opt/traccar/bin/./wrapper: Syntax error:
word unexpected (expecting ")")
Waiting for traccar..................

## WARNING: traccar may have failed to start.

Do you have any idea about this error.
BR

**Comment by vitalidze** [comment]
I think you have some error in your configuration file (`traccar.cfg` or `traccar.xml` located under `conf` folder). You should have done some modifications according to http://traccar.litvak.su/installation.html. I suggest to double check all entries there.

**Comment by Fleetracking** [comment]
Hello
Finally i reinstalled traccar from scratch.
The source of this issue is a modification that i did to "reset.css" file in old "traccar-web.war" file (V3.2).
No problem for version 3.2 but this issue appeared for new package supported V3.3.

---

## html,body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,p,blockquote,th,td{margin:0;padding:0;}body,html{border:0;background:url(**http://Mysite.com/Authentication_Window.jpg**);}img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}ol,ul {list-style:none;}caption,th {text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;}q:before,q:after{content:'';}

Do you have a new way to change the style of authentication window. Another question by the way how to modify the list of supported langages in authentication page (for exp: keep only Fr & En)?

Best ragards

**Comment by vitalidze** [comment]
> Do you have a new way to change the style of authentication window

I have described the correct way here: https://github.com/vitalidze/traccar-web/issues/265#issuecomment-140539981 (requires project recompilation) I don't think you should change the `reset.css` file, the approach was quite tricky from the start.

> Another question by the way how to modify the list of supported langages in authentication page (for exp: keep only Fr & En)?

You need to change the `I18N.gwt.xml` file and leave only desired locales there: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/i18n/I18N.gwt.xml#L18

**Comment by Fleetracking** [comment]
Hi
For second point, i changed "I18N.gwt.xml" in "traccar-web.war" file, restart traccar service and clear browser cache, but all languages still appears in authentication window.

**Comment by vitalidze** [comment]
You need to rebuild the `traccar-web.war` file after that by following these instructions: http://traccar.litvak.su/building.html (you may require to install apache maven on your development machine)

**Comment by Fleetracking** [comment]
Hi 
I succesfully build war package for second point (languages filtred).
Regardind first point (styling authentication window), i follow your comment as below but backgound image loaded loaded and the page stay in loading state (background.jpg put in images folder).
Any idea about this behavior.
BR

-----------------------------------traccar.html----------------------------------------------------------------------

    

```
<style type="text/css">
  .olControlAttribution { bottom: 5px !important; }
  .olImageLoadError {
      /* Some layers (e.g. seamark, sports) only render tiles where
       * an object exists. Unknown tiles are displayed in pink by
       * default. We change this behaviour by hiding these tiles.
       */
      display: none !important;
  }

  .rootWithBackground {
    background: url('/theme/img/background.jpg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }

</style>
```

----------------------------"onFailure"-- inside -----"onLogin" method --------------------------------------------------
 public void onFailure(Throwable caught) {
                    **RootPanel.get().addStyleName("rootWithBackground");**
                    if (caught instanceof UserBlockedException) {
                        new AlertMessageBox(i18n.error(), i18n.errUserAccountBlocked()).show();
                    } else if (caught instanceof UserExpiredException) {
                        new AlertMessageBox(i18n.error(), i18n.errUserAccountExpired()).show();
                    } else {
                        new AlertMessageBox(i18n.error(), i18n.errInvalidUsernameOrPassword()).show();
                    }

##                 }

**Comment by vitalidze** [comment]
@Fleetracking code in java in that thread's comment is outdated. Now you need to put it to the same `login` method but to the `onSuccess` for the case when current user can not be found:

``` java
  public void login(final LoginHandler loginHandler) {
        this.loginHandler = loginHandler;

        Application.getDataService().authenticated(new BaseAsyncCallback<User>(i18n) {
            @Override
            public void onSuccess(User result) {
                if (result == null) {
                    // here you add the style to the root panel
                    RootPanel.get().addStyleName("rootWithBackground");
                    // ------
                    dialog = new LoginDialog(LoginController.this);
                    hideLoadingDiv();
                    dialog.show();
                } else {
                    ApplicationContext.getInstance().setUser(result);
                    hideLoadingDiv();
                    loginHandler.onLogin();
                }
            }

            void hideLoadingDiv() {
                RootPanel.getBodyElement().removeChild(DOM.getElementById("loading"));
            }
        });
    }
```

**Comment by Fleetracking** [comment]
Yes its done
Thank you for your help

**Comment by vitalidze** [comment]
You are welcome.
