### ISSUE TITLE
gps watch integrated with traccar

### ISSUE THREAD

**Issue by t3mp30r3k** [vitalidze/traccar-web#578]
dear all .
has anyone, that already implemented with gps watch.. wich model gps watch support by traccar ?.. 
is this model support

**Comment by t3mp30r3k** [comment]
http://s.aliexpress.com/mQZVfAzu

**Comment by joepr** [comment]
The best option is to contact the manufacturer or search on google to verify what protocol it uses. Then  go to https://www.traccar.org/devices and search if that protocol is already integrated. If not then contact the traccar team and send them the info. I'm sure they will be happy to integrate it to the Database. 

PS. Nice finding that model looks very good.
