### ISSUE TITLE
install web UI 

### ISSUE THREAD

**Issue by mataier** [vitalidze/traccar-web#581]
Установил Web UI, не отображает местоположение устройства, переустанавливал на traccar 3.4; traccar 3.3; traccar 3.2; web war не хочет показывать местоположение.

**Comment by vitalidze** [comment]
Скорее всего ошибка в конфигурационном файле. Проверяйте все измененные запросы. Также я советую ставить на 3.2 чтобы избежать других проблем.

Если ошибку не видно - покажите содержимое `tracker-server.log` файла.

**Comment by mataier** [comment]
установка по схеме http://traccar.litvak.su/installation.html произведена, без web war сервер работает хорошо. 

``` xml
<entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>
    <entry key='web.type'>old</entry>
    <entry key='web.application'>/opt/traccar/traccar-web.war</entry>
 <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>
 <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://127.0.0.1:3306/TRACCARDB?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>

----------------------
     <entry key='database.loginUser'>
        SELECT * FROM "user"
        WHERE email = :email;
    </entry>

    <entry key='database.selectUser'>
        SELECT * FROM "user"
        WHERE id = :id;
    </entry>

    <entry key='database.selectUsersAll'>
        SELECT id, login AS name, email, readOnly AS readonly, admin FROM users;
    </entry>

    <entry key='database.insertUser'>
        INSERT INTO "user" (name, email, hashedPassword, salt, admin)
        VALUES (:name, :email, :hashedPassword, :salt, :admin);
    </entry>

<entry key='database.updateUser'>
        UPDATE "user" SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        language = :language,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom
        WHERE id = :id;
    </entry>

    <entry key='database.updateUserPassword'>
        UPDATE "user" SET hashedPassword = :hashedPassword, salt = :salt WHERE $
    </entry>

 <entry key='database.updateUserPassword'>
        UPDATE "user" SET hashedPassword = :hashedPassword, salt = :salt WHERE $
    </entry>

    <entry key='database.deleteUser'>
        DELETE FROM "user" WHERE id = :id;
    </entry>

    <entry key='database.getPermissionsAll'>
        SELECT u.id AS userId, d.id AS deviceId FROM users u, devices d WHERE u$
    </entry>

    <entry key='database.selectDevicesAll'> SELECT * FROM devices; </entry>
<entry key='database.selectDevices'>
        SELECT * FROM device d INNER JOIN user_device ud ON d.id = ud.deviceId $
    </entry>

    <entry key='database.insertDevice'>
        INSERT INTO device (name, uniqueId) VALUES (:name, :uniqueId);
    </entry>
 <entry key='database.updateDevice'>
        UPDATE device SET name = :name, uniqueId = :uniqueId WHERE id = :id;
    </entry>

    <entry key='database.deleteDevice'>
        DELETE FROM device WHERE id = :id;
    </entry>
<entry key='database.unlinkDevice'>
        DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM position WHERE deviceId = :deviceId AND fixTime BETWEEN :$
    </entry>

    <entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitu$
    </entry>
<entry key='database.selectLatestPositions'>
        SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceT$
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;
    </entry>
```

журнал wepper.log

```
NFO   | jvm 1    | 2016/03/25 08:30:49 |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/03/25 08:30:49 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/03/25 08:30:49 |   at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2016/03/25 08:30:49 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/03/25 08:30:49 |   ... 42 more
INFO   | jvm 1    | 2016/03/25 08:31:02 | Mar 25, 2016 8:31:02 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2016/03/25 08:31:02 | INFO: Register 'sam'
INFO   | jvm 1    | 2016/03/25 08:55:43 | Mar 25, 2016 8:55:43 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2016/03/25 08:55:43 | INFO: Login 'admin'
```

журнал сервера мониторинга.

```
2016-03-25 09:04:38  INFO: [7ABD0440] connected
2016-03-25 09:04:38 DEBUG: [7ABD0440: 5055 < 178.88.30.217] HEX: 474554202f3f69643d3636373739342674696d657374616d703d31343538383936363737266c61743d34332e3139383939343634333431333437266c6f6e3d37362e39313932313636383136333833332673706565643d302e302662656172696e673d3135332e3938343636343931363939323226616c7469747564653d3931362e3036333335373237363130393226626174743d31362e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342e322e323b2047542d5337353832204275696c642f4a44513339290d0a486f73743a2035322e32362e38392e35383a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2016-03-25 09:04:38 DEBUG: [7ABD0440: 5055 > 178.88.30.217] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-03-25 09:04:38  INFO: [7ABD0440] disconnected
2016-03-25 09:04:38  WARN: Incorrect string value: '\xD1\x83\xD0\xBB. ...' for column 'address' at row 1 - SQLException (... < QueryBuilder:428 < DataManager:345 < DefaultDataHandler:27 < ...)
2016-03-25 09:04:38  INFO: [7ABD0440] id: 1, time: 2016-03-25 09:04:37, lat: 43.19899, lon: 76.91922, speed: 0.0, course: 154.0
```

**Comment by mataier** [comment]
сервер вроде работает, устройство на сервер данные посылает, ошибок не дает. веб UI не показывает данные.,??

**Comment by vitalidze** [comment]
Вроде похоже на правильный конфиг. Я думаю проблема в кодировке сервера:

```
2016-03-25 09:04:38  WARN: Incorrect string value: '\xD1\x83\xD0\xBB. ...' for column 'address' at row 1 - SQLException (... < QueryBuilder:428 < DataManager:345 < DefaultDataHandler:27 < ...)
```

Попробуйте решение из #254

**Comment by mataier** [comment]
http://52.26.89.58:8082
admin
admin

**Comment by vitalidze** [comment]
Да, устройство посылает, сервер принимает, но не записывает их в базу. Я думаю в таблице `positions` вообще не будет записей.

**Comment by mataier** [comment]
спасибо попробую разобраться.

**Comment by mataier** [comment]
{"reason":"The device is not registered on the server","success":false}
??????????

**Comment by vitalidze** [comment]
Я так понимаю это про отправку команд на устройство. Это сообщение означает что в данный момент нет соединения с устройством.

**Comment by mataier** [comment]
пробовал менять кодировки &, &amp, UTF-8,  UTF8mb4, wepper.conf менять, как только что-то меняю сервер traccar не грузится.

**Comment by mataier** [comment]
может в интерфейсе какие то настройки нужны, когда заходишь админом в web UI?

**Comment by vitalidze** [comment]
Нет, никаких настроек не нужно. Попробуйте выключить reverse geocoding:

``` xml
 <entry key='geocoder.enable'>false</entry>
```

В том логе проблема в том, что сервер не может записать адрес в базу (наверное русские символы). Если выключить reverse geocoding то адреса не будет и позиция должна сохраниться в базу.

**Comment by mataier** [comment]
WOW, сработало. есть контакт. Большое спасибо.

**Comment by mataier** [comment]
значит надо базу данных переделать?

**Comment by vitalidze** [comment]
Похоже на то, кодировка должна быть везде UTF-8.

**Comment by mataier** [comment]
русских символы имеете ввиду название и пароли баз данных?

**Comment by vitalidze** [comment]
Я думаю русские символы получились в результате reverse geocoding (получения адреса по координатам).

**Comment by mataier** [comment]
Большое спасибо за помощь.

**Comment by mataier** [comment]
уронил старую и создал новую базу данных в utf8>CREATE DATABASE `my_db` CHARACTER SET utf8 COLLATE utf8_general_ci;  работает.

**Comment by mataier** [comment]
вопрос? можно ли поддержку казахского языка включить, что для этого можно сделать?

**Comment by vitalidze** [comment]
Для этого нужно перевести интерфейс. Лучший способ - это добавить перевод на сайте [transifex](https://www.transifex.com/traccar-web-ui-mod/traccar-web/). Потом я его включу в проект и он будет доступен для всех пользователей Traccar Web UI mod.

**Comment by mataier** [comment]
может помочь?

**Comment by vitalidze** [comment]
У меня нет ни времени ни возможности переводить на казахский язык. Так что если Вам это нужно - переводите, я постараюсь включить в следующую публичную версию.

**Comment by mataier** [comment]
ок.

**Comment by Sergio-tix** [comment]
У меня такая же проблема, но при настройке `<entry key='geocoder.enable'>false</entry>` работать не начинает. Объясните по русски, что и как надо делать? Устанавливаю в Ubuntu 14.04 traccar и mysql. Запускаю, всё работает. Устанавливаю WEB UI, всё запускается, но координаты не принимает. Сделал `<entry key='geocoder.enable'>false</entry>`  , не помогло. Установил phpmyadmin, посмотрел все БД и таблицы - они в `utf8_general_ci`. Если менять кодировку, то где и как это сделать в phpmyadmin? 
Если установить traccar, mysql, не запускать и не создавать БД, поставить и web ui а потом запустить, то не работает. Сначала нужно запустить traccar, а только потом остановить его и установить web ui, или как?

**Comment by vitalidze** [comment]
> Запускаю, всё работает. Устанавливаю WEB UI, всё запускается, но координаты не принимает. 

Нужно посмотреть в лог-файл tracker-server.log, чтобы понять причину.

> Если менять кодировку, то где и как это сделать в phpmyadmin? 

Я не знаю, попробуйте поискать в google какой запрос нужно выполнить для изменения кодировки таблицы в MySQL.

> Если установить traccar, mysql, не запускать и не создавать БД, поставить и web ui а потом запустить, то не работает. Сначала нужно запустить traccar, а только потом остановить его и установить web ui, или как?

Лучше всего сначала Web UI поставить, а потом запускать. Если сначала запустить traccar, то потом придется удалять все таблицы из базы, чтобы Web UI при старте смог создать правильные таблицы для себя.

**Comment by Sergio-tix** [comment]
Что означает:
 `WARN: Field 'deviceid' doesn't have a default value - SQLException (... < QueryBuilder:431 < DataManager:440 < DefaultDataHandler:27 < ...)`
И как от этого избавиться?

И не записываются координаты в БД, кусок лога:
`2016-04-29 15:51:20  INFO: [9B93CFDB] connected
2016-04-29 15:51:20 DEBUG: [9B93CFDB: 5055 < 172.17.0.1] HEX: 474554202f3f69643d3030312674696d657374616d703d31343631393334323830266c61743d35352e393038373038266c6f6e3d33372e3439373532362673706565643d302e302662656172696e673d302e3026616c7469747564653d3235302e3026626174743d39382e3020485454502f312e310a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420782e782e783b204d6f62696c6558204275696c642f4b4f54343948290a486f73743a207878782e7878782e7878782e7878783a353035350a436f6e6e656374696f6e3a204b6565702d416c6976650a4163636570742d456e636f64696e673a20677a69700a
2016-04-29 15:51:20 DEBUG: [9B93CFDB: 5055 > 172.17.0.1] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-04-29 15:51:20  INFO: [9B93CFDB] disconnected
2016-04-29 15:51:20  WARN: Field 'deviceid' doesn't have a default value - SQLException (... < QueryBuilder:431 < DataManager:440 < DefaultDataHandler:27 < ...)
2016-04-29 15:51:20  INFO: [9B93CFDB] id: 1, time: 2016-04-29 15:51:20, lat: 55.908708, lon: 37.497526, speed: 0.0, course: 0.0`
Некоторые данные поменял

**Comment by vitalidze** [comment]
Это означает что в Вашей базе неправильная структура таблицы `positions`. Скорее всего пришло из оригинальной версии traccar. Чтобы это исправить нужно удалить таблицу и перезапустить сервер с выключенной опцией `database.changelog`, закомментировать ее в конфигурационном файле (как сказано в инструкцияхhttp://traccar.litvak.su/installation.html):

``` xml
<!-- entry key='database.changelog'>./database/changelog-master.xml</entry -->
```

**Comment by mataier** [comment]
При создании базы данных Mysql для Traccar, кодировку поставьте utf8, тогда
геокодировку не нужно менять в конфигурационном файле: true на false.

28 апреля 2016 г., 20:52 пользователь Sergio-tix notifications@github.com
написал:

**Comment by Sergio-tix** [comment]
Да! Всем спасибо! С трудом, но удалось всё сделать. И вроде всё работает. Иногда только вылетает ошибка "Сбой удалённого вызова", во время залогинивания или какого-либо запроса. Приходится рестарт делать. И не понял как pushbullet настроить. Я получил Access Tokens, ввёл этот ключ в настройках, сделал тест, ответ "ok". В настройках учётной записи включил все уведомления. В pushbullet в настройках Connected Apps появился Pushbullet API Access. Но мне уведомления не приходят... Что не так?
P.S. Это мой, почти первый, опыт работы с линуксом. Устанавливал всё в докер на ubuntu под Synology/

**Comment by vitalidze** [comment]
> В pushbullet в настройках Connected Apps появился Pushbullet API Access. Но мне уведомления не приходят... Что не так?

Надо смотреть в wrapper.log. Там должны быть сообщение об отправке уведомлений.

**Comment by Sergio-tix** [comment]
Он каждую минуту пытается отправить мэйл. Хотя я его даже не настраивал, мне мэйл уведомления не нужны.

```
org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2016/05/03 05:30:06 | WARNING: User 'admin' has empty email field
INFO   | jvm 1    | 2016/05/03 05:31:06 | May 03, 2016 5:31:06 AM 
```

Про  Pushbullet в логах ничего нет. Появилось только когда попробовал "тест":

```
INFO   | jvm 1    | 2016/05/03 10:21:02 | INFO: {"active":true,"iden":"ujxyXXXXXX","created":1.4621755007715352e+09,"modified":1.4622132463091772e+09,"email":"sXXXX.XX@gmail.com","email_normalized":"sXXXXXX@gmail.com","name":"SXXXX XX","image_url":"https://static.pushbullet.com/missing-image/e85845-53","max_upload_size":26214400}
```

**Comment by vitalidze** [comment]
У Вас не заполнено поле email для пользователя admin, которому система пытается отправить уведомления. В качестве адреса получателя для pushbullet уведомлений используется email, также как и в случае с отправкой через электронную почту.

**Comment by Sergio-tix** [comment]
Удалось победить, уведомления приходят. Но не совсем. Настроил необходимые переменные. Жму тест и получаю:
`Потеряна связь с устройством 'Serega' в зоне '1km' в Tue May 03 14:32:52 MSK 2016`
Тестирую реально, и получаю от pushbullet:
`Потеряна связь с устройством 'Serega' в зоне 'N/A' в Tue May 03 14:35:32 MSK 2016`
В настройках геозоны включил "для всех устройств",  также поставил галочки на всех устройствах.
Строка вот так выглядит:
`Потеряна связь с устройством '${deviceName}' в зоне '${geoFenceName}' в ${positionTime}`
Почему может не цепляться тег ${geoFenceName} ?

**Comment by vitalidze** [comment]
Потому что событие потери связи не имеет ничего общего с геозонами. Их нельзя объединять. Для геозон сейчас есть только события входа\выхода.

**Comment by Sergio-tix** [comment]
Понятно теперь. Думал можно любые комбинации собирать. Спасибо!

**Comment by Sergio-tix** [comment]
Мне снова требуется помощь. Можете объяснить для чего нужно меню "Датчики" в настройках устройств? Я так понял, некий трекер может передавать множество информации, например traccar для андроида оптравляет:
`GET /?id=000001&timestamp=1462534888&lat=55.555555&lon=37.555555&speed=0.0&bearing=0.0&altitude=0.0&batt=100.0 HTTP/1.1`
И я в меню "Датчики" могу настроить запись некого параметра, например параметра `&batt`, или любого другого, который будет? Я попробовал в поле "Параметр" вставить значение `batt`, но оно в архиве не отображается. Также в Архиве есть множество полей: время, адрес, широта... заряд. Почему-то в поле "заряд" ничего не пишется, там пусто. Хотя в запросе параметр есть, и при наведении курсора на девайс уровень заряда отображается.
Поясните как пользоваться Датчиками, или где об этом почитать?

**Comment by vitalidze** [comment]
Для датчиков в данный момент можно настроить только отображение во всплывающем окне. В архиве они не отображаются, поле 'Заряд' не используется, нужно его будет удалить. Почитать про датчики можно здесь: http://traccar.litvak.su/features/sensors.html

**Comment by Sergio-tix** [comment]
О каких всплывающих окнах речь?

**Comment by vitalidze** [comment]
Оно появляется при наведении на маркер на карте и при наведении на строку в таблице с устройствами.

**Comment by AidakoMed** [comment]
Как вольты с дута преоброзовать в литры?
