### ISSUE TITLE
Three-part appliacation

### ISSUE THREAD

**Issue by WiliamM** [vitalidze/traccar-web#583]
Hi Litvak!
I have used your modified version of Traccar and it works perfectly, really like all of the features that you have added especially the geofence feature. 
I have decided to develop an android applications to use with the REST api. It works fine with the original traccar REST api but then I cant use the geofence feature. 
Orginal Traccar uses HTTP authorization headers and a build in CORS filter so it would be easy to implement in different three-part applications. 
I wounder if there is any way/solution to connect your REST api with three-part applications on our own servers ? 
I would really want to use your geofence feature in my application. Do you know any solution to the problem in addition to building an entirely new API?

**Comment by vitalidze** [comment]
> I wounder if there is any way/solution to connect your REST api with three-part applications on our own servers ? 

I think you can use current [REST API](http://traccar.litvak.su/features/rest-api.html) with any application.

As for API for geo-fences please read discussion here #512

**Comment by WiliamM** [comment]
Thanks for your answer!

But the REST API works even if the program is on a separate server, there will be no cross-domain problem?

Thanks for the geo-fence API information.

**Comment by vitalidze** [comment]
> But the REST API works even if the program is on a separate server, there will be no cross-domain problem?

Well, I guess it will not work in the web browser because currently API does not set an `Access-Control-Allow-Origin` header. However, it will work from any third party application, which does not check that header. Examples on the web site make requests with cURL without any issue.
