### ISSUE TITLE
Route Overlay

### ISSUE THREAD

**Issue by cwworth** [vitalidze/traccar-web#589]
Is there a way to create a temporary route overlay on the map from a GPX data import?

My requirement is that I use the server for locating mobile units who provide first aid cover for cyclists riding a prearranged route. What I would like to do is to load this route onto the map that can be seen by the event controllers account and other users accounts so I and they can see where on the route they are.

I tried to use the geofence function for this but could not figure out how to make it do what I wanted as the routes are mostly point to point and do not return to the start which appear to be a requirement of a 'fence'.

**Comment by vitalidze** [comment]
Currently there is no way to do it. I think the geo-fence of type named 'Line' is exactly what you want. It does not need to return to start, and from my vision it's main use case is to represent a route or part of a route. So you need to import your route from GPX and save it as a geo-fence, the GPX Parser code is here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/GPXParser.java

**Comment by cwworth** [comment]
Have tried using the geofence and whilst it could be used for what I want, I was hoping I could build it from and import of GPX data. However I don't know how to use the java code to do that. 
So I thought I would import the co-ordinates from a GPS track straight into the MySQL database, however unless I am reading the table incorrectly the sample geofence I made has the nodes stored as Lon Lat, Lon Lat and not Lat Lon, Lat Lon as I would expect, making it very time consuming to pre-process my track to swap the Lat and Lon over for each data point.

**Comment by vitalidze** [comment]
You are correct. Values are swapped and go as lonlat. It should not consume
much time especially if you parse GPX file before inserting values.

пятница, 1 апреля 2016 г. пользователь cwworth написал:

> Have tried using the geofence and whilst it could be used for what I want,
> I was hoping I could build it from and import of GPX data. However I don't
> know how to use the java code to do that.
> So I thought I would import the co-ordinates from a GPS track straight
> into the MySQL database, however unless I am reading the table incorrectly
> the sample geofence I made has the nodes stored as Lon Lat, Lon Lat and not
> Lat Lon, Lat Lon as I would expect, making it very time consuming to
> pre-process my track to swap the Lat and Lon over for each data point.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/589#issuecomment-204157141

## 

Kind regards, Vitaly Litvak

**Comment by joepr** [comment]
@cwworth traccar is a excellent option however I might have a better solution for you scenario. Send me a email    fncprlog @ gmail.com hope I can help you.
