### ISSUE TITLE
Issue with automatic login

### ISSUE THREAD

**Issue by bospre** [vitalidze/traccar-web#59]
Today I found another issue with automatic login.
Maybe this can easily be fixed.
I logged in with the link with the automatic login. Because I wanted to change settings I logged off and logged in with my own account (it is not the account with the automatic login).
When I finished I didn't logoff, instead I just closed the browser tab.
When I later opened the link with the automatic login, the login parameters where ignored. Traccar still showed me my account. I had explicitely to logoff and logon again.

I think traccar should check the login dates. If another account is active, this should be logged out.
If there is no new login data, traccar can show the "normal website".
Do you think this can be fixed?
Of course I can logout, as I am suposed to, but I think I am not the only one who is lazy.
And actually I can live with that, but it is a kind of security leak.
Sincerly
Boris

**Comment by antoniopaisfernandes** [comment]
Can't this be closed?
