### ISSUE TITLE
Mileage detail Report Generation 

### ISSUE THREAD

**Issue by kedarnathjimage** [vitalidze/traccar-web#590]
i used trarccar only inserting data into database. i develop front end with php and mysql. but it is difficult generate report. and  what is the difference between distance and total mileage? and how to calculate it.

**Comment by vitalidze** [comment]
On mileage detail report Distance column shows distance travelled for each day (a "daily distance"). "Total mileage" shows overall distance for the report period.

You can find code of report generator here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/reports/ReportMD.java Distance between two is calculated using this formula: http://www.movable-type.co.uk/scripts/latlong.html

**Comment by vitalidze** [comment]
Closed due to inactivity
