### ISSUE TITLE
Popup box configuration

### ISSUE THREAD

**Issue by pshome** [vitalidze/traccar-web#591]
Hi,

First: thanks a lot for your great application and all the effort you are putting into this!

Question: is it possible to reduce the content of the popup box that appears when i move the mouse over a tracked item. The box shows information that really is not needed on an operational system. All data between the speed and geofence info (Protocol, sat,mcc, mnc,lac , cid, index,ip) is of little interest on a system that is up and running properly, but makes the box unecessarily large.

Thanks

Peter

**Comment by vitalidze** [comment]
Thank you for the warm words about the app. I appreciate that.

You can hide unnecessary information with the [sensors](http://traccar.litvak.su/features/sensors.html) functionality (including 'Protocol').

**Comment by pshome** [comment]
Perfect, thanks for your quick reply.
Greetings
Peter

**Comment by pshome** [comment]
Well, it doesnt seem to work for the "Protocol" field, all other fields removed fine using the sensors table. Maybe i use the wrong syntax? I tried "protocol" and "Protocol".

Thanks

Peter

**Comment by vitalidze** [comment]
Yes, you are right. I have revised the code and it won't work for the 'protocol'. My bad.

**Comment by pshome** [comment]
No problem, i can live with that, with all the other lines gone its much better now.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
