### ISSUE TITLE
Load button missing in german version

### ISSUE THREAD

**Issue by pshome** [vitalidze/traccar-web#592]
Hello again

After switching to German language, the load button is missing in the Archive window. 
To load data, it is needed to click the ">>" button and select "Load". 
![no_load_btn](https://cloud.githubusercontent.com/assets/18210861/14206628/b92560a4-f814-11e5-9b46-e9968af62418.jpg)

i have the browser maximized on a 1366x768 Laptop screen. Same in Firefox and Opera,

Thanks & Cheers

Peter

**Comment by gsiotas** [comment]
Yeap the same happens in Greek language. You can resize the window in the horizontal axis to view the button.

**Comment by vitalidze** [comment]
This is a trade off for supporting many translations. Actually the `Load` button should be present in the popup menu opened by the button with `>>` sign.

**Comment by pshome** [comment]
Well, the window is already maximized, no way to extend it further. 
Where are are the translation strings located? Shortening the two labels to the left should make the button visible, correct?

**Comment by vitalidze** [comment]
Yes, that's right, if you shorten the strings they might fit in your resolution. German translation is here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/resources/org/traccar/web/client/i18n/Messages_de.properties You will need to rebuild the `traccar-web.war` after translation completed with these instructions: http://traccar.litvak.su/building.html (may require apache maven installed on your machine).

**Comment by mpele** [comment]
Also, if you do not use Snap to road and filtering you could hide those
checkboxes.

**Comment by pshome** [comment]
got my load button, thanks for your help! :+1: 
![load_btn](https://cloud.githubusercontent.com/assets/18210861/14216047/eb180e54-f846-11e5-89fa-e5ed2abfcc4a.jpg)
