### ISSUE TITLE
Erasing old data [Help Wanted]

### ISSUE THREAD

**Issue by hardjumper** [vitalidze/traccar-web#593]
Can someone please help me with erasing old data from mysql I have been recording data over 6 months and my server is full so I want to get rid of old data for the past 5 months..

**Comment by vitalidze** [comment]
Please look here #244

**Comment by hardjumper** [comment]
I tried to follow #244 but it did not help much.My real problem is that my system is extremely slow I though that by  erased some of the old data it might speed up but it doesnt.I have about 400 devices..To log in to the application  it takes close to 25 min.Any advice to make my application speed is welcomed.

**Comment by vitalidze** [comment]
I think this can be caused by the "Groups" function. I mentioned slowdown on the demo site as well. I will investigate it and get back once I have some update.

**Comment by hardjumper** [comment]
After removing the groups everything came back to normal.Thank you.

**Comment by vitalidze** [comment]
You are welcome. I plan to rewrite groups functionality in nearest future.
