### ISSUE TITLE
GL200 data being written to DB but not all displayed.

### ISSUE THREAD

**Issue by ko922** [vitalidze/traccar-web#594]
I just recently setup a GL200, I'm TCPDUMPing all traffic to 5004, seeing data coming in to include RESP entries, and i'm verifying they are being written into the MySQL DB however when logged into the web interface the tracker doesn't show updated data.  The battery level indicator is not displaying, the last update time is not correct, etc.  

There are sporadic updates that occur to the map for this tracker but with it sitting in one location and continuously getting GL200 updates it does not show the updates.

I'm also running an Android app which updates every 5 or 10 seconds and that does correctly display on the map.

Also - is it possible to use the "send commands" to a GL200?  If so, what has to be done to get that to work?

Thanks!!

**Comment by vitalidze** [comment]
> I just recently setup a GL200, I'm TCPDUMPing all traffic to 5004, seeing data coming in to include RESP entries, and i'm verifying they are being written into the MySQL DB however when logged into the web interface the tracker doesn't show updated data. The battery level indicator is not displaying, the last update time is not correct, etc.
> 
> There are sporadic updates that occur to the map for this tracker but with it sitting in one location and continuously getting GL200 updates it does not show the updates.

This sounds like an issue with your device, which sends positions in wrong order or sends some 'invalid' positions. I think you can set up some kind of filter for positions (see https://www.traccar.org/configuration-file/ options starting from `filter.`). Also it's worth to try to update your traccar backend to the latest version (3.4 at the moment of writing) if you hadn't yet done it.

> Also - is it possible to use the "send commands" to a GL200? If so, what has to be done to get that to work?

From the source code of backend I can see that it supports the following commands:
- positionSingle
- engineStop
- engineResume
- rebootDevice (not supported by the web UI mod yet)

You can use the 'Command' menu available in the latest version of the Traccar web UI mod: select your device, click on 'Command' button, select type of command and click 'Send'.

**Comment by ko922** [comment]
Yeah I'm running 3.4.  It is strange, looking at the positions table in the MySQL it shows valid lat/long for where the device is/was. Are you saying if it buffers positions and then sends real time positions before the buffered ones it can mess things up because they are 'out of order' ?

I just added  <entry key='filter.enable'>false</entry>
in the config XML, is that correct?

**Comment by ko922** [comment]
The GL200 is sending GTFRI messages, the lat/long is correct, the "other" shows {"mcc":310,"mnc":410,"lac":4301,"cid":30272,"battery":"98","ip":"107.77.xxx.xx"}, server time 2016-04-01 20:23:47, time 2016-04-01 20:23:47.  Is this a time mismatch issue that is preventing it from showing on traccar web?

It is also not displaying any of the battery info, etc that it has done at least once before.

**Comment by vitalidze** [comment]
> Yeah I'm running 3.4. It is strange, looking at the positions table in the MySQL it shows valid lat/long for where the device is/was. Are you saying if it buffers positions and then sends real time positions before the buffered ones it can mess things up because they are 'out of order' ?

Yes, that's right. Web UI just displays latest position received by the backend, nothing more.

> I just added false
> in the config XML, is that correct?

The `false` word without parameter name does not mean anything in scope of configuration file unless you provide the parameter name. What parameter have you changed?

> The GL200 is sending GTFRI messages, the lat/long is correct, the "other" shows {"mcc":310,"mnc":410,"lac":4301,"cid":30272,"battery":"98","ip":"107.77.xxx.xx"}, server time 2016-04-01 20:23:47, time 2016-04-01 20:23:47. Is this a time mismatch issue that is preventing it from showing on traccar web?

I don't know. Time should not be an issue if your positions are received sequentially. Anyway, in database table time is stored in unified format and probably in a different time zone. Most probably the one which you will see on the web UI will be different, because it shows it in a web browser's timezone (i.e. time zone of desktop PC). I suggest to verify that positions from your mobile phone have similar time.

> It is also not displaying any of the battery info, etc that it has done at least once before.

This means your devices does not send this information with every position. I have seen such behaviour before. Some devices send battery info periodically, say once per minute.

**Comment by ko922** [comment]
``` xml
 <entry key='filter.enable'>false</entry>
```

**Comment by ko922** [comment]
entry key='filter.enable' false /entry

the brackets are being treated as HTML I think on here so it screwed it up the first time.

**Comment by vitalidze** [comment]
Well, this means you have disabled filtering at all. I think you need to figure out the order of messages that is sent by your device. I think you can just take a look at the `tracker-server.log`. There will be decoded messages in order they are posted to database.
