### ISSUE TITLE
Delete records - shrink Database

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#595]
Hi!
I would like to shrink the database with this command:
 `DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);`
but I got this error:
`mysql> DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`gps31`.`events`, CONSTRAINT`events_fkey_position_id`FOREIGN KEY (`position_id`) REFERENCES`positions`(`id`))`
With the original Traccar Vers. it works fine. How to fix?

**Comment by vitalidze** [comment]
Please read answer to your old question here: #244

**Comment by connectnet** [comment]
Im sorry. Maybe Im getting old : -(

**Comment by vitalidze** [comment]
No problem, hope it will work for you ;)
