### ISSUE TITLE
API GeoFence

### ISSUE THREAD

**Issue by WiliamM** [vitalidze/traccar-web#596]
Hi, 
We are building a three-part application based on the RESTful API and we want to use the geofence functionality to draw the geofence on the map. The REST API call "getGeofences" only respond with the id, name and color of the geofence. Is there any way to get the coordinates of the geofence?

**Comment by vitalidze** [comment]
First of all please don't post similar questions multiple times. 

Please read answer here https://github.com/vitalidze/traccar-web/issues/583#issuecomment-202003557
