### ISSUE TITLE
Need the logics of idle / moving / online / offline

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#597]
Hi,

I see there are tags for devices 

Thats 

Idle
Moving
Online
Offline

Can you provide me logic how they are tagged in terms 

How much time if location doesnt come its tagged to the following status

**Comment by vitalidze** [comment]
From the [features list page](http://traccar.litvak.su/features/):

> - possibility to detect ‘offline’ devices - when signal hasn’t came for some time (set up in device settings). They will be shown on a map with a marker of different colour and there will be some sign in popup that they are actually offline.
> - new device status - idle. It is shown in popup and also there will be a time of idling. Each device got new setting ‘Idle when speed is <=’, which is zero by default. It may be changed to some reasonable value, which is then used to consider device idle (for example to handle ‘satelite drift compansation’).

Idling is now detected by speed and the time the speed is below a value from device profile (i.e. when speed is <= 3km/h for one minute, then device considered idle).

**Comment by abhishekricky** [comment]
what about offline and moving ?

**Comment by vitalidze** [comment]
It's the opposite status. If device is not offline, then it is online. If it is not idle, then it's moving.

**Comment by abhishekricky** [comment]
I need to understand how many seconds if no location comes to the system, it will mark offline to the user

Whats the timeout seconds

**Comment by vitalidze** [comment]
This is covered by 'timeout' setting in device profile. By default it is 300 seconds (5 minutes).

**Comment by abhishekricky** [comment]
Well One doubt when i click the dropdown to select offline devices 

![image](https://cloud.githubusercontent.com/assets/5213928/14249376/16a8b27e-fa97-11e5-8359-0811682a1682.png)

offline devices dont tick mark

**Comment by vitalidze** [comment]
Please read article about devices visibility carefully: http://traccar.litvak.su/features/visibility.html especially about how the states are combined when calculating device visibility flag
