### ISSUE TITLE
Web Dashboard Extremely Slow

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#598]
Hi,

I have added 13 users with devices. Now Dashboard is extremely slow 

Its takes alomost 30 minutes for user to show real time on the map

**Comment by vitalidze** [comment]
From my investigation this can be caused by the "Groups" functionality. Are you using groups?

**Comment by abhishekricky** [comment]
Nope I am not using Groups

**Comment by vitalidze** [comment]
Ok, I see. Can you provide some other details? Like when it started to run slow, maybe something was changed on your server. Are all users experience this slowness?

**Comment by abhishekricky** [comment]
Yes all users are experiencing slowness.

My Azure config is 1 core and 1GB ram. This started suddenly which i observer after all 13 devices starting throwing location to server

**Comment by vitalidze** [comment]
Try disabling event recording in global settings.

**Comment by abhishekricky** [comment]
What does event recording do ?

**Comment by abhishekricky** [comment]
Well disabled it same issue slowness is there

**Comment by vitalidze** [comment]
Well, I am out of ideas. You need to run some profiling tool. Also if you are using H2 database you should try switching to MySQL and verify that you are using InnoDB storage engine.

**Comment by mpele** [comment]
Are there any effects if you truncate table events?

**Comment by vitalidze** [comment]
Please check latest version.
