### ISSUE TITLE
Timezone issue 

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#599]
Hi,

Below is the screen shot 

![image](https://cloud.githubusercontent.com/assets/5213928/14278835/659d4a7e-fb47-11e5-9a01-b4c4bf5038f1.png)

Now problem is I have set my timezone thats Asia/Calcutta (GMT +5.30)

But in the pop up it always show with respect to GMT +5.30 timezone 

And even though I am online it never shows me online always offline

**Comment by vitalidze** [comment]
This means your device sends date/time with incorrect timezone.

**Comment by abhishekricky** [comment]
Its sending correct because at database end I can see its a proper unixtimestamp is stored

**Comment by vitalidze** [comment]
Your unix timestamp must be in UTC timezone, which has the time shift. I still insist that you have incorrect value in your database.

**Comment by abhishekricky** [comment]
Hey I checked, can you guide in positions table 

there are 2 columns "server time" and "time"

Now server time is stored in UTC rite ? and time in the timezone of settings ?

Well I also downloaded the newest traccar app. I am seeing for some values its sending to table position there is direct 1 day increment in time !!!

**Comment by vitalidze** [comment]
Time is always stored timezone independent, i.e. in UTC or something like this. In your tool that you use to query database you may see time from non UTC zone. For example, see MySQL documentation: https://dev.mysql.com/doc/refman/5.5/en/datetime.html

> Well I also downloaded the newest traccar app. I am seeing for some values its sending to table position there is direct 1 day increment in time !!!

This may be an issue with traccar application. You should look into `tracker-server.log` file to see what it actually sends and stores.

**Comment by abhishekricky** [comment]
Hey got last time the status online/offline is decided by position "time" field rite ?

**Comment by vitalidze** [comment]
Actually it looks into both fields - `time` and `serverTime`
