### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by aacable** [vitalidze/traccar-web#60]
I have few requests.

1- Status of device in infobox, like "In-Motion" or "Start" "Stop" (ref opengts)

2- Icon should have arrow so that we can get idea in which direction vehicle was moving. (as showed in opengts. example is attached)

![1](https://cloud.githubusercontent.com/assets/6860656/5640412/efd28388-9646-11e4-911f-6ca27f68cf9b.JPG)

3- Current location inquiry via sending sms to the mobile. as someone discussed here.
https://github.com/tananaev/traccar-client-android/issues/106

**Comment by Jeferex** [comment]
I wrote a piece of code for direction in https://github.com/tananaev/traccar-web/issues/112

For the arrow, one way to do it is to have all icons with direction arrows and then, with a simple condition, show the correct icon.

I have icons in my drive: https://drive.google.com/open?id=0BxkLrFGnkpHjcTVGN2VyaVptRTg&authuser=0

**Comment by gsiotas** [comment]
:+1:

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
