### ISSUE TITLE
Change the Online/Offline Logic a bit

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#600]
Hi,

In this screenshot 

![image](https://cloud.githubusercontent.com/assets/5213928/14279709/6ecff830-fb4c-11e5-985d-8f05c9785e97.png)

There are option of Idle/Moving/Online/Offline

I want a simple solution to change in the code if device is offline as per status it should get selected on clicking the offline checkbox 

and rest where offline status is not shown it should get ticked on online checkbox selection

**Comment by abhishekricky** [comment]
And I need the online/offline logic to be just based on servertime when the entry has come

**Comment by vitalidze** [comment]
You can get the desired behaviour if you set up check boxes correctly, like check 'Idle' and 'Moving', uncheck 'Online' and check 'Offline' - it will show you all 'Offline' devices. See official article for additional info: http://traccar.litvak.su/features/visibility.html

**Comment by abhishekricky** [comment]
Sorry bro it was question I just want to know the code where the device states can be edited

Because I need the online/offline condition just based on the servertime field of position

**Comment by vitalidze** [comment]
You can observe changes in this commit: https://github.com/vitalidze/traccar-web/commit/0400343be84e50aeae5d60b91ab5bc4d891c4033 Basically it should be enough to update `DeviceView`, `VisibilityController` and `MapController` classes.
