### ISSUE TITLE
Incorrect work of offline detector

### ISSUE THREAD

**Issue by vitalidze** [vitalidze/traccar-web#601]
The check against server time is incorrect:

``` java
                if (currentTime.getTime() - position.getTime().getTime() >= timeout
                        && (position.getServerTime() == null || position.getServerTime().getTime() >= timeout)) {
```

Also we should have similar check in UI to consider server time as well.

**Comment by abhishekricky** [comment]
Hey,

will correct syntax here would be this 

```
 if (currentTime.getTime() - position.getTime().getTime() >= timeout
   && (position.getServerTime() == null || (currentTime.getTime() - position.getServerTime().getTime()) >= timeout)) {
```

**Comment by vitalidze** [comment]
@abhishekricky yes, it should be like this. Will be fixed in next release.

**Comment by abhishekricky** [comment]
@vitalidze bro any plans to shift to some other platform. Because I am seeing slowly google GWT userbase has decreased and no recent update to the Google GWT framework ?

**Comment by vitalidze** [comment]
No, there are no plans to shift. Google GWT framework is still developed and there is a 2.8 beta. Also Sencha GXT 4.0 community edition was recently released: https://plus.google.com/+DavidMichaelChandler/posts/EozRLMpjvTy (framework used in Traccar Web)

**Comment by abhishekricky** [comment]
Hey,

I tried this code 

```
 if (currentTime.getTime() - position.getTime().getTime() >= timeout
   && (position.getServerTime() == null || (currentTime.getTime() - position.getServerTime().getTime()) >= timeout)) {

but its same what code you are planning to include here 
```

**Comment by vitalidze** [comment]
I don't understand your question. Are there any question?

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
