### ISSUE TITLE
WARN: Column "STATUS" not found

### ISSUE THREAD

**Issue by crarchile** [vitalidze/traccar-web#602]
Hi Guys:

I need some help.

I have a Traccar v3.4 server running with two tracker devices model GT06.

I am receiving the following error:

2016-04-06 00:50:38  WARN: Column "STATUS" not found; SQL statement:
UPDATE devices SET status = ?, lastUpdate = ? WHERE id = ?; [42122-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:253 < ConnectionManager:110 < ...)

Somebody knows how I can solve this error?

My two devices are showed on the map but the status inside popup info window is "inactive since 876d 21h"

Regards,

Carlos

**Comment by vitalidze** [comment]
> 2016-04-06 00:50:38 WARN: Column "STATUS" not found; SQL statement:
> UPDATE devices SET status = ?, lastUpdate = ? WHERE id = ?; [42122-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:253 < ConnectionManager:110 < ...)
> 
> Somebody knows how I can solve this error?

Please read #439 

> My two devices are showed on the map but the status inside popup info window is "inactive since 876d 21h"

It's not related anyhow with the above issue. Are you sure your device has sent some data? Maybe there is incorrect date/time setting on your device?

**Comment by crarchile** [comment]
yes, mi two devices are sending data.

Both trackers are the same model and maker, one, the first, works ok, the second shows a wrong date and last time.

**Comment by vitalidze** [comment]
This sounds like an issue with your second device. You should read the manual or consult with device manufacturer to figure out how to configure date and time there.

**Comment by crarchile** [comment]
I have configured the second tracker the same way that first tracker but the second tracker shows a wrong date (inactive  876d 23h  since 2013-11-10 21:00:00).

**Comment by crarchile** [comment]
@vitalidze thanks for your comments..

**Comment by peptoni** [comment]
I'm getting this error:

WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:255 < ConnectionManager:110 < ...)

Seems to show on every device I have, every couple of seconds or so... Devices look good on map...

Is it related...?

**Comment by vitalidze** [comment]
@peptoni Yes, it is related, please read #439

**Comment by peptoni** [comment]
Sorry, I did not find the #439 issue...  Have to search more next time.
