### ISSUE TITLE
GWT Compile fails with out of memory

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#603]
Hi,

I have 8GB RAM pc. Now from past 2 days I am not able to compile. Its giving me out of memory 

Its compile till permutation 160 then it shows the Build Time and then suddenly out of memory error comes 

Not sure how to fix and speed up compile as it takes more than 1 hour to compile

**Comment by vitalidze** [comment]
The issue with big memory consumption and long compilation time was related with the number of locales (languages) supported and that GWT builds a javascript file for every language. Couple of months ago I have redesigned that so right now language strings are loaded dynamically at runtime. Now compilation on my machine takes about 5 minutes.

So, you should update your project with the latest source code from github (`dev` branch). This should help to resolve your issues.

**Comment by abhishekricky** [comment]
Well in the existing code I did many changes. If i update it will do in corruption mode . Is it possible you can point me some commits which I can incorporate in the code to have faster compilations

**Comment by vitalidze** [comment]
I think it's time to merge your changes with the upstream (i.e. `dev` branch). Merging just these commits will make syncing more complicated for sure.

There are many commits, starting from `Dec 12, 2015` ending at `Dec 18, 2015`

**Comment by abhishekricky** [comment]
Well I agree its better to merge. Now one thing the v3.3 release on Feb 10 contains this real time compilation improvement right ?

**Comment by vitalidze** [comment]
All releases of the Traccar Web UI mod made after 18th december should contain these changes. The number of permutations must be 6 (six) after these changes.

**Comment by abhishekricky** [comment]
Hey 

I cloned new project. But now I run in eclipse I am getting this error java.lang.OutOfMemoryError: GC overhead limit exceeded
