### ISSUE TITLE
error RPC

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#604]
Hi,
The application freezes and when I open the log appears this warning ... What could be the problem?

![rmpc](https://cloud.githubusercontent.com/assets/16056476/14309059/42f00ffa-fbda-11e5-9982-bfdabfd592ee.png)

Thanks

**Comment by vitalidze** [comment]
Looks like your server goes down for some reason. You need to connect there and check `wrapper.log` file for error messages.

**Comment by ghost** [comment]
Thanks
I have the need for an application, can I have your email so I'll explain in private...

**Comment by ghost** [comment]
application > APP

**Comment by vitalidze** [comment]
You can find my email in github profile.
