### ISSUE TITLE
Zoom to devices

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#607]
Would someone else find interesting a button in the top bar to "zoom to devices"?

When clicked, the view would zoom as close as possible to include all visible devices.

Also, could be an option in users default zoom.

**Comment by vitalidze** [comment]
Next release will contain a function called 'Automatic zoom to selected/followed device', which level could be set up in user's preferences. This will adjust zoom level when you click on any device or such device is being followed. I don't know whether it intersects with the function you describe.

**Comment by peptoni** [comment]
My suggestion affects ALL devices on view, so the view would zoom to a level where all device would fit in the map window.
It's like a "zoom as much as possible on the map, while keeping all devices visible on the map"

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
