### ISSUE TITLE
Visual problem with columns on devices grid

### ISSUE THREAD

**Issue by peptoni** [vitalidze/traccar-web#608]
On Safari 9.1 running on OS X 10.11.4 there is a visual problem with columns on devices list. All columns are visible, no matter what the visibility setting is.  It does not happen with Firefox, on the same computer.  Latest traccar-web and Traccar 3.4. I attach screenshots:

Group column visible
![screen shot 2016-04-06 at 18 24 02](https://cloud.githubusercontent.com/assets/11501146/14324493/4cf77b78-fc25-11e5-95a4-4922613d24f9.png)

Group column hidden
![screen shot 2016-04-06 at 18 23 37](https://cloud.githubusercontent.com/assets/11501146/14324499/50fd7ace-fc25-11e5-8e87-5cc11c0d25e0.png)

Only Name column visible
![screen shot 2016-04-06 at 18 32 33](https://cloud.githubusercontent.com/assets/11501146/14324667/fd214b32-fc25-11e5-8844-80fac1cfdad7.png)

**Comment by vitalidze** [comment]
Well, I doubt anything can be done about this. It is the Sencha GXT framework which is used to draw the grid.

**Comment by vitalidze** [comment]
I have rewritten the devices grid to a different component. Please let me know if the issue still exists.
