### ISSUE TITLE
Need to convert servertime popup to one set in user preference

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#609]
Hi,

in position popup, I want to show the server time but its in UTC I want to show in users timezone 

Tried via datetimeformat used this string to convert "yyyy-MM-dd HH:mm:ss GMT+0530" but its not working

**Comment by vitalidze** [comment]
Have you tried googling for it? See [this stackoverflow thread](http://stackoverflow.com/questions/2189148/how-do-i-get-gwt-datetimeformat-to-display-using-the-server-timezone-rather-tha) for example.

Anyway, the approach is wrong. You work around the issue with either your server or your device. This means once you fix it (or stub it) on the client side, it will definitely break when you get a device of different type. When you store values correctly they will be displayed correctly in the web browser's timezone without any change.
