### ISSUE TITLE
Best way to show a logo image in login window

### ISSUE THREAD

**Issue by Jeferex** [vitalidze/traccar-web#61]
I want to show a logo in login window but I wonder what is the best way to do it. I searched in GXT demos and I don't find anything.

**Comment by vitalidze** [comment]
The easiest way is to add a `ContentPanel` to the layout and set up custom style. This style must be defined in `traccar.html` (either in `<head>` or put `css` somewhere in `webapp` folder).

In `LoginDialog.ui.xml`:

````xml
<!-- ... -->
    <gxt:Window ui:field="window" pixelSize="300, 130" modal="true" closable="false" headingText="{i18n.authentication}" focusWidget="{login}">
    <container:VerticalLayoutContainer>
      <container:child layoutData="{verticalLayoutData}">
        <g:ContentPanel bodyStyleName="logo"/>
      </container:child>
      <container:child layoutData="{verticalLayoutData}">
        <form:FieldLabel text="{i18n.user}" labelWidth="110">
          <form:widget>
            <form:TextField ui:field="login" />
          </form:widget>
        </form:FieldLabel>
      </container:child>
<!-- ... -->
````

In `traccar.html`:

````html
<!-- ... -->
<head>
<!-- ... -->
    <style type="text/css">
        .logo {
            background: url('logo.jpg') no-repeat;
        }
    </style>
<!-- ... -->
</head>
<!-- ... -->
````

**Comment by Jeferex** [comment]
It didn't work. The ContentPanel is a widget from GXT not G and it is shown inside the Login dialog but doesn't show the image. I think this is because the login Dialog is a window. I think it should be a panel or something else. What do you think of redesign the login page? A vertical panel should work. Also, include the logo and title as a setting (for the administrator) would be great.

What do you think?

**Comment by vitalidze** [comment]
It's working for me with `CenterLayoutContainer`:

````xml
<!-- ... -->
      <container:child layoutData="{verticalLayoutData}">
        <container:CenterLayoutContainer styleName="logo" pixelSize="280, 30"/>
      </container:child>
<!-- ... -->
````

You should specify size in pixels and style.

Regarding redesigning, you may submit a separate feature request about it. If someone besides you would need it, I will do it. Right now I doubt that it's valuable to spend time on it.

**Comment by Jeferex** [comment]
It worked, thanks! But I had to change a couple of things. This is what I did.

- As you said, I had to add `    pixelSize` in `    <container:child>`
- I had to increase `    window pixelSize` so the logo can fit.
- I added `    resizable = "false" draggable="false"` to Window attributes so It didn't look weird with user interactions.

I think the last modification shoud added to dev branch.

Thanks

**Comment by vitalidze** [comment]
You are welcome. Can you please file a pull request with these changes? (resizable and draggable set to false for login dialog)
