### ISSUE TITLE
error 404 send command /traccar/rest/sendCommand

### ISSUE THREAD

**Issue by jesusto** [vitalidze/traccar-web#612]
hi, excuse my English, I'm using google translator

I have a problem with the path /traccar/rest/sendCommand
says 404 error

**Comment by vitalidze** [comment]
I can see two possible issues with such error message:

1) there are no such method exposed in the API. This can be caused by an outdated version of Traccar Web UI Mod

2) you are using wrong parameters format in your API call. See #571 for an example

**Comment by jesusto** [comment]
```
$.ajax({
    type: "POST",
    url: "http://149.56.3.246:8082/traccar/rest/sendCommand",
    dataType: "text",
    data: JSON.stringify({"deviceId": 1, "type": "engineStop"}),
    success: function (res) { console.log("done");  console.log(res); }
});
```

**Comment by vitalidze** [comment]
Please read #571 carefully. Arguments of each method are always an array. You put an object there. Try the following:

``` javascript
$.ajax({
type: "POST",
url: "http://149.56.3.246:8082/traccar/rest/sendCommand",
dataType: "text",
data: JSON.stringify([{"deviceId": 1, "type": "engineStop"}]),
success: function (res) { console.log("done"); console.log(res); }
});
```

**Comment by jesusto** [comment]
thank you

**Comment by beryindo** [comment]
Dear jesusto can u share ur project ?? u coding on php ?

**Comment by jesusto** [comment]
above for stop engine

<?php
$lines = file('c:/wamp/cookie.txt');
$trows = '';
foreach($lines as $line) {
// we only care for non-comment, non-blank lines
  if($line[0] != '#' && substr_count($line, "\t") == 6) {
    // get tokens in an array
    $tokens = explode("\t", $line);
    $cookie= rtrim($tokens[5]) . "=" . rtrim($tokens[6]);  // JSESSIONID from cookie.txt
    // trim the tokens
    $tokens = array_map('trim', $tokens);

```
// let's convert the expiration to something readable
//$tokens[4] = date('Y-m-d h:i:s', $tokens[4]);

// we can do different things with the tokens, here we build a table row
 $trows .= '<tr><td>' . implode('</td><td>', $tokens) . '</td></tr>' .PHP_EOL;
```

  }
}

$url='http://149.0.0.1/traccar/rest/sendCommand';  // your ip address
$data='[{"deviceId": 3, "type": "engineStop"}]';
$headers = array("Expect:");

//send request
$curl=curl_init($url);

//save in separate variable instead of printing in browser
curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
curl_setopt($curl, CURLOPT_POST,1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
curl_setopt($curl, CURLOPT_COOKIESESSION, TRUE);
curl_setopt($curl, CURLOPT_COOKIE, $cookie);
curl_setopt($curl, CURLOPT_HEADER, 0);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_VERBOSE, TRUE);
//get response in a variable to decode json
$response=curl_exec($curl);
echo $response;
$decoded = json_decode($response);
if (isset($decoded->response->status) && $decoded->response->status ==
'ERROR') {
    die('error occured: ' . $decoded->response->errormessage);
}
var_dump($decoded);

?>

above login

```
<?php
$url='http://149.0.0.1/traccar/rest/login';  // your ip
$data='["admin","admin"]';
$cookie='';
$headers = array("Expect:");

//send request
$curl=curl_init($url);

//save in separate variable instead of printing in browser
curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
curl_setopt($curl, CURLOPT_POST,1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
curl_setopt($curl, CURLOPT_COOKIESESSION, TRUE);
curl_setopt($curl, CURLOPT_COOKIEJAR, 'c:/wamp/cookie.txt');
curl_setopt($curl, CURLOPT_COOKIE, $cookie);
curl_setopt($curl, CURLOPT_HEADER, 0);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
//get response in a variable to decode json
$response=curl_exec($curl);
//echo $response;
if ($response === false) {
    $info = curl_getinfo($curl);
    curl_close($curl);
    die('error occured during curl exec. Additional info: ' .
var_export($info));
}
curl_close($curl);
?>
```

I hope you work, for me works better in ajax

**Comment by beryindo** [comment]
waw, long code :dancers: any short code ? :+1:

**Comment by jesusto** [comment]
javascript

above login

var objJSON={"user":"admin", "password": "admin"};




$.ajax({
type: "POST",
url: "http://149.0.0.1/traccar/rest/login",
headers: {'Content-Type': 'application/x-www-form-urlencoded'},
dataType: "json",
crossDomain: true,
xhrFields: { withCredentials: true },
data:
"["+JSON.stringify(objJSON.user)+","+JSON.stringify(objJSON.password)+"]",
success: function (res, status, xhr) { console.log("done");
console.log(res); console.log(xhr); }
});




2016-04-26 20:36 GMT-04:30 beryindo <notifications@github.com>:

**Comment by jesusto** [comment]
in javascript
Login

```
var objJSON={"user":"admin", "password": "admin"};

$.ajax({
    type: "POST",
    url: "http://149.0.0.1/traccar/rest/login",
    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
    dataType: "json",
    crossDomain: true,
    xhrFields: { withCredentials: true },
    data: "["+JSON.stringify(objJSON.user)+","+JSON.stringify(objJSON.password)+"]",
    success: function (res, status, xhr) { console.log("done");  console.log(res); console.log(xhr);  }
});
```

**Comment by jesusto** [comment]
engineStop

```
$.ajax({
        type: "POST",
        url: "http://149.0.0.1/traccar/rest/sendCommand",
        dataType: "json",
                xhrFields: { withCredentials: true },
                crossDomain: true,


        data: JSON.stringify([{"deviceId": 3, "type": "engineStop"}]),
        success: function (res) { console.log("done"); console.log(res);}
});
```

I hope you work,

**Comment by beryindo** [comment]
php work, tks
