### ISSUE TITLE
CW 801B

### ISSUE THREAD

**Issue by lilicsubatman** [vitalidze/traccar-web#616]
my device [CW 801B](http://www.winvike.com/Products_details.asp?id=353) with port 5040 in traccar... the device can be send interval signal to the server... but server can't display potition on the map... please help me...

**Comment by vitalidze** [comment]
It sounds like your device either does not send data to server or server cannot receive it for some reason.  This project is not related with processing data from devices, it more like a display for that data. Please ask your question here: https://github.com/tananaev/traccar/issues and most probably you will need to provide contents of `tracker-server.log` file from the start. Also it's worth to check contents of this article: https://www.traccar.org/troubleshooting/
