### ISSUE TITLE
GWT Developer Plugin

### ISSUE THREAD

**Issue by ndebug1** [vitalidze/traccar-web#617]
Hi  Litvak,
Hope this finds you well.
GWT Developer Plugin is not working in NetBeans 8.1, how I can use Super Dev Mode?
Many thanks

**Comment by vitalidze** [comment]
You should just check the 'SuperDevMode' box when you run project from NetBeans.

Or if you meant that latest version of plugin is for NetBeans 8.0 then as far as I know you can install it over 8.1 too, so it should be compatible.

**Comment by ndebug1** [comment]
Hi Litvak,
Well, I'm new to gwt. I don't know how to start the Super Dev mode. I can't find the "SuperDevMode" check box either. And run command is currently disabled. Do I have to install it first?
I would need detailed explanation step by step, please.
Thank you

**Comment by vitalidze** [comment]
Here are the instructions: http://traccar.litvak.su/ide/netbeans.html

**Comment by ndebug1** [comment]
I followed this instructions earlier, when i hit Launch Default Browser, it gives an error that GWT is not more compatible with recent browsers, I have tried all the browsers available..

**Comment by vitalidze** [comment]
That's correct, old plugin is not supported anymore by modern browsers (it used `DevMode`). You need to use SuperDevMode, which does not require any browser plugin. Are you sure you are running it from the `dev` branch?

I don't have NetBeans installed to check how to run it. From my memory there were no difficulties, meaning it either run in SuperDevMode automatically or there were some check box in run configuration.
