### ISSUE TITLE
Need to display string and variable in log

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#620]
Hi,

in the current codebase. I want to display certain string and variable value in log.

I tried many ways to display buts its not displaying in the log When i push to product. Please can you help me out

**Comment by vitalidze** [comment]
You can inject `Logger` instance into your code, then just call it's methods. See [NotificationServiceImpl](https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/NotificationServiceImpl.java) for example.

**Comment by abhishekricky** [comment]
I tried same code but its nt reflecting in logs. I am tryign to print value to log in file Event impementation file

**Comment by vitalidze** [comment]
What is this file?

**Comment by abhishekricky** [comment]
src/main/java/org/traccar/web/server/model/EventServiceImpl.java

this is the file EventServiceImpl.java

**Comment by vitalidze** [comment]
You need to put there:

``` java
@Inject
Logger logger;
```

Then when you call methods from that logger they should put some data to the log, which appears in `wrapper.log` file.
