### ISSUE TITLE
Need to change latest position algorithm 

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#621]
Hi,

Currently it stores the latestposition based on any recent position that is recieved. But I want to change it to this logic

Where it will check whether current reported position time is less than current latest position then its lastposition should not change

Where would I have to edit to have this logic done ?

**Comment by vitalidze** [comment]
Best place to change it is on the backend side. I think it is already changed: https://github.com/tananaev/traccar/blob/master/src/org/traccar/DefaultDataHandler.java#L29 All versions of backend released after `September 23 2015` should include it (3.2, 3.3, 3.4).

**Comment by abhishekricky** [comment]
the code reference is in traccar code wht abt this current  codebase of yrs?

**Comment by vitalidze** [comment]
As I said it is in "backend" project.

**Comment by abhishekricky** [comment]
oh k i would need to build traccar project rite ? Can you guide how to then configure with your project

**Comment by vitalidze** [comment]
Well, you can just use a pre-built version downloaded from https://www.traccar.org/download/

Usually you just install the Traccar Web UI mod over the traccar installation.

**Comment by abhishekricky** [comment]
Hey,

I got how to do it , well compiled and it gave tracker-server.jar , which i replaced in the /opt/traccar folder

But Still I am not able to achieve what I want. I wanted simple logic to change that suppose servertime of last position and servertime of current position is less than timeout even though the actual time difference of last and current position is greater than timeout . It should stamp tag as online not offline as its current scenario

**Comment by vitalidze** [comment]
In the first message of this thread you wanted to update latest position with the new one only when it's time is greater than the time of current latest position. The code from backend does exactly that.
