### ISSUE TITLE
own icons

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#622]
Hello,

I've a picture 256/256 but when I add it, there is only a part of it that is diplay !!

![traccar_icone](https://cloud.githubusercontent.com/assets/15246747/14478160/cef932d6-015e-11e6-81d9-b60807a3f6e4.jpg)

**Comment by vitalidze** [comment]
It should be fine on map. In this list probably it will need to be shrinked. Will try to update it in the next release.

**Comment by ghost** [comment]
I confirm, the bug is only inside the pool of icons; it display well on the map, but 256:256 is realy too big, so I reduce to 76/56 that seems good.
The last problem is how to remove the black around my icon, I use "pinta editor" and just have the icon with 'nothing' around, but, there is still a black around !!!!
![transparent](https://cloud.githubusercontent.com/assets/15246747/14487864/c3e30442-01b0-11e6-89f8-e1266886638d.jpg)

I've found, must save icon as   .png  and not  jpg.

**Comment by vitalidze** [comment]
Your icon must have transparent background. JPEG does not support transparency. Thus you need to have it either in GIF or in PNG format.

**Comment by MarceloMJM** [comment]
Hello everyone,
Or use PNG image in sizes 32x32 and 64x64, if they can provide interest.
![ambulancia 32x32](https://cloud.githubusercontent.com/assets/9204676/14501990/7c79fbbe-017f-11e6-9c72-c4c721c0ce99.png)
![ambulancia 64x64](https://cloud.githubusercontent.com/assets/9204676/14501992/7f49fe0c-017f-11e6-8411-8d718c065477.png)

**Comment by MarceloMJM** [comment]
sorry my english bad ... I have several picture to share.

**Comment by vitalidze** [comment]
I have tried lightweight solution with the `background-size` [CSS3 attribute](http://stackoverflow.com/questions/9262861/css-background-image-to-fit-width-height-should-auto-scale-in-proportion), but unfortunately it scales small images as well. So, since big images is a rare case, I am closing this issue.
