### ISSUE TITLE
How to calculate the geofence area and bring in the report?

### ISSUE THREAD

**Issue by dvlas** [vitalidze/traccar-web#623]
Good day!
How can I calculate the geofence area and display it in a report?
I unpacked project from the git, but did not find the report editor.
Help please how can I implement this?
Thank you very much!

**Comment by vitalidze** [comment]
> How can I calculate the geofence area and display it in a report?

I think you can calculate area using geometrical formulas. For circle and line I think it can be quite simple. For polygons it can be complicated, use google (for example http://www.wikihow.com/Calculate-the-Area-of-a-Polygon). Each geofence is represented as set of points.

> I unpacked project from the git, but did not find the report editor.

All code of reports is located here https://github.com/vitalidze/traccar-web/tree/dev/src/main/java/org/traccar/web/server/reports

**Comment by vitalidze** [comment]
You can also find useful discussion from here #550

**Comment by dvlas** [comment]
Thank you very much.
