### ISSUE TITLE
login without authenticaton problem

### ISSUE THREAD

**Issue by Johntaa** [vitalidze/traccar-web#624]
Just installed a new fresh tarccar on a server  ,then install the web-ui ,  now when I enter 3 to 4 spaces in the name and some spaces in the password, then press Register,  I'll  login directly to the system . is this a bug or there are some configuration that I need to do.
Note : the account button well be disabled after login by this way

**Comment by vitalidze** [comment]
I think you are registering new user this way. When you click 'register' and user account is not yet taken then system registers new user and logs you in.

**Comment by Johntaa** [comment]
that's right but how to prevent it from registering empty values

**Comment by vitalidze** [comment]
You cannot prevent it without changing code. Space is a valid character in user name.

**Comment by Johntaa** [comment]
you mean there is no input validation available in traccar, and must be added by developers

**Comment by vitalidze** [comment]
That's correct.

**Comment by Johntaa** [comment]
thanks

**Comment by vitalidze** [comment]
You are welcome. I don't see big issue here. If you want to restrict your users you can disable registration and just create users by yourself in Settings >> Users menu.
