### ISSUE TITLE
Update of Online/Offline Tag

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#626]
Hi,

I am opening new issue to better explain what feature I am trying to achieve from code

Currently, suppose there is no data connection then traccar app stores the data locally and sends them when it connects to the internet

And suppose a past value comes where time is offcourse small then the latest position. It does update in the latestpositionid but at the same time I want to flag the status it online by using the formulae

currentservertime-lastservertime <=timeout --> then status must be tagged as online and if 

currentservertime-lastservertime >=timeout --> then status must be tagged as offline 

For this I changed in the src/main/java/org/traccar/web/server/model/EventServiceImpl.java but it dint work . In the same file I was trying to print value to log which I used according to issue #620 but it was nt displaying in logs also

**Comment by abhishekricky** [comment]
@vitalidze  Please can you help me out. Would like to understand and work on it

**Comment by vitalidze** [comment]
Looks like you have all the necessary information. All you need to do is just write code and then debug it until it works like you desired. Maybe it's worth to write some unit tests. For logging you can try use plain `System.out.prinltn` instructions.
