### ISSUE TITLE
traccer-web 

### ISSUE THREAD

**Issue by RAJENDRA2151** [vitalidze/traccar-web#627]
Sir ,I currently working in ur traccer project ,so I want to change that project UI .So how i can change that UI Part And from where? guide me sir

**Comment by vitalidze** [comment]
I think you should start from reading about [GXT appearances](https://docs.sencha.com/gxt-guides/3/concepts/appearance/Appearance_3.html) and [GXT themes](https://docs.sencha.com/gxt-guides/3/ui/theme/Themes.html). Then just set up project and try to develop your own theme.
