### ISSUE TITLE
Issue with server db.

### ISSUE THREAD

**Issue by peterghobrial** [vitalidze/traccar-web#628]
I installed traccar 3.4 and make modifications with conf file and removed the db, restarted traccar service. and i get this warn in the server log:

2016-04-15 16:24:37  WARN: Column "STATUS" not found; SQL statement:
UPDATE devices SET status = ?, lastUpdate = ? WHERE id = ?; [42122-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:253 < ConnectionManager:110 < ...)

attached conf file.

[traccar.txt](https://github.com/vitalidze/traccar-web/files/221163/traccar.txt)

**Comment by vitalidze** [comment]
Please read #439
