### ISSUE TITLE
Communication Failure 

### ISSUE THREAD

**Issue by RAJENDRA2151** [vitalidze/traccar-web#629]
When Database.mv size exceed more than 20 GB  then system give Communication failure ,But Traccer server  is in Running State but login screen not appear instead of login Screen show Communication Failure Screen .so help me to solve this issue

**Comment by vitalidze** [comment]
I think you should not use default H2 database engine for such amount of data. You should switch to MySQL. 

To investigate the issue I think you should look into `wrapper.log` file.
