### ISSUE TITLE
Direction of vehicle

### ISSUE THREAD

**Issue by RAJENDRA2151** [vitalidze/traccar-web#630]
i Want to change direction or head of vehicle  when vehicle goes opposite direction ......Current System not provide this feature so help me

**Comment by vitalidze** [comment]
You should update the `MapPositionRenderer` class for that purpose.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
