### ISSUE TITLE
because I stopped working time ?

### ISSUE THREAD

**Issue by zonavip** [vitalidze/traccar-web#631]
A consultation in reports does not work me time stopped.

as it calculated ?

as I can solve it?

I 'm using a GPS GT06 ,
the state of ignition is in the other column

from now thanks

**Comment by vitalidze** [comment]
I doubt I understand your question. The 'Idle' or 'Stopped' state is now calculated by speed and not by 'ignition' state.

**Comment by zonavip** [comment]
Because I have always 0 ?

it is not calculating in reports

**Comment by vitalidze** [comment]
If you have speed value as zero then on reports it will show such device as idle or stopped.

**Comment by zonavip** [comment]
Excellent!
and I found the problem ...

In the vehicle issue had > = 1

the last query, it does not work " adjust road tour "

thanks

**Comment by vitalidze** [comment]
I don't understand you.

**Comment by zonavip** [comment]
attached a picture with error
`<img src="http://s24.postimg.org/h478k3mf8/ajuste_recorrido.jpg" alt="spdfail" style="max-width:100%;">`

**Comment by zonavip** [comment]
[http://s24.postimg.org/h478k3mf8/ajuste_recorrido.jpg](url)

**Comment by zonavip** [comment]
[http://postimg.org/image/lq3csg7y9/](url)

**Comment by zonavip** [comment]
[http://postimg.org/image/lq3csg7y9/](http://postimg.org/image/lq3csg7y9/)

**Comment by vitalidze** [comment]
This is a known issue and has nothing to do with Traccar Web UI Mod. There is a limitation on the number of points in a query to a third party provider, which provides the "snapped" track. This limitation is 100 points per query, so if your archived track has more than 100 points then "snap to roads" functionality won't work for you.

**Comment by zonavip** [comment]
no other provider to have another alternative?

**Comment by zonavip** [comment]
thanks

**Comment by vitalidze** [comment]
I don't know. You can host your own instance of the same provider. However, you will need to update provider URL in code because right now it is hard coded to use Project OSRM's demo server.

**Comment by zonavip** [comment]
ok thanks
