### ISSUE TITLE
Howto modify  'inscription' button

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#632]
Hello,

Because i don't use this button as "inscription" possibility; is it possible to
- rename it as "website"
- and make a link to my website if it's click ?

Please, how to do that.

Thanks.

**Comment by vitalidze** [comment]
If you are talking about "Register" button it is possible only by updating source code and building project.

**Comment by beryindo** [comment]
how to remove register button in login page ?

**Comment by vitalidze** [comment]
You need to update the `LoginDialog` class.

**Comment by beryindo** [comment]
what the code must be removed or modified?
