### ISSUE TITLE
Take 2 to 3 min to display vehicles on map after login  

### ISSUE THREAD

**Issue by digitaltrackit** [vitalidze/traccar-web#635]
Hello Sir 
   I added 30 vehicles on portal successfully but now  whenever we login it take 2 to 3 min. or some time more then that to appear vehicles on  map Please help me to sort out this problem.
Thanks 
Best Regards

**Comment by vitalidze** [comment]
Display time may depend on:

1) number of positions you have in your database. How many positions do you have?

2) device groups function. I know that right now it works quite slow, but for 30 vehicles it should be fine. Do you use groups?

**Comment by digitaltrackit** [comment]
number of positions 30 , Yes There is 2 groups.

**Comment by vitalidze** [comment]
I was asking about how many points are stored in your database. If there are 30 points (positions), then it probably means that you have one position per device. It should work lightning fast in this case. So, how many overall points/positions do you have stored for all these devices?

Also, do you use H2 database (default) or switched to MySQL?

**Comment by digitaltrackit** [comment]
yes there are 30 points and we switched to MySQL Database .

**Comment by vitalidze** [comment]
Then I have no idea what happens for you if you have only 30 points in history of your database. You can try running some profiling tool to see what's happening (like Flight Recorder from Java Development Kit).

**Comment by digitaltrackit** [comment]
what do u mean 30 points ? 30 points means devices right ? That we added ?

**Comment by vitalidze** [comment]
Each device has multiple positions (i.e. it's track, or archive). I am talking about total number of positions for all devices. They are stored in `positions` table in your database.

**Comment by digitaltrackit** [comment]
ok got it . its 24

**Comment by digitaltrackit** [comment]
hello sir 
i was wrong its not 24 or 30 points in positions its 5353937 points total . Please help me to sort out this problem . 
Thanks 
Best Regards

**Comment by vitalidze** [comment]
You can try tuning your MySQL (innodb storage, query cache, etc.). Alternatively you can just delete old positions.

**Comment by gsiotas** [comment]
I have 20 devices and around 3.500.000 points in digitalocean.com server (the lowest one) and traccar-web runs smoothly

**Comment by digitaltrackit** [comment]
is there any way to solve  this problem ?

**Comment by gsiotas** [comment]
Maybe it a problem with the host computer? What kind of system are you running traccar on? Can you see the processes? Maybe something is CPU intensive.

**Comment by digitaltrackit** [comment]
i m using  godaddy VPS  with xeon 2.4 ghz with 4 GB Ram and 160 GB HDD

**Comment by digitaltrackit** [comment]
is this VPS configuration is not enough  ?

**Comment by gsiotas** [comment]
More than enough. Can you see the processes?

**Comment by digitaltrackit** [comment]
its intel xeon 2.4 Ghz

**Comment by vitalidze** [comment]
I think the issue can be with HDD, which is probably slower than Digital Ocean's SSD drive. That's why I suggest to either rune MySQL to force it keeping more data in memory (innodb_buffer_pool_size, query_cache, etc.) and reduce the number of positions.

**Comment by digitaltrackit** [comment]
Device sending data in every after 3 sec.

**Comment by gsiotas** [comment]
Processes I mean the programs that are running in the server. Are you using Windows or Linux? Do you use is it exclusively for traccar or for other uses as well? Also the 3 sec interval update is too much. For me after tests I use 30-35sec interval.

**Comment by digitaltrackit** [comment]
its windows server 2008.  yes its only use for traccar.

**Comment by gsiotas** [comment]
As Vitaly suggested try deleting some points. For example I would backup positions table and then delete all positions, to see if the problem exists. If the problem doesn't exist after this then it's not database problem

**Comment by digitaltrackit** [comment]
ok let me try

**Comment by digitaltrackit** [comment]
shall i change to  digitalocean.com to fix this problem

**Comment by gsiotas** [comment]
I don't think is necessary the server from digitalocean isn't as good as the one you currently have. Try the solution I mentioned.

**Comment by digitaltrackit** [comment]
i m using VPS is need cloud SSD ?

**Comment by digitaltrackit** [comment]
on VPS have  HDD

**Comment by gsiotas** [comment]
With SSD will be better

**Comment by digitaltrackit** [comment]
1st i want to say thank a lot both of u for u r fast reply :) 
we r planing to add 200 devices on traccar what u think is there any problem will create with number of that much devices

**Comment by gsiotas** [comment]
Yes if you have a problem with 30 devices then definitely you will have a problem with 200 devices :P Have you tried linux instead of Windows? Also the 5sec interval I think is an overkill.

**Comment by digitaltrackit** [comment]
no i did not try with linux . how much interval should be keep for device ? i want to tell u that this problem did not come with traccar 3.4 or 3.3 V.  when i shift this on new web ui  after add .war file i face this problem .

**Comment by gsiotas** [comment]
I use 30-35sec interval, for the devices. If this happens only with traccar-web you should stick to traccar 3.4, then.

**Comment by digitaltrackit** [comment]
but in 3.4 don't have marker and geo fences services that i need thats is why i shift with traccar-war :(

**Comment by vitalidze** [comment]
I am aware of some slowness with large number of positions, which I can reproduce on the demo server. There are issues both with groups and with the database size. I will try to work it out when I have time.

**Comment by digitaltrackit** [comment]
Thanks sir i really appreciate u r help

**Comment by digitaltrackit** [comment]
i will wait for u r update sir 
Thanks lot ones again

**Comment by vitalidze** [comment]
I don't think it will happen soon. Sure, you can wait. But meanwhile it's worth to try optimizing your MySQL settings.

**Comment by digitaltrackit** [comment]
ok I will try that .

**Comment by vitalidze** [comment]
Please try latest version. It should perform better.
