### ISSUE TITLE
Https:// error 503

### ISSUE THREAD

**Issue by gonenmustafa** [vitalidze/traccar-web#636]
When I try to open the demo server than this is what I get.
http error: 503
Problem accessing /. Reason
Service unavailable

**Comment by gsiotas** [comment]
I don't think traccar or traccar-web supports https? Does http works?

**Comment by vitalidze** [comment]
It ran out of disk space. I have cleaned it up. Now it is fine. Thank you for reporting.

@gsiotas yeah, demo server works over HTTPS behind the nginx reverse proxy.
