### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by gonenmustafa** [vitalidze/traccar-web#637]
Now I am getting this. When I try to open demo server.

**Comment by vitalidze** [comment]
Looks like it is running out of resources of that Digital Ocean instance :) I have enabled swap on the machine, let's see how it goes.

**Comment by vitalidze** [comment]
Thank you.

**Comment by vitalidze** [comment]
I think it is fine now, adding 'swap' fixed the issue. Thanks for noting.

**Comment by gonenmustafa** [comment]
Yes ty very much
