### ISSUE TITLE
Timestamp (summer time)

### ISSUE THREAD

**Issue by Fleetracking** [vitalidze/traccar-web#640]
Hi
Please refer to my issue posted at traccar projet forum:
https://www.traccar.org/forums/topic/server-time-device-time-difference/#post-5675
BR

**Comment by vitalidze** [comment]
Anton posted the correct answer. Traccar stores data in time-zone independent format. Then it is just displayed in the web browser's timezone on the web UI. So probably your device sends incorrect data, which is then stored in database.
