### ISSUE TITLE
report is not working

### ISSUE THREAD

**Issue by kedarnathjimage** [vitalidze/traccar-web#644]
When trying generate report it would not show any data.
do not show any error in logs. i have attached screen shot of drives and stops report
![123](https://cloud.githubusercontent.com/assets/16332684/14810125/de273334-0bae-11e6-9160-14063d76e4b5.png)

**Comment by vitalidze** [comment]
Do you have any archived data for this period for any of these devices? Maybe everything is just filtered out, or don't exist.

**Comment by kedarnathjimage** [comment]
i have almost one month of data still it not working

when install traccar at the begining it reports are working properly. then after two weeks it stopped working

**Comment by vitalidze** [comment]
Do you see tracks on map for those data?

**Comment by vitalidze** [comment]
Closed due to inactivity.
