### ISSUE TITLE
Languange Indonesia

### ISSUE THREAD

**Issue by beryindo** [vitalidze/traccar-web#645]
I am succes change lang to Indonesia. but I don't know, how to add Indonesia, in login page. Any one help me ?

![screenshot_1193](https://cloud.githubusercontent.com/assets/11897545/14814529/e39c6f56-0bd0-11e6-8611-68172e335d63.png)

**Comment by vitalidze** [comment]
You need to update couple of files in the project, see this commit for example: https://github.com/vitalidze/traccar-web/commit/37595bd89bab2b443633ce62b746287bfd6bf9d1

Then build it by following official instructions: http://traccar.litvak.su/building.html (may require maven installation).

**Comment by beryindo** [comment]
I been edit I18N.gwt.xml
![screenshot_1195](https://cloud.githubusercontent.com/assets/11897545/14814900/875f1ed0-0bd2-11e6-8f90-55b5b33941a3.png)

![screenshot_1194](https://cloud.githubusercontent.com/assets/11897545/14814901/8beeadb2-0bd2-11e6-9707-d3484e574b0d.png)
but not show indonsia in login page

**Comment by vitalidze** [comment]
As I said you need to edit it in source code, then rebuild the `traccar-web.war` file by following above instructions.

**Comment by beryindo** [comment]
yes I try again to edit, I am ekstrak traccar-web.war and edit, and compres to zip agan traccar-web.zip and rename traccar-web.war

**Comment by vitalidze** [comment]
Again, you need to build using these instructions: http://traccar.litvak.su/building.html

**Comment by beryindo** [comment]
owh ok, and where output ?

**Comment by vitalidze** [comment]
Article clearly states where will be the output.

**Comment by beryindo** [comment]
failed build
![screenshot_1199](https://cloud.githubusercontent.com/assets/11897545/14817006/5c704530-0bde-11e6-8229-904302f05406.png)

**Comment by beryindo** [comment]
not found .war file in folder target

![screenshot_1205](https://cloud.githubusercontent.com/assets/11897545/14820699/ead8ae80-0bf1-11e6-9d95-b6e4c98acb38.png)
![screenshot_1206](https://cloud.githubusercontent.com/assets/11897545/14820758/2f4c1e1c-0bf2-11e6-92c3-d3f212d08284.png)

**Comment by vitalidze** [comment]
Your build has not completed. Most probably your machine ran out of memory and kernel killed the process.

**Comment by beryindo** [comment]
omg.....
![screenshot_1211](https://cloud.githubusercontent.com/assets/11897545/14826835/ed5a76bc-0c09-11e6-8a4f-1594f2aa263e.png)

success, thaks very much vitalidze

**Comment by vitalidze** [comment]
This is a normal behaviour for the compilation process. It compiles using all cores as much as possible to speed up.

P.S. it would be good if you can share your translation. You can do it on transifex web site.

**Comment by beryindo** [comment]
ok, tks very much

**Comment by beryindo** [comment]
Done. Plase add stop and parking vitalidze. tks
![screenshot_1224](https://cloud.githubusercontent.com/assets/11897545/14870746/7b227bdc-0d06-11e6-8d45-fc6718573d1a.png)

**Comment by vitalidze** [comment]
Thank you. I will include it in next public release.

Icons for stopped and parking are in plans.

**Comment by vitalidze** [comment]
Included in latest release, written [news](http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
