### ISSUE TITLE
geo fence 

### ISSUE THREAD

**Issue by cesarruben** [vitalidze/traccar-web#646]
hello my question is why a geo fence created administrator account can be viewed and modified by anyone other user accounts.

**Comment by vitalidze** [comment]
Only users, that were created by that administrator will have access to that geo-fence. You can read about access to geo-fences here: http://traccar.litvak.su/features/geofences.html (see `Sharing geo-fence` paragraph)

**Comment by cesarruben** [comment]
Thank you.
