### ISSUE TITLE
[Question] Loading popup at archive menu.

### ISSUE THREAD

**Issue by gsiotas** [vitalidze/traccar-web#648]
Hi! I tried the new version and when selecting load in the archive menu I get this popup. I get this maybe because I am using Greek language and there in transifex there was not the relevant translation. 
![loading-icon](https://cloud.githubusercontent.com/assets/10040858/14867946/d0aa9a90-0cd3-11e6-8ce0-1023f763d3d1.png)

PS.> I got the same weird @@@@ in other places in the menu as well, most probably due to missing translation. I logged into transifex and I completed the Greek translation.

**Comment by vitalidze** [comment]
This is not related with missing translation. If some string is not translated it will just fall back to the english translation.

The reason for this is some cached scripts/JSON in your web browser. I have already faced this when traccar-web was behind nginx reverse proxy. Try to clean up browser cache/cookies as said here: http://superuser.com/questions/548096/how-can-i-clear-cookies-for-a-single-site

**Comment by gsiotas** [comment]
Yes you are right thank you!
