### ISSUE TITLE
share remove register button

### ISSUE THREAD

**Issue by beryindo** [vitalidze/traccar-web#649]
replace :
`LoginDialog.java` and `LoginDialog.ui.xml`
download from here
http://gpsindo.web.id/traccar/
and rebuild traccar-web.war

![screenshot_1225](https://cloud.githubusercontent.com/assets/11897545/14871626/429d5f54-0d0e-11e6-9c87-1bac3a85cb01.png)

**Comment by vitalidze** [comment]
Thank you for sharing. However, it's better to share changesets (or step-by-step approach) and not the whole files because they will be changed in time, and simple replacing will most probably break the system.

**Comment by beryindo** [comment]
Ok vitalidze
Delete code in file `LoginDialog.java`
![screenshot_1229](https://cloud.githubusercontent.com/assets/11897545/14879019/fc1f6de0-0d50-11e6-906d-419458f0d7b1.png)

```
@UiField
TextButton registerButton;
```

![screenshot_1230](https://cloud.githubusercontent.com/assets/11897545/14879055/2bd92756-0d51-11e6-9c0c-e9ee81ea5883.png)

```
if (ApplicationContext.getInstance().getApplicationSettings().getRegistrationEnabled()) {
registerButton.enable();
}
```

![screenshot_1231](https://cloud.githubusercontent.com/assets/11897545/14879080/44b30350-0d51-11e6-891a-36897155c159.png)

```
@UiHandler("registerButton")
public void onRegisterClicked(SelectEvent event) {
loginHandler.onRegister(login.getText(), password.getText());
}
```

Delete code in file `LoginDialog.ui.xml`
![screenshot_1233](https://cloud.githubusercontent.com/assets/11897545/14879110/773be22e-0d51-11e6-940f-3330ae93ed1c.png)

```
<gxt:button>
<button:TextButton ui:field="registerButton" text="{i18n.register}" enabled="false" />
</gxt:button>
```

**Comment by beryindo** [comment]
can u help me vitalidze. how to show button for engine stop and engine resume in mode mobile ?

**Comment by vitalidze** [comment]
Thank you. I will think about opening new section on the web site. There is already a thread here discussing changing of the login screen background.

**Comment by vitalidze** [comment]
> can u help me vitalidze. how to show button for engine stop and engine resume in mode mobile ?

You need to update [index.html](https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/index.html) for the view and [traccar-mobile.js](https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/traccar-mobile.js) for the code. Just call an [REST API](http://traccar.litvak.su/features/rest-api.html) method.

**Comment by beryindo** [comment]
can u helpe me for code :D, I don't know languange html and js :D

**Comment by vitalidze** [comment]
Well, I guess you can start learning from reading the [Framework7 documentation](http://framework7.io/get-started/)

**Comment by beryindo** [comment]
hmmmm hard code

**Comment by wolfbgn** [comment]
About REGISTER button.
Is this modification of files permanent or it is some how connected with the function of open and close registrations?
If it is permanent, is it possible to make it in some future releases connected with the check mark for the registrations ( now the button turns just gray - not disappear ).

**Comment by beryindo** [comment]
Permanent, if u need not permanent just uncheck Registrasion : 
![screenshot_1268](https://cloud.githubusercontent.com/assets/11897545/14930895/82372a3a-0e91-11e6-8a06-503a380cb1f7.png)

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2016/05/21/Quick-reports,-device-context-menu.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
