### ISSUE TITLE
3.5 Traccar error server

### ISSUE THREAD

**Issue by dsolissilva** [vitalidze/traccar-web#651]
I have the following problem. If cooperation could help me please . thank you very much.

> 2016-04-29 16:48:03  INFO: Operating system name: Windows Server 2012 R2 version: 6.3 architecture: amd64
> 2016-04-29 16:48:03  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
> 2016-04-29 16:48:03  INFO: Memory limit heap: 455mb non-heap: 130mb
> 2016-04-29 16:48:03  INFO: Character encoding: UTF-8 charset: UTF-8
> 2016-04-29 16:48:03  INFO: Version: 3.5-SNAPSHOT
> **2016-04-29 16:48:04  WARN: Table "SERVER" not found; SQL statement:
> SELECT \* FROM server; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:456 < PermissionsManager:74 < ...)**
> 2016-04-29 16:48:05  INFO: Starting server...

**Comment by vitalidze** [comment]
You can safely ignore this warning.

**Comment by dsolissilva** [comment]
Thanks vitalidze
