### ISSUE TITLE
version 3.5 does not display the address

### ISSUE THREAD

**Issue by jovicassia** [vitalidze/traccar-web#652]
Congratulations for implementation of the web interface, very complete and intuitive

I installed a new version of TRACCAR (3.5)

Using the standard GUI everything works well, but when I use your version the address field is saved as NULL

In the latest version of TRACCAR (Version: 3.5-SNAPSHOT) Tananev made many changes in the database, including several tables were eliminated

Any suggestions of what might be happening?

Also I have a warnig in the log file

2016-04-29 14:01:00  WARN: Unknown column 'status' in 'field list'

**Comment by vitalidze** [comment]
> Using the standard GUI everything works well, but when I use your version the address field is saved as NULL

This sounds like an issue with reverse geocoding. It's not about display, but the server just does not write any value in that column You should look into `tracker-server.log` file for error messages right after receiving positions. Most probably it has nothing to do with the Web UI Mod. This article may be helpful too: https://www.traccar.org/reverse-geocoding/

> 2016-04-29 14:01:00 WARN: Unknown column 'status' in 'field list'

You can safely ignore it. Moreover, in latest released version (a week ago), I have added necessary columns, so it should not appear anymore (see #439).

**Comment by jovicassia** [comment]
Thanks for the quick response

Better explaining the problem, I installed the Version: 3.5-SNAPSHOT 

This version has only 4 or 5 database tables. ???

I tested sending data and it works, even shows the address perfectly

When I make changes to the file "traccar.xml" and installs the new interface address field does not write more in the database, returns NULL

In the log of the system has no error

2016-04-29 14:15:33  INFO: [1DC67BA8] connected
2016-04-29 14:15:33 DEBUG: [1DC67BA8: 5055 < 192.168.2.1] HEX: 474554202f3f69643d3830393034302674696d657374616d703d31343631393439363838266c6$
2016-04-29 14:15:33 DEBUG: [1DC67BA8: 5055 > 192.168.2.1] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-04-29 14:15:33  INFO: [1DC67BA8] disconnected
2016-04-29 14:15:33  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:357 < C$
2016-04-29 14:15:33  INFO: [1DC67BA8] id: 1, time: 2016-04-29 14:08:08, lat: -24.10654, lon: -46.64445, speed: 0.0, course: 0.0
2016-04-29 14:16:33  INFO: [43537B3A] connected
2016-04-29 14:16:33 DEBUG: [43537B3A: 5055 < 192.168.2.1] HEX: 474554202f3f69643d3830393034302674696d657374616d703d31343631393439373438266c6$
2016-04-29 14:16:33 DEBUG: [43537B3A: 5055 > 192.168.2.1] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-04-29 14:16:33  INFO: [43537B3A] disconnected
2016-04-29 14:16:33  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:357 < C$
2016-04-29 14:16:33  INFO: [43537B3A] id: 1, time: 2016-04-29 14:09:08, lat: -24.10654, lon: -46.64445, speed: 0.0, course: 0.0
2016-04-29 14:17:33  INFO: [FA9B1239] connected
2016-04-29 14:17:33 DEBUG: [FA9B1239: 5055 < 192.168.2.1] HEX: 474554202f3f69643d3830393034302674696d657374616d703d31343631393439383038266c6$
2016-04-29 14:17:33 DEBUG: [FA9B1239: 5055 > 192.168.2.1] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-04-29 14:17:33  INFO: [FA9B1239] disconnected
2016-04-29 14:17:33  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:357 < C$
2016-04-29 14:17:33  INFO: [FA9B1239] id: 1, time: 2016-04-29 14:10:08, lat: -24.10654, lon: -46.64445, speed: 0.0, course: 0.0
2016-04-29 14:18:34  INFO: [BEE37B13] connected
2016-04-29 14:18:34 DEBUG: [BEE37B13: 5055 < 192.168.2.1] HEX: 474554202f3f69643d3830393034302674696d657374616d703d31343631393439383638266c6$
2016-04-29 14:18:34 DEBUG: [BEE37B13: 5055 > 192.168.2.1] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-04-29 14:18:34  INFO: [BEE37B13] disconnected
2016-04-29 14:18:34  WARN: Unknown column 'status' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:431 < DataManager:357 < C$
2016-04-29 14:18:34  INFO: [BEE37B13] id: 1, time: 2016-04-29 14:11:08, lat: -24.10654, lon: -46.64445, speed: 0.0, course: 0.0

**Comment by jovicassia** [comment]
Updated to latest version of "traccar-web.war"

In the error log:

Table 'tracking.server intelli' it does not exist

**Comment by vitalidze** [comment]
> This version has only 4 or 5 database tables. ???

It has more than 10 tables. I have no idea what could be the issue, there are no error in log you have provided. All I can recommend is to double check all entries in configuration file, maybe you have deleted the reverse geocoding settings.

> Table 'tracking.server intelli' it does not exist

It is safe to ignore it.

**Comment by jovicassia** [comment]
**Default tables in version 3.5**

mysql> show tables;
+---------------------------+
| Tables_in_intellitracking |
+---------------------------+
| DATABASECHANGELOG         |
| DATABASECHANGELOGLOCK     |
| devices                   |
| groups                    |
| positions                 |
| server                    |
| user_device               |
| user_group                |
| users                     |
+---------------------------+
9 rows in set (0.00 sec)

**tables after running your version**
mysql> show tables;
+---------------------------+
| Tables_in_intellitracking |
+---------------------------+
| application_settings      |
| device_icons              |
| devices                   |
| devices_geofences         |
| events                    |
| geofences                 |
| groups                    |
| groups_users              |
| maintenances              |
| notification_settings     |
| notification_templates    |
| pictures                  |
| positions                 |
| reports                   |
| reports_devices           |
| reports_geofences         |
| reports_users             |
| sensors                   |
| ui_state                  |
| user_settings             |
| users                     |
| users_devices             |
| users_geofences           |
| users_notifications       |
+---------------------------+
24 rows in set (0.00 sec)

**Comment by jovicassia** [comment]
Using default interface
![image](https://cloud.githubusercontent.com/assets/18741425/14924463/1bab7abe-0e19-11e6-879a-6fa80830702d.png)

**Comment by vitalidze** [comment]
Have you deleted database (or all tables from database) before installing the web UI mod? Currently there is no way to safely upgrade existing tables.

**Comment by jovicassia** [comment]
Yes, I drop de database (mysql)

**Comment by jovicassia** [comment]
![image](https://cloud.githubusercontent.com/assets/18741425/14926332/177be7f4-0e22-11e6-9b2c-2eabe86b6cac.png)

**Comment by jovicassia** [comment]
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

```
<entry key='web.enable'>true</entry>
<entry key='web.port'>8082</entry>
<entry key='web.path'>/opt/traccar/web</entry>
<entry key='web.type'>old</entry>
<entry key='web.application'>/opt/traccar/traccar-web.war</entry>

<!-- Geocoder options -->

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>opencage</entry>
<entry key='geocoder.url'>http://api.opencagedata.com/geocode/v1</entry>
<entry key='geocoder.key'>mykey</entry>

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>

<entry key='logger.enable'>true</entry>
<entry key='logger.level'>all</entry>
<entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

<!-- DATABASE CONFIG -->

<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/intellitracking?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>MYUSER</entry>
<entry key='database.password'>MYPASSWORD</entry>

<entry key='database.selectServers'>
    SELECT * FROM server;
</entry>

<entry key='database.updateServer'>
    UPDATE server SET
    registration = :registration,
    readonly = :readonly,
    map = :map,
    bingKey = :bingKey,
    mapUrl = :mapUrl,
    distanceUnit = :distanceUnit,
    speedUnit = :speedUnit,
    latitude = :latitude,
    longitude = :longitude,
    zoom = :zoom,
    twelveHourFormat = :twelveHourFormat
    WHERE id = :id;
</entry>

<entry key='database.loginUser'>
    SELECT * FROM users
    WHERE email = :email;
</entry>

<entry key='database.selectUser'>
    SELECT * FROM users
    WHERE id = :id;
</entry>

<entry key='database.selectUsersAll'>
SELECT id, login AS name, email, readOnly AS readonly, admin FROM users;
</entry>

<entry key='database.insertUser'>
    INSERT INTO users (name, email, hashedPassword, salt, admin, map, distanceUnit, speedUnit, latitude, longitude, zoom, twelveHourFormat)
    VALUES (:name, :email, :hashedPassword, :salt, :admin, :map, :distanceUnit, :speedUnit, :latitude, :longitude, :zoom, :twelveHourFormat);
</entry>

<entry key='database.selectDevicePermissions'>
    SELECT u.id AS userId, d.id AS deviceId FROM users u, devices d WHERE u.admin=1
    UNION
    SELECT ud.users_id AS userId, ud.devices_id AS deviceId FROM users_devices ud
    INNER JOIN users u ON ud.users_id=u.id
    WHERE u.admin=0 AND u.readOnly=0
</entry>

<entry key='database.updateUser'>
    UPDATE users SET
    name = :name,
    email = :email,
    admin = :admin,
    map = :map,
    distanceUnit = :distanceUnit,
    speedUnit = :speedUnit,
    latitude = :latitude,
    longitude = :longitude,
    zoom = :zoom,
    twelveHourFormat = :twelveHourFormat
    WHERE id = :id;
</entry>

<entry key='database.updateUserPassword'>
    UPDATE users SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
</entry>

<entry key='database.deleteUser'>
    DELETE FROM users WHERE id = :id;
</entry>

<entry key='database.selectDevicePermissions'>
    SELECT userId, deviceId FROM user_device;
</entry>

<entry key='database.selectGroupPermissions'>
    SELECT userId, groupId FROM user_group;
</entry>

<entry key='database.selectDevicesAll'>
    SELECT * FROM devices;
</entry>

<entry key='database.insertDevice'>
    INSERT INTO devices (name, uniqueId, groupId) VALUES (:name, :uniqueId, :groupId);
</entry>

<entry key='database.updateDevice'>
    UPDATE devices SET name = :name, uniqueId = :uniqueId, groupId = :groupId WHERE id = :id;
</entry>

<entry key='database.updateDeviceStatus'>
    UPDATE devices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id;
</entry>

<entry key='database.deleteDevice'>
    DELETE FROM devices WHERE id = :id;
</entry>

<entry key='database.unlinkDevice'>
    DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
</entry>

<entry key='database.selectGroupsAll'>
    SELECT * FROM groups;
</entry>

<entry key='database.insertGroup'>
    INSERT INTO groups (name) VALUES (:name);
</entry>

<entry key='database.updateGroup'>
    UPDATE groups SET name = :name, groupId = :groupId WHERE id = :id;
</entry>

<entry key='database.deleteGroup'>
    DELETE FROM groups WHERE id = :id;
</entry>

<entry key='database.linkGroup'>
    INSERT INTO user_group (userId, groupId) VALUES (:userId, :groupId);
</entry>

<entry key='database.unlinkGroup'>
    DELETE FROM user_group WHERE userId = :userId AND groupId = :groupId;
</entry>

<entry key='database.selectPositions'>
    SELECT * FROM positions WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime;
</entry>

<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
VALUES (:deviceId, :protocol, :now, :deviceTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
</entry>

<entry key='database.selectLatestPositions'>
    SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime, 
    valid, latitude, longitude, altitude, speed, course, address, other AS attributes 
    FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);    
</entry>

<entry key='database.updateLatestPosition'>
UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;    
</entry>

<!-- PROTOCOL CONFIG -->

<entry key='gps103.port'>5001</entry>
<entry key='tk103.port'>5002</entry>
<entry key='gl100.port'>5003</entry>
<entry key='gl200.port'>5004</entry>
<entry key='t55.port'>5005</entry>
<entry key='xexun.port'>5006</entry>
<entry key='xexun.extended'>false</entry>
<entry key='totem.port'>5007</entry>
<entry key='enfora.port'>5008</entry>
<entry key='meiligao.port'>5009</entry>
<entry key='trv.port'>5010</entry>
<entry key='suntech.port'>5011</entry>
<entry key='progress.port'>5012</entry>
<entry key='h02.port'>5013</entry>
<entry key='jt600.port'>5014</entry>
<entry key='huabao.port'>5015</entry>
<entry key='v680.port'>5016</entry>
<entry key='pt502.port'>5017</entry>
<entry key='tr20.port'>5018</entry>
<entry key='navis.port'>5019</entry>
<entry key='meitrack.port'>5020</entry>
<entry key='skypatrol.port'>5021</entry>
<entry key='gt02.port'>5022</entry>
<entry key='gt06.port'>5023</entry>
<entry key='megastek.port'>5024</entry>
<entry key='navigil.port'>5025</entry>
<entry key='gpsgate.port'>5026</entry>
<entry key='teltonika.port'>5027</entry>
<entry key='mta6.port'>5028</entry>
<entry key='tzone.port'>5029</entry>
<entry key='tlt2h.port'>5030</entry>
<entry key='taip.port'>5031</entry>
<entry key='wondex.port'>5032</entry>
<entry key='cellocator.port'>5033</entry>
<entry key='galileo.port'>5034</entry>
<entry key='ywt.port'>5035</entry>
<entry key='tk102.port'>5036</entry>
<entry key='intellitrac.port'>5037</entry>
<entry key='gpsmta.port'>5038</entry>
<entry key='wialon.port'>5039</entry>
<entry key='carscop.port'>5040</entry>
<entry key='apel.port'>5041</entry>
<entry key='manpower.port'>5042</entry>
<entry key='globalsat.port'>5043</entry>
<entry key='atrack.port'>5044</entry>
<entry key='pt3000.port'>5045</entry>
<entry key='ruptela.port'>5046</entry>
<entry key='topflytech.port'>5047</entry>
<entry key='laipac.port'>5048</entry>
<entry key='aplicom.port'>5049</entry>
<entry key='gotop.port'>5050</entry>
<entry key='sanav.port'>5051</entry>
<entry key='gator.port'>5052</entry>
<entry key='noran.port'>5053</entry>
<entry key='m2m.port'>5054</entry>
<entry key='osmand.port'>5055</entry>
<entry key='easytrack.port'>5056</entry>
<entry key='gpsmarker.port'>5057</entry>
<entry key='khd.port'>5058</entry>
<entry key='piligrim.port'>5059</entry>
<entry key='stl060.port'>5060</entry>
<entry key='cartrack.port'>5061</entry>
<entry key='minifinder.port'>5062</entry>
<entry key='haicom.port'>5063</entry>
<entry key='eelink.port'>5064</entry>
<entry key='box.port'>5065</entry>
<entry key='freedom.port'>5066</entry>
<entry key='telic.port'>5067</entry>
<entry key='trackbox.port'>5068</entry>
<entry key='visiontek.port'>5069</entry>
<entry key='orion.port'>5070</entry>
<entry key='riti.port'>5071</entry>
<entry key='ulbotech.port'>5072</entry>
<entry key='tramigo.port'>5073</entry>
<entry key='tr900.port'>5074</entry>
<entry key='ardi01.port'>5075</entry>
<entry key='xt013.port'>5076</entry>
<entry key='autofon.port'>5077</entry>
<entry key='gosafe.port'>5078</entry>
<entry key='tt8850.port'>5079</entry>
<entry key='bce.port'>5080</entry>
<entry key='xirgo.port'>5081</entry>
<entry key='calamp.port'>5082</entry>
<entry key='mtx.port'>5083</entry>
<entry key='tytan.port'>5084</entry>
<entry key='avl301.port'>5085</entry>
<entry key='castel.port'>5086</entry>
<entry key='mxt.port'>5087</entry>
<entry key='cityeasy.port'>5088</entry>
<entry key='aquila.port'>5089</entry>
<entry key='flextrack.port'>5090</entry>
<entry key='blackkite.port'>5091</entry>
<entry key='adm.port'>5092</entry>
<entry key='watch.port'>5093</entry>
<entry key='t800x.port'>5094</entry>
<entry key='upro.port'>5095</entry>
<entry key='auro.port'>5096</entry>
<entry key='disha.port'>5097</entry>
<entry key='thinkrace.port'>5098</entry>
<entry key='pathaway.port'>5099</entry>
<entry key='arnavi.port'>5100</entry>
<entry key='nvs.port'>5101</entry>
<entry key='kenji.port'>5102</entry>
<entry key='astra.port'>5103</entry>
<entry key='homtecs.port'>5104</entry>
<entry key='fox.port'>5105</entry>
<entry key='gnx.port'>5106</entry>
<entry key='arknav.port'>5107</entry>
<entry key='supermate.port'>5108</entry>
<entry key='appello.port'>5109</entry>
```

</properties>

**Comment by vitalidze** [comment]
Why do you have several geocoder entries?

``` xml
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>opencage</entry>
<entry key='geocoder.url'>http://api.opencagedata.com/geocode/v1</entry>
<entry key='geocoder.key'>mykey</entry>

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>
```

You should have only one, for example google:

``` xml
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>
```

This is definitely a wrong reverse geocoder configuration entry. It's a big surprise if it even work with original traccar config and database.

**Comment by jovicassia** [comment]
The first time was only tested with google

Before I tested at all forms, with one at a time, with three at the same time does not work

**Comment by jovicassia** [comment]
aff !!!

is working, tanks a lot
