### ISSUE TITLE
traccar unable to start after modified conf file for more features 

### ISSUE THREAD

**Issue by vasu2211** [vitalidze/traccar-web#653]
http:// traccar.litvak.su/installation.html, according to link and my knowledge i updated conf file , after that traccar start fail due to service error code 1, please help me to resolve the issue.

**Comment by vasu2211** [comment]
need help

**Comment by vitalidze** [comment]
Since you have posted #654, this issue is resolved? Can it be closed?

**Comment by vasu2211** [comment]
yes i am closing
