### ISSUE TITLE
command SMS

### ISSUE THREAD

**Issue by cesarruben** [vitalidze/traccar-web#656]
Hi I need to know how to send sms the command works, you must configure a gateway sms or connect a modem. Thank you

**Comment by vitalidze** [comment]
I think the easiest way will be to use some third-party provider like https://www.twilio.com/ and add a new notification sending method to the system. You can set up an SMS gateway too, but it looks more complicated from the start.

**Comment by vitalidze** [comment]
Oh, if it's about the new command type 'Send SMS'. From my understanding it just sends some command to the device over TCP/UDP connection with the SMS message text. Then this text is just sent from the device to the number you have specified. It's better to ask here: https://github.com/tananaev/traccar/issues

**Comment by cesarruben** [comment]
Thank you...
