### ISSUE TITLE
notification expiration period

### ISSUE THREAD

**Issue by Mindreader12345** [vitalidze/traccar-web#657]
If I have a Device registered and don´t turn it on in next 12 hours, the Device is expired and doesn´t show anymore in Traccar !?
Is it possible to reset it and how ?

Thank you ...

**Comment by vitalidze** [comment]
The `notification expiration period` just controls the notifications sent by email/pushbullet: geo-fence enter/exit, offline, idle, movement. If notification cannot be sent within 12 hours period for some reason, say there are no configured notification settings, or they are incorrect, or email/pushbullet service is down for this period, then notification is considered expired. So it won't be sent anymore to the users of platform.

Thus, it has nothing to do with the device turned off. If you turn it on then it should just appear automatically.

**Comment by Mindreader12345** [comment]
Ah, OK.
Sorry for that, I misunderstood that.
I didn´t find my device, but the problem was another: I changed my Webadress, but not in my GPS-device :-(

Thank you ...
