### ISSUE TITLE
Can not send commands

### ISSUE THREAD

**Issue by Ruben1966** [vitalidze/traccar-web#659]
I install the  traccar-windows-32-3.5.zip (date 17-Apr-2016), but  when I sent a command it show me the next error:"{\"reason\":\"java.lang.reflect.InvocationTargetException: null\",\"success\":false}", please see the attached image.

You will find attached the traccar config files and logs files
Please help me to fix this trouble
Best regards

Ruben

![traccar1](https://cloud.githubusercontent.com/assets/15811174/15060388/325f40b0-12e7-11e6-91f3-1c13357c1d84.JPG)
[services wrapper logs .docx](https://github.com/vitalidze/traccar-web/files/251358/services.wrapper.logs.docx)
[traccar server logs.docx](https://github.com/vitalidze/traccar-web/files/251359/traccar.server.logs.docx)

**Comment by Ruben1966** [comment]
Attached you also will find traccar config files
[traccar.txt](https://github.com/vitalidze/traccar-web/files/251362/traccar.txt)

**Comment by vitalidze** [comment]
The reason of this issue is that such command is not supported by the device:

```
INFO   | jvm 1    | 2016/05/05 11:54:11 | Caused by: java.lang.RuntimeException: Command positionPeriodic is not supported in protocol h02
INFO   | jvm 1    | 2016/05/05 11:54:11 |   at org.traccar.BaseProtocol.sendCommand(BaseProtocol.java:45)
INFO   | jvm 1    | 2016/05/05 11:54:11 |   at org.traccar.database.ActiveDevice.sendCommand(ActiveDevice.java:46)
INFO   | jvm 1    | 2016/05/05 11:54:11 |   ... 59 more
```

**Comment by Ruben1966** [comment]
Thank you very much

Please let me know,  what should I do to solve this problem

**Comment by vitalidze** [comment]
You need to implement this particular command for the protocol your device is using. All commands sending is implemented on the "backend" project: https://github.com/tananaev/traccar According to this particular file the "Position periodic" is actually implemented: https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/H02Protocol.java However, it's support is not yet released, i.e. it is not included in traccar 3.5. So you should either build it yourself from sources or wait until traccar 3.6 is released.

**Comment by Ruben1966** [comment]
Thank you very much

I'm new using  traccar,  what the tab ¨ import¨ is for

**Comment by vitalidze** [comment]
You can import positions for device from a GPX file.

**Comment by Ruben1966** [comment]
Thank you very much

**Comment by inghenryh** [comment]
I have the same error, I have gps with gps103 protocol and when I send a command appears this 
![screenshot5](https://cloud.githubusercontent.com/assets/18343978/15664085/aef4fe70-2733-11e6-9509-05bf994ac4ac.png)

I think I know the error, when the installation is a command that had to replace the traccar.xml

I had to replace

Old:

<Entry key = 'database.getPermissionsAll'>
     SELECT userid, deviceId FROM user_device;
</ Entry>

but in the installation of the original file traccar 3.5 this command does not appear

<Entry key = 'database.getPermissionsAll'>
     SELECT userid, deviceId FROM user_device;
</ Entry>

command does not appear like that I can not replace:

<Entry key = 'database.selectDevicePermissions'>
     U.id AS SELECT userid, d.id deviceId AS FROM users u, d WHERE devices u.admin = 1
     UNION
     Ud.users_id AS SELECT userid, ud.devices_id AS FROM users_devices ud deviceId
     INNER JOIN users u ON ud.users_id = u.id
     WHERE AND u.readOnly u.admin = 0 = 0
</ Entry>

I think that's the problem.

Excuse my English

**Comment by vitalidze** [comment]
@inghenryh message from your screenshot is completely different from the message from @Ruben1966 It actually means that command has been sent successfully.

**Comment by inghenryh** [comment]
and because only appears {}? should not appear "the command has been sent"?

2016-05-31 13:38 GMT+08:00 Vitaly Litvak notifications@github.com:
