### ISSUE TITLE
i have tk103 device already connected to another server and tracking software should i connect to traccar

### ISSUE THREAD

**Issue by vasu2211** [vitalidze/traccar-web#660]
i tried to connect my mobile to traccar which is on my pc localhost, unable to connect,

tracker server logs i found 

2016-05-06 10:26:49  WARN: Table "SERVER" not found; SQL statement:

**Comment by vitalidze** [comment]
It is not related anyhow.

Your tk103 tracker should have access to your local machine, you can not put `localhost` in it's settings.

**Comment by vasu2211** [comment]
ok thx
