### ISSUE TITLE
issue with latest traccar

### ISSUE THREAD

**Issue by vopatel** [vitalidze/traccar-web#661]
I am getting following errors in wrapper logs. I am using postgresql. This is fresh database.

INFO   | jvm 1    | 2016/05/06 11:51:25 | INFO: Login 'admin'
INFO   | jvm 1    | 2016/05/06 11:52:04 | May 06, 2016 11:52:04 AM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2016/05/06 11:52:04 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2016/05/06 11:52:04 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at org.traccar.web.server.model.EventServiceImpl$OfflineDetector.doWork(EventServiceImpl.java:58)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/05/06 11:52:04 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/05/06 11:52:04 |

**Comment by vitalidze** [comment]
This error means you don't have value in `time` column in the `positions` table for some row. Most probably you have incorrect query to insert positions into database in your `traccar.xml` file.

**Comment by vopatel** [comment]
Ok. I added time column in insert positions query in traccar.xml as follows
    <entry key='database.insertPosition'>
        INSERT INTO positions (deviceid, protocol, servertime, devicetime, fixtime, valid, latitude, longitude, altitude, speed, course, address, attributes, time)
        VALUES (:deviceid, :protocol, :now, :devicetime, :fixtime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes, :now);
    </entry>

Now I am getting following error while starting up the traccar and traccar doesnt start. All the values in 'time' column of 'positions' table are populated (none of them are null)

INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at java.io.StringReader.<init>(StringReader.java:50)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder$7.process(QueryBuilder.java:359)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder.executeQuery(QueryBuilder.java:409)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.getLatestPositions(DataManager.java:452)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.database.ConnectionManager.<init>(ConnectionManager.java:55)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:179)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/05/06 13:25:58 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)

**Comment by vitalidze** [comment]
Looks like you have some error in your `traccar.xml` file (typo).

**Comment by vopatel** [comment]
I havent modified the traccar.xml except the above change. I have attached traccar.xml here for your review.
[traccar.xml.txt](https://github.com/vitalidze/traccar-web/files/256189/traccar.xml.txt)

**Comment by vitalidze** [comment]
Your config file looks good. I think I got it. You cannot have `null` in `time` column. It fails during startup because of that. So, you need to fill it with some values.
