### ISSUE TITLE
WARN: Table 'dbtc.server' doesn't exist

### ISSUE THREAD

**Issue by novistudionl** [vitalidze/traccar-web#664]
Hi,

I might have a problem here, see below log. Running traccar version 3.5 and Traccar UI version 3.5. I have installed the server from scratch (not by updating it).

log:
`2016-05-06 18:52:48  WARN: Table 'dbtc.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457 < PermissionsManager:74 < ...)`

**Comment by vitalidze** [comment]
You can safely ignore it.

P.S. this has been reported several times. Please use search before posting your own question.

**Comment by novistudionl** [comment]
I did use the search funtion plus i googled it several times. Didnt pop up any threads. Anyway, thanks for answering, You rock.
