### ISSUE TITLE
Email all users

### ISSUE THREAD

**Issue by wolfbgn** [vitalidze/traccar-web#666]
Thanks again for the great job.
Since you are constantly improving the program and adding new features isn't it possible to add function for admin to send explanatory email to all users. I have several of my friends (who don't speak English) using my server guarding their cars and I am tired of explaining them the new features. It will be really convenient to write just one mail and send it to every user with push of a button.

**Comment by vitalidze** [comment]
Thank you for the warm words.

This sounds like a job for the Email client application. Why don't you use the Gmail or MS Outlook or The Bat or Thunderbird for such task?

**Comment by wolfbgn** [comment]
I use my own mail server on the same machine with Traccar to send notifications to users. It works-sends emails locally on the same domain. I will look in settings of roundcube if postmaster is able to send mail to all users.

**Comment by wolfbgn** [comment]
As a matter of fact I just looked in the mail client and discovered that I can mail to a whole group from my address book. Thank you very much.

**Comment by vitalidze** [comment]
No problem, you are welcome. I just don't see much point in making mailing app out of traccar. There are many other ways to notify your users, besides email - like web site, group on google plus, on facebook, twitter, etc. I think you can even embed the news list into the traccar login page too. I don't think it should be a part of a public project, at least for now.
