### ISSUE TITLE
Change Vehicle icons from side view to top

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#668]
Hi Litvak
you did a great job with the latest update, i would like to suggest that instead of displaying vehicle icons like cars and truck with side view like this
![car-left-red-icon](https://cloud.githubusercontent.com/assets/11395006/15097806/c13e2dce-1520-11e6-9024-021504bcfb4e.png)

it personally think it will look better if they are displayed from top view like this
![car-top-red-icon](https://cloud.githubusercontent.com/assets/11395006/15097818/fdcea6a6-1520-11e6-8396-fd77410bd9a4.png)

This are just suggestions, i will also like your input on this.

**Comment by vitalidze** [comment]
Well, I can add such icons to the default set. For now I have other higher priority tasks. Since everybody has an option to upload his own icons, I don't see much value in spending time on this.

**Comment by gpproton** [comment]
i understand your position, on that.

Date: Sun, 8 May 2016 06:04:35 -0700
