### ISSUE TITLE
FIX https - nginx reverse proxy to http - MIXED CONTENT

### ISSUE THREAD

**Issue by dschense** [vitalidze/traccar-web#672]
Way to fix the mixed contend error when reverse proxy (i did it with nginx) https domain to http content on local service. (Only in the Desktop version. No problem with the mobile version)

The problem was: //www.openstreetmap.org/openlayers/OpenStreetMap.js file.
I unzipped traccar-web.war to edit the traccar.html file.
there the line: //www.openstreetmap.org/openlayers/OpenStreetMap.js is the problem.

I downloaded this file over the browser and safed it local as OpenStreetMap.js
then I edited all http:// to only // like:

```
"http://a.tile.openstreetmap.org/${z}/${x}/${y}.png",
 "http://b.tile.openstreetmap.org/${z}/${x}/${y}.png",
 "http://c.tile.openstreetmap.org/${z}/${x}/${y}.png"

<a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>
```

to:

```
"//a.tile.openstreetmap.org/${z}/${x}/${y}.png",
 "//b.tile.openstreetmap.org/${z}/${x}/${y}.png",
 "//c.tile.openstreetmap.org/${z}/${x}/${y}.png"

<a href='//www.openstreetmap.org/copyright'>OpenStreetMap</a>
```

I changed all of them.

after this i uploaded this to github and linked it to rawgit to get accessable file.
Its also possible to upload it to the own webspace to access. (http://rawgit.com/)

after this edit the line above in traccar-web.war --> traccar.html file.
edit:

`//www.openstreetmap.org/openlayers/OpenStreetMap.js`

to the uploaded and changed  

`//webserver/address/path/to/OpenStreetMap.js`

safe and restart traccar.

after this there are no mixed content anymore. 

These are my changes of OpenStreetMap.js:
https://github.com/dschense/script-stuff/blob/master/server/traccar/openlayers/OpenStreetMap.js

**Comment by dschense** [comment]
Update:

I found some more links with the http - https problem:

```
'http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker-green.png'
'http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker.png'
```

its the same procedure to get https i think

already checked the https link support

```
'https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker-green.png'
'https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker.png'
```

exist, so

```
'//cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker-green.png'
'//cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker.png'
```

should do the job again.

**Comment by vitalidze** [comment]
Included, written [news](http://traccar.litvak.su/2016/05/21/Quick-reports,-device-context-menu.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
