### ISSUE TITLE
Error delete admin

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#676]
hello Vitalize
Using new version 3.5 with current Web UI, face this problem.
Logged in as admin, I can not delete another admin even removing their permissions.
Follow the error log
[Log erro.txt](https://github.com/vitalidze/traccar-web/files/263883/Log.erro.txt)

**Comment by vitalidze** [comment]
This is because your administrator created some users. Thus, these users have him set up as their manager. I don't know what should be the correct way to handle such situation. I think you should just block his account.

**Comment by MarceloMJM** [comment]
OK thank you...

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/05/21/Quick-reports,-device-context-menu.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
