### ISSUE TITLE
Installation precision

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#678]
Hello,

I want to install  3.5
As write here http://traccar.litvak.su/installation.html

```
update following lines:
SQL query to select list of GPS tracking devices (does not apply to 3.3)
```

means strictly and ONLY for 3.3 ?  so for 3.4, 3.5 I need to follow instructions below ?

**Comment by vitalidze** [comment]
This particular query is the same as the original one for 3.3, 3.4 and 3.5. So you don't need to change it, even if you change it there will be no difference. All other queries must be updated accordingly.
