### ISSUE TITLE
Odometer zero

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#679]
Hi!
I have a request from our users to att odometer function. That is, the user want to add current milage and get calculated from that point.
Now when I dig into this I can see that we do not have the odometer at all in the popup for devices and in our database we have only zeros. We use two different devices.
Is odometer data something that is coming from the device itself or is it a number calculated by traccar?

/zzyber

**Comment by vitalidze** [comment]
Currently odometer is either set up manually or can be updated automatically by scanning received positions and summing up distance between them. If you have zero value in odometer then it won't be shown in popup. A little bit more info can be found here: http://traccar.litvak.su/features/maintenance.html

Also in latest versions there is a possibility to hide it from popup even when it has non-zero value.

**Comment by zzyber** [comment]
Oh I´m so sorry, I can see now I have to add a odometer start in device settings and as long as this is not done I have zero which is same as disabled. Thanks
