### ISSUE TITLE
"Send location" icon is missed

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#680]
I've noticed that icons are missed, but work.

![image](https://cloud.githubusercontent.com/assets/5688080/15288149/c8740f02-1b81-11e6-9987-525824fe3b79.png)

**Comment by vitalidze** [comment]
Thanks for reporting. Looks like it is caused by an update of `framework7` library. Will try to fix it in next release.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/05/21/Quick-reports,-device-context-menu.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
