### ISSUE TITLE
Archive toolbar: order devices by name

### ISSUE THREAD

**Issue by MMartinezV** [vitalidze/traccar-web#681]
Hi Vitaly,

It would be nice to have the devices ordered by name in the devices selector on the archive toolbar.

It's obviously not important, but I think it is simple to do and it would look better ;-)

Regards,

  Manuel

**Comment by vitalidze** [comment]
It should be already fixed in the latest update. Please read release notes here: http://traccar.litvak.su/2016/05/07/Device-direction,-idle-status-on-map.html

**Comment by MMartinezV** [comment]
Sorry,

I thought I was already using the latest version (but mine is from 25-apr). I'll do the update tonight.

Thanks,

  Manuel

**Comment by vitalidze** [comment]
Please close this issue if it works for you with latest update.

**Comment by MMartinezV** [comment]
I'll do.

Thanks again.

**Comment by MMartinezV** [comment]
It's already solved in the 7-May update.

Thanks
