### ISSUE TITLE
About Port 

### ISSUE THREAD

**Issue by kedarnathjimage** [vitalidze/traccar-web#685]
I am using Gosafe G3A GPS Device. I am unable to see the device on map, when i check the log i get this hex. I am sending the data on port 5078 

2a475330322c3335353233333035343639383931332c434c4c3a3030303030303030303030303b3430343b32323b31303133353b313233312c5354543a34303b302c4144433a303b31312e393b313b34342e303b323b342e323b333b302e3023

Any input on this will be highly appreciated. Thanks

**Comment by vitalidze** [comment]
This issue is most probably not related with this web UI project. Please
try requesting help on the "backend" project's issue tracker
https://github.com/tananaev/traccar

четверг, 19 мая 2016 г. пользователь kedarnathjimage написал:

> I am using Gosafe G3A GPS Device. I am unable to see the device on map,
> when i check the log i get this hex. I am sending the data on port 5078
> 
> 2a475330322c3335353233333035343639383931332c434c4c3a3030303030303030303030303b3430343b32323b31303133353b313233312c5354543a34303b302c4144433a303b31312e393b313b34342e303b323b342e323b333b302e3023
> 
> Any input on this will be highly appreciated. Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/685

## 

Kind regards, Vitaly Litvak
