### ISSUE TITLE
Bug in Archive and Pop-up Window ?

### ISSUE THREAD

**Issue by Mindreader12345** [vitalidze/traccar-web#687]
Hello Vitaly,

I think there is a Bug, if you look in Archive or at the Pop-Up-Window about the Device-Icon and the Speed is set in Km/h, then the Speed is visible as kn and not in Km/h.

Greats Mindreader

**Comment by vitalidze** [comment]
Popup shows speed for archive in absolutely same way as it does for the latest position. What do you see for the latest position, kn or km/h? Can you show screen shot?

**Comment by Mindreader12345** [comment]
Hello, 

I find out that in my own account everything is in Km/h but if I share it with another account (only read) the speed is visible in kn.

Screenshot: 
![bild](https://cloud.githubusercontent.com/assets/17202885/15447502/9954c592-1f44-11e6-8b04-ee5e2010d1aa.jpg)

**Comment by vitalidze** [comment]
This means that user has "knots" set up for displaying speed value in his preferences.

**Comment by Mindreader12345** [comment]
Ok, but user have only Rights to Read, he can`t do anything in Preferences, how can you switch it to Km/h ?

**Comment by vitalidze** [comment]
You can change him temporarily to non-read only, update settings and then switch back to read-only.

**Comment by Mindreader12345** [comment]
Ok, thank you Vitaly !
