### ISSUE TITLE
How to speed up compile or reload

### ISSUE THREAD

**Issue by sodasonic** [vitalidze/traccar-web#688]
i test from eclipse and export .war  is slow for compile more then 2-3 minute
but download from war from website  is faster

thank.

**Comment by vitalidze** [comment]
Are you sure you are using the version from `dev` branch? For me usually it takes couple of minutes for the startup, but then all recompilations are incremental, and taking couple of seconds.

Building of `traccar-web.war` file takes 5-6 minutes on my laptop.

**Comment by sodasonic** [comment]
Hi dear
  i check out from dev branch i export war file from eclipse and deploy to jetty is slow . some time can't start 
please recommend for create war from eclipse
Now test deploy from http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war  is very fast.

Thank.

**Comment by vitalidze** [comment]
How do you build the `traccar-web.war` file? You need to do it with maven: http://traccar.litvak.su/building.html

**Comment by sodasonic** [comment]
Sorry Sir
  now download check out from git and run from eclipse and export war
  last night i test from you recommend  

Thank.
