### ISSUE TITLE
How to clean/purge my old data (Database is too heavy)

### ISSUE THREAD

**Issue by peterghobrial** [vitalidze/traccar-web#689]
How to clean/purge old database data as the Database is too heavy, and causes server to crash.
I get service unavailable 503 when I browse it!

**Comment by vitalidze** [comment]
For records removal please see #244

As for the heavy load, recent versions of the Traccar Web UI Mod should reduce it. Are you using latest version? Have you found the reason of crashes? Is it memory issue or what?

**Comment by peterghobrial** [comment]
increased cpu and ram with no luck, I don't know how to show java logs, it is windows server.
I also can't show database devices, users, settings in db.
If you can help me tell me how to access db or I can give you access to the server!

**Comment by peterghobrial** [comment]
Iam using recent version.

**Comment by vitalidze** [comment]
Can you please attach here `wrapper.log` and `tracker-server.log` files, which date is the date when you experienced crashes?

**Comment by peterghobrial** [comment]
[tracker-server.log.txt](https://github.com/vitalidze/traccar-web/files/277286/tracker-server.log.txt)
[wrapper.log.20160523.txt](https://github.com/vitalidze/traccar-web/files/277288/wrapper.log.20160523.txt)

[tracker-server.log.txt](https://github.com/vitalidze/traccar-web/files/277284/tracker-server.log.txt)
[wrapper.log.20160523.txt](https://github.com/vitalidze/traccar-web/files/277285/wrapper.log.20160523.txt)

**Comment by peterghobrial** [comment]
please note that when I stop traccar and move the db to another folder, then starting traccar again to recreate new db, the server working fine.
but when restoring my db it crashes again, I don't know if there is something wrong with db?

**Comment by vitalidze** [comment]
You are using the H2 database. It should not be used in production system, just for testing purposes. You should switch to MySQL: https://www.traccar.org/mysql/

**Comment by peterghobrial** [comment]
ok, I need to extract users data and devices data from the db, I can connect to it but where are these data?
![db](https://cloud.githubusercontent.com/assets/17801055/15471437/3648ae2e-20f6-11e6-96d8-68c109bf3b54.png)
![db2](https://cloud.githubusercontent.com/assets/17801055/15471438/36500228-20f6-11e6-8d6b-fd97646318e1.png)

**Comment by vitalidze** [comment]
Extracting data is not a trivial task. The database name should be just `database` without `mv.db` suffix. Then you should be able to expand "tables" and see your data.

**Comment by peterghobrial** [comment]
I don't have experience with databases, I renamed db (without mv.db), still the same issue, is there specific driver for the h2 db, I use the default one with the dbeaver....

**Comment by peterghobrial** [comment]
I don't have experience with databases, I renamed db (without mv.db), still the same issue, is there specific driver for the h2 db, I use the default one with the dbeaver....

**Comment by peterghobrial** [comment]
I was able to fix the access issue, but now I got error message, general error java.lang.nullpointerexception
How to fix this error?

**Comment by vitalidze** [comment]
Please show contents of latest `wrapper.log` file.

**Comment by peterghobrial** [comment]
[wrapper.log.20160525.TXT](https://github.com/vitalidze/traccar-web/files/282091/wrapper.log.20160525.TXT)

**Comment by vitalidze** [comment]
The log file shows that your H2 database is damaged. I have seen this several times and this is actually one of the reasons to recommend NOT using it in production. In theory you can repair your database somehow, but it's not a trivial task.
