### ISSUE TITLE
Combine import/export buttons in menu

### ISSUE THREAD

**Issue by vitalidze** [vitalidze/traccar-web#69]
This will reduce consumed space on archive toolbar.

**Comment by antoniopaisfernandes** [comment]
If you I can do this.

**Comment by vitalidze** [comment]
I don't mind, please do.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/01/13/Notifications,-archive-styling-and-couple-minor-improvements.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
