### ISSUE TITLE
Load Multiple Devices under Archive Pane

### ISSUE THREAD

**Issue by w32gold** [vitalidze/traccar-web#691]
Hi,
Could you please show me how to load multiple devices in archive?
Thank you.

**Comment by vitalidze** [comment]
You need to load them one-by-one. For example:

1) Select first device in archive panel, click "Load". System will load track for the device.
2) Select second device in archive panel, set up different color for the track, click "Load". System will load track for this device and track for the first one will remain untouched. There will be tabs in the archive table so you can navigate through all points for all devices, for which you have loaded tracks.
3) Continue same steps for any number of devices you want to load.

**Comment by w32gold** [comment]
Thank you.
