### ISSUE TITLE
Unable to see preference icon in the child accounts

### ISSUE THREAD

**Issue by emailragu425** [vitalidze/traccar-web#693]
Guys,
I am able to create multiple users from the admin role/login. In admin I can see all the buttons, Settings, logs, preference etc.. I did select Google maps and preference were set to km/h, since most of the watchers dont know knots.

When I login using the child account/ without admin role (Read-only, manager etc) I am unable to see preference button and it always defaults to knots. Can some one please help how to change the default to km/h or mph? Thank you

**Comment by vitalidze** [comment]
The "Preferences" button should be hidden only for "Read-only" users. If you need to change their settings then the only way is to make them temporarily non read-only, update settings and change back to "read only".

I will think about allowing read-only users to change their preferences. Also probably it's worth to define a global setting with default speed (and maybe distance) units, which will be set for all newly created user accounts.

**Comment by emailragu425** [comment]
vitalidze,
Thank you. I am able to get the data points in km/h. Few things I observed in my case:
1. Secondary/Child accounts, must be set to admin first. Only in this role the preference button comes up. Rest of all the roles it vanishes 
2. Settings button for the child user is not working. Not sure if there are JavaScript or anyother browser related issues. If other users are not seeing this problem, please let me know. 
3. Like you mentioned, it will be very helpful to add few more settings in the Global role so that the  maps,calibration etc can be controlled from the admin to other users..

Cheers

**Comment by vitalidze** [comment]
> Secondary/Child accounts, must be set to admin first. Only in this role the preference button comes up. Rest of all the roles it vanishes

This applies to "read-only" users only. I have double checked and for ordinary users it works just fine. Let me know if you can reproduce it, say on the demo site https://d.traccar.litvak.su/

> Settings button for the child user is not working. Not sure if there are JavaScript or anyother browser related issues. If other users are not seeing this problem, please let me know.

What is the "Settings" button you are talking about?

> Like you mentioned, it will be very helpful to add few more settings in the Global role so that the maps,calibration etc can be controlled from the admin to other users..

It will not change the existing users, but it will set up preferences for all newly created users. Probably I will include something like this in next version.

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2016/06/04/Sensor-text-color-and-icon,-bug-fixes.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
