### ISSUE TITLE
Unable to send custom command to GT06N

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#694]
Good day Litvak

I would like to know if it possible now to send commands to GT06N devices but I always see this "{\"reason\":\"The device is not registered on the server\",\"success\":false}" on my screen.
![gt06n_commands](https://cloud.githubusercontent.com/assets/11395006/15502395/829e3fcc-21ab-11e6-81d7-2d955edcbce1.PNG)

I really would be glad if you can tell me what can fix this.

**Comment by vitalidze** [comment]
This means your device is not currently connected to the traccar server. You can not send commands to device until they create a connection to the traccar server.

**Comment by gpproton** [comment]
But i'm thinking there should probably be constant retry for about 10 second before giving reply.

**Comment by vitalidze** [comment]
It does not work this way and looks like it's not planned. If you want to send commands to device there are following requirements:

1) Device MUST be connected to the server
2) Command MUST be implemented for the protocol that your device is using
3) Your device MUST support receiving commands through the TCP/IP

**Comment by vitalidze** [comment]
Just a little clarification - connection between device and traccar server is usually persistent, so once it connected, it opens a special "channel" to transfer data about positions, etc. The channel can hang for hours in theory.

So actually there is no point in waiting for 10 seconds. The device is either connected or not connected, there is a very little probability that something will change in 10 seconds.
