### ISSUE TITLE
Snap to road

### ISSUE THREAD

**Issue by integreated** [vitalidze/traccar-web#706]
Hello Vitalidze
Can you please tell me why I get this when I try to use Snap to road.
I use MySql,traccar 3.5 and the latest ui.
![screen](https://cloud.githubusercontent.com/assets/13402422/15648337/c673b7f8-2661-11e6-967f-3ce1c07a3ac9.jpg)

**Comment by gsiotas** [comment]
Check #387  and especially https://github.com/vitalidze/traccar-web/issues/387#issuecomment-166806797

**Comment by integreated** [comment]
Thanks gsiotas I tried it with a short trip and it was ok.
