### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by hardjumper** [vitalidze/traccar-web#708]
Since I have updated to the latest version of ui the idle status on the pop ups do not display the time right.My devices display 7 days idling time.Can somebody else check to make sure it is a bug.Thank you.

**Comment by gsiotas** [comment]
No this is not happening to me. Are you sure that the devices send their positions? Can you see the new positions in the tracker.log?

**Comment by hardjumper** [comment]
Sorry I have restarted traccar and now the idling times have changed and yes the dives report thier positions properly.I will take a close look and see whether  the idling time gets updated.Thanks again.

**Comment by vitalidze** [comment]
I think this can be a bug. Can you please attach all wrapper.log files for the last week or even last 8 days? You can send them by email (find in my github profile).

**Comment by hardjumper** [comment]
I do not keep logs because I do not have much space on the drive.Anyways after rebooting the server few days back everything is now back to normal. if you still want the logs I can  keep  some  for few days and send them to you.

**Comment by vitalidze** [comment]
I want to see the log when the issue reproduces. There should be some record on a day, which your device is considered as the idle starting date. I think something happens there. So, basically I don't need abstract log files, the idea is to catch error somehow.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2016/06/04/Sensor-text-color-and-icon,-bug-fixes.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

Please let me know if you still can reproduce this issue.
