### ISSUE TITLE
Time format changes from Local time setting to GMT while exporting the reports

### ISSUE THREAD

**Issue by hypnotisedkid** [vitalidze/traccar-web#709]
The time format should remain the same as the admin settings while exporting the reports right ? Also there seems to be some error with the csv formatting ( kingsoft office does not differentiate between the date and time )

**Comment by vitalidze** [comment]
> The time format should remain the same as the admin settings while exporting the reports right ?

Time format for reports is currently: `yyyy-MM-dd HH:mm:ss`
Date format is: `d MMM yyyy`

> Also there seems to be some error with the csv formatting ( kingsoft office does not differentiate between the date and time )

I don't know what is the kingsoft office. The target platform is MS Office and LibreOffice.

**Comment by hypnotisedkid** [comment]
Apologies I meant the time zone changes while exporting. i.e if the time zone for the traccar Web interface is set to GMT+5:30,then exporting it to csv generated the report in GMT  instead of GMT+5:30.

Kingsoft office is like LibreOffice for Windows.

**Comment by vitalidze** [comment]
> Apologies I meant the time zone changes while exporting. i.e if the time zone for the traccar Web interface is set to GMT+5:30,then exporting it to csv generated the report in GMT instead of GMT+5:30.

Timezone setting does not affect export to CSV. Dates will be in the timezone from your server. I think you can change server timezone to achieve desired result.

> Kingsoft office is like LibreOffice for Windows.

How it should differentiate between date and time? What does it mean?

**Comment by hypnotisedkid** [comment]
Oh thank you . The reports documentation [http://traccar.litvak.su/features/reports.html](here) states that the timezone setting in reports is that of the preferences hence the confusion maybe. Thanks !

**Comment by hypnotisedkid** [comment]
Regarding the differentiation aspect it either displayed the date or the time. Added a custom filter and that sorted the issue with it.

**Comment by vitalidze** [comment]
> Oh thank you . The reports documentation http://traccar.litvak.su/features/reports.html states that the timezone setting in reports is that of the preferences hence the confusion maybe. Thanks !

This works for reports. CSV export is not covered by that article.

**Comment by hypnotisedkid** [comment]
My bad sorry. I considered csv exports as a part of the same. Thanks for being patient about it. I changed my server timezone settings and the csv is all good now! 

Also is their a way I can remove certain column from csv before exporting  it? Like a default option that does not include altitudes, other info etc in reports or csv. 
TIA!

**Comment by vitalidze** [comment]
> Also is their a way I can remove certain column from csv before exporting it? Like a default option that does not include altitudes, other info etc in reports or csv. 

There is no way to configure it. Current format is hard coded, I guess it should be fairly easy to delete a column in LibreOffice or MS Excel.

**Comment by hypnotisedkid** [comment]
Doing that currently .!   It's it possible to remove it forever..? Like changing the dB or code?  I don't need them anytime.

**Comment by vitalidze** [comment]
You can update the code here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/ExportServlet.java#L109 Then rebuild project by following official instructions: http://traccar.litvak.su/building.html (may require local apache maven installation)

**Comment by hypnotisedkid** [comment]
Thanks!
