### ISSUE TITLE
How to use REST api

### ISSUE THREAD

**Issue by Hemendrajain** [vitalidze/traccar-web#71]
Vitali,
   Please give examples of using REST API..
I intend to export last GPS tracking data for a particular user...

Thanks,
DK

**Comment by vitalidze** [comment]
Current simple REST API exposes methods from DataService interface on `/traccar/rest` URL https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/model/DataService.java

Authentication info is held in HTTP session, so you should have corresponding cookie in every request after logging in. Below are examples of logging in an fetching data with `curl` (with demo site at http://d.traccar.litvak.su).

* Login (`login` method)

````bash
 ~  curl -v -X POST --data "[\"user\",\"password\"]" http://d.traccar.litvak.su/traccar/rest/login
* Hostname was NOT found in DNS cache
*   Trying 188.166.50.6...
* Connected to d.traccar.litvak.su (188.166.50.6) port 80 (#0)
> POST /traccar/rest/login HTTP/1.1
> User-Agent: curl/7.37.1
> Host: d.traccar.litvak.su
> Accept: */*
> Content-Length: 25
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 25 out of 25 bytes
< HTTP/1.1 200 OK
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Fri, 16 Jan 2015 11:50:26 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 217
< Connection: keep-alive
< Set-Cookie: JSESSIONID=xxxxxxxxxxxx;Path=/
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
<
* Connection #0 to host d.traccar.litvak.su left intact
{"id":2,"login":"user","password_hash_method":"MD5","admin":true,"manager":true,"userSettings":{"speedUnit":"knots","timePrintInterval":10,"zoomLevel":1,"centerLongitude":12.5,"centerLatitude":41.9,"mapType":"OSM"}}%
````

Note `Set-Cookie` header with `JSESSIONID`. This should be put in all next requests.

* Load list of devices (`getDevices` method)

````bash
curl -v --cookie "JSESSIONID=xxxxxxxxxxx" http://d.traccar.litvak.su/traccar/rest/getDevices
* Hostname was NOT found in DNS cache
*   Trying 188.166.50.6...
* Connected to d.traccar.litvak.su (188.166.50.6) port 80 (#0)
> GET /traccar/rest/getDevices HTTP/1.1
> User-Agent: curl/7.37.1
> Host: d.traccar.litvak.su
> Accept: */*
> Cookie: JSESSIONID=xxxxxxxxxx
>
< HTTP/1.1 200 OK
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Fri, 16 Jan 2015 11:51:57 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 5593
< Connection: keep-alive
<
[{"id":3,"uniqueId":"123","name":"Phone","timeout":300,"idleSpeedThreshold":0.0,"iconType":{"ARCHIVE":{"width":21,"height":25,"urls":["http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker-blue.png","http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/img/marker-gold.png"]},"OFFLINE":{"width":63,"height":25,"urls":["/img/long-truck-white.png","/img/long-truck-green.png"]},"LATEST":{"width":63,"height":25,"urls":["/img/long-truck-red.png","/img/long-truck-green.png"]}}}]%
````

Take full JSON of device and put it to `getPositions` method.

* Load archived positions (`getPositions` method)

````bash
curl -v --cookie "JSESSIONID=xxxxxxxxx" -X POST --data "[{\"id\":3,\"uniqueId\":\"123\",\"name\":\"Phone\"},\"2015-01-01 00:00:00 GMT\",\"2015-01-01 23:59:59 GMT\",false]" http://d.traccar.litvak.su/traccar/rest/getPositions
* Hostname was NOT found in DNS cache
*   Trying 188.166.50.6...
* Connected to d.traccar.litvak.su (188.166.50.6) port 80 (#0)
> POST /traccar/rest/getPositions HTTP/1.1
> User-Agent: curl/7.37.1
> Host: d.traccar.litvak.su
> Accept: */*
> Cookie: JSESSIONID=xxxxxxx
> Content-Length: 109
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 109 out of 109 bytes
< HTTP/1.1 200 OK
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Fri, 16 Jan 2015 11:56:41 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 2
< Connection: keep-alive
<
* Connection #0 to host d.traccar.litvak.su left intact
[]%
````

In this concrete example there are no positions in reply.

* log out (`logout` method)

````bash
~  curl -v --cookie "JSESSIONID=xxxxxxxx" http://d.traccar.litvak.su/traccar/rest/logout
* Hostname was NOT found in DNS cache
*   Trying 188.166.50.6...
* Connected to d.traccar.litvak.su (188.166.50.6) port 80 (#0)
> GET /traccar/rest/logout HTTP/1.1
> User-Agent: curl/7.37.1
> Host: d.traccar.litvak.su
> Accept: */*
> Cookie: JSESSIONID=xxxxxxxx
>
< HTTP/1.1 200 OK
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Fri, 16 Jan 2015 11:57:57 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 4
< Connection: keep-alive
<
* Connection #0 to host d.traccar.litvak.su left intact
true%
````

**Comment by Hemendrajain** [comment]
Thanks Vitali

**Comment by vitalidze** [comment]
Added REST api documentation [page on official web site](http://traccar.litvak.su/features/rest-api.html)

**Comment by LuisAVT** [comment]
Hi, sorry but i don't get it, i don't understand how this api works, we're trying to develope a gps tracking android app, so we're using traccar as the server with all the gps devices conected there, please can you help us with this how can we integrate this api to the android app?? for example we want to ask traccar for positions and be able to calculate arrival timings for a specific device to a certain point .. hope you can help us this is really important for us!!! thank you in advance!

**Comment by vitalidze** [comment]
@LuisAVT There is an example on how to load latest positions (in cURL), loading archived positions is similar. You should be familiar at least with HTTP requests in order to use API provided by `traccar-web`. 

Or I am missing something in your question.

**Comment by LuisAVT** [comment]
Hi Vital, so a more specific question would be like this:

How would we login using this http://d.traccar.litvak.su/traccar/rest/login?payload=[“your_username”,”your_password”]

**Comment by vitalidze** [comment]
You should make a `GET` HTTP request to that URL, response will contain an `Set-Cookie` header with `JSESSONID`. This is an unique session identifier. You should then use that identifier in all next requests as cookie.

**Comment by LuisAVT** [comment]
How would we send request? I mean through which link, If we send the request it will definitely be send through a link, Which is that link supposing that we're using a remote server with traccar? sorry but i'm new with this and we are working outta time

**Comment by vitalidze** [comment]
You should put an IP address or DNS name of your remote server instead of `d.traccar.litvak.su`, so it will be something like:

```
http://1.2.3.4/traccar/rest/login?payload=[“your_username”,”your_password”]
```

**Comment by LuisAVT** [comment]
Ok Vital but I guess this part /traccar/rest/login is a location on that server right? because in the traccar folder i don't see any rest or login folders or am I confusing something, i've already installed traccar with this http://traccar.litvak.su/installation.html

**Comment by vitalidze** [comment]
No, this URL is defined in `web.xml` and is served programmatically by servlet.

**Comment by LuisAVT** [comment]
Alright... and this part [“your_username”,”your_password”], supposing that I login traccar with admin (user) and admin (password), I should put it like this: [“admin”,”admin”] ?

**Comment by vitalidze** [comment]
Yeah, `["admin","admin"]` should work.

**Comment by LuisAVT** [comment]
Ok my friend we'll be testing out all of this, thanks a lot!!!!!!!!!!
