### ISSUE TITLE
Server would not work 

### ISSUE THREAD

**Issue by gonenmustafa** [vitalidze/traccar-web#713]
Demo server is dark when you try on a Web browser

**Comment by vitalidze** [comment]
It works just fine for me. I didn't do anything.

**Comment by vitalidze** [comment]
Looks like there is some issue with mobile UI.

**Comment by gonenmustafa** [comment]
Yessir.
Still dark I tried 3 different browser

**Comment by vitalidze** [comment]
Should be working now. Please check. I also updated release with a fix for this issue.

**Comment by gonenmustafa** [comment]
Ok thanks
