### ISSUE TITLE
traccar web ui + traccar server 3.5 Remote call error

### ISSUE THREAD

**Issue by reivaxgc** [vitalidze/traccar-web#723]
Hello,

I installed the latest version traccar ui web server and traccar 3.5 and when I open the browser then I get the error "remote call error".

The log wrapper.log gives me the following information:

`STATUS | wrapper  | 2016/06/09 18:17:01 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/06/09 18:17:01 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/06/09 18:17:01 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/06/09 18:17:01 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/06/09 18:17:01 | 
STATUS | wrapper  | 2016/06/09 18:17:02 | Launching a JVM...
INFO   | jvm 1    | 2016/06/09 18:17:02 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/06/09 18:17:02 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/06/09 18:17:02 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/06/09 18:17:03 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9heyx1hrfcy3xv|3bf36586, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9heyx1hrfcy3xv|3bf36586, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2016/06/09 18:17:03 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @976ms
INFO   | jvm 1    | 2016/06/09 18:17:04 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.15.v20160210
INFO   | jvm 1    | 2016/06/09 18:17:05 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7f68d1e9{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/06/09 18:17:06 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2016/06/09 18:17:10 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@5a91027f{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-3480985839084386476.dir/webapp/,AVAILABLE}{/opt/traccar/traccar-web.war}
INFO   | jvm 1    | 2016/06/09 18:17:10 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@7f54a5f8{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/06/09 18:17:10 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @7802ms
INFO   | jvm 1    | 2016/06/09 18:17:13 | [qtp252444603-36] INFO / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: ERROR: The serialization policy file '/traccar/70E9F10B67D13B085A9FB99358417542.gwt.rpc' was not found; did you forget to include it in this deployment?
INFO   | jvm 1    | 2016/06/09 18:17:13 | [qtp252444603-36] INFO / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: ERROR: The serialization policy file '/traccar/70E9F10B67D13B085A9FB99358417542.gwt.rpc' was not found; did you forget to include it in this deployment?
INFO   | jvm 1    | 2016/06/09 18:17:13 | [qtp252444603-36] INFO / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: WARNING: Failed to get the SerializationPolicy '70E9F10B67D13B085A9FB99358417542' for module 'http://192.0.0.8:8082/traccar/'; a legacy, 1.3.3 compatible, serialization policy will be used.  You may experience SerializationExceptions as a result.
STATUS | wrapper  | 2016/06/09 18:25:14 | TERM trapped.  Shutting down.
INFO   | jvm 1    | 2016/06/09 18:25:14 | [Thread-14] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@7f54a5f8{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/06/09 18:25:14 | [Thread-14] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@5a91027f{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-3480985839084386476.dir/webapp/,UNAVAILABLE}{/opt/traccar/traccar-web.war}
INFO   | jvm 1    | 2016/06/09 18:25:14 | [Thread-14] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@7f68d1e9{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/06/09 18:25:14 | <-- Wrapper Stopped`

Any ideas?

Thank you

**Comment by vitalidze** [comment]
I think there is either some issue with your server machine, like out of disk space in `/tmp` folder or you haven't cleaned up web browser cache.

**Comment by reivaxgc** [comment]
Hello

Thanks, it was actually the browser. I've tried i chrome it worked the first time. With firefox I struggled, but after clearing the cache has also worked. Thank you very much
