### ISSUE TITLE
geofence reports and notifications not working

### ISSUE THREAD

**Issue by bizkit1** [vitalidze/traccar-web#724]
Hello and let me congratulate you on your great work with this project.
I am having trouble getting reports and email notifications for units entering or leaving geofences. I have created a couple of geofences, but in the reports i don't get anything and either notifications.
Any ideea about this?
Thanks!

**Comment by vitalidze** [comment]
This sounds like incorrect setup of geo-fences. Are you sure have set them up correctly? Have you read official article about geo-fences http://traccar.litvak.su/features/geofences.html ?

**Comment by bizkit1** [comment]
Yup, i deleted the geofence, created it again and it works. SOrry, my bad.
