### ISSUE TITLE
Parameter "#1" is not set; SQL statement:

### ISSUE THREAD

**Issue by gitty8** [vitalidze/traccar-web#728]
How to fix:

`WARN: Parameter "#1" is not set; SQL statement:
INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); [90012-191] - JdbcSQLException (... < QueryBuilder:431 < DataManager:440 < DefaultDataHandler:27 < ...)
2016-06-13 03:17:57  INFO: [4D26274E] id: 1, time: 2016-06-13 03:17:13, lat: 99.21199, lon: 99.94865, speed: 0.0, course: 0.0
`

Device not showing up.

**Comment by vitalidze** [comment]
I think you have incorrect query in your configuration file. Please double check all configuration entries from http://traccar.litvak.su/installation.html page

**Comment by gitty8** [comment]
`2016-06-30 03:48:29  WARN: Table "DEVICE" not found; SQL statement:
SELECT * FROM device; [42102-191] - JdbcSQLException (... < QueryBuilder:61 < *:131 < DataManager:328 < *:139 < *:185 < BaseProtocolDecoder:47 < ...)
`

**Comment by gitty8** [comment]
Can you check my traccar.xml http://pastebin.com/rr9LP2C5
unknown how to fix this issue.

**Comment by w32gold** [comment]
Alter table name "device" to "devices".
Hope it helps.
- Sherwin

**Comment by gitty8** [comment]
Do you mean:

`<entry key='database.selectDevicesAll'>
        SELECT * FROM device;
    </entry>`

to

`<entry key='database.selectDevicesAll'>
        SELECT * FROM devices;
    </entry>`

**Comment by gitty8** [comment]
Thanks! this resolved the issue! thank you!
