### ISSUE TITLE
Zoom to device on click

### ISSUE THREAD

**Issue by pallavt** [vitalidze/traccar-web#73]
It would be a nice feature if the map would zoom in when a device is clicked.

**Comment by antoniopaisfernandes** [comment]
Hi pallavt,

Zoom to what extend? Max zoom? It's wierd.. :)

Best regards,
Antonio Fernandes

**Comment by vitalidze** [comment]
It looks weird for me too. From my opinion it works quite well when you set up constant zoom level and save it in preferences. Then on every click in devices table at the left hand side you get your device/vehicle centered on map.

**Comment by pallavt** [comment]
That is a work around.
