### ISSUE TITLE
traccar manager

### ISSUE THREAD

**Issue by bizkit1** [vitalidze/traccar-web#731]
Any ideea if the Traccar Manager for android works with this mod installed?
Thanks!

**Comment by vitalidze** [comment]
AFAIK for now there is no manager application for Android OS, which supports Traccar Web UI Mod.

**Comment by karthikindia** [comment]
thanks pls close the issue

**Comment by ijrad** [comment]
Hi, I developed a Traccar manager version using hybrid framework (Ionic), it is free and compatible with the UI Mod:
https://play.google.com/store/apps/details?id=com.ionicframework.tracgpsmonitor461755

**Comment by degaray** [comment]
Ijrad do you have ionic source code?
