### ISSUE TITLE
Traffic jam and report

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#732]
Hi!
I have a question regarding the report start and stop. If I want to use it as a driver´s log I get a lot of registered records when in a traffic jam. It can be for hours and with almost the same records for every few meters. How can I tune this in traccar ui? Is it even possible?

**Comment by vitalidze** [comment]
You can tune it with "Min. idle time" setting. It is used to consider device idle when the speed is below "Min idle speed" value. If you set it for an hour and "Min idle speed" to 0, then to consider device as stopped it should have 0 speed for an hour.

**Comment by zzyber** [comment]
Thanks, that did it
