### ISSUE TITLE
Compatible version 3.2 +

### ISSUE THREAD

**Issue by warlockopy** [vitalidze/traccar-web#733]
with what version of traccar is now compatible? regards.

**Comment by vitalidze** [comment]
Traccar Web UI Mod is compatible with all public available versions of traccar. You can find installation instructions here: http://traccar.litvak.su/installation.html

**Comment by warlockopy** [comment]
ok I am asking becase last time i have to downgrade from 3.3 to 3.2
because of this issue #502 
Is this solved?
I will try to install in these days to test out. I am a little bussy currently.
