### ISSUE TITLE
traccar manager android app not working after updating vitalidze ui

### ISSUE THREAD

**Issue by karthikindia** [vitalidze/traccar-web#735]
traccar manager android app not working with vitalidze ui

i was using traccar application.
worked fine web, android client, ios client, android manager.

after updating with vitalidze ui
all worked fine with web, android client, ios client except the android manager app (https://play.google.com/store/apps/details?id=org.traccar.manager&hl=en)

the error message is as follows when i debug with android studio

says Unauthorized 
401
http://domainname.com:8082/api/session

kindly advice

**Comment by vitalidze** [comment]
The traccar manager android app is not compatible with Traccar Web UI Mod.

P.S. #731 has absolutely same question. Please use search before posting your own questions.

**Comment by ijrad** [comment]
Hi, I developed a Traccar manager version using hybrid framework (Ionic), it is free and compatible with the UI Mod:
https://play.google.com/store/apps/details?id=com.ionicframework.tracgpsmonitor461755

**Comment by jolypas** [comment]
hello

this application works but but seems far away from the original  track manager (and a lot of advertising)
http web ui mobile release is providing more fuctions .
