### ISSUE TITLE
generate report to pdf 

### ISSUE THREAD

**Issue by dmetrosoft** [vitalidze/traccar-web#737]
Please i need help on How to generate and convert report like stops,geo fencing to pdf, instead of opening it on a new tab

**Comment by vitalidze** [comment]
Per current design you will need to write a PDF renderer, which will implement all methods used for drawing in a way you want them to be written to PDF. You can use iText library for that.

Probably you can also try to work it out with HTML-to-PDF converter library, from my memory PDFbox can do it. You can use google for this task.

**Comment by dmetrosoft** [comment]
We are creating an application so that we dont have to use a web browser to access the traccar web, we are using Iframe to access it, but the problem is when we try to generate reports the application will open a new window, with http Get error,  that was why I asked if it can be generated to a pdf, CSV file, but if their is a way you could show me on how to make the report open as a popup not on a new window, I will 100% appreciate it.

**Comment by vitalidze** [comment]
I think discussion from #722 may be useful in generating reports task.
