### ISSUE TITLE
HTTP method GET is not supported by this URL.

### ISSUE THREAD

**Issue by dmetrosoft** [vitalidze/traccar-web#738]
Sir, i am creating an application with [electron](https://github.com/electron/electron) so that i don't have to use a web browser to access the traccar-web ui,  i am using Iframe to access it, but the problem is when i try to generate reports the application will open a new window, with HTTP ERROR 405

Problem accessing /traccar/report/Drives%20and%20stops.html. Reason:

```
HTTP method GET is not supported by this URL.
```

Sir i could use your guide on how to generate the report on the same page via a model.

**Comment by vitalidze** [comment]
This means exactly as it says. You need to make a POST request with some parameters (see #722) to generate a report.

**Comment by dmetrosoft** [comment]
Thanks sir,  finally got it working

**Comment by dmetrosoft** [comment]
How  can I disabled world registration,  and allow only admin to register users?

**Comment by vitalidze** [comment]
There is a setting in Settings >> Global screen.

**Comment by WalrusHat** [comment]
@emmanuelnwala mind posting your answer for... others. (I need help with the call to get the drives and stops report)
