### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by sameerbatavia** [vitalidze/traccar-web#739]
saw your web ui its good , i am a noob and would like to have a step by step guide , your guide is confusing to me as my default traccar installation does not have traccar-web.war file firstly ,, also i am too noob to complile like the instructions given but want to use please guide me

**Comment by vitalidze** [comment]
If you don't have `traccar-web.war` then you don't need to back it up. I don't have any other instructions besides these: http://traccar.litvak.su/installation.html

**Comment by sameerbatavia** [comment]
i tried to do as per procedure on ur pae but it seems i am going wrong somewhere , can you please provide updated conf files and wrapper.conf  please

**Comment by vitalidze** [comment]
You don't need to modify `wrapper.conf` if you are running version other than `3.1`. The version of configuration file depend on your environment: OS and path where you installed traccar.

**Comment by sameerbatavia** [comment]
i did not modify wrapper.conf did all modifications as per instructions but still could not run the server please please upload updated xml so as i can directly put traccar-web.war and replace xml please

**Comment by sameerbatavia** [comment]
done working perfectly thanks

**Comment by vitalidze** [comment]
That's awesome. I am really glad that you managed to work it out yourself! 👍
