### ISSUE TITLE
Portuguese ( pt )

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#74]
Hello congratulations for the new changes , my doubt is how to use the Portuguese language that is available in this new version .

**Comment by vitalidze** [comment]
You should add `?locale=pt_PT` to your web browser address like:

```
http://server:8082/?locale=pt_PT
```

**Comment by MarceloMJM** [comment]
Would have to add in traccar configuration file CFG
Date: Wed, 28 Jan 2015 04:46:51 -0800

**Comment by vitalidze** [comment]
You should just type it in address bar in your web browser. No modifications in traccar configuration file required.

**Comment by MarceloMJM** [comment]
giving this error but I will check .

the mobile version was parabens show, managed to change the title in the web version , how to change the title of the mobile version .
Date: Wed, 28 Jan 2015 05:09:47 -0800

**Comment by vitalidze** [comment]
To change mobile title you should edit this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/pages/login.html

**Comment by antoniopaisfernandes** [comment]
Olá Marcelo,

Sim, se utilizares o URL com   ?locale=pt_PT  funciona perfeitamente :)
Se precisares de ajuda, diz.

Antonio Fernandes

---

Hi Marcelo,

Yes, if you use the URL with  ?locale=pt_PT   it works nicely :)
If you need any help, feel free to ask.

Antonio Fernandes

**Comment by MarceloMJM** [comment]
I am grateful for the help but unfortunately I'm still hard, do the whole process and the browser does not find the corresponding path .

**Comment by antoniopaisfernandes** [comment]
What is the current URL you use to access your traccar-web application?

**Comment by MarceloMJM** [comment]
http://my ip:8082 
at the end if I acresentar the locale =  pt_PT 
the browser displays the following error Your search - http://201.21.141.157:8082 locale = pr_PT - did not match any document.

**Comment by antoniopaisfernandes** [comment]
Try http://201.21.141.157:8082/?locale=pt_PT

**Comment by MarceloMJM** [comment]
all right now friend , thank you for help
