### ISSUE TITLE
how to add new protocol for new device

### ISSUE THREAD

**Issue by karthikindia** [vitalidze/traccar-web#740]
how to add new protocol for any new device
I received a protocol document from the device manufacturer
I tried by pointing to my server ip and port using sms config option. the device posts hex.
i decoded the hex also, but unable to find possible or understandable notes to add new device.

I dont have much idea on how to add the device.

can u suggest or help on this.

**Comment by vitalidze** [comment]
I recommend to post same question to the issue tracker of "backend" project: https://github.com/tananaev/traccar/issues Please include 'HEX' strings coming from your device there.

**Comment by karthikindia** [comment]
thanks
