### ISSUE TITLE
user allready exist

### ISSUE THREAD

**Issue by ifindu-dk** [vitalidze/traccar-web#742]
When creating new user on a brandnew install i get this error.

User allready exist

I can't create any users

**Comment by vitalidze** [comment]
This means you haven't followed installation instructions carefully. I think you haven't dropped existing traccar database or haven't disabled database schema upgrades as said in instructions.

Please follow instructions http://traccar.litvak.su/installation.html one more time and double check every step.

**Comment by ifindu-dk** [comment]
No it doesn't mean that !!!
I followed the instructions to the letter, so either are the instructions wrong, or you are wrong.

But i'm installing on an win-server 2008 v2 , and I believe that there can be a problem with the java classpath config.

**Comment by ifindu-dk** [comment]
Do you have a solution for a clean install with version 3.5 and with Mysql?

Or do I have to install the original, and then make all the modifications you have described?

**Comment by vitalidze** [comment]
> Or do I have to install the original, and then make all the modifications you have described?

Yes, you need to install original version of traccar and then make modifications per instructions. These instructions are correct, me personally followed them dozens of times and I know that many people done the same.

> But i'm installing on an win-server 2008 v2 , and I believe that there can be a problem with the java classpath config.

If you have the application running, then most probably you don't have any issue with classpath.

Again, have you dropped MySQL database created by the original version of traccar?

**Comment by ifindu-dk** [comment]
Well I followed the instructions very precisely...
So I don't think there are any problems in that setup.
(You could put an examplefile for the traccar.xml for the 3.5 version) so that we could compare with our own, or just use your example(with own modification in path)
The Mysql DB, has never been used, and is therefor totally empty - only DB-name is created

**Comment by ifindu-dk** [comment]
new DB, fixed the problem
