### ISSUE TITLE
How to show the aplication on webserver? under domainname

### ISSUE THREAD

**Issue by ifindu-dk** [vitalidze/traccar-web#748]
I can't figure out, how ro setup iis to work with the traccar-service

It's working fine on localhost:8082
But that's only the administrator of the server that has access and can see that.

I would like to have access through a domainname - just like https://d.traccar.litvak.su/ 

Im running windows 2008 server v2

**Comment by vitalidze** [comment]
First of all, please don't duplicate your questions.

Regarding your task, you have two options:

1) Configure your IIS server to be a reverse proxy for your traccar web server running on port 8082

2) Configure traccar to run on port 80, which obviously will require to stop IIS running on that port.

> But that's only the administrator of the server that has access and can see that.

If you are a server administrator then I guess you can set it up to open port 8082 on the network.

**Comment by ifindu-dk** [comment]
1: Sorry about that, I was writing in another way, because I was unclear in first Question!

Reverse proxy ?  maybe that will do - 

I can only see the service when logged in on server, and using the webservers browser :/
I t must be a permision-problem somehow.

But how can I run it as a public (traccar)server on the internet, if I wan't to use the windows-server i have allready in use?

What OS are you using yourself?

**Comment by vitalidze** [comment]
> Reverse proxy ? maybe that will do -
> 
> I can only see the service when logged in on server, and using the webservers browser :/
> I t must be a permision-problem somehow.

I think you should try using google search to look for an configuration of IIS. I doubt many people are using IIS for the traccar.

> But how can I run it as a public (traccar)server on the internet, if I wan't to use the windows-server i have allready in use?

You will need to have a public IP address for that.

> What OS are you using yourself?

On demo site there is an ubuntu linux 14.04. I have been using debian, centos, freebsd and windows 7 on other servers running traccar application. For reverse proxy I used mostly nginx, but apache will work too. Never used IIS, I don't know who and why should use this piece of ... software :)

**Comment by ifindu-dk** [comment]
Thanks a lot Vitalik
Reverse proxy is working nicely :)

IIS is use because i can run several domainnames etc. on same ip, and iis is the defacto standard in windows web server....
