### ISSUE TITLE
Remote Procedure Call error / Session Expired When Logging in the Administrator

### ISSUE THREAD

**Issue by nairazc621** [vitalidze/traccar-web#749]
There's a Remote Procedure Call error then followed up by Session Expired when i login the Administrator account. :(

Here is the wrapper.log

Any help will be appreciated, Thanks
![wrapper log error](https://cloud.githubusercontent.com/assets/13865157/16368452/f7ee959a-3c60-11e6-9676-f4a498557b89.jpg)

**Comment by nairazc621** [comment]
i'd just found out that some accounts are having the same issue too :(

**Comment by vitalidze** [comment]
According to the log your H2 database is damaged. You should NOT use it in production server, use H2 only for testing. I recommend using MySQL instead.

**Comment by nairazc621** [comment]
oh noo :'( 

is it still possible to recover fix it if i transfer it to mysql? :(

**Comment by vitalidze** [comment]
Well, both tasks are quite complicated. It would be much easier to start from scratch.

**Comment by nairazc621** [comment]
ok :(
thanks for your help vitali
