### ISSUE TITLE
Events and notifications

### ISSUE THREAD

**Issue by antoniopaisfernandes** [vitalidze/traccar-web#75]
The events table is getting populated and there's no user with notifications set.

The events should only be added if there's at least one active user consuming them. Or, instead, an application setting that shutdowns/starts the offlineDetector (EventServiceImpl).

By the way, as the events table grows (60k records) the java process (and mysql) starts hogging the CPU..

Best regards,
Antonio Fernandes

**Comment by vitalidze** [comment]
I have in plans to extend this functionality of events and notifications, so each device may have it's own event log (record engine start/stop, movement start/stop, etc.). So I believe it's better to leave it on for everyone. But maybe you are right and there should be an option to disable event logging at all (or per device).

High CPU usage is definitely an issue, actually I haven't got so many rows in that table on my servers. Why there are so many for you? Are you experiencing so many device outages? There must be a single record per device outage.

**Comment by antoniopaisfernandes** [comment]
At least full application on/off would be helpful.

Yes, I use traccar-web for 20 cars with GPS data and there's a problem with some (half) that, every minute, send same positions.
10 x (7AM->20PM = 13 hours) x 60 minutes = 7200 per day x 1 week = a lot of entries.

I should filter from the datasource so that the DB doesn't get redundant data (i'll do it anyway) but I found strange the high CPU and analyzing queries in the DB, found it was related to events...

BTW - my GPS data collector only gets data at work hours... so, by night, it's all devices being 'offline' x deviceTimeout

**Comment by vitalidze** [comment]
Well, this means ideally you should have a 20 events per day (or 140 per week). I still don't understand why you have so many events.

**Comment by antoniopaisfernandes** [comment]
I have 17 new entries in events table per minute from 7AM till 8PM:
![image](https://cloud.githubusercontent.com/assets/6171197/5955109/3da74d58-a797-11e4-8047-92ac1b22ddc3.png)

Browsing the code I see that they are placed there if the difference between the current time and the device's last position time is greater or equal to the device timeout (in seconds):
currentTime.getTime() - device.getLatestPosition().getTime().getTime() >= device.getTimeout() \* 1000

The device's timeout is 300 seconds (standard): 5 minutes
![image](https://cloud.githubusercontent.com/assets/6171197/5955159/d7b34ece-a797-11e4-9455-ee995e6d3d88.png)

This is the device's picture:
![image](https://cloud.githubusercontent.com/assets/6171197/5955174/fbbca22a-a797-11e4-8f9a-36632ee0f0d8.png)
I see (more or less, because they can be overlapped) 7 'red' (active) devices and 11 'white' (inactive).

My system works like this:
1. I have data of 22 devices collected every minute from 7AM till 8PM through an webservice the GPS provider supports
2. The data is feeded directly to the database adding a position entry and the updating the last position in the device's table
3. The data always comes with the last know position (it can be the same coordinates minute over minute and a new position id is added)

Summing all up, yes I do have a lot of offline/online so the feature of disabling this events would be a plus.

While writing this post, the last events id changed from 1285 to 1537 (+ 252 in a few minutes)
![image](https://cloud.githubusercontent.com/assets/6171197/5955277/40ce1992-a799-11e4-800f-42d713440001.png)

**Comment by vitalidze** [comment]
Added check box to the Global settings, hope you enjoy it :) Written [news](http://traccar.litvak.su/2015/01/29/ability-to-disable-event-recording.html), updated [article](http://traccar.litvak.su/features/notifications.html).

**Comment by antoniopaisfernandes** [comment]
Thanks, that helps :)
