### ISSUE TITLE
traccar service may have failed to start 

### ISSUE THREAD

**Issue by nairazc621** [vitalidze/traccar-web#750]
Hi everyone,

```
  My traccar service wont start after installing it(including vitali's version). it says"traccar service may have failed to start "
```

here are the wrapper logs

any help will be appreciated , thank you

![wrapper log new-1](https://cloud.githubusercontent.com/assets/13865157/16408692/836074a4-3d4c-11e6-9dcc-81b8374b50c7.jpg)

![wrapper log new-2](https://cloud.githubusercontent.com/assets/13865157/16408700/8dd362ca-3d4c-11e6-872e-5ec36e963090.jpg)

**Comment by vitalidze** [comment]
I think you made some typo when updating configuration file. Please double check all entries in configuration file.

**Comment by nairazc621** [comment]
Thanks, i accidentally removed some file in the traccar directory, I'm so stupid. lol
