### ISSUE TITLE
Problem not showing any device's position or state

### ISSUE THREAD

**Issue by samuelrojasp** [vitalidze/traccar-web#755]
Hi,

i implemented traccar ui, using the mods of the xml file. When using mysql it show an error "table traccar.server doesn't exist",  and it doesn't show devices positions.

However when changed it back to H2 database the problem desapeared. is there anything i may be missing with mysql? i'm using root user on mysql on a jboss google cloud server.

**Comment by vitalidze** [comment]
Do you see any error message in either `wrapper.log` or `tracker-server.log` files? Have you dropped database and disabled the database schema upgrade as per instructions http://traccar.litvak.su/installation.html before first start up of the service with web UI mod installed?

**Comment by samuelrojasp** [comment]
thanks for the answer..

i find this error in tracker-server.log WARN: No value specified for parameter 3 - SQLException (... < QueryBuilder:431 < DataManager:440 < DefaultDataHandler:27 < ...)

And the "table traccar.server doesn't exist" error found in the frontend logs.

I followed the instructions about dropped database with no results.

**Comment by vitalidze** [comment]
> WARN: No value specified for parameter 3 - SQLException (... < QueryBuilder:431 < DataManager:440 < DefaultDataHandler:27 < ...)

This means you have done some mistake during `traccar.xml` file update process. You need to double check all entries.

> And the "table traccar.server doesn't exist" error found in the frontend logs.

It can be safely ignored.

**Comment by samuelrojasp** [comment]
Respect to xml is there a way i can have a complete copy of xml as it has to be?

**Comment by samuelrojasp** [comment]
Another thing: i'm following the instructions for v. 3.5 is that right? how to ensure i'm using that version?

**Comment by vitalidze** [comment]
> Respect to xml is there a way i can have a complete copy of xml as it has to be?

No, there is no way. I don't want to share it because from my point of view it will cause more problems since the configuration file depends on OS and environment.

> Another thing: i'm following the instructions for v. 3.5 is that right? how to ensure i'm using that version?

Version is usually printed in the `tracker-server.log` file right after restart.
