### ISSUE TITLE
Ideal Pop with new imei

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#761]
My ideia is make a popup when nem imei has detected on logserver, with option, +add new vehicle or ignore..

It's possible @vitalidze ?

**Comment by vitalidze** [comment]
It's quite hard to implement because there is no trace of unknown devices on the server. It only posts a message to the log file and ignores further messages. So, the only option I can see at the moment is to parse log file. I don't think this will be implemented soon.
