### ISSUE TITLE
Minimum length password and user

### ISSUE THREAD

**Issue by 100n0m3** [vitalidze/traccar-web#762]
i've write some pice of code to implement a minimum leght of user and password somewone could just check if is ok?
im not a programmer but i think is right

`private boolean validate(String login, String password) {
        if (login);
        var loginCount = login.length;
        var pwCount = password.length; if (loginCount < 6) { alert("Login precisa de no mínimo 6 caracteres");
        } else if (pwCount < 6) { alert("Senha precisa de no mínimo 6 caracteres"); } else { alert("Cadastro realizado!");     } )
    }`

**Comment by vitalidze** [comment]
Well, I don't understand the purpose of this ticket. You better ask it on some programmer's forum, on stackoverflow for example.
