### ISSUE TITLE
I am not able to use api/session api.

### ISSUE THREAD

**Issue by rbniranjan** [vitalidze/traccar-web#765]
Hi Vitaly,

I am using your web UI for traccar server. Everything is working fine. I am able to create new user using web-UI. But when I try to access "api/session" (Traccar rest api) api with same credential that I am using for web login. It is given "Unauthorized" error.

can you please let me know. How can I fix it?

Looking forward your reply.

**Comment by vitalidze** [comment]
It's not compatible at the moment. You should use project's own api
http://traccar.litvak.su/features/rest-api.html

среда, 13 июля 2016 г. пользователь rbniranjan написал:

> Hi Vitaly,
> 
> I am using your web UI for traccar server. Everything is working fine. I
> am able to create new user using web-UI. But when I try to access
> "api/session" (Traccar rest api) api with same credential that I am using
> for web login. It is given "Unauthorized" error.
> 
> can you please let me know. How can I fix it?
> 
> Looking forward your reply.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/765, or mute the thread
> https://github.com/notifications/unsubscribe/ACMCNR4kKHdRSMS2pA2uVSoNsJCfKeoHks5qVP49gaJpZM4JLhCE
> .

## 

Kind regards, Vitaly Litvak

**Comment by rbniranjan** [comment]
Thanks for your reply.

Can I use "JSESSIONID"(That I will get using your rest api) in traccar server api for calling other api method?

**Comment by vitalidze** [comment]
Yes. You should be able to do that. You need to update all queries per
installation instructions in order to fix the permissions check on the
backend side.

среда, 13 июля 2016 г. пользователь rbniranjan написал:

> Thanks for your reply.
> 
> Can I use "JSESSIONID"(That I will get using your rest api) in traccar
> server api for calling other api method?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/765#issuecomment-232393746,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACMCNXAXwFldcEzMTWsD1Sd85aiMsRySks5qVQWFgaJpZM4JLhCE
> .

## 

Kind regards, Vitaly Litvak
