### ISSUE TITLE
Version 3.6 installation

### ISSUE THREAD

**Issue by vijaemanlapaz** [vitalidze/traccar-web#776]
Hi
i have downloaded the latest version of the from traccar.org and installed it on my system and run it without error or anything, then i tried to follow the installation instruction of your mod in you website
however i cannot login anymore from the login page just keep saying invalid username or password.

Can you help me set this up, this is exactly what i have been looking for.

**Comment by grafviktor** [comment]
Hi **vijaemanlapaz**
We're still beta testing traccar v3.6, please use a previous version of traccar for now. What do you mean by saying you cannot login **anymore**? Are you updating your installation from a previous version or you unable to login into traccar's native ui ?

**Comment by vijaemanlapaz** [comment]
@grafviktor 

Thanks for the reply.

No i am not updating from the previous version of traccar (3.5). I did a clean install of version 3.6, i logged  in as admin then stop the service, then downloaded the traccar-web.war from http://traccar.litvak.su/ then copy and paste it to the installation directory of traccar 3.6 then run the service opened up a browser and went thru localhost:8082 from the login page the admin account is not valid anymore just keep saying "Invalid username or password" something like that.

**Comment by grafviktor** [comment]
Please double check that you've updated `database.selectUsersAll` query in your `traccar.xml` configuration file according to the installation manual for v3.5. Please see [this page](http://traccar.litvak.su/installation.html). Version 3.6 is not officially supported yet, there are a lot more changes should be done in `traccar.xml` to get Traccar v3.6 and Traccar web UI working together, please follow our news.

**Comment by vijaemanlapaz** [comment]
Thanks @grafviktor got it to work..

**Comment by yonhing** [comment]
Hi, @vijaemanlapaz ; I also same problem with you, can you let me know how to solve it ? Thank you.

**Comment by vitalidze** [comment]
@yonhing I think you have missed the step which says to disable database schema updates by "backend" and to drop your existing database.

**Comment by yonhing** [comment]
the error log as below show...

2016-08-22 09:50:07  INFO: Character encoding: UTF-8 charset: UTF-8
2016-08-22 09:50:07  INFO: Version: 3.6-SNAPSHOT
2016-08-22 09:50:08  WARN: Error preparing query: Table 'databasename.server' doesn't exist - SQLSyntaxErrorException (... < QueryBuilder:380 < *:276 < DataManager:526 < PermissionsManager:76 < ...)
2016-08-22 09:50:08  WARN: Error preparing query: Table 'databasename.positions' doesn't exist - SQLSyntaxErrorException (... < QueryBuilder:380 < DataManager:521 < ConnectionManager:56 < ...)
2016-08-22 09:50:08  INFO: Starting server...

**Comment by vitalidze** [comment]
This log looks good. You can restart your server and the warning about `positions` table will be gone. The warning about `server` table will still be there, but it is absolutely safe to ignore it.

**Comment by yonhing** [comment]
I restart the server and the warning for positions not display , only the log file still have " Table 'databasename.server' doesn't exist"  and still can not login... check the MariaDB database the table content is  username admin password admin, but still can not login.

**Comment by vitalidze** [comment]
@yonhing I think you have missed something in configuration. You need to double check all steps.

**Comment by yonhing** [comment]
Ok, i will double check all steps. thanks
