### ISSUE TITLE
How to edit the page title?

### ISSUE THREAD

**Issue by tectonny** [vitalidze/traccar-web#779]
How to edit the page title?

```
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Traccar</title>
```

**Comment by vitalidze** [comment]
You can update `traccar.html` file inside `traccar-web.war`, which is an ordinary zip archive.

**Comment by tectonny** [comment]
Perfect, I did not know that could use winrar, can.

Solved, thank you.

**Comment by esurnet** [comment]
please where is located  this  traccar-web.war file?

**Comment by vitalidze** [comment]
@esurnet please don't resurrect old closed threads. Open new threads instead.

This project is the Traccar Web UI Mod, which contains UI code inside of `traccar-web.war`. Installation instructions are here http://traccar.litvak.su/installation.html 

So it seems that you are writing into a wrong issue tracker. Probably you should ask something here https://github.com/tananaev/traccar-web/issues instead.
