### ISSUE TITLE
Installation help traccar.xml lines missing

### ISSUE THREAD

**Issue by pmlewisuk** [vitalidze/traccar-web#783]
Hi 

trying to following the install instructions to upgrade to traccar-web but bits are missing from traccar.xml - instruction number 4.2 & 4.3 arn't in my xml - Help

Regards

Mark

**Comment by vitalidze** [comment]
Which version of traccar are you running?

**Comment by pmlewisuk** [comment]
Hi Vitalidze,

thanks, I think I've been daft as I'm using 3.5 so those lines aren't required ..... commented out

Regards

Mark
