### ISSUE TITLE
Calculation for quantity device.

### ISSUE THREAD

**Issue by tectonny** [vitalidze/traccar-web#785]
Is there any formula to know how many crawlers can use the system.
Example for a VPS 1Gb how many devices can I track?

**Comment by vitalidze** [comment]
There is no formula. It depends on many parameters such as frequency of reports coming from your devices. Also geo-fences and other events may increase the load on your server. You can use search in this issue tracker, on [backend issue tracker](https://github.com/tananaev/traccar/issues) and on [backend forums](https://www.traccar.org/forums/) for the same questions. It was asked dozens of times.
