### ISSUE TITLE
traccarweb and traccar3.6 -> installation OK

### ISSUE THREAD

**Issue by flyjodel** [vitalidze/traccar-web#797]
Hi Anton,

i've freshly installed a VPS with : 
- debian 8 x64
- java 8
- traccar 3.6
- mysql database
- this fork of the project

everything runs smoothly, no problem at all after the first tests with one device.
if needed, i've taken notes of the installation process, just the requested steps.
regards !

**Comment by vitalidze** [comment]
Well, thank you for reporting. There is no Anton here, my name is Vitaly ;) You could send it by email, since you don't have any issues.

**Comment by flyjodel** [comment]
Vitaly, sorry !!!!! I was on Anton's website at the same time, that's why, sorry again, and you've done a great work, as usual ;)
