### ISSUE TITLE
Cant add notification server

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#80]
Notification does not work with microsoft mail address:
From:email@hotmail.com
Server:smtp-mail.outlook.com
Port:587

**Comment by vitalidze** [comment]
You should check `wrapper.log` file for error message description. Most probably you must enable third-party application access to your google account in preferences.

**Comment by connectnet** [comment]
ok. I will see. thank you!

**Comment by connectnet** [comment]
Strange. Test was ok but I never get an email.

**Comment by vitalidze** [comment]
Test itself does not send email, it just checks connection. Email is sent only when some device goes offline and there is a user that wants to receive notifications.

**Comment by vitalidze** [comment]
You should look into `wrapper.log` for additional information about notifications sending.

**Comment by connectnet** [comment]
Fixed. I have to checked "STARTTLS". (The test without "STARTTLS" seems ok)
Thank you again!
