### ISSUE TITLE
Web UI Shows incorrect Ignition status 

### ISSUE THREAD

**Issue by sulfy** [vitalidze/traccar-web#809]
Dear @vitalidze @tananaev 
Tracer Web UI Shows **ignition = FALSE** when ACC is ON 
and  **ignition = TRUE** when ACC is OFF .

Please help.

**Comment by vitalidze** [comment]
This sounds like in issue with protocol implementation. Please ask on the backend project issue tracker: https://github.com/tananaev/traccar/issues

**Comment by tananaev** [comment]
The issue is already solved:

https://www.traccar.org/forums/topic/traccar-ignition-status-shows-wrong-info/

**Comment by vitalidze** [comment]
@tananaev ok, thank you :)
