### ISSUE TITLE
How to set address active from source and dissable lat and long

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#81]
Where I can find to set the address active in the source code?

**Comment by vitalidze** [comment]
To fill address column you should use reverse geocoding. Here is todays thread discussing this https://github.com/tananaev/traccar/issues/1058

**Comment by connectnet** [comment]
Thats what I know and it works well. But want that the "address" box is checked from source code.

**Comment by vitalidze** [comment]
If you want to see it in archive there is a drop down in each column of table header. 'Address' column is hidden by default, but you may unhide it using that drop down menu. See this page http://traccar.litvak.su/features/address-column-in-archive-grid.html for additional info

**Comment by connectnet** [comment]
And I want the 'Address' column active by default and 'Latitude' and 'Longitude' hidden.
Where I change it in the source code?

**Comment by vitalidze** [comment]
These settings are stored in database. Every newly created user will get 'valid' and 'address' column hidden, which is hard coded in this constant field https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/shared/model/UIStateEntry.java#L25

``` java
public static final String DEFAULT_ARCHIVE_GRID_STATE = "{\"hidden\":[\"valid\",\"address\"]}";
```

I think you should put there something like:

``` java
public static final String DEFAULT_ARCHIVE_GRID_STATE = "{\"hidden\":[\"valid\",\"latitude\",\"longitude\"]}";
```

Then you may want to update existing users records in `ui_state` table.

**Comment by connectnet** [comment]
Perfect!!! Thanks a lot!

**Comment by mohsinknsd** [comment]
Excuse me sir @vitalidze 
I have no such option to show address in archive panel.
Have a look on the snap...
![column list](https://cloud.githubusercontent.com/assets/10682808/6035500/aa969708-ac5a-11e4-8686-4d21446f7ad5.png)

**Comment by vitalidze** [comment]
Then @khansquare you most probably have default version of trraccar web UI installed. Please follow [these instructions](http://traccar.litvak.su/installation.html) to install my version of web UI, which contains address column in archive table and other [features](http://traccar.litvak.su/features/).

**Comment by mohsinknsd** [comment]
Okay thank your sir. :+1:

**Comment by connectnet** [comment]
Strange. The columns are hidden now but  small 'Latitude' and 'Longitude' are already shown:

![bildschirmfoto vom 2015-02-04 17 29 51](https://cloud.githubusercontent.com/assets/8360383/6045381/fa1f512c-ac99-11e4-8f9f-3d0997aaff12.png)

**Comment by vitalidze** [comment]
This is an issue in GXT library that is used for the UI, I have posted it a while on their forum, but no reply: http://www.sencha.com/forum/showthread.php?296644-Hidden-columns-state-in-grid-is-loaded-incorrectly
