### ISSUE TITLE
configure MySQL

### ISSUE THREAD

**Issue by tectonny** [vitalidze/traccar-web#810]
Can anyone help me set up Mysql?

It works well in clean traccar, but after I upgrade to traccar-web I get the following message:
503 - Service Unavailable

**Comment by vitalidze** [comment]
I think you missed the step, which says to drop database and disable database schema updates.

**Comment by tectonny** [comment]
Where has this please step

**Comment by vitalidze** [comment]
You need to read installation instructions carefully: http://traccar.litvak.su/installation.html It is present there.

**Comment by tectonny** [comment]
Sorry, but that part is not clear.

Should I just delete the database and create again?

**Comment by tectonny** [comment]
It seems to work removing the bank and creating a void.
I am sure?

**Comment by vitalidze** [comment]
You need to have blank database before the first start. You can either drop all tables one-by-one or drop entire database and create it again.

**Comment by tectonny** [comment]
Solved

**Comment by akmal1999** [comment]
Hi Techonny,

Would you please send steps you took to implement mysql i am stuck with that too.
