### ISSUE TITLE
MapQuest layer

### ISSUE THREAD

**Issue by mpele** [vitalidze/traccar-web#817]
Just to mention - MapQuest tiles are not available as it was. On Monday, July 11, 2016, direct tile access to MapQuest legacy maps was discontinued.

**Comment by vitalidze** [comment]
Thanks for the information. Looks like there is no solution for the MapQuest maps and they are subject to be removed in next release of this project.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
