### ISSUE TITLE
Help with a map design

### ISSUE THREAD

**Issue by tectonny** [vitalidze/traccar-web#818]
I would use the function for auto login already implemented by vitalidze.

And after the auto login point to a page with only the map with the device selection and command.

I thought of using the mobile version, but this version is not with Google Maps.

You can clone the mobile page with google maps?

**Comment by vitalidze** [comment]
The mobile version will use google maps if you select them in the user's profile as the default mapping provider.

**Comment by tectonny** [comment]
True, sorry to nonchalance.
