### ISSUE TITLE
requests per seconds

### ISSUE THREAD

**Issue by zzyber** [vitalidze/traccar-web#821]
Hi!

We have had problems with reverse geocoding since we opened our platform and our solution was to install and manage our own nominatim server. Now we really would like to buy this service instead and I wonder how we can measure request/day and requests/second in the system? 
Any suggestion to a really good geocoding service at a low price out there? We are looking at OpenCage and I´m trying out the free alternative for now.

**Comment by vitalidze** [comment]
You need to calculate the number of positions you receive within one day. I think this can be easily done with some SQL query. This will give you approximate number of requests per day. I know that traccar "backend" caches requests by longitude/latitude, which means if you have several positions with EXACTLY same longitude/latitude it will save you a query. However, I believe this is a rare case, so I would not rely on this. Also it may be worth to ask on the "backend" issue tracker here: https://github.com/tananaev/traccar/issues

**Comment by tectonny** [comment]
Hello zzyber, I am also wanting to create my own nominatim server.
But no success.
I tried VPS with 2Gb memory, I tried with ubuntu or hundreds, but everyone always gives errors.

Could you tell me the steps I followed to install your?

I appreciate any help.

**Comment by zzyber** [comment]
Hi Tectonny!
It´s a bit tricky if you ask me but it´s doable. As you may know there is a lot of non working tutorials out there but i found this: http://koo.fi/blog/2015/03/19/openstreetmap-nominatim-server-for-geocoding/ that is a good instruction to go with.
