### ISSUE TITLE
About Double login and snap to roads

### ISSUE THREAD

**Issue by ilijaoh** [vitalidze/traccar-web#822]
I have installed traccar version 3.6 with your beta UI on for that version and it works on ubuntu 16.04 VPS but i have some strange problem. 
1. When i log in e.g user: admin pass: admin it not goes to to the map but login window disappear so i need to make refresh page or F5 to go in... and its working (all the case with all users), (This is case and for other version than 3.6 (only traccar and also with web UI)
2. Option Snap to roads not working i have tried with more than 100 points and only with 5 points but every time when i add option Snap to roads  the route disappear... 
   Does this is only for this beta version problem? because i haven't installed another version just 3.6

**Comment by vitalidze** [comment]
> When i log in e.g user: admin pass: admin it not goes to to the map but login window disappear so i need to make refresh page or F5 to go in... and its working (all the case with all users), (This is case and for other version than 3.6 (only traccar and also with web UI)

Well, I know several users complain about this issue. I am unable to reproduce it. Looks like something is wrong with the javascript, but it works fine on all server, where I have access to. If possible, please give me access to your server. You can send me an email with credentials of test user.

> Option Snap to roads not working i have tried with more than 100 points and only with 5 points but every time when i add option Snap to roads the route disappear... 
> Does this is only for this beta version problem? because i haven't installed another version just 3.6

The 100 points is the restriction from the third party data provider (OSRM). If your track has more than 100 points, then you should get an error. If it disappears then something went wrong, maybe there is a proxy server issue, I don't know. You should check web browser console for error messages.

**Comment by linkintegrated** [comment]
I have the same issue with Snap to roads using the beta version. Using either https://router.project-osrm.org/match server or my own hosted server with OSRM. Once I tick snap to road the route disappears. If I do a small distance 5 points when I snap to road it works.

**Comment by ilijaoh** [comment]
i think i found the log that you need ?
this is from chrome console F12 log

Uncaught TypeError: Cannot read property 'length' of undefinedBtd @ traccar-0.js:7116$s @ traccar-0.js:5073mt @ traccar-0.js:7106(anonymous function) @ traccar-0.js:4728gj @ traccar-0.js:3360jj @ traccar-0.js:4603(anonymous function) @ traccar-0.js:5803

**Comment by mpele** [comment]
> When i log in e.g user: admin pass: admin it not goes to to the map but login window disappear so i need to make refresh page or F5 to go in... and its working (all the case with all users), (This is case and for other version than 3.6 (only traccar and also with web UI)

I would like to add that, in my case, "double logging" is needed only first time after the browser is started. After that it works as expected. 
I have recently reinstalled system, I am not sure but I think that it worked normally after reinstallation.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
