### ISSUE TITLE
Mail notification settings test failed - 3.6 Beta

### ISSUE THREAD

**Issue by plomac** [vitalidze/traccar-web#823]
Hello, 
I have an issue with mail notification : the settings test failed with 500 internal server error, the call failed on the server.

Versions :
Ubuntu Desktop 16.04 LTS
Traccar 3.6
Web UI 3.6 Beta

It isn't a communication or setting problem, Thunderbird mail is working with same smtp settings. Send and Receive tested.

From wrapper.log :
INFO   | jvm 1    | 2016/08/25 09:38:38 | INFO: Sending Email notification to 'MAIL@ADDRESS'...
INFO   | jvm 1    | 2016/08/25 09:38:38 | Aug 25, 2016 9:38:38 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/08/25 09:38:38 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2016/08/25 09:38:38 | javax.mail.MessagingException: Could not connect to SMTP host: XXX.XXX.XXX.XXX, port: 143, response: -1

I have no trace of incoming connection in the maillog mail server.

Do you have an idea how I can solve this or what to look at ?
Thanks

**Comment by vitalidze** [comment]
This sounds like a networking issue. I recommend to set up your ubuntu OS to send messages from command line (i.e. via `mail` application). After that you should be able to set up traccar to send messages too.

**Comment by vitalidze** [comment]
Are you sure that settings are absolutely same? Port 143 looks weird.

**Comment by plomac** [comment]
You're wright, 143 is IMAP protocol, not SMTP.
It does work for a mail client but not for telnet test or Traccar which is using smtp.
Once corrected to port 25 and SAVE, everything is working.
Thank you
