### ISSUE TITLE
Position of History

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#83]
hello with the new interface queries the historic tripled the time and often not consultation , please could help me .

**Comment by vitalidze** [comment]
Are you using archive filtering? If not then the only thing that may affect performance is distance calculation. How many positions does your query return?

**Comment by MarceloMJM** [comment]
The consultation is being done without filters.

Over 55 positions is very slow .

With the old interface was the same queries very quickly almost instantaneous .

**Comment by vitalidze** [comment]
Well, I have no idea what could be the issue. Just checked demo server and it loads 50 positions in an instant. Maybe it's a database engine issue? Are you using MySQL?

**Comment by vitalidze** [comment]
My demo server is the cheapest virtual machine instance running single core with 512MB of RAM. And I am using MySQL.

**Comment by MarceloMJM** [comment]
Yes mysql
Ex: if I do a query of the last two hours is fast return if I increase the time delay is too much .

My server is with 3 MB of ram .

**Comment by vitalidze** [comment]
Can you confirm that query is running fast? To check that can connect to your server using `mysql` command line client and run following query:

``` sql
SELECT * FROM positions WHERE device_id=7 AND time BETWEEN '2015-02-04 10:00:05' AND '2015-02-04 11:00:00'
```

Replace time interval and device id with your data. At the end of result set MySQL will print query execution time. If it runs fast then it's a web UI issue, if slow then you have to do something with your MySQL instance (start with checking indexes on `positions` table, there should be an index on `(device_id, time)` columns).

**Comment by MarceloMJM** [comment]
Mysql query result

19:07:46    SELECT \* FROM positions WHERE device_id=3 AND time BETWEEN '2015-02-04 10:00:05' AND '2015-02-04 11:00:00' LIMIT 0, 1000    124 row(s) returned 0.000 sec / 0.000 sec

**Comment by MarceloMJM** [comment]
Query 5 hours.

19:08:13    SELECT \* FROM positions WHERE device_id=3 AND time BETWEEN '2015-02-04 06:00:05' AND '2015-02-04 11:00:00' LIMIT 0, 1000    387 row(s) returned 0.000 sec / 0.000 sec

**Comment by vitalidze** [comment]
Well, it looks like it's not a MySQL issue. Then can you switch back (temporarily) to the default version of traccar web UI and confirm that same queries are working with acceptable timing?

**Comment by MarceloMJM** [comment]
Old web interface

19:36:56    SELECT \* FROM positions WHERE device_id=3 AND time BETWEEN '2015-02-04 10:00:05' AND '2015-02-04 11:00:00' LIMIT 0, 1000    124 row(s) returned 0.000 sec / 0.000 sec

19:39:14    SELECT \* FROM positions WHERE device_id=3 AND time BETWEEN '2015-02-04 06:00:05' AND '2015-02-04 11:00:00' LIMIT 0, 1000    387 row(s) returned 0.016 sec / 0.000 sec

**Comment by vitalidze** [comment]
Next step is to profile it using your web browser tools. Google chrome has built-in profiler in More tools >> Developer tools menu. Please run recording while loading positions (Profiling >> CPU and Timeline), then send results by email (in CPU there will be a "Save" link, and in Timeline right click on Graph and choose "Save timeline data..." from context menu).

**Comment by MarceloMJM** [comment]
good morning

Follows as requested , so need is ask.
Date: Wed, 4 Feb 2015 23:56:37 -0800

**Comment by vitalidze** [comment]
Please send an email to me (email is in github profile) because github issues don't support attachments.

**Comment by vitalidze** [comment]
I can see frequent timer removal and installation events in timeline logs. Looks like you have changed the "Update interval" setting to the very small value. What is the current value?

**Comment by MarceloMJM** [comment]
Forgive me I did not understand , this update interval you referred to the device ?

**Comment by vitalidze** [comment]
It's a setting in web UI in Settings >> Global menu.

**Comment by MarceloMJM** [comment]
ok this interval 15000 , I remember having changed.

**Comment by vitalidze** [comment]
Please leave it with 15000 and try loading your positions from archive again. If it's still slow then please record another timeline and send it to me by email.

**Comment by MarceloMJM** [comment]
Hello , thank you for your commitment I think we can put an end to this matter, since after the creation of a new administrator account consultations are going well.
once again thank you and congratulations for the great job.

**Comment by vitalidze** [comment]
Awesome. You are welcome!
