### ISSUE TITLE
MapQuest is not operational

### ISSUE THREAD

**Issue by dinamic** [vitalidze/traccar-web#832]
MapQuest whether Aerial or Road is not operational on the demo.

I would presume it does not work. It says direct tile access has been disabled.

**Comment by vitalidze** [comment]
Yes, I know about this. It was already reported in #817. Please use search before posting your own threads.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
