### ISSUE TITLE
Snap to roads not working

### ISSUE THREAD

**Issue by sankalpask** [vitalidze/traccar-web#833]
Hi,
I have tried to get device route with snap to roads enabled, there's an error message coming "'Error loading track snapped to roads (400): {"status":400,"status_message":"Too many coordinates"}".
How can I solve this issue?

**Comment by vitalidze** [comment]
There is a restriction on the number of coordinates per each request (100 - one hundred), which comes from the data provider (project OSRM). So if your track has more than 100 points then this function will not work.

**Comment by sankalpask** [comment]
can I customize the parameters name that parsing to snap to roads? 
as example the system is parsing Latitude and longitude as "loc", can i change that to "path".??
(eg : path=60.170880,24.942795|60.170879,24.942796|60.170877,24.942796)

I'm trying to use google snap to roads.

**Comment by vitalidze** [comment]
It will not work if you just change the request parameters and URL. Google's response is different than the one from project-osrm. Also google has restriction on 100 points per request as the project-osrm does. Currently I don't know a good way to solve it.
