### ISSUE TITLE
Official traccar not applied litvak changes

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#836]
We compile litvak traccar in Intelij IDEA IDE and make some changes like color, buttons' location etc.. So when we executed it at Intelij Idea it work perfectly, but when we install it in traccar org with got problem.
So first screen we see compiled project at Intelij Idea
![before](https://cloud.githubusercontent.com/assets/14888435/18233448/4ab5352a-72f0-11e6-8f65-a07250ea45e7.png)
 And second is traccar-web.war pasted in traccar org
![after](https://cloud.githubusercontent.com/assets/14888435/18233450/5050b34c-72f0-11e6-9688-4d11cb6866de.png)
Can anybody help us? Thanks

**Comment by vitalidze** [comment]
How do you build project? You need to build it with maven. Then you need to clean up web browser cache after each re-deployment to be sure that you are using latest version.

**Comment by ghost** [comment]
I made all changes that i want in litvak WebUI in Intelij IDEA. After this i build project same as at this link http://traccar.litvak.su/building.html. Then i clear all browser history and .war file in traccar org. Finally I pointed the way to the folder in conf\traccar.xml as i saw in http://traccar.litvak.su/installation.html

**Comment by vitalidze** [comment]
I think you made these changes improperly. How did you made them?

**Comment by ghost** [comment]
Some changes in java code some changes with color in traccar.html like .com-sencha-gxt-theme-neptune-client-base-panel-Css3ContentPanelAppearance-Css3ContentPanelStyle-header {
        background: linear-gradient(to bottom, #F5F5F5 0%, #F5F5F5 100%) !important;
      }

**Comment by vitalidze** [comment]
These CSS changes will not work because during compilation all class names are changed. You need to work with GXT appearance: https://docs.sencha.com/gxt-guides/3/ui/theme/Themes.html

**Comment by ghost** [comment]
Thanks!
