### ISSUE TITLE
Presentation mode 

### ISSUE THREAD

**Issue by dudek-marcin** [vitalidze/traccar-web#84]
Hello, it would be nice feature, to add something like presentation mode (or account type), so it will show only map. Or let the bottom and left side panels to be hidden (now they are seizable, but can't be seized to just line). I would like to show it on big screen. Actually, it can be achieved using mobile version, but there is only open street map avaible.

**Comment by vitalidze** [comment]
Mobile version contains all maps from desktop version. You can switch them in user's preferences (Settings » Preferences). Then you need to refresh mobile version and it will load proper map.

**Comment by vitalidze** [comment]
I believe mobile version works for such case along with recently introduced 'read-only' users feature (and auto-login if necessary), so I am closing this issue.
