### ISSUE TITLE
installation this version

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#842]
Is this version of supposed to be an addition to the original traccar or a different one. I am trying to install this from scratch, however, wanted to make sure I am on the correct path.

**Comment by vitalidze** [comment]
This version installs over original traccar and the main goal is just to replace the web UI. The original traccar server functionality is then limited to only collect data from devices. All features list is here: http://traccar.litvak.su/features/

P.S. please don't duplicate your questions, especially in the old threads not related with your clause (like #25)

**Comment by wilderkaiser** [comment]
Hello, i am little bit confused after reading the statement; @vitalidze: you wrote that after insalling this mod, collecting data is only possible from devices ... So if that, isnt OsmAnd Web Tracking (via Port 5055) longer supported ? Hope that i´m misunderstanding this :-) By the way let me say THANK YOU for this great MOD :-)

**Comment by vitalidze** [comment]
@wilderkaiser all devices, which are supported by traccar (see this list https://www.traccar.org/devices/) will be supported after installing the web UI Mod over traccar.
