### ISSUE TITLE
Issue upgrading to this version that you have.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#844]
I tried to follow your installation method and missed up the original installation.  I would say it would be better to build the xml off of the steps you have made and replace the xml in base system. I have done this could you check if this looks good to you...
[traccar.zip](https://github.com/vitalidze/traccar-web/files/468740/traccar.zip)

when I did this and followed your installation instraction it totally broke the origional installation and had to remove everything and install the https://github.com/tananaev/traccar/releases/tag/v3.7  64 bit linux  am i doing it wrong?

**Comment by vitalidze** [comment]
> I would say it would be better to build the xml off of the steps you have made and replace the xml in base system. 

The configuration file depends on environment and also there can already be some changes, which should not be overwritten. The only thing that can be improved here from my point of view is to add some kind of script, which will update it automatically, which is in plans.

> I have done this could you check if this looks good to you...

You can check it by yourself. All entries are available in installation instructions.

> when I did this and followed your installation instraction it totally broke the origional installation and had to remove everything and install the https://github.com/tananaev/traccar/releases/tag/v3.7 64 bit linux am i doing it wrong?

The 3.7 version is not yet supported. Please use 3.6 or lower.

**Comment by akmal1999** [comment]
Hi Vitalidze,

My bad I meant 3.6, however noticed the 3.6 does not have the file you are referring.  traccar-web.war so I didn't have to remove it... is that normal.

**Comment by vitalidze** [comment]
Yes, it is normal. The `traccar-web.war` file is not included in installation since 3.x version of traccar.

**Comment by akmal1999** [comment]
Thanks
