### ISSUE TITLE
mysql database

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#848]
Hi,

Has anyone made a mysql database for this web could you share it? Ofcourse your xml file as well without pass and user id... I am stuck transitioning from h2 to mysql.... if any instraction will appreciate that.

**Comment by halie412** [comment]
Hello if is a blan installation of traccar only need make empity database and in your traccar.xml change few lines like:

<entry key="database.driver">com.mysql.jdbc.Driver</entry>
<entry key="database.url">jdbc:mysql://127.0.0.1:3306/--database--?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key="database.user">--user--</entry>
<entry key="database.password">--pass--</entry>

**Comment by halie412** [comment]
Hello if is a blan installation of traccar only need make empity database and in your traccar.xml change few lines like:
`<entry key="database.driver">com.mysql.jdbc.Driver</entry>
<entry key="database.url">jdbc:mysql://127.0.0.1:3306/--database--?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key="database.user">--user--</entry>
<entry key="database.password">--pass--</entry>`

**Comment by vitalidze** [comment]
You should update your configuration file according to the official documentation: https://www.traccar.org/mysql/

**Comment by akmal1999** [comment]
Thanks Halie412 and Vitalidze, 

I have created the mysql db and then added all the info in traccar.xml and commented out the H2,

however, when open MySQL through MYPHPadmin I see the database is absolutely empty. How can I make sure the website uses MySQL database other than xml parameter.. my site still works when I stopped and started traccar however, I don't know if still uses H2 or mysql.. any feedback will be appreciated.

thanks
AK

**Comment by vitalidze** [comment]
There should definitely be some tables in your database. To make sure which one is used you can look for a similar line at your `wrarpper.log` file right after you start it:

```
INFO   | jvm 1    | 2016/09/16 07:11:12 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9jdtsagb1m38qzx|163da81, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9jdtsagb1m38qzx|163da81, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
```

It describes your connection settings. There are at least two notable things related to the mysql configuration:
- `driverClass -> com.mysql.jdbc.Driver`
- `jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8`
