### ISSUE TITLE
Upload personal placemark

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#85]
It would be nice to upload an own placemark e.E. an own picture.
Is it possible?

**Comment by vitalidze** [comment]
It is possible and I have this in plans. Right now you can replace pictures in `traccar-web.war` file in `img` subfolder, but picture size should be exactly same. Or you may need to update it in code and rebuild the .war file.

**Comment by bigoss** [comment]
wow this is good and easier than with with original tracer web where i had to replace links to remote open layers images

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/06/09/major-changes-to-devices.html), updated [article](http://traccar.litvak.su/features/change-device-icon.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
