### ISSUE TITLE
How to change traccar OpenStreetMap to Google Api key map.?Step By Step.

### ISSUE THREAD

**Issue by sdip025** [vitalidze/traccar-web#852]
I wants to setup traccar .for that i wants to change OpenStreetMap to google api key ..Please tell me the following steps which i need follow.

**Comment by vitalidze** [comment]
You can read #754 about this task. Also have you tried using search before posting your own question?

**Comment by sdip025** [comment]
I have only changed<  script async defer src="https://maps.googleapis.com/maps/api/js?key=Mykey&callback=initMap"
type="text/javascript >< / script > and put my own key.in traccar.html. what is the others steps?

**Comment by vitalidze** [comment]
If you have updated it inside `traccar-web.war` file then you don't need anything more to do.

**Comment by sdip025** [comment]
Thanks for reply.If you don't mind .i need more help.i have cloned this from https://github.com/vitalidze/traccar-web.git in my NetBeans.After That i modify this script.If you help me how i will update inside  traccar-web.war then what i will do as per your guides..or how to do in netbeans.please reply.I am using 3.6 version.how to get the war file.

**Comment by vitalidze** [comment]
You can build the `traccar-web.war` file by following official instructions: http://traccar.litvak.su/building.html

From NetBeans you can simply run `package` maven task.

**Comment by akmal1999** [comment]
Hi Vitalidze,

source code for traccar installation does not carry traccar-web.war for 3.7
correct? I do not see this file in /opt/traccar folder.

**Comment by vitalidze** [comment]
@akmal1999 yes, that's correct. No `traccar-web.war` is included since version 3.x

Please **stop** posting your questions in random threads. Otherwise you will be banned and your messages will be deleted.
