### ISSUE TITLE
traccar on Linux Mint

### ISSUE THREAD

**Issue by Alfa115** [vitalidze/traccar-web#853]
Hallo there,
I'm using traccar since about a half year on a raspi, it works quite fine, but - because of the raspi's low performance, its slow in loading tracks and creating export-files. So I decided to bring the installation on an Linux Mint PC. 
In addition to traccar server I use the Livtak mod, maybe this is part of my problem. I use the latest traccar version (3.6), that is not yet officially supported.
My Problem
- I can't create groups, there is an error Prozedurfehler bei Aufruf / Remote procedure call error
- There is no data for the selected device   No results found for selected period

I use the database, that ist installed, when you don't do any changes, that should be H2 database, I deleted the content of the folder data, like described in the installation manual, I'm sure the portforwarding is correct, I can't fin any difference to the installation on the raspi.

Is there any idea, what's the problem?

regards
Peter

**Comment by vitalidze** [comment]
It sounds like a configuration issue. Have you disabled the database schema upgrades as said in instructions for the 3.5/3.6?

Also, I highly not recommend using H2 database in production system. Use MySQL instead.

**Comment by cdmarioe** [comment]
Downgrade to 3.5 Version, i had the same problem with 3.7 ....3.5 works fine.

**Comment by cdmarioe** [comment]
I tried 3.7. 3.6 and i had the problem when i migrate to mysql (Remote procedure call error on create groups, It did not generate tables), in H2 works fine, I guess there are an problem with the script, or something else, i have running 3.5 with mysql ok.

**Comment by Alfa115** [comment]
this is what I suspected. It's an easy thing to delete and reinstall the traccar. I was not sure, if the problem is the difference between a PC and the raspi. Indeed for installing the raspi i followed the instruction for an ubuntu PC.
This way doesn't satisfy but it's a way.

Thanks for this information

**Comment by Turbovix** [comment]
Dear due to problem in Mysql database with error (NO_ZERO_DATE) suriro to add the following statement in the configuration line, as shown below.

**&sessionVariables=sql_mode=''**

`<entry key='database.url'>jdbc:mysql://localhost:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>`
