### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by wilderkaiser** [vitalidze/traccar-web#857]
Hello, i have installed Traccar 3.7 for x64 on WindowsServer2012.

Everything was working very fine. After updating to your MOD, step by step custom changes of traccar xml and removing the H2 database files (after terminating Java.exe) ... i got a 503 - Service not available error. Logfile is here: http://ge.tt/3A3RObe2

There are some SQL errors :-( After replacing all files to the original version everything is working again :-)

Can you please take a closer look? Whats wrong here?

Kind regards from Austria

Joerg

**Comment by vitalidze** [comment]
You are installing it over 3.7 version of traccar, which is not yet supported. Please use 3.5 or 3.6 instead.

For the `503 - Service not available` it's better to look at the `wrapper.log` file for error messages.

Also I highly not recommend using H2 database in production system. Use MySQL instead.

**Comment by wilderkaiser** [comment]
I see :-) V.3.7 Thanks for serving me and also for this great work!! I try and be back soon :-)

**Comment by wilderkaiser** [comment]
I installed 3.5 and also 3.6 ... same procedure - same error :-( maybe i have something done wrong in traccar.xml. Can you provide me with a working file? mySQL before or after migrating the MOD?

**Comment by vitalidze** [comment]
I cannot provide a working file because it depends on your environment. You should double check all entries and also make sure that you have dropped database and disabled schema upgrades before first start. Then you need to check `wrapper.log` and `tracker-server.log` files for error messages.

>  mySQL before or after migrating the MOD?

I recommend to set up MySQL before migrating. This way your new instance will be ready to use once it is up and running.

**Comment by wilderkaiser** [comment]
not successfull :-( 
3.5 .. plain working - with mod :-(  failed
3.6 .. plain working - with mod :-(  failed

3.7 .. plain working - with mod :-) BUT ... no Device displayed that worked with plain installation.

Can anyone please help me? Teamviewer? Please ... 

logfile contains some sql errors (like the installations before) http://ge.tt/1sT0r8f2

**Comment by vitalidze** [comment]
You can contact me by email to discuss options of helping you.

> logfile contains some sql errors (like the installations before) http://ge.tt/1sT0r8f2

This web site is considered "harmful" by chrome. It does not let me download your log file.

**Comment by wilderkaiser** [comment]
Really nice your offer; i see -> new to me that logfiles are a risk :-(

I send mail :-) Thanks again for serving me :-)
