### ISSUE TITLE
Load a lot hours

### ISSUE THREAD

**Issue by leontino** [vitalidze/traccar-web#87]
Hi dear, when I put the platform to load of 10:00 AM to 22:00 PM, the page don't  load. This problem is in my virtual host with lazy memory or the script ?

**Comment by vitalidze** [comment]
I am running latest available version on d.traccar.litvak.su, which is a minimal virtual machine instance with 512MB and single core processor. On my macbook air (core i5, 8GB of RAM) it took about twenty seconds to load 10582 positions for five days (23 Jan 2015 to 28 Jan 2015) in google chrome web browser. So the problem maybe both on your server and your client.  I suggest to try running same query on another machine or another web browser. 

Also there is an issue #83, which looks like to be on client-side, but I am still working on it.

**Comment by leontino** [comment]
Thanks Dear. I go try it

**Comment by vitalidze** [comment]
Latest version should perform a bit better in terms of loading big number of archived positions. It's worth to give it a try.

**Comment by vitalidze** [comment]
Does problem exist anymore? BTW, I have added several performance improvements in recent version, I recommend trying it.

**Comment by leontino** [comment]
Nice dear, I GO see! And the project of geofence?
Em 17/03/2015 16:58, "Vitaly Litvak" notifications@github.com escreveu:

**Comment by vitalidze** [comment]
Geofences are still in progress. I will post news here http://traccar.litvak.su/news.html and update issue #100 once it's done.

**Comment by MarceloMJM** [comment]
Ola, Leontino tive o mesmo problema com as consultas, o problema estava em meu servidor ainda não sei alcerto o que é, mas a solução foi abrir uma nova conta de administrador  agora esta tudo correndo bem.

Att Marcelo.

**Comment by vitalidze** [comment]
Any update on this issue?

**Comment by MarceloMJM** [comment]
but in my case was normalized with the opening of new administrator accounts.

**Comment by vitalidze** [comment]
Dear @leontino, what about your issue with loading lots of hours?

**Comment by vitalidze** [comment]
I have found two bottlenecks, which work slow:
- archive grid - even if I disable drawing of map it is filled very slowly when number of records grows. Maybe 'paging' may help.
- drawing of markers. If I disable these then it is drawn very quickly for one of my devices even for a monthly history. Long time ago I thought about replacing markers with circles drawn with vector graphics, which may work much faster.

First one with archive grid should be fixed in latest release. Please give it a try.

**Comment by vitalidze** [comment]
@leontino @Marcelomjm Latest version should perform much better when loading large number of positions. Please give it a try and report if it works for you

**Comment by leontino** [comment]
Minha versão está ok. Marcelo.  My versão be alrigth dear Vitalizde

Em qui, 14 de mai de 2015 04:14, Vitaly Litvak notifications@github.com
escreveu:

**Comment by vitalidze** [comment]
Consider as fixed because no one else reports anything about this slowness. Some people report that now UI can handle even 50K of points.
