### ISSUE TITLE
problems compiling traccar web 

### ISSUE THREAD

**Issue by joelfeijoo** [vitalidze/traccar-web#872]
Hi vitalidze, thanks for the excellent work you're doing.

I'm trying to compile the git for new updates and have an error.

[ERROR] symbol: class LonLat

I think the problem is, org.traccar.web.shared.model.LonLat, does not exist.

thanks for all the work you are doing, I hope to collaborate with my little knowledge.

**Comment by rsanni** [comment]
Me too having the same issue

**Comment by leontino** [comment]
me too

**Comment by vitalidze** [comment]
Please try now. I forgot to push `LonLat` class.

**Comment by leontino** [comment]
Now is ok to me!

**Comment by rsanni** [comment]
Thank you
