### ISSUE TITLE
Mobile map fixed on OSM

### ISSUE THREAD

**Issue by damocov** [vitalidze/traccar-web#873]
I've installed versions 3.5 through 3.7, on a clean Ubuntu 16.04 image each time, followed full instructions, and each time the desktop site opens fine using my Bing maps key, but the mobile site only ever shows OSM maps irrespective of the settings in the user preferences.

Is this a known error - or has the design changed?

**Comment by vitalidze** [comment]
This is a bug. I have just fixed it in code. The bing maps key wasn't transferred to the mobile version. Mobile version always falls back to OSM if there is some issue with bing maps key (for example it is missing).

**Comment by damocov** [comment]
Excellent, thanks for that quick response, I'll download the source and build a war

**Comment by damocov** [comment]
Looks good thanks.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
