### ISSUE TITLE
traccar/rest/getApplicationSettings.

### ISSUE THREAD

**Issue by rsanni** [vitalidze/traccar-web#875]
Hi Vitalidze,

Am trying to call api from my html app through traccar-web.js, I get the Below eroor, please help me how to overcome this 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

Thanks for the wonderfull webapp

**Comment by vitalidze** [comment]
Please use google to search for the error message you are facing. You will find many answers related to this issue.

**Comment by rsanni** [comment]
Yes vitalidze, I ended by choosing a implenting via PHP but i couldnt create the session, anyway thanks for your response
