### ISSUE TITLE
Wrong GPS position.

### ISSUE THREAD

**Issue by VdovinN** [vitalidze/traccar-web#876]
I started traccar service and I was at same place for an half hour. Then i generate a report with map and i was suprised to see so many position. 
First problem.
![1](https://cloud.githubusercontent.com/assets/7619704/19020341/71be4674-88ae-11e6-8c6b-1203718cddf5.png)

Second problem.
![2](https://cloud.githubusercontent.com/assets/7619704/19020343/8d10a3cc-88ae-11e6-9990-15e7d6ac9e96.png)

How i can fix it? I want to have only one point at the map if i was at the same place.

**Comment by vitalidze** [comment]
I think this is most probably because of unstable work of GPS when device is indoors. I am not sure how can you fix location jumps, but for close locations you can set up a filter by distance in traccar configuration file: https://www.traccar.org/configuration-file/

**Comment by leontino** [comment]
Some GPS trackers have a position error. I already  had 2 models showing wrong positions
