### ISSUE TITLE
Unable to send custom command

### ISSUE THREAD

**Issue by szmolnar** [vitalidze/traccar-web#879]
Hi there!

Sending a custom command it seems not to work, however the same command using the original version of traccar 3.7 is working properly.

![screen shot 2016-10-02 at 19 54 28](https://cloud.githubusercontent.com/assets/3518047/19022551/0ed0bfc4-88db-11e6-94ca-8b7bb296b33a.png)
![screen shot 2016-10-02 at 19 54 37](https://cloud.githubusercontent.com/assets/3518047/19022552/0efb89de-88db-11e6-9c28-91cfe2b5656d.png)

Log:
2016-10-02 19:54:35 DEBUG: [8F547004: 5072 > 91.87.128.nn]
2016-10-02 19:54:35  WARN: [8F547004] error - unsupported message type: class java.lang.String - IllegalArgumentException (...)
2016-10-02 19:54:35  INFO: [8F547004] disconnected
2016-10-02 19:54:36  INFO: [E4A2F80F] connected
2016-10-02 19:54:36 DEBUG: [E4A2F80F: 5072 < 91.87.128.nn] HEX: 2a545330312c38363833323330323531363639373323

Original traccar log:
2016-10-01 19:09:05 DEBUG: [149567DD: 5072 > 91.87.128.nn] HEX: 2a545330312c56455223
2016-10-01 19:09:06 DEBUG: [149567DD: 5072 < 91.87.128.nn] HEX: 2a545330312c3836383332333032353136343938362c3137303930363031313031362c5645523a312e3030353b312e3130373b31303a30393a31302d31382e30392e313623

Br.
Szabolcs

**Comment by vitalidze** [comment]
It works just fine for me. Why are you setting up command message as HEX string?

Are you sure you are using latest version of the Traccar Web UI Mod?

**Comment by szmolnar** [comment]
Hi!

I'm using Ulbotech protocol in Bin mode because Text format is not working in some of the reason.
Text format wasn't working on standard Traccar versions like 3.6 or 3.7 

When using text mode, the received commands are not processed on the server side. 
It looks strange that by setting command to text mode, the traccar log is still showing it as hex.
Ex:
 Bin mode:
![bin](https://cloud.githubusercontent.com/assets/3518047/19046345/2b902844-899d-11e6-8cfa-04718e8a071f.png)

"
2016-10-03 19:07:02  INFO: [8D8377B5] id: 868323025164986, time: 2016-10-03 19:07:01, lat: 47.49980, lon: 18.74843, speed: 0.0, course: 0.0
2016-10-03 19:07:14 DEBUG: [8FCC7234: 5072 < 91.82.128.74] HEX: f8010108683230251669739f854cc1010e02d31f6e0123696100000000006203040000000004040ac3b5d30506035317f22213100101894bf8
"

 Text mode:
![text](https://cloud.githubusercontent.com/assets/3518047/19046357/3fead99c-899d-11e6-90e3-b2a7a9fe47c4.png)

"
2016-10-03 19:05:00 DEBUG: [8D8377B5: 5072 < 91.82.128.74] HEX: 2a545330312c3836383332333032353136343938362c3137303435393033313031362c4750533a333b4e34372e3439393739393b4531382e3734383432373b303b303b322e30382c5354543a303b322c4d47523a3231363732353938362c4144433a303b31322e37373b313b33392e34353b323b342e30322c4556543a3123
"

So because Text mode was never working for me I thought to use Bin mode.
Traccar is receiving in Bin mode and is processed properly, device is shown on the map etc, I only have problems sending commands to the device.

Also sending command in text are not working.
![screen shot 2016-10-03 at 19 19 40](https://cloud.githubusercontent.com/assets/3518047/19046609/7257405e-899e-11e6-98dc-953d1bca9328.png)
![screen shot 2016-10-03 at 19 19 22](https://cloud.githubusercontent.com/assets/3518047/19046610/728d4fe6-899e-11e6-8b30-8d2d8030a7a6.png)
![screen shot 2016-10-03 at 19 19 11](https://cloud.githubusercontent.com/assets/3518047/19046611/72915f3c-899e-11e6-99d4-7e5a51b2dcb3.png)

Regarding your second question I just downloaded the latest version from:
http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war

**Comment by vitalidze** [comment]
> Text format wasn't working on standard Traccar versions like 3.6 or 3.7

So, have you done any modifications to the original traccar code? From what I can see it should be sending text commands only in standard implementation.

As for the log entries you are showing - they show what your device sends to traccar and not commands send from traccar. I am totally confused now.

**Comment by szmolnar** [comment]
First of all no, absolutely no mods. Only mod I did is the config file.

((( As for the entries posted in my last post, those are samples of incoming messages, you are right. I only inserted those to show you what I'm receiving in txt or bin modes. I thought it is interesting for you why receiving in text mode isn't working for me.
Sorry getting you confused. )))

Getting back to my original problem You asked me why I'm using hex mode. I got confused and I thought hex mode is not allowed for sending commands. Either way sending command bin or text isn't working for me.
I also tested text mode commands. On my last post the last 3 screenshots are samples for sending a text mode command.
If you want me to run additional tests please let me know!

Am I etering commands in the right way? 
Do I ned to add any additional string?
Sending both Hex or Text mode is allowed?

Thanks you!

**Comment by vitalidze** [comment]
> Am I etering commands in the right way? 
> Do I ned to add any additional string?
> Sending both Hex or Text mode is allowed?

From my understanding the only custom commands format, which is supported for now is text format. I don't know how it should work in your case and I don't have such device for testing. So, if you are using original 3.7 traccar, is the command sent interpreted correctly on your device? I think it should not.

**Comment by szmolnar** [comment]
As mentioned earlier yes, custom commands sent in bin format with original Traccar 3.7 are working perfectly. 

Sending in text mode it is not working.

**Comment by vitalidze** [comment]
Well, I think you have faced a bug in this project. It needs to be fixed in code. Until then you will not be able to send commands in binary format.

**Comment by szmolnar** [comment]
What do you think when it will be fixed?
At the other hand do you exactly know where the bug is? May I fix it by myself?

Thanks!

**Comment by vitalidze** [comment]
It will not be fixed in nearest future. Maybe within this month. Bug is in `DataServiceImpl` class. It sends custom command by directly invoking of `write` method of the `ActiveDevice`. But instead of this it should be invoking `sendCommand` as it does for all other commands types. There is one more thing to know - that it may work in 3.7, but most probably it will not work in some previous versions, where sending of CUSTOM commands wasn't implemented on the "backend" side.

**Comment by szmolnar** [comment]
I haven't spent much time to interpret the code.
You really mean do I only need to replace "write" to "sendCommand" ? 

"
Class<?> objectClass = Class.forName("java.lang.Object");
                    Method sendCommand = activeDevice.getClass().getDeclaredMethod("write", objectClass);
                    sendCommand.invoke(activeDevice, command.getCommand());
"

**Comment by vitalidze** [comment]
No, I think removing/commenting out whole code in 'if' branch and leaving only 'else' branch should work it out. But I am not sure.

**Comment by szmolnar** [comment]
Unfortunately it's not working.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2016/12/17/Bugfix-Release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
