### ISSUE TITLE
Start Notification

### ISSUE THREAD

**Issue by maxlife70** [vitalidze/traccar-web#88]
Goodmorning, Is possible to have an email notification also when the target start and not only when stop?
Thanks.
BR

**Comment by vitalidze** [comment]
Right now notifications are only sent when device goes offline (i.e. no positions are received within some time interval).

**Comment by JoeTaylor95** [comment]
Hi @vitalidze 

The above question would be a defiantly great feature! 
:+1:  Following for updates

**Comment by vitalidze** [comment]
This was implemented couple of versions ago.
