### ISSUE TITLE
 Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#880]
Hi @vitalidze,

I really like what you did to traccar, thank you for your great contribution to humanity.

I have this small issue just like jesusto stated here https://github.com/vitalidze/traccar-web/issues/613, I did all the necessary things suggested on this thread, I copied src/main/java/org/traccar/web/server/model/CorsFilter.java to the same directory as my server copy, recompiled just as mentioned on this link http://traccar.litvak.su/building.html

I still can't get it to work :(

Here's my testing script.

http://54.254.236.138/traccar.php

Please help :)

**Comment by vitalidze** [comment]
You need to set up filter in `GuiceServletConfig` too. Just adding java class will not work.

**Comment by ghost** [comment]
@vitalidze i see these lines on GuiceServletConfig

```
            filter("/traccar/*").through(PersistFilter.class);
            filter("/", "/traccar.html", "/m/", "/m/index.html").through(LocaleFilter.class);
```

Please let me know what to add there :(

Thank you.

**Comment by vitalidze** [comment]
You should add similar line for the URL pattern, where you want to apply filter and use `CorsFilter.class`.

**Comment by ghost** [comment]
Is this correct 
filter("/*").through(CorsFilter.class); 

?

**Comment by vitalidze** [comment]
It looks correct. You can read about configuration here: https://github.com/google/guice/wiki/ServletModule

**Comment by ghost** [comment]
Ok @vitalidze , you are awesome! Thank you! I'm an arduino/PHP expert, still learning JAVA :)
