### ISSUE TITLE
rest api curl issue on domain access

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#881]
Using curl, I can access the API through a local IP (i.e. 192.168.1.11) or any other outside public IP but not with a domain (i.e. example.com), it just loads infinitely.

Here is my curl example.

```
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, "54.254.236.138:8082/traccar/rest/login");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, "[\"admin\",\"admin\"]");
```

Please help :(

**Comment by vitalidze** [comment]
You can find working cURL examples in official documentation: http://traccar.litvak.su/features/rest-api.html Your code seems to be written in PHP, I guess you should debug it somehow. I personally don't have any experience in calling curl from PHP.

**Comment by ghost** [comment]
Ok thanks. I made it double curl. I put the main curl on the traccar IP based domain, while the domain name also uses curl to call it.
