### ISSUE TITLE
how to register or add user via api

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#884]
I can't find it on any documentation.

Please help :(

**Comment by vitalidze** [comment]
You should read documentation carefully. It says that API exposes all methods from the `DataService` interface: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/model/DataService.java

I don't have time to describe each method with it's arguments. Instead of this I describe common approach on the API usage. You can also look for other issues regarding API on this issue tracker.

**Comment by ghost** [comment]
I see two, I don't know which one to use.

User addUser(User user) throws InvalidMaxDeviceNumberForUserException;

User register(String login, String password) throws AccessDeniedException;

I tried both but it says, "404 not found" :(

**Comment by ghost** [comment]
I run these via command line

curl -v --cookie "JSESSIONID=9ac1ctuq5005e5nohiapqkg8" -X POST --data "[\"user5\",\"user5\"]" 54.254.236.138:8082/traccar/rest/login

curl -v --cookie "JSESSIONID=9ac1ctuq5005e5nohiapqkg8" -X POST --data "[\"user5\",\"user5\"]" 54.254.236.138:8082/traccar/rest/addUser

same error

**Comment by vitalidze** [comment]
> curl -v --cookie "JSESSIONID=9ac1ctuq5005e5nohiapqkg8" -X POST --data "[\"user5\",\"user5\"]" 54.254.236.138:8082/traccar/rest/login

You are using `login` method here. The signature of `register` method is same as for `login` method. You should not put any JSESSIONID here. Also you are missing `http://` prefix.

> curl -v --cookie "JSESSIONID=9ac1ctuq5005e5nohiapqkg8" -X POST --data "[\"user5\",\"user5\"]" 54.254.236.138:8082/traccar/rest/addUser

This one accepts user object in JSON format. You are providing array of strings.

**Comment by ghost** [comment]
I'm sorry @vitalidze but I still can't register using this

curl -v -X POST --data "[\"user1\",\"user1\"]" http://54.254.236.138:8082/traccar/rest/register

Error 500 Server Error

I really need help on this :(

**Comment by ghost** [comment]
Ok. I got a "username is already taken" error, that's why I can't register via api. I deleted the database, created another one and now it's fixed.

I'm using this method to register new user

curl -v  -X POST --data "[\"user5\",\"user5\"]" 54.254.236.138:8082/traccar/rest/register

Thanks for your patience @vitalidze , you have a great virtue ;)

**Comment by meneva** [comment]
Hello, I have a manager user access(userlimit: -1, deviceLimit: -1). Now i want to create another user under this account. I used the following code:
`public static function addUser($cookie, $name, $email, $password) {
		$id = '-1';
		$name = $name;
		$email = $email;
		$readonly = 'false';
		$admin = 'false';
		$map = '';
		$latitude = '0';
		$longitude = '0';
		$zoom = '0';
		$password = $password;
		$twelveHourFormat = 'false';
		$coordinateFormat = '0';
		$disabled = 'false';
		$expirationTime = '';
		$deviceLimit = '0';
		$userLimit = '0';
		$deviceReadonly = 'false';
		$limitCommands = 'false';
		$token = '';
		//$attributes = $attributes;
		$data = '{"name":"' . $name . '","email":"' . $email . '","password":"' . $password . '","readonly":"' . $readonly . '","admin":"' . $admin . '","map":"' . $map . '","latitude":"' . $latitude . '","longitude":"' . $longitude . '","zoom":"' . $zoom . '","twelveHourFormat":"' . $twelveHourFormat . '","coordinateFormat":"' . $coordinateFormat . '","disabled":"' . $disabled . '","expirationTime":"' . $expirationTime . '","devicelimit":"' . $deviceLimit.'","userlimit":"' . $userLimit . '"}';

		return self::curl('/api/users', 'POST', $cookie, $data, array(self::$jsonC));
	}`

It creates the user successfully but there is no entry in user_user table in database. Therefore, the new user is not under my manager account. Can u please guide me on where is the actual issue. thanks in advance

**Comment by vitalidze** [comment]
@meneva the table `user_user` is not used in this project. The `managedBy` column will have manager's identifier.

**Comment by vitalidze** [comment]
@meneva also please don't resurrect old closed threads. Open new one instead.

**Comment by meneva** [comment]
Hello vitalidze.. thanks for your reply... can u please tell me which table has the "managedBy" column ? is it in "users" table ?

**Comment by vitalidze** [comment]
@meneva  Yes, it's in `users` table.
