### ISSUE TITLE
New feature: Set new fence on a single click for Bike/Ebike Antitheft

### ISSUE THREAD

**Issue by Phantomatz** [vitalidze/traccar-web#889]
I would like to use traccar as notification server, in case someone is stealing my bike.

I would need to activate a geofence around current position more or less on a "single"click on the mobile phone. Of course, when I'am back I would like to switch it of as easy as possible, as well.

Can this be somehow handled ? Within one of the next releases ?
Any chance I could build myself a PHP script which could do the necessary in Traccar and I could activate/deactivate by opening the browser with the PHP script ?

**Comment by vitalidze** [comment]
> Can this be somehow handled ? Within one of the next releases ?

It looks too custom to be included in next releases. I don't think it will be included.

> Any chance I could build myself a PHP script which could do the necessary in Traccar and I could activate/deactivate by opening the browser with the PHP script ?

There is an API: http://traccar.litvak.su/features/rest-api.html You can connect/disconnect geo-fence with desired devices using the API. Also I think it should be possible to directly update database (for example if you are using MySQL database it should not be a problem to update it with PHP script).

**Comment by Phantomatz** [comment]
Thank you for the feedback. I'll check the API.

**Comment by wouterbudding** [comment]
Can you please tell me what hardware you use on your (e)bike to connect to traccar?

**Comment by Phantomatz** [comment]
Helligkeit wouterbudding, I use a TK5000XL dir my Ebike
