### ISSUE TITLE
How to change favicon ?

### ISSUE THREAD

**Issue by jolypas** [vitalidze/traccar-web#890]
I would like to customize the favicon.
I tried  to replace in traccar/web/favicon.ico but it is not working (even after cleaning the cache).

Another way ?

Thanks

**Comment by vitalidze** [comment]
I am not sure, but I guess you can just put it inside `traccar-web.war` right in the root of archive, i.e. on the same level as `traccar.html` file. Then you need to make sure that your favicon.ico is accessible through the HTTP GET (like try to put the address in browser address bar).

**Comment by jolypas** [comment]
It works fine !
thanks a lot

**Comment by jolypas** [comment]
hello, I don't know if can mark this "issue" as "resolved" myself  ?
