### ISSUE TITLE
traccar wen 3.7 and mysql

### ISSUE THREAD

**Issue by jolypas** [vitalidze/traccar-web#895]
Hello

I would like to migrate to mysql 

I followed the traccar docuementation, I created an empty database, a user/password with priviledges on it but I cannot start the service

the wrapper log

> STATUS | wrapper  | 2016/10/13 19:50:16 | --> Wrapper Started as Daemon
> STATUS | wrapper  | 2016/10/13 19:50:16 | Java Service Wrapper Community Edition 64-bit 3.5.28
> STATUS | wrapper  | 2016/10/13 19:50:16 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
> STATUS | wrapper  | 2016/10/13 19:50:16 |     http://wrapper.tanukisoftware.com
> STATUS | wrapper  | 2016/10/13 19:50:16 |
> STATUS | wrapper  | 2016/10/13 19:50:16 | Launching a JVM...
> INFO   | jvm 1    | 2016/10/13 19:50:16 | WrapperManager: Initializing...
> INFO   | jvm 1    | 2016/10/13 19:50:18 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
> INFO   | jvm 1    | 2016/10/13 19:50:19 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @2608ms
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp:
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error: Encountered an error running main:
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error: java.lang.NullPointerException
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:272)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:98)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:79)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:218)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:498)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
> INFO   | jvm 1    | 2016/10/13 19:50:19 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
> STATUS | wrapper  | 2016/10/13 19:50:21 | <-- Wrapper Stopped
> m2aim@M2AIMvm3:/opt/traccar/logs$

I gave all priviledges on the database without success

any ideas ?

**Comment by vitalidze** [comment]
You haven't followed installation instructions carefully: http://traccar.litvak.su/installation.html

Please double check all steps.

**Comment by jolypas** [comment]
Thanks for yout prompt anwer !

I redo from the beginning  and it works fine now !
