### ISSUE TITLE
Installation of server for traccar-web.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#899]
Hi Vitalidze,

I have followed your installation instruction http://traccar.litvak.su/installation.html for traccar and have the following issue so far could you please help.

first of all service runs and gives "503 - Service Unavailable"

Here is the log 

INFO   | jvm 1    | 2016/10/15 22:10:51 | [Thread-15] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@36ca05b6{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/15 22:10:51 | [Thread-15] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@533b7613{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-2862334566163662806.dir/webapp/,UNAVAILABLE}{c:\Program Files\Traccar\traccar-web.war}
INFO   | jvm 1    | 2016/10/15 22:10:53 | [Thread-15] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@37dae84b{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/10/15 22:10:54 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/10/15 22:11:50 | --> Wrapper Started as Service**
STATUS | wrapper  | 2016/10/15 22:11:51 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/15 22:11:51 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/15 22:11:51 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/15 22:11:51 | 
STATUS | wrapper  | 2016/10/15 22:11:51 | Launching a JVM...
INFO   | jvm 1    | 2016/10/15 22:11:51 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/15 22:11:53 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/15 22:11:54 | [WrapperSimpleAppMain] INFO **com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (This operation is not supported.)**
INFO   | jvm 1    | 2016/10/15 22:11:55 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @3369ms
INFO   | jvm 1    | 2016/10/15 22:11:56 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO   | jvm 1    | 2016/10/15 22:11:58 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7727d654{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/10/15 22:12:14 | [WrapperSimpleAppMain] INFO **org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet**
**INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@2d20a41{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-4442421638176066230.dir/webapp/,STARTING}{c:\Program Files\Traccar\traccar-web.war}**
**INFO   | jvm 1    | 2016/10/15 22:12:24 | java.lang.RuntimeException: Unable to perform DB migrations
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:77)**
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.server.Server.start(Server.java:387)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.server.Server.doStart(Server.java:354)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.web.WebServer.start(WebServer.java:179)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.Main.main(Main.java:40)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.web.server.model.DBMigrations$SetDefaultExpiredFlagForEvents.migrate(DBMigrations.java:406)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.web.server.model.DBMigrations.migrate(DBMigrations.java:72)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:75)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   ... 32 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   ... 35 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'events'.
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2444)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/10/15 22:12:24 |   ... 43 more
INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@371d37a5{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/15 22:12:24 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server

**Comment by vitalidze** [comment]
If you need to use it with MS SQL Server you need these additional steps #669

**Comment by akmal1999** [comment]
Are you referring to Unpack WEB-INF/classes/META-INF/persistence.xml file from traccar-web.war zip-archive.

Is that something you have done and have a copy as I am not very good with linux commands. Would you mind giving me a copy.

**Comment by akmal1999** [comment]
Ok I think i did it.. I will try and let you know.

**Comment by akmal1999** [comment]
Worked like charm. many thanks for this project..
