### ISSUE TITLE
Securring traccar server

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#902]
Hi Everyone,

I was wondering who has achieved to secure the traccar server so far and what strategy did you choose.
specially for windows 2012 server.

I see traccar opens alot of ports does this mean we have to open each and every port in our firewall to get the devices to work?

Does anyone have used waf?

Please sure any security measures taken and how to configure.

**Comment by wolfbgn** [comment]
5000 forward to range 5000 - 5100 for devices + 8082 for Traccar

**Comment by akmal1999** [comment]
@wolfbgn @vitalidze well, it is very unrealistic however, look at how many ports are open.

 Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:445            DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:2869           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5001           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5002           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5003           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5004           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5005           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5006           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5007           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5008           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5009           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5010           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5011           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5012           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5013           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5014           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5015           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5016           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5017           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5018           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5019           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5020           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5022           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5023           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5024           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5025           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5026           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5027           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5028           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5029           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5030           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5031           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5032           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5033           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5034           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5035           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5036           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5037           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5039           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5040           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5041           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5042           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5043           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5044           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5045           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5046           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5047           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5048           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5049           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5050           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5051           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5052           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5054           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5055           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5056           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5057           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5058           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5059           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5060           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5061           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5062           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5063           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5064           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5065           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5066           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5067           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5068           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5069           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5070           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5071           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5072           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5073           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5074           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5075           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5076           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5077           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5078           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5079           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5080           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5081           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5083           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5085           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5086           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5087           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5088           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5089           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5090           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5091           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5092           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5093           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5094           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5095           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5096           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5097           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5098           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5099           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5100           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5101           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5102           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5103           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5105           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5106           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5107           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5108           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5109           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5111           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5112           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5113           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5114           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5115           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5116           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5117           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5118           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:5357           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:8082           DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49664          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49665          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49666          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49667          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49668          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:49683          DESKTOP-OL2UKHH:0      LISTENING
  TCP    0.0.0.0:52075          DESKTOP-OL2UKHH:0      LISTENING
  TCP    127.0.0.1:31001        DESKTOP-OL2UKHH:32000  ESTABLISHED
  TCP    127.0.0.1:32000        DESKTOP-OL2UKHH:0      LISTENING
  TCP    127.0.0.1:32000        DESKTOP-OL2UKHH:31001  ESTABLISHED
  TCP    127.0.0.1:53554        DESKTOP-OL2UKHH:53555  ESTABLISHED
  TCP    127.0.0.1:53555        DESKTOP-OL2UKHH:53554  ESTABLISHED
  TCP    127.0.0.1:53556        DESKTOP-OL2UKHH:53557  ESTABLISHED
  TCP    127.0.0.1:53557        DESKTOP-OL2UKHH:53556  ESTABLISHED
  TCP    127.0.0.1:53558        DESKTOP-OL2UKHH:53559  ESTABLISHED
  TCP    127.0.0.1:53559        DESKTOP-OL2UKHH:53558  ESTABLISHED
  TCP    127.0.0.1:53566        DESKTOP-OL2UKHH:53567  ESTABLISHED
  TCP    127.0.0.1:53567        DESKTOP-OL2UKHH:53566  ESTABLISHED
  TCP    127.0.0.1:53568        DESKTOP-OL2UKHH:53569  ESTABLISHED
  TCP    127.0.0.1:53569        DESKTOP-OL2UKHH:53568  ESTABLISHED
  TCP    127.0.0.1:53570        DESKTOP-OL2UKHH:53571  ESTABLISHED
  TCP    127.0.0.1:53571        DESKTOP-OL2UKHH:53570  ESTABLISHED
  TCP    127.0.0.1:53572        DESKTOP-OL2UKHH:53573  ESTABLISHED
  TCP    127.0.0.1:53573        DESKTOP-OL2UKHH:53572  ESTABLISHED
  TCP    127.0.0.1:53574        DESKTOP-OL2UKHH:53575  ESTABLISHED
  TCP    127.0.0.1:53575        DESKTOP-OL2UKHH:53574  ESTABLISHED
  TCP    127.0.0.1:53633        DESKTOP-OL2UKHH:53634  ESTABLISHED
  TCP    127.0.0.1:53634        DESKTOP-OL2UKHH:53633  ESTABLISHED
  TCP    192.168.2.30:139       DESKTOP-OL2UKHH:0      LISTENING
  TCP    192.168.2.30:445       AKM-PC:53410           ESTABLISHED
  TCP    192.168.2.30:445       AKM-PC:53436           ESTABLISHED
  TCP    192.168.2.30:445       AKM-PC:53437           ESTABLISHED
  TCP    192.168.2.30:445       AKM-PC:53438           ESTABLISHED
  TCP    192.168.2.30:2869      mynetwork:41818        TIME_WAIT
  TCP    192.168.2.30:2869      mynetwork:41819        TIME_WAIT
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:53561  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54300  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54301  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54302  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54303  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54304  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54305  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54306  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54307  ESTABLISHED
  TCP    192.168.2.30:52075     DESKTOP-OL2UKHH:54309  ESTABLISHED
  TCP    192.168.2.30:53561     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54209     bn3sch020010637:https  ESTABLISHED
  TCP    192.168.2.30:54211     msnbot-65-52-108-213:https  ESTABLISHED
  TCP    192.168.2.30:54300     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54301     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54302     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54303     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54304     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54305     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54306     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54307     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54309     DESKTOP-OL2UKHH:52075  ESTABLISHED
  TCP    192.168.2.30:54319     dm2301-skpfe:http      ESTABLISHED
  TCP    192.168.2.30:54321     a-0001:https           TIME_WAIT
  TCP    192.168.2.30:54322     a23-221-11-195:http    ESTABLISHED
  TCP    192.168.2.30:54323     a104-84-148-128:http   ESTABLISHED
  TCP    192.168.2.30:54325     a-0001:https           ESTABLISHED
  TCP    192.168.2.30:54327     40.80.145.27:http      ESTABLISHED
  TCP    192.168.2.30:54331     mynetwork:49153        TIME_WAIT
  TCP    192.168.2.30:54333     a184-24-145-75:http    TIME_WAIT
  TCP    192.168.2.30:54336     mynetwork:49153        TIME_WAIT
  TCP    192.168.2.30:54345     a184-24-145-75:http    TIME_WAIT
  TCP    [::]:135               DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:445               DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:2869              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5001              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5002              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5003              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5004              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5005              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5006              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5007              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5008              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5009              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5010              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5011              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5012              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5013              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5014              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5015              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5016              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5017              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5018              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5019              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5020              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5022              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5023              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5024              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5025              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5026              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5027              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5028              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5029              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5030              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5031              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5032              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5033              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5034              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5035              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5036              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5037              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5039              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5040              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5041              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5042              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5043              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5044              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5045              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5046              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5047              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5048              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5049              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5050              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5051              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5052              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5054              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5055              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5056              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5057              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5058              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5059              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5060              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5061              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5062              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5063              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5064              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5065              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5066              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5067              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5068              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5069              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5070              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5071              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5072              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5073              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5074              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5075              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5076              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5077              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5078              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5079              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5080              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5081              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5083              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5085              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5086              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5087              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5088              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5089              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5090              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5091              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5092              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5093              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5094              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5095              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5096              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5097              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5098              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5099              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5100              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5101              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5102              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5103              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5105              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5106              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5107              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5108              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5109              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5111              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5112              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5113              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5114              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5115              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5116              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5117              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5118              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:5357              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:8082              DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49664             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49665             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49666             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49667             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49668             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:49683             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::]:52075             DESKTOP-OL2UKHH:0      LISTENING
  TCP    [::1]:8082             DESKTOP-OL2UKHH:54258  ESTABLISHED
  TCP    [::1]:54258            DESKTOP-OL2UKHH:8082   ESTABLISHED
  UDP    0.0.0.0:1434           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:3702           _:_
  UDP    0.0.0.0:5001           _:_
  UDP    0.0.0.0:5002           _:_
  UDP    0.0.0.0:5003           _:_
  UDP    0.0.0.0:5004           _:_
  UDP    0.0.0.0:5005           _:_
  UDP    0.0.0.0:5009           _:_
  UDP    0.0.0.0:5016           _:_
  UDP    0.0.0.0:5020           _:_
  UDP    0.0.0.0:5021           _:_
  UDP    0.0.0.0:5027           _:_
  UDP    0.0.0.0:5031           _:_
  UDP    0.0.0.0:5032           _:_
  UDP    0.0.0.0:5038           _:_
  UDP    0.0.0.0:5044           _:_
  UDP    0.0.0.0:5050           _:_
  UDP    0.0.0.0:5052           _:_
  UDP    0.0.0.0:5053           _:_
  UDP    0.0.0.0:5074           _:_
  UDP    0.0.0.0:5081           _:_
  UDP    0.0.0.0:5082           _:_
  UDP    0.0.0.0:5084           _:_
  UDP    0.0.0.0:5086           _:_
  UDP    0.0.0.0:5103           _:_
  UDP    0.0.0.0:5104           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5355           _:_
  UDP    0.0.0.0:54033          _:_
  UDP    0.0.0.0:57933          _:_
  UDP    0.0.0.0:62029          _:_
  UDP    127.0.0.1:1900         _:_
  UDP    127.0.0.1:54032        _:_
  UDP    192.168.2.30:137       _:_
  UDP    192.168.2.30:138       _:_
  UDP    192.168.2.30:1900      _:_
  UDP    192.168.2.30:54031     _:_
  UDP    [::]:1434              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:3702              _:_
  UDP    [::]:5001              _:_
  UDP    [::]:5002              _:_
  UDP    [::]:5003              _:_
  UDP    [::]:5004              _:_
  UDP    [::]:5005              _:_
  UDP    [::]:5009              _:_
  UDP    [::]:5016              _:_
  UDP    [::]:5020              _:_
  UDP    [::]:5021              _:_
  UDP    [::]:5027              _:_
  UDP    [::]:5031              _:_
  UDP    [::]:5032              _:_
  UDP    [::]:5038              _:_
  UDP    [::]:5044              _:_
  UDP    [::]:5052              _:_
  UDP    [::]:5053              _:_
  UDP    [::]:5074              _:_
  UDP    [::]:5081              _:_
  UDP    [::]:5082              _:_
  UDP    [::]:5084              _:_
  UDP    [::]:5086              _:_
  UDP    [::]:5103              _:_
  UDP    [::]:5104              _:_
  UDP    [::]:54034             _:_
  UDP    [::]:57934             _:_
  UDP    [::]:62030             _:_
  UDP    [::1]:1900             _:_
  UDP    [::1]:54030            _:_

C:\Users\testing>
