### ISSUE TITLE
Hosting Services cheap and good.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#904]
Hi Everyone,

Which hosting service allows all these port openings to servers and how do you secure this traccar server?

thanks.

**Comment by Turbovix** [comment]
Hi @akmal1999 , i use an EC2(Amazon) and is perfect for using the platform.
https://goo.gl/ebYtc2 

In my region, you get 12 months to test the service in Virginia USA servers, being charged only at the end if you want to follow with AWS.

**Comment by vitalidze** [comment]
I can recommend digital ocean: https://www.digitalocean.com/

**Comment by Turbovix** [comment]
The DigitalOcean services are also great and has a fair value.

**Comment by akmal1999** [comment]
Many thanks for the feedback. Appreciated.
