### ISSUE TITLE
Frequncy Interval and data quantification

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#909]
Hi Everyone,

Has anyone quantify how much data is used per min if we configure the apps frequency intervals.
Suppose if we keep the frequency like below:

1 sec
5 sec
10 sec
60  sec
120 sec
240 sec

Will appreciate any quantification analysis on the above frequency intervals.

**Comment by wolfbgn** [comment]
30s - 25MB/month

**Comment by akmal1999** [comment]
Many thanks.
