### ISSUE TITLE
TK102 configuration on the web

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#911]
Hi Everyone,

Just a quick question, has anyone configured TK102 and can monitor it?

I happen to get the IMEI and put the number in as unique identifier however, I couldn't get it working.
Is the phone number become the unique id or IMEI?

Appreciate your feedback.

**Comment by wolfbgn** [comment]
Devices that use TK103 protocol (port 5002) use 12-digit device identifier instead of IMEI. Usually it consists of 11 last digits from IMEI plus leading zero. For example, if IMEI number is 123456789012345, the unique id would be 056789012345.

**Comment by akmal1999** [comment]
Many thanks I will try this. and check.

**Comment by akmal1999** [comment]
Hi I have kept all the traccar ports open. However, where do you have to specify the port at? is that on the server side? Appreciated your help.

**Comment by wolfbgn** [comment]
Router

**Comment by akmal1999** [comment]
This would be much my hosting provider then correct?

**Comment by akmal1999** [comment]
I have not gotten this working. I will still try another round in the weekend.

**Comment by akmal1999** [comment]
Do we need to configure sos ?

**Comment by akmal1999** [comment]
Do we configure sensors if yes is there a sensor list I could refer?
