### ISSUE TITLE
How to Increase marker of object Direction?

### ISSUE THREAD

**Issue by akamomer** [vitalidze/traccar-web#912]
My Traccar-Web worked very good.
I need to increase direction marker because as its shown in below pic they are few and I can't recognize the exact direction when two lines are together (When The vehicle moved on both sides on the road).

<img width="454" alt="capture" src="https://cloud.githubusercontent.com/assets/21143005/19522674/b684189a-9620-11e6-8931-642171b87c46.PNG">

**Comment by vitalidze** [comment]
There is a setting named "Arrow size" in device properties, which controls size of marker. You can also change the "Timestamp print interval" (it's in minutes) setting in "Preferences", which will put arrows more frequently.
