### ISSUE TITLE
Read Only Login issue.

### ISSUE THREAD

**Issue by akmal1999** [vitalidze/traccar-web#916]
Hi,

When read only user logs in, the user can see and change groups created by admin and impacts admin group if changed.

how to hide groups created by admin so read only user can not see the groups created in main admin and can not change.

regards,

**Comment by vitalidze** [comment]
I am unable to reproduce this issue. There are no "Groups" menu for read-only user. Moreover, on server side there is a validation so the read-only user will not be able to save anything.

> how to hide groups created by admin so read only user can not see the groups created in main admin and can not change.

There is no way to hide them. If you assigned a group to device, then it _will be_ available for all users having access to that device. This is to show device under appropriate group in devices list.

**Comment by akmal1999** [comment]
Hi Vitlidze,

I am sorry I was making a mistake with the user. I am talking about not readonly user but, manager.
the manager user sees the group that admin makes and manger can change the group too. This is correct in the case of the main admin who creates the manager user and the the same manager logs in and sees the groups that the admin created. Manager can remove and can rename the group made by admin. I am using following. I have added following customization on top of the version 3.7.. http://traccar.litvak.su/installation.html

**Comment by vitalidze** [comment]
"Read-only" and "manager" users are a completely different concepts in the system. About accessing group - this is how access works and it cannot be changed without changing the code. You can read about group and access here: http://traccar.litvak.su/features/groups.html
