### ISSUE TITLE
Migrating database

### ISSUE THREAD

**Issue by bospre** [vitalidze/traccar-web#918]
Hello Vitali,
actually this is no issue and I am not sure if this is the right place to ask for.

I was running traccar 2.10 with your "addon" a long time.
But last week the latest java update destroyed my setup. Reverting to an older Java release did not solve my problem. So I decided to migrate to the latest traccar version (which actually I wanted have done before)
Finally I got through all the setup steps and have a new 3.7 version running.
But it would be nice to keep all the recorded data.
I have a backup of the database (database.mv.db and database.trace.db)
I there a way to import them to the new version?
Thank you in advance.
Boris

**Comment by vitalidze** [comment]
If you have installed Traccar Web UI Mod correctly then it should be safe to just overwrite your existing database files. After starting service back you should see all your data.

**Comment by bospre** [comment]
Good Morning,
thank you for your fast reply.
Of course I already tried that.
But Traccar does not start.
Any idea what could be wrong?

Here some lines of wrapper.log.xx
STATUS | wrapper  | 2016/10/24 07:45:34 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/10/24 07:46:22 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/10/24 07:46:22 | Java Service Wrapper Community Edition 32-bit 3.5.28
STATUS | wrapper  | 2016/10/24 07:46:22 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/24 07:46:22 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/24 07:46:22 | 
STATUS | wrapper  | 2016/10/24 07:46:23 | Launching a JVM...
INFO   | jvm 1    | 2016/10/24 07:46:24 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/24 07:46:27 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "java.lang.IllegalStateException: Chunk 3093219 no longer exists [1.4.192/9]" [50000-192]
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.initDatabase(DataManager.java:111)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.<init>(DataManager.java:66)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error: Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Chunk 3093219 no longer exists [1.4.192/9]" [50000-192]
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.message.DbException.get(DbException.java:168)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.message.DbException.convert(DbException.java:295)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Database.openDatabase(Database.java:301)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Database.<init>(Database.java:264)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Engine.openSession(Engine.java:64)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Engine.openSession(Engine.java:176)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Engine.createSession(Engine.java:137)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Engine.createSession(Engine.java:27)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.Driver.connect(Driver.java:72)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:508)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   ... 12 more
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error: Caused by: java.lang.IllegalStateException: Chunk 3093219 no longer exists [1.4.192/9]
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:951)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.MVStore.getChunk(MVStore.java:933)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.MVStore.readPage(MVStore.java:1935)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.MVMap.readPage(MVMap.java:736)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.Page.getChildPage(Page.java:217)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.Cursor.fetchNext(Cursor.java:150)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.Cursor.next(Cursor.java:50)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.db.TransactionStore$TransactionMap$1.fetchNext(TransactionStore.java:1402)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.db.TransactionStore$TransactionMap$1.next(TransactionStore.java:1426)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.mvstore.db.MVSecondaryIndex$MVStoreCursor.next(MVSecondaryIndex.java:507)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Database.open(Database.java:750)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   at org.h2.engine.Database.openDatabase(Database.java:270)
INFO   | jvm 1    | 2016/10/24 07:46:28 | WrapperSimpleApp Error:   ... 26 more
STATUS | wrapper  | 2016/10/24 07:46:30 | <-- Wrapper Stopped

**Comment by vitalidze** [comment]
This means your database is damaged. I think this was the reason of your issues and not the java update.

Generally, I highly not recommend using H2 database in production system. Use MySQL instead.

**Comment by bospre** [comment]
Probably you are right.
But the system was running fine until Java Update.

Is there a tutorial for using a mySQL-database?

**Comment by vitalidze** [comment]
Here is how to configure it on traccar side: https://www.traccar.org/mysql/

**Comment by bospre** [comment]
Thank you. I will try that later.
