### ISSUE TITLE
Dashboard for Traccar Web UI

### ISSUE THREAD

**Issue by prassannajohnpaul** [vitalidze/traccar-web#920]
Hi 
Is it possible to add a dashboard to UI? If yes, then how? It could be taken as a ticket for RoadMap.

Thank you

**Comment by vitalidze** [comment]
There are no "dashboard" functionality at the moment. I don't plan to add anything to the roadmap until current plan is completed.

**Comment by prassannajohnpaul** [comment]
Thank you
You may give priority to the same after completion of current plan.

**Comment by prassannajohnpaul** [comment]
Thank you Vitaly 
You may give priority to the same after completing current plan.
