### ISSUE TITLE
my Traccar services suddenly stop then not started

### ISSUE THREAD

**Issue by sourabhkhare** [vitalidze/traccar-web#922]
Dear Sir,

,my traccar web service suddenly stop then its not started. i found following log

STATUS | wrapper  | 2016/10/26 00:29:51 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/10/26 00:29:51 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/26 00:29:51 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/26 00:29:51 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/26 00:29:51 |
STATUS | wrapper  | 2016/10/26 00:29:51 | Launching a JVM...
INFO   | jvm 1    | 2016/10/26 00:29:52 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/26 00:29:52 | log4j:ERROR Failed to flush writer,
INFO   | jvm 1    | 2016/10/26 00:29:52 | java.io.IOException: No space left on device
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at java.io.FileOutputStream.writeBytes(Native Method)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at java.io.FileOutputStream.write(FileOutputStream.java:345)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:369)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.Category.callAppenders(Category.java:206)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.Category.forcedLog(Category.java:391)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.apache.log4j.Category.info(Category.java:666)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.traccar.helper.Log.info(Log.java:140)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.traccar.helper.Log.logSystemInfo(Log.java:89)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.traccar.helper.Log.setupLogger(Log.java:74)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.traccar.Context.init(Context.java:117)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/26 00:29:52 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/10/26 0ERROR  | wrapper  | 2016/10/26 09:47:32 | 23302 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 09:47:32 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 09:48:17 | 23488 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 09:48:17 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 10:15:58 | 24821 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 10:15:58 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory

**Comment by vitalidze** [comment]
You have ran out of disk space:

```
INFO | jvm 1 | 2016/10/26 00:29:52 | java.io.IOException: No space left on device
```

**Comment by sourabhkhare** [comment]
dear sir,

I have extend the disk space but still have same error.

**Comment by vitalidze** [comment]
You need to find out who consumes your disk space.

**Comment by sourabhkhare** [comment]
problem was solved i have deleated the traccar.pid file then restart the taccar. its working
