### ISSUE TITLE
Rename Export File Names

### ISSUE THREAD

**Issue by nikhilnayak98** [vitalidze/traccar-web#927]
How to export the csv or gpx files as DevicePositions.csv or DevicePositions.gpx instead of traccar-positions.csv or traccar-positions.gpx.

**Comment by vitalidze** [comment]
The file name is hardcoded here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/ExportServlet.java

You need to update code and rebuild the `traccar-web.war` file to change the name.

**Comment by gpproton** [comment]
I think it will be better if the exported file name is the device name and the selected date range.
