### ISSUE TITLE
Valid column header issue

### ISSUE THREAD

**Issue by ggps** [vitalidze/traccar-web#93]
Every time I login in Traccar Web, the header of the column "Valid" is showed in archive even if it is unselected. I must select and unselect for hiding it.
![capture](https://cloud.githubusercontent.com/assets/10890109/6308762/632bab84-b947-11e4-8ca1-7737afb8ebc1.png)

**Comment by vitalidze** [comment]
This is a known issue, already discussed in #81. Issue is in GXT library that is used for the UI, I have posted it a while on their forum, but no reply: http://www.sencha.com/forum/showthread.php?296644-Hidden-columns-state-in-grid-is-loaded-incorrectly.

**Comment by ggps** [comment]
Ok , thanks.

**Comment by vitalidze** [comment]
Finally, guy on sencha forum has suggested a workaround, which is applied in latest version. Issue should be gone now. Please check if possible.

**Comment by vitalidze** [comment]
Closed due to inactivity.
