### ISSUE TITLE
New install form 3.7

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#932]
Hello,

(xfce 16.04)
3 times I followed instructions. Once done I can't connect.
1°) I install 3.7 without any modif
   I ran   127.0.0.1:8082   access OK
2°) I install Litvak's mod
  I ran   127.0.0.1:8082   access  OK
3°) I switch database as  mysql
  I ran   127.0.0.1:8082
  I get an   "unable to access  127.0.0.1:8082"

This is a part of  wrapper log
`STATUS | wrapper  | 2016/11/01 17:59:22 | Launching a JVM...
INFO   | jvm 1    | 2016/11/01 17:59:24 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/11/01 17:59:29 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/11/01 17:59:30 | Tue Nov 01 17:59:30 NCT 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

And a part of my tracker-server log :
`2016-11-01 17:59:29  INFO: Operating system name: Linux version: 4.4.0-45-generic architecture: amd64
2016-11-01 17:59:29  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.91-b14
2016-11-01 17:59:29  INFO: Memory limit heap: 479mb non-heap: 0mb
2016-11-01 17:59:29  INFO: Character encoding: UTF-8 charset: UTF-8
2016-11-01 17:59:29  INFO: Version: 3.7-SNAPSHOT
2016-11-01 17:59:31  WARN: Table 'traccal.groups' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:245 < DeviceManager:243 < ...)
2016-11-01 17:59:33  WARN: Table 'traccal.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:318 < PermissionsManager:85 < ...)`

show databases     show me the  traccal   database

I don't understand where is my problem.

Thanks.
Igor

**Comment by vitalidze** [comment]
Looks like you haven't disabled the queries to look up groups and devices before the first start. Because of that the traccar web UI mod was unable to create necessary tables. Maybe your mysql user does not have sufficient privileges to create tables in your database.

**Comment by ghost** [comment]
Thanks for having a look, so do I just
- stop traccar
- Disable queries to groups/device
- drop my database
- create  it
- grant all privileges to mysql user ?
- Start traccar
- stop traccar
- Enable queries to groups/devices
- start traccar 
  Do I miss something ?

**Comment by vitalidze** [comment]
Yes, it should work after that.
