### ISSUE TITLE
Feature request: Copying attributes from last position

### ISSUE THREAD

**Issue by gpproton** [vitalidze/traccar-web#933]
Hi @vitalidze i recently created an issue on Traccar back-end repository concerning devices that don't repeatedly send sensor information such as ignition on or of to server, and i was reffered to this issue https://github.com/tananaev/traccar/pull/2467 and https://github.com/tananaev/traccar/issues/2325 which @tananaev said it'll be implemented in the next release of Traccar back-end i'll like to know if it'll be functional with Traccar-web UI mod.

**Comment by vitalidze** [comment]
I think it will be compatible since it will be simply copying some attributes from previously received positions.
