### ISSUE TITLE
From 3.7 + Litvak MOD H2 to Mysql

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#935]
hello,

I've a fully functional traccar3.7 + mod
Now I want to switch from H2 to Mysql (loosing my H2 data is not a problem)

sudo service traccar stop
I create a new mysql database
> create database traccar;

I follow xml modifications as write   https://www.traccar.org/mysql/
replace [HOST], [DATABASE], [USER], [PASSWORD] with appropriate values; for local database use “localhost” as HOST)

sudo service traccar start

But NO WAY to have the webpage (unable to display 127.0.0.1:8082); going back to old config(H2) work.

**Comment by vitalidze** [comment]
What's the difference between this thread and #932?

 Is default version of traccar working with MySQL? I think you should try it and check logs for error messages.
