### ISSUE TITLE
Integration Problem with Traccar Server 3.7

### ISSUE THREAD

**Issue by Sargunan** [vitalidze/traccar-web#939]
Hi,

 I have installed traccar 3.7 in window 7,  I have problem in while deploying WAR (Generated from eclipse) with Traccar 3.7 ,  But WAR file (http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) download is working file with 3.7

RPC error is thrown while login, Please help me to solve this problem

**[qtp12330572-49] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/11/02 15:54:39 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.login(java.lang.String,java.lang.String) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: java.lang.IllegalStateException
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at** com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/11/02 15:54:39 | Caused by: java.lang.IllegalStateException
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:119)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.traccar.web.server.model.MethodCallLogger.invoke(MethodCallLogger.java:43)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:58)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:164)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at **sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/11/02 15:54:39 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)**

Thanks and Regards
Sargunan R

**Comment by vitalidze** [comment]
This means you have entered incorrect username/password pair.

**Comment by Sargunan** [comment]
I think my maven execution is not proper to generate WAR file.  

whenever i  try execute mvnw package (goal) , I am getting error **Please set the M2_HOME variable in your environment to match the location of the Maven installation.**

But I have got successfully installed maven, 
I have checked with mvn --version. It displaying excepted message,
_Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: C:\Program Files\apache-maven-3.3.9
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_102\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8", version: "6.2", arch: "x86", family: "dos"_

**Please help me know how to overcome this error. Thanks**

Note : During last execution to generate WAR To solve i have commented checkMBat,

**Comment by vitalidze** [comment]
I think you don't have apache maven properly installed. The `mvnw` cannot install it for you for some reason, so you need to install it manually before you build the project.

**Comment by Sargunan** [comment]
Thanks for hint,  I will recheck it once again.

Meanwhile, I am positing this error,

FO   | jvm 1    | 2016/11/04 18:03:38 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@73b06b{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/11/04 18:03:38 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @64727ms
**INFO   | jvm 1    | 2016/11/04 18:04:27 | [qtp14136310-55] INFO / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: ERROR: The serialization policy file '/traccar/48ACB3167486C154BB2793684679C460.gwt.rpc' was not found; did you forget to include it in this deployment?**
**INFO   | jvm 1    | 2016/11/04 18:04:27 | [qtp14136310-55] WARN / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: Malformed moduleBaseURL: http://0:0:0:0:0:0:0:1:8082/traccar/
INFO   | jvm 1    | 2016/11/04 18:04:27 | java.net.MalformedURLException: For input string: "0:0:0:0:0:0:1:8082"**
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.net.URL.<init>(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.net.URL.<init>(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.net.URL.<init>(Unknown Source)
**INFO   | jvm 1    | 2016/11/04 18:04:27 |     at com.google.gwt.user.server.rpc.RemoteServiceServlet.loadSerializationPolicy(RemoteServiceServlet.java:60)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.doGetSerializationPolicy(RemoteServiceServlet.java:420)**
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$d76dfcaf.CGLIB$doGetSerializationPolicy$37(<generated>)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$d76dfcaf$$FastClassByGuice$$8fab18cc.invoke(<generated>)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.traccar.web.server.model.FixSerializationPolicy.invoke(FixSerializationPolicy.java:19)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$d76dfcaf.doGetSerializationPolicy(<generated>)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.getSerializationPolicy(RemoteServiceServlet.java:234)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.prepareToRead(ServerSerializationStreamReader.java:505)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:240)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:296)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 | Caused by: java.lang.NumberFormatException: For input string: "0:0:0:0:0:0:1:8082"
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.lang.NumberFormatException.forInputString(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.lang.Integer.parseInt(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.lang.Integer.parseInt(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   at java.net.URLStreamHandler.parseURL(Unknown Source)
INFO   | jvm 1    | 2016/11/04 18:04:27 |   ... 57 more
INFO   | jvm 1    | 2016/11/04 18:04:27 | [qtp14136310-55] INFO / - **Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: ERROR: The module path requested, null, is not in the same web application as this servlet, .  Your module may not be properly configured or your client and server code maybe out of date.
INFO   | jvm 1    | 2016/11/04 18:04:27 | [qtp14136310-55] INFO / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: WARNING: Failed to get the SerializationPolicy '48ACB3167486C154BB2793684679C460' for module 'http://localhost:8082/traccar/'; a legacy, 1.3.3 compatible, serialization policy will be used.  You may experience SerializationExceptions as a result.**

**Comment by vitalidze** [comment]
This means you have either built project incorrectly or haven't cleaned up web browser cache.

**Comment by Sargunan** [comment]
Thank you very much for support
After deleting the web browser cahe, above error is not appearing,
[output.txt](https://github.com/vitalidze/traccar-web/files/571603/output.txt)
I can build project successfully. For more info please find attachment

---

Tests run: 61, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- gwt-maven-plugin:2.7.0:compile (default) @ traccar-web ---
[INFO] org.traccar.web.Traccar is up to date. GWT compilation skipped
[INFO] 
[INFO] --- maven-war-plugin:2.6:war (default-war) @ traccar-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [traccar-web] in [C:\Users\Home\git2\traccar-web\target\traccar-web-0.12.2]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Users\Home\git2\traccar-web\src\main\webapp]
[INFO] Webapp assembled in [4096 msecs]
[INFO] Building war: C:\Users\Home\git2\traccar-web\target\traccar-web-0.12.2.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:55.875s
[INFO] Finished at: Fri Nov 04 18:53:58 IST 2016
[INFO] Final Memory: 23M/247M

---

But when i run now, I am error pop with message **"Couldn't load traccar from Super Dev Mode
server at http://localhost:9876.
Please make sure this server is ready.
Do you want to try again?"**

**Do you think there are stills errors in building ?**

**Comment by vitalidze** [comment]
I think there are either issues with building or you took the wrong traccar-web.war file for deployment.

**Comment by Sargunan** [comment]
Hi,

Problem is resolved by using workaround solution, with help of solution"https://github.com/vitalidze/traccar-web/issues/514".  But Rootcause of solution is not known.
- But It looks if you run the program "SuperDevMode "  and than generated WAR is corrupted.
- Everything its ok, if i try fresh git clone https://github.com/vitalidze/traccar-web.git -> modification -> then build maven (without run gwt super dev mode).

Thanks for your guidelines.
