### ISSUE TITLE
Extended info in mobile version

### ISSUE THREAD

**Issue by Abyss777** [vitalidze/traccar-web#94]
In desktop version I can see extended info of my tracker then I move mouse over device in device list: satellites, battery, inputs etc.
It would be nice to see such information in mobile version in device list.

**Comment by vitalidze** [comment]
Implemented, written [news](http://traccar.litvak.su/2015/02/25/extended-info-in-mobile-UI-and-GPX-export-bugfix.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).
