### ISSUE TITLE
Upgrade from 3.3 to 3.8

### ISSUE THREAD

**Issue by Fleetracking** [vitalidze/traccar-web#953]
Hello
How can i upgrade my traccar server using 3.3 backend with mysql + 3.3 war GUI to latest version 3.7 of both projects without losing data?
BR

**Comment by vitalidze** [comment]
Briefly I would do it this way:

1) Stop current service
2) Back up your MySQL database
3) Uninstall 3.3
4) Install 3.7
5) Set up your MySQL database in config
6) Install the Traccar Web UI Mod by following appropriate instructions: http://traccar.litvak.su/installation.html

It should work fine if you follow the Traccar Web UI Mod instructions precisely. Don't forget to disable database schema updates in traccar config. If you do follow instructions then you should not loose any data and it should just start working with newer version of traccar.

**Comment by Fleetracking** [comment]
Thank you for your answer.
At which step and how to disable database scheme update?
BR

**Comment by vitalidze** [comment]
Database schema updates disabling is a step in installation instructions of the Traccar Web UI Mod: http://traccar.litvak.su/installation.html

**Comment by Fleetracking** [comment]
A new version of backend 3.8 is published today.
Does the procedure stay the same for this new release?

Last strategic question that i have since a long time: why 2 seperated projects (backend & SU GUI)? why dont unify efforts to have one complete project? 
For example Tananaev has investing time and effort to develop some functionnalities (reports, geofence,...) already implemented and works fine in your UI project.

Thank you for your contributions

**Comment by vitalidze** [comment]
> Does the procedure stay the same for this new release?

I don't know. Have to try it myself.

> Last strategic question that i have since a long time: why 2 seperated projects (backend & SU GUI)? why dont unify efforts to have one complete project? 
> For example Tananaev has investing time and effort to develop some functionnalities (reports, geofence,...) already implemented and works fine in your UI project.

We have different visions on how the UI should be developed. Also projects are based on different technologies.

**Comment by Fleetracking** [comment]
Dear Vitalidze
Did you test traccar 3.8 version with traccar-web 3.7 ?
BR

**Comment by vitalidze** [comment]
No, I haven't got a time to test it yet. However, according to this comment https://github.com/vitalidze/traccar-web/issues/958#issuecomment-261745248 it works just fine. You can give it a try, don't forget to backup and just roll back if needed. Then report it here.

**Comment by vitalidze** [comment]
I have just posted installation instructions for 3.8: http://traccar.litvak.su/installation.html
