### ISSUE TITLE
Email notifications up to 10 minutes late

### ISSUE THREAD

**Issue by xewonder** [vitalidze/traccar-web#962]
Version 3.7 

Hi,
 
Sometimes, email notifications are up to 10 minutes late. Looking at the wrapper log and smtp server log they are actually sent 10 minutes late???

Why would that be, and how an I fix it?

I would also like for the system to scan for notifications more often than one minute because we need to notify VERY short term. (in city) How can I do that?

**Comment by vitalidze** [comment]
> Sometimes, email notifications are up to 10 minutes late. Looking at the wrapper log and smtp server log they are actually sent 10 minutes late???

I think this may happen due to high load on your server. Do you see that the sending of notification is after 10 minutes or you receive them with 10 minutes delay?

> I would also like for the system to scan for notifications more often than one minute because we need to notify VERY short term. (in city) How can I do that?

I think that email is not a reliable way to handle such notifications. I would try with pushbullet instead. To send notifications more often than one minute you will need to update the source code and rebuild project.

**Comment by xewonder** [comment]
Hi,

> I think this may happen due to high load on your server. Do you see that the sending of notification is after 10 minutes or you receive them with 10 minutes delay?

The server is not (or should not be) busy at all. We are testing one device. The notifications are sent up to 10 minutes late. This can be seen in the Wrapper log. Someting is not right...

> I think that email is not a reliable way to handle such notifications. I would try with pushbullet instead

We are using an "SMTP to SMS" application on the same server. It works very well if the emails would be sent on time.

> To send notifications more often than one minute you will need to update the source code and rebuild project.

Could you please put me in the right directions? I beleive there are 2 timers. One for data collection and the other for notification sending.

Thank you in advance

**Comment by vitalidze** [comment]
Well, I have no other ideas, except to run a debug session to see what happens.

You are right about two timers:

* https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/EventServiceImpl.java#L454 - this one scans received positions and posts necessary events. There is a time when event was posted. You can check it for debugging.

* https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/server/model/NotificationServiceImpl.java#L344 - this one sends notifications. It just queries for all events with "notification not sent" flag, then looks for recipients and sends notifications with the javamail.

I know that it works quite well and I haven't seen 10 minutes delay.

**Comment by xewonder** [comment]
Hi,
compiling the latest version  + Mysql database seems to have "fixed" the issue. I will post here after a few days of testing.
thank you
