### ISSUE TITLE
devices's icons from your  .apk

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#977]
Hello,

I like so much your .apk  with icons cars that show them turning.

is it possible to have that on the computer ?

Thanks.

**Comment by vitalidze** [comment]
I don't think I understand what do you mean. All icons are available in this repository.

**Comment by waca98** [comment]
I mean, that apk's diplay cars moving, and turning  on live !!!

![cars](https://cloud.githubusercontent.com/assets/15246747/20884054/539b2c0e-bb3d-11e6-9c44-ab28ee65fb8a.jpg)

**Comment by ghost** [comment]
I mean that the apk show cars moving      turning icon on live as the car drive, right, left

![cars](https://cloud.githubusercontent.com/assets/15246747/20884175/d2302e84-bb3d-11e6-9a6d-6efafc9adcb2.png)

**Comment by vitalidze** [comment]
I don't have any relation with this application.
