### ISSUE TITLE
Forward events to another server

### ISSUE THREAD

**Issue by jlms77** [vitalidze/traccar-web#978]
Hi, i'm testing the forward functionality, i manage to capture all the data using the, event.forward.enable and event.forward.url in the xml file. Al the date is going via HTTP post to another server where i am already capturing all the data using the default web interface from traccar.

Is there any way to have similar functionality with your ui?

We are trying to send SMS notifications using an existent SMS gateway so we want to have all the events forwarded for processing on an external server.

Thank you in advance.

**Comment by vitalidze** [comment]
Currently it's not possible and I think is quite complicated because requires redesign of the notification system. You can find some info about this topic here: #153

**Comment by ghost** [comment]
@jlms77 

My system already has notifications to what you are looking for you can check:

187.190.109.14
user: demodemo
pass: demodemo

regars.

**Comment by vitalidze** [comment]
@condeitokako it's not a place for advertising your product. If you post another advertisement you will be banned.
