### ISSUE TITLE
Huge log file

### ISSUE THREAD

**Issue by sankalpask** [vitalidze/traccar-web#980]
Hello,
how can I clear wrapper log file?
there are many server downs happen because of huge wrapper.log files. (some files are bigger than 10gb).

Please help. Thanks

**Comment by vitalidze** [comment]
You can just delete these files. However, it's better to figure out why it becomes so huge. You need to look through messages in log and determine why they are coming. See #826 for additional info.

**Comment by sankalpask** [comment]
Thanks a lot. I'll check this.

**Comment by sankalpask** [comment]
Can I disable log?

**Comment by vitalidze** [comment]
I think you can. See this article: https://wrapper.tanukisoftware.com/doc/german/prop-logfile.html
