### ISSUE TITLE
Can't loggin mobile on http://<ipadres>/m 

### ISSUE THREAD

**Issue by tjeerd13** [vitalidze/traccar-web#981]
When i'm trying to acces with a mobile devicve http://<ipadres>/m i get a black screen this happens on mobile device and on desktop.

When i loged in with an account with the desktop version then http://<ipadres>/m is working. When i press logout i see the login screen and I  can loggin again. When i Refresh the page is black again. And i cant login anymore. Everything is working except the /m login page. 

I entered my Google API key in traccar.html and put it back to traccar-web.war

`
    <script src="//maps.google.com/maps/api/js?key=MyAPIKey&v=3"></script>
 `
Someone with some sugestions?

**Comment by vitalidze** [comment]
You need to check web browser console for error messages when you are getting "black" screen.

**Comment by tjeerd13** [comment]
Problem sometimes exist, looks like a caching problem on mobile devices, After 1 of more refresh the login page appears again, i cant make any sense of it.  Stil getting sometimes balck screen.

**Comment by vitalidze** [comment]
Well, it sounds like an issue with internet connection on your mobile device.

**Comment by tjeerd13** [comment]
Still happens sometimes, Looks like the build in browser with some app's on android. Or an caching problem, sometimes refresh fixes te black screen
