### ISSUE TITLE
filter position in the future

### ISSUE THREAD

**Issue by jolypas** [vitalidze/traccar-web#983]
Hello.
I have erroneous positions from some devices time to time ... in the future 
example : 
2016-12-07 18:20:56  INFO: [9EC1B198] id: xxxxxxxxxx, time: 2054-12-30 01:00:05, lat: 32.57188, lon: -314.38729, speed: 352.0, course: 1256.0

I guess I cannot filter with existing filter ? 

It seems that this is knonw issue from some device and it fixed in the last release (3.8) of the orginal project.
Any chance to have the pach in web ui or an update release based on it ?

https://www.traccar.org/forums/topic/traccar-3-7-odd-position-issue/page/4/#post-9746

Thanks a lot

**Comment by vitalidze** [comment]
I think you can try using Traccar Web UI Mod with 3.8, where this issue is already fixed.

**Comment by jolypas** [comment]
Hi Vitaly

Thanks for the prompt answer.
I'll test on another server I was afraid of compatibilty for the datatables in database (mysql)
I'll keep inform if success

Regards

**Comment by jolypas** [comment]
Hello

I tried but it seems not compatible

I first tried to connect to mysql but it was not working so I restarted from scratch and followed 3.7 installation method

I have following error on each position update

2016-12-08 20:12:49  INFO: [7522EF34] connected
2016-12-08 20:12:49 DEBUG: [7522EF34: 5005 < 37.169.212.161] HEX: 24504749442c3335323737333037313933393635322a30350d0a
2016-12-08 20:13:26 DEBUG: [C9800DF2: 5005 < 37.169.212.161] HEX: 2454524343522c32303136313230383139313235382e3030302c412c34382e39313338393636363636363636372c322e3235323432333333333333333333332c302e302c3335352e34382c38332e322c35322c2a30300d0a
2016-12-08 20:13:26  INFO: [C9800DF2] disconnected
2016-12-08 20:13:26  WARN: NULL not allowed for column "DEVICEID"; SQL statement:
INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); [23502-193] - JdbcSQLException (... < QueryBuilder:443 < DataManager:287 < DefaultDataHandler:27 < ...)
2016-12-08 20:13:26  INFO: [C9800DF2] id: 352773071939652, time: 2016-12-08 20:12:58, lat: 48.91390, lon: 2.25242, speed: 0.0, course: 355.5


some changes in the Database structure between 3.7 & 3.8 ?


regards

**Comment by vitalidze** [comment]
This means you either haven't dropped default database or haven't disabled database schema updates. The column `deviceId` should not be present if you use the Traccar Web UI Mod.

**Comment by jolypas** [comment]
Ok
so I restarted by dropping first the exisiting database , I redo 7a) and 8a) of installation but I have following error

**wrapper.log** 

INFO|7897/0|Service traccar|16-12-08 21:14:04|java.lang.reflect.InvocationTargetException
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|7897/0|Service traccar|16-12-08 21:14:04|Caused by: java.lang.NullPointerException
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:273)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:103)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:80)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.traccar.Context.init(Context.java:235)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  at org.traccar.Main.main(Main.java:35)
INFO|7897/0|Service traccar|16-12-08 21:14:04|  ... 6 more
INFO|wrapper|Service traccar|16-12-08 21:14:04|waitpid 7897 59136
INFO|wrapper|Service traccar|16-12-08 21:14:04|exit code posix process: 59136 application: 0


**Traccer-server.log** 

2016-12-08 21:20:06  INFO: Operating system name: Linux version: 3.19.0-75-generic architecture: amd64
2016-12-08 21:20:06  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.111-b14
2016-12-08 21:20:06  INFO: Memory limit heap: 837mb non-heap: 0mb
2016-12-08 21:20:06  INFO: Character encoding: UTF-8 charset: UTF-8
2016-12-08 21:20:06  INFO: Version: 3.8-SNAPSHOT
2016-12-08 21:20:06  WARN: Table "GROUPS" not found; SQL statement:
SELECT * FROM groups [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:239 < DeviceManager:244 < ...)
2016-12-08 21:20:07  WARN: Table "SERVER" not found; SQL statement:
SELECT * FROM server [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:312 < PermissionsManager:87 < ...)

**Comment by vitalidze** [comment]
I have just posted installation instructions for 3.8 on official installation page: http://traccar.litvak.su/installation.html. Please try following them.

**Comment by jolypas** [comment]
Thanks for update but I got the same result (I restarted from 0)

2016-12-08 21:52:18  WARN: Table "GROUPS" not found; SQL statement:
SELECT * FROM groups [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:239 < DeviceManager:244 < ...)
2016-12-08 21:52:18  WARN: Table "SERVER" not found; SQL statement:
SELECT * FROM server [42102-193] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:312 < PermissionsManager:87 < ...)



INFO|9488/0|Service traccar|16-12-08 21:52:18|[main] INFO org.eclipse.jetty.util.log - Logging initialized @3199ms
INFO|9488/0|Service traccar|16-12-08 21:52:18|java.lang.reflect.InvocationTargetException
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|9488/0|Service traccar|16-12-08 21:52:18|Caused by: java.lang.NullPointerException
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:273)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:103)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:80)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.traccar.Context.init(Context.java:235)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  at org.traccar.Main.main(Main.java:35)
INFO|9488/0|Service traccar|16-12-08 21:52:18|  ... 6 more
INFO|wrapper|Service traccar|16-12-08 21:52:18|waitpid 9488 59136
INFO|wrapper|Service traccar|16-12-08 21:52:18|exit code posix process: 59136 application: 0

**Comment by vitalidze** [comment]
I think you haven't followed these instructions carefully. I did it and it worked just fine on my test environment. The error message that you are getting is coming when you don't have your database correctly initialised.

**Comment by jolypas** [comment]
OK I restarted and It works !!
thanks a lot for this update.

I'm testing on a "test" platform with H2. 
I would like to connect again to mysql on the reference platform and to backup/restore the existing database (which is working with traccar 3.7 and web ui)

 do you think mysqldump and restore of traccar has a chance to work between 3.7 & 3.8 ?

Regards

**Comment by vitalidze** [comment]
> do you think mysqldump and restore of traccar has a chance to work between 3.7 & 3.8 ?

Yes, absolutely. You need to make sure that you have disabled database schema updates on "backend" side.

**Comment by jolypas** [comment]
Ok very good, I'll test it

To be sure what do you mean by 

> disabled database schema updates on "backend" side

Put in comment 
`
`

**Comment by vitalidze** [comment]
Yes, that's right.

**Comment by negamkpk** [comment]
how to diasble database.

**Comment by vitalidze** [comment]
@negamkpk it is present in @jolypas's post and also it is present as a step in installation instructions.

**Comment by jolypas** [comment]
Hello
I tested the method with release 3.9 (just released, I wanted to avoid 2 upgrades on production)  but I got some issue with "maintenance" when receiving datas 
```
2016-12-10 16:47:00  INFO: [B25A2B1E] connected
2016-12-10 16:47:00 DEBUG: [B25A2B1E: 5005 < 37.165.178.7] HEX: 24504749442c3335323737333037313933393635322a30350d0a
2016-12-10 16:47:30 DEBUG: [B25A2B1E: 5005 < 37.165.178.7] HEX: 2454524343522c32303136313231303135343732342e3030302c412c34382e39313437323636363636363636372c322e32353237332c302e302c3137352e30322c36352e332c32332c2a30650d0a
**2016-12-10 16:47:30  WARN: [B25A2B1E] error - NullPointerException (DeviceManager:388 < *:357 < MaintenanceEventHandler:41 < BaseEventHandler:28 < ...)**
2016-12-10 16:47:30  INFO: [B25A2B1E] disconnected
```

**Comment by vitalidze** [comment]
You need to disable all event handlers as said in installation instructions.

**Comment by jolypas** [comment]
OK

adding these 2 lines in traccar.xml make the procedure OK for 3.9

```
<entry key='event.statusHandler'>false</entry>
<entry key='event.maintenanceHandler'>false</entry>
```

**Comment by vitalidze** [comment]
I have just updated installation instructions with those lines. Thank you very much for testing.

**Comment by jolypas** [comment]
Thank you very much to you to be so reactive !

Now it works fine with H2 but I still have issue with mysql in 3.8 & 3.9 on the test env. (not sure it's link to the release and neither with webui)

my configuration is as following
```
<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://localhost:3306/traccarOrig?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>traccar</entry>
<entry key='database.password'>mypasswd</entry>
```

my table database is empty

I have this error in wrapper.log 

`INFO|wrapper|Service traccar|16-12-10 17:10:38|started process with pid 13041
INFO|13041/0|Service traccar|16-12-10 17:10:40|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|13041/0|Service traccar|16-12-10 17:10:41|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO|13041/0|Service traccar|16-12-10 17:10:46|java.lang.reflect.InvocationTargetException
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|13041/0|Service traccar|16-12-10 17:10:46|Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.traccar.database.DataManager.initDatabase(DataManager.java:112)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.traccar.Context.init(Context.java:176)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at org.traccar.Main.main(Main.java:35)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	... 6 more
**INFO|13041/0|Service traccar|16-12-10 17:10:46|Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.**
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.Util.getInstance(Util.java:408)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2163)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2088)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:508)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	... 12 more
INFO|13041/0|Service traccar|16-12-10 17:10:46|Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
INFO|13041/0|Service traccar|16-12-10 17:10:46|
INFO|13041/0|Service traccar|16-12-10 17:10:46|The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	... 26 more
INFO|13041/0|Service traccar|16-12-10 17:10:46|Caused by: java.net.ConnectException: Connection refused (Connection refused)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.PlainSocketImpl.socketConnect(Native Method)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at java.net.Socket.connect(Socket.java:589)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
INFO|13041/0|Service traccar|16-12-10 17:10:46|	... 28 more
INFO|wrapper|Service traccar|16-12-10 17:10:46|waitpid 13041 59136
INFO|wrapper|Service traccar|16-12-10 17:10:46|exit code posix process: 59136 application: 0`


I tested the database connection with a small php script from the same server with the same parameters  (user, password, db name) and it is OK (but I don't see user/passwd issue in the wrapper log)

Any idea (I'm afraid to migrate the production server where mysql is working in 3.7) ?

**Comment by vitalidze** [comment]
According to this log, it just cannot connect to your MySQL server, system reports "connection refused" like no app is listening on that port.

**Comment by jolypas** [comment]
The issue was in the bind_adress of mysql (ip of the server)
putting ip into traccar.xml instead of localhost solved it

now I have the databse mysql and I restored all data from the production one without problem

thanks a lot
