### ISSUE TITLE
NetBeans break-point

### ISSUE THREAD

**Issue by lcatoni72** [vitalidze/traccar-web#984]
I configured the project and following the described instructions and the program starts correctly in super Dev mode. However I can not debug in my NetBeans environment. I tried to set a break point but the execution does not stop at break point selected. (ex. into into DeviceDialog class constructor, when click on editor device or add device)
Can someone help me ?

**Comment by vitalidze** [comment]
I think this article should be helpful: http://www.gwtproject.org/articles/superdevmode.html (see "Debugging" section). Basically, you need to enable source maps and put break points in your web browser (in Chrome for example). If you were using IntelliJ Idea, then it has a special plugin for web browser, which allows you to debug code right in IDE. From my understanding you cannot do that with NetBeans.

**Comment by vitalidze** [comment]
This applies only for the UI (or client) side debugging. You can put break point at any place in the server source code (i.e. in `DataServiceImpl` class) and it will work as expected.
