### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by lcatoni72** [vitalidze/traccar-web#985]
I configured the NetBeans project and following the described instructions and the program starts correctly in super Dev mode. However I can not connect to MySql database. 
I have replaced the following code in my persistence.xml. (debug unit):

```
<persistence-unit name="debug">
    <properties>
      <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver"/>
      <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/traccar"/>
      <property name="hibernate.connection.username" value="root"/>
      <property name="hibernate.connection.password" value="password"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
  </persistence-unit>
```
I receive "failed Try again" message on web browser during loading application. 
What am I doing wrong?
Where can I find the log files ?
Thank you very much

**Comment by vitalidze** [comment]
Your approach is correct. I think something is wrong with your connection settings, maybe username or password. And I think you are using incorrect properties. Also you need to create database in MySQL before running the application.

Here are my settings, which I use for development:

````xml
  <persistence-unit name="debug">
    <properties>
      <property name="javax.persistence.jdbc.driver" value="com.mysql.jdbc.Driver" />
      <property name="javax.persistence.jdbc.url" value="jdbc:mysql://localhost:3306/traccar" />
      <property name="javax.persistence.jdbc.user" value="traccar" />
      <property name="javax.persistence.jdbc.password" value="traccar" />

      <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />
      <property name="hibernate.show_sql" value="true" />
      <property name="hibernate.hbm2ddl.auto" value="update" />
    </properties>
  </persistence-unit>
````

You should see some error messages in your IDE when application is starting up.

**Comment by lcatoni72** [comment]
Ok, now it works. But when I click on "Lunch Default button" on GWT Development Mode Window, Chrome ask me to download GWT plugin:

"Development Mode requires the GWT Developer Plugin"

But clicking on download button I obtain the Google message:

404. That’s an error.

The requested URL was not found on this server. That’s all we know.

What should I do ?
Thanks.

**Comment by vitalidze** [comment]
The `Dev Mode` is outdated and not supported by most modern web browsers. You should user `Super Dev Mode` instead.
