### ISSUE TITLE
Mobile App Frontend

### ISSUE THREAD

**Issue by uppaljs** [vitalidze/traccar-web#99]
Hi,

I see that you're already using framework7 for the mobile front-end - Is there a possibility to decouple it from the actual web-app , so that it can be built into an easy to use app with something like phone gap?

Thanks,

**Comment by vitalidze** [comment]
I think yes, there is such possibility. There are two points here:

1) You will still need running traccar-web in java to provide RESTful API
2) You will need some UI to set up server URL along with the storage logic for such setting

**Comment by uppaljs** [comment]
Hi @vitalidze , Thanks a lot for the response , I understand that the traccar-web would be running for the API , the UI can just be a config page , which stores local values for the server address.

Is this something you're planning to implement? If not , i can talk a try at it , but would need some help.

Thanks,

**Comment by vitalidze** [comment]
I don't have it in plans. From my point of view mobile UI in browser is enough, you can always create a shortcut in iOS/Android right on the dashboard to have a quick access.

Anyway, feel free to ask questions if you intend to implement such app yourself.

**Comment by vitalidze** [comment]
Closed due to inactivity
