### ISSUE TITLE
IP-Adress of Demo-Server?

### ISSUE THREAD

**Issue by bospre** [vitalidze/traccar-web#990]
Hello,
I have two new trackers type TK909. As far as I found out, they cannot configured to use a domain, they only accept an IP-adress.
So it is impossible to use my own traccar-server.
Now I want to use your Demoserver (https://d.traccar.litvak.su/).
But actually I do not know the IP-adress. Is it a fixed adress? And can you please tell me?
Sincerly
Boris

**Comment by vitalidze** [comment]
The IP address is: 188.166.50.6 . Currently it is fixed and hasn't changed for couple of years. But this may change in future.

**Comment by bospre** [comment]
Thank you.
If the IP-adress will change, the tracker has to be reconfigured. That is not a big problem.

But just now, for me it seems the server is down?
Only "loading apllication" appears and nothing more happens.
Boris

**Comment by vitalidze** [comment]
It ran out of disk space (again). Now it is up and running.
