### ISSUE TITLE
TimeServer in mysql +30mins

### ISSUE THREAD

**Issue by halie412** [vitalidze/traccar-web#994]
Hello Friend i have a issue, my installation is saving ServerTime with 30 minutes in the future, i know this because the timeserver is correct but when i see the mysql records i see the difference, i need fix it because i have 2 traccar installations in same mysql database.

This is the trouble:
When server A receibe an position save with correct time and show correct time of this position, but if the position was receibe by server B the server A will show this with 30 mins of delay.

If server B receibe an position save with correct time and show correct time of the position but if this position will show by server A will show this with 30 mins of above.

Note: My trouble is my actual VPS is limited to 1000 TCP connections and i need 2 servers in transition to move the 995 devices on old server (server A) to server B.

**Comment by halie412** [comment]
This was solved... here the solition if can be helpful for someone, i need to force the timezone of Traccar in wrapper.conf with this line in both servers. I find help in traccar project issues:

wrapper.java.additional.1=-Duser.timezone=UTC

**Comment by vitalidze** [comment]
Thank you very much for sharing this.
