### ISSUE TITLE
upgrade to latest web-ui - error

### ISSUE THREAD

**Issue by rozikj** [vitalidze/traccar-web#995]
Hi, 
how do I upgrade  your traccar web-ui to the latest version? I'm using tatanaev traccar 3.5 with your web-ui (version downloaded roughly 07/2016). I tried the following steps.

1. stop the traccar
2. backup the database and the traccar directory
3. Download the latest web-ui from http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war
4. replace the current traccar-web for downloaded
5. start traccar

The traccar probably is running (There is added a new positions record etc. in the server log file) but the web return only red text "Directory: " on white page.

When I stop the traccar, copy the original traccar-web file back and start the traccar, your web-ui is working fine.

Any Ideas?

Is somewhere your versions changelog and features. Since 11 Jul is your news page dead :-(.

Thank you for this project!

**Comment by vitalidze** [comment]
> how do I upgrade your traccar web-ui to the latest version? I'm using tatanaev traccar 3.5 with your web-ui (version downloaded roughly 07/2016). I tried the following steps.

There were no updates since 07/2016.

> The traccar probably is running (There is added a new positions record etc. in the server log file) but the web return only red text "Directory: " on white page.

I think you have some damaged .war file. You should re-download it if needed.

> Is somewhere your versions changelog and features. Since 11 Jul is your news page dead :-(.

Again, there were no updates since then.

**Comment by rozikj** [comment]
Hi,
thank you for your reply.
if there are no changes, then to download the latest .war file isn't need. I hope that the project is developing still and I'm looking forward for new features ;-).

**Comment by vitalidze** [comment]
You can find some info about further development here #971

**Comment by rozikj** [comment]
Sorry to hear you with your time and an other in thread but it good to hear that the project isn't dead. 

Thanks for this project again!
